objects/Account.object
<CustomObject>
    <recordTypes>
        <fullName>Organization</fullName>
        <active>true</active>
        <description>An Account representing an organization</description>
        <label>Organization</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/EOY_Progress__c.object
<CustomObject>
    <description>This object is used to determine the current completion progress in the EOY Wizard.</description>
    <fields>
        <fullName>Setup__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Look up to the setup record, since a setup represents an active configuration for a school.</description>
        <inlineHelpText>Determine the progress for an active setup to a school.</inlineHelpText>
        <label>Setup</label>
        <referenceTo>Setup__c</referenceTo>
        <relationshipLabel>EOY Progresses</relationshipLabel>
        <relationshipName>EOY_Progresses</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Year__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>The year that the EOY Wizard process is for.</description>
        <inlineHelpText>The year for the EOY Wizard to process.</inlineHelpText>
        <label>Year</label>
        <referenceTo>Time_Element__c</referenceTo>
        <relationshipLabel>EOY Progresses</relationshipLabel>
        <relationshipName>EOY_Progresses</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>EOY Progress</label>
    <nameField>
        <label>EOY Save State Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>EOY Progresses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Setup__c.object
<CustomObject>
    <description>This object is used to setup Schoolforce and is referenced in multiple pieces of code.  There should be one setup object per school.</description>
    <fields>
        <fullName>Year__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>School Year associated to the Setup</description>
        <label>Year</label>
        <referenceTo>Time_Element__c</referenceTo>
        <relationshipLabel>Setup (Year)</relationshipLabel>
        <relationshipName>Setup_Year</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Setup</label>
    <nameField>
        <displayFormat>S-{0}</displayFormat>
        <label>Setup ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Setup</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/Time_Element__c.object
<CustomObject>
    <label>Time</label>
    <nameField>
        <displayFormat>T-{000000}</displayFormat>
        <label>Time Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Time</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/CT_Test_SetupWizard_Utils.cls
/**
 * This class contains unit tests for validating the behavior of Apex classes
 * and triggers.
 *
 * Unit tests are class methods that verify whether a particular piece
 * of code is working properly. Unit test methods take no arguments,
 * commit no data to the database, and are flagged with the testMethod
 * keyword in the method definition.
 *
 * All test methods in an organization are executed whenever Apex code is deployed
 * to a production organization to confirm correctness, ensure code
 * coverage, and prevent regressions. All Apex classes are
 * required to have at least 75% code coverage in order to be deployed
 * to a production organization. In addition, all triggers must have some code coverage.
 * 
 * The @isTest class annotation indicates this class only contains test
 * methods. Classes defined with the @isTest annotation do not count against
 * the organization size limit for all Apex scripts.
 *
 * See the Apex Language Reference for more information about Testing and Code Coverage.
 */
@isTest
private class CT_Test_SetupWizard_Utils {

	static testMethod void testQuerySchools() {
		Test.startTest();
			List<Account> schools = CT_SetupWizard_Utils.querySchools();
			system.assertEquals(0,schools.size());
			
			TestDataSetupUtil_v2.setupCoreData(1);
			schools = CT_SetupWizard_Utils.querySchools();
			system.assertEquals(1,schools.size());
		Test.stopTest();
	}
	
	static testMethod void testQueryYears(){
		Test.startTest();
			List<Time_Element__c> years = CT_SetupWizard_Utils.queryYears();
			system.assertEquals(0,years.size());
			
			TestDataSetupUtil_v2.setupCoreData(1);
			years = CT_SetupWizard_Utils.queryYears();
			system.assertEquals(1,years.size());
		Test.stopTest();
	}
	
	static testMethod void testGetSetupById(){
		Test.startTest();
			TestDataSetupUtil_v2.setupCoreData(1);
			Setup__c setup = CT_SetupWizard_Utils.getSetupById(TestDataSetupUtil_v2.activeSetup.id);
			system.assertEquals(TestDataSetupUtil_v2.activeSetup.id,setup.id);
		Test.stopTest();
	}
	
	static testMethod void testGetEOYProgressRecord(){
		Test.startTest();
			TestDataSetupUtil_v2.setupCoreData(1);
			EOY_Progress__c progress = CT_SetupWizard_Utils.getEOYProgressRecord(TestDataSetupUtil_v2.activeSetup);
			system.assertEquals(null,progress.id);
			system.assertEquals(TestDataSetupUtil_v2.activeSetup.id,progress.Setup__c);
			system.assertEquals(TestDataSetupUtil_v2.activeSetup.Year__c,progress.Year__c);
			system.assertEquals(CT_SetupWizard_Utils.SW_RECORD_TYPE,progress.RecordTypeId);
			
			insert progress;
			EOY_Progress__c newProgress = CT_SetupWizard_Utils.getEOYProgressRecord(TestDataSetupUtil_v2.activeSetup);
			system.assertEquals(progress.id,newProgress.id);
			
		Test.stopTest();
	}
}