objects/Account.object
<CustomObject>
    <recordTypes>
        <fullName>School</fullName>
        <active>true</active>
        <description>This record type is for physical school locations.</description>
        <label>School</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Grade__c.object
<CustomObject>
    <fields>
        <fullName>Student__c</fullName>
        <label>Student</label>
        <referenceTo>Student__c</referenceTo>
        <relationshipLabel>Grades</relationshipLabel>
        <relationshipName>Grades</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Grade</label>
    <nameField>
        <displayFormat>G-{0}</displayFormat>
        <label>Grade Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Grades</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Indicator_Area__c.object
<CustomObject>
    <description>This object is part of the Interventions app. Indicator Area defines a high-level intervention focus area (e.g., Behavior, Attendance, English Language Arts). Students are assigned to Indicator Areas in order to schedule them in Intervention Programs and Sections.</description>
    <label>Indicator Area</label>
    <nameField>
        <label>Indicator Area</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Indicator Areas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Indicator_Area_Student__c.object
<CustomObject>
    <description>The Indicator Area/Student object is a joiner object that associates an Indicator Area and a Student.</description>
    <fields>
        <fullName>Indicator_Area__c</fullName>
        <inlineHelpText>This field joins the Indicator Area/Student record to the correct Indicator Area</inlineHelpText>
        <label>Indicator Area</label>
        <referenceTo>Indicator_Area__c</referenceTo>
        <relationshipLabel>Indicator Area/Student</relationshipLabel>
        <relationshipName>Indicator_Area_Student</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Student__c</fullName>
        <inlineHelpText>This field joins the Indicator Area/Student record to the correct Student</inlineHelpText>
        <label>Student</label>
        <referenceTo>Student__c</referenceTo>
        <relationshipLabel>Indicator Area/Student</relationshipLabel>
        <relationshipName>Indicator_Area_Student</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Indicator Area/Student</label>
    <nameField>
        <displayFormat>IA/S -{000}</displayFormat>
        <label>IA/Student ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Indicator Area/Student</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Student__c.object
<CustomObject>
    <fields>
        <fullName>Grade__c</fullName>
        <inlineHelpText>Displays the student&apos;s current grade level.</inlineHelpText>
        <label>Grade</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>PS</fullName>
                </value>
                <value>
                    <fullName>PK</fullName>
                    <color>#78C953</color>
                    <label>PK</label>
                </value>
                <value>
                    <fullName>K</fullName>
                </value>
                <value>
                    <fullName>1</fullName>
                    <color>#A845DC</color>
                    <label>1</label>
                </value>
                <value>
                    <fullName>2</fullName>
                    <color>#F3D904</color>
                    <label>2</label>
                </value>
                <value>
                    <fullName>3</fullName>
                    <color>#A53711</color>
                    <label>3</label>
                </value>
                <value>
                    <fullName>4</fullName>
                    <color>#66E9BD</color>
                    <label>4</label>
                </value>
                <value>
                    <fullName>5</fullName>
                    <color>#0B24BE</color>
                    <label>5</label>
                </value>
                <value>
                    <fullName>6</fullName>
                    <color>#419249</color>
                    <label>6</label>
                </value>
                <value>
                    <fullName>7</fullName>
                    <color>#B6E32E</color>
                    <label>7</label>
                </value>
                <value>
                    <fullName>8</fullName>
                    <color>#641CCF</color>
                    <label>8</label>
                </value>
                <value>
                    <fullName>9</fullName>
                    <color>#F96FB7</color>
                    <label>9</label>
                </value>
                <value>
                    <fullName>10</fullName>
                    <color>#2F5D85</color>
                    <label>10</label>
                </value>
                <value>
                    <fullName>11</fullName>
                    <color>#AFCADF</color>
                    <label>11</label>
                </value>
                <value>
                    <fullName>12</fullName>
                    <color>#8F6429</color>
                    <label>12</label>
                </value>
                <value>
                    <fullName>UN Ungraded</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Student_Last_Name__c</fullName>
        <inlineHelpText>Displays the student&apos;s last name.</inlineHelpText>
        <label>Student Last Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Student__c</fullName>
        <inlineHelpText>Displays the student&apos;s middle name.</inlineHelpText>
        <label>Student Middle Name</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <label>Student</label>
    <nameField>
        <label>Student Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Students</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/Test_IndicatorAreasController.cls
@isTest
private class Test_IndicatorAreasController {
	private static List<Student__c> students;
	private static Account school;
	private static IndicatorAreasController  iac;

	static void setupData(){
		TestDataUtil.setupTime();
		school = TestDataUtil.createSchool('ApexTest School');
		insert school;
		TestDataUtil.schoolList.add(school);
		TestDataUtil.setupSetupRecord();
		students = TestDataUtil.createStudents(10, school);
		insert students;

		List<Indicator_Area__c> ia = TestDataUtil.createIndicatorAreas();
		insert ia;
	}

	static void initialize(){
		iac = new IndicatorAreasController();
		iac.SchoolFilterParam = school.id;
		iac.changeSchool();
	}


	static testMethod void testConstructor() {
		Test.startTest();
			iac = new IndicatorAreasController();
			system.assert(!iac.hasUnsavedChanges);
			system.assertEquals(0,iac.sites.size());
			system.assertEquals(0,iac.schools.size());
			system.assertEquals(0,iac.areas.size());

			setupData();
			iac = new IndicatorAreasController();
			system.assertEquals(1,iac.sites.size());
			system.assertEquals(1,iac.schools.size());
			system.assertEquals(4,iac.areas.size());
		Test.stopTest();
	}

	static testMethod void testFilterSchools() {
		setupData();
		Test.startTest();
			initialize();
			system.assertEquals(students.size(),iac.studentsFiltered.size());
		Test.stopTest();
	}

	static testMethod void testFilterGrades() {
		setupData();
		for(integer i=0; i<5; i++) students[i].Grade__c = '4';
		update students;

		Test.startTest();
			initialize();

			iac.selectedGrade = '4';
			iac.filterGrades();
			system.assertEquals(5,iac.StudentsFiltered.size());
			iac.selectedGrade = 'all';
			iac.filterGrades();
			system.assertEquals(students.size(),iac.StudentsFiltered.size());
			iac.selectedGrade = '8';
			iac.filterGrades();
			system.assertEquals('There are no students available using your filters. Please check your filters.',ApexPages.getMessages()[0].getSummary());
		Test.stopTest();
	}

	static testMethod void testLoadGradeLevels() {
		setupData();
		for(integer i=0; i<5; i++) students[i].Grade__c = '4';
		update students;

		Test.startTest();
			initialize();

			iac.loadGradeLevels(new Set<String>{'4','5'});
			system.assertEquals(3,iac.gradeLevels.size());
			iac.loadGradeLevels(new Set<String>{'4','5','notagrade'});
			system.assertEquals(3,iac.gradeLevels.size());
		Test.stopTest();
	}

	static testMethod void testSelectStudent() {
		setupData();
		Test.startTest();
			initialize();

			iac.selectStudent();
			system.assertEquals('No students selected.',ApexPages.getMessages()[0].getSummary());

			iac.selectStudentParam = students[0].id;
			iac.selectStudent();
			system.assertEquals(1,iac.selected.size());

			iac.selectStudentParam = students[0].id+';'+students[1].id;
			iac.selectStudent();
			system.assertEquals(2,iac.selected.size());
		Test.stopTest();
	}

	static testMethod void testAddPrep() {
		setupData();
		Test.startTest();
			initialize();

			iac.selectStudentParam='';
			for(Student__c stud: students){
				if(iac.selectStudentParam!='') iac.selectStudentParam+=';';
				iac.selectStudentParam+=stud.id;
			}
			iac.selectStudent();

//			iac.addPrep();
//			String prevName = '';
//			for(IndicatorAreasController.StudentWrapper stud: iac.addTo.values()){
//				if(prevName!='') system.assert(prevName<=stud.student.Student_Last_Name__c);
//				prevName = stud.student.Student_Last_Name__c;
//			}
		Test.stopTest();
	}

	static testMethod void testResetPage() {
		setupData();
		Test.startTest();
			initialize();

			PageReference pr = iac.resetPage();
			system.assert(pr.getURL().contains('IM_Indicator_Areas'));
		Test.stopTest();
	}

	static testMethod void testGetIAList() {
		setupData();
		Test.startTest();
			iac = new IndicatorAreasController();
			List<SelectOption> areas = iac.getIAList();
			system.assertEquals(4,iac.areas.size());
		Test.stopTest();
	}

	static testMethod void testUpdateStudents() {
		setupData();
		Test.startTest();
			initialize();
			iac.selectStudentParam = students[0].id+';'+students[1].id;
			iac.selectStudent();
//			iac.addPrep();

			Indicator_Area__c ia = [SELECT id FROM Indicator_Area__c limit 1];
            List<id> newlist = new List<id>();
            newlist.add(ia.id);
			//verify no IA/S already exist
			system.assertEquals(null,iac.StudentWrapperMap.get(students[0].id).areaIds.get(ia.id));
			system.assertEquals(null,iac.StudentWrapperMap.get(students[1].id).areaIds.get(ia.id));

			iac.activeIAId = newlist;
			iac.updateStudents();
			system.assertNotEquals(null,iac.StudentWrapperMap.get(students[0].id).areaIds.get(ia.id));
			system.assertNotEquals(null,iac.StudentWrapperMap.get(students[1].id).areaIds.get(ia.id));
			system.assert(iac.hasUnsavedChanges);
			//should not be committed to database
			List<Indicator_Area_Student__c> ias = [SELECT id FROM Indicator_Area_Student__c];
			system.assertEquals(0,ias.size());
		Test.stopTest();
	}

	static testMethod void testSaveChanges() {
		setupData();
		Test.startTest();
			initialize();
			iac.selectStudentParam = students[0].id+';'+students[1].id;
			iac.selectStudent();
//			iac.addPrep();

			Indicator_Area__c ia = [SELECT id FROM Indicator_Area__c limit 1];
            List<id> arealist = new List<id>();
            arealist.add(ia.id);
			iac.activeIAId = arealist;
			iac.updateStudents();
			iac.saveChanges();
			//saving commits changes to database, so they should be query-able now
			List<Indicator_Area_Student__c> ias = [SELECT id FROM Indicator_Area_Student__c];
			system.assertEquals(0,ias.size());
		Test.stopTest();
	}
	
}