objects/Account.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <label>Active</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>No</fullName>
                </value>
                <value>
                    <fullName>Yes</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Reference_Id__c</fullName>
        <externalId>true</externalId>
        <label>Reference Id</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Site__c</fullName>
        <label>Location</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Baton Rouge</fullName>
                </value>
                <value>
                    <fullName>Boston</fullName>
                </value>
                <value>
                    <fullName>Buffalo</fullName>
                </value>
                <value>
                    <fullName>Chicago</fullName>
                </value>
                <value>
                    <fullName>City Year</fullName>
                </value>
                <value>
                    <fullName>Cleveland</fullName>
                </value>
                <value>
                    <fullName>Columbia</fullName>
                </value>
                <value>
                    <fullName>Columbus</fullName>
                </value>
                <value>
                    <fullName>Dallas</fullName>
                </value>
                <value>
                    <fullName>Denver</fullName>
                </value>
                <value>
                    <fullName>Detroit</fullName>
                </value>
                <value>
                    <fullName>Jacksonville</fullName>
                </value>
                <value>
                    <fullName>Kansas City</fullName>
                </value>
                <value>
                    <fullName>Little Rock</fullName>
                </value>
                <value>
                    <fullName>Los Angeles</fullName>
                </value>
                <value>
                    <fullName>Memphis</fullName>
                </value>
                <value>
                    <fullName>Miami</fullName>
                </value>
                <value>
                    <fullName>Milwaukee</fullName>
                </value>
                <value>
                    <fullName>New Hampshire</fullName>
                </value>
                <value>
                    <fullName>New Orleans</fullName>
                </value>
                <value>
                    <fullName>New York City</fullName>
                </value>
                <value>
                    <fullName>Orlando</fullName>
                </value>
                <value>
                    <fullName>Philadelphia</fullName>
                </value>
                <value>
                    <fullName>Providence</fullName>
                </value>
                <value>
                    <fullName>Rhode Island</fullName>
                </value>
                <value>
                    <fullName>Sacramento</fullName>
                </value>
                <value>
                    <fullName>San Antonio</fullName>
                </value>
                <value>
                    <fullName>San Jose/Silicon Valley</fullName>
                </value>
                <value>
                    <fullName>Seattle/King County</fullName>
                </value>
                <value>
                    <fullName>Tulsa</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <recordTypes>
        <fullName>Individuals</fullName>
        <active>true</active>
        <label>Individuals</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Account_Program__c.object
<CustomObject>
    <description>The Account/Program object is part of the Interventions App and links Programs and Schools/Accounts.  This linking occurs in the Interventions Setup when a school selects which interventions Programs they will enroll in for a specific year.  This object tracks the relationships of Programs and Schools and whether the Programs are active.</description>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Is this Program active for this School in this year?</inlineHelpText>
        <label>Active?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Reference_ID__c</fullName>
        <externalId>true</externalId>
        <inlineHelpText>This ID is used to prevent duplicate Account/Program records. It should not be changed.</inlineHelpText>
        <label>Reference ID</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <label>Account/Program</label>
    <nameField>
        <label>School Program Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Accounts/Programs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>true</defaultValue>
        <inlineHelpText>Schools/organizations can choose to use this field when a Contact record is active. When Contact records are created through SchoolForce Setup, this check box is selected.</inlineHelpText>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Reference_Id__c</fullName>
        <description>To store Student/Parent Id as External Id</description>
        <externalId>true</externalId>
        <inlineHelpText>Displays the unique reference ID for the student.  This value should be the same as the Student Id on the associated Student record(s).</inlineHelpText>
        <label>Reference Id</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <recordTypes>
        <fullName>Staff</fullName>
        <active>true</active>
        <description>This record type is for staff members.</description>
        <label>Staff</label>
    </recordTypes>
    <recordTypes>
        <fullName>Student</fullName>
        <active>true</active>
        <description>This record type is for students</description>
        <label>Student</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Indicator_Area__c.object
<CustomObject>
    <description>This object is part of the Interventions app. Indicator Area defines a high-level intervention focus area (e.g., Behavior, Attendance, English Language Arts). Students are assigned to Indicator Areas in order to schedule them in Intervention Programs and Sections.</description>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>true</defaultValue>
        <inlineHelpText>Indicates whether or not this indicator area is available to assign to students on the Add Students to Indicator Areas screen. If you uncheck this field, SchoolForce deactivates any associated Program, Staff/Section, and Student/Section records.</inlineHelpText>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <label>Indicator Area</label>
    <nameField>
        <label>Indicator Area</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Indicator Areas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Program__c.object
<CustomObject>
    <description>Program is an Intervention object. Intervention Programs are aligned with Indicator Areas and are a high level set of activities with defined dosage goals. Each Program has its own frequency, target dosage, and recommended time per session. An example Program is one-on-one reading.</description>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>If this box is checked then the Program is currently available for use.</inlineHelpText>
        <label>Active?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Indicator_Area__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>You must select an Indicator Area that aligns with this Program.</inlineHelpText>
        <label>Indicator Area</label>
        <referenceTo>Indicator_Area__c</referenceTo>
        <relationshipLabel>Programs</relationshipLabel>
        <relationshipName>Programs</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Program</label>
    <nameField>
        <label>Program Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/Section__c.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Check this box if the section is a currently active section</description>
        <inlineHelpText>Check this box if the section is a currently active section</inlineHelpText>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Reference_Id__c</fullName>
        <externalId>true</externalId>
        <label>Reference Id</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Section__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Recursive lookup for groups</description>
        <label>Section</label>
        <referenceTo>Section__c</referenceTo>
        <relationshipLabel>Groups in Section</relationshipLabel>
        <relationshipName>Sections1</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Section</label>
    <nameField>
        <label>Section Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sections</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Skill__c.object
<CustomObject>
    <fields>
        <fullName>Category__c</fullName>
        <label>Category</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Literacy</fullName>
                </value>
                <value>
                    <fullName>Math</fullName>
                </value>
                <value>
                    <fullName>SEL/Behavior and Attendance Interventions</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Skill</label>
    <nameField>
        <label>Skill Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Skills</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Staff__c.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Reference_Id__c</fullName>
        <externalId>true</externalId>
        <label>Reference Id</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Site__c</fullName>
        <formula>TEXT(Organization__r.Site__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Location</label>
        <type>Text</type>
    </fields>
    <label>Staff</label>
    <nameField>
        <label>Staff Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Staff</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/User.object
<CustomObject>
    <fields>
        <fullName>Reference_Id__c</fullName>
        <externalId>true</externalId>
        <label>Reference Id</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Site__c</fullName>
        <label>Location</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Baton Rouge</fullName>
                </value>
                <value>
                    <fullName>Boston</fullName>
                </value>
                <value>
                    <fullName>Buffalo</fullName>
                </value>
                <value>
                    <fullName>Chicago</fullName>
                </value>
                <value>
                    <fullName>Cleveland</fullName>
                </value>
                <value>
                    <fullName>Columbia</fullName>
                </value>
                <value>
                    <fullName>Columbus</fullName>
                </value>
                <value>
                    <fullName>Dallas</fullName>
                </value>
                <value>
                    <fullName>Denver</fullName>
                </value>
                <value>
                    <fullName>Detroit</fullName>
                </value>
                <value>
                    <fullName>Headquarters</fullName>
                </value>
                <value>
                    <fullName>Jacksonville</fullName>
                </value>
                <value>
                    <fullName>Kansas City</fullName>
                </value>
                <value>
                    <fullName>Little Rock</fullName>
                </value>
                <value>
                    <fullName>Los Angeles</fullName>
                </value>
                <value>
                    <fullName>Memphis</fullName>
                </value>
                <value>
                    <fullName>Miami</fullName>
                </value>
                <value>
                    <fullName>Milwaukee</fullName>
                </value>
                <value>
                    <fullName>New Hampshire</fullName>
                </value>
                <value>
                    <fullName>New Orleans</fullName>
                </value>
                <value>
                    <fullName>New York City</fullName>
                </value>
                <value>
                    <fullName>Orlando</fullName>
                </value>
                <value>
                    <fullName>Philadelphia</fullName>
                </value>
                <value>
                    <fullName>Providence</fullName>
                </value>
                <value>
                    <fullName>Sacramento</fullName>
                </value>
                <value>
                    <fullName>San Antonio</fullName>
                </value>
                <value>
                    <fullName>San Jose/Silicon Valley</fullName>
                </value>
                <value>
                    <fullName>Seattle/King County</fullName>
                </value>
                <value>
                    <fullName>Tulsa</fullName>
                </value>
                <value>
                    <fullName>Washington, D.C.</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

classes/TestctlAddTimeFlow.cls
/**
  Due to the complexity of the data model, it is very difficult to set up all test data within the test itself.
	Therefore, this unit test, hence the deployment of this change set, depends on test data being set up before deployment.
  Test data includes:
	1. Test user, with an Alias 'AdamV'
	2. Test staff, pointing to the user.
	3. Test sections (3), assigned to the test staff
	4. Test students, assigned to the section
	5. Each test section needs to have at least a student assigned.
*/
@isTest
public class TestctlAddTimeFlow {
	public static Account individualsAccount;
	public static User u;
	public static Contact c;

	public static void createCommunityUser(){
		ID indivudalsRTID = CYUtil.getRecordTypeID('Individuals');
		individualsAccount = new Account(Name = 'Individuals', RecordTypeID = indivudalsRTID);
		insert individualsAccount;

		ID corpsCommunityProfileID = [select id from Profile where Name = 'Corps Members Community - Customer License'][0].ID;
		ID staffContactRTID = CYUtil.getRecordTypeID('Staff');

		c = new Contact(
			RecordTypeID = staffContactRTID,
			FirstName = 'Test',
			LastName = 'Staff',
			Reference_ID__c = '12345',
			Active__c = true,
			AccountID = individualsAccount.ID
		);
		insert c;

		u = new User(
			ContactID = c.ID,
			FirstName = 'Test',
			LastName = 'Staff',
			Alias = 'tstaff',
			Username = 'tstaff@test.com',
			Email = 'tstaff@test.com',
			CommunityNickname = 'tstaff',
			TimeZoneSidKey='America/New_York',
			LocaleSidKey = 'en_US',
			EmailEncodingKey = 'UTF-8' ,
			ProfileId = corpsCommunityProfileID,
			LanguageLocaleKey='en_US',
			Site__c = 'Washington, DC',
			IsActive = true
		);
		insert u;
	}

	public static testMethod void testPositiveMyController() {
		List<Section__c> mysections;
		PageReference pageRefSection = Page.pageSectionList;
		Test.setCurrentPage(pageRefSection);

		Skill__c skill = new Skill__c();
		skill.Name = 'Self-Awareness: Identifying strengths and weaknesses';
		skill.Category__c = 'SEL/Behavior and Attendance Interventions';
		insert skill;

		TestDataUtil.setupSharingControls();
		TestDataUtil.setupData(1);
		List<Indicator_Area__c> ia = TestDataUtil.createIndicatorAreas();
		List<Program__c> programs = TestDataUtil.createPrograms(1,true,ia[0]);
		programs.addAll(TestDataUtil.createPrograms(1,true,ia[1]));
		programs.addAll(TestDataUtil.createPrograms(1,false,ia[2]));
		programs.addAll(TestDataUtil.createPrograms(1,false,ia[3]));
		insert programs;
		Account_Program__c accProg = TestDataUtil.createAccountProgram(TestDataUtil.schoolList[0], programs[0]);
		insert accProg;
		TestDataUtil.createIAStudents(TestDataUtil.testDataMap.values()[0].students, ia[0].Id);

		createCommunityUser();
		c.User__c = u.ID;
		update c;

		Staff__c staff = TestDataUtil.createStaff(c,TestDataUtil.schoolList[0],1);
		insert staff;
		Section__c section = TestDataUtil.createSection(TestDataUtil.schoolList[0], accProg, TestDataUtil.testDataMap.values()[0].students, staff, programs[0]);

		Test.startTest();
		System.RunAs(u){
			ctlAddTimeFlow controller = new ctlAddTimeFlow();
			mysections = controller.getSecList();
			system.assertEquals(1,mysections.size());
			controller.getPageNumber();
			controller.getTotal_size();
			controller.getTotalPages();
			controller.getprev();
			controller.getnxt();
			controller.Beginning();
			controller.Previous();
			controller.Next();
			controller.End();

			System.debug('Mysection 1:' + mysections[0].Id + mysections[0].Name);
			controller.sectionID=mysections[0].Id;
			PageReference pageRefSectionStudents = controller.doSectionStudents();
			List<ctlAddTimeFlow.StudentWrapper> mystudents = new List<ctlAddTimeFlow.StudentWrapper>();

			PageReference pageRefSectionStudentsCancel = controller.doStudentsCancel();
			System.assertEquals('/apex/pagesectionlist', pageRefSectionStudentsCancel.getURL());

			controller.studentsInSection.get(0).selected = true;
			mystudents = controller.studentsInSection;
			Decimal val = mystudents[0].stuSecRec.Dosage_to_Date__c;
			System.assertEquals('/apex/pagesectionstudents', pageRefSectionStudents.getURL());
			System.debug('Student Name 1:' + mystudents[0].selected + mystudents[0].stuSecRec.Student_Name__c);
			PageReference pageRefAddTime = controller.doStudentsAddTime();
			System.assertEquals('/apex/pageaddtime', pageRefAddTime.getURL());

			controller.currentSession.Date__c = Date.today();
			controller.currentSession.Section__c = mysections[0].Id;
			controller.currentSession.All_avenues__c = 'In-Person Service';
			controller.sessionDosage = 10;

			PageReference pageRefAddStudent = controller.doAddStudentToSession();
			System.assertEquals('/apex/pagesectionstudents', pageRefAddStudent.getURL());

			pageRefAddTime = controller.doStudentsAddTime();
			System.assertEquals('/apex/pageaddtime', pageRefAddTime.getURL());

			controller.selectedFields.addAll(controller.avaliableFields);
			for(Intervention_Session_Result__c isr:controller.studentsInSession){
				isr.Amount_of_Time__c = 10;
			}

			PageReference pageRefSectionStudents1 = controller.doSessionSubmit();
			//System.assertEquals('/apex/pageaddtime', pageRefSectionStudents1.getURL());
		  //  System.assertEquals(val + 10,mystudents[0].stuSecRec.Dosage_to_Date__c);


			PageReference pageRefAddStudentToSession = controller.doAddStudentToSession();
			System.assertEquals('/apex/pagesectionstudents', pageRefAddStudentToSession.getURL());


			PageReference pageSessionList = controller.doShowSessions();
			System.assertEquals('/apex/pagesessionlist', pageSessionList.getURL());

			PageReference pageSessionListCancel = controller.doSessionListCancel();
			System.assertEquals('/apex/pagesectionstudents', pageSessionListCancel.getURL());

			PageReference pageSessionCancel = controller.doSessionCancel();
			System.assertEquals('/apex/pagesectionstudents', pageSessionCancel.getURL());

			controller.getPageNumber();
			controller.getTotal_size();
			controller.getTotalPages();
			controller.getprev();
			controller.getnxt();
			controller.Next();
			controller.End();
			controller.Previous();
			controller.Beginning();
			
			/*
			List<SessionList> mysessions;
			mysessions=controller.getSessionList();
			system.assertEquals(1, mysessions.size());
			controller.updateSessionID=mysessions[0].Id;

			PageReference pageRefAddTime1 = controller.doUpdateSession();
			System.assertEquals('/apex/pageaddtime', pageRefAddTime1.getURL());

			controller.sessionDosage = 20;

			PageReference pageRefSectionStudents2 = controller.doSessionSubmit();
			System.assertEquals('/apex/pagesectionstudents', pageRefSectionStudents2.getURL());
			*/
		}//System.RunAs
		Test.stopTest();
	}

	static testMethod void testNegativeMyController() {
		List<Section__c> mysections;
		PageReference pageRefSection = Page.pageSectionList;
		Test.setCurrentPage(pageRefSection);

		Skill__c skill = new Skill__c();
		skill.Name = 'Self-Awareness: Identifying strengths and weaknesses';
		skill.Category__c = 'SEL/Behavior and Attendance Interventions';
		insert skill;

		TestDataUtil.setupSharingControls();
		TestDataUtil.setupData(1);
		List<Indicator_Area__c> ia = TestDataUtil.createIndicatorAreas();
		List<Program__c> programs = TestDataUtil.createPrograms(1,true,ia[0]);
		programs.addAll(TestDataUtil.createPrograms(1,true,ia[1]));
		programs.addAll(TestDataUtil.createPrograms(1,false,ia[2]));
		programs.addAll(TestDataUtil.createPrograms(1,false,ia[3]));
		insert programs;
		Account_Program__c accProg = TestDataUtil.createAccountProgram(TestDataUtil.schoolList[0], programs[0]);
		insert accProg;
		TestDataUtil.createIAStudents(TestDataUtil.testDataMap.values()[0].students, ia[0].Id);

		createCommunityUser();
		c.User__c = u.ID;
		update c;

		Staff__c staff = TestDataUtil.createStaff(c,TestDataUtil.schoolList[0],1);
		insert staff;
		Section__c section = TestDataUtil.createSection(TestDataUtil.schoolList[0], accProg, TestDataUtil.testDataMap.values()[0].students, staff, programs[0]);

		Test.startTest();

		System.RunAs(u){
		ctlAddTimeFlow controller = new ctlAddTimeFlow();
		mysections = controller.getSecList();
		controller.getPageNumber();
		controller.getTotal_size();
		controller.getTotalPages();
		controller.getprev();
		controller.getnxt();
		controller.Beginning();
		controller.Previous();
		controller.Next();
		controller.End();

		System.debug('Mysection 1:' + mysections[0].Id + mysections[0].Name);
		controller.sectionID=mysections[0].Id;
		PageReference pageRefSectionStudents = controller.doSectionStudents();
		List<ctlAddTimeFlow.StudentWrapper> mystudents = new List<ctlAddTimeFlow.StudentWrapper>();

		PageReference pageRefSectionStudentsCancel = controller.doStudentsCancel();
		System.assertEquals('/apex/pagesectionlist', pageRefSectionStudentsCancel.getURL());

		//Negative Test Case
		controller.studentsInSection.get(0).selected = true;
		mystudents = controller.studentsInSection;

		PageReference pageRefAddTime = controller.doStudentsAddTime();
		controller.currentSession.Date__c = Date.Today().addDays(1);
		controller.currentSession.Section__c = mysections[0].Id ;
		controller.sessionDosage = 10;
		try{
		  PageReference pageRefSectionStudents1 = controller.doSessionSubmit();
		}catch (DmlException e) {
		  System.assert( e.getMessage().contains('Date should be within current Fiscal Year'),e.getMessage());

		}
	 }
	 Test.stopTest();
	}

	public static testMethod void testIDConversion(){
		String shortID = '005c0000001ASda';
		String longID= '005c0000001ASdaAAG';

		System.assertEquals(shortID, ctlAddTimeFlow.convert18To15ID(longID));
		System.assertEquals(longID, ctlAddTimeFlow.convert15To18ID(shortID));
	}
}