objects/Account.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <label>Active</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>No</fullName>
                </value>
                <value>
                    <fullName>Yes</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <recordTypes>
        <fullName>School</fullName>
        <active>true</active>
        <description>This record type is for physical school locations.</description>
        <label>School</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Account_Program__c.object
<CustomObject>
    <description>The Account/Program object is part of the Interventions App and links Programs and Schools/Accounts.  This linking occurs in the Interventions Setup when a school selects which interventions Programs they will enroll in for a specific year.  This object tracks the relationships of Programs and Schools and whether the Programs are active.</description>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Is this Program active for this School in this year?</inlineHelpText>
        <label>Active?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Current_Year_ID__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>The year that this record is (was) active for</inlineHelpText>
        <label>Current Year ID</label>
        <referenceTo>Time_Element__c</referenceTo>
        <relationshipLabel>Accounts/Programs</relationshipLabel>
        <relationshipName>Accounts_Programs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Program__c</fullName>
        <inlineHelpText>This field joins the Account/Program record to the correct intervention Program</inlineHelpText>
        <label>Program</label>
        <referenceTo>Program__c</referenceTo>
        <relationshipLabel>School Programs</relationshipLabel>
        <relationshipName>Accounts_Programs</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>School__c</fullName>
        <inlineHelpText>This field joins the Account/Program record to the correct School.</inlineHelpText>
        <label>School</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Accounts/Programs</relationshipLabel>
        <relationshipName>Accounts_Programs</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Account/Program</label>
    <nameField>
        <label>School Program Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Accounts/Programs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>true</defaultValue>
        <inlineHelpText>Schools/organizations can choose to use this field when a Contact record is active. When Contact records are created through SchoolForce Setup, this check box is selected.</inlineHelpText>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <recordTypes>
        <fullName>Staff</fullName>
        <active>true</active>
        <description>This record type is for staff members.</description>
        <label>Staff</label>
    </recordTypes>
    <recordTypes>
        <fullName>Student</fullName>
        <active>true</active>
        <description>This record type is for students</description>
        <label>Student</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Indicator_Area__c.object
<CustomObject>
    <description>This object is part of the Interventions app. Indicator Area defines a high-level intervention focus area (e.g., Behavior, Attendance, English Language Arts). Students are assigned to Indicator Areas in order to schedule them in Intervention Programs and Sections.</description>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>true</defaultValue>
        <inlineHelpText>Indicates whether or not this indicator area is available to assign to students on the Add Students to Indicator Areas screen. If you uncheck this field, SchoolForce deactivates any associated Program, Staff/Section, and Student/Section records.</inlineHelpText>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <label>Indicator Area</label>
    <nameField>
        <label>Indicator Area</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Indicator Areas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Indicator_Area_Student__c.object
<CustomObject>
    <description>The Indicator Area/Student object is a joiner object that associates an Indicator Area and a Student.</description>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>true</defaultValue>
        <inlineHelpText>Is the Indicator Area associated to this Student active? If this box is unchecked then the Student no longer requires intervention in this area.</inlineHelpText>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <label>Indicator Area/Student</label>
    <nameField>
        <displayFormat>IA/S -{000}</displayFormat>
        <label>IA/Student ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Indicator Area/Student</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Program__c.object
<CustomObject>
    <description>Program is an Intervention object. Intervention Programs are aligned with Indicator Areas and are a high level set of activities with defined dosage goals. Each Program has its own frequency, target dosage, and recommended time per session. An example Program is one-on-one reading.</description>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>If this box is checked then the Program is currently available for use.</inlineHelpText>
        <label>Active?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Required_Program__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Is this Program required for your school or organization? Administrators can select whether Programs should be required or not. If yes, then each school will automatically be associated with this Program. Schools can opt of required Programs.</inlineHelpText>
        <label>Required Program</label>
        <type>Checkbox</type>
    </fields>
    <label>Program</label>
    <nameField>
        <label>Program Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/Section__c.object
<CustomObject>
    <fields>
        <fullName>Account_Program__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>What intervention Program is this intervention Section associated to?</inlineHelpText>
        <label>School Program</label>
        <lookupFilter>
            <active>false</active>
            <filterItems>
                <field>Account_Program__c.Program__c</field>
                <operation>equals</operation>
                <valueField>$Source.Program__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account_Program__c</referenceTo>
        <relationshipLabel>Sections</relationshipLabel>
        <relationshipName>Sections</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Check this box if the section is a currently active section</description>
        <inlineHelpText>Check this box if the section is a currently active section</inlineHelpText>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Program__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>What intervention Program is this Intervention Section for?</inlineHelpText>
        <label>Program</label>
        <referenceTo>Program__c</referenceTo>
        <relationshipLabel>Sections</relationshipLabel>
        <relationshipName>Sections</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>School__c</fullName>
        <label>School</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Sections</relationshipLabel>
        <relationshipName>Sections</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Section__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Recursive lookup for groups</description>
        <label>Section</label>
        <referenceTo>Section__c</referenceTo>
        <relationshipLabel>Groups in Section</relationshipLabel>
        <relationshipName>Sections1</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Section</label>
    <nameField>
        <label>Section Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sections</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Setup__c.object
<CustomObject>
    <description>This object is used to setup Schoolforce and is referenced in multiple pieces of code.  There should be one setup object per school.</description>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Is this school setup active for this school year?</inlineHelpText>
        <label>Active?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>School__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>School</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1 OR 2</booleanFilter>
            <filterItems>
                <field>Account.RecordType.Name</field>
                <operation>equals</operation>
                <value>School</value>
            </filterItems>
            <filterItems>
                <field>Account.RecordType.Name</field>
                <operation>equals</operation>
                <value>Summer School</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Setup</relationshipLabel>
        <relationshipName>Setup</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Year__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>School Year associated to the Setup</description>
        <label>Year</label>
        <referenceTo>Time_Element__c</referenceTo>
        <relationshipLabel>Setup (Year)</relationshipLabel>
        <relationshipName>Setup_Year</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Setup</label>
    <nameField>
        <displayFormat>S-{0}</displayFormat>
        <label>Setup ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Setup</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/Staff__c.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <label>Staff</label>
    <nameField>
        <label>Staff Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Staff</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/Staff_Section__c.object
<CustomObject>
    <fields>
        <fullName>School__c</fullName>
        <formula>Section__r.School__r.Id</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>The School related to this Section</inlineHelpText>
        <label>School</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Section__c</fullName>
        <label>Section</label>
        <referenceTo>Section__c</referenceTo>
        <relationshipLabel>Staff</relationshipLabel>
        <relationshipName>Staff_Section</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Staff/Section</label>
    <nameField>
        <displayFormat>SfS-{000000}</displayFormat>
        <label>Staff/Section ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Staff/Section</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Student__c.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>true</defaultValue>
        <inlineHelpText>Indicates whether or not this Student record is active. If checked, then this is the current Student record. If unchecked, this is an old Student record.</inlineHelpText>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>School__c</fullName>
        <inlineHelpText>Displays the name of the student&apos;s current SchoolForce school. You can click on the link to see the details of this school.</inlineHelpText>
        <label>School</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Students</relationshipLabel>
        <relationshipName>Students</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Section__c</fullName>
        <inlineHelpText>Displays the student&apos;s current homeroom name or room number. This field can be used for reporting purposes.</inlineHelpText>
        <label>Current Homeroom</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Setup__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Displays the Setup record associated to this Student record. The Setup record defines the settings for the school in a specific school year.</inlineHelpText>
        <label>Setup</label>
        <referenceTo>Setup__c</referenceTo>
        <relationshipLabel>Students</relationshipLabel>
        <relationshipName>Students</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Student</label>
    <nameField>
        <label>Student Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Students</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/TriggerUtils.cls
public with sharing class TriggerUtils {
	public static final String MATH = 'Math';
	public static final String BEH = 'Behavior';
	public static final String ATT = 'Attendance';
	public static final String ELA = 'ELA/Literacy';

	public static void createAccountPrograms(List<Account> schools, List<Program__c> programs){
		List<Account_Program__c> connections = new List<Account_Program__c>();
	
		for (Program__c program : programs){
			if(program.Required_Program__c){
				for(Account acc : schools){
					Account_Program__c AP = new Account_Program__c();
					AP.Active__c = false;
					AP.School__c = acc.id;
					AP.Program__c = program.id;
					AP.name = program.name;
					connections.add(AP);
				}
			}
		}
		
		if(!connections.isEmpty()) insert connections;
	}
	
	public static void deactivateAccountPrograms(Set<ID> programs){
		List<Account_Program__c> connections = [SELECT id FROM Account_Program__c WHERE Program__c IN :programs];
		if(!connections.isEmpty()){
			for(Account_Program__c ap: connections){
				ap.Active__c = false;
			}
			update connections;
		}
	}
	
	public static void assignSchoolYear(List<Account_Program__c> newList){
		Set<ID> schoolIDs = new Set<ID>();
		for(Account_Program__c ap: newList) schoolIDs.add(ap.School__c);
		List<Setup__c> setups = [SELECT id, School__c, School__r.Name, Year__c FROM Setup__c
			WHERE School__c IN :schoolIDs AND Active__c=true];
			
		Map<ID,Setup__c> schoolToActiveSetup = new Map<ID,Setup__c>();
		for(Setup__c setup: setups) schoolToActiveSetup.put(setup.School__c,setup);
		
		for(Account_Program__c ap: newList){
			if(schoolToActiveSetup.containsKey(ap.School__c)){
				ap.Current_Year_ID__c = schoolToActiveSetup.get(ap.School__c).Year__c;
				if(ap.Current_Year_ID__c==null)
					ap.addError('There is no current school year for this school.  Please check that the active setup for '+schoolToActiveSetup.get(ap.School__c).School__r.Name+' has an associated year record.');
			}
			else
				ap.addError('There is no active setup for school with id: '+ap.School__c+'.  Please activate a setup for this school.');
		}
	}
	
	public static void AUSectionStaffSectionCreate(List<Section__c> triggerNew, Map<Id, Section__c> triggerMapOld) {
		List<Staff_Section__c> staffList = new List<Staff_Section__c>();
		List<Id> sectionIds = new List<Id>(); 
		for(Section__c sec :triggerNew){
			if(sec.Intervention_Primary_Staff__c != triggerMapOld.get(sec.Id).Intervention_Primary_Staff__c && sec.Intervention_Primary_Staff__c != null){
				sectionIds.add(sec.Id);
			}
		}

		if(!sectionIds.isEmpty()){
			
			List<Section__c> sections = [Select Id, Name, Intervention_Primary_Staff__c, (Select Id, Staff__c, Section__c, Intervention_Primary_Staff__c FROM Staff_Section__r) FROM Section__c WHERE Id IN :triggerNew];
		
			for(Section__c sec :sections) {
				Boolean isNoActiveSS = true;
				if(sec.Staff_Section__r!=null && !sec.Staff_Section__r.isEmpty()){
					for(Staff_Section__c ss :sec.Staff_Section__r) {
						if(ss.Staff__c == sec.Intervention_Primary_Staff__c) {
							if(ss.Intervention_Primary_Staff__c != true) {
								ss.Intervention_Primary_Staff__c = true;
								staffList.add(ss);
							}
							isNoActiveSS = false;
						}
					}
				}
				if(isNoActiveSS){
					Staff_Section__c staffSec = new Staff_Section__c();
					staffSec.Intervention_Primary_Staff__c = true;
					staffSec.Staff__c = sec.Intervention_Primary_Staff__c;
					staffSec.Section__c = sec.id;
					staffList.add(staffSec);
				}
			}
			
			try {
				if(!staffList.isEmpty()) upsert staffList;
			} catch( Dmlexception e) {
				String linkString='';
				for(Section__c sec: sections){
					if(linkString!='') linkString+=';';
					linkString+=sec.Name+','+sec.id;
				}
				Global_Error__c ge = Error_Handling.handleError(linkString,'Section Trigger','Update primary corps member staff sections failure',e);
			}
		}
	}
	public static void AISectionStaffSectionCreate(List<Section__c> triggerNew) {
		List<Staff_Section__c> staffList = new List<Staff_Section__c>();
		for(Section__c sec :triggerNew) {
			if(sec.Intervention_Primary_Staff__c!=null){
				Staff_Section__c staffSec = new Staff_Section__c();
				staffSec.Intervention_Primary_Staff__c = true;
				staffSec.Staff__c = sec.Intervention_Primary_Staff__c;
				staffSec.Section__c = sec.Id;
				staffList.add(staffSec);
			}
		}
		try {
			if(!staffList.isEmpty()) insert staffList;
		} catch( Dmlexception e) {
			String linkString='';
			for(Section__c sec: triggerNew){
				if(linkString!='') linkString+=';';
				linkString+=sec.Name+','+sec.id;
			}
			Global_Error__c ge = Error_Handling.handleError(linkString,'Section Trigger','Insert primary corps member staff sections failure',e);
		}
	}
	
	public static void AIAUStaffSection(List<Staff_Section__c> triggerNew) {
		List<Id> sectionIds = new List<Id>();
		for(Staff_Section__c ss :triggerNew) {
			if(ss.Intervention_Primary_Staff__c == true) sectionIds.add(ss.Section__c);
		}
		
		List<Staff_Section__c> PCMList = new List<Staff_Section__c>();
		Map <Id, Section__c> SecMap = new Map<Id, Section__c>([SELECT Id, Intervention_Primary_Staff__c,(SELECT Id, Intervention_Primary_Staff__c FROM Staff_Section__r WHERE Intervention_Primary_Staff__c = true AND Id NOT IN :triggerNew) FROM Section__c WHERE Id IN :sectionIds]);
		List <Section__c> sectionsToUpdate = new List<Section__c>();		
		if(!sectionIds.isEmpty()){
			for(Staff_Section__c ss :triggerNew) {
				if(SecMap.containsKey(ss.Section__c) && ss.Intervention_Primary_Staff__c) {
					Section__c sec = SecMap.get(ss.Section__c);
					sec.Intervention_Primary_Staff__c = ss.Staff__c;
					if(sec.Staff_Section__r!=null && !sec.Staff_Section__r.isEmpty()){
						for(Staff_Section__c pm :sec.Staff_Section__r) {
							pm.Intervention_Primary_Staff__c = false;
							PCMList.add(pm);
						}
					}
					SecMap.put(sec.id,sec);
				}
			}
		}
		
		try {
			if(!PCMList.isEmpty()) update PCMList;
			if(!SecMap.isEmpty()) update SecMap.values();
			
		} catch( Dmlexception e) {
			String linkString='';
			for(Staff_Section__c sec: triggerNew){
				if(linkString!='') linkString+=';';
				linkString+=sec.Staff__r.Name+'-'+sec.Section__r.Name+','+sec.id;
			}
			Global_Error__c ge = Error_Handling.handleError(linkString,'Staff/Section Trigger','DML Failure',e);
		}
	}

	public static void checkReferenceId(List<Indicator_Area_Student__c> newList){
		for(Indicator_Area_Student__c ias : newList){
			String key = ias.Student__c+'_'+ias.Indicator_Area__c;
			if(ias.Reference_ID__c!=key) ias.Reference_ID__c = key;
		}
	}
	
	public static void checkReferenceId(List<Account_Program__c> newList){
		for(Account_Program__c ap : newList){
			String key = ap.School__c+'_'+ap.Program__c+'_'+ap.Current_Year_ID__c;
			if(ap.Reference_ID__c != key) ap.Reference_ID__c = key;
		}
	}
	
	public static Contact createContact(Student__c student, Account school){
		Contact newContact = new Contact();
		if(Student.Student_Last_Name__c != null){
			newContact.LastName = Student.Student_Last_Name__c;
		}
		if(Student.Student_First_Name__c != null){
			newContact.FirstName = Student.Student_First_Name__c;
		}
		if(Student.Date_of_Birth__c!= null){
			newContact.Date_of_Birth__c = Student.Date_of_Birth__c;
		}
		if(Student.Gender__c != null){
			newContact.Gender__c = Student.Gender__c;
		}
		if(Student.Ethnicity__c != null){
			newContact.Ethnicity__c = Student.Ethnicity__c;
		}
		if(Student.Active__c != null){
			newContact.Active__c = Student.Active__c;
		}
		if(school != null){
			newContact.AccountId = school.id;
		}
		return newContact;
	}
}