objects/Account.object
<CustomObject>
    <fields>
        <fullName>Site__c</fullName>
        <label>Location</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Baton Rouge</fullName>
                </value>
                <value>
                    <fullName>Boston</fullName>
                </value>
                <value>
                    <fullName>Buffalo</fullName>
                </value>
                <value>
                    <fullName>Chicago</fullName>
                </value>
                <value>
                    <fullName>City Year</fullName>
                </value>
                <value>
                    <fullName>Cleveland</fullName>
                </value>
                <value>
                    <fullName>Columbia</fullName>
                </value>
                <value>
                    <fullName>Columbus</fullName>
                </value>
                <value>
                    <fullName>Dallas</fullName>
                </value>
                <value>
                    <fullName>Denver</fullName>
                </value>
                <value>
                    <fullName>Detroit</fullName>
                </value>
                <value>
                    <fullName>Jacksonville</fullName>
                </value>
                <value>
                    <fullName>Kansas City</fullName>
                </value>
                <value>
                    <fullName>Little Rock</fullName>
                </value>
                <value>
                    <fullName>Los Angeles</fullName>
                </value>
                <value>
                    <fullName>Memphis</fullName>
                </value>
                <value>
                    <fullName>Miami</fullName>
                </value>
                <value>
                    <fullName>Milwaukee</fullName>
                </value>
                <value>
                    <fullName>New Hampshire</fullName>
                </value>
                <value>
                    <fullName>New Orleans</fullName>
                </value>
                <value>
                    <fullName>New York City</fullName>
                </value>
                <value>
                    <fullName>Orlando</fullName>
                </value>
                <value>
                    <fullName>Philadelphia</fullName>
                </value>
                <value>
                    <fullName>Providence</fullName>
                </value>
                <value>
                    <fullName>Rhode Island</fullName>
                </value>
                <value>
                    <fullName>Sacramento</fullName>
                </value>
                <value>
                    <fullName>San Antonio</fullName>
                </value>
                <value>
                    <fullName>San Jose/Silicon Valley</fullName>
                </value>
                <value>
                    <fullName>Seattle/King County</fullName>
                </value>
                <value>
                    <fullName>Tulsa</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <recordTypes>
        <fullName>School</fullName>
        <active>true</active>
        <description>This record type is for physical school locations.</description>
        <label>School</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Student__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>This field provides a link to the most recent Student record.</inlineHelpText>
        <label>Student</label>
        <referenceTo>Student__c</referenceTo>
        <relationshipLabel>Contacts</relationshipLabel>
        <relationshipName>Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <recordTypes>
        <fullName>Staff</fullName>
        <active>true</active>
        <description>This record type is for staff members.</description>
        <label>Staff</label>
    </recordTypes>
    <recordTypes>
        <fullName>Student</fullName>
        <active>true</active>
        <description>This record type is for students</description>
        <label>Student</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Indicator_Area_Student__c.object
<CustomObject>
    <description>The Indicator Area/Student object is a joiner object that associates an Indicator Area and a Student.</description>
    <fields>
        <fullName>Student__c</fullName>
        <inlineHelpText>This field joins the Indicator Area/Student record to the correct Student</inlineHelpText>
        <label>Student</label>
        <referenceTo>Student__c</referenceTo>
        <relationshipLabel>Indicator Area/Student</relationshipLabel>
        <relationshipName>Indicator_Area_Student</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Indicator Area/Student</label>
    <nameField>
        <displayFormat>IA/S -{000}</displayFormat>
        <label>IA/Student ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Indicator Area/Student</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Intervention_Session__c.object
<CustomObject>
    <description>The Intervention Session object captures that an Intervention Section met on a particular day. The outcome of the session is attached to the Intervention Session record.</description>
    <fields>
        <fullName>Section__c</fullName>
        <inlineHelpText>This field connects the Intervention Session record to the correct intervention Section.</inlineHelpText>
        <label>Section</label>
        <referenceTo>Section__c</referenceTo>
        <relationshipLabel>Intervention Sessions</relationshipLabel>
        <relationshipName>Intervention_Sessions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Intervention Session</label>
    <nameField>
        <displayFormat>IS-{000000}</displayFormat>
        <label>Inter. Session ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Intervention Sessions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Intervention_Session_Result__c.object
<CustomObject>
    <description>The Intervention Session Result is an object that captures the outcome of a student&apos;s participation in an Intervention Session. The result includes duration and notes.</description>
    <fields>
        <fullName>Student__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>This field connects the Student record to the Intervention Session Result</inlineHelpText>
        <label>Student</label>
        <referenceTo>Student__c</referenceTo>
        <relationshipLabel>Intervention Session Results</relationshipLabel>
        <relationshipName>Intervention_Session_Results</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Intervention Session Result</label>
    <nameField>
        <displayFormat>ISR-{000000}</displayFormat>
        <label>Time ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Intervention Session Results</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Section__c.object
<CustomObject>
    <fields>
        <fullName>Section__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Recursive lookup for groups</description>
        <label>Section</label>
        <referenceTo>Section__c</referenceTo>
        <relationshipLabel>Groups in Section</relationshipLabel>
        <relationshipName>Sections1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Staff__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Staff</label>
        <referenceTo>Staff__c</referenceTo>
        <relationshipLabel>Sections</relationshipLabel>
        <relationshipName>Sections</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Section</label>
    <nameField>
        <label>Section Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sections</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Skill__c.object
<CustomObject>
    <fields>
        <fullName>Category__c</fullName>
        <label>Category</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Literacy</fullName>
                </value>
                <value>
                    <fullName>Math</fullName>
                </value>
                <value>
                    <fullName>SEL/Behavior and Attendance Interventions</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Skill</label>
    <nameField>
        <label>Skill Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Skills</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Staff__c.object
<CustomObject>
    <fields>
        <fullName>Site__c</fullName>
        <formula>TEXT(Organization__r.Site__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Location</label>
        <type>Text</type>
    </fields>
    <label>Staff</label>
    <nameField>
        <label>Staff Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Staff</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/Student__c.object
<CustomObject>
    <fields>
        <fullName>Section__c</fullName>
        <inlineHelpText>Displays the student&apos;s current homeroom name or room number. This field can be used for reporting purposes.</inlineHelpText>
        <label>Current Homeroom</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Staff__c</fullName>
        <inlineHelpText>Displays the name of the student&apos;s homeroom teacher.  You can use this field for reporting purposes.</inlineHelpText>
        <label>Current Homeroom Teacher</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Student__c</fullName>
        <inlineHelpText>Displays the student&apos;s middle name.</inlineHelpText>
        <label>Student Middle Name</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <label>Student</label>
    <nameField>
        <label>Student Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Students</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Student_Section__c.object
<CustomObject>
    <fields>
        <fullName>Section__c</fullName>
        <label>Section</label>
        <referenceTo>Section__c</referenceTo>
        <relationshipLabel>Student</relationshipLabel>
        <relationshipName>Student_Section</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Student__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Student</label>
        <referenceTo>Student__c</referenceTo>
        <relationshipLabel>Section</relationshipLabel>
        <relationshipName>Student_Section</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Student/Section</label>
    <nameField>
        <displayFormat>SS-{000000}</displayFormat>
        <label>Student/Section ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Student/Section</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/ModalEnrollStudentController_Test.cls
@isTest
private class ModalEnrollStudentController_Test {

    private static Account school;
    private static Section__c section;
    private static Section__c section1;
    private static List<Student__c> students;
    private static Staff__c staff;
    private static Skill__c skill;
    private static final Integer UNENROLLED_STUDENT_COUNT = 5;
    private static final Integer ALL_STUDENT_COUNT = 10;

    private static void setupTestData() {
        skill = new Skill__c();
        skill.Name = 'Self-Awareness: Identifying strengths and weaknesses';
        skill.Category__c = 'SEL/Behavior and Attendance Interventions';
        insert skill;
        TestDataUtil.setupSharingControls();
        TestDataUtil.setupTime();
        school = TestDataUtil.createSchool('ApexTestSchool1');
        school.Site__c = 'Boston';
        insert school;
        TestDataUtil.schoolList.add(school);
        TestDataUtil.setupSetupRecord();
        List<Indicator_Area__c> ia = TestDataUtil.createIndicatorAreas();
        insert ia;
        List<Program__c> programs = TestDataUtil.createPrograms(1, true, ia[0]);
        programs.addAll(TestDataUtil.createPrograms(1, true, ia[1]));
        programs.addAll(TestDataUtil.createPrograms(1, false, ia[2]));
        programs.addAll(TestDataUtil.createPrograms(1, false, ia[3]));
        insert programs;
        Account_Program__c accProg = TestDataUtil.createAccountProgram(school, programs[0]);
        Account_Program__c accProg1 = TestDataUtil.createAccountProgram(school, programs[1]);
        insert new List<Account_Program__c>{
                accProg, accProg1
        };
        students = TestDataUtil.createStudents(ALL_STUDENT_COUNT, school);
        insert students;
        List<Indicator_Area_Student__c> ias = TestDataUtil.createIAStudents(students, ia[0].Id);
        insert ias;

        Contact c = TestDataUtil.createContact('ApexTest', 'User', null);
        insert c;
        staff = TestDataUtil.createStaff(c, school, 1);
        insert staff;
        section = TestDataUtil.createSections_WithoutInsert(1, school, accProg, staff, programs[0])[0];
        section.Start_Date__c = Date.today().addDays(-7);
        section1 = TestDataUtil.createSections_WithoutInsert(1, school, accProg1, staff, programs[1])[0];
        section1.Name = 'SectionNewTest';
        section1.Start_Date__c = Date.today().addDays(-7);

        insert new List<Section__c>{
                section, section1
        };

        insert TestDataUtil.createStudentSections_WithoutInsert(new List<Section__c>{
                section, section1
        }, new List<List<Student__c>>{
                students, students
        });

        List<Student__c> notEnrolled = TestDataUtil.createStudents(UNENROLLED_STUDENT_COUNT, school);
        insert notEnrolled;

        Test.setCurrentPage(Page.IM_SectionDetail);
        ApexPages.currentPage().getParameters().put('SectionID', section.id);
    }

    private static Id setupExistingSessions() {
        Intervention_Session__c session = new Intervention_Session__c(
                Section__c = section.ID,
                Session_Time_Completed_For__c = staff.ID,
                All_avenues__c = 'In-Person Service',
                Date__c = Date.today()
        );
        insert session;

        List<Intervention_Session_Result__c> results = new List<Intervention_Session_Result__c>();
        for (Student_Section__c s : [select id from Student_Section__c where Section__c = :section.ID]) {
            results.add(new Intervention_Session_Result__c(
                    Intervention_Session__c = session.ID,
                    Amount_of_Time__c = 30,
                    Student_Section__c = s.ID
            ));
        }
        insert results;
        return session.Id;
    }

//    static testMethod void testConstructor_NoSectionID() {
//        setupTestData();
//        Test.setCurrentPage(Page.IM_SectionDetail);
//        ApexPages.currentPage().getParameters().remove('SectionID');
//        Test.startTest();
//        ModalEnrollStudentController controller = new ModalEnrollStudentController();
//        System.assertEquals('The system was unable to locate the id of the section you wish to view. Please return to the section detail page and try again.', ApexPages.getMessages()[0].getSummary());
//        Test.stopTest();
//    }

    static testMethod void testConstructor() {
        setupTestData();
        Test.startTest();

        ModalEnrollStudentController controller = new ModalEnrollStudentController();
        System.assertEquals(section.ID, controller.sectionID, 'Expected the section IDs to match.');
        Test.stopTest();
    }

    static testMethod void testEnrollStudents() {
        setupTestData();
        Test.startTest();

        ModalEnrollStudentController controller = new ModalEnrollStudentController();
        controller.section = section;
        controller.startEnrollStudents();
        System.assertEquals(15, controller.availableStudents.size(), 'Expected the availableStudents size to match the unenrolled students in the school.');
        System.assertEquals(2, controller.gradeFilters.size());
        System.assertEquals(2, controller.indicatorAreaFilters.size());

        for (StudentInfoWrapper s : controller.availableStudents) {
            s.selected = true;
        }

        controller.addToSelected();
        System.assertEquals(15, controller.selectedStudents.size(), 'Expected all student to be moved to selectedStudents.');

        controller.selectedStudents[0].selected = true;
        controller.removeFromSelected();
        System.assertEquals(1, controller.availableStudents.size(), 'Expected only one student to be removed');
        System.assertEquals(15 - 1, controller.selectedStudents.size(), 'Expected only one student to be removed.');

        controller.enrollStudents();
        Test.stopTest();
    }

//    static testMethod void testDisplayStudent() {
//        setupTestData();
//        Test.startTest();
//        ModalEnrollStudentController controller = new ModalEnrollStudentController();
//
//        controller.displayStudent();
//        Test.stopTest();
//    }


    static testMethod void enrollTest() {
        setupTestData();

        Test.setCurrentPage(Page.IM_SectionDetail);
        ApexPages.currentPage().getParameters().put('SectionID', section.id);
        Test.startTest();
        ModalEnrollStudentController controller = new ModalEnrollStudentController();
        controller.section = section;

        controller.startEnrollStudents();
        system.assert(controller.availableStudents.size() > 0);

        Integer startingAvaible = controller.availableStudents.size();
        string stuIds = '';
        for (StudentInfoWrapper s : controller.availableStudents) {
            s.selected = true;
        }
        controller.addToSelected();
        system.assertEquals(startingAvaible, controller.selectedStudents.size());
        system.assertEquals(0, controller.availableStudents.size());

        for (StudentInfoWrapper s : controller.selectedStudents) {
            s.selected = true;
        }
        controller.removeFromSelected();
        system.assertEquals(0, controller.selectedStudents.size());
        system.assertEquals(startingAvaible, controller.availableStudents.size());

        for (StudentInfoWrapper s : controller.availableStudents) {
            s.selected = true;
        }
        controller.addToSelected();
        system.assertEquals(startingAvaible, controller.selectedStudents.size());
        system.assertEquals(0, controller.availableStudents.size());

        controller.studentSectionHolder.Enrollment_Start_Date__c = system.today();
        controller.enrollStudents();
        test.stopTest();
    }
}