objects/Account_Program__c.object
<CustomObject>
    <description>The Account/Program object is part of the Interventions App and links Programs and Schools/Accounts.  This linking occurs in the Interventions Setup when a school selects which interventions Programs they will enroll in for a specific year.  This object tracks the relationships of Programs and Schools and whether the Programs are active.</description>
    <fields>
        <fullName>Program__c</fullName>
        <inlineHelpText>This field joins the Account/Program record to the correct intervention Program</inlineHelpText>
        <label>Program</label>
        <referenceTo>Program__c</referenceTo>
        <relationshipLabel>School Programs</relationshipLabel>
        <relationshipName>Accounts_Programs</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Account/Program</label>
    <nameField>
        <label>School Program Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Accounts/Programs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Data_Load_Log__c.object
<CustomObject>
    <description>Logs information about data loads such as status and success/failure statistics.</description>
    <fields>
        <fullName>Type__c</fullName>
        <description>Type of data loaded.</description>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Section</fullName>
                </value>
                <value>
                    <fullName>Session</fullName>
                </value>
                <value>
                    <fullName>Staff</fullName>
                </value>
                <value>
                    <fullName>Staff/Section</fullName>
                </value>
                <value>
                    <fullName>Student</fullName>
                </value>
                <value>
                    <fullName>Student/Section</fullName>
                </value>
                <value>
                    <fullName>Interventions Data Deactivation</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Data Load Log</label>
    <nameField>
        <displayFormat>DLL-{0000000}</displayFormat>
        <label>Data Load Log #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Data Load Log</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Indicator_Area__c.object
<CustomObject>
    <description>This object is part of the Interventions app. Indicator Area defines a high-level intervention focus area (e.g., Behavior, Attendance, English Language Arts). Students are assigned to Indicator Areas in order to schedule them in Intervention Programs and Sections.</description>
    <label>Indicator Area</label>
    <nameField>
        <label>Indicator Area</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Indicator Areas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Indicator_Area_Student__c.object
<CustomObject>
    <description>The Indicator Area/Student object is a joiner object that associates an Indicator Area and a Student.</description>
    <fields>
        <fullName>Indicator_Area__c</fullName>
        <inlineHelpText>This field joins the Indicator Area/Student record to the correct Indicator Area</inlineHelpText>
        <label>Indicator Area</label>
        <referenceTo>Indicator_Area__c</referenceTo>
        <relationshipLabel>Indicator Area/Student</relationshipLabel>
        <relationshipName>Indicator_Area_Student</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Student__c</fullName>
        <inlineHelpText>This field joins the Indicator Area/Student record to the correct Student</inlineHelpText>
        <label>Student</label>
        <referenceTo>Student__c</referenceTo>
        <relationshipLabel>Indicator Area/Student</relationshipLabel>
        <relationshipName>Indicator_Area_Student</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Indicator Area/Student</label>
    <nameField>
        <displayFormat>IA/S -{000}</displayFormat>
        <label>IA/Student ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Indicator Area/Student</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Program__c.object
<CustomObject>
    <description>Program is an Intervention object. Intervention Programs are aligned with Indicator Areas and are a high level set of activities with defined dosage goals. Each Program has its own frequency, target dosage, and recommended time per session. An example Program is one-on-one reading.</description>
    <fields>
        <fullName>Indicator_Area__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>You must select an Indicator Area that aligns with this Program.</inlineHelpText>
        <label>Indicator Area</label>
        <referenceTo>Indicator_Area__c</referenceTo>
        <relationshipLabel>Programs</relationshipLabel>
        <relationshipName>Programs</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Program</label>
    <nameField>
        <label>Program Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/Section__c.object
<CustomObject>
    <fields>
        <fullName>Account_Program__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>What intervention Program is this intervention Section associated to?</inlineHelpText>
        <label>School Program</label>
        <lookupFilter>
            <active>false</active>
            <filterItems>
                <field>Account_Program__c.Program__c</field>
                <operation>equals</operation>
                <valueField>$Source.Program__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account_Program__c</referenceTo>
        <relationshipLabel>Sections</relationshipLabel>
        <relationshipName>Sections</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Indicator_Area__c</fullName>
        <formula>Program__r.Indicator_Area__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>What Indicator Area is this Program addressing? This field cannot be modified here.</inlineHelpText>
        <label>Indicator Area</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Program__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>What intervention Program is this Intervention Section for?</inlineHelpText>
        <label>Program</label>
        <referenceTo>Program__c</referenceTo>
        <relationshipLabel>Sections</relationshipLabel>
        <relationshipName>Sections</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Section__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Recursive lookup for groups</description>
        <label>Section</label>
        <referenceTo>Section__c</referenceTo>
        <relationshipLabel>Groups in Section</relationshipLabel>
        <relationshipName>Sections1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <description>Section or Standard Group or Custom Group</description>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Section</fullName>
                </value>
                <value>
                    <fullName>Standard Group</fullName>
                </value>
                <value>
                    <fullName>Custom Group</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Section</label>
    <nameField>
        <label>Section Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sections</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Student__c.object
<CustomObject>
    <fields>
        <fullName>Section__c</fullName>
        <inlineHelpText>Displays the student&apos;s current homeroom name or room number. This field can be used for reporting purposes.</inlineHelpText>
        <label>Current Homeroom</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Student__c</fullName>
        <inlineHelpText>Displays the student&apos;s middle name.</inlineHelpText>
        <label>Student Middle Name</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <label>Student</label>
    <nameField>
        <label>Student Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Students</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/Test_BatchDeactivateData.cls
@isTest
private class Test_BatchDeactivateData {
	
	@isTest static void Test_EOYDataDeactivation() {
		TestDataUtil.setupData(1);
		TestDataUtil.SchoolWrapper SW = TestDataUtil.testData[0];
		
		Indicator_Area__c ia = TestDataUtil.createIndicatorAreas(1)[0];
		insert ia;
		List<Indicator_Area_Student__c> iaStuList = TestDataUtil.createIAStudents(SW.students,ia.Id);
		insert iaStuList;
		Program__c program = TestDataUtil.createPrograms(1,true,ia)[0];
		insert program;
		Account_Program__c ap = TestDataUtil.createAccountProgram(SW.school, program);
		insert ap;
		List<Section__c> sections = TestDataUtil.createSections(1, SW.school,ap,new List<List<Student__c>>{SW.students},SW.cmDirect.staffRecord,program);
		
		Test.setCurrentPage(Page.EOYWiz_InterventionsLanding);
		Test.StartTest();
			EOY_InterventionsLanding controller = new EOY_InterventionsLanding();
			controller.checkForEOYProgress();

			controller.startDeactivation();
			List<Data_Load_Log__c> logs = [select id from Data_Load_Log__c where Type__c = 'Interventions Data Deactivation'];
			system.assertEquals(1, logs.size());

			controller.finalizeBatch();
		Test.stopTest();
	}
	
	
}