objects/Account.object
<CustomObject>
    <recordTypes>
        <fullName>Organization</fullName>
        <active>true</active>
        <description>An Account representing an organization</description>
        <label>Organization</label>
    </recordTypes>
    <recordTypes>
        <fullName>School</fullName>
        <active>true</active>
        <description>This record type is for physical school locations.</description>
        <label>School</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Picklist_Value__c.object
<CustomObject>
    <fields>
        <fullName>Setup__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Setup</label>
        <referenceTo>Setup__c</referenceTo>
        <relationshipLabel>Picklist Values</relationshipLabel>
        <relationshipName>Picklist_Values</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Attendance</fullName>
                </value>
                <value>
                    <fullName>Time</fullName>
                </value>
                <value>
                    <fullName>Assignment</fullName>
                </value>
                <value>
                    <fullName>Grade Scale</fullName>
                </value>
                <value>
                    <fullName>Homework</fullName>
                </value>
                <value>
                    <fullName>Behavior Type</fullName>
                </value>
                <value>
                    <fullName>Behavior Consequence</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Picklist Value</label>
    <nameField>
        <label>Display Value</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Picklist Values</pluralLabel>
    <recordTypes>
        <fullName>Time</fullName>
        <active>true</active>
        <label>Time</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Setup__c.object
<CustomObject>
    <description>This object is used to setup Schoolforce and is referenced in multiple pieces of code.  There should be one setup object per school.</description>
    <fields>
        <fullName>School__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>School</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1 OR 2</booleanFilter>
            <filterItems>
                <field>Account.RecordType.Name</field>
                <operation>equals</operation>
                <value>School</value>
            </filterItems>
            <filterItems>
                <field>Account.RecordType.Name</field>
                <operation>equals</operation>
                <value>Summer School</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Setup</relationshipLabel>
        <relationshipName>Setup</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Year__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>School Year associated to the Setup</description>
        <label>Year</label>
        <referenceTo>Time_Element__c</referenceTo>
        <relationshipLabel>Setup (Year)</relationshipLabel>
        <relationshipName>Setup_Year</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Setup</label>
    <nameField>
        <displayFormat>S-{0}</displayFormat>
        <label>Setup ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Setup</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/Time_Element__c.object
<CustomObject>
    <fields>
        <fullName>Name__c</fullName>
        <label>Name</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Picklist_Value__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Picklist Value</label>
        <referenceTo>Picklist_Value__c</referenceTo>
        <relationshipLabel>Time</relationshipLabel>
        <relationshipName>Time</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>School__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>School</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Time</relationshipLabel>
        <relationshipName>Time</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Year</fullName>
                </value>
                <value>
                    <fullName>Semester</fullName>
                </value>
                <value>
                    <fullName>Trimester</fullName>
                </value>
                <value>
                    <fullName>Quarter</fullName>
                </value>
                <value>
                    <fullName>Period</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Time</label>
    <nameField>
        <displayFormat>T-{000000}</displayFormat>
        <label>Time Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Time</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/CT_Test_SetupWizard_Home.cls
/**
 * This class contains unit tests for validating the behavior of Apex classes
 * and triggers.
 *
 * Unit tests are class methods that verify whether a particular piece
 * of code is working properly. Unit test methods take no arguments,
 * commit no data to the database, and are flagged with the testMethod
 * keyword in the method definition.
 *
 * All test methods in an organization are executed whenever Apex code is deployed
 * to a production organization to confirm correctness, ensure code
 * coverage, and prevent regressions. All Apex classes are
 * required to have at least 75% code coverage in order to be deployed
 * to a production organization. In addition, all triggers must have some code coverage.
 * 
 * The @isTest class annotation indicates this class only contains test
 * methods. Classes defined with the @isTest annotation do not count against
 * the organization size limit for all Apex scripts.
 *
 * See the Apex Language Reference for more information about Testing and Code Coverage.
 */
@isTest
private class CT_Test_SetupWizard_Home {

    static testMethod void testConstructor() {
        Test.startTest();
            CT_SetupWizard_Home swh = new CT_SetupWizard_Home();
            system.assert(swh.needSchools);
            system.assert(!swh.needYears);
            system.assert(!swh.orgWideComplete);
            
            Account a = new Account(Name='Test School', RecordTypeId=CT_core_SoqlUtils.getRecordTypesBySobject('Account').get('School'));
            insert a;
            swh = new CT_SetupWizard_Home();
            system.assert(!swh.needSchools);
            system.assert(swh.needYears);
            system.assert(!swh.orgWideComplete);
            
            Picklist_Value__c yearPV = new Picklist_Value__c(Name='Year',Type__c='Time',RecordTypeId=CT_core_SoqlUtils.getRecordTypesBySobject('Picklist_Value__c').get('Time'));
            insert yearPV;
            Time_Element__c year = new Time_Element__c(Name__c='Test Year',Picklist_Value__c=yearPV.id);
            insert year;
            swh = new CT_SetupWizard_Home();
            system.assert(!swh.needSchools);
            system.assert(!swh.needYears);
            system.assert(swh.orgWideComplete);
            system.assertEquals(1,swh.schools.size());
            system.assertEquals(1,swh.years.size());
        Test.stopTest();
    }
    
    static testMethod void testGoToSchoolSetup(){
        Account a = new Account(Name='Test School', RecordTypeId=CT_core_SoqlUtils.getRecordTypesBySobject('Account').get('School'));
        insert a;
        Picklist_Value__c yearPV = new Picklist_Value__c(Name='Year',Type__c='Time',RecordTypeId=CT_core_SoqlUtils.getRecordTypesBySobject('Picklist_Value__c').get('Time'));
        insert yearPV;
        Time_Element__c year = new Time_Element__c(Name__c='Test Year',Picklist_Value__c=yearPV.id);
        insert year;
        Test.startTest();
            CT_SetupWizard_Home swh = new CT_SetupWizard_Home();
            PageReference pr = swh.goToSchoolSetup();
            system.assertEquals(null,pr);
            system.assertEquals('Please select a school to set up.',ApexPages.getMessages()[0].getSummary());
            system.assertEquals('Please select a year for which the setup will be valid.',ApexPages.getMessages()[1].getSummary());
            
            Setup__c setup = [SELECT id FROM Setup__c WHERE School__c=:a.id AND Year__c=:year.id];
            swh.selectedSchool = a.id;
            swh.selectedYear = year.id;
            pr = swh.goToSchoolSetup();
            system.assert(pr.getURL().toLowerCase().contains('ct_core_termsetup_v2'));
            system.assertEquals(setup.id,pr.getParameters().get('setupId'));
        Test.stopTest();
    }
}