objects/Account_Program__c.object
<CustomObject>
    <description>The Account/Program object is part of the Interventions App and links Programs and Schools/Accounts.  This linking occurs in the Interventions Setup when a school selects which interventions Programs they will enroll in for a specific year.  This object tracks the relationships of Programs and Schools and whether the Programs are active.</description>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Is this Program active for this School in this year?</inlineHelpText>
        <label>Active?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Program__c</fullName>
        <inlineHelpText>This field joins the Account/Program record to the correct intervention Program</inlineHelpText>
        <label>Program</label>
        <referenceTo>Program__c</referenceTo>
        <relationshipLabel>School Programs</relationshipLabel>
        <relationshipName>Accounts_Programs</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Account/Program</label>
    <nameField>
        <label>School Program Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Accounts/Programs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Enrollment_Tracking__c.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Active?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Student_Section__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Student/Section</label>
        <referenceTo>Student_Section__c</referenceTo>
        <relationshipLabel>Enrollment Tracking</relationshipLabel>
        <relationshipName>Enrollment_Tracking</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Student__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Student</label>
        <referenceTo>Student__c</referenceTo>
        <relationshipLabel>Enrollment Tracking</relationshipLabel>
        <relationshipName>Enrollment_Tracking</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Enrollment Tracking</label>
    <nameField>
        <displayFormat>ET-{0000000}</displayFormat>
        <label>Enrollment Tracking Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Enrollment Tracking</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Intervention_Session__c.object
<CustomObject>
    <description>The Intervention Session object captures that an Intervention Section met on a particular day. The outcome of the session is attached to the Intervention Session record.</description>
    <fields>
        <fullName>Section__c</fullName>
        <inlineHelpText>This field connects the Intervention Session record to the correct intervention Section.</inlineHelpText>
        <label>Section</label>
        <referenceTo>Section__c</referenceTo>
        <relationshipLabel>Intervention Sessions</relationshipLabel>
        <relationshipName>Intervention_Sessions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Intervention Session</label>
    <nameField>
        <displayFormat>IS-{000000}</displayFormat>
        <label>Inter. Session ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Intervention Sessions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Intervention_Session_Result__c.object
<CustomObject>
    <description>The Intervention Session Result is an object that captures the outcome of a student&apos;s participation in an Intervention Session. The result includes duration and notes.</description>
    <fields>
        <fullName>Amount_of_Time__c</fullName>
        <inlineHelpText>Amount of time spent with a student (in minutes) in a single Intervention Session</inlineHelpText>
        <label>Amount of Time (in minutes)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Program__c</fullName>
        <description>Program name for associated intervention session results</description>
        <formula>Student_Section__r.Section__r.Program__c</formula>
        <label>Program</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Student_Section__c</fullName>
        <inlineHelpText>This field connects the Intervention Session Result record to the correct Student/Section.</inlineHelpText>
        <label>Student/Section</label>
        <referenceTo>Student_Section__c</referenceTo>
        <relationshipLabel>Intervention Session Results</relationshipLabel>
        <relationshipName>Intervention_Session_Results</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Student__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>This field connects the Student record to the Intervention Session Result</inlineHelpText>
        <label>Student</label>
        <referenceTo>Student__c</referenceTo>
        <relationshipLabel>Intervention Session Results</relationshipLabel>
        <relationshipName>Intervention_Session_Results</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Intervention Session Result</label>
    <nameField>
        <displayFormat>ISR-{000000}</displayFormat>
        <label>Time ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Intervention Session Results</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Program__c.object
<CustomObject>
    <description>Program is an Intervention object. Intervention Programs are aligned with Indicator Areas and are a high level set of activities with defined dosage goals. Each Program has its own frequency, target dosage, and recommended time per session. An example Program is one-on-one reading.</description>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>If this box is checked then the Program is currently available for use.</inlineHelpText>
        <label>Active?</label>
        <type>Checkbox</type>
    </fields>
    <label>Program</label>
    <nameField>
        <label>Program Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/Scheduled_Section__c.object
<CustomObject>
    <fields>
        <fullName>Section__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Section</label>
        <referenceTo>Section__c</referenceTo>
        <relationshipLabel>Scheduled Sections</relationshipLabel>
        <relationshipName>Scheduled_Sections</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Scheduled Section</label>
    <nameField>
        <label>Scheduled Section Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Scheduled Sections</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Section__c.object
<CustomObject>
    <fields>
        <fullName>Account_Program__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>What intervention Program is this intervention Section associated to?</inlineHelpText>
        <label>School Program</label>
        <lookupFilter>
            <active>false</active>
            <filterItems>
                <field>Account_Program__c.Program__c</field>
                <operation>equals</operation>
                <valueField>$Source.Program__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account_Program__c</referenceTo>
        <relationshipLabel>Sections</relationshipLabel>
        <relationshipName>Sections</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Check this box if the section is a currently active section</description>
        <inlineHelpText>Check this box if the section is a currently active section</inlineHelpText>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Program__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>What intervention Program is this Intervention Section for?</inlineHelpText>
        <label>Program</label>
        <referenceTo>Program__c</referenceTo>
        <relationshipLabel>Sections</relationshipLabel>
        <relationshipName>Sections</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Section__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Recursive lookup for groups</description>
        <label>Section</label>
        <referenceTo>Section__c</referenceTo>
        <relationshipLabel>Groups in Section</relationshipLabel>
        <relationshipName>Sections1</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Section</label>
    <nameField>
        <label>Section Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sections</pluralLabel>
    <recordTypes>
        <fullName>Schedule_Group</fullName>
        <active>true</active>
        <description>Groups of Students Used for Scheduling Purposes</description>
        <label>Schedule Group</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Student__c.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>true</defaultValue>
        <inlineHelpText>Indicates whether or not this Student record is active. If checked, then this is the current Student record. If unchecked, this is an old Student record.</inlineHelpText>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Section__c</fullName>
        <inlineHelpText>Displays the student&apos;s current homeroom name or room number. This field can be used for reporting purposes.</inlineHelpText>
        <label>Current Homeroom</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Student__c</fullName>
        <inlineHelpText>Displays the student&apos;s middle name.</inlineHelpText>
        <label>Student Middle Name</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <label>Student</label>
    <nameField>
        <label>Student Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Students</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Student_Program__c.object
<CustomObject>
    <description>This is an object is students/program roll up</description>
    <fields>
        <fullName>Amount_of_Time__c</fullName>
        <label>Total Time for Program</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Program__c</fullName>
        <formula>IF(  ISBLANK( Section_del__r.Program__c ) ,  &quot;&quot; ,   Section_del__r.Program__r.Name  )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Program</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Student__c</fullName>
        <description>Student/Program</description>
        <label>Student</label>
        <referenceTo>Student__c</referenceTo>
        <relationshipLabel>Student/Programs</relationshipLabel>
        <relationshipName>Student_Programs</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Student/Program</label>
    <nameField>
        <displayFormat>SP-{0000}</displayFormat>
        <label>Student/Program Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Student/Programs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Student_Section__c.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Amount_of_Time__c</fullName>
        <label>Amount of time per section</label>
        <summarizedField>Intervention_Session_Result__c.Amount_of_Time__c</summarizedField>
        <summaryForeignKey>Intervention_Session_Result__c.Student_Section__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Program__c</fullName>
        <formula>CASESAFEID(Section__r.Program__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Program</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Section__c</fullName>
        <label>Section</label>
        <referenceTo>Section__c</referenceTo>
        <relationshipLabel>Student</relationshipLabel>
        <relationshipName>Student_Section</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Student_Program__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Student/Program</label>
        <referenceTo>Student_Program__c</referenceTo>
        <relationshipLabel>Student/Section</relationshipLabel>
        <relationshipName>Student_Section</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Student__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Student</label>
        <referenceTo>Student__c</referenceTo>
        <relationshipLabel>Section</relationshipLabel>
        <relationshipName>Student_Section</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Student/Section</label>
    <nameField>
        <displayFormat>SS-{000000}</displayFormat>
        <label>Student/Section ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Student/Section</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/Test_Student_Section_Utils.cls
@isTest
private class Test_Student_Section_Utils {
	private static final Integer COUNT = 5;
	private static final Integer AMOUNT = 30;

	@testSetup
	private static void setupData(){
		testDataSetupUtil_v2.setUPCoreData(COUNT);
		testDataSetupUtil_v2.setUPStaffData(COUNT);
		testDataSetupUtil_v2.setUPStudentData(COUNT);
		testDataSetupUtil_v2.setUPProgramData(testDataSetupUtil_v2.sectionsList, testDataSetupUtil_v2.school);
		testDataSetupUtil_v2.setUPExistingSessionResults(AMOUNT);

		List<Section__c> groups = TestDataSetupUtil_v2.getScheduleGroups_Section();
		//groups[0] has 3 sections, groups[1] has 2 sections
		List<Scheduled_Section__c> schsec = TestDataSetupUtil_v2.createScheduledSections(groups);		
	}

	static testMethod void testFillStudentProgramField() {
		List<Student_Section__c> listSS = [SELECT Id, Student__c, Program__c, Amount_of_Time__c, Student_Program__c, Active__c FROM Student_Section__c];
		for(Student_Section__c studentSection: listSS){
			studentSection.Student_Program__c = null;
		}

    	Test.startTest();
    		StudentSectionUtils.fillStudentProgramField(listSS, null);
    	Test.stopTest();

		for(Student_Section__c studentSection: listSS){
			System.assertNotEquals(null, studentSection.Student_Program__c);
		}
	}

	static testMethod void testCalculateAmountOfTime() {
		List<Student_Section__c> listSS = [SELECT Id, Student__c, Program__c, Amount_of_Time__c, Student_Program__c, Active__c FROM Student_Section__c];
		StudentSectionUtils.fillStudentProgramField(listSS, null);

    	Test.startTest();
    		StudentSectionUtils.calculateAmountOfTime(listSS, null);
    	Test.stopTest();

    	List<Student_Program__c> studentPrograms = new List<Student_Program__c>([SELECT Id, Student__c, Amount_of_Time__c FROM Student_Program__c]);
    	System.assertEquals(COUNT + 1, studentPrograms.size());
		for(Student_Program__c studentProgram: studentPrograms){
			System.assertEquals(AMOUNT, studentProgram.Amount_of_Time__c);
		}
	}

	static testMethod void testdeleteStudentSection() {
		List<Student_Section__c> listSS = [SELECT Id, Student__c, Section__c, Section__r.Account_Program__c, Program__c, Amount_of_Time__c, Student_Program__c, Active__c,
			(SELECT Id, Intervention_Session__c FROM Intervention_Session_Results__r) FROM Student_Section__c];
		List<Section__c> listS = [SELECT Id FROM Section__c];
		Section__c newSec = listS[COUNT-1];
		newSec.Program__c = listSS[0].Program__c;
		newSec.Account_Program__c = listSS[0].Section__r.Account_Program__c;
		update newSec;
		Student_Section__c uss = new Student_Section__c(Section__c = listSS[COUNT].Section__c, Student__c = listSS[0].Student__c);
		insert uss;
		
		Map<Id, Intervention_Session__c> mapIS = new Map<Id, Intervention_Session__c>(); 
		for(Student_Section__c ss: listSS){
			for(Intervention_Session_Result__c isr: ss.Intervention_Session_Results__r){
				mapIS.put(isr.Intervention_Session__c, new Intervention_Session__c(Id=isr.Intervention_Session__c));
			}
		}

    	Test.startTest();
    		delete mapIS.values();
    		delete listSS;
    	Test.stopTest();

    	List<Student_Program__c> studentPrograms = new List<Student_Program__c>([SELECT Id, Student__c, Amount_of_Time__c FROM Student_Program__c]);
    	System.assertEquals(1, studentPrograms.size());
	}

	static testMethod void testdeleteSection() {
		List<Section__c> listS = [SELECT Id FROM Section__c];		

    	Test.startTest();
    		delete listS;
    	Test.stopTest();

    	List<Student_Program__c> studentPrograms = new List<Student_Program__c>([SELECT Id, Student__c, Amount_of_Time__c FROM Student_Program__c]);
    	System.assertEquals(0, studentPrograms.size());
	}

	static testMethod void testEnrollmentSS() {
		List<Enrollment_Tracking__c> listET;
		List<Student_Section__c> listSS = [SELECT Id, Student__c, Section__c, Section__r.Account_Program__c, Program__c, Amount_of_Time__c, Student_Program__c, Active__c FROM Student_Section__c];

    	Test.startTest();
    		listSS[0].Active__c = false;
    		listSS[0].Section_Exit_Reason__c = core_triggerUtils.SECTIONEXITREASONBYTRIGGER;
    		update listSS[0];
    		listET = [SELECT Id FROM Enrollment_Tracking__c WHERE Student_Section__c = :listSS[0].Id];
    		System.assertEquals(2, listET.size());
    		listSS[0].Active__c = true;
    		listSS[0].Enrollment_start_date__c = Datetime.now().addMinutes(1);
    		update listSS[0];
    		listET = [SELECT Id FROM Enrollment_Tracking__c WHERE Student_Section__c = :listSS[0].Id];
    		System.assertEquals(3, listET.size());    		
    	Test.stopTest();
	}

	static testMethod void testSheduledSS() {
		List<Section__c> groups = [SELECT Id FROM Section__c WHERE RecordType.DeveloperName='Schedule_Group'];
		List<Student__c> listStudent = [SELECT Id FROM Student__c];

		Test.startTest();
			listStudent[0].Primary_Schedule_Group__c = groups[0].id;
			update listStudent[0];
			List<Student_Section__c> listSS = [SELECT Id FROM Student_Section__c WHERE Student__c = :listStudent[0].Id];
			System.assertEquals(2, listSS.size());
		Test.stopTest();
	}

}