objects/Account.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <label>Active</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>No</fullName>
                </value>
                <value>
                    <fullName>Yes</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <recordTypes>
        <fullName>School</fullName>
        <active>true</active>
        <description>This record type is for physical school locations.</description>
        <label>School</label>
    </recordTypes>
    <recordTypes>
        <fullName>State</fullName>
        <active>true</active>
        <description>This record type is for states.</description>
        <label>State</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/EOY_Progress__c.object
<CustomObject>
    <description>This object is used to determine the current completion progress in the EOY Wizard.</description>
    <fields>
        <fullName>EOY_Next_School_Year_Completed__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Create the next school year here or potentially in the school setup wizard.</description>
        <inlineHelpText>This will be checked if the next school year is created.</inlineHelpText>
        <label>EOY Next School Year Completed</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>EOY_Purge_Settings_Completed__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Customizing the Purge Settings for the entire org.</description>
        <inlineHelpText>This is set to true if the EOY Purge custom settings are configured for the year.</inlineHelpText>
        <label>EOY Purge Settings Completed</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Is_Complete__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Complete</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Module_Name__c</fullName>
        <label>Module Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Parent_Progress__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This is the parent progress tracking record for this record.</description>
        <label>Parent Progress</label>
        <referenceTo>EOY_Progress__c</referenceTo>
        <relationshipLabel>EOY Progresses</relationshipLabel>
        <relationshipName>EOY_Progresses</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>School_Grade_Span_Completed__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Select the grade span for the school.</description>
        <inlineHelpText>This will be checked when the grade span has been confirmed for the next school year.</inlineHelpText>
        <label>School Grade Span Completed</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>School_Next_Year_Students_Completed__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Schools will create the next year student records here.</description>
        <inlineHelpText>This will be checked when the net new student records are generated for the next year.</inlineHelpText>
        <label>School Next Year Students Completed</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>School_Process_Data_Completed__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Schools will process the EOY data, where records will get deactivated and archived.</description>
        <inlineHelpText>This will be checked when the EOY Data is deactivated and archived has been verified.</inlineHelpText>
        <label>School Process Data Completed</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>School_Purge_EOY_Data_Completed__c</fullName>
        <defaultValue>false</defaultValue>
        <description>School EOY Data purge process.</description>
        <inlineHelpText>This will be checked when the EOY Data has successfully been purged.</inlineHelpText>
        <label>School Purge EOY Data Completed</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>School_Purge_Historical_Data_Completed__c</fullName>
        <defaultValue>false</defaultValue>
        <description>School process to purge historical data.</description>
        <inlineHelpText>This will be checked when Historical Data has been successfully purged.</inlineHelpText>
        <label>School Purge Historical Data Completed</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>School_Snapshots_Completed__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Schools will create snapshot records for the year.</description>
        <inlineHelpText>This will be checked when snapshots are successfully created for the year.</inlineHelpText>
        <label>School Snapshots Completed</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>School_Student_Promotional_Completed__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Set the students&apos; promotional status for the following year.</description>
        <inlineHelpText>This will be checked when the student&apos;s record is verified for: Intent to return, Promoted, Next year School, and Final Grade Level.</inlineHelpText>
        <label>School Student Promotional Completed</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>School__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field is required to keep track of the EOY progression for a school.</description>
        <inlineHelpText>This field is required for EOY Progression on schools.</inlineHelpText>
        <label>School</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>EOY Progresses</relationshipLabel>
        <relationshipName>EOY_Progresses</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Setup__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Look up to the setup record, since a setup represents an active configuration for a school.</description>
        <inlineHelpText>Determine the progress for an active setup to a school.</inlineHelpText>
        <label>Setup</label>
        <referenceTo>Setup__c</referenceTo>
        <relationshipLabel>EOY Progresses</relationshipLabel>
        <relationshipName>EOY_Progresses</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Year__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>The year that the EOY Wizard process is for.</description>
        <inlineHelpText>The year for the EOY Wizard to process.</inlineHelpText>
        <label>Year</label>
        <referenceTo>Time_Element__c</referenceTo>
        <relationshipLabel>EOY Progresses</relationshipLabel>
        <relationshipName>EOY_Progresses</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>EOY Progress</label>
    <nameField>
        <label>EOY Save State Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>EOY Progresses</pluralLabel>
    <recordTypes>
        <fullName>EOY</fullName>
        <active>true</active>
        <label>EOY</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Picklist_Value__c.object
<CustomObject>
    <fields>
        <fullName>Setup__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Setup</label>
        <referenceTo>Setup__c</referenceTo>
        <relationshipLabel>Picklist Values</relationshipLabel>
        <relationshipName>Picklist_Values</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Attendance</fullName>
                </value>
                <value>
                    <fullName>Time</fullName>
                </value>
                <value>
                    <fullName>Assignment</fullName>
                </value>
                <value>
                    <fullName>Grade Scale</fullName>
                </value>
                <value>
                    <fullName>Homework</fullName>
                </value>
                <value>
                    <fullName>Behavior Type</fullName>
                </value>
                <value>
                    <fullName>Behavior Consequence</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Picklist Value</label>
    <nameField>
        <label>Display Value</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Picklist Values</pluralLabel>
    <recordTypes>
        <fullName>Time</fullName>
        <active>true</active>
        <label>Time</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Setup__c.object
<CustomObject>
    <description>This object is used to setup Schoolforce and is referenced in multiple pieces of code.  There should be one setup object per school.</description>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Is this school setup active for this school year?</inlineHelpText>
        <label>Active?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>New_School_Year__c</fullName>
        <defaultValue>false</defaultValue>
        <label>New School Year</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>School__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>School</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1 OR 2</booleanFilter>
            <filterItems>
                <field>Account.RecordType.Name</field>
                <operation>equals</operation>
                <value>School</value>
            </filterItems>
            <filterItems>
                <field>Account.RecordType.Name</field>
                <operation>equals</operation>
                <value>Summer School</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Setup</relationshipLabel>
        <relationshipName>Setup</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Term__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Term refers to the Term &apos;Template&apos; that the administrator associates to the School; this contains all Semeser/Quarter/Period logic necessary to create Sessions.</description>
        <label>Term</label>
        <referenceTo>Time_Element__c</referenceTo>
        <relationshipLabel>Setup</relationshipLabel>
        <relationshipName>Setup</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Year__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>School Year associated to the Setup</description>
        <label>Year</label>
        <referenceTo>Time_Element__c</referenceTo>
        <relationshipLabel>Setup (Year)</relationshipLabel>
        <relationshipName>Setup_Year</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Setup</label>
    <nameField>
        <displayFormat>S-{0}</displayFormat>
        <label>Setup ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Setup</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/Time_Element__c.object
<CustomObject>
    <fields>
        <fullName>Current__c</fullName>
        <defaultValue>false</defaultValue>
        <description>If this flag is checked, this value is the current years value; will uncheck when new year is created.</description>
        <label>Current</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Date_Start_Date__c</fullName>
        <defaultValue>Today()</defaultValue>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>End_Date__c</fullName>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Name__c</fullName>
        <label>Name</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>New_School_Year__c</fullName>
        <defaultValue>false</defaultValue>
        <label>New School Year</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Picklist_Value__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Picklist Value</label>
        <referenceTo>Picklist_Value__c</referenceTo>
        <relationshipLabel>Time</relationshipLabel>
        <relationshipName>Time</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Previous_Year__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Previous Year</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>School__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>School</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Time</relationshipLabel>
        <relationshipName>Time</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Year</fullName>
                </value>
                <value>
                    <fullName>Semester</fullName>
                </value>
                <value>
                    <fullName>Trimester</fullName>
                </value>
                <value>
                    <fullName>Quarter</fullName>
                </value>
                <value>
                    <fullName>Period</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Time</label>
    <nameField>
        <displayFormat>T-{000000}</displayFormat>
        <label>Time Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Time</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/User.object
<CustomObject>
    <fields>
        <fullName>School__c</fullName>
        <label>School</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

classes/EOYWiz_Landing.cls
public without sharing class EOYWiz_Landing {
/*
    Programmer's notes:
    The objective of this Wizard is to direct the user through a step by step process for the end of year (EOY) school process .
    There is an initial step of providing a setting for an 'Org wide setting'.  In this step the system administrator must provide
    the EOY Purge objects for 1 year and 2 years.  Also in this inital step the user must create the net new next year to allow 
    the addition of students to that year if it has not been done yet through the Setup Wizard.  
    Note that once a new year is created, additional setups are created for all of the Schools
    
    After initial steps there are additional steps to close out each school in the org.  Currently there are approximately 7 steps:
        * Validate the schools gradespan 
        * update the student's promotional status and school enrollment
        * Create net new student records for the new year
        * Create snapshot data
        
    These steps actually are not school dependent, should only validate after the above steps are completed
        * Process EOY Data (also known as deactivate Data)
        * Purge EOY Data
        * Purge Historical Data
            
    Enhancement: Module awareness
    With the addition of the Interventions Module, Development has decided that the EOY Process will generate the EOY Records for other
    Modules as necessary.  The detection Method will be querying for the various 'EOY_Landing' pages within the environment.  These pages should 
    be separated via their NamespacePrefix.  From there EOY_Progress records will be generated as appropriate with the note that a EOY_Landing page 
    with a blank NamespacePrefix should typically be the EOY_Landing page from the non-package version of SchoolForce.  The non-package EOY_Progress 
    version will own a Module_Name__c of 'SchoolForce' as well the as the package version of SchoolForce.
    
    Additional enhancement will be to allow this EOY_Landing page to be more cognizant of Schools created and net new Modules installed mid year.  
    Currently EOY_Progress record generation is a one time ordeal, upon arriving the landing page.  New functionality is to always check first and then 
    create as necessary.
*/
    public Map<ID, Setup__c> schoolToCurrentActiveSetup {get; set;}
    public Map<ID, EOY_Progress__c> schoolToEOYProgress {get; set;}
    public Map<String, EOY_Progress__c> currentOrgProgresses {get; set;}
    public Time_Element__c activeYear {get; set;}
    public Time_Element__c nextYear {get; set;}
    public ID EOYrecordType {get; set;}
    
    //display table
    public List<EOY_Progress__c> dEOYProgress {get; set;}
    
    //only for step 0
    public EOY_Progress__c orgWideProgress {get; set;}
    public Boolean orgWideComplete {get; set;}
	public Boolean schoolEOYComplete {get; set;}
	public Boolean moduleEOYComplete {get; set;}
    public String selectedProgress {get; set;}
    
    public Boolean initializationError {get; set;}

    //constructor
    public EOYWiz_Landing() {
        schooltoCurrentActiveSetup = new Map<ID, Setup__c>();       
        schooltoEOYProgress = new Map<ID, EOY_Progress__c>();
        currentOrgProgresses = new Map<String, EOY_Progress__c>();        
        dEOYProgress = new List<EOY_Progress__c>();

        initializationError = false;
        EOYrecordType = core_SoqlUtils.getRecordTypesBySobject('EOY_Progress__c').get('EOY');
        
        populateYearInformation();
    }
    
    //Org redirects
    public PageReference gotoOrgPurgeSettings() {
        pageReference p = new pageReference('/apex/EOYWiz_OrgPurgeSettings');
        //pass EOY_Progress__c record
        p.getParameters().put('EOY_Progress', (String)orgWideProgress.ID);
        p.setRedirect(true);
        return p;
    }
    
    public pageReference gotoOrgNextSchoolYear() {
        pageReference p = new pageReference('/apex/EOYWiz_OrgNextYear');
        //pass EOY_Progress__c record
        p.getParameters().put('EOY_Progress', (String)orgWideProgress.ID);
        p.setRedirect(true);
        return p;
    }
    
    public pageReference gotoOrgExport() {
        pageReference p = new pageReference('/apex/EOYWiz_OrgExport');
        //pass EOY_Progress__c record
        p.getParameters().put('EOY_Progress', (String)orgWideProgress.ID);
        p.setRedirect(true);
        return p;       
    }
    
    public void setSelectedProgress() {
        selectedProgress = apexPages.currentPage().getParameters().get('selectedProgress');
        system.debug('selectedProgress: ' + selectedProgress);      
    }
    
    public pageReference gotoSchoolGradeSpan() {
        pageReference p = new pageReference('/apex/EOYWiz_SchoolGradeSpan');
        p.getParameters().put('selectedProgress', selectedProgress);
        p.getParameters().put('activeYear', (String)activeYear.ID);
        p.getParameters().put('nextYear', (String)nextYear.ID);
        p.setRedirect(true);
        return p;
    }
    
    public pageReference gotoSchoolStudentPromotional() {
        pageReference p = new pageReference('/apex/EOYWiz_SchoolStudentPromotional');
        p.getParameters().put('selectedProgress', selectedProgress);
        p.getParameters().put('activeYear', (String)activeYear.ID);
        p.getParameters().put('nextYear', (String)nextYear.ID);     
        p.setRedirect(true);
        return p;
    }
    
    public pageReference gotoSchoolNextYearStudents() {
        pageReference p = new pageReference('/apex/EOYWiz_SchoolNextYearStudents');
        p.getParameters().put('selectedProgress', selectedProgress);
        p.getParameters().put('activeYear', (String)activeYear.ID);
        p.getParameters().put('nextYear', (String)nextYear.ID);     
        p.setRedirect(true);
        return p;
    }
    
    public pageReference gotoSchoolSnapshots() {
        pageReference p = new pageReference('/apex/EOYWiz_SchoolSnapshots');
        p.getParameters().put('selectedProgress', selectedProgress);
        p.getParameters().put('activeYear', (String)activeYear.ID);
        p.getParameters().put('nextYear', (String)nextYear.ID);
        p.setRedirect(true);
        return p;
    }
    
    public pageReference gotoSchoolProcessData() {
        pageReference p = new pageReference('/apex/EOYWiz_SchoolProcessData');
        p.getParameters().put('selectedProgress', selectedProgress);
        p.getParameters().put('activeYear', (String)activeYear.ID);
        p.getParameters().put('nextYear', (String)nextYear.ID);     
        p.setRedirect(true);
        return p;
    }
    
    public pageReference gotoSchoolPurgeEOYData() {
        pageReference p = new pageReference('/apex/EOYWiz_SchoolPurgeEOYData');
        p.getParameters().put('selectedProgress', selectedProgress);
        p.getParameters().put('activeYear', (String)activeYear.ID);
        p.getParameters().put('nextYear', (String)nextYear.ID);     
        p.setRedirect(true);
        return p;
    }
    
    public pageReference gotoSchoolPurgeHistoricalData() {
        pageReference p = new pageReference('/apex/EOYWiz_SchoolPurgeHistoricalData');
        p.getParameters().put('selectedProgress', selectedProgress);
        p.getParameters().put('activeYear', (String)activeYear.ID);
        p.getParameters().put('nextYear', (String)nextYear.ID);     
        p.setRedirect(true);
        return p;
    }
    
    //verification and EOY_Progress record generation
    public void orgWideSettingsComplete() {
    	//this getSchoolProgress() is SchoolForce Main Package specific.
    	getSchoolProgress();
    	
        //search for EOY_Progress__c record for the year
        if(!initializationError) {
            try {
            	//updated to look specifically the Org EOY Progress that is SchoolForce or Module_Name__c is null
                for(EOY_Progress__c eoyP : [SELECT ID, EOY_Purge_Settings_Completed__c, EOY_Next_School_Year_Completed__c, Year__r.Name__c, Is_Complete__c, Module_Name__c, Parent_Progress__c FROM EOY_Progress__c WHERE School__c = null AND Year__c =: activeYear.ID AND RecordTypeID =: EOYrecordType AND (Module_Name__c = 'SchoolForce' OR Module_Name__c = null)]) {
                    if(orgWideProgress == null) {
                        orgWideProgress = eoyP;
                    } else {
                    	//DE3252
                        Error_Handling.errorMessage('There are more than one EOY_Progress__c for this year. Please request technical resource to verify the EOY_Progress__c states.');
                    }
                }
                
                //here, check to see if additional Module EOY Progress Records are needed.  Create them here.  Always check to see if there are any that needs to be created. 
                Map<String, EOY_Progress__c> insertOrgProgresses = new Map<String, EOY_Progress__c>();
                
                for(EOY_Progress__c ep : [SELECT ID, Is_Complete__c, Module_Name__c, Parent_Progress__c FROM EOY_Progress__c WHERE (Module_Name__c != 'SchoolForce' AND Module_Name__c != null) AND Year__c =: activeYear.ID]){
                	currentOrgProgresses.put(ep.Module_Name__c, ep);
                }

                //query for the remainder EOY_Landing via ApexPage      
            	for(ApexPage p : [SELECT ID, NamespacePrefix FROM ApexPage WHERE Name = 'EOYWiz_Landing' AND (NamespacePrefix != 'SchoolForce' AND NamespacePrefix != null)]) {
					if(!currentOrgProgresses.containsKey(p.NamespacePrefix) && !String.isBlank(p.NamespacePrefix)) {
						EOY_Progress__c newEP = new EOY_Progress__c();
						newEP.Module_Name__c = p.NamespacePrefix;
						newEP.Parent_Progress__c = orgWideProgress.ID;
						newEP.Year__c = activeYear.ID;
						insertOrgProgresses.put(newEP.Module_Name__c, newEP);
					}
            	}
            	
            	//check to see if there are any Org Progresses to insert
            	if(insertOrgProgresses.size() > 0) {
            		try {
            			insert insertOrgProgresses.Values();
            			//after insertion, place the items in the currentOrgProgresses
            			for(EOY_Progress__c iEP : insertOrgProgresses.Values()) {
            				currentOrgProgresses.put(iEP.Module_Name__c, iEP);
            			}
            		}
            		catch(DMLException d) {
            			ApexPages.addMessage(new apexPages.message(apexPages.Severity.ERROR, 'ERROR Inserting EOY Progress Record for Module: ' + d.getMessage()));
            		}
            	}
            }
            catch(Exception e) {
                Apexpages.addMessage(new apexPages.message(apexPages.severity.ERROR, 'The EOY_Progress__c query must have failed.  Conditional clause: WHERE School__c = null AND Year_Lookup__c =: activeYear.ID'));
            }
            
            //State validation, checks the Org Step 1, Org Step 2, and optional Org Step Export
            try {
            	if(!orgWideProgress.EOY_Purge_Settings_Completed__c || !orgWideProgress.EOY_Next_School_Year_Completed__c) {
            		orgWideComplete = false;
            		apexPages.addMessage(new apexPages.message(apexPages.Severity.WARNING, 'The Org Wide Settings are not completed. Please complete the Org Wide Settings.'));
            		return;
            	}
            	else if(orgWideProgress.EOY_Next_School_Year_Completed__c && nextYear == null) {
            		orgWideComplete = false;
            		apexPages.addMessage(new apexPages.message(apexPages.Severity.ERROR, 'The Org Wide Settings step 2 is complete but the next year is null.  Please verify the Year records.'));
            		return;
            	}
                else if(orgWideProgress.EOY_Purge_Settings_Completed__c && orgWideProgress.EOY_Next_School_Year_Completed__c ) {
                    orgWideComplete = true;
                    if(!orgWideProgress.Is_Complete__c) {
                    	apexPages.addMessage(new apexPages.message(apexPages.Severity.INFO, 'The Org Wide Settings are completed.'));
                    }
                    //verify here if there are null setup records for the school progress.
                    for(EOY_Progress__c e : dEOYProgress) {
                    	if(e.Setup__c != null) {
                    		if(e.Setup__r.Year__c != activeYear.ID) {
                    			apexPages.addMessage(new apexPages.message(apexPages.Severity.WARNING, 'You have not activated a Setup for the current year for one or more schools.  Any school under School Settings Status that has an entirely gray progress bar is impacted.'));
                    			break;
                    		}
                    	}
                    	else {
                    		apexPages.addMessage(new apexPages.message(apexPages.Severity.WARNING, 'You have not activated a Setup for the current year for one or more schools.  Any school under School Settings Status that has an entirely gray progress bar is impacted.'));
                    		break;
                    	}
                    }
                    
                    if(!schoolEOYComplete) {
                    	apexPages.addMessage(new apexPages.message(apexPages.Severity.INFO, 'You have not completed the EOY Process for all of your schools.'));
                    }
                    //school Progresses are complete check module completion
                    else {
                    	moduleEOYComplete = true;
                    	for(EOY_Progress__c ep : currentOrgProgresses.Values()) {
                    		if(!ep.Is_Complete__c) {
                    			moduleEOYComplete = false;
                    			break;
                    		}
                    	}
                    	//final validation check everything:
                    	if(!moduleEOYComplete) {
                    		apexPages.addMessage(new apexPages.message(apexPages.Severity.WARNING, 'You have not completed the EOY Process for all installed modules.'));
                    	}
                    	else {
                    		try {
                    			orgWideProgress.Is_Complete__c = true;
                    			update orgWideProgress;
                    			apexPages.addMessage(new apexPages.message(apexPages.Severity.INFO, 'All school EOY Process is complete. Please activate the next year.'));
                    		}
                    		catch (DMLException d) {
                    			apexPages.addMessage(new apexPages.message(apexPages.Severity.ERROR, 'DML update orgWidePRogress has failed: ' + d.getMessage()));
                    		}
                    	}
                    }
                    
                    return;
                }
            }
            //if it cannot verify the states, that means there are no Org level EOY Records to check against.  Create the main one first in the Catch
            catch(Exception e) {
                //query for EOY_Landing.page
                //been added for the spring 2014 release
                List<EOY_Progress__c> insertProgresses = new List<EOY_Progress__c>();
                
                //create the parent EOY_Progress for all child Modules
                for(ApexPage p : [SELECT ID, NamespacePrefix FROM ApexPage WHERE Name = 'EOYWiz_Landing' AND (NamespacePrefix = 'SchoolForce' OR NamespacePrefix = null)]) {
                	//base case: finds the main schoolforce landing page
                	EOY_Progress__c thisEOYProgress = new EOY_Progress__c(Year__c = activeYear.ID, RecordTypeID = EOYrecordType, Module_Name__c = 'SchoolForce');
                	try {
	                	if(orgWideProgress == null) {
	                		orgWideProgress = thisEOYProgress;
	                		insert thisEOYProgress;
	                	}
	                	else {
	                		apexPages.addMessage(new apexPages.message(apexPages.Severity.ERROR, 'There are more than one Org Wide EOY Progress Record!  Please verify and correct the EOY_Progress__c record for this year.'));
	                	}
                	}
                	catch(DMLException d) {
                		apexPages.addMessage(new apexPages.message(apexPages.Severity.ERROR, 'Org Wide EOY Progress Record failed to insert.'));
                	}
                }
                
				//throw the warning message!
            	apexPages.addMessage(new apexPages.message(apexPages.Severity.WARNING, 'The Org Wide Settings are not completed. Please complete the Org Wide Settings.'));
              	orgWideComplete = false;
                system.debug('*~*~* orgWideProgress: ' + orgWideProgress);  
            } 
        }
    }

    
    private void populateYearInformation() {
        List<Time_Element__c> activeYears = new List<Time_Element__c>();
        List<Time_Element__c> nextYears = new List<Time_Element__c>();
        
        ID rtID = core_SoqlUtils.getRecordTypesBySobject('Picklist_Value__c').get('Time');
        Picklist_Value__c yearPLV = [SELECT ID FROM Picklist_Value__c WHERE Type__c = 'Time' AND Name='Year' AND RecordTypeID =: rtID LIMIT 1];        
        system.debug('yearPLV: ' + yearPLV);
        
        //for(Time_Element__c year : [SELECT ID, Name__c, Date_Start_Date__c, End_Date__c, Current__c, New_School_Year__c FROM Time_Element__c WHERE ((Current__c = true AND New_School_Year__c = false) OR (New_School_Year__c = true AND Current__c = false)) ORDER BY Current__c DESC]) {
        for(Time_Element__c year : [SELECT ID, Name__c, Date_Start_Date__c, End_Date__c, Current__c, New_School_Year__c FROM Time_Element__c WHERE Picklist_Value__c =: yearPLV.ID ORDER BY Current__c DESC]) {
            if(year.Current__c) {
                activeYears.add(year);
                if(activeYears.size() > 1) {
                    Apexpages.addMessage(new apexpages.message(apexpages.severity.ERROR, 'There are multiple years that are marked \'Current\'. Please verify the year time elements'));
                    initializationError = true;
                }
            }   
            
            if(year.New_School_Year__c) {
                nextYears.add(year);
                if(nextYears.size() > 1) {
                    Apexpages.addMessage(new apexpages.message(apexpages.severity.ERROR, 'There are multiple years that are marked \'New School Year\'.  Please verify the year time elements.'));                  
                    initializationError = true;
                }
            }
        }
        
        if(activeYears.size() == 1) {
        	if(activeYears[0].Current__c && activeYears[0].New_School_Year__c) {
        		ApexPages.addMessage(new apexpages.message(apexpages.severity.ERROR, 'Found a year element that is marked \'Current\' and \'New School Year\'.  Please verify the year time elements.'));
        	}
        	else {
            	activeYear = activeYears[0];
        	}
        }
        else if(activeYears.size() == 0) {
            Apexpages.addMessage(new apexpages.message(apexpages.severity.ERROR, 'There are no years that are marked \'Current\'. Please verify the current year.'));
            initializationError = true;
        }
        
        system.debug('nextYears.size(): ' + nextYears.size());
        if(nextYears.size() == 1) {
        	if(nextYears[0].Current__c && nextYears[0].New_School_Year__c) {
        		ApexPages.addMessage(new apexpages.message(apexpages.severity.ERROR, 'Found a year element that is marked \'New School Year\' and \'Current\'.  Please verify the year time elements.'));
        	}
        	else {
            	nextYear = nextYears[0];
        	}
        }
        else if(nextYears.size() == 0) {
            //should warn users to create a net next year! that is part of the process.
        }
    }
    
    //this is called before looking for EOY Org wide records
    
    public void getSchoolProgress() {
        system.debug('getSchoolProgress');
        Map<ID, EOY_Progress__c> updateSchoolProgress = new Map<ID, EOY_Progress__c>();
        //EOY Completion validation
        //true until proven guilty
        schoolEOYComplete = true;
        
        //US3521: modifying to schoolforce to accomdate summer school in EOY process: add to clause Parent = null
        for(Setup__c s : [SELECT ID, School__c, Year__c FROM Setup__c WHERE Active__c = true AND School__r.ParentID = null]) {
            schoolToCurrentActiveSetup.put(s.School__c, s); 
        }
        try {
            for(EOY_Progress__c eoy : [SELECT ID, School__c, School_Grade_Span_Completed__c, School_Student_Promotional_Completed__c, School_Next_Year_Students_Completed__c, School_Snapshots_Completed__c, School_Process_Data_Completed__c, School_Purge_EOY_Data_Completed__c, School_Purge_Historical_Data_Completed__c, Setup__c, Setup__r.Year__c, Year__c FROM EOY_Progress__c WHERE School__c IN: schoolToCurrentActiveSetup.KeySet() AND Year__c =: activeYear.ID AND recordTypeID =: EOYrecordType]){
                if(eoy.Setup__c == null) {
                	if(schoolToCurrentActiveSetup.containsKey(eoy.School__c)) {
                		if(schoolToCurrentActiveSetup.get(eoy.School__c).Year__c == activeYear.ID) {
                			eoy.Setup__c = schoolToCurrentActiveSetup.get(eoy.School__c).ID;
                			updateSchoolProgress.put(eoy.School__c, eoy);
                		}
                	}
                }
                else if(eoy.Setup__c != null) {
                	if(eoy.Setup__r.Year__c != activeYear.ID) {
	                	if(schoolToCurrentActiveSetup.containsKey(eoy.School__c)) {
	                		if(schoolToCurrentActiveSetup.get(eoy.School__c).Year__c == activeYear.ID) {
	                			eoy.Setup__c = schoolToCurrentActiveSetup.get(eoy.School__c).ID;
	                			updateSchoolProgress.put(eoy.School__c, eoy);
	                		}
	                	}
                	}
                }
                
                schoolToEOYProgress.put(eoy.School__c, eoy);
                
                
                //a little late to incorporate the eoy.Is_Complete__c if implemented,
                //then would need to run a script.
                if(!(eoy.School_Grade_Span_Completed__c &&
                    eoy.School_Student_Promotional_Completed__c &&
                    eoy.School_Next_Year_Students_Completed__c &&
                    eoy.School_Snapshots_Completed__c && 
                    eoy.School_Process_Data_Completed__c &&
                    eoy.School_Purge_EOY_Data_Completed__c && 
                    eoy.School_Purge_Historical_Data_Completed__c)){
                     	
					schoolEOYComplete = false;
                } else {
                    eoy.Is_Complete__c = true;
                }
            }
            update updateSchoolProgress.Values();
			
            system.debug('query for EOY Progress');
        }
        catch(Exception e) {
            apexPages.addMessage(new apexPages.message(apexPages.Severity.ERROR, 'ERROR! Failed to find any EOY Progress for schools.'));
        }
        
        
        try {
            //The query result is probably empty, so create the necessary records for those schools and this year.
            List<EOY_Progress__c> newEOYProgress = new List<EOY_Progress__c>();
            
            for(ID school : schoolToCurrentActiveSetup.KeySet()) {
            	
          		if(!schoolToEOYProgress.containsKey(school)) {
                    EOY_Progress__c newEOY = new EOY_Progress__c( Year__c = activeYear.ID,
                                                                  School__c = school,
                                                                  RecordTypeID = EOYrecordType);
                    if(schoolToCurrentActiveSetup.containsKey(school)) {
                    	if(schoolToCurrentActiveSetup.get(school).Year__c == activeYear.ID) {
                    		newEOY.Setup__c = schoolToCurrentActiveSetup.get(school).ID;
                    	}
                    }
                    schoolToEOYProgress.put(school, newEOY);
                    newEOYProgress.add(newEOY);
          		}
            }
            
            if(newEOYProgress.size() > 0) {
            	upsert newEOYProgress;
            }
            system.debug('after insertion');
        }
        catch(Exception e) {
            apexPages.addMessage(new apexPages.message(apexPages.Severity.ERROR, 'ERROR! Failed to insert new EOY Progress for active schools.'));
        }
        
		for(EOY_Progress__c eoy : [SELECT ID, School__c, School_Grade_Span_Completed__c, School_Student_Promotional_Completed__c, School_Next_Year_Students_Completed__c, School_Snapshots_Completed__c, School_Process_Data_Completed__c, School_Purge_EOY_Data_Completed__c, School_Purge_Historical_Data_Completed__c, Setup__c, Setup__r.Year__c, Year__c, Module_Name__c, Parent_Progress__c, Is_Complete__c FROM EOY_Progress__c WHERE School__c IN: schoolToCurrentActiveSetup.KeySet() AND Year__c =: activeYear.ID AND recordTypeID =: EOYrecordType]){
			schoolToEOYProgress.put(eoy.School__c, eoy);
		}
        
        dEOYProgress = schoolToEOYProgress.Values();
    }
    
    public void deactivateCurrentYear() {
        nextYear.New_School_Year__c = false;
        nextYear.Current__c = true;
        update nextYear;
        activeYear.New_School_Year__c = false;
        activeYear.Current__c = false;
        activeYear.Previous_Year__c = true;
        update activeYear;
        
        //call the cleanup batch process
        Batch_EOYDataCleanup cleanupBatch = new Batch_EOYDataCleanup(0);
        Database.executeBatch(cleanupBatch);
    }   
    
    public pageReference redirectToHome() {
        pageReference p = new pageReference('/apex/EOYWiz_Landing');     
        p.setRedirect(true);
        return p;    	
    }
    
}