objects/Account.object
<CustomObject>
    <recordTypes>
        <fullName>State</fullName>
        <active>true</active>
        <description>This record type is for states.</description>
        <label>State</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Data_Load_Log__c.object
<CustomObject>
    <description>Logs information about data loads such as status and success/failure statistics.</description>
    <fields>
        <fullName>Class_Name__c</fullName>
        <label>Class Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>End_Time_Text__c</fullName>
        <description>text representation of the end time field</description>
        <label>End Time Text</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>End_Time__c</fullName>
        <description>Date/time this load finished processing.</description>
        <label>End Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Failed_Records__c</fullName>
        <description>Number of failed records.</description>
        <label>Failed Records</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Messages__c</fullName>
        <description>Any messages generated during the load.</description>
        <label>Messages</label>
        <length>32000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Reporting_Period__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>the reporting period that created this data load log</description>
        <label>Reporting Period</label>
        <referenceTo>Time_Element__c</referenceTo>
        <relationshipLabel>Data Load Log</relationshipLabel>
        <relationshipName>Data_Load_Log</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Setup__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>the setup object whose publish created this data load log</description>
        <label>Setup</label>
        <referenceTo>Setup__c</referenceTo>
        <relationshipLabel>Data Load Log</relationshipLabel>
        <relationshipName>Data_Load_Log</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Status of this data load.</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Pending</fullName>
                </value>
                <value>
                    <fullName>Running</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Total_Records__c</fullName>
        <description>Total number of records processed.</description>
        <label>Total Records</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <description>Type of data loaded.</description>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Section</fullName>
                </value>
                <value>
                    <fullName>Session</fullName>
                </value>
                <value>
                    <fullName>Staff</fullName>
                </value>
                <value>
                    <fullName>Staff/Section</fullName>
                </value>
                <value>
                    <fullName>Student</fullName>
                </value>
                <value>
                    <fullName>Student/Section</fullName>
                </value>
                <value>
                    <fullName>Interventions Data Deactivation</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Data Load Log</label>
    <nameField>
        <displayFormat>DLL-{0000000}</displayFormat>
        <label>Data Load Log #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Data Load Log</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Global_Error__c.object
<CustomObject>
    <label>Global Error</label>
    <nameField>
        <label>Global Error Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Global Errors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Setup__c.object
<CustomObject>
    <description>This object is used to setup Schoolforce and is referenced in multiple pieces of code.  There should be one setup object per school.</description>
    <fields>
        <fullName>School__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>School</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1 OR 2</booleanFilter>
            <filterItems>
                <field>Account.RecordType.Name</field>
                <operation>equals</operation>
                <value>School</value>
            </filterItems>
            <filterItems>
                <field>Account.RecordType.Name</field>
                <operation>equals</operation>
                <value>Summer School</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Setup</relationshipLabel>
        <relationshipName>Setup</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Setup</label>
    <nameField>
        <displayFormat>S-{0}</displayFormat>
        <label>Setup ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Setup</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

classes/SchoolSetup_Staff.cls
public with sharing class SchoolSetup_Staff {
	public Id setupId					{get;set;}
	public String schoolName			{get;set;}
	public Setup__c setup				{get;set;}
	public boolean bProcessing			{get;set;}
	public boolean isManaged			{get;set;}
	public BatchWrapper batch			{get;set;}
	public List<Data_Load_Log__c> logs	{get;set;}
	
	public SchoolSetup_Staff(){
		bProcessing = true;
		isManaged = Schema.SObjectType.Setup__c.getName().replace('__c', '').contains('__');
		if(System.currentPageReference().getParameters().containsKey('setupid')){
			setupId = System.currentPageReference().getParameters().get('setupid');
			if(setupId!=null){
				if(System.currentPageReference().getParameters().get('failed') != null){
					Error_Handling.errorMessage('One or more records has failed to publish. Review the holding object for the errors. See SchoolForce Help for information about troubleshooting failures.');
				}
				setup = SetupWizard_Utils.getSetupById(setupId);
				schoolName = setup.School__r.Name;
				loadLogs();
			}
			else SetupWizard_Utils.addMessage(apexpages.severity.ERROR,SetupWizard_Utils.NO_SETUP_MESSAGE);
		}
		else SetupWizard_Utils.addMessage(apexpages.severity.ERROR,SetupWizard_Utils.NO_SETUP_MESSAGE);
	}

	public void loadLogs(){
		logs = [SELECT id, OwnerId, LastModifiedDate, End_Time_Text__c, Type__c, Status__c, Failed_Records__c, Messages__c, Total_Records__c, Reporting_Period__c 
				FROM Data_Load_Log__c
				WHERE Setup__c = :setupId
				AND Class_Name__c ='CT_Scheduler_HoldingProcessor'
				and Type__c != 'Session'
				ORDER BY End_Time__c DESC];
	}

	public void publishData(){
		try{
			bProcessing = true;
			CT_Scheduler_HoldingProcessor shp = new CT_Scheduler_HoldingProcessor();
			shp.continueBatch = true;
			shp.cSetup = core_SoqlUtils.getSetupById(setupId);//new core_SetupWrapper(core_SoqlUtils.getSetupById(setupId),'publish');
			shp.mode = 'Staff';
			Id batchId = database.executeBatch(shp);
			batch = new BatchWrapper(batchId,setupId);
			continueBatch();
		}
		catch(Exception e){
			ApexPages.addMessage(new apexpages.message(apexpages.severity.ERROR, 'A processing error has occurred.'));
			Global_Error__c ge = Error_Handling.handleError('Setup, '+setupId, 'Core (Publish)', 'error during staff propagation', e);
			insert ge;
		}	 	
	}
	
	public PageReference continueBatch(){
		try{
			boolean failed = batch.continueBatch();
			loadLogs();
			if(failed!=null){
				//bit of hard coding, but it overcomes the publisher not correctly reporting it's failure state.
				if(logs.size()>=2){
					if((logs[0].Failed_Records__c != null && logs[0].Failed_Records__c >0) ||
						(logs[1].Failed_Records__c != null && logs[1].Failed_Records__c >0)){
						failed = true;
					}
				}
				
				return SetupWizard_Utils.refreshPage(setupId,failed);
			}
		}
		catch(Exception e){
			ApexPages.addMessage(new apexpages.message(apexpages.severity.ERROR, 'There was an error while checking the status of the batch.'));
			Global_Error__c ge = Error_Handling.handleError('Setup, '+setupId+'; Batch, '+batch.batchId, 'Core (Publish)', 'batch check failed', e);
			insert ge;
		}
		return null;
	}

	public PageReference prev(){
		Integer location = SetupWizard_Utils.calculateStepLocation(setupId);
		if(location >= SetupWizard_Utils.STAFF)
			return SetupWizard_Utils.goToSchoolStep(SetupWizard_Utils.ROOMS,false,SetupWizard_Utils.getSetupById(setupId));
		else {
			SetupWizard_Utils.addMessage(apexpages.severity.ERROR,SetupWizard_Utils.NO_FORWARD_MESSAGE);
			return null;
		}
	}
	
	public PageReference next(){
		Integer location = SetupWizard_Utils.calculateStepLocation(setupId);
		if(location >= SetupWizard_Utils.STAFF)
			return SetupWizard_Utils.goToSchoolStep(SetupWizard_Utils.GROUP_CONFIG,true,SetupWizard_Utils.getSetupById(setupId));
		else {
			SetupWizard_Utils.addMessage(apexpages.severity.ERROR,SetupWizard_Utils.NO_FORWARD_MESSAGE);
			return null;
		}
	}
}