objects/Account.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <label>Active</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>No</fullName>
                </value>
                <value>
                    <fullName>Yes</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Is_Active__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Is Active?</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>true</defaultValue>
        <inlineHelpText>Schools/organizations can choose to use this field when a Contact record is active. When Contact records are created through SchoolForce Setup, this check box is selected.</inlineHelpText>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Is_Active__c</fullName>
        <defaultValue>true</defaultValue>
        <inlineHelpText>Do not use this field; it is no longer used by SchoolForce.</inlineHelpText>
        <label>Is Active? *Retired*</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Student__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>This field provides a link to the most recent Student record.</inlineHelpText>
        <label>Student</label>
        <referenceTo>Student__c</referenceTo>
        <relationshipLabel>Contacts</relationshipLabel>
        <relationshipName>Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Displays the lookup to the User record.  Staff must have a User record in this field to interact with SchoolForce.</inlineHelpText>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>User</relationshipName>
        <type>Lookup</type>
    </fields>
    <recordTypes>
        <fullName>Staff</fullName>
        <active>true</active>
        <description>This record type is for staff members.</description>
        <label>Staff</label>
    </recordTypes>
    <recordTypes>
        <fullName>Student</fullName>
        <active>true</active>
        <description>This record type is for students</description>
        <label>Student</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Data_Load_Log__c.object
<CustomObject>
    <description>Logs information about data loads such as status and success/failure statistics.</description>
    <fields>
        <fullName>Batch_ID__c</fullName>
        <description>This is the id of the batch that the Data Load Log was created for</description>
        <label>Batch ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Class_Name__c</fullName>
        <label>Class Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>End_Time_Text__c</fullName>
        <description>text representation of the end time field</description>
        <label>End Time Text</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>End_Time__c</fullName>
        <description>Date/time this load finished processing.</description>
        <label>End Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Messages__c</fullName>
        <description>Any messages generated during the load.</description>
        <label>Messages</label>
        <length>32000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Start_Time_Text__c</fullName>
        <description>text representation of the start time field</description>
        <label>Start Time Text</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Start_Time__c</fullName>
        <description>Date/time this load was started.</description>
        <label>Start Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Status of this data load.</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Pending</fullName>
                </value>
                <value>
                    <fullName>Running</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Data Load Log</label>
    <nameField>
        <displayFormat>DLL-{0000000}</displayFormat>
        <label>Data Load Log #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Data Load Log</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Section__c.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Check this box if the section is a currently active section</description>
        <inlineHelpText>Check this box if the section is a currently active section</inlineHelpText>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>School__c</fullName>
        <label>School</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Sections</relationshipLabel>
        <relationshipName>Sections</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Section__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Recursive lookup for groups</description>
        <label>Section</label>
        <referenceTo>Section__c</referenceTo>
        <relationshipLabel>Groups in Section</relationshipLabel>
        <relationshipName>Sections1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Staff__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Staff</label>
        <referenceTo>Staff__c</referenceTo>
        <relationshipLabel>Sections</relationshipLabel>
        <relationshipName>Sections</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Section</label>
    <nameField>
        <label>Section Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sections</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/SharingControls__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Controls what users will have the sharing run</description>
    <fields>
        <fullName>Profile_Name__c</fullName>
        <description>Profile name must contain this text for these users to have sharing recalculated.  For instance, if Profile Name = &apos;Corps Member&apos;, sharing will be recalculated for &apos;NEW Corps Member&apos;, &apos;Corps Member OLD&apos;, etc.</description>
        <label>Profile Name</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Sharing Controls</label>
</CustomObject>

objects/Staff__c.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Individual__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Individual</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Staff</relationshipLabel>
        <relationshipName>Staff</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Is_Active__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Active?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Organization__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Staff Member&apos;s employer</description>
        <label>Organization</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Staff</relationshipLabel>
        <relationshipName>Staff</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Supervisor__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Supervisor</label>
        <referenceTo>Staff__c</referenceTo>
        <relationshipLabel>Staff</relationshipLabel>
        <relationshipName>Staff</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Staff</label>
    <nameField>
        <label>Staff Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Staff</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/Staff_Section__c.object
<CustomObject>
    <fields>
        <fullName>Is_Active__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Is Active?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Section__c</fullName>
        <label>Section</label>
        <referenceTo>Section__c</referenceTo>
        <relationshipLabel>Staff</relationshipLabel>
        <relationshipName>Staff_Section</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Staff__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Staff</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Staff__c.Organization__r.Id</field>
                <operation>equals</operation>
                <valueField>$Source.Account__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Staff__c</referenceTo>
        <relationshipLabel>Sections</relationshipLabel>
        <relationshipName>Staff_Section</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Staff/Section</label>
    <nameField>
        <displayFormat>SfS-{000000}</displayFormat>
        <label>Staff/Section ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Staff/Section</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Student__c.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>true</defaultValue>
        <inlineHelpText>Indicates whether or not this Student record is active. If checked, then this is the current Student record. If unchecked, this is an old Student record.</inlineHelpText>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Individual__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Displays the name for the Contact record associated to this Student record. You can click the link to view the student&apos;s Contact record.</inlineHelpText>
        <label>Individual Record</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Student Records</relationshipLabel>
        <relationshipName>Students</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Is_Active__c</fullName>
        <defaultValue>true</defaultValue>
        <inlineHelpText>Do not use this field; it is no longer used by SchoolForce.</inlineHelpText>
        <label>Is Active?*Retired*</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Section__c</fullName>
        <inlineHelpText>Displays the student&apos;s current homeroom name or room number. This field can be used for reporting purposes.</inlineHelpText>
        <label>Current Homeroom</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Staff__c</fullName>
        <inlineHelpText>Displays the name of the student&apos;s homeroom teacher.  You can use this field for reporting purposes.</inlineHelpText>
        <label>Current Homeroom Teacher</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Student__c</fullName>
        <inlineHelpText>Displays the student&apos;s middle name.</inlineHelpText>
        <label>Student Middle Name</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <label>Student</label>
    <nameField>
        <label>Student Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Students</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Student_Section__c.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Section__c</fullName>
        <label>Section</label>
        <referenceTo>Section__c</referenceTo>
        <relationshipLabel>Student</relationshipLabel>
        <relationshipName>Student_Section</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Student__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Student</label>
        <referenceTo>Student__c</referenceTo>
        <relationshipLabel>Section</relationshipLabel>
        <relationshipName>Student_Section</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Student/Section</label>
    <nameField>
        <displayFormat>SS-{000000}</displayFormat>
        <label>Student/Section ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Student/Section</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/CYSharingRecalculator.cls
global class CYSharingRecalculator{/* implements Database.Batchable<SObject> {
	global static boolean hasBeenScheduled = false;
	global String query = 'SELECT id, Profile.Name FROM User WHERE IsActive=true and Profile.UserType!= \'CSPLitePortal\'';
	global boolean useLog = false;
	
	global CYSharingRecalculator(){
		
	}
	
	global CYSharingRecalculator(boolean bUseLog){
		useLog = bUseLog;
	}
	
	global Iterable<sObject> start(Database.BatchableContext bc) {
		if(useLog){
			List<Data_Load_Log__c> logs = SharingUtils.getAllLogs('Pending');
			Set<String> userIDs = new Set<String>();
			if(logs != null && !logs.isEmpty()){
				for(Data_Load_Log__c dll: logs){
					if(!String.isBlank(dll.Messages__c)){
						userIDs.addAll(dll.Messages__c.split(','));
						dll.Status__c = 'Running';
						dll.Start_Time__c = System.now();
						dll.Start_Time_Text__c = System.now().format('MM/dd/yyyy hh:mm a');
						dll.Batch_ID__c=BC.getJobId();
						dll.Class_Name__c = 'CYSharingRecalculator';
					}
				}
			}

			if(logs == null || logs.isEmpty() || userIDs.isEmpty()){
				System.abortJob(BC.getJobId());
				if(logs == null && !Test.isRunningTest())
					SharingUtils.rescheduleBatch();
				return null;
			} else {
				query += updateQuery(' AND Id IN (',',','\'','\'', new List<String>(userIDs));
			}
			
			
			update logs;
		}

		Map<String,SharingControls__c> controls = SharingControls__c.getAll();
		if(controls.size()!=0){
			List<String> profiles = new List<String>();
			for(SharingControls__c sc: controls.values()) profiles.add(sc.Profile_Name__c);
			query += updateQuery(' AND (',' OR ','Profile.Name LIKE \'%','%\'',profiles);
		}

		if(Test.isRunningTest()){
			query += ' limit 1';
		}
		system.debug('query: ' +query);
		return Database.query(query);
	}
	
	global void execute(Database.BatchableContext bc, List<sObject> batch){
		List<User> users = (List<User>) batch;
		Set<ID> cmUsers = new Set<ID>();
		Set<ID> saUsers = new Set<ID>();
		Map<String,SharingControls__c> controls = SharingControls__c.getAll();
		Set<ID> userIDs = new Set<ID>();
		for(User u: users){
			userIDs.add(u.id);
			//I hate hardcoding but whatever
			if(controls.containsKey('CM')) if(u.Profile.Name.contains(controls.get('CM').Profile_Name__c)) cmUsers.add(u.id);
			if(controls.containsKey('SA')) if(u.Profile.Name.contains(controls.get('SA').Profile_Name__c)) saUsers.add(u.id);
		}
		List<Student__Share> newStudentShares = new List<Student__Share>();
		List<Section__Share> newSectionShares = new List<Section__Share>();
		Map<ID,Map<ID,ID>> existingSharingRules = SharingUtils.getExistingSharing(userIDs);
		calculateCMSharing(cmUsers, newStudentShares, newSectionShares, existingSharingRules);
		calculateSchoolAdminSharing(saUsers, newStudentShares, newSectionShares, existingSharingRules);
		insert newStudentShares;
		insert newSectionShares;
		SharingUtils.deleteRemainingRules(SharingUtils.getIDsToDelete(existingSharingRules));
	}
	
	global void finish(Database.BatchableContext bc){
		try {
			Data_Load_Log__c dll = [SELECT id FROM Data_Load_Log__c WHERE Batch_Id__c=:BC.getJobId() LIMIT 1 FOR UPDATE];
			dll.Status__c = 'Completed';
			dll.End_Time__c = System.now();
			dll.End_Time_Text__c = System.now().format('MM/dd/yyyy hh:mm a');
			update dll;
		} catch (Exception e){ }
	}
	
	global String updateQuery(String startString, String separator, String beginString, String endString, List<String> addStrings){
		
		String newQuery = startString;
		boolean init = true;
		for(String newString: addStrings){
			if(!init) newQuery += separator;
			newQuery += beginString;
			newQuery += newString;
			newQuery += endString;
			init = false;
		}
		newQuery += ')';
		return newQuery;
	}
	
	global void calculateCMSharing(Set<ID> userIDs, List<Student__Share> studentShares, List<Section__Share> sectionShares, Map<ID,Map<ID,ID>> existingSharingRules){
		Map<ID,Set<ID>> sectionToStaff = new Map<ID,Set<ID>>();
		for(Staff_Section__c ss: [SELECT id, Staff__r.Individual__r.User__r.Id, Section__c FROM Staff_Section__c WHERE Staff__r.Individual__r.User__r.Id IN :userIDs AND Is_Active__c=true]){
			ID user = ss.Staff__r.Individual__r.User__r.Id;
			if(!sectionToStaff.containsKey(ss.Section__c))
				sectionToStaff.put(ss.Section__c, new Set<ID>{user});
			else
				sectionToStaff.get(ss.Section__c).add(user);
			//create section shares
			ID share = getExistingShare(user, ss.Section__c, existingSharingRules);
			//if no share exists, create one
			if(share==null) sectionShares.add(SharingUtils.createSectionShare(user, ss.Section__c));
		}
		
		for(Student_Section__c ss: [SELECT id, Student__c, Section__c FROM Student_Section__c WHERE Section__c IN :sectionToStaff.keySet() AND Active__c=true]){
			for(ID user: sectionToStaff.get(ss.Section__c)){
				//create student share
				ID share = getExistingShare(user, ss.Student__c, existingSharingRules);
				//if no share exists, create one
				if(share==null) studentShares.add(SharingUtils.createStudentShare(user, ss.Student__c));
			}
		}
	}
	
	global void calculateSchoolAdminSharing(Set<ID> userIDs, List<Student__Share> studentShares, List<Section__Share> sectionShares, Map<ID,Map<ID,ID>> existingSharingRules){
		Map<ID,Set<ID>> schoolToUsers = new Map<ID,Set<ID>>();
		for(Staff__c staff: [SELECT id, Organization__c, Individual__r.User__r.Id FROM Staff__c WHERE Individual__r.User__r.Id IN :userIDs AND Active__c=true]){
			if(!schoolToUsers.containsKey(staff.Organization__c))
				schoolToUsers.put(staff.Organization__c, new Set<ID>{staff.Individual__r.User__r.Id});
			else
				schoolToUsers.get(staff.Organization__c).add(staff.Individual__r.User__r.Id);
		}

		//added territory share 15.06.2017
		Map<Id, Set<Id>> mapTerritory2School = new Map<Id, Set<Id>>();
		for(ObjectTerritory2Association ota: [SELECT Id, AssociationCause, IsDeleted, ObjectId, SobjectType, Territory2Id FROM ObjectTerritory2Association WHERE Object.Type = 'Account' AND ObjectId IN :schoolToUsers.keySet()]){
			System.debug('@@@ ota: '+ota);
			if(!mapTerritory2School.containsKey(ota.Territory2Id)){
				mapTerritory2School.put(ota.Territory2Id, new Set<Id>());
			}
			mapTerritory2School.get(ota.Territory2Id).add(ota.ObjectId);
		}

		for(UserTerritory2Association uta: [SELECT IsActive, RoleInTerritory2, Territory2Id, UserId FROM UserTerritory2Association WHERE Territory2Id IN :mapTerritory2School.keySet()]){
			System.debug('@@@ uta: '+uta);
			for(Id schoolId: mapTerritory2School.get(uta.Territory2Id)){
				if(!schoolToUsers.containsKey(schoolId)){
					schoolToUsers.put(schoolId, new Set<Id>());
				}
				schoolToUsers.get(schoolId).add(uta.UserId);
			}
		}
		//end territory
		
		for(Student__c student: [SELECT id, School__c FROM Student__c WHERE School__c IN :schoolToUsers.keySet()]){
			for(ID user: schoolToUsers.get(student.School__c)){
				ID share = getExistingShare(user, student.id, existingSharingRules);
				//if no share exists, create one
				if(share==null) studentShares.add(SharingUtils.createStudentShare(user, student.id));
			}
		}
		
		for(Section__c section: [SELECT id, School__c FROM Section__c WHERE School__c IN :schoolToUsers.keySet()]){
			for(ID user: schoolToUsers.get(section.School__c)){
				ID share = getExistingShare(user, section.id, existingSharingRules);
				//if no share exists, create one
				if(share==null) sectionShares.add(SharingUtils.createSectionShare(user, section.id));
			}
		}
	}
	
	global ID getExistingShare(ID user, ID shareRecord, Map<ID,Map<ID,ID>> existingSharingRules){
		Map<ID,ID> temp = existingSharingRules.get(user);
		ID share;
		//remove share if it's valid
		//all invalid sharing rules will remain and be deleted at the end of the batch
		if(temp!=null) share = temp.remove(shareRecord);
		existingSharingRules.put(user,temp);
		return share;
	}
	*/
}