objects/Account.object
<CustomObject>
    <recordTypes>
        <fullName>School</fullName>
        <active>true</active>
        <description>This record type is for physical school locations.</description>
        <label>School</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/EOY_Progress__c.object
<CustomObject>
    <description>This object is used to determine the current completion progress in the EOY Wizard.</description>
    <fields>
        <fullName>School_Grade_Span_Completed__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Select the grade span for the school.</description>
        <inlineHelpText>This will be checked when the grade span has been confirmed for the next school year.</inlineHelpText>
        <label>School Grade Span Completed</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>School_Grade_Span_Last_Modified__c</fullName>
        <description>To keep track of the individual who last modified, the time, and the date.</description>
        <inlineHelpText>Last user to modify and the time.</inlineHelpText>
        <label>School Grade Span Last Modified</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>School__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field is required to keep track of the EOY progression for a school.</description>
        <inlineHelpText>This field is required for EOY Progression on schools.</inlineHelpText>
        <label>School</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>EOY Progresses</relationshipLabel>
        <relationshipName>EOY_Progresses</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Setup__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Look up to the setup record, since a setup represents an active configuration for a school.</description>
        <inlineHelpText>Determine the progress for an active setup to a school.</inlineHelpText>
        <label>Setup</label>
        <referenceTo>Setup__c</referenceTo>
        <relationshipLabel>EOY Progresses</relationshipLabel>
        <relationshipName>EOY_Progresses</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Year__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>The year that the EOY Wizard process is for.</description>
        <inlineHelpText>The year for the EOY Wizard to process.</inlineHelpText>
        <label>Year</label>
        <referenceTo>Time_Element__c</referenceTo>
        <relationshipLabel>EOY Progresses</relationshipLabel>
        <relationshipName>EOY_Progresses</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>EOY Progress</label>
    <nameField>
        <label>EOY Save State Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>EOY Progresses</pluralLabel>
    <recordTypes>
        <fullName>EOY</fullName>
        <active>true</active>
        <label>EOY</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Setup__c.object
<CustomObject>
    <description>This object is used to setup Schoolforce and is referenced in multiple pieces of code.  There should be one setup object per school.</description>
    <fields>
        <fullName>Grade_Span__c</fullName>
        <description>Used to identify which grades are taught in a given school/setup. Because it&apos;s tied to the setup record it can change year-to year</description>
        <inlineHelpText>Select the grade level(s) that will be taught at this school in the current school year.</inlineHelpText>
        <label>Grade Span</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>PS</fullName>
                </value>
                <value>
                    <fullName>PK</fullName>
                </value>
                <value>
                    <fullName>PK-3</fullName>
                </value>
                <value>
                    <fullName>PK-4</fullName>
                </value>
                <value>
                    <fullName>PK Pre-K</fullName>
                </value>
                <value>
                    <fullName>Kindergarten/Preschool</fullName>
                </value>
                <value>
                    <fullName>KG Kindergarten</fullName>
                </value>
                <value>
                    <fullName>PG Postgraduate/Adult</fullName>
                </value>
                <value>
                    <fullName>Kindergarten</fullName>
                </value>
                <value>
                    <fullName>K</fullName>
                </value>
                <value>
                    <fullName>1</fullName>
                </value>
                <value>
                    <fullName>2</fullName>
                </value>
                <value>
                    <fullName>3</fullName>
                </value>
                <value>
                    <fullName>4</fullName>
                </value>
                <value>
                    <fullName>5</fullName>
                </value>
                <value>
                    <fullName>6</fullName>
                </value>
                <value>
                    <fullName>7</fullName>
                </value>
                <value>
                    <fullName>8</fullName>
                </value>
                <value>
                    <fullName>9</fullName>
                </value>
                <value>
                    <fullName>10</fullName>
                </value>
                <value>
                    <fullName>11</fullName>
                </value>
                <value>
                    <fullName>12</fullName>
                </value>
                <value>
                    <fullName>UN Ungraded</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>New_School_Year__c</fullName>
        <defaultValue>false</defaultValue>
        <label>New School Year</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>School__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>School</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1 OR 2</booleanFilter>
            <filterItems>
                <field>Account.RecordType.Name</field>
                <operation>equals</operation>
                <value>School</value>
            </filterItems>
            <filterItems>
                <field>Account.RecordType.Name</field>
                <operation>equals</operation>
                <value>Summer School</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Setup</relationshipLabel>
        <relationshipName>Setup</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Year__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>School Year associated to the Setup</description>
        <label>Year</label>
        <referenceTo>Time_Element__c</referenceTo>
        <relationshipLabel>Setup (Year)</relationshipLabel>
        <relationshipName>Setup_Year</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Setup</label>
    <nameField>
        <displayFormat>S-{0}</displayFormat>
        <label>Setup ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Setup</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/Time_Element__c.object
<CustomObject>
    <fields>
        <fullName>Current__c</fullName>
        <defaultValue>false</defaultValue>
        <description>If this flag is checked, this value is the current years value; will uncheck when new year is created.</description>
        <label>Current</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Date_Start_Date__c</fullName>
        <defaultValue>Today()</defaultValue>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>End_Date__c</fullName>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Grade_Span__c</fullName>
        <label>Grade Span</label>
        <length>180</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Name__c</fullName>
        <label>Name</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>New_School_Year__c</fullName>
        <defaultValue>false</defaultValue>
        <label>New School Year</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>School__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>School</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Time</relationshipLabel>
        <relationshipName>Time</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Time</label>
    <nameField>
        <displayFormat>T-{000000}</displayFormat>
        <label>Time Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Time</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/User.object
<CustomObject>
    <fields>
        <fullName>School__c</fullName>
        <label>School</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

classes/EOYWiz_SchoolGradeSpan.cls
public with sharing class EOYWiz_SchoolGradeSpan {
    
    //School Progress
    public EOY_Progress__c schoolProgress {get; set;}
    public String EOYID {get; set;}
    public ID EOYrecordType {get; set;}
    
    //specifically for School Step 1
    public Time_Element__c activeYear {get; set;}
    public Time_Element__c nextYear {get; set;}
    
    public Setup__c activeSetup {get; set;}
    public Setup__c nextSetup {get; set;}
    
    //used to check for changes in grade span
    public Boolean unsaved {get; set;}
    public String currentNextGradeSpan {get; set;}
    
    public static String warning1 = 'The grade span has been edited. Please save when you are done.';
    public static String warning2 = 'The grade span is not finalized for the next school year.';
    public static String error1 = 'Error! Failed to update the grade span for the next school year.';
    public static String success1 = 'Success! The grade span for the next school year is updated.';
    public static String success2 = 'Success! The grade span for the next school year is finalized.';
    
    public EOYWiz_SchoolGradeSpan() {
        schoolProgress = new EOY_Progress__c();
        EOYID = '';
        
        activeYear = new Time_Element__c();
        nextYear = new Time_Element__c();
        
        activeSetup = new Setup__c();
        nextSetup = new Setup__c();
        
        unsaved = false;
        currentNextGradeSpan = '';
        EOYrecordType = core_SoqlUtils.getRecordTypesBySobject('EOY_Progress__c').get('EOY');
        initialize();
    }
    
    private void initialize() {
        populateYearInformation();
        getSchoolProgress();
        getSchoolSetups();
        
        if(!schoolProgress.School_Grade_Span_Completed__c) {
            apexPages.addMessage(new apexPages.message(apexPages.severity.WARNING, warning2));
        }       
    }
    
    public pageReference gotoEOYLandingPage() {
        pageReference p = new pageReference('/apex/EOYWiz_Landing');
        p.setRedirect(true);
        return p;
    }
    
    public pageReference gotoSchoolStudentPromotional() {
        pageReference p = new pageReference('/apex/EOYWiz_SchoolStudentPromotional');
        p.getParameters().put('selectedProgress', EOYID);
        p.getParameters().put('activeYear', (String)activeYear.ID);
        p.getParameters().put('nextYear', (String)nextYear.ID);
        p.setRedirect(true);
        return p;
    }   
    
    public void editNextGradeSpan() {
        if(currentNextGradeSpan != nextSetup.grade_span__c) {
            apexPages.addMessage(new apexPages.message(apexPages.severity.WARNING, warning1));
            unsaved = true;
        }
        else {
            apexPages.addMessage(new apexPages.message(apexPages.severity.WARNING, warning2));
            unsaved = false;
        }
    }
    
    public Boolean saveFunction() {
        Database.upsertResult results;
        
        try {
            system.debug('before Upserting: ' + nextSetup);
            results = Database.upsert(nextSetup);   
        }
        catch(Exception e) {
            apexPages.addMessage(new apexPages.message(apexPages.severity.FATAL, error1));
        }
        
        Boolean successFlag = true;
        if(results != null) {
            if(!results.isSuccess()) {
                if(successFlag) {
                    successFlag = false;
                }
                Database.Error[] errs = results.getErrors();
                for(Database.Error err : errs) {
                    system.debug(err.getStatusCode() + ' - ' + err.getMessage());
                }
            }
        }
        return successFlag;    	
    }
    
    public void saveNextSetup() {
        if(saveFunction()) {
            apexPages.addMessage(new apexPages.message(apexPages.Severity.INFO, success1));
        }
        
        setLastModified();
        unsaved = false;
    }   
    
    public void finalizeNextSetup() {
        if(nextSetup.grade_span__c != null) {
            schoolProgress.School_Grade_Span_Completed__c = true;
            //saveNextSetup();
        	if(saveFunction()) {
        		apexPages.addMessage(new apexPages.message(apexPages.Severity.INFO, success2));
        	}
        	setLastModified();
        	unsaved = false;
        }
        else {
            apexPages.addMessage(new apexPages.message(apexPages.Severity.ERROR, 'Error! The grade span is not acceptable.'));
        }
    }
    
    public void setLastModified() {
        user u = [SELECT ID, Name FROM User WHERE ID =: UserInfo.getUserID() LIMIT 1];
        String timeZone = UserInfo.getTimeZone().getID();
        schoolProgress.School_Grade_Span_Last_Modified__c = u.Name + ' ' + dateTime.now().format('MM/dd/yyyy hh:mm:ss a', timeZone);
        upsert schoolProgress;
        getSchoolProgress();
        getSchoolSetups();
    }
    
    public void getSchoolProgress() {
        EOYID = apexPages.currentPage().getParameters().get('selectedProgress');        
        if(EOYID != null || EOYID != '') {
            system.debug('eoyID: ' + EOYID);
            schoolProgress = [SELECT ID, School_Grade_Span_Completed__c, School_Grade_Span_Last_Modified__c, School__c, School__r.Name, Setup__c FROM EOY_Progress__c WHERE ID =: EOYID AND Year__c =: activeYear.ID AND RecordTypeID =: EOYrecordType];
        }
        else {
            //should display an error message here
        }
    }
    
    private void populateYearInformation() {
        String activeYearID = apexPages.currentPage().getParameters().get('activeYear');
        String nextYEarID = apexPages.currentPage().getParameters().get('nextYear');
        
        for(Time_Element__c y : [SELECT ID, Name__c, Date_Start_Date__c, End_Date__c, Current__c, New_School_Year__c FROM Time_Element__c WHERE ID =: activeYearID OR ID =: nextYearID]) {
            if(y.Current__c) {
                activeYear = y;
            }
            else if(y.New_School_Year__c) {
                nextYear = y;
            }
        }
    }   
    
    private void getSchoolSetups() {
        try {
            activeSetup = [SELECT ID, Grade_Span__c, Year__c, Year__r.Name__c, School__c, School__r.Name FROM Setup__c WHERE ID =: schoolProgress.Setup__c];
            nextSetup = [SELECT ID, Grade_Span__c, Year__c, Year__r.Name__c, School__c, School__r.Name FROM Setup__c WHERE Year__c =: nextYear.ID AND School__c =: schoolProgress.School__c];
        }
        catch(Exception e) {
            apexPages.addMessage(new apexPages.message(apexPages.Severity.ERROR, 'Error! Failed to get school setups.'));
        }
        
        /*
        for(String g : nextSetup.Grade_Span__c.split(',')) {
            currentNextGradeSpan.add(g);
            system.debug('currentNextGradeSpan: ' + currentNextGradeSpan);
        }
        */
        currentNextGradeSpan = nextSetup.Grade_Span__c;
    }
}