objects/Account.object
<CustomObject>
    <recordTypes>
        <fullName>School</fullName>
        <active>true</active>
        <description>This record type is for physical school locations.</description>
        <label>School</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Schedule_Template__c.object
<CustomObject>
    <fields>
        <fullName>Reporting_Period__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Reporting Period</label>
        <referenceTo>Time_Element__c</referenceTo>
        <relationshipLabel>Schedule Templates</relationshipLabel>
        <relationshipName>Schedule_Templates</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Setup__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Setup</label>
        <referenceTo>Setup__c</referenceTo>
        <relationshipLabel>Schedule Templates</relationshipLabel>
        <relationshipName>Schedule_Templates</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Schedule Template</label>
    <nameField>
        <label>Schedule Template Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Schedule Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Section__c.object
<CustomObject>
    <fields>
        <fullName>All_Grades__c</fullName>
        <inlineHelpText>Select the grade(s) for which the section is available. SchoolForce uses this field to determine the available sectons into which you can schedule a student when you use the Section Wizard.</inlineHelpText>
        <label>All Grades</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>PS</fullName>
                </value>
                <value>
                    <fullName>PK</fullName>
                </value>
                <value>
                    <fullName>K</fullName>
                </value>
                <value>
                    <fullName>1</fullName>
                </value>
                <value>
                    <fullName>2</fullName>
                </value>
                <value>
                    <fullName>3</fullName>
                </value>
                <value>
                    <fullName>4</fullName>
                </value>
                <value>
                    <fullName>5</fullName>
                </value>
                <value>
                    <fullName>6</fullName>
                </value>
                <value>
                    <fullName>7</fullName>
                </value>
                <value>
                    <fullName>8</fullName>
                </value>
                <value>
                    <fullName>9</fullName>
                </value>
                <value>
                    <fullName>10</fullName>
                </value>
                <value>
                    <fullName>11</fullName>
                </value>
                <value>
                    <fullName>12</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <inlineHelpText>Enter a description of the section. This field only displays in the Description field on the Section record. You can use it on reports.</inlineHelpText>
        <label>Description</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Grade_Level__c</fullName>
        <inlineHelpText>Select the grade level of the course, if desired. SchoolForce uses the All Grades list box to determine the grade level(s) for which the section is available. You can use the Grade Level drop-down list on reports.</inlineHelpText>
        <label>Grade Level</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>PS</fullName>
                </value>
                <value>
                    <fullName>PK</fullName>
                </value>
                <value>
                    <fullName>K</fullName>
                </value>
                <value>
                    <fullName>1</fullName>
                </value>
                <value>
                    <fullName>2</fullName>
                </value>
                <value>
                    <fullName>3</fullName>
                </value>
                <value>
                    <fullName>4</fullName>
                </value>
                <value>
                    <fullName>5</fullName>
                </value>
                <value>
                    <fullName>6</fullName>
                </value>
                <value>
                    <fullName>7</fullName>
                </value>
                <value>
                    <fullName>8</fullName>
                </value>
                <value>
                    <fullName>9</fullName>
                </value>
                <value>
                    <fullName>10</fullName>
                </value>
                <value>
                    <fullName>11</fullName>
                </value>
                <value>
                    <fullName>12</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Name_Spanish__c</fullName>
        <description>The section name in Spanish language.</description>
        <inlineHelpText>Enter the Spanish translation for the section name. This field only displays in the Name in Spanish field on the Section record. You can use it on reports. The Name in Spanish field on the Course displays on report cards/progress reports.</inlineHelpText>
        <label>Name in Spanish</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Reporting_Period__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Usually the only reporting period; could be the first if the section spans multiple reporting periods.</description>
        <label>Reporting Period</label>
        <referenceTo>Time_Element__c</referenceTo>
        <relationshipLabel>Sections (First Reporting Period)</relationshipLabel>
        <relationshipName>Sections1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>School__c</fullName>
        <label>School</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Sections</relationshipLabel>
        <relationshipName>Sections</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Section__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Recursive lookup for groups</description>
        <label>Section</label>
        <referenceTo>Section__c</referenceTo>
        <relationshipLabel>Groups in Section</relationshipLabel>
        <relationshipName>Sections1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Time__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Time</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Time_Element__c.Picklist_Value__r.Name</field>
                <operation>equals</operation>
                <value>Year</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Time_Element__c</referenceTo>
        <relationshipLabel>Sections</relationshipLabel>
        <relationshipName>Sections</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Section</label>
    <nameField>
        <label>Section Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sections</pluralLabel>
    <recordTypes>
        <fullName>Schedule_Group</fullName>
        <active>true</active>
        <description>Groups of Students Used for Scheduling Purposes</description>
        <label>Schedule Group</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Setup__c.object
<CustomObject>
    <description>This object is used to setup Schoolforce and is referenced in multiple pieces of code.  There should be one setup object per school.</description>
    <fields>
        <fullName>Group_Based__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>If Checked, schedule is based on students moving between classes as a group, enabling Schedule Templates &amp; scheduling in a Group Agenda view;
If Unchecked, school schedule is based on periods, enabling Period Templates &amp; scheduling in a Grid View</inlineHelpText>
        <label>Group Based ?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>School__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>School</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1 OR 2</booleanFilter>
            <filterItems>
                <field>Account.RecordType.Name</field>
                <operation>equals</operation>
                <value>School</value>
            </filterItems>
            <filterItems>
                <field>Account.RecordType.Name</field>
                <operation>equals</operation>
                <value>Summer School</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Setup</relationshipLabel>
        <relationshipName>Setup</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Term__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Term refers to the Term &apos;Template&apos; that the administrator associates to the School; this contains all Semeser/Quarter/Period logic necessary to create Sessions.</description>
        <label>Term</label>
        <referenceTo>Time_Element__c</referenceTo>
        <relationshipLabel>Setup</relationshipLabel>
        <relationshipName>Setup</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Year__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>School Year associated to the Setup</description>
        <label>Year</label>
        <referenceTo>Time_Element__c</referenceTo>
        <relationshipLabel>Setup (Year)</relationshipLabel>
        <relationshipName>Setup_Year</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Setup</label>
    <nameField>
        <displayFormat>S-{0}</displayFormat>
        <label>Setup ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Setup</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/Term__c.object
<CustomObject>
    <description>Junction object  between Time and Setup.</description>
    <fields>
        <fullName>Setup__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Setup</label>
        <referenceTo>Setup__c</referenceTo>
        <relationshipLabel>Terms</relationshipLabel>
        <relationshipName>Terms</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Time_Element__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Time Element</label>
        <referenceTo>Time_Element__c</referenceTo>
        <relationshipLabel>Terms</relationshipLabel>
        <relationshipName>Terms</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Term</label>
    <nameField>
        <displayFormat>Term-{000000}</displayFormat>
        <label>Term Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Terms</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Time_Element__c.object
<CustomObject>
    <fields>
        <fullName>Reporting_Period__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Reporting Period?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>School__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>School</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Time</relationshipLabel>
        <relationshipName>Time</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Time</label>
    <nameField>
        <displayFormat>T-{000000}</displayFormat>
        <label>Time Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Time</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/core_SetupWrapper.cls
public class core_SetupWrapper {

public boolean 	bHasSetup {get;set;}
public Setup__c 	setup {get;set;}
public Account	school {get;set;}
public List <Time_Element__c> 		reportingPeriodList {get;set;}
public List <Schedule_Template__c> setupScheduleTemplateList {get;set;}
public List <cTime> 		cRPeriodList {get;set;}
public Map <Id, List <Schedule_Template__c>> rpScheduleTemplateMap;
public string selectedTab {get;set;}
public List <Section__c> 	scheduleGroupList {get;set;}

public core_SetupWrapper(){
	
}

public core_SetupWrapper(Setup__c s, string tab){
	bHasSetup = true;
	this.rpScheduleTemplateMap = new Map <Id, List <Schedule_Template__c>>();
	this.cRPeriodList = new List <cTime>();
	this.selectedTab = tab;
	this.setup = s;
	if (setup.term__c!=null) reportingPeriodList = core_SoqlUtils.getTimeElementsByTerm(setup.term__c, true);
	Set <Id> rpIds = new Set <Id>();
	if (reportingPeriodList!=null){
		for (Time_Element__c te: reportingPeriodList){
			rpIds.add(te.id);
		}
		this.setupScheduleTemplateList = scheduler_SoqlUtils.retreiveScheduleTemplates(this.setup, rpIds);
	}
	this.school = core_SoqlUtils.getSchoolMap(new Set<Id>{setup.school__c}).values();
	
	//Start of US1254 changes
	if (setup.Group_Based__c){
		refreshScheduleGroups();
	}
		//End of US1254 changes
	
	if (setupScheduleTemplateList!=null){
		for (Schedule_Template__c st: setupScheduleTemplateList){
			if (rpScheduleTemplateMap.get(st.reporting_period__c) !=null){
				rpScheduleTemplateMap.get(st.reporting_period__c).add(st);
			}
			else {
				rpScheduleTemplateMap.put(st.reporting_period__c, new List <Schedule_Template__c>{st});
			}
		}
	
		for (Time_Element__c te: reportingPeriodList){
			cTime newCTime = new cTime(te, setup.id, rpScheduleTemplateMap.get(te.id));
			cRPeriodList.add(newCTime);
		}
	}
}
	//Start of US1254 changes
public void refreshScheduleGroups(){
	this.scheduleGroupList = new List <Section__c>();
		for (Section__c sect:  [select id, grade_level__c, name, All_Grades__c, Description__c, school__c, name_spanish__c  from Section__c 
											where RecordType.DeveloperName = 'Schedule_Group' 
											and school__c=	:setup.school__c
											and time__c 	= :setup.year__c]){
		     	this.scheduleGroupList.add(sect);
		}
}
	//End of US1254 changes


    public pageReference newScheduleTemplate(){
    	pageReference pr = new PageReference('/apex/core_ScheduleTemplate?setupid='+setup.id+'&new=1');
    	pr.setRedirect(true);
    	return pr;
    }
 
 public class cTime{
	public Time_Element__c rPeriod {get;set;}
	public string				schedLink {get;set;}
	public string				schedIcon {get;set;}
	public List <Schedule_Template__c> scheduleTemplateList {get;set;}
	public cTime(Time_Element__c te, Id setupId, List <Schedule_Template__c> stList){
		this.rPeriod =te;
		this.schedIcon =  '/img/func_icons/util/pencil12.gif';
		this.schedLink='/apex/Scheduler_Grid?setupId='+setupId+'&id='+te.Id;
		this.scheduleTemplateList = stList;
		if (this.scheduleTemplateList == null) this.scheduleTemplateList = new List <Schedule_Template__c>();
	}
}
    
    

}