objects/Account.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <label>Active</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>No</fullName>
                </value>
                <value>
                    <fullName>Yes</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <recordTypes>
        <fullName>School</fullName>
        <active>true</active>
        <description>This record type is for physical school locations.</description>
        <label>School</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Account_Program__c.object
<CustomObject>
    <description>The Account/Program object is part of the Interventions App and links Programs and Schools/Accounts.  This linking occurs in the Interventions Setup when a school selects which interventions Programs they will enroll in for a specific year.  This object tracks the relationships of Programs and Schools and whether the Programs are active.</description>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Is this Program active for this School in this year?</inlineHelpText>
        <label>Active?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Program__c</fullName>
        <inlineHelpText>This field joins the Account/Program record to the correct intervention Program</inlineHelpText>
        <label>Program</label>
        <referenceTo>Program__c</referenceTo>
        <relationshipLabel>School Programs</relationshipLabel>
        <relationshipName>Accounts_Programs</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>School__c</fullName>
        <inlineHelpText>This field joins the Account/Program record to the correct School.</inlineHelpText>
        <label>School</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Accounts/Programs</relationshipLabel>
        <relationshipName>Accounts_Programs</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Account/Program</label>
    <nameField>
        <label>School Program Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Accounts/Programs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Indicator_Area__c.object
<CustomObject>
    <description>This object is part of the Interventions app. Indicator Area defines a high-level intervention focus area (e.g., Behavior, Attendance, English Language Arts). Students are assigned to Indicator Areas in order to schedule them in Intervention Programs and Sections.</description>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>true</defaultValue>
        <inlineHelpText>Indicates whether or not this indicator area is available to assign to students on the Add Students to Indicator Areas screen. If you uncheck this field, SchoolForce deactivates any associated Program, Staff/Section, and Student/Section records.</inlineHelpText>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <label>Indicator Area</label>
    <nameField>
        <label>Indicator Area</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Indicator Areas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Indicator_Area_Student__c.object
<CustomObject>
    <description>The Indicator Area/Student object is a joiner object that associates an Indicator Area and a Student.</description>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>true</defaultValue>
        <inlineHelpText>Is the Indicator Area associated to this Student active? If this box is unchecked then the Student no longer requires intervention in this area.</inlineHelpText>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Indicator_Area__c</fullName>
        <inlineHelpText>This field joins the Indicator Area/Student record to the correct Indicator Area</inlineHelpText>
        <label>Indicator Area</label>
        <referenceTo>Indicator_Area__c</referenceTo>
        <relationshipLabel>Indicator Area/Student</relationshipLabel>
        <relationshipName>Indicator_Area_Student</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Student__c</fullName>
        <inlineHelpText>This field joins the Indicator Area/Student record to the correct Student</inlineHelpText>
        <label>Student</label>
        <referenceTo>Student__c</referenceTo>
        <relationshipLabel>Indicator Area/Student</relationshipLabel>
        <relationshipName>Indicator_Area_Student</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Indicator Area/Student</label>
    <nameField>
        <displayFormat>IA/S -{000}</displayFormat>
        <label>IA/Student ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Indicator Area/Student</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Program__c.object
<CustomObject>
    <description>Program is an Intervention object. Intervention Programs are aligned with Indicator Areas and are a high level set of activities with defined dosage goals. Each Program has its own frequency, target dosage, and recommended time per session. An example Program is one-on-one reading.</description>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>If this box is checked then the Program is currently available for use.</inlineHelpText>
        <label>Active?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Indicator_Area__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>You must select an Indicator Area that aligns with this Program.</inlineHelpText>
        <label>Indicator Area</label>
        <referenceTo>Indicator_Area__c</referenceTo>
        <relationshipLabel>Programs</relationshipLabel>
        <relationshipName>Programs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Required_Program__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Is this Program required for your school or organization? Administrators can select whether Programs should be required or not. If yes, then each school will automatically be associated with this Program. Schools can opt of required Programs.</inlineHelpText>
        <label>Required Program</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <inlineHelpText>This field is automatically updated based on whether your organization has setup approval processes for Programs.</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Pending</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Program</label>
    <nameField>
        <label>Program Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/Section__c.object
<CustomObject>
    <fields>
        <fullName>Account_Program__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>What intervention Program is this intervention Section associated to?</inlineHelpText>
        <label>School Program</label>
        <lookupFilter>
            <active>false</active>
            <filterItems>
                <field>Account_Program__c.Program__c</field>
                <operation>equals</operation>
                <valueField>$Source.Program__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account_Program__c</referenceTo>
        <relationshipLabel>Sections</relationshipLabel>
        <relationshipName>Sections</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Check this box if the section is a currently active section</description>
        <inlineHelpText>Check this box if the section is a currently active section</inlineHelpText>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>End_Date__c</fullName>
        <inlineHelpText>When does the Intervention Section end?</inlineHelpText>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>In_After_School__c</fullName>
        <inlineHelpText>Is this Intervention Section considered in school or extended learning?</inlineHelpText>
        <label>In School/Extended Learning/Curriculum</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>In School</fullName>
                </value>
                <value>
                    <fullName>Extended Learning</fullName>
                </value>
                <value>
                    <fullName>Curriculum</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Indicator_Area__c</fullName>
        <formula>Program__r.Indicator_Area__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>What Indicator Area is this Program addressing? This field cannot be modified here.</inlineHelpText>
        <label>Indicator Area</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Program__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>What intervention Program is this Intervention Section for?</inlineHelpText>
        <label>Program</label>
        <referenceTo>Program__c</referenceTo>
        <relationshipLabel>Sections</relationshipLabel>
        <relationshipName>Sections</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>School__c</fullName>
        <label>School</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Sections</relationshipLabel>
        <relationshipName>Sections</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Section__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Recursive lookup for groups</description>
        <label>Section</label>
        <referenceTo>Section__c</referenceTo>
        <relationshipLabel>Groups in Section</relationshipLabel>
        <relationshipName>Sections1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <inlineHelpText>What is the start date for this intervention Section?</inlineHelpText>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Target_Dosage_Section_Goal__c</fullName>
        <inlineHelpText>What is the specific target dosage goal for this Intervention Section? It may be the same or different than the Program Target Dosage goal.</inlineHelpText>
        <label>Target Dosage - Section Goal (in mins)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Section</label>
    <nameField>
        <label>Section Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sections</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Student__c.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>true</defaultValue>
        <inlineHelpText>Indicates whether or not this Student record is active. If checked, then this is the current Student record. If unchecked, this is an old Student record.</inlineHelpText>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>School__c</fullName>
        <inlineHelpText>Displays the name of the student&apos;s current SchoolForce school. You can click on the link to see the details of this school.</inlineHelpText>
        <label>School</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Students</relationshipLabel>
        <relationshipName>Students</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Section__c</fullName>
        <inlineHelpText>Displays the student&apos;s current homeroom name or room number. This field can be used for reporting purposes.</inlineHelpText>
        <label>Current Homeroom</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Student__c</fullName>
        <inlineHelpText>Displays the student&apos;s middle name.</inlineHelpText>
        <label>Student Middle Name</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <label>Student</label>
    <nameField>
        <label>Student Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Students</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/TestStudentProgramController.cls
@isTest
private class TestStudentProgramController {

	static testMethod void TestFilterChanges() {
		TestDataUtil.setupData(2);	
		List<Student__c> students = TestDataUtil.testData[0].students;
		students.addAll(TestDataUtil.testData[1].students);
		Account school_1 = TestDataUtil.testData[0].school;
		Account school_2 = TestDataUtil.testData[1].school;
		Indicator_Area__c ia = new Indicator_Area__c();
		ia.Name = 'IA';
		insert ia;
		List<Indicator_Area_Student__c> iaStuList = new List<Indicator_Area_Student__c>();
		for(Student__c stu :students) {
			Indicator_Area_Student__c iaStu = new Indicator_Area_Student__c();
			iaStu.Student__c = stu.id;
			iaStu.Indicator_Area__c = ia.id;
			iaStu.Active__c = true;
			iaStuList.add(iaStu);
		}
		insert iaStuList;
		List<Program__c> programs = new List<Program__c>();
		programs.add(new Program__c(Name = 'Program', Required_Program__c =true, Status__c = 'Approved',Indicator_Area__c = ia.Id));
		programs.add(new Program__c(Name = 'Not Required Program', Required_Program__c =false, Status__c = 'Approved',Indicator_Area__c = ia.Id));
		
		insert programs;
		List<Account_Program__c> aps = new List<Account_Program__c>();
		aps.add(new Account_Program__c(Program__c = programs[0].id,School__c = school_1.id,Active__c = true));
		aps.add(new Account_Program__c(Program__c = programs[1].id,School__c = school_1.id,Active__c = true));
		aps.add(new Account_Program__c(Program__c = programs[0].id,School__c = school_2.id,Active__c = true));
		aps.add(new Account_Program__c(Program__c = programs[1].id,School__c = school_2.id,Active__c = true));
		insert aps;

		Section__c sec = new Section__c();
		ApexPages.StandardController sc = new ApexPages.standardController(sec);
			
		test.startTest();
		system.runAs(TestDataUtil.testData[0].sysAdmin.userRecord) {
			StudentProgramController controller = new StudentProgramController(sc);
			system.assertEquals(2, controller.schools.size(),'Expected 2 schools to load.');
			controller.getFreqOptions(); //called from page
			controller.getSchoolList();

			controller.activeSchoolID = controller.schools[0].id;
			controller.changeSchool();
			system.assertEquals(2, controller.programs.size(),'Expected 2 programs to load for this school.');
			controller.selectedProgram = controller.programs[0].getValue();
			controller.changeProgram();

			system.assertEquals(10, controller.availableStudents.size(),'Expected 10 students by default.');
			system.assertEquals(false, controller.indicatorAreas.isEmpty(),'Expected there to be at least one indicator Area to choose from.');
			controller.selectedIndicatorArea = controller.indicatorAreas[0].getValue();
			controller.changeIndicatorArea();
			system.assertEquals(false, controller.availableStudents.isEmpty(),'Expected at least one student to remain.');

			controller.selectedFilterSection = 'null';
			controller.changeSection();
			system.assertEquals('null', controller.selectedIndicatorArea,'Choosing a section should reset the indicator area filter.');

			controller.selectedGrade = '5';
			controller.changeGrade();
			system.assertEquals(false, controller.availableStudents.isEmpty(),'Expected at least one student to remain.');
		}
		test.stopTest();
	}
	
	static testMethod void enrollmentTableTest() {
		TestDataUtil.setupData(2);	
		List<Student__c> students = TestDataUtil.testData[0].students;
		students.addAll(TestDataUtil.testData[1].students);
		Account school_1 = TestDataUtil.testData[0].school;
		Account school_2 = TestDataUtil.testData[1].school;
		Indicator_Area__c ia = new Indicator_Area__c();
		ia.Name = 'IA';
		insert ia;
		List<Indicator_Area_Student__c> iaStuList = new List<Indicator_Area_Student__c>();
		for(Student__c stu :students) {
			Indicator_Area_Student__c iaStu = new Indicator_Area_Student__c();
			iaStu.Student__c = stu.id;
			iaStu.Indicator_Area__c = ia.id;
			iaStu.Active__c = true;
			iaStuList.add(iaStu);
		}
		insert iaStuList;
		List<Program__c> programs = new List<Program__c>();
		programs.add(new Program__c(Name = 'Program', Required_Program__c =true, Status__c = 'Approved',Indicator_Area__c = ia.Id));
		programs.add(new Program__c(Name = 'Not Required Program', Required_Program__c =false, Status__c = 'Approved',Indicator_Area__c = ia.Id));
		
		insert programs;
		List<Account_Program__c> aps = new List<Account_Program__c>();
		aps.add(new Account_Program__c(Program__c = programs[0].id,School__c = school_1.id,Active__c = true));
		aps.add(new Account_Program__c(Program__c = programs[1].id,School__c = school_1.id,Active__c = true));
		aps.add(new Account_Program__c(Program__c = programs[0].id,School__c = school_2.id,Active__c = true));
		aps.add(new Account_Program__c(Program__c = programs[1].id,School__c = school_2.id,Active__c = true));
		insert aps;
			
		
		test.startTest();
		system.runAs(TestDataUtil.testData[0].sysAdmin.userRecord) {
			Section__c sec = new Section__c();
			ApexPages.StandardController sc = new ApexPages.standardController(sec);
			StudentProgramController cont = new StudentProgramController(sc);
			
			for(studentWrapper s :cont.availableStudents) {
				s.checked = true;
			}
			cont.addStudents();
			system.assertEquals(false, cont.selectedStudents.isEmpty());
			system.assertEquals(true, cont.availableStudents.isEmpty());

			for(studentWrapper s :cont.selectedStudents) {
				s.checked = true;
			}
			cont.removeStudents();


			cont.addStudents();
			cont.removeStudents();

		}
		test.stopTest();
	}
	static testMethod void createSectionErrors() {
		TestDataUtil.setupData(2);	
		List<Student__c> students = TestDataUtil.testData[0].students;
		students.addAll(TestDataUtil.testData[1].students);
		Account school_1 = TestDataUtil.testData[0].school;
		Account school_2 = TestDataUtil.testData[1].school;
		Indicator_Area__c ia = new Indicator_Area__c();
		ia.Name = 'IA';
		insert ia;
		List<Indicator_Area_Student__c> iaStuList = new List<Indicator_Area_Student__c>();
		for(Student__c stu :students) {
			Indicator_Area_Student__c iaStu = new Indicator_Area_Student__c();
			iaStu.Student__c = stu.id;
			iaStu.Indicator_Area__c = ia.id;
			iaStu.Active__c = true;
			iaStuList.add(iaStu);
		}
		insert iaStuList;
		List<Program__c> programs = new List<Program__c>();
		programs.add(new Program__c(Name = 'Program', Required_Program__c =true, Status__c = 'Approved',Indicator_Area__c = ia.Id));
		programs.add(new Program__c(Name = 'Not Required Program', Required_Program__c =false, Status__c = 'Approved',Indicator_Area__c = ia.Id));
		
		insert programs;
		List<Account_Program__c> aps = new List<Account_Program__c>();
		aps.add(new Account_Program__c(Program__c = programs[0].id,School__c = school_1.id,Active__c = true));
		aps.add(new Account_Program__c(Program__c = programs[1].id,School__c = school_1.id,Active__c = true));
		aps.add(new Account_Program__c(Program__c = programs[0].id,School__c = school_2.id,Active__c = true));
		aps.add(new Account_Program__c(Program__c = programs[1].id,School__c = school_2.id,Active__c = true));
		insert aps;
			
		
		test.startTest();
		system.runAs(TestDataUtil.testData[0].sysAdmin.userRecord) {
			Section__c sec = new Section__c();
			ApexPages.StandardController sc = new ApexPages.standardController(sec);
			StudentProgramController cont = new StudentProgramController(sc);
			
			for(studentWrapper s :cont.availableStudents) {
				s.checked = true;
			}
			cont.addStudents();
			cont.saveSection();
			system.assert(true);
			
		}
		test.stopTest();
	}
	static testMethod void createSection() {
		TestDataUtil.setupData(2);	
		List<Student__c> students = TestDataUtil.testData[0].students;
		students.addAll(TestDataUtil.testData[1].students);
		Account school_1 = TestDataUtil.testData[0].school;
		Account school_2 = TestDataUtil.testData[1].school;
		Indicator_Area__c ia = new Indicator_Area__c();
		ia.Name = 'IA';
		insert ia;
		List<Indicator_Area_Student__c> iaStuList = new List<Indicator_Area_Student__c>();
		for(Student__c stu :students) {
			Indicator_Area_Student__c iaStu = new Indicator_Area_Student__c();
			iaStu.Student__c = stu.id;
			iaStu.Indicator_Area__c = ia.id;
			iaStu.Active__c = true;
			iaStuList.add(iaStu);
		}
		insert iaStuList;
		List<Program__c> programs = new List<Program__c>();
		programs.add(new Program__c(Name = 'Program', Required_Program__c =true, Status__c = 'Approved',Indicator_Area__c = ia.Id));
		programs.add(new Program__c(Name = 'Not Required Program', Required_Program__c =false, Status__c = 'Approved',Indicator_Area__c = ia.Id));
		
		insert programs;
		List<Account_Program__c> aps = new List<Account_Program__c>();
		aps.add(new Account_Program__c(Program__c = programs[0].id,School__c = school_1.id,Active__c = true));
		aps.add(new Account_Program__c(Program__c = programs[1].id,School__c = school_1.id,Active__c = true));
		aps.add(new Account_Program__c(Program__c = programs[0].id,School__c = school_2.id,Active__c = true));
		aps.add(new Account_Program__c(Program__c = programs[1].id,School__c = school_2.id,Active__c = true));
		insert aps;
			
		
		test.startTest();
		system.runAs(TestDataUtil.testData[0].sysAdmin.userRecord) {
			Section__c sec = new Section__c();
			ApexPages.StandardController sc = new ApexPages.standardController(sec);
			StudentProgramController cont = new StudentProgramController(sc);
			
			cont.activeSchoolId = TestDataUtil.testData[0].cmDirect.staffRecord.Organization__c;
			cont.changeSchool();
			
			for(studentWrapper s :cont.availableStudents) {
				s.checked = true;
			}

			cont.addStudents();
			cont.selectedStaff = TestDataUtil.testData[0].cmDirect.staffRecord.Id;
			
			cont.sectionHolder.Start_Date__c = Date.Today();
			cont.sectionHolder.End_Date__c = Date.Today().addDays(5);
			cont.freqChecks.add('Monday');
			cont.sectionHolder.In_After_School__c = 'In School';
			cont.sectionHolder.Target_Dosage_Section_Goal__c = 100;
			cont.stuSecHolder.Enrollment_Start_Date__c = Date.Today();
			PageReference pref = cont.saveSection();
			System.assertNotEquals(null, pref);
			
			pref = cont.saveAndNewSection();
			System.assertNotEquals(null, pref);

			cont.getSectionToClone();
			
		}
		test.stopTest();
	}
}