objects/Account.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <label>Active</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>No</fullName>
                </value>
                <value>
                    <fullName>Yes</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <recordTypes>
        <fullName>School</fullName>
        <active>true</active>
        <description>This record type is for physical school locations.</description>
        <label>School</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>true</defaultValue>
        <inlineHelpText>Schools/organizations can choose to use this field when a Contact record is active. When Contact records are created through SchoolForce Setup, this check box is selected.</inlineHelpText>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>User_ID__c</fullName>
        <formula>User__r.Id</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Displays the contact&apos;s 15-digit Salesforce ID from the User record. Note that only staff Contact records have a User record.</inlineHelpText>
        <label>User ID</label>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/EOY_Progress__c.object
<CustomObject>
    <description>This object is used to determine the current completion progress in the EOY Wizard.</description>
    <fields>
        <fullName>School__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field is required to keep track of the EOY progression for a school.</description>
        <inlineHelpText>This field is required for EOY Progression on schools.</inlineHelpText>
        <label>School</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>EOY Progresses</relationshipLabel>
        <relationshipName>EOY_Progresses</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Setup__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Look up to the setup record, since a setup represents an active configuration for a school.</description>
        <inlineHelpText>Determine the progress for an active setup to a school.</inlineHelpText>
        <label>Setup</label>
        <referenceTo>Setup__c</referenceTo>
        <relationshipLabel>EOY Progresses</relationshipLabel>
        <relationshipName>EOY_Progresses</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Year__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>The year that the EOY Wizard process is for.</description>
        <inlineHelpText>The year for the EOY Wizard to process.</inlineHelpText>
        <label>Year</label>
        <referenceTo>Time_Element__c</referenceTo>
        <relationshipLabel>EOY Progresses</relationshipLabel>
        <relationshipName>EOY_Progresses</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>EOY Progress</label>
    <nameField>
        <label>EOY Save State Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>EOY Progresses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Indicator_Area__c.object
<CustomObject>
    <description>This object is part of the Interventions app. Indicator Area defines a high-level intervention focus area (e.g., Behavior, Attendance, English Language Arts). Students are assigned to Indicator Areas in order to schedule them in Intervention Programs and Sections.</description>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>true</defaultValue>
        <inlineHelpText>Indicates whether or not this indicator area is available to assign to students on the Add Students to Indicator Areas screen. If you uncheck this field, SchoolForce deactivates any associated Program, Staff/Section, and Student/Section records.</inlineHelpText>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <label>Indicator Area</label>
    <nameField>
        <label>Indicator Area</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Indicator Areas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Indicator_Area_Student__c.object
<CustomObject>
    <description>The Indicator Area/Student object is a joiner object that associates an Indicator Area and a Student.</description>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>true</defaultValue>
        <inlineHelpText>Is the Indicator Area associated to this Student active? If this box is unchecked then the Student no longer requires intervention in this area.</inlineHelpText>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <label>Indicator Area/Student</label>
    <nameField>
        <displayFormat>IA/S -{000}</displayFormat>
        <label>IA/Student ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Indicator Area/Student</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Section__c.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Check this box if the section is a currently active section</description>
        <inlineHelpText>Check this box if the section is a currently active section</inlineHelpText>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>School__c</fullName>
        <label>School</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Sections</relationshipLabel>
        <relationshipName>Sections</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Staff__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Staff</label>
        <referenceTo>Staff__c</referenceTo>
        <relationshipLabel>Sections</relationshipLabel>
        <relationshipName>Sections</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Section</label>
    <nameField>
        <label>Section Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sections</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Setup__c.object
<CustomObject>
    <description>This object is used to setup Schoolforce and is referenced in multiple pieces of code.  There should be one setup object per school.</description>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Is this school setup active for this school year?</inlineHelpText>
        <label>Active?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>School__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>School</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1 OR 2</booleanFilter>
            <filterItems>
                <field>Account.RecordType.Name</field>
                <operation>equals</operation>
                <value>School</value>
            </filterItems>
            <filterItems>
                <field>Account.RecordType.Name</field>
                <operation>equals</operation>
                <value>Summer School</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Setup</relationshipLabel>
        <relationshipName>Setup</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Setup</label>
    <nameField>
        <displayFormat>S-{0}</displayFormat>
        <label>Setup ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Setup</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/Staff__c.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Organization__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Staff Member&apos;s employer</description>
        <label>Organization</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Staff</relationshipLabel>
        <relationshipName>Staff</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>User_ID__c</fullName>
        <formula>Individual__r.User_ID__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>User ID</label>
        <type>Text</type>
    </fields>
    <label>Staff</label>
    <nameField>
        <label>Staff Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Staff</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/Staff_Section__c.object
<CustomObject>
    <fields>
        <fullName>School__c</fullName>
        <formula>Section__r.School__r.Id</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>The School related to this Section</inlineHelpText>
        <label>School</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Staff__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Staff</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Staff__c.Organization__r.Id</field>
                <operation>equals</operation>
                <valueField>$Source.Account__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Staff__c</referenceTo>
        <relationshipLabel>Sections</relationshipLabel>
        <relationshipName>Staff_Section</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Staff/Section</label>
    <nameField>
        <displayFormat>SfS-{000000}</displayFormat>
        <label>Staff/Section ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Staff/Section</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Student__c.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>true</defaultValue>
        <inlineHelpText>Indicates whether or not this Student record is active. If checked, then this is the current Student record. If unchecked, this is an old Student record.</inlineHelpText>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>School__c</fullName>
        <inlineHelpText>Displays the name of the student&apos;s current SchoolForce school. You can click on the link to see the details of this school.</inlineHelpText>
        <label>School</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Students</relationshipLabel>
        <relationshipName>Students</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Setup__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Displays the Setup record associated to this Student record. The Setup record defines the settings for the school in a specific school year.</inlineHelpText>
        <label>Setup</label>
        <referenceTo>Setup__c</referenceTo>
        <relationshipLabel>Students</relationshipLabel>
        <relationshipName>Students</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Staff__c</fullName>
        <inlineHelpText>Displays the name of the student&apos;s homeroom teacher.  You can use this field for reporting purposes.</inlineHelpText>
        <label>Current Homeroom Teacher</label>
        <type>TextArea</type>
    </fields>
    <label>Student</label>
    <nameField>
        <label>Student Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Students</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Student_Section__c.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>School__c</fullName>
        <formula>Student__r.School__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>School</label>
        <type>Text</type>
    </fields>
    <label>Student/Section</label>
    <nameField>
        <displayFormat>SS-{000000}</displayFormat>
        <label>Student/Section ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Student/Section</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Time_Element__c.object
<CustomObject>
    <fields>
        <fullName>School__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>School</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Time</relationshipLabel>
        <relationshipName>Time</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Time</label>
    <nameField>
        <displayFormat>T-{000000}</displayFormat>
        <label>Time Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Time</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/CYUtil.cls
public with sharing class CYUtil{
	public static String CMPROFILENAME = 'CY CM/Direct Service Provider Profile';
	public static String SCHOOLPROFILENAME = 'CY School Administrator Profile';
	public static String SITEPROFILENAME = 'CY Location/Site Administrator Profile';
	public static String NETWORKPROFILENAME = 'CY Network Admin (HQ) Profile';
	public static String SYSADMINPROFILENAME = 'System Administrator';

	public static Time_Element__c currentYear;

	public static Map<String, ID> recordTypeNameMap;
	public static Map<ID, Profile> profileMap;
	
	public static List<Account> getStaffSchool(){
		List<Account> schools = new List<Account>();
		String userId = Userinfo.getUserId();
		userId = userId.substring(0,15);
		system.debug(userId);
		List<Staff__c> staffRecords = new List<Staff__c>();
		Profile p = [Select Id, Name from Profile WHERE Id =:Userinfo.getProfileId()];
		RecordType rt = [Select ID FROM RecordType WHERE Name = 'School'];
		if(p.Name == SYSADMINPROFILENAME) {
			schools = [Select Id, Name FROM Account WHERE RecordTypeId = :rt.Id ORDER BY Name ASC];
			return schools;
		}
		else {
			staffRecords = [SELECT Id, Name, User_ID__c, Organization__r.Id,Organization__r.Name FROM Staff__c where User_ID__c = :userId AND Active__c = true];
			if(staffRecords.size() >=1){
				for(Staff__c s :staffRecords)
				{
					if(userId.equals(s.User_ID__c) && s.Organization__r!=null)
						schools.add(s.Organization__r);
				}
				return schools;
			}
		}
		return null;
	}
	
	public static List<Account> getAllActiveSchools() {
		ID rtID = getRecordTypeID('School');
		List<Account> schools = new List<Account>();
		for(Setup__c s:
				[select id, School__r.Name, School__c 
				from Setup__c 
				where Active__c = true
				and School__r.RecordTypeId = :rtID
				ORDER BY School__r.Name ASC]){
			schools.add(s.School__r);
		}
		if(schools.size() > 0){
			return schools;
		}
		return null;
		 
	}

	public static Id getSchoolYearID(Id schoolID) {
		List <Setup__c> activeSetup = [SELECT Id, Year__r.Id FROM Setup__c WHERE Active__c = true AND School__c = :schoolID limit 1];
		
		if(activeSetup.Size() > 0)
			return activeSetup[0].Year__r.Id;//r.Id;
		return null;
	}

	public static Id getRecordTypeID(String recordTypeName) {
		if(recordTypeNameMap == null){
			recordTypeNameMap = new Map<String, ID>();

			for (RecordType rt: [SELECT id, Name, DeveloperName , sObjectType
								FROM RecordType 
								WHERE Name!=null
								AND IsActive = true]){
				if(rt.sObjectType == 'Section__c' || rt.sObjectType == 'Contact' 
					|| rt.sObjectType == 'Account' || rt.sObjectType == 'EOY_Progress__c'){
					recordTypeNameMap.put(rt.Name, rt.ID);
				}
			}
		}
		
		return recordTypeNameMap.get(recordTypeName);
	}

	public static String getProfileTypeName(Id ProfileTypeID) {
		if(profileMap == null){
			profileMap = new Map<ID, Profile>([SELECT Id, Name FROM Profile WHERE Id = :ProfileTypeID LIMIT 1]);
		}
		if(profileMap.containsKey(ProfileTypeID)){
			return profileMap.get(ProfileTypeID).Name;
		}
		return null;
	}

	public static List<Intervention_Session__c> getInterventionDataForSection(Id sectionId){
		return [Select Skills_Covered_for_the_Session__c, Id, Date__c, Comments__c
				From Intervention_Session__c WHERE Section__c = :sectionId];
	}
	
	public static list<Intervention_Session__c> getInterventionDataForSection(Id sectionId, Date startDate, Date endDate){
		return [Select Skills_Covered_for_the_Session__c, Id, Date__c, Comments__c,
					(Select Id, Amount_of_Time__c, Student_Section__c, Intervention_Session__r.Skills_Covered_for_the_Session__c,
						Intervention_Session__r.Date__c, Intervention_Session__r.Comments__c , 
						Intervention_Session__c, Student__c, Student_Section__r.Student__c
					FROM Intervention_Session_Results__r )
				From Intervention_Session__c WHERE Section__c = :sectionId AND Date__c >= :startDate AND Date__c <= :endDate
				ORDER BY Date__c ASC];
	}

	public static ID getCurrentYearID(){
		return getCurrentYear().id;
	}

	public static Time_Element__c getCurrentYear(){
		if(currentYear == null){ //why query when you already have it?
			try{
				currentYear=
					[select id, Name__c, Date_Start_Date__c, End_Date__c 
					from Time_Element__c 
					where Current__c = true 
					order by End_Date__c
					limit 1];
			} catch (System.QueryException e){
				return null;
			}
		}
		return currentYear; 
	}

	public static map<ID, list<Indicator_Area_Student__c>> getStudentIndicatorAreaMap(list<Student__c> students) {
		list<Indicator_Area_Student__c> iaList = new list<Indicator_Area_Student__c>([
			SELECT Id, Name, Student__c, Indicator_Area__c
			FROM Indicator_Area_Student__c
			WHERE Student__c IN :students
		]);
		map<ID, list<Indicator_Area_Student__c>> studentIndicatorAreaMap = new map<ID, list<Indicator_Area_Student__c>>();
		for (Indicator_Area_Student__c ia : iaList) {
			if (!studentIndicatorAreaMap.containsKey(ia.Student__c)) {
				studentIndicatorAreaMap.put(ia.Student__c, new list<Indicator_Area_Student__c>());
			}
			studentIndicatorAreaMap.get(ia.Student__c).add(ia);
		}
		return studentIndicatorAreaMap;
	}

	public static void errorMessage(String message){
		ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR,message));
	}

	public static void infoMessage(String message){
		ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.INFO,message));
	}

	public static void warningMessage(String message){
		ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.WARNING,message));
	}

	public static void successMessage(String message){
		ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.CONFIRM,message));
	}

	public class InterventionsException extends Exception{
		
	}

	public class InterventionsPermissionsException extends Exception{

	}

	public static ID userStaffsSection(ID sectionID){
		List<Staff_Section__c> userSectionStaff =
			[select id,Staff__c from Staff_Section__c 
			WHERE Section__c =:sectionID
			AND Is_Active__c=true
			AND Staff__r.Individual__r.User__c =: UserInfo.getUserID()];

		if(userSectionStaff.isEmpty()){
			return null;
		} else {
			return userSectionStaff[0].Staff__c;
		}
	}
}