objects/Account.object
<CustomObject>
    <fields>
        <fullName>Site__c</fullName>
        <label>Location</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Baton Rouge</fullName>
                </value>
                <value>
                    <fullName>Boston</fullName>
                </value>
                <value>
                    <fullName>Buffalo</fullName>
                </value>
                <value>
                    <fullName>Chicago</fullName>
                </value>
                <value>
                    <fullName>City Year</fullName>
                </value>
                <value>
                    <fullName>Cleveland</fullName>
                </value>
                <value>
                    <fullName>Columbia</fullName>
                </value>
                <value>
                    <fullName>Columbus</fullName>
                </value>
                <value>
                    <fullName>Dallas</fullName>
                </value>
                <value>
                    <fullName>Denver</fullName>
                </value>
                <value>
                    <fullName>Detroit</fullName>
                </value>
                <value>
                    <fullName>Jacksonville</fullName>
                </value>
                <value>
                    <fullName>Kansas City</fullName>
                </value>
                <value>
                    <fullName>Little Rock</fullName>
                </value>
                <value>
                    <fullName>Los Angeles</fullName>
                </value>
                <value>
                    <fullName>Memphis</fullName>
                </value>
                <value>
                    <fullName>Miami</fullName>
                </value>
                <value>
                    <fullName>Milwaukee</fullName>
                </value>
                <value>
                    <fullName>New Hampshire</fullName>
                </value>
                <value>
                    <fullName>New Orleans</fullName>
                </value>
                <value>
                    <fullName>New York City</fullName>
                </value>
                <value>
                    <fullName>Orlando</fullName>
                </value>
                <value>
                    <fullName>Philadelphia</fullName>
                </value>
                <value>
                    <fullName>Providence</fullName>
                </value>
                <value>
                    <fullName>Rhode Island</fullName>
                </value>
                <value>
                    <fullName>Sacramento</fullName>
                </value>
                <value>
                    <fullName>San Antonio</fullName>
                </value>
                <value>
                    <fullName>San Jose/Silicon Valley</fullName>
                </value>
                <value>
                    <fullName>Seattle/King County</fullName>
                </value>
                <value>
                    <fullName>Tulsa</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <recordTypes>
        <fullName>School</fullName>
        <active>true</active>
        <description>This record type is for physical school locations.</description>
        <label>School</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Account_Program__c.object
<CustomObject>
    <description>The Account/Program object is part of the Interventions App and links Programs and Schools/Accounts.  This linking occurs in the Interventions Setup when a school selects which interventions Programs they will enroll in for a specific year.  This object tracks the relationships of Programs and Schools and whether the Programs are active.</description>
    <fields>
        <fullName>Program__c</fullName>
        <inlineHelpText>This field joins the Account/Program record to the correct intervention Program</inlineHelpText>
        <label>Program</label>
        <referenceTo>Program__c</referenceTo>
        <relationshipLabel>School Programs</relationshipLabel>
        <relationshipName>Accounts_Programs</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Account/Program</label>
    <nameField>
        <label>School Program Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Accounts/Programs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Comments__c</fullName>
        <inlineHelpText>Displays the most recent Overall Comments written for the student. This field is automatically updated if the Comments field on the Student record is updated.</inlineHelpText>
        <label>Comments</label>
        <length>32000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Student__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>This field provides a link to the most recent Student record.</inlineHelpText>
        <label>Student</label>
        <referenceTo>Student__c</referenceTo>
        <relationshipLabel>Contacts</relationshipLabel>
        <relationshipName>Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <recordTypes>
        <fullName>Staff</fullName>
        <active>true</active>
        <description>This record type is for staff members.</description>
        <label>Staff</label>
    </recordTypes>
    <recordTypes>
        <fullName>Student</fullName>
        <active>true</active>
        <description>This record type is for students</description>
        <label>Student</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Program__c.object
<CustomObject>
    <description>Program is an Intervention object. Intervention Programs are aligned with Indicator Areas and are a high level set of activities with defined dosage goals. Each Program has its own frequency, target dosage, and recommended time per session. An example Program is one-on-one reading.</description>
    <fields>
        <fullName>Indicator_Area__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>You must select an Indicator Area that aligns with this Program.</inlineHelpText>
        <label>Indicator Area</label>
        <referenceTo>Indicator_Area__c</referenceTo>
        <relationshipLabel>Programs</relationshipLabel>
        <relationshipName>Programs</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Program</label>
    <nameField>
        <label>Program Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/Section__c.object
<CustomObject>
    <fields>
        <fullName>Account_Program__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>What intervention Program is this intervention Section associated to?</inlineHelpText>
        <label>School Program</label>
        <lookupFilter>
            <active>false</active>
            <filterItems>
                <field>Account_Program__c.Program__c</field>
                <operation>equals</operation>
                <valueField>$Source.Program__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account_Program__c</referenceTo>
        <relationshipLabel>Sections</relationshipLabel>
        <relationshipName>Sections</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Indicator_Area__c</fullName>
        <formula>Program__r.Indicator_Area__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>What Indicator Area is this Program addressing? This field cannot be modified here.</inlineHelpText>
        <label>Indicator Area</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Program__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>What intervention Program is this Intervention Section for?</inlineHelpText>
        <label>Program</label>
        <referenceTo>Program__c</referenceTo>
        <relationshipLabel>Sections</relationshipLabel>
        <relationshipName>Sections</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Section__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Recursive lookup for groups</description>
        <label>Section</label>
        <referenceTo>Section__c</referenceTo>
        <relationshipLabel>Groups in Section</relationshipLabel>
        <relationshipName>Sections1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Staff__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Staff</label>
        <referenceTo>Staff__c</referenceTo>
        <relationshipLabel>Sections</relationshipLabel>
        <relationshipName>Sections</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Section</label>
    <nameField>
        <label>Section Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sections</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Skill__c.object
<CustomObject>
    <fields>
        <fullName>Category__c</fullName>
        <label>Category</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Literacy</fullName>
                </value>
                <value>
                    <fullName>Math</fullName>
                </value>
                <value>
                    <fullName>SEL/Behavior and Attendance Interventions</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Skill</label>
    <nameField>
        <label>Skill Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Skills</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Staff__c.object
<CustomObject>
    <fields>
        <fullName>Site__c</fullName>
        <formula>TEXT(Organization__r.Site__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Location</label>
        <type>Text</type>
    </fields>
    <label>Staff</label>
    <nameField>
        <label>Staff Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Staff</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/Student__c.object
<CustomObject>
    <fields>
        <fullName>Comments__c</fullName>
        <inlineHelpText>Displays the comments teachers enter for the student using the Overall Comments Wizard. This text displays on elementary school report cards and progress reports.</inlineHelpText>
        <label>Comments</label>
        <length>32000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Section__c</fullName>
        <inlineHelpText>Displays the student&apos;s current homeroom name or room number. This field can be used for reporting purposes.</inlineHelpText>
        <label>Current Homeroom</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Student__c</fullName>
        <inlineHelpText>Displays the student&apos;s middle name.</inlineHelpText>
        <label>Student Middle Name</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <label>Student</label>
    <nameField>
        <label>Student Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Students</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/User.object
<CustomObject>
    <fields>
        <fullName>Site__c</fullName>
        <label>Location</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Baton Rouge</fullName>
                </value>
                <value>
                    <fullName>Boston</fullName>
                </value>
                <value>
                    <fullName>Buffalo</fullName>
                </value>
                <value>
                    <fullName>Chicago</fullName>
                </value>
                <value>
                    <fullName>Cleveland</fullName>
                </value>
                <value>
                    <fullName>Columbia</fullName>
                </value>
                <value>
                    <fullName>Columbus</fullName>
                </value>
                <value>
                    <fullName>Dallas</fullName>
                </value>
                <value>
                    <fullName>Denver</fullName>
                </value>
                <value>
                    <fullName>Detroit</fullName>
                </value>
                <value>
                    <fullName>Headquarters</fullName>
                </value>
                <value>
                    <fullName>Jacksonville</fullName>
                </value>
                <value>
                    <fullName>Kansas City</fullName>
                </value>
                <value>
                    <fullName>Little Rock</fullName>
                </value>
                <value>
                    <fullName>Los Angeles</fullName>
                </value>
                <value>
                    <fullName>Memphis</fullName>
                </value>
                <value>
                    <fullName>Miami</fullName>
                </value>
                <value>
                    <fullName>Milwaukee</fullName>
                </value>
                <value>
                    <fullName>New Hampshire</fullName>
                </value>
                <value>
                    <fullName>New Orleans</fullName>
                </value>
                <value>
                    <fullName>New York City</fullName>
                </value>
                <value>
                    <fullName>Orlando</fullName>
                </value>
                <value>
                    <fullName>Philadelphia</fullName>
                </value>
                <value>
                    <fullName>Providence</fullName>
                </value>
                <value>
                    <fullName>Sacramento</fullName>
                </value>
                <value>
                    <fullName>San Antonio</fullName>
                </value>
                <value>
                    <fullName>San Jose/Silicon Valley</fullName>
                </value>
                <value>
                    <fullName>Seattle/King County</fullName>
                </value>
                <value>
                    <fullName>Tulsa</fullName>
                </value>
                <value>
                    <fullName>Washington, D.C.</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

classes/SessionInterventionBulkUploadContrTest.cls
@isTest
public with sharing class SessionInterventionBulkUploadContrTest {
    private static Account school;
    private static Section__c section;
    private static List<Student__c> students;
    private static Skill__c skill;

    private static testmethod void testConstructor(){
        test.startTest();
        SessionInterventionBulkUploadController controller = new SessionInterventionBulkUploadController();
        system.assertEquals(false, controller.showDownloadTemplate);
        test.stopTest();
    }

    static testMethod void myUnitTest(){
        setupData();
        Test.setCurrentPage(Page.SessionInterventionBulkUpload);
        Test.startTest();
            SessionInterventionBulkUploadController controller = new SessionInterventionBulkUploadController();
            system.assertEquals(1, controller.schools.size(),'Expected the school list to contain 1 entry only');
            controller.selectedSchool = controller.schools[0].getValue();
            controller.changeSchool();
            System.assertEquals(1, controller.staff.size(),'Expected only one staff to display');
            controller.selectedStaff = controller.staff[0].getValue();
            controller.changeStaff();
            System.assertEquals(1, controller.sections.size(),'Expected only one section to display');
            controller.selectedSection = controller.sections[0].getValue();
            controller.changeSection();
            System.assertEquals(2, controller.resultsData.size());
            controller.toggleSortDirection();
            controller.resultsData[0].isChecked = true;
            controller.confirmSelectedStudents();
            System.assertEquals(2, controller.resultsData.size());
            System.assertEquals(true, controller.showDownloadTemplate);
            controller.prepareStudentsTemplate();
            System.assertEquals(1, controller.newISRs.size());
            controller.resetPage();
            System.assertEquals(true, controller.showImportSection);
        Test.stopTest();
    }

    static testMethod void saveForExportTest(){
        setupData();
        Test.setCurrentPage(Page.SessionInterventionBulkUpload);
        Test.startTest();
        SessionInterventionBulkUploadController controller = new SessionInterventionBulkUploadController();
        controller.resultsData[0].isChecked = true;
        controller.resultsData[1].isChecked = true;
        controller.confirmSelectedStudents();
        PageReference pref = controller.saveForExport();
        system.assertEquals(pref.getURL(), Page.SessionInterventionBulkUploadExport.getURL());
        PageReference pref2 = controller.startSessionImport();
        system.assertEquals(pref.getURL(), Page.SessionInterventionBulkUploadExport.getURL());
        Test.stopTest();
    }

    static testMethod void importStudentsTest(){
        setupData();
        SessionInterventionBulkUploadController controller = new SessionInterventionBulkUploadController();
        controller.csvData = '';
        String importData = 'Intervention Session Results,Generated 6-11-2021,,,,,\n' +
                'Student Internal Id, Student USID, Student Id, Student Name, *REQ* Date, *REQ* Amount of Time (in minutes) (Amount_of_Time__c), Exit Ticket (Exit_Ticket__c)\n' +
                + students[0].Id + ',082402M909,CY-736701,"Delcastillo, Rudy",06/21/2021,34,yes\n' +
                + students[1].Id + ',082402M922,CY-736714,"Flemings, Tena",06/22/2021,36,no';

        test.startTest();
            PageReference pref = controller.startImport();
            system.assertEquals(pref.getURL(), Page.SessionInterventionBulkUploadImport.getURL());
            controller.fileBlob = Blob.valueOf(importData);
            importData = '';
            controller.fileName = 'testData.csv';
            controller.fileContentType = 'text/csv';
            controller.processInput();
            System.assertEquals(2, controller.createdSessions.size());
            controller.saveSessionsForExport();
            System.assertEquals(true, controller.showImportSessionsButton);
            PageReference pref1 = controller.exportSessionTemplate();
            system.assertEquals(pref1.getURL(), Page.SessionInterventionBulkUploadExport.getURL());
            controller.csvData = '';
            importData = 'Intervention Sessions,Generated 6-16-2021,,,,,,,,\n' +
                    'Session Internal ID, Session ID, Date, Add\'l Comments for Session (Comments__c), All avenues (All_avenues__c), Primary Skill (Skill_Primary__c), Other Skills (Skills_Covered_for_the_Session__c), Site Details (Site_Details__c), Session Type (Session_Type__c), Session Format (Session_Format__c)\n' +
                    + controller.createdSessions[0].Id + ',IS-1507330,2021-06-09 00:00:00,test comment 1,In-Person Service,Critical Thinking,,Option 1,Small Group,Push In\n' +
                    + controller.createdSessions[1].Id + ',IS-1507329,2021-06-10 00:00:00,test comment 2,Virtual Service,Decision Making,,Option 2,Small Group,Pull Out';
            controller.fileBlob = Blob.valueOf(importData);
            importData = '';
            controller.fileName = 'testData.csv';
            controller.fileContentType = 'text/csv';
            controller.processSessionsInput();
            System.assertEquals(2, controller.createdSessions.size());
            System.assertEquals(true, controller.showUpdatedSessions);
        test.stopTest();
    }

    static void setupData(){
        String category1 = 'SEL/Behavior and Attendance Interventions';
        skill = new Skill__c();
        skill.Name = 'Self-Awareness: Identifying strengths and weaknesses';
        skill.Category__c = category1;
        Skill__c skill1 = new Skill__c(
                Name = 'Critical Thinking',
                Category__c = category1
        );
        Skill__c skill2 = new Skill__c(
                Name = 'Decision Making',
                Category__c = category1
        );
        List<Skill__c> skills = new List<Skill__c>{skill, skill1, skill2};
        insert skills;
        TestDataUtil.setupSharingControls();
        TestDataUtil.setupTime();
        school = TestDataUtil.createSchool('ApexTestSchool1');
        school.Site__c = 'Boston';
        insert school;

        TestDataUtil.schoolList.add(school);
        TestDataUtil.setupSetupRecord();

        List<Indicator_Area__c> ia = TestDataUtil.createIndicatorAreas();
        insert ia;

        List<Program__c> programs = TestDataUtil.createPrograms(1,true,ia[0]);
        programs.addAll(TestDataUtil.createPrograms(1,true,ia[1]));
        programs.addAll(TestDataUtil.createPrograms(1,false,ia[2]));
        programs.addAll(TestDataUtil.createPrograms(1,false,ia[3]));
        insert programs;
        Account_Program__c accProg = TestDataUtil.createAccountProgram(school, programs[0]);
        insert accProg;
        students = TestDataUtil.createStudents(2, school);
        insert students;

        Contact c = TestDataUtil.createContact('ApexTest','User',null);
        insert c;
        Staff__c staff = TestDataUtil.createStaff(c,school,1);
        insert staff;
        section = TestDataUtil.createSections_WithoutInsert(1,school, accProg, staff, programs[0])[0];
        section.Start_Date__c = Date.newInstance(2021, 6, 15);
        insert section;

        insert TestDataUtil.createStudentSections_WithoutInsert(new List<Section__c>{section}, new List<List<Student__c>>{students});
    }

}