objects/Account_Program__c.object
<CustomObject>
    <description>The Account/Program object is part of the Interventions App and links Programs and Schools/Accounts.  This linking occurs in the Interventions Setup when a school selects which interventions Programs they will enroll in for a specific year.  This object tracks the relationships of Programs and Schools and whether the Programs are active.</description>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Is this Program active for this School in this year?</inlineHelpText>
        <label>Active?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Program__c</fullName>
        <inlineHelpText>This field joins the Account/Program record to the correct intervention Program</inlineHelpText>
        <label>Program</label>
        <referenceTo>Program__c</referenceTo>
        <relationshipLabel>School Programs</relationshipLabel>
        <relationshipName>Accounts_Programs</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Account/Program</label>
    <nameField>
        <label>School Program Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Accounts/Programs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Indicator_Area__c.object
<CustomObject>
    <description>This object is part of the Interventions app. Indicator Area defines a high-level intervention focus area (e.g., Behavior, Attendance, English Language Arts). Students are assigned to Indicator Areas in order to schedule them in Intervention Programs and Sections.</description>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>true</defaultValue>
        <inlineHelpText>Indicates whether or not this indicator area is available to assign to students on the Add Students to Indicator Areas screen. If you uncheck this field, SchoolForce deactivates any associated Program, Staff/Section, and Student/Section records.</inlineHelpText>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <label>Indicator Area</label>
    <nameField>
        <label>Indicator Area</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Indicator Areas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Indicator_Area_Student__c.object
<CustomObject>
    <description>The Indicator Area/Student object is a joiner object that associates an Indicator Area and a Student.</description>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>true</defaultValue>
        <inlineHelpText>Is the Indicator Area associated to this Student active? If this box is unchecked then the Student no longer requires intervention in this area.</inlineHelpText>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Indicator_Area__c</fullName>
        <inlineHelpText>This field joins the Indicator Area/Student record to the correct Indicator Area</inlineHelpText>
        <label>Indicator Area</label>
        <referenceTo>Indicator_Area__c</referenceTo>
        <relationshipLabel>Indicator Area/Student</relationshipLabel>
        <relationshipName>Indicator_Area_Student</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Student__c</fullName>
        <inlineHelpText>This field joins the Indicator Area/Student record to the correct Student</inlineHelpText>
        <label>Student</label>
        <referenceTo>Student__c</referenceTo>
        <relationshipLabel>Indicator Area/Student</relationshipLabel>
        <relationshipName>Indicator_Area_Student</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Indicator Area/Student</label>
    <nameField>
        <displayFormat>IA/S -{000}</displayFormat>
        <label>IA/Student ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Indicator Area/Student</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Program__c.object
<CustomObject>
    <description>Program is an Intervention object. Intervention Programs are aligned with Indicator Areas and are a high level set of activities with defined dosage goals. Each Program has its own frequency, target dosage, and recommended time per session. An example Program is one-on-one reading.</description>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>If this box is checked then the Program is currently available for use.</inlineHelpText>
        <label>Active?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Indicator_Area__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>You must select an Indicator Area that aligns with this Program.</inlineHelpText>
        <label>Indicator Area</label>
        <referenceTo>Indicator_Area__c</referenceTo>
        <relationshipLabel>Programs</relationshipLabel>
        <relationshipName>Programs</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Program</label>
    <nameField>
        <label>Program Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/Section__c.object
<CustomObject>
    <fields>
        <fullName>Account_Program__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>What intervention Program is this intervention Section associated to?</inlineHelpText>
        <label>School Program</label>
        <lookupFilter>
            <active>false</active>
            <filterItems>
                <field>Account_Program__c.Program__c</field>
                <operation>equals</operation>
                <valueField>$Source.Program__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account_Program__c</referenceTo>
        <relationshipLabel>Sections</relationshipLabel>
        <relationshipName>Sections</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Check this box if the section is a currently active section</description>
        <inlineHelpText>Check this box if the section is a currently active section</inlineHelpText>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Indicator_Area__c</fullName>
        <formula>Program__r.Indicator_Area__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>What Indicator Area is this Program addressing? This field cannot be modified here.</inlineHelpText>
        <label>Indicator Area</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Program__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>What intervention Program is this Intervention Section for?</inlineHelpText>
        <label>Program</label>
        <referenceTo>Program__c</referenceTo>
        <relationshipLabel>Sections</relationshipLabel>
        <relationshipName>Sections</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Section_Exit_Reason__c</fullName>
        <label>Section Exit Reason</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>SS_Exit_Reason</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Section__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Recursive lookup for groups</description>
        <label>Section</label>
        <referenceTo>Section__c</referenceTo>
        <relationshipLabel>Groups in Section</relationshipLabel>
        <relationshipName>Sections1</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Section</label>
    <nameField>
        <label>Section Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sections</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Student__c.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>true</defaultValue>
        <inlineHelpText>Indicates whether or not this Student record is active. If checked, then this is the current Student record. If unchecked, this is an old Student record.</inlineHelpText>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Comments__c</fullName>
        <inlineHelpText>Displays the comments teachers enter for the student using the Overall Comments Wizard. This text displays on elementary school report cards and progress reports.</inlineHelpText>
        <label>Comments</label>
        <length>32000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Section__c</fullName>
        <inlineHelpText>Displays the student&apos;s current homeroom name or room number. This field can be used for reporting purposes.</inlineHelpText>
        <label>Current Homeroom</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Student__c</fullName>
        <inlineHelpText>Displays the student&apos;s middle name.</inlineHelpText>
        <label>Student Middle Name</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <label>Student</label>
    <nameField>
        <label>Student Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Students</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Student_Section__c.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Amount_of_Time__c</fullName>
        <label>Amount of time per section</label>
        <summarizedField>Intervention_Session_Result__c.Amount_of_Time__c</summarizedField>
        <summaryForeignKey>Intervention_Session_Result__c.Student_Section__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Enrollment_End_Date__c</fullName>
        <label>Enrollment End Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Enrollment_Start_Date__c</fullName>
        <label>Enrollment Start Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Program__c</fullName>
        <formula>CASESAFEID(Section__r.Program__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Program</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Section_Exit_Reason__c</fullName>
        <label>Section Exit Reason</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Accidental Enrollment</fullName>
                </value>
                <value>
                    <fullName>School Year ended</fullName>
                </value>
                <value>
                    <fullName>Deactivated by trigger.</fullName>
                </value>
                <value>
                    <fullName>ACM no longer available</fullName>
                </value>
                <value>
                    <fullName>Student no longer available</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Section__c</fullName>
        <label>Section</label>
        <referenceTo>Section__c</referenceTo>
        <relationshipLabel>Student</relationshipLabel>
        <relationshipName>Student_Section</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Student__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Student</label>
        <referenceTo>Student__c</referenceTo>
        <relationshipLabel>Section</relationshipLabel>
        <relationshipName>Student_Section</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Student/Section</label>
    <nameField>
        <displayFormat>SS-{000000}</displayFormat>
        <label>Student/Section ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Student/Section</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

globalValueSets/SS_Exit_Reason.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Accidental Enrollment</fullName>
    </customValue>
    <customValue>
        <fullName>Student no longer available</fullName>
    </customValue>
    <customValue>
        <fullName>School Year ended</fullName>
    </customValue>
    <customValue>
        <fullName>ACM no longer available</fullName>
    </customValue>
    <customValue>
        <fullName>Deactivated by trigger.</fullName>
    </customValue>
    <customValue>
        <fullName>Teacher scheduling change/reassignment</fullName>
        <isActive>false</isActive>
        <label>Teacher scheduling change/reassignment</label>
    </customValue>
    <customValue>
        <fullName>Chronic absenteeism</fullName>
        <isActive>false</isActive>
        <label>Chronic absenteeism</label>
    </customValue>
    <customValue>
        <fullName>Student referred for more intensive services by other personnel</fullName>
        <isActive>false</isActive>
        <label>Student referred for more intensive services by other personnel</label>
    </customValue>
    <customValue>
        <fullName>Transferred to another City Year school</fullName>
        <isActive>false</isActive>
        <label>Transferred to another City Year school</label>
    </customValue>
    <customValue>
        <fullName>Behavior significantly distracts sessions</fullName>
        <isActive>false</isActive>
        <label>Behavior significantly distracts sessions</label>
    </customValue>
    <customValue>
        <fullName>Student scheduling change prevents regular participation</fullName>
        <isActive>false</isActive>
        <label>Student scheduling change prevents regular participation</label>
    </customValue>
    <customValue>
        <fullName>Student met exit criteria</fullName>
        <isActive>false</isActive>
        <label>Student met exit criteria</label>
    </customValue>
    <customValue>
        <fullName>Student completed participation criteria, though should be reenrolled in subsequent section</fullName>
        <isActive>false</isActive>
        <label>Student completed participation criteria, though should be reenrolled in subsequent section</label>
    </customValue>
    <customValue>
        <fullName>Corps member has left the school or service</fullName>
        <isActive>false</isActive>
        <label>Corps member has left the school or service</label>
    </customValue>
    <masterLabel>SS Exit Reason</masterLabel>
</GlobalValueSet>

classes/TestSectionDetailComponent.cls
@isTest
private class TestSectionDetailComponent{

	private static TestDataUtil.schoolWrapper SW;
	private static Section__c section;
	private static List<Student__c> enrolledStudents;
	/* KC: This is old test class from the Interventions package. You can delete it if you want.
	private static void setupTestData(){
		TestDataUtil.setupData(1);
		SW = TestDataUtil.testData[0];
		
		Indicator_Area__c ia = TestDataUtil.createIndicatorAreas(1)[0];
		insert ia;
		List<Indicator_Area_Student__c> iaStu =  TestDataUtil.createIAStudents (SW.students,ia.Id);
		insert iaStu;
		Program__c program = TestDataUtil.createPrograms(1,true,ia)[0];
		insert program;
		Account_Program__c accProg = TestDataUtil.createAccountProgram(SW.school, program);
		insert accProg;
		enrolledStudents = new List<Student__c>();
		List<Student__c> notEnrolledStudents = new List<Student__c>();
		integer cnt = 0;
		for(Student__c s :SW.students) {
			if(cnt < SW.students.size()/2) {
				enrolledStudents.add(s);
			} else notEnrolledStudents.add(s);
			cnt++;
		}

		List<Section__c> sections = TestDataUtil.createSections(2,SW.school, accProg, new List<List<Student__c>>{enrolledStudents,notEnrolledStudents}, SW.cmDirect.staffRecord, program);
		section = sections[0];
	}

	static testMethod void testConstructor(){
		setupTestData();
		Test.setCurrentPage(Page.IM_SectionDetail);
		ApexPages.currentPage().getParameters().put('SectionID', section.ID);

		Test.startTest();
			sectionDetailExtension controller = new sectionDetailExtension();
			system.assertEquals(section.ID, controller.selectedSection.ID,'Expected the provided section to load');
			system.assertEquals(5, controller.enrolledStudents.size(),'Expected there to be 5 students in the section.');
			system.assertEquals(false, ApexPages.hasMessages());
		Test.stopTest();
	}

	static testMethod void testAddStudents(){
		setupTestData();
		Test.setCurrentPage(Page.IM_SectionDetail);
		ApexPages.currentPage().getParameters().put('SectionID', section.ID);

		Test.startTest();
			sectionDetailExtension controller = new sectionDetailExtension();
			system.assertEquals(5, controller.enrolledStudents.size(),'Expected 5 students to be enrolled in the section.');

			controller.startAddStudents();
			system.assertEquals(false, controller.availableStudents.isEmpty(),'Expected there to be at least one available student.');

			controller.availableStudents[0].checked = true;
			controller.addStudents();

			controller.selectedStudents[0].checked = true;
			controller.removeStudents();

			controller.availableStudents[0].checked = true;
			ID reactivatedStudentID = controller.availableStudents[0].studentID;
			controller.addStudents();
			
			system.assertEquals(1, controller.selectedStudents.size());

			controller.studentSectionHolder.Enrollment_Start_Date__c = system.today().addDays(1);

			controller.enrollStudents();
			system.assertEquals(6, controller.enrolledStudents.size(),'Expected there to be 6 students now.');

			for(sectionDetailExtension.studentEnrollmentWrapper sew: controller.enrolledStudents){
				if(sew.stuSecRec.Student__c == reactivatedStudentID){
					system.assertEquals(true, sew.stuSecRec.Active__c, 'Expected the student to be active.');
				}
			}

			system.assertEquals(1, [select id from Student_Section__c where Student__c=: reactivatedStudentID and Section__c =: section.id].size());
		Test.stopTest();
	}

	static testMethod void testAddStudentFilters(){
		setupTestData();
		Test.setCurrentPage(Page.IM_SectionDetail);
		ApexPages.currentPage().getParameters().put('SectionID', section.ID);

		Test.startTest();
			sectionDetailExtension controller = new sectionDetailExtension();
			system.assertEquals(5, controller.enrolledStudents.size(),'Expected 5 students to be enrolled in the section.');

			controller.startAddStudents();
			system.assertEquals(false, controller.availableStudents.isEmpty(),'Expected there to be at least one available student.');

			controller.selectedGrade = controller.grades[0].getValue();
			controller.changeGrade();

			controller.selectedGrade = 'null';
			controller.changeGrade();

			controller.selectedIndicatorArea = controller.indicatorAreas[0].getValue();
			controller.changeIndicatorArea();

			controller.selectedFilterSection = controller.filterSections[0].getValue();
			controller.changeSection();
			system.assertEquals('null', controller.selectedIndicatorArea);

			controller.selectedFilterSection = 'null';
			controller.changeSection();
		Test.stopTest();
	}

	static testMethod void testExitStudents(){
		setupTestData();
		Test.setCurrentPage(Page.IM_SectionDetail);
		ApexPages.currentPage().getParameters().put('SectionID', section.ID);

		Test.startTest();
			sectionDetailExtension controller = new sectionDetailExtension();
			system.assertEquals(5, controller.enrolledStudents.size(),'Expected 5 students to be enrolled in the section.');

			controller.enrolledStudents[0].checked = true;

			controller.startExitStudents();
			controller.studentSectionHolder.Enrollment_End_Date__c = system.today().addDays(3);
			controller.studentSectionHolder.Section_Exit_Reason__c = 'Testing the exit';

			controller.finishExitStudents();
		Test.stopTest();
	}

	static testMethod void addTimetTest() {
		setupTestData();

		Test.setcurrentPage(Page.IM_SectionDetail);
		ApexPages.currentPage().getParameters().put('SectionID',section.id);
		Test.startTest();
			System.runAs(TestDataUtil.testData[0].sysAdmin.userRecord){
				sectionDetailExtension controller = new sectionDetailExtension();
				
				controller.enrolledStudents[0].checked = true;
				controller.enrolledStudents[1].checked = true;
				controller.enrolledStudents[2].checked = true;
				controller.enrolledStudents[3].checked = true;
				controller.enrolledStudents[4].checked = true;
				controller.addStudentstoAddTime();
				system.assertEquals(5, controller.studentsToAddTime.size());

				controller.ISHolder.Date__c = Date.today();
				controller.ISHolder.Skills__c = 'Test Skills';
				controller.ISHolder.Comments__c = 'Test Comments';
				controller.ISRHolder.Amount_of_Time__c = 10;
				controller.addTime();
				for(sectionDetailExtension.studentEnrollmentWrapper sew: controller.enrolledStudents){
					system.assertEquals(10, sew.Dosage);
				}
				
				controller.ISHolder.Date__c = Date.today();
				controller.getSessionDetails();
				controller.ISHolder.Skills__c = 'Test Skills';
				controller.ISHolder.Comments__c = 'Test Comments';
				controller.ISRHolder.Amount_of_Time__c = 15;
				controller.addTime();
				for(sectionDetailExtension.studentEnrollmentWrapper sew: controller.enrolledStudents){
					system.assertEquals(15, sew.Dosage);
				}
			}
		Test.stopTest();
	}
	*/
}