objects/Account.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <label>Active</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>No</fullName>
                </value>
                <value>
                    <fullName>Yes</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Reference_Id__c</fullName>
        <externalId>true</externalId>
        <label>Reference Id</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <recordTypes>
        <fullName>School</fullName>
        <active>true</active>
        <description>This record type is for physical school locations.</description>
        <label>School</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Account_Program__c.object
<CustomObject>
    <description>The Account/Program object is part of the Interventions App and links Programs and Schools/Accounts.  This linking occurs in the Interventions Setup when a school selects which interventions Programs they will enroll in for a specific year.  This object tracks the relationships of Programs and Schools and whether the Programs are active.</description>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Is this Program active for this School in this year?</inlineHelpText>
        <label>Active?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Current_Year_ID__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>The year that this record is (was) active for</inlineHelpText>
        <label>Current Year ID</label>
        <referenceTo>Time_Element__c</referenceTo>
        <relationshipLabel>Accounts/Programs</relationshipLabel>
        <relationshipName>Accounts_Programs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Program__c</fullName>
        <inlineHelpText>This field joins the Account/Program record to the correct intervention Program</inlineHelpText>
        <label>Program</label>
        <referenceTo>Program__c</referenceTo>
        <relationshipLabel>School Programs</relationshipLabel>
        <relationshipName>Accounts_Programs</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Reference_ID__c</fullName>
        <externalId>true</externalId>
        <inlineHelpText>This ID is used to prevent duplicate Account/Program records. It should not be changed.</inlineHelpText>
        <label>Reference ID</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>School__c</fullName>
        <inlineHelpText>This field joins the Account/Program record to the correct School.</inlineHelpText>
        <label>School</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Accounts/Programs</relationshipLabel>
        <relationshipName>Accounts_Programs</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Account/Program</label>
    <nameField>
        <label>School Program Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Accounts/Programs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Indicator_Area__c.object
<CustomObject>
    <description>This object is part of the Interventions app. Indicator Area defines a high-level intervention focus area (e.g., Behavior, Attendance, English Language Arts). Students are assigned to Indicator Areas in order to schedule them in Intervention Programs and Sections.</description>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>true</defaultValue>
        <inlineHelpText>Indicates whether or not this indicator area is available to assign to students on the Add Students to Indicator Areas screen. If you uncheck this field, SchoolForce deactivates any associated Program, Staff/Section, and Student/Section records.</inlineHelpText>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <label>Indicator Area</label>
    <nameField>
        <label>Indicator Area</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Indicator Areas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Program__c.object
<CustomObject>
    <description>Program is an Intervention object. Intervention Programs are aligned with Indicator Areas and are a high level set of activities with defined dosage goals. Each Program has its own frequency, target dosage, and recommended time per session. An example Program is one-on-one reading.</description>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>If this box is checked then the Program is currently available for use.</inlineHelpText>
        <label>Active?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Indicator_Area__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>You must select an Indicator Area that aligns with this Program.</inlineHelpText>
        <label>Indicator Area</label>
        <referenceTo>Indicator_Area__c</referenceTo>
        <relationshipLabel>Programs</relationshipLabel>
        <relationshipName>Programs</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Program</label>
    <nameField>
        <label>Program Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/Setup__c.object
<CustomObject>
    <description>This object is used to setup Schoolforce and is referenced in multiple pieces of code.  There should be one setup object per school.</description>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Is this school setup active for this school year?</inlineHelpText>
        <label>Active?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>School__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>School</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1 OR 2</booleanFilter>
            <filterItems>
                <field>Account.RecordType.Name</field>
                <operation>equals</operation>
                <value>School</value>
            </filterItems>
            <filterItems>
                <field>Account.RecordType.Name</field>
                <operation>equals</operation>
                <value>Summer School</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Setup</relationshipLabel>
        <relationshipName>Setup</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Year__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>School Year associated to the Setup</description>
        <label>Year</label>
        <referenceTo>Time_Element__c</referenceTo>
        <relationshipLabel>Setup (Year)</relationshipLabel>
        <relationshipName>Setup_Year</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Setup</label>
    <nameField>
        <displayFormat>S-{0}</displayFormat>
        <label>Setup ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Setup</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

classes/TestSchoolProgramLinkTriggers.cls
@isTest
private class TestSchoolProgramLinkTriggers {
	
	static testMethod void TestSchoolCreate() {
		TestDataUtil.setupData(1);
		TestDataUtil.SchoolWrapper SW = TestDataUtil.testData[0];
		Indicator_Area__c ia = TestDataUtil.createIndicatorAreas(1)[0];
		insert ia;
		List<Program__c> addPrograms = TestDataUtil.createPrograms(5,true,ia);
		insert addPrograms;
		
		Account a = new Account();
		a.name = 'school';
		a.RecordTypeId = [SELECT id FROM RecordType WHERE DeveloperName='School' and sObjectType='Account'].id;
		insert a;
		a  = [select (select id from Accounts_Programs__r) from Account where id=:a.id];
		
		System.assertEquals(5, a.Accounts_Programs__r.size());
	}
	
	static testMethod void TestReqProgramCreate() {
		TestDataUtil.setupData(5);
		Indicator_Area__c ia = TestDataUtil.createIndicatorAreas(1)[0];
		insert ia;
		Program__c program = TestDataUtil.createPrograms(1,true,ia)[0];
		insert program;
		
		program  = [select (select id from Accounts_Programs__r) from Program__c where id=:program.id];
		System.assertEquals(5,program.Accounts_Programs__r.size());
	}
	
	 static testMethod void TestConnectionDelete() {
		TestDataUtil.setupData(1);
		TestDataUtil.SchoolWrapper SW = TestDataUtil.testData[0];
		Indicator_Area__c ia = TestDataUtil.createIndicatorAreas(1)[0];
		insert ia;
		List<Program__c> addPrograms = TestDataUtil.createPrograms(5,true,ia);
		insert addPrograms;
		
		Account a = new Account();
		a.name = 'school';
		a.RecordTypeId = [SELECT id FROM RecordType WHERE DeveloperName='School' and sObjectType='Account'].id;
		insert a;
		
		List<Account_Program__c> connections  = [select id from Account_Program__c where School__c=:a.id];
		System.assertEquals(5,connections.size());
	
		try{
			delete connections;
		}
		catch(Exception e){
		}
		
		connections  = [select id from Account_Program__c where School__c=:a.id];
		System.assertEquals(5,connections.size());
	}

	static testMethod void testAssignSchoolYear(){
		TestDataUtil.setupData(1);
		TestDataUtil.SchoolWrapper SW = TestDataUtil.testData[0];
		Indicator_Area__c ia = TestDataUtil.createIndicatorAreas(1)[0];
		insert ia;
		Program__c program = TestDataUtil.createPrograms(1,true,ia)[0];
		insert program;
		
		//delete setups associated with school to check error message
		List<Setup__c> setups = [SELECT id FROM Setup__c WHERE School__c=:SW.school.id];
		delete setups;
		
		Account_Program__c ap = TestDataUtil.createAccountProgram(SW.school, program);
		Database.SaveResult result = Database.insert(ap,false);
		system.assert(!result.isSuccess());
		system.assertEquals('There is no active setup for school with id: '+SW.school.id+'.  Please activate a setup for this school.', result.getErrors()[0].getMessage());
		
		//create a setup, but don't add a school year
		Setup__c setup = new Setup__c(School__c=SW.school.id, Active__c=true);
		insert setup;
		result = Database.insert(ap,false);
		system.assert(!result.isSuccess());
		system.assertEquals('There is no current school year for this school.  Please check that the active setup for '+SW.school.Name+' has an associated year record.', result.getErrors()[0].getMessage());
		
		//add a school year, should succeed
		setup.Year__c = TestDataUtil.masterYear.id;
		update setup;
		result = Database.insert(ap,false);
		system.assert(result.isSuccess());
	}
	
	static testMethod void testReferenceId(){
		TestDataUtil.setupData(1);
		TestDataUtil.SchoolWrapper SW = TestDataUtil.testData[0];
		Indicator_Area__c ia = TestDataUtil.createIndicatorAreas(1)[0];
		insert ia;
		Program__c program = TestDataUtil.createPrograms(1,true,ia)[0];
		insert program;
		
		Account_Program__c ap = TestDataUtil.createAccountProgram(SW.school, program);
		insert ap;
		ap = [SELECT Reference_ID__c FROM Account_Program__c WHERE id=:ap.id];
		system.assertEquals(SW.school.id+'_'+program.id+'_'+TestDataUtil.masterYear.id,ap.Reference_ID__c);
	}
	
	static testMethod void testNoYearChange(){
		TestDataUtil.setupData(1);
		TestDataUtil.SchoolWrapper SW = TestDataUtil.testData[0];
		Indicator_Area__c ia = TestDataUtil.createIndicatorAreas(1)[0];
		insert ia;
		Program__c program = TestDataUtil.createPrograms(1,true,ia)[0];
		insert program;
		
		Account_Program__c ap = TestDataUtil.createAccountProgram(SW.school, program);
		insert ap;
		ap.Current_Year_ID__c = null;
		Database.SaveResult result = Database.update(ap,false);
		system.assert(!result.isSuccess());
		system.assertEquals('School year on Account/Program cannot be changed.',result.getErrors()[0].getMessage());
	}
}