objects/Account.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <label>Active</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>No</fullName>
                </value>
                <value>
                    <fullName>Yes</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Is_Active__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Is Active?</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>true</defaultValue>
        <inlineHelpText>Schools/organizations can choose to use this field when a Contact record is active. When Contact records are created through SchoolForce Setup, this check box is selected.</inlineHelpText>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Is_Active__c</fullName>
        <defaultValue>true</defaultValue>
        <inlineHelpText>Do not use this field; it is no longer used by SchoolForce.</inlineHelpText>
        <label>Is Active? *Retired*</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Setup__c.object
<CustomObject>
    <description>This object is used to setup Schoolforce and is referenced in multiple pieces of code.  There should be one setup object per school.</description>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Is this school setup active for this school year?</inlineHelpText>
        <label>Active?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Calculation_Type__c</fullName>
        <description>Choose a calculation type for standard based grading.</description>
        <inlineHelpText>Select a calculation type for standard-based grading. This must be selected if using standards - based grading.</inlineHelpText>
        <label>Calculation Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Mean</fullName>
                </value>
                <value>
                    <fullName>Power Law</fullName>
                </value>
                <value>
                    <fullName>Highest</fullName>
                </value>
                <value>
                    <fullName>Most Recent</fullName>
                </value>
                <value>
                    <fullName>Law of Decaying Average</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Data_Activated__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Data Activated</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Group_Based__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>If Checked, schedule is based on students moving between classes as a group, enabling Schedule Templates &amp; scheduling in a Group Agenda view;
If Unchecked, school schedule is based on periods, enabling Period Templates &amp; scheduling in a Grid View</inlineHelpText>
        <label>Group Based ?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Law_of_Decaying_Average_Weight__c</fullName>
        <description>This field is only used for the standard calculation type: Law of Decaying Average.  A value of 1.00 to 0.00 is desired in determining the weight.</description>
        <label>Law of Decaying Average Weight</label>
        <precision>6</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Passing_Grade_Threshold__c</fullName>
        <inlineHelpText>Select the grade threshold (0-100 scale) that defines passing for this school.  Any section grade that is calculated below this number will display in the Gradebook UI as red.  Any number between this and the &quot;On Track&quot; number will yellow.</inlineHelpText>
        <label>Passing Grade Threshold</label>
        <precision>5</precision>
        <scale>1</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Published__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Published</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Rolling_Standard_Grade__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Controls whether standard grade calculations will carry over from reporting period to reporting period or are independently calculated.</description>
        <inlineHelpText>Select if you want a standard grade to include the assignment grades from the first through the current reporting period (e.g., a specific standard in Q3 is calculated using the grades from Q1-Q3).</inlineHelpText>
        <label>Rolling Standard Grade?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>School__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>School</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1 OR 2</booleanFilter>
            <filterItems>
                <field>Account.RecordType.Name</field>
                <operation>equals</operation>
                <value>School</value>
            </filterItems>
            <filterItems>
                <field>Account.RecordType.Name</field>
                <operation>equals</operation>
                <value>Summer School</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Setup</relationshipLabel>
        <relationshipName>Setup</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Standards_Based_Grading__c</fullName>
        <defaultValue>false</defaultValue>
        <description>School-wide setting that will reduce config time if set to false</description>
        <inlineHelpText>Select if school wants to grade standards.  If set to false, users will enter traditional grades without association to standards or standard grades.  If checked, users in the Hybrid or Standard ONLY Gradebook can grade standards.</inlineHelpText>
        <label>Standards Based Grading</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Standards_ONLY_Gradebook__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This should be checked if the Standards ONLY gradebook that was designed for ELH should be used.</description>
        <inlineHelpText>Is this school using the Standards ONLY Gradebook? This Gradebook allows users to enter only standard grades.  Please see additional documentation for more information.</inlineHelpText>
        <label>Standards ONLY Gradebook</label>
        <type>Checkbox</type>
    </fields>
    <label>Setup</label>
    <nameField>
        <displayFormat>S-{0}</displayFormat>
        <label>Setup ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Setup</pluralLabel>
    <recordTypes>
        <fullName>Published</fullName>
        <active>true</active>
        <description>For Published Setups - Not Editable</description>
        <label>Published</label>
    </recordTypes>
    <sharingModel>Read</sharingModel>
</CustomObject>

classes/Setup_Utils.cls
public without sharing class Setup_Utils {
	public static void deactivateOldSetups(List<Setup__c> newSetups, Map<ID, Setup__c> oldSetupMap){
		Set<ID> schoolIDs = new Set<ID>();
		for(Setup__c setup:newSetups){
			Setup__c oldSetup;
			if(oldSetupMap!= null){
				oldSetup = oldSetupMap.get(setup.ID);
			}

			if((setup.Active__c && oldSetup == null) || (setup.Active__c && setup.Active__c != oldSetup.Active__c)){
				schoolIDs.add(setup.School__c);
			}
		}

		core_TriggerUtils.deactivateSchoolSetups(schoolIds);
	}

	public static void cloneOldSetupConfiguration(List<Setup__c> newSetups){
		List<Setup__c> setupsToCloneData = new List<Setup__c>();
		Set<ID> schoolIDs = new Set<ID>();

		for(Setup__c s:newSetups){
			schoolIDs.add(s.School__c);
		}

		Map<ID, Account> accountMap = new Map<ID, Account>([select id, Is_Active__c, (select id from Setup__r) from Account where ID IN:schoolIDs]);

		for(Setup__c s:newSetups){
			if(accountMap.get(s.School__c).Is_Active__c && accountMap.get(s.School__c).Setup__r.size() > 1){
				setupsToCloneData.add(s);
			}
		}

		if(!setupsToCloneData.isEmpty()){
			Batch_CloneSetupData batch = new Batch_CloneSetupData(setupsToCloneData);
			Database.executeBatch(batch,1);
		}
	}

	public static void validateData(List<Setup__c> newSetups, Map<ID, Setup__c> oldSetupMap){
		for(Setup__c setup:newSetups){
			Setup__c oldSetup = oldSetupMap.get(setup.ID);
			if(setup.Published__c){
				if(setup.Group_Based__c != oldSetup.Group_Based__c){
					setup.Group_Based__c.addError('The group based field is not editable after setup has been published.');
				}

				if(setup.Standards_Based_Grading__c != oldSetup.Standards_Based_Grading__c ||
						setup.Standards_ONLY_Gradebook__c != oldSetup.Standards_ONLY_Gradebook__c){
					setup.addError('Once a setup has been published, it\'s gradbook type cannot be changed.');
				}

				if(!setup.Active__c && setup.Data_Activated__c){
					if(setup.Passing_Grade_Threshold__c != oldSetup.Passing_Grade_Threshold__c){
						setup.Passing_Grade_Threshold__c.addError('This setup is from a past year. You can no longer edit Passing Grade Threshold because it affects grade calculations in the past year. If you need to make a change, please contact the SchoolForce support team so that they can work with you to see if this change is possible.');
					}
					if(setup.Rolling_Standard_Grade__c != oldSetup.Rolling_Standard_Grade__c){
						setup.Rolling_Standard_Grade__c.addError('This setup is from a past year. You can no longer edit Rolling Standard Grade because it affects grade calculations in the past year. If you need to make a change, please contact the SchoolForce support team so that they can work with you to see if this change is possible.');
					}
					if(setup.Calculation_Type__c != oldSetup.Calculation_Type__c){
						setup.Calculation_Type__c.addError('This setup is from a past year. You can no longer edit Calculation Type because it affects grade calculations in the past year. If you need to make a change, please contact the SchoolForce support team so that they can work with you to see if this change is possible.');
					}
					if(setup.Law_of_Decaying_Average_Weight__c != oldSetup.Law_of_Decaying_Average_Weight__c){
						setup.Law_of_Decaying_Average_Weight__c.addError('This setup is from a past year. You can no longer edit Law of Decaying Average Weight because it affects grade calculations in the past year. If you need to make a change, please contact the SchoolForce support team so that they can work with you to see if this change is possible.');
					}
				}
			}
		}
	}

	public static void recalculateStandardGrades(List<Setup__c> newSetups, Map<ID, Setup__c> oldSetupMap){
		Set<ID> setupsToRecalc = new Set<ID>();
		for (Setup__c setup: newSetups){
			Setup__c oldSetup = oldSetupMap.get(setup.ID);
			if(setup.Calculation_Type__c != null && setup.Active__c){
				if(setup.Law_of_Decaying_Average_Weight__c != oldSetup.Law_of_Decaying_Average_Weight__c ||
						setup.Calculation_Type__c != oldSetup.Calculation_Type__c ||
						setup.Rolling_Standard_Grade__c != oldSetup.Rolling_Standard_Grade__c){
					setupsToRecalc.add(setup.ID);
				}
			}
		}
			
		if(!setupsToRecalc.isEmpty()) {
			Batch_StandardGradeRecalc bsg = new Batch_StandardGradeRecalc(setupsToRecalc);
			Database.executeBatch(bsg, 50);
		}
	}
}