objects/Account.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <label>Active</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>No</fullName>
                </value>
                <value>
                    <fullName>Yes</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <recordTypes>
        <fullName>School</fullName>
        <active>true</active>
        <description>This record type is for physical school locations.</description>
        <label>School</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Account_Program__c.object
<CustomObject>
    <description>The Account/Program object is part of the Interventions App and links Programs and Schools/Accounts.  This linking occurs in the Interventions Setup when a school selects which interventions Programs they will enroll in for a specific year.  This object tracks the relationships of Programs and Schools and whether the Programs are active.</description>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Is this Program active for this School in this year?</inlineHelpText>
        <label>Active?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Program__c</fullName>
        <inlineHelpText>This field joins the Account/Program record to the correct intervention Program</inlineHelpText>
        <label>Program</label>
        <referenceTo>Program__c</referenceTo>
        <relationshipLabel>School Programs</relationshipLabel>
        <relationshipName>Accounts_Programs</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Account/Program</label>
    <nameField>
        <label>School Program Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Accounts/Programs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>true</defaultValue>
        <inlineHelpText>Schools/organizations can choose to use this field when a Contact record is active. When Contact records are created through SchoolForce Setup, this check box is selected.</inlineHelpText>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Student__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>This field provides a link to the most recent Student record.</inlineHelpText>
        <label>Student</label>
        <referenceTo>Student__c</referenceTo>
        <relationshipLabel>Contacts</relationshipLabel>
        <relationshipName>Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <recordTypes>
        <fullName>Staff</fullName>
        <active>true</active>
        <description>This record type is for staff members.</description>
        <label>Staff</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Data_Load_Log__c.object
<CustomObject>
    <description>Logs information about data loads such as status and success/failure statistics.</description>
    <fields>
        <fullName>Batch_ID__c</fullName>
        <description>This is the id of the batch that the Data Load Log was created for</description>
        <label>Batch ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>End_Time__c</fullName>
        <description>Date/time this load finished processing.</description>
        <label>End Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Messages__c</fullName>
        <description>Any messages generated during the load.</description>
        <label>Messages</label>
        <length>32000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Status of this data load.</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Pending</fullName>
                </value>
                <value>
                    <fullName>Running</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Data Load Log</label>
    <nameField>
        <displayFormat>DLL-{0000000}</displayFormat>
        <label>Data Load Log #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Data Load Log</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Indicator_Area__c.object
<CustomObject>
    <description>This object is part of the Interventions app. Indicator Area defines a high-level intervention focus area (e.g., Behavior, Attendance, English Language Arts). Students are assigned to Indicator Areas in order to schedule them in Intervention Programs and Sections.</description>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>true</defaultValue>
        <inlineHelpText>Indicates whether or not this indicator area is available to assign to students on the Add Students to Indicator Areas screen. If you uncheck this field, SchoolForce deactivates any associated Program, Staff/Section, and Student/Section records.</inlineHelpText>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <label>Indicator Area</label>
    <nameField>
        <label>Indicator Area</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Indicator Areas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Program__c.object
<CustomObject>
    <description>Program is an Intervention object. Intervention Programs are aligned with Indicator Areas and are a high level set of activities with defined dosage goals. Each Program has its own frequency, target dosage, and recommended time per session. An example Program is one-on-one reading.</description>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>If this box is checked then the Program is currently available for use.</inlineHelpText>
        <label>Active?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Indicator_Area__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>You must select an Indicator Area that aligns with this Program.</inlineHelpText>
        <label>Indicator Area</label>
        <referenceTo>Indicator_Area__c</referenceTo>
        <relationshipLabel>Programs</relationshipLabel>
        <relationshipName>Programs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <inlineHelpText>This field is automatically updated based on whether your organization has setup approval processes for Programs.</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Pending</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Program</label>
    <nameField>
        <label>Program Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/Section__c.object
<CustomObject>
    <fields>
        <fullName>Account_Program__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>What intervention Program is this intervention Section associated to?</inlineHelpText>
        <label>School Program</label>
        <lookupFilter>
            <active>false</active>
            <filterItems>
                <field>Account_Program__c.Program__c</field>
                <operation>equals</operation>
                <valueField>$Source.Program__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account_Program__c</referenceTo>
        <relationshipLabel>Sections</relationshipLabel>
        <relationshipName>Sections</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Check this box if the section is a currently active section</description>
        <inlineHelpText>Check this box if the section is a currently active section</inlineHelpText>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Indicator_Area__c</fullName>
        <formula>Program__r.Indicator_Area__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>What Indicator Area is this Program addressing? This field cannot be modified here.</inlineHelpText>
        <label>Indicator Area</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Program__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>What intervention Program is this Intervention Section for?</inlineHelpText>
        <label>Program</label>
        <referenceTo>Program__c</referenceTo>
        <relationshipLabel>Sections</relationshipLabel>
        <relationshipName>Sections</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Section__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Recursive lookup for groups</description>
        <label>Section</label>
        <referenceTo>Section__c</referenceTo>
        <relationshipLabel>Groups in Section</relationshipLabel>
        <relationshipName>Sections1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Staff__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Staff</label>
        <referenceTo>Staff__c</referenceTo>
        <relationshipLabel>Sections</relationshipLabel>
        <relationshipName>Sections</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Section</label>
    <nameField>
        <label>Section Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sections</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Staff__c.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <label>Staff</label>
    <nameField>
        <label>Staff Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Staff</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/Student__c.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>true</defaultValue>
        <inlineHelpText>Indicates whether or not this Student record is active. If checked, then this is the current Student record. If unchecked, this is an old Student record.</inlineHelpText>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Section__c</fullName>
        <inlineHelpText>Displays the student&apos;s current homeroom name or room number. This field can be used for reporting purposes.</inlineHelpText>
        <label>Current Homeroom</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Staff__c</fullName>
        <inlineHelpText>Displays the name of the student&apos;s homeroom teacher.  You can use this field for reporting purposes.</inlineHelpText>
        <label>Current Homeroom Teacher</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Student__c</fullName>
        <inlineHelpText>Displays the student&apos;s middle name.</inlineHelpText>
        <label>Student Middle Name</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <label>Student</label>
    <nameField>
        <label>Student Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Students</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/Test_CYSharingRecalculator.cls
@isTest
private class Test_CYSharingRecalculator {
/*	
	private static Account school;
	private static User user;
	private static Contact c;
	private static Staff__c staff;
	private static List<Student__c> students;
	private static Section__c sec;
	
	static testMethod void testConstructor(){
		Test.startTest();
			CYSharingRecalculator cysr = new CYSharingRecalculator();
			system.assert(!cysr.useLog);
			cysr = new CYSharingRecalculator(true);
			system.assert(cysr.useLog);
		Test.stopTest();
	}
	
	static testMethod void testCorpsMember(){
		TestDataUtil.setupSharingControls();
		TestDataUtil.setupTime();
		setupSchool('Corps Member');
		setupSection(staff);
		Test.startTest();
			User cmUser = [SELECT id, Profile.Name FROM User WHERE id=:user.id];
			CYSharingRecalculator cysr = new CYSharingRecalculator();
			cysr.execute(null,new List<User>{cmUser});
			Map<ID,Map<ID,ID>> shares = SharingUtils.getExistingSharing(new Set<ID>{cmUser.id});
			system.assertEquals(1,shares.size());
			system.assertEquals(4,shares.get(cmUser.Id).size());
			staff.Active__c = false;
			update staff;
			cysr.execute(null,new List<User>{cmUser});
			shares = SharingUtils.getExistingSharing(new Set<ID>{cmUser.id});
			system.assertEquals(0,shares.size());
		Test.stopTest();
	}
	
	static testMethod void testSchoolAdmin(){
		TestDataUtil.setupSharingControls();
		TestDataUtil.setupTime();
		setupSchool('School Admin');
		Contact c2 = TestDataUtil.createContact('ApexText','CM',null);
		insert c2;
		Staff__c cmstaff = TestDataUtil.createStaff(c2,school,2);
		insert cmstaff;
		setupSection(cmstaff);
		Test.startTest();
			User saUser = [SELECT id, Profile.Name FROM User WHERE id=:user.id];
			CYSharingRecalculator cysr = new CYSharingRecalculator();
			cysr.execute(null,new List<User>{saUser});
			Map<ID,Map<ID,ID>> shares = SharingUtils.getExistingSharing(new Set<ID>{saUser.id});
			system.assertEquals(1,shares.size());
			system.assertEquals(4,shares.get(saUser.Id).size());
			staff.Active__c = false;
			update staff;
		Test.stopTest();
		shares = SharingUtils.getExistingSharing(new Set<ID>{saUser.id});
		system.assertEquals(0,shares.size());
	}
	
	static testMethod void testBatch(){
		TestDataUtil.setupSharingControls();
		TestDataUtil.setupTime();
		setupSchool('Corps Member');
		setupSection(staff);
		Test.startTest();
			Data_Load_Log__c dll = SharingUtils.getLog('Pending');
			dll.Messages__c = user.id;
			upsert dll;
			CYSharingRecalculator cysr = new CYSharingRecalculator(true);
			Database.executeBatch(cysr,1);
		Test.stopTest();
		Map<ID,Map<ID,ID>> shares = SharingUtils.getExistingSharing(new Set<ID>{user.id});
		system.assertEquals(1,shares.size());
		system.assertEquals(4,shares.get(user.Id).size());
		
		dll = [SELECT id, Batch_ID__c, Status__c, End_Time__c FROM Data_Load_Log__c WHERE id=:dll.id];
		system.assertEquals('Completed', dll.Status__c);
		system.assertNotEquals(null,  dll.End_Time__c);
	}
	
	static testMethod void testUpdateQuery(){
		Test.startTest();
			CYSharingRecalculator cysr = new CYSharingRecalculator();
			String newString = cysr.updateQuery('start (',',','beg ',' end', new List<String>{'a','b','c'});
			system.assertEquals('start (beg a end,beg b end,beg c end)',newString);
		Test.stopTest();
	}
	
	static testMethod void testSchedule(){
		Test.startTest();
			Schedule_CYSharingRecalculator cys = new Schedule_CYSharingRecalculator(true);
			DateTime sched = system.now().addMinutes(5);
			String sch = sched.second()+' '+sched.minute()+' '+sched.hour()+' '+sched.day()+' '
				+sched.month()+' ? '+sched.year();
			ID jobId = System.schedule('Test Schedule',sch,cys);
			
			CronTrigger ct = [SELECT id, CronExpression, TimesTriggered FROM CronTrigger WHERE id=:jobId];
			system.assertEquals(sch, ct.CronExpression);
			system.assertEquals(0, ct.TimesTriggered);
		Test.stopTest();
	}
	
	static void setupSchool(String profile){
		school = TestDataUtil.createSchool('ApexTest School');
		insert school;
		TestDataUtil.schoolList.add(school);
		TestDataUtil.setupSetupRecord();
		
		String profileName = '%'+profile+'%';
		Profile p = [SELECT id FROM Profile WHERE Name LIKE :profileName and UserType = 'Standard' LIMIT 1];
		user = TestDataUtil.createUser('ApexTestUser',p.id);
		insert user;
		c = TestDataUtil.createContact('ApexTest','User',user.id);
		insert c;
		staff = TestDataUtil.createStaff(c,school,1);
		insert staff;
		students = TestDataUtil.createStudents(3, school);
		insert students;
	}
	
	static void setupSection(Staff__c cmstaff){
		List<Indicator_Area__c> ia = TestDataUtil.createIndicatorAreas();
		insert ia;
		List<Program__c> programs = TestDataUtil.createPrograms(1,true,ia[0]);
		insert programs;
		Account_Program__c ap = TestDataUtil.createAccountProgram(school,programs[0]);
		insert ap;
		sec = TestDataUtil.createSection(school, ap, students, cmstaff, programs[0]);
	}
	*/
}