objects/Account.object
<CustomObject>
    <fields>
        <fullName>Site__c</fullName>
        <label>Location</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Baton Rouge</fullName>
                </value>
                <value>
                    <fullName>Boston</fullName>
                </value>
                <value>
                    <fullName>Buffalo</fullName>
                </value>
                <value>
                    <fullName>Chicago</fullName>
                </value>
                <value>
                    <fullName>City Year</fullName>
                </value>
                <value>
                    <fullName>Cleveland</fullName>
                </value>
                <value>
                    <fullName>Columbia</fullName>
                </value>
                <value>
                    <fullName>Columbus</fullName>
                </value>
                <value>
                    <fullName>Dallas</fullName>
                </value>
                <value>
                    <fullName>Denver</fullName>
                </value>
                <value>
                    <fullName>Detroit</fullName>
                </value>
                <value>
                    <fullName>Jacksonville</fullName>
                </value>
                <value>
                    <fullName>Kansas City</fullName>
                </value>
                <value>
                    <fullName>Little Rock</fullName>
                </value>
                <value>
                    <fullName>Los Angeles</fullName>
                </value>
                <value>
                    <fullName>Memphis</fullName>
                </value>
                <value>
                    <fullName>Miami</fullName>
                </value>
                <value>
                    <fullName>Milwaukee</fullName>
                </value>
                <value>
                    <fullName>New Hampshire</fullName>
                </value>
                <value>
                    <fullName>New Orleans</fullName>
                </value>
                <value>
                    <fullName>New York City</fullName>
                </value>
                <value>
                    <fullName>Orlando</fullName>
                </value>
                <value>
                    <fullName>Philadelphia</fullName>
                </value>
                <value>
                    <fullName>Providence</fullName>
                </value>
                <value>
                    <fullName>Rhode Island</fullName>
                </value>
                <value>
                    <fullName>Sacramento</fullName>
                </value>
                <value>
                    <fullName>San Antonio</fullName>
                </value>
                <value>
                    <fullName>San Jose/Silicon Valley</fullName>
                </value>
                <value>
                    <fullName>Seattle/King County</fullName>
                </value>
                <value>
                    <fullName>Tulsa</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <recordTypes>
        <fullName>School</fullName>
        <active>true</active>
        <description>This record type is for physical school locations.</description>
        <label>School</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Grade__c.object
<CustomObject>
    <fields>
        <fullName>Student__c</fullName>
        <label>Student</label>
        <referenceTo>Student__c</referenceTo>
        <relationshipLabel>Grades</relationshipLabel>
        <relationshipName>Grades</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Grade</label>
    <nameField>
        <displayFormat>G-{0}</displayFormat>
        <label>Grade Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Grades</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Indicator_Area_Student__c.object
<CustomObject>
    <description>The Indicator Area/Student object is a joiner object that associates an Indicator Area and a Student.</description>
    <fields>
        <fullName>Indicator_Area__c</fullName>
        <inlineHelpText>This field joins the Indicator Area/Student record to the correct Indicator Area</inlineHelpText>
        <label>Indicator Area</label>
        <referenceTo>Indicator_Area__c</referenceTo>
        <relationshipLabel>Indicator Area/Student</relationshipLabel>
        <relationshipName>Indicator_Area_Student</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Student__c</fullName>
        <inlineHelpText>This field joins the Indicator Area/Student record to the correct Student</inlineHelpText>
        <label>Student</label>
        <referenceTo>Student__c</referenceTo>
        <relationshipLabel>Indicator Area/Student</relationshipLabel>
        <relationshipName>Indicator_Area_Student</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Indicator Area/Student</label>
    <nameField>
        <displayFormat>IA/S -{000}</displayFormat>
        <label>IA/Student ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Indicator Area/Student</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Section__c.object
<CustomObject>
    <fields>
        <fullName>Indicator_Area__c</fullName>
        <formula>Program__r.Indicator_Area__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>What Indicator Area is this Program addressing? This field cannot be modified here.</inlineHelpText>
        <label>Indicator Area</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>School__c</fullName>
        <label>School</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Sections</relationshipLabel>
        <relationshipName>Sections</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Section</label>
    <nameField>
        <label>Section Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sections</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Student__c.object
<CustomObject>
    <fields>
        <fullName>Homeroom__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Displays the student&apos;s homeroom. This field is not used by SchoolForce, but you can use it for reporting purposes.</inlineHelpText>
        <label>Homeroom</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Only sections marked as Homerooms can be selected</errorMessage>
            <filterItems>
                <field>Section__c.Homeroom__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Section__c</referenceTo>
        <relationshipLabel>Students (Homeroom)</relationshipLabel>
        <relationshipName>Students</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Local_Student_ID__c</fullName>
        <externalId>true</externalId>
        <inlineHelpText>This field can be populated with either the student???s school/district assigned ID or a local ID.</inlineHelpText>
        <label>Local Student ID</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>School__c</fullName>
        <inlineHelpText>Displays the name of the student&apos;s current SchoolForce school. You can click on the link to see the details of this school.</inlineHelpText>
        <label>School</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Students</relationshipLabel>
        <relationshipName>Students</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Student_First_Name__c</fullName>
        <inlineHelpText>Displays the student&apos;s first name.</inlineHelpText>
        <label>Student First Name</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Student_Id__c</fullName>
        <inlineHelpText>Displays the student&apos;s ID. This field displays on report cards, progress reports, and transcripts. It must be unique; SchoolForce uses this ID to link the Student record with the correct Contact record.</inlineHelpText>
        <label>Student Id</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Student_Last_Name__c</fullName>
        <inlineHelpText>Displays the student&apos;s last name.</inlineHelpText>
        <label>Student Last Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Student__c</fullName>
        <inlineHelpText>Displays the student&apos;s middle name.</inlineHelpText>
        <label>Student Middle Name</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <label>Student</label>
    <nameField>
        <label>Student Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Students</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Student_Program__c.object
<CustomObject>
    <description>This is an object is students/program roll up</description>
    <fields>
        <fullName>Indicator_Area__c</fullName>
        <formula>IF( ISBLANK( Section_del__r.Indicator_Area__c ) , &quot;&quot;,  ( Section_del__r.Indicator_Area__c ) )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Indicator Area</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Student__c</fullName>
        <description>Student/Program</description>
        <label>Student</label>
        <referenceTo>Student__c</referenceTo>
        <relationshipLabel>Student/Programs</relationshipLabel>
        <relationshipName>Student_Programs</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Student/Program</label>
    <nameField>
        <displayFormat>SP-{0000}</displayFormat>
        <label>Student/Program Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Student/Programs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Student_Section__c.object
<CustomObject>
    <fields>
        <fullName>Local_Student_ID__c</fullName>
        <formula>Student__r.Local_Student_ID__c</formula>
        <label>Local Student ID</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>School__c</fullName>
        <formula>Student__r.School__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>School</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Student_First_Name__c</fullName>
        <formula>Student__r.Student_First_Name__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Student First Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Student_Id__c</fullName>
        <formula>Student__r.Student_Id__c</formula>
        <label>Student Id</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Student__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Student</label>
        <referenceTo>Student__c</referenceTo>
        <relationshipLabel>Section</relationshipLabel>
        <relationshipName>Student_Section</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Student/Section</label>
    <nameField>
        <displayFormat>SS-{000000}</displayFormat>
        <label>Student/Section ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Student/Section</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/IndicatorAreasController.cls
public with sharing class IndicatorAreasController {
    public Set<Id> selected                             {get;set;}
    public List<StudentInfoWrapper> StudentsFiltered    {get;set;}
    public List<StudentInfoWrapper> StudentsFilteredTest    {get;set;}
    public Map<String,List<SelectOption>> siteToSchools {get;set;}
    public List<SelectOption> schools                   {get;set;}
    public Map<Id, StudentInfoWrapper> addTo            {get;set;}
    public List<Indicator_Area__c> areas                {get;set;}
    public List<SelectOption> gradeLevels               {get;set;}
    public String selectedGrade                         {get;set;}
    public String[] activeIAId                         {get;set;}
    public List<Id> orderedStudentIdsInAddTo            {get;set;}
    public Map<Id, StudentInfoWrapper> orderedStudentsAddToMap  {get;set;}
    
    public List<Indicator_Area_Student__c> changes;
    public Set<String> changesIDs;
    public String errorMessage                          {get;set;}
    
    public Map<Id, Student__c> StudentMap               {get;set;}
    public Map<Id, StudentInfoWrapper> StudentWrapperMap            {get;set;}
    public Map<String, List<StudentInfoWrapper>> studentsByGradeMap {get;set;}
    public Map<Id, Indicator_Area__c> AreaMap       {get;set;}
    
    public String SchoolFilterParam                 {get;set;}
    public List<SelectOption> sites                 {get;set;}
    public String selectedSite                      {get;set;}
    
    public Boolean hasUnsavedChanges                {get; set;}

    public IndicatorAreasController(){
        StudentsFiltered = new List<StudentInfoWrapper>();
        StudentsFilteredTest = new List<StudentInfoWrapper>();
        addTo = new Map<Id, StudentInfoWrapper>();
        schools = new List<SelectOption>();
        sites = new List<SelectOption>();
        selected = new set<Id>();
        StudentMap = new Map<Id, Student__c>();
        AreaMap = new Map<Id, Indicator_Area__c>();
        StudentWrapperMap = new Map<Id, StudentInfoWrapper>();
        changes= new List<Indicator_Area_Student__c>();
        changesIDs= new Set<String>();
        orderedStudentIdsInAddTo = new List<String>();
        orderedStudentsAddToMap = new Map<Id, StudentInfoWrapper>();

        loadAreas();
        loadSchools();
        hasUnsavedChanges = false;
    }
    
    public void loadSchools(){
        siteToSchools = new Map<String,List<SelectOption>>();
        sites = new List<SelectOption>();
        List<Account> schoolList = [select id, Name, Site__c, (select id from Students__r limit 1) from Account where Site__c != null order by Name];
        for(Account school:schoolList){
            if(school.Students__r.size()>0){
                if(siteToSchools.containsKey(school.Site__c)){
                    siteToSchools.get(school.Site__c).add(new SelectOption(school.ID, school.Name));
                } else {
                    siteToSchools.put(school.Site__c, new List<SelectOption>{new SelectOption(school.ID, school.Name)});
                    sites.add(new SelectOption(school.Site__c, school.Site__c));
                }
            }
        }
        system.debug(siteToSchools.keySet());

        if(siteToSchools.isEmpty()){
            CYUtil.errorMessage('There are no valid schools to load. Please check your data.');
        } else {
            sites.sort();
            selectedSite = sites[0].getValue();
            changeSite();
        }
    }

    public void changeSite(){
        schools = new List<SelectOption>();
        schools.addAll(siteToSchools.get(selectedSite));
    }

    public void changeSchool(){
        selectedGrade = 'all';
        loadStudents();
    }

    public void loadStudents(){
        String query = 
            'SELECT Id, Name, Student_Id__c, Local_Student_ID__c, Student_Last_Name__c, Student_First_Name__c, ' +
                'School__c, Grade__c, Entry_Date__c, Expiration_Date__c, '+
                '(SELECT Indicator_Area__r.name, Student__r.Name, Reference_ID__c, Active__c, IA_Effective_Date__c '+
                'FROM Indicator_Area_Student__r '+
                'ORDER BY Indicator_Area__r.name asc), '+
                '(SELECT Section_Exit_Reason__c, Section__r.Program__r.Indicator_Area__r.Name '+
                'FROM Student_Section__r '+
                'ORDER BY Section__r.Program__r.Indicator_Area__r.Name asc) '+  
                //'(SELECT Program1__r.Name, Program1__r.Indicator_Area__r.Name '+
                //'from Student_Programs__r '+
                //'order by Program1__r.Indicator_Area__r.name asc) '+
            'FROM Student__c '+
            'WHERE School__c=\''+String.escapeSingleQuotes(schoolFilterParam)+'\' '+
            'and Active__c=true '+
            'and Archived__c=false ';

        if(String.isNotBlank(selectedGrade) && selectedGrade != 'all'){
            query += 'and Grade__c = \''+String.escapeSingleQuotes(selectedGrade)+'\' ';
        }
        query += 'order by student_last_name__c, student_first_name__c asc';
        
        List<Student__c> students = (schoolFilterParam != '--None--')? Database.query(query): new List<Student__c>();

        studentsFiltered = new List<StudentInfoWrapper>();
        studentWrapperMap = new Map<Id, StudentInfoWrapper>();

        Set<String> studentGrades = new Set<String>();
        for(Student__c student:students){
            studentGrades.add(student.Grade__c);
            if(studentsFiltered.size()<1000){
                StudentInfoWrapper newSW = new StudentInfoWrapper(student, student.Indicator_Area_Student__r);
                studentsFiltered.add(newSW);
                studentWrapperMap.put(student.ID,newSW);
            }
        }

        if(studentGrades.size()>0 && selectedGrade == 'all'){
            loadGradeLevels(studentGrades);
        }

        if(studentsFiltered.size() > 1000){
            CYUtil.infoMessage('There are more than 1000 students in the selected school. Students must be filtered by a grade for this school.');
            if(gradeLevels[0].getValue() == 'all'){
                gradeLevels.remove(0);
            }
            if(gradeLevels[0].getValue() != ''){
                gradeLevels.add(0, new SelectOption('', 'Choose a grade', true));
            }
            selectedGrade = '';
        }

        if(studentsFiltered.isEmpty()){
            CYUtil.errorMessage('There are no students available using your filters. Please check your filters.');
        }       
    }

    public void filterGrades(){
        loadStudents();
    }
    
    public void loadAreas(){
        //The filter by name was a specific request by CY. Generally they just didn't want that value to display on this page.
        areas = [select name from Indicator_Area__c where Name!='Non-specific IA' order by name asc limit 40000];
        
        activeIAId = new List<string>();
        /**
        for(Indicator_Area__c IndId :areas){
        if(areas.size()>0){
             activeIAId.add(IndId.id);
        }
        }
        **/
        for(Indicator_Area__c ia : areas){
            AreaMap.put(ia.id, ia);
        }
    }

    public void loadGradeLevels(Set<String> studentGrades){
        gradeLevels = new List<SelectOption>{new SelectOption('all','All Grade Levels')};
        
        Schema.DescribeFieldResult possibleGrades = Student__c.Grade__c.getDescribe();
        for(Schema.PicklistEntry pe: possibleGrades.getPicklistValues()){
            if(studentGrades.contains(pe.getValue())){
                gradeLevels.add(new SelectOption(pe.getValue(),pe.getLabel()));
            }
        }
    }

    public String selectStudentParam{get;set;}
    
    public void selectStudent(){
        processSelectedStudents(selectStudentParam);
        if(selected.IsEmpty()){
            ApexPages.addMessage(new ApexPages.Message(apexpages.severity.error,'No students selected.'));
            selectStudentParam=null;
        }
    }

    public void processSelectedStudents(String selectStudentParam){
        for(StudentInfoWrapper studentWrapper: studentsFiltered){
            selected.remove(studentWrapper.student.ID);
            if (orderedStudentIdsInAddTo.contains(studentWrapper.student.ID)) {
                orderedStudentIdsInAddTo.remove(orderedStudentIdsInAddTo.indexOf(studentWrapper.student.ID));
            }
            addTo.remove(studentWrapper.student.ID);
            orderedStudentsAddToMap.remove(studentWrapper.student.ID);
        }

        if(String.isNotBlank(selectStudentParam)){
            List<String> ids = selectStudentParam.split(';');
            Set<Id> selIds = new Set<Id>();
            for(String i : ids){
                selIds.add(i.trim());
            }
            selected.addAll(selIds);
            List<Id> orderedStudents = sortStudentsByLastName(selected);
            for(StudentInfoWrapper studentWrapper: studentsFiltered){
                if(selIds.contains(studentWrapper.student.ID)){
                    orderedStudentsAddToMap.put(studentWrapper.student.ID, studentWrapper);
                }
            }
            System.debug('addToMap ' + orderedStudentsAddToMap);
            for (Id selectedId : orderedStudents) {
                if (orderedStudentsAddToMap.containsKey(selectedId)) {
                    System.debug('addto ' + addTo);
                    orderedStudentIdsInAddTo.add(selectedId);
                    addTo.put(selectedId, orderedStudentsAddToMap.get(selectedId));
                }
            }
        }   
    }

    private List<Id> sortStudentsByLastName(Set<Id> studentIds) {
        List<Id> sortedStudentIds = new List<Id>();
        List<Student__c> students = [SELECT Id, Student_First_Name__c, Student_Last_Name__c FROM Student__c WHERE Id IN :studentIds ORDER BY Student_Last_Name__c ASC];
        for (Student__c student : students) {
            sortedStudentIds.add(student.Id);
        }
        return sortedStudentIds;
    }

//  public void addPrep(){
        //addTo = new List<StudentWrapper>();
        //for(StudentWrapper studentWrapper: studentsFiltered){
        //  if(selected.contains(studentWrapper.student.ID)){
        //      addTo.add(studentWrapper);
        //  }
        //}
//  }
    
    public PageReference resetPage(){
        PageReference returnPage = new PageReference('/apex/IM_Indicator_Areas');
        returnPage.setRedirect(true);
        return returnPage;
            
    }

    public List<SelectOption> getIAList() {
        List<SelectOption> options = new List<SelectOption>();
        for(Indicator_Area__c a :areas){
            options.add(new SelectOption(a.Id, a.Name));
        }
        return options;
    }
    
    public void updateStudents(){
    if(activeIAId !=null && activeIAId.size()>0){
    
       for(string arealistId:activeIAId){
       
        Indicator_Area__c ia = AreaMap.get(arealistId);
       
        for(StudentInfoWrapper s : addTo.values()){
            Indicator_Area_Student__c IA_S = s.areaIds.get(arealistId);
            
            if(IA_S == null){
                IA_S = new Indicator_Area_Student__c();
                IA_S.Indicator_Area__c = ia.id;
                IA_S.Indicator_Area__r = ia;
                IA_S.Student__c = s.student.id;
                IA_S.Student__r = s.student;
                IA_S.Reference_ID__c = s.student.id+'_'+ia.id;
                IA_S.Active__c = true;
                s.addArea(IA_S);
            }

            IA_S.IA_Effective_Date__c = s.dtIA == null? IA_S.IA_Effective_Date__c: s.dtIA;
            IA_S.Active__c = true;
            if(!changesIDs.contains(IA_S.Reference_ID__c)){
                changes.add(IA_S);
                changesIDs.add(IA_S.Reference_ID__c);
            }
            s.refreshIndicatorAreaDisplay();
        }
        }
        hasUnsavedChanges = true;
        selected = new set<Id>();
        addTo = new Map<Id, StudentInfoWrapper>();
       }
       else{
        ApexPages.Message myMsg = new ApexPages.Message(ApexPages.Severity.FATAL, 'Please select atleast one Indicator area');
       }
    }
    
    public void saveChanges(){
        for (StudentInfoWrapper studWrap : StudentsFiltered) {
            for (Indicator_Area_Student__c IA_S : changes) {
                if (studWrap.student.Id == IA_S.Student__c) {
                    IA_S.IA_Effective_Date__c = studWrap.dtIA;
                }
            }

        }
        List<String> errorMessages = new List<String>();
        for(Indicator_Area_Student__c IA_S: changes){
            StudentInfoWrapper siw = StudentWrapperMap.containsKey(IA_S.Student__c)?
                    StudentWrapperMap.get(IA_S.Student__c): new StudentInfoWrapper(new Student_Section__c());
            if(siw.dtIA != null && IA_S.IA_Effective_Date__c == null){
                IA_S.IA_Effective_Date__c = StudentWrapperMap.get(IA_S.Student__c).dtIA;
            }
            if(IA_S.IA_Effective_Date__c == null){
                errorMessages.add('Please populate IA date for student: '+siw.name+' and IA: '+AreaMap.get(IA_S.Indicator_Area__c).name+'.');
            }
            if(siw.student.Entry_Date__c > IA_S.IA_Effective_Date__c || siw.student.Expiration_Date__c < IA_S.IA_Effective_Date__c){
                errorMessages.add('Student '+siw.name+' should have the IA Effective Date in the range of '+(siw.student.Entry_Date__c!=null?siw.student.Entry_Date__c.format():'-')+' to '+(siw.student.Expiration_Date__c!=null?siw.student.Expiration_Date__c.format():'-')+'.');
            }
        }
        if(changes.isEmpty()){
            CYUtil.errorMessage('Please choose an indicator area to assign before saving.'); return;
        }

        if(errorMessages.isEmpty()){
            List<Database.UpsertResult> results = Database.upsert(changes,Indicator_Area_Student__c.Reference_ID__c.getDescribe().getSObjectField(),false);
            for(integer i=0; i<results.size(); i++){
                List<Database.Error> errors = results[i].getErrors();
                for(Database.Error er : errors){
                    errorMessages.add('For student '+changes[i].Student__r.Name+'. '+er.getMessage()+'.');
                }
            }
        }

        if(errorMessages.isEmpty()){
            CYUtil.successMessage('Your changes have been saved.');
            changes= new List<Indicator_Area_Student__c>();
            changesIDs.clear();
            hasUnsavedChanges = false;
            for (StudentInfoWrapper studWrap : StudentsFiltered) {
                studWrap.selected = false;
            }
        }else{
            CYUtil.errorMessage(String.join(errorMessages, '<br/>')+'<br/>Please verify that your changes have been saved.');
        }
    }
}