objects/Account.object
<CustomObject>
    <recordTypes>
        <fullName>School</fullName>
        <active>true</active>
        <description>This record type is for physical school locations.</description>
        <label>School</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Contact.object
<CustomObject>
    <recordTypes>
        <fullName>Staff</fullName>
        <active>true</active>
        <description>This record type is for staff members.</description>
        <label>Staff</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Picklist_Value__c.object
<CustomObject>
    <fields>
        <fullName>Setup__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Setup</label>
        <referenceTo>Setup__c</referenceTo>
        <relationshipLabel>Picklist Values</relationshipLabel>
        <relationshipName>Picklist_Values</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Picklist Value</label>
    <nameField>
        <label>Display Value</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Picklist Values</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Section__c.object
<CustomObject>
    <fields>
        <fullName>School__c</fullName>
        <label>School</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Sections</relationshipLabel>
        <relationshipName>Sections</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Section__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Recursive lookup for groups</description>
        <label>Section</label>
        <referenceTo>Section__c</referenceTo>
        <relationshipLabel>Groups in Section</relationshipLabel>
        <relationshipName>Sections1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Staff__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Staff</label>
        <referenceTo>Staff__c</referenceTo>
        <relationshipLabel>Sections</relationshipLabel>
        <relationshipName>Sections</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Section</label>
    <nameField>
        <label>Section Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sections</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Setup__c.object
<CustomObject>
    <description>This object is used to setup Schoolforce and is referenced in multiple pieces of code.  There should be one setup object per school.</description>
    <fields>
        <fullName>On_Track_Threshold__c</fullName>
        <description>This is a secondary threshold used for a three-tiered grade tracking system</description>
        <inlineHelpText>Select a grade (0-100 scale) that this school defines as &quot;On Track&quot; or &quot;Green.&quot; Any section grades that are above this number will display in the Gradebook UI as Green.  Any number that falls between this  and the Passing Grade threshold will be yellow.</inlineHelpText>
        <label>On Track Threshold</label>
        <precision>5</precision>
        <scale>1</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Passing_Grade_Threshold__c</fullName>
        <inlineHelpText>Select the grade threshold (0-100 scale) that defines passing for this school.  Any section grade that is calculated below this number will display in the Gradebook UI as red.  Any number between this and the &quot;On Track&quot; number will yellow.</inlineHelpText>
        <label>Passing Grade Threshold</label>
        <precision>5</precision>
        <scale>1</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>School__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>School</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1 OR 2</booleanFilter>
            <filterItems>
                <field>Account.RecordType.Name</field>
                <operation>equals</operation>
                <value>School</value>
            </filterItems>
            <filterItems>
                <field>Account.RecordType.Name</field>
                <operation>equals</operation>
                <value>Summer School</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Setup</relationshipLabel>
        <relationshipName>Setup</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Standards_Based_Grading__c</fullName>
        <defaultValue>false</defaultValue>
        <description>School-wide setting that will reduce config time if set to false</description>
        <inlineHelpText>Select if school wants to grade standards.  If set to false, users will enter traditional grades without association to standards or standard grades.  If checked, users in the Hybrid or Standard ONLY Gradebook can grade standards.</inlineHelpText>
        <label>Standards Based Grading</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Term__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Term refers to the Term &apos;Template&apos; that the administrator associates to the School; this contains all Semeser/Quarter/Period logic necessary to create Sessions.</description>
        <label>Term</label>
        <referenceTo>Time_Element__c</referenceTo>
        <relationshipLabel>Setup</relationshipLabel>
        <relationshipName>Setup</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Year__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>School Year associated to the Setup</description>
        <label>Year</label>
        <referenceTo>Time_Element__c</referenceTo>
        <relationshipLabel>Setup (Year)</relationshipLabel>
        <relationshipName>Setup_Year</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Setup</label>
    <nameField>
        <displayFormat>S-{0}</displayFormat>
        <label>Setup ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Setup</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/Staff__c.object
<CustomObject>
    <fields>
        <fullName>Individual__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Individual</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Staff</relationshipLabel>
        <relationshipName>Staff</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Organization__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Staff Member&apos;s employer</description>
        <label>Organization</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Staff</relationshipLabel>
        <relationshipName>Staff</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Staff</label>
    <nameField>
        <label>Staff Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Staff</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/Term__c.object
<CustomObject>
    <description>Junction object  between Time and Setup.</description>
    <fields>
        <fullName>Setup__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Setup</label>
        <referenceTo>Setup__c</referenceTo>
        <relationshipLabel>Terms</relationshipLabel>
        <relationshipName>Terms</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Time_Element__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Time Element</label>
        <referenceTo>Time_Element__c</referenceTo>
        <relationshipLabel>Terms</relationshipLabel>
        <relationshipName>Terms</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Term</label>
    <nameField>
        <displayFormat>Term-{000000}</displayFormat>
        <label>Term Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Terms</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Time_Element__c.object
<CustomObject>
    <fields>
        <fullName>Name__c</fullName>
        <label>Name</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Picklist_Value__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Picklist Value</label>
        <referenceTo>Picklist_Value__c</referenceTo>
        <relationshipLabel>Time</relationshipLabel>
        <relationshipName>Time</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>School__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>School</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Time</relationshipLabel>
        <relationshipName>Time</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Time</label>
    <nameField>
        <displayFormat>T-{000000}</displayFormat>
        <label>Time Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Time</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/User.object
<CustomObject>
    <fields>
        <fullName>School__c</fullName>
        <label>School</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

classes/core_BaseInfo_v2.cls
public with sharing class core_BaseInfo_v2{ 
	public static Contact con {get;set;} //Logged in contact
	public static User cUser {get;set;} 
	public static List <Staff__c> staffList {get;set;} //List of staff records for logged in Contact (no need to link back to contact record since there will only ever be 1)
	public static Map <Id, Id> staffSchoolMap {get;set;} //Needed to get the staff record related to the school since its 1:1 
	public static Map <Id, Account> schoolMap {get;set;} //If toggling between schools this helps retreive that info
	public static Map <Id, List <Section__c>> staffSectionListMap {get;set;} //List of sections related to a single school/ needed if toggling
	public static Map <Id, Setup__c> activeSetupsBySchoolMap {get;set;}
	public static Map<String, Id> picklistValueRecordTypeMap {get;set;} //LIst of recordTypes for Picklist Value obj
	public static String[] errorMessages {get;set;}
	public static core_BaseInfo_v2.cSchool_BaseInfo baseInfoObj {get;set;}
	public static Map<String,Map<String,List<Section__c>>> yearSectionsMap;
	public static List<String> recentSchoolYears;
	public static Map<String,Map<String,Setup__c>> schoolSetupsByYearMap;
	public static Id UserId; 

	public core_BaseInfo_v2(){
	}

	public static void showErrorMessages(){
		if (!errorMessages.isEmpty()){
			for (String s: errorMessages){
				ApexPages.addMessage(new ApexPages.message(ApexPages.severity.ERROR,s));
			}
		}
	}

	public static void initBaseInfo(){
		loadBaseInfo(null, true, true, true,false,null);
	}
	
	public static void initBaseInfo(Boolean isYOY){
		loadBaseInfo(null, true, true, true,true,null);
	}

	public static void initBaseInfo(Boolean isYOY, String yearID){
		loadBaseInfo(null, true, true, true, true, yearID);
	}
	
	public static void initBaseInfo(String schoolId){
		loadBaseInfo(schoolId, true, true, true,false,null);
	}
	
	public static void initBaseInfo(boolean reporting, boolean section, boolean picklist){
		loadBaseInfo(null, reporting, section, picklist,false,null);
	}
	
	public static void initBaseInfo(String schoolId, boolean reporting, boolean section, boolean picklist){
		loadBaseInfo(schoolId, reporting, section, picklist,false,null);
	}
	
	private static void loadBaseInfo(string schoolId, boolean reporting, boolean section, boolean picklist,boolean prevYear, String yearID) {
		staffSchoolMap = new Map <Id, Id>();
		staffList = new List <Staff__c>();
		schoolMap = new Map <Id, Account>();
		staffSectionListMap = new Map<Id, List <Section__c>>();
		activeSetupsBySchoolMap = new Map <Id, Setup__c>();
		Set <Id> staffIds = new Set <Id>();
		Set <Id> schoolIds = new Set <Id>();
		errorMessages = new String[]{};
		picklistValueRecordTypeMap = new Map<String, Id>();
		
		//get logged in user id
		if (core_Baseinfo_v2.UserId==null){
			UserId = UserInfo.getUserId();
		}
		
		con = core_SoqlUtils.getLoggedInContact(); //Always first step, get logged in contact
		if (con == null){
			errorMessages.add('The system was unable to locate a contact record for your user. Please contact your administrator.');
			return;
		}
		cUser = core_SoqlUtils.getLoggedInUser();
		
		try{
			staffList = [select id, Organization__c from staff__c where Individual__c=:con.id];
		} catch (Exception e){
			errorMessages.add('The system was unable to locate staff records for your contact. Please contact your administrator.');
			return;
		}
		
		//make a map of schools avaiable for the logged in user
		for (Staff__c s: staffList){
			staffIds.add(s.id);
			if (s.Organization__c!=null) {
				schoolIds.add(s.organization__c);
				staffSchoolMap.put(s.organization__c, s.id);
			}
		}
		
		if(schoolIds.isEmpty()){
			errorMessages.add('The system was unable to locate schools linked to your staff record(s). Please contact your administrator.');
			return;
		}
		
		schoolMap= core_SoqlUtils.getSchoolMap(schoolIds);
		activeSetupsBySchoolMap = core_SoqlUtils.getActiveSetups(schoolMap.keySet());//TBD add error handling if there is not an active setup for a certain school
		
		if(section){
			staffSectionListMap= core_SoqlUtils.getSectionsbyStaffMap(staffIds); //TBD needs to be a single school
		}
		
		recentSchoolYears = core_SoqlUtils.getRecentThreeYears(); 
		schoolSetupsByYearMap = core_SoqlUtils.getRecentSchoolSetups(recentSchoolYears, staffSchoolMap.keyset());

		if(prevYear){
			if(section) 
			yearSectionsMap = core_SoqlUtils.getSectionsByYear(staffSchoolMap.keyset(),staffSchoolMap.values(),recentSchoolYears);
			System.debug('$$$staffSchoolMap.keyset()$$$$'+staffSchoolMap.keyset());
			System.debug('$$$recentSchoolYears$$$$$'+recentSchoolYears);	
			System.debug('$$$yearSectionsMap$$$$$'+yearSectionsMap);	
		}

		//Set the current school to the users last used school, or the first of the avaiable schools.
		if(schoolId != null){
			if(prevYear){
				baseInfoObj = new core_BaseInfo_v2.cSchool_BaseInfo(schoolId, reporting, section,activeSetupsBySchoolMap.get(schoolId).Year__c);
			}
			else 
			baseInfoObj = new core_BaseInfo_v2.cSchool_BaseInfo(schoolId, reporting, section);
		} else if(cUser.School__c == null || cUser.School__c == ''){
			if(prevYear){
				if(String.isBlank(yearID)){
					baseInfoObj = new core_BaseInfo_v2.cSchool_BaseInfo(schoolMap.values()[0].id, reporting, section,activeSetupsBySchoolMap.get(schoolMap.values()[0].id).Year__c);
				} else {
					baseInfoObj = new core_BaseInfo_v2.cSchool_BaseInfo(schoolMap.values()[0].id, reporting, section,yearID);
				}
			} else{
				baseInfoObj = new core_BaseInfo_v2.cSchool_BaseInfo(schoolMap.values()[0].id, reporting, section); 
			} 
			cUser.School__c = String.valueOf(baseInfoObj.school.Id);
		} else {
			if(prevYear){
				if(String.isBlank(yearID)){
					baseInfoObj = new core_BaseInfo_v2.cSchool_BaseInfo(cUser.School__c, reporting, section,activeSetupsBySchoolMap.get(cUser.School__c).Year__c);
				} else {
					baseInfoObj = new core_BaseInfo_v2.cSchool_BaseInfo(cUser.School__c, reporting, section,yearID);
				}
			} else{
				baseInfoObj = new core_BaseInfo_v2.cSchool_BaseInfo(cUser.School__c, reporting, section);
			}
		}
		
		if(picklist){ 
			picklistValueRecordTypeMap = core_SoqlUtils.getRecordTypesBySobject('Picklist_Value__c');
		}
	}
	
	//Nested class
	public class cSchool_BaseInfo{
		public Staff__c staff {get;set;}
		public boolean bStandardsBased {get;set;}
		public Decimal dPassingGrade {get;set;}
		//NYC functionality commented out, 8/20/2012 uncommented dFailingGrade
		public Decimal dFailingGrade {get;set;}
		public Setup__c activeSetup {get;set;}
		public Account school {get;set;}
		public List <Section__c> sectionList {get;set;}
		public List <SelectOption> reportingPeriodOptions {get;set;}
		public List <SelectOption> sectionOptions {get;set;}
		public List <SelectOption> assignmentTypeOptions {get;set;}
		public Id selectedTimeId {get;set;}
		public Map <Id, Section__c> sectionMap {get;set;}
		
		public cSchool_BaseInfo(Id SchoolId){
			this(SchoolId, true, true);
		}
		
		public cSchool_BaseInfo(Id SchoolId, boolean reporting, boolean section){
			sectionMap = new Map <Id, Section__c>();
			sectionList = new List<Section__c>();
			reportingPeriodOptions = new List <SelectOption>();
			sectionOptions = new List <SelectOption>();
			
			activeSetup = core_BaseInfo_v2.activeSetupsBySchoolMap.get(SchoolId);
			school = core_BaseInfo_v2.schoolMap.get(SchoolId);
			staff = core_SoqlUtils.getStaffDetails(core_BaseInfo_v2.staffSchoolMap.get(schoolId));

			if (activeSetup!=null){
				bStandardsBased = activeSetup.Standards_Based_Grading__c;
				//NYC functonality commented out, 8/20/2012 uncommented dPassingGrade, dFailingGrade
				//dPassingGrade = activeSetup.Passing_Grade_Threshold__c;
				dPassingGrade = activeSetup.On_Track_Threshold__c;
				dFailingGrade = activeSetup.Passing_Grade_Threshold__c;
				
				if(reporting){ 
					for (Time_Element__c t: core_SoqlUtils.getTimeElementsByTermGB(activeSetup.term__c)){
						reportingPeriodOptions.add(new SelectOption(t.Id, t.Name__c)); 
					}
				}
				
				if(section){
					if (core_BaseInfo_v2.staffSectionListMap.get(staffSchoolMap.get(SchoolId))!=null){
						for (Section__c s: core_BaseInfo_v2.staffSectionListMap.get(staffSchoolMap.get(SchoolId))){
							sectionMap.put(s.id, s);
							sectionList.add(s);
							sectionOptions.add(new SelectOption(s.id, s.name));
						}
					}
					else{
						core_BaseInfo_v2.errorMessages.add('No sections for school year: '+activeSetup.Year__r.Name__c);
					}
				}
			} else {
				core_BaseInfo_v2.errorMessages.add('No active setup for your School. Please contact your administrator.');
			}
			
		}
		
		public cSchool_BaseInfo(Id SchoolId, boolean reporting, boolean section,String yearId){
			sectionMap = new Map <Id, Section__c>();
			sectionList = new List<Section__c>();
			reportingPeriodOptions = new List <SelectOption>();
			sectionOptions = new List <SelectOption>();
			
			
			activeSetup = core_BaseInfo_v2.schoolSetupsByYearMap.get(SchoolId).get(yearId);
			school = core_BaseInfo_v2.schoolMap.get(SchoolId);
			staff = core_SoqlUtils.getStaffDetails(core_BaseInfo_v2.staffSchoolMap.get(schoolId));
			if (activeSetup!=null){
				bStandardsBased = activeSetup.Standards_Based_Grading__c;
				//NYC functionality commented out, 8/20/2012 uncommented dPassingGrade, dFailingGrade
				//dPassingGrade = activeSetup.Passing_Grade_Threshold__c;
				dPassingGrade = activeSetup.On_Track_Threshold__c;
				dFailingGrade = activeSetup.Passing_Grade_Threshold__c;
				
				if(reporting){ 
					for (Time_Element__c t: core_SoqlUtils.getTimeElementsByTermGB(activeSetup.term__c)){
						reportingPeriodOptions.add(new SelectOption(t.Id, t.Name__c)); 
					}
				}
				
				if(section){
					if (core_BaseInfo_v2.yearSectionsMap.get(schoolId).get(activeSetup.Year__c)!=null){
						for (Section__c s: core_BaseInfo_v2.yearSectionsMap.get(schoolId).get(activeSetup.Year__c)){
							sectionMap.put(s.id, s);
							sectionList.add(s);
							sectionOptions.add(new SelectOption(s.id, s.name));
						}
					}
					else{
						core_BaseInfo_v2.errorMessages.add('No sections for school year: '+activeSetup.Year__r.Name__c);
					}
				}
			} else {
				core_BaseInfo_v2.errorMessages.add('No active setup for your School. Please contact your administrator.');
			}
			
		}
	}
}