objects/Account_Program__c.object
<CustomObject>
    <description>The Account/Program object is part of the Interventions App and links Programs and Schools/Accounts.  This linking occurs in the Interventions Setup when a school selects which interventions Programs they will enroll in for a specific year.  This object tracks the relationships of Programs and Schools and whether the Programs are active.</description>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Is this Program active for this School in this year?</inlineHelpText>
        <label>Active?</label>
        <type>Checkbox</type>
    </fields>
    <label>Account/Program</label>
    <nameField>
        <label>School Program Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Accounts/Programs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Intervention_Session__c.object
<CustomObject>
    <description>The Intervention Session object captures that an Intervention Section met on a particular day. The outcome of the session is attached to the Intervention Session record.</description>
    <fields>
        <fullName>All_avenues__c</fullName>
        <label>All avenues</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>In-Person Service</fullName>
                </value>
                <value>
                    <fullName>Virtual Service</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Section__c</fullName>
        <inlineHelpText>This field connects the Intervention Session record to the correct intervention Section.</inlineHelpText>
        <label>Section</label>
        <referenceTo>Section__c</referenceTo>
        <relationshipLabel>Intervention Sessions</relationshipLabel>
        <relationshipName>Intervention_Sessions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Session_Time_Completed_For__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <inlineHelpText>Who was the staff member that led the Intervention Section? This field allows a user to enter Session time on behalf of another user.</inlineHelpText>
        <label>Session Time Completed For</label>
        <referenceTo>Staff__c</referenceTo>
        <relationshipLabel>Intervention Sessions</relationshipLabel>
        <relationshipName>Intervention_Sessions</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Skill_Primary__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Primary Skill</label>
        <referenceTo>Skill__c</referenceTo>
        <relationshipLabel>Intervention Sessions</relationshipLabel>
        <relationshipName>Intervention_Sessions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Skills_Covered_for_the_Session__c</fullName>
        <inlineHelpText>What specific skills were covered in this Intervention Session?</inlineHelpText>
        <label>Other Skills</label>
        <length>2000</length>
        <type>LongTextArea</type>
    </fields>
    <label>Intervention Session</label>
    <nameField>
        <displayFormat>IS-{000000}</displayFormat>
        <label>Inter. Session ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Intervention Sessions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Intervention_Session_Result__c.object
<CustomObject>
    <description>The Intervention Session Result is an object that captures the outcome of a student&apos;s participation in an Intervention Session. The result includes duration and notes.</description>
    <fields>
        <fullName>Amount_of_Time__c</fullName>
        <inlineHelpText>Amount of time spent with a student (in minutes) in a single Intervention Session</inlineHelpText>
        <label>Amount of Time (in minutes)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Intervention_Session__c</fullName>
        <inlineHelpText>This field connects the Intervention Session Result record to the correct Intervention Session.</inlineHelpText>
        <label>Intervention Session</label>
        <referenceTo>Intervention_Session__c</referenceTo>
        <relationshipLabel>Intervention Session Results</relationshipLabel>
        <relationshipName>Intervention_Session_Results</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>SkillsCovered__c</fullName>
        <label>Other Skills</label>
        <length>2000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Student_Section__c</fullName>
        <inlineHelpText>This field connects the Intervention Session Result record to the correct Student/Section.</inlineHelpText>
        <label>Student/Section</label>
        <referenceTo>Student_Section__c</referenceTo>
        <relationshipLabel>Intervention Session Results</relationshipLabel>
        <relationshipName>Intervention_Session_Results</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Intervention Session Result</label>
    <nameField>
        <displayFormat>ISR-{000000}</displayFormat>
        <label>Time ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Intervention Session Results</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Section__c.object
<CustomObject>
    <fields>
        <fullName>Account_Program__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>What intervention Program is this intervention Section associated to?</inlineHelpText>
        <label>School Program</label>
        <lookupFilter>
            <active>false</active>
            <filterItems>
                <field>Account_Program__c.Program__c</field>
                <operation>equals</operation>
                <valueField>$Source.Program__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account_Program__c</referenceTo>
        <relationshipLabel>Sections</relationshipLabel>
        <relationshipName>Sections</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Check this box if the section is a currently active section</description>
        <inlineHelpText>Check this box if the section is a currently active section</inlineHelpText>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Auto_Name__c</fullName>
        <formula>Program__r.Name+ &quot; - &quot; + LEFT(Intervention_Primary_Staff__r.First_Name_Staff__c , 1) +  Intervention_Primary_Staff__r.Staff_Last_Name__c + &quot; - &quot; + System_Auto_Number__c</formula>
        <inlineHelpText>This name is created using the Program Name, the Primary Point person, and an automatically generated number. This field cannot be modified here.</inlineHelpText>
        <label>Intervention Section Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Section__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Recursive lookup for groups</description>
        <label>Section</label>
        <referenceTo>Section__c</referenceTo>
        <relationshipLabel>Groups in Section</relationshipLabel>
        <relationshipName>Sections1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Staff__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Staff</label>
        <referenceTo>Staff__c</referenceTo>
        <relationshipLabel>Sections</relationshipLabel>
        <relationshipName>Sections</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Section</label>
    <nameField>
        <label>Section Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sections</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Staff__c.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Supervisor__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Supervisor</label>
        <referenceTo>Staff__c</referenceTo>
        <relationshipLabel>Staff</relationshipLabel>
        <relationshipName>Staff</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Staff</label>
    <nameField>
        <label>Staff Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Staff</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/Staff_Section__c.object
<CustomObject>
    <fields>
        <fullName>Section__c</fullName>
        <label>Section</label>
        <referenceTo>Section__c</referenceTo>
        <relationshipLabel>Staff</relationshipLabel>
        <relationshipName>Staff_Section</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Staff__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Staff</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Staff__c.Organization__r.Id</field>
                <operation>equals</operation>
                <valueField>$Source.Account__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Staff__c</referenceTo>
        <relationshipLabel>Sections</relationshipLabel>
        <relationshipName>Staff_Section</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Staff/Section</label>
    <nameField>
        <displayFormat>SfS-{000000}</displayFormat>
        <label>Staff/Section ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Staff/Section</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Student_Section__c.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Amount_of_Time__c</fullName>
        <label>Amount of time per section</label>
        <summarizedField>Intervention_Session_Result__c.Amount_of_Time__c</summarizedField>
        <summaryForeignKey>Intervention_Session_Result__c.Student_Section__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Section__c</fullName>
        <label>Section</label>
        <referenceTo>Section__c</referenceTo>
        <relationshipLabel>Student</relationshipLabel>
        <relationshipName>Student_Section</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Student/Section</label>
    <nameField>
        <displayFormat>SS-{000000}</displayFormat>
        <label>Student/Section ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Student/Section</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/ModalAddSessionCtrl.cls
/**
 * Created by TarasTorubka on 24.09.2020.
 */

public with sharing class ModalAddSessionCtrl {
    public Section__c               section                     {get;set;}
    public List<StudentInfoWrapper> studentSections             {get;set;}

    //Add time
    public String selectedStaff                                 {get;set;}
    public List<SelectOption> availableStaff                    {get;set;}
    public Integer dosage                                       {get;set;}

    //Edit time
    public String selectedSessionID                             {get;set;}
    public String sessionID                                     {get;set;}
    public ISTool.SessionWrapper selectedSession                {get;set;}


    //Add Students to Session
    public List<StudentInfoWrapper> addableStudents             {get;set;}

    //Remove Students from Session
    public String                   studentSectionIDToRemove    {get;set;}

    private ISTool sessionLoader;

    //Skills multipicklist values
    public String                   primarySkill                {get; set; }
    public SelectOption[]           selectedFields              {get; set; }
    public SelectOption[]           avaliableFields             {get; set; }
    public SelectOption[]           allPrimaryFields            {get; set; }
    public List<SelectOption>       allAvenuesOptions           {get; set; }

    public List<SelectOption>       siteDetailsOptions          {get; set; }
    public Boolean showTutoringModel                            {get; set; }


    public ModalAddSessionCtrl(){
        selectedSession = new ISTool.SessionWrapper(new Intervention_Session__c());
        initAllPicklist();
        showTutoringModel = false;
    }

    /* Add New Time */
    public void startAddTime(){
        Boolean isStaffs = initAvaliableStaff(section);
        if(isStaffs == false){
            return;
        }

        selectedStaff = availableStaff[0].getValue();
        selectedSession = new ISTool.SessionWrapper(new Intervention_Session__c());
        selectedSession.session.All_avenues__c = CT_core_SoqlUtils.getPicklistDefaultValue('Intervention_Session__c' ,'All_avenues__c');
        dosage = 0;

        for(StudentInfoWrapper sew: studentSections){
            if(sew.selected){
                selectedSession.studentResults.add(
                        new Intervention_Session_Result__c(
                                Student_Section__r = sew.studentSection,
                                Amount_of_Time__c = dosage,
                                Student_Section__c = sew.studentSection.ID
                        )
                );
            }
        }

        if(selectedSession.studentResults.isEmpty()){
            CyUtil.errorMessage('Please select a student to add time for.');
        }
        //added for multiselect picklist
        initializePicklist();
        showTutoringModel = section.Auto_Name__c.contains('Tutoring: Math') || section.Auto_Name__c.contains('Tutoring: Literacy');
    }

    public void loadSession(){
        if(section==null || section.Id==null){
            return;
        }
        sessionLoader = new ISTool(section.Id, false);

        initializePicklist();
        sessionLoader.setSingleSession(selectedSessionID);
        sessionLoader.updateResultSelection(true);
        sessionLoader.loadSessionData();
        selectedSession = sessionLoader.getSessionByID((ID)selectedSessionID);
        selectedStaff = selectedSession.session.Session_Time_Completed_For__c;
        availableStaff.add(new SelectOption(selectedStaff, selectedSession.session.Session_Time_Completed_For__r.Name));

        if(selectedSession.studentResults.size()>0){
            dosage = Integer.valueOf(selectedSession.studentResults[0].Amount_of_Time__c);
        } else {
            dosage = 0;
        }
        //added for multiSelect Picklist
        primarySkill = selectedSession.session.Skill_Primary__c;
        String skillset = selectedSession.session.Skills_Covered_for_the_Session__c != null? selectedSession.session.Skills_Covered_for_the_Session__c: '';
        List<SelectOption> tempAvailable = new List<SelectOption>();
        Set<String> setSkills = new Set<String>();
        List<String> skills = skillset.split(',');
        selectedFields.clear();
        for(String key : skills){
            String opt = key.removeStart(' ').removeEnd(' ');
            setSkills.add(opt);
            selectedFields.add(new SelectOption(opt, opt));
        }
        for(SelectOption opt : avaliableFields){
            if(!setSkills.contains(opt.getLabel())){
                tempAvailable.add(new SelectOption(opt.getLabel(),opt.getLabel()));
            }
        }
        avaliableFields.clear();
        avaliableFields.addAll(tempAvailable);
    }

    public void saveTime(){
        if(selectedSession.studentResults.isEmpty()){
            CYUtil.errorMessage('Please add one student to the session before saving.');
            return;
        }
       // if(String.isBlank(primarySkill) && selectedSession.session.All_avenues__c!='Virtual Service'){
       //   CYUtil.errorMessage('You should select the primary skill!');
       //   return;
       // }
        if(selectedSession.session.ID == null){
            selectedSession.session.Section__c = section.ID;
        }
        selectedSession.session.Session_Time_Completed_For__c = selectedStaff;
        //added for skills multiselect picklist
        List<String> lstSkills = new List<String>();
        for(SelectOption skill : selectedFields){
            lstSkills.add(skill.getLabel());
        }
        String skills = String.join(lstSkills, ', ');
        System.debug('Skills>>'+skills);

        selectedSession.session.Skill_Primary__c = primarySkill;
        selectedSession.session.Skills_Covered_for_the_Session__c = skills;
        try{
            upsert selectedSession.session;
        } catch(System.DMLException e){
            for(Integer i=0; i<e.getNumDml(); i++){
                CyUtil.errorMessage(e.getDMLMessage(i));
            }
            return;
        }

        for(Intervention_Session_Result__c isr:selectedSession.studentResults){
            if(isr.ID == null){
                isr.Intervention_Session__c = selectedSession.session.ID;
                isr.Student_Section__c = isr.Student_Section__r.ID;
            }
            //added to update skills to Intervention Session Result
            isr.SkillsCovered__c = selectedSession.session.Skills_Covered_for_the_Session__c;
            //commented ref Task# T-417933
            //isr.Amount_of_Time__c = dosage;
        }

        try{
            upsert selectedSession.studentResults;
            CyUtil.successMessage('Your time has been entered successfully.');
        }catch(System.DMLException e){
            for(Integer i=0; i<e.getNumDml(); i++){
                CyUtil.errorMessage(e.getDMLMessage(i));
            }
        }

//        loadSectionData(section.ID);
    }

    public void startAddStudents(){
        addableStudents = new List<StudentInfoWrapper>();
        Set<ID> studentsInSession = new Set<ID>();
        for(Intervention_Session_Result__c isr:selectedSession.studentResults){
            if(isr.ID == null){
                studentsInSession.add(isr.Student_Section__r.ID);
            } else {
                studentsInSession.add(isr.Student_Section__c);
            }
        }

        for(StudentInfoWrapper sw:studentSections){
            if(!studentsInSession.contains(sw.studentSection.ID) && sw.studentSection.Active__c){
                sw.selected = false;
                addableStudents.add(sw);
            }
        }
    }

    public void addStudentsToSession(){
        Integer oldSessionSize = selectedSession.studentResults.size();
        for(StudentInfoWrapper sew: addableStudents){
            if(sew.selected){
                selectedSession.studentResults.add(
                        new Intervention_Session_Result__c(
                                Student_Section__r = sew.studentSection,
                                Amount_of_Time__c = (dosage!=null)?dosage:0,
                                Student_Section__c = sew.studentSection.ID
                        )
                );
            }
        }

        if(selectedSession.studentResults.size() == oldSessionSize){
            CyUtil.errorMessage('Please select a student to add to the session.');
        }
    }

    public void removeStudentFromSession(){
        system.debug(studentSectionIDToRemove);
        Intervention_Session_Result__c toDelete;
        for(Integer i=0;i<selectedSession.studentResults.size();i++){

            if(selectedSession.studentResults[i].Student_Section__c == studentSectionIDToRemove){
                toDelete = selectedSession.studentResults.remove(i);
                break;
            }
        }
        if(toDelete == null){
            CYUtil.errorMessage('The system was unable to locate the student to be deleted. Please reload the session and check that the student is still present.');
            return;
        }

        if(toDelete.ID != null){
            delete toDelete;
        }
    }

//=============================================Init skill functions==========================================================
    public void initAvaliableAndAllFields(){
        allPrimaryFields = new List<SelectOption>();
        avaliableFields = new List<SelectOption>();
        String schoolProgram = section.Account_Program__r.Name;
        ISTool.getAvaliableSkills(schoolProgram, avaliableFields, allPrimaryFields);
        allAvenuesOptions = ISTool.getAllAvenues();
        siteDetailsOptions = ISTool.getSiteDetailsOptions();
    }

    public void initSelectedFields(){
        selectedFields = new List<SelectOption>();
    }

    public void initializePicklist(){
        primarySkill = '';
        avaliableFields = new List<SelectOption>();
        selectedFields = new List<SelectOption>();
        allPrimaryFields = new List<SelectOption>();
        initAvaliableAndAllFields();
        initSelectedFields();
    }

    public void initAllPicklist(){
        primarySkill = '';
        availableStaff = new List<SelectOption>();
        avaliableFields = new List<SelectOption>();
        selectedFields = new List<SelectOption>();
        allPrimaryFields = new List<SelectOption>();
        allAvenuesOptions = new List<SelectOption>();
        siteDetailsOptions = new List<SelectOption>();
    }

    public Boolean initAvaliableStaff(Section__c sec){
        availableStaff = new List<SelectOption>();
        if(sec == null || sec.Staff_Section__r.isEmpty()){
            CyUtil.errorMessage('There are currently no active staff for this section.');
            return false;
        }

        for(Staff_Section__c s:sec.Staff_Section__r){
            availableStaff.add(new SelectOption(s.Staff__c, s.Staff__r.Name));
        }
        return true;
    }

    public PageReference getRecordPage() {
        String sessionRecordUrl = URL.getSalesforceBaseUrl().toExternalForm() + '/' + sessionID ;
        PageReference sessionPage = new PageReference(sessionRecordUrl);
        return sessionPage;
    }
}