objects/Account.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <label>Active</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>No</fullName>
                </value>
                <value>
                    <fullName>Yes</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Legacy_ID__c</fullName>
        <externalId>true</externalId>
        <label>Legacy ID</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <recordTypes>
        <fullName>School</fullName>
        <active>true</active>
        <description>This record type is for physical school locations.</description>
        <label>School</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Assesment__c.object
<CustomObject>
    <fields>
        <fullName>Date_Administered__c</fullName>
        <description>Date the assessment was administered</description>
        <inlineHelpText>Date the assessment was administered</inlineHelpText>
        <label>Date Administered</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Date__c</fullName>
        <label>Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Goal_Met__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Has the goal for this assessment been met?</description>
        <label>Goal Met</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>School__c</fullName>
        <formula>Student__r.School__r.Name</formula>
        <label>School</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Score__c</fullName>
        <label>Score</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Student_First_Name__c</fullName>
        <formula>Student__r.Student_First_Name__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Student First Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Student_Id__c</fullName>
        <label>Student_Id</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Student_Last_Name__c</fullName>
        <formula>Student__r.Student_Last_Name__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Student Last Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Student_Name__c</fullName>
        <label>Student Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Student__c</fullName>
        <label>Student Assessment</label>
        <referenceTo>Student__c</referenceTo>
        <relationshipLabel>Assessments</relationshipLabel>
        <relationshipName>Assesment</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Assessment Type</label>
        <referenceTo>Picklist_Value__c</referenceTo>
        <relationshipLabel>Assessment Result</relationshipLabel>
        <relationshipName>Assessment_Result</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Assessment</label>
    <nameField>
        <label>Assessments Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Assessments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Picklist_Value__c.object
<CustomObject>
    <fields>
        <fullName>Fieldset__c</fullName>
        <label>Field Set</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Attendance</fullName>
                </value>
                <value>
                    <fullName>Time</fullName>
                </value>
                <value>
                    <fullName>Assignment</fullName>
                </value>
                <value>
                    <fullName>Grade Scale</fullName>
                </value>
                <value>
                    <fullName>Homework</fullName>
                </value>
                <value>
                    <fullName>Behavior Type</fullName>
                </value>
                <value>
                    <fullName>Behavior Consequence</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Picklist Value</label>
    <nameField>
        <label>Display Value</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Picklist Values</pluralLabel>
    <recordTypes>
        <fullName>Assessment_Type</fullName>
        <active>true</active>
        <description>Assessments given by the school.</description>
        <label>Assessment Type</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Student__c.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>true</defaultValue>
        <inlineHelpText>Indicates whether or not this Student record is active. If checked, then this is the current Student record. If unchecked, this is an old Student record.</inlineHelpText>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Grede_Multiselect__c</fullName>
        <label>Grade</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>PS</fullName>
                </value>
                <value>
                    <fullName>PK</fullName>
                </value>
                <value>
                    <fullName>K</fullName>
                </value>
                <value>
                    <fullName>1</fullName>
                </value>
                <value>
                    <fullName>2</fullName>
                </value>
                <value>
                    <fullName>3</fullName>
                </value>
                <value>
                    <fullName>4</fullName>
                </value>
                <value>
                    <fullName>5</fullName>
                </value>
                <value>
                    <fullName>6</fullName>
                </value>
                <value>
                    <fullName>7</fullName>
                </value>
                <value>
                    <fullName>8</fullName>
                </value>
                <value>
                    <fullName>9</fullName>
                </value>
                <value>
                    <fullName>10</fullName>
                </value>
                <value>
                    <fullName>11</fullName>
                </value>
                <value>
                    <fullName>12</fullName>
                </value>
                <value>
                    <fullName>UN Ungraded</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Legacy_Id__c</fullName>
        <description>USI ID</description>
        <inlineHelpText>Displays the Unique Student Identifier (USI) for the student. This field is not used by SchoolForce, but you can use it for reporting purposes.</inlineHelpText>
        <label>USI ID</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>School__c</fullName>
        <inlineHelpText>Displays the name of the student&apos;s current SchoolForce school. You can click on the link to see the details of this school.</inlineHelpText>
        <label>School</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Students</relationshipLabel>
        <relationshipName>Students</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Student_First_Name__c</fullName>
        <inlineHelpText>Displays the student&apos;s first name.</inlineHelpText>
        <label>Student First Name</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Student_Id__c</fullName>
        <inlineHelpText>Displays the student&apos;s ID. This field displays on report cards, progress reports, and transcripts. It must be unique; SchoolForce uses this ID to link the Student record with the correct Contact record.</inlineHelpText>
        <label>Student Id</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Student_Last_Name__c</fullName>
        <inlineHelpText>Displays the student&apos;s last name.</inlineHelpText>
        <label>Student Last Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Student__c</fullName>
        <inlineHelpText>Displays the student&apos;s middle name.</inlineHelpText>
        <label>Student Middle Name</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <label>Student</label>
    <nameField>
        <label>Student Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Students</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/Test_AssessmentWizard.cls
@isTest
private class Test_AssessmentWizard {
	
	private static List<Picklist_Value__c> assessmentTypes = new List<Picklist_Value__c>();
	private static void setupData(){
		testDataSetupUtil_v2.setUPCoreData(1);
		testDataSetupUtil_v2.setUpStaffData(1);
		testDataSetupUtil_v2.setUpStudentData(3);
		boolean isManagedPackage = Schema.SObjectType.Assesment__c.getName().replace('__c', '').contains('__');
		string assessmentTypeRTID = core_SoqlUtils.getRecordTypesBySobject('Picklist_Value__c').get('Assessment_Type');
		string fieldSet = ((isManagedPackage)?'SchoolForce__':'') + 'Score__c, ';
		fieldSet = fieldSet + ((isManagedPackage)?'SchoolForce__':'') + 'Goal_Met__c';
		
		assessmentTypes.add(new Picklist_Value__c(RecordTypeID = assessmentTypeRTID, Name = 'Test1'
												,FieldSet__c = fieldSet
			));
		assessmentTypes.add(new Picklist_Value__c(RecordTypeID = assessmentTypeRTID, Name = 'LongTest2'
												,FieldSet__c = fieldSet
			));
			
		insert assessmentTypes;
	}
	private static void setupData1(){
		testDataSetupUtil_v2.setUPCoreData(1);
		testDataSetupUtil_v2.setUpStaffData(1);
		testDataSetupUtil_v2.setUpStudentData(3);
		boolean isManagedPackage = Schema.SObjectType.Assesment__c.getName().replace('__c', '').contains('__');
		string assessmentTypeRTID = core_SoqlUtils.getRecordTypesBySobject('Picklist_Value__c').get('Assessment_Type');
		string fieldSet = ((isManagedPackage)?'SchoolForce__':'') + 'Score__c, ';
		fieldSet = fieldSet + ((isManagedPackage)?'SchoolForce__':'') + 'Goal_Met__c';
		fieldSet = fieldSet + ((isManagedPackage)?'SchoolForce__':'') + ',Date_Administered__c';
		//System.assertEquals('p',fieldSet);
		//fieldSet = fieldSet + 'Date_Administered__c';
		assessmentTypes.add(new Picklist_Value__c(RecordTypeID = assessmentTypeRTID, Name = 'Test1'
												,FieldSet__c = fieldSet
			));
		assessmentTypes.add(new Picklist_Value__c(RecordTypeID = assessmentTypeRTID, Name = 'LongTest2'
												,FieldSet__c = fieldSet
			));
			
		insert assessmentTypes;
	}
	
	private static testmethod void testConstructor(){
		setupdata();
		test.startTest();
			AssessmentWizardController controller = new AssessmentWizardController();
			system.assertEquals(true, controller.mainPage);
			system.assert(controller.yearOptions.size() >= 1);
			system.assertEquals(0, controller.studentList.size());
		test.stopTest();
	}
	
	private static testmethod void testStudentSearch(){
		setupdata();
        test.startTest();
			AssessmentWizardController controller = new AssessmentWizardController();
			controller.searchChange();
			controller.searchType = 'student';
			controller.studentSearchInfo.school = '--None--';
			controller.studentSearchInfo.student.Active__c = true;
            controller.studentSearchInfo.student.Grede_Multiselect__c='5';
			controller.groupSearch();
			system.assertEquals(3, controller.studentSearchResults.size());
			for(AssessmentWizardController.studentWrapper s: controller.studentSearchResults){
				s.selected = true;
			}
            Set<String> ids= new Set<String>(); 
            String str=String.valueOf(controller.studentSearchResults[0].student.Student_Id__c); 
            ids.add(str);
            controller.addStudents(ids);
            system.assertEquals(1, controller.studentList.size());
            system.assertEquals(0, controller.studentSearchResults.size());
           
		test.stopTest();
	}
    private static testmethod void testSectionSearch(){
		setupData();
		
		test.startTest();
			AssessmentWizardController controller = new AssessmentWizardController();
			controller.searchChange();
			controller.searchType = 'section';
			controller.groupSearch();
			system.assertEquals(1, controller.sectionSearchResults.size());
			controller.sectionSearchResults[0].selected = true;	
            controller.addSections();
		test.stopTest();
	}
    private static testmethod void testAssessmentGen(){
		setupdata();

		test.startTest();
			AssessmentWizardController controller = new AssessmentWizardController();
			controller.searchChange();
			controller.searchType = 'student';
			controller.studentSearchInfo.school = '--None--';
			controller.studentSearchInfo.student.Active__c = true;
            controller.studentSearchInfo.student.Grede_Multiselect__c='5';
			controller.groupSearch();
			for(AssessmentWizardController.studentWrapper s: controller.studentSearchResults){
				s.selected = true;
			}
            Set<String> ids= new Set<String>(); 
            String str=String.valueOf(controller.studentSearchResults[0].student.Student_Id__c); 
            ids.add(str);
            controller.addStudents(ids);
			controller.studentList[0].selected = true;
			controller.removestudents();
			//system.assertEquals(2, controller.studentList.size());
			controller.generateAssessments();
			
			//system.assertEquals(2, controller.newAssessments.size());
			
		test.stopTest();
	}
    private static testMethod void testExport(){
		setupdata();

		test.startTest();
			AssessmentWizardController controller = new AssessmentWizardController();
			controller.searchChange();
			controller.searchType = 'student';
			controller.studentSearchInfo.school = '--None--';
			controller.studentSearchInfo.student.Active__c = true;
            controller.studentSearchInfo.student.Grede_Multiselect__c='5';
			controller.groupSearch();
			for(AssessmentWizardController.studentWrapper s: controller.studentSearchResults){
				s.selected = true;
			}
            Set<String> ids= new Set<String>(); 
            String str=String.valueOf(controller.studentSearchResults[0].student.Student_Id__c); 
            ids.add(str);
            str=String.valueOf(controller.studentSearchResults[1].student.Student_Id__c);
            ids.add(str);
            controller.addStudents(ids);	
            controller.generateAssessments();
			controller.selectedType = assessmentTypes[0].id;
			controller.changeAssessmentType();
			controller.saveForExport();
			controller.goHome();
			
		test.stopTest();
	}
    
    private static testMethod void testImport(){
		setupdata1();

			assessmentWizardController controller = new AssessmentWizardController();
			controller.searchChange();
			controller.searchType = 'student';
			controller.studentSearchInfo.school = '--None--';
			controller.studentSearchInfo.student.Active__c = true;
            controller.studentSearchInfo.student.Grede_Multiselect__c='5';
			controller.groupSearch();
			for(AssessmentWizardController.studentWrapper s: controller.studentSearchResults){
				s.selected = true;
			}
			Set<String> ids= new Set<String>(); 
            String str1=String.valueOf(controller.studentSearchResults[0].student.Student_Id__c); 
            ids.add(str1);
            str1=String.valueOf(controller.studentSearchResults[1].student.Student_Id__c);
            ids.add(str1);
            controller.addStudents(ids);
			for(AssessmentWizardController.studentWrapper s: controller.studentList){
				s.selected = true;
			}
			controller.generateAssessments();
			controller.selectedType = assessmentTypes[0].id;
			controller.changeAssessmentType();
			controller.saveForExport();
			List<String> str =new List<String>();
			//transform the data some to boost coverage (<75% without)
			List<string> csvData = controller.csvData.split('\n');
			controller.csvData = '';
			//system.assertEquals(str,csvData);
			List<string> rowData = new List<String>();
			rowData = csvData[2].split(',');
			rowData[3] = 'abc 123';
			rowData[4] = 'TRUE'; 
			rowData[5] = '3/31/2016';
				
			
			csvData[2] = StringUtils.join(rowData, ',', null);
			rowData = csvData[3].split(',');
			rowData[3] = '"abc \n123"';
			rowData[4] = 'FALSE';
            rowData[5] = '3/31/2016';

			csvData[3] = StringUtils.join(rowData, ',', null);
     		/*rowData = csvData[4].split(',');
			rowData[3] = '"""abc123"""';
			rowData[4] = 'TRUE';
             rowData[5] = '3/31/2016';

   			csvData[4] = StringUtils.join(rowData, ',', null);*/
           
			string importData = StringUtils.join(csvData, '\n', null);
			
			csvData.clear();
			rowData.clear();
			
			test.startTest();
				PageReference pref = controller.startImport();
				system.assertEquals(pref.getURL(), Page.Assessment_Import.getURL());
				controller.fileBlob = Blob.valueOf(importData);
			//	system.assertEquals('abc',importData);
				importData = '';
				controller.fileName = 'testData.csv';
				controller.fileContentType = 'text/csv';
				
				controller.processInput();
				controller.saveInput();
			test.stopTest();
	}
    private static testMethod void testExistingExport(){
		setupdata();
		
		Assesment__c testAssessment = new Assesment__c(Student__c= testDataSetupUtil_v2.studentsList[0].id
										,Type__c = assessmentTypes[0].id
										,Goal_Met__c = true
										,Score__c = '5'
										,Date__c = system.today());
										
		insert testAssessment;

		test.startTest();
			AssessmentWizardController controller = new AssessmentWizardController();
			
			//load export screen
			controller.startExistingExport();
			system.assertEquals(true,controller.showExport);
			
			//setup search
			//use an instance of section to hold the data
			controller.startDate = system.today().format();
			controller.endDate = system.today().format();
			controller.gradeHolder.All_Grades__c = '1;2;3;4;5;';
			controller.selectedType = assessmentTypes[0].id;
			controller.studentSearchInfo.school = testDataSetupUtil_v2.school.id;
			controller.searchExisting();
			//export as CSV
			controller.exportExisting();
			controller.saveExisting();
			testAssessment = [select id, Score__c from Assesment__c where id=: testAssessment.id];
			test.stopTest();
	}
    private static testMethod void testFunctionality(){
        setupdata();
            AssessmentWizardController controller = new AssessmentWizardController();
        	test.startTest();
            controller.searchChange();
			controller.searchType = 'section';
			controller.groupSearch();
			system.assertEquals(1, controller.sectionSearchResults.size());
            controller.goToMain();
            controller.changeYear();
            controller.slctdStdId=String.valueOf(testDataSetupUtil_v2.studentsList[0].ID)+','+String.valueOf(testDataSetupUtil_v2.studentsList[1].Id);
            controller.getstdata();
            //controller.exportExisting2();
            controller.dummyRefresh();
            PageReference pr= controller.cancelImport();
        
    }
	 private static testMethod void testExistingExport2(){
		setupdata();
		Student__c st=testDataSetupUtil_v2.studentsList[0];
        st.Active__C=true;
        update st;
        system.assertEquals(st.Active__C,true);
		Assesment__c testAssessment = new Assesment__c(Student__c= st.id
										,Type__c = assessmentTypes[0].id
                                        ,Student_Id__c=st.Student_Id__c
										,Goal_Met__c = true
										,Score__c = '5'
										,Date__c = system.today());
										
		insert testAssessment;
       
        update testAssessment;
        test.startTest();
			AssessmentWizardController controller = new AssessmentWizardController();
			controller.startExistingExport();
			system.assertEquals(true,controller.showExport);
		    controller.selectedType = assessmentTypes[0].id;
			controller.studentSearchInfo.student.Student_Id__c=testAssessment.Student_Id__c;
		    controller.studentSearchInfo.school=testAssessment.student__r.School__r.Name;
            controller.studentSearchInfo.indicatorArea='--None--';
            controller.searchExisting();
            List<Assesment__c> ast=[select Date__c, Student_Name__c, Student__r.Student_First_Name__c, Student__r.Student_Last_Name__c, Student__r.Legacy_Id__c, Score__c, Goal_Met__c From Assesment__c where Student__c != null and Type__c='a0rR000000235AmIAI' and Student__r.Active__c = true AND Student_Id__c = 'SC1230_Stu0' order by Date__c Limit 3000]; 
            System.assertEquals(testAssessment.student__r.Active__C,False);
       		controller.exportExisting();
			controller.saveExisting();
			testAssessment = [select id, Score__c from Assesment__c where id=: testAssessment.id];
			test.stopTest();
}
}