objects/Account.object
<CustomObject>
    <fields>
        <fullName>Reference_Id__c</fullName>
        <externalId>true</externalId>
        <label>Reference Id</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Grade__c.object
<CustomObject>
    <fields>
        <fullName>Student__c</fullName>
        <label>Student</label>
        <referenceTo>Student__c</referenceTo>
        <relationshipLabel>Grades</relationshipLabel>
        <relationshipName>Grades</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Grade</label>
    <nameField>
        <displayFormat>G-{0}</displayFormat>
        <label>Grade Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Grades</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Notification__c.object
<CustomObject>
    <description>This object captures notification data which allows administrators to schedule system notifications.</description>
    <fields>
        <fullName>End_Date__c</fullName>
        <description>This is the date that the notification period ends.</description>
        <label>End Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Setup__c</fullName>
        <description>This is a lookup to the setup object that the notifications are for.</description>
        <label>Setup</label>
        <referenceTo>Setup__c</referenceTo>
        <relationshipLabel>Notifications</relationshipLabel>
        <relationshipName>Notifications</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <description>This is the date that the notification period starts.</description>
        <label>Start Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <label>Notification</label>
    <nameField>
        <label>Notification Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Notifications</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Picklist_Value__c.object
<CustomObject>
    <fields>
        <fullName>Setup__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Setup</label>
        <referenceTo>Setup__c</referenceTo>
        <relationshipLabel>Picklist Values</relationshipLabel>
        <relationshipName>Picklist_Values</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Picklist Value</label>
    <nameField>
        <label>Display Value</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Picklist Values</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Points__c.object
<CustomObject>
    <fields>
        <fullName>Points__c</fullName>
        <label>Points</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Student__c</fullName>
        <label>Student</label>
        <referenceTo>Student__c</referenceTo>
        <relationshipLabel>Points Transactions</relationshipLabel>
        <relationshipName>Points_Transactions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Points Transaction</label>
    <nameField>
        <displayFormat>PT-{000000}</displayFormat>
        <label>Points Transaction Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Points Transactions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Schedule__c.object
<CustomObject>
    <fields>
        <fullName>Date__c</fullName>
        <label>Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Setup__c</fullName>
        <label>Setup</label>
        <referenceTo>Setup__c</referenceTo>
        <relationshipLabel>Points Reset Schedules</relationshipLabel>
        <relationshipName>Schedules</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Schedule</label>
    <nameField>
        <displayFormat>S-{0000}</displayFormat>
        <label>Schedule Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Schedules</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Setup__c.object
<CustomObject>
    <description>This object is used to setup Schoolforce and is referenced in multiple pieces of code.  There should be one setup object per school.</description>
    <fields>
        <fullName>Days__c</fullName>
        <label>Days</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <controllingField>Points_Frequency__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Sun</fullName>
                </value>
                <value>
                    <fullName>Mon</fullName>
                </value>
                <value>
                    <fullName>Tue</fullName>
                </value>
                <value>
                    <fullName>Wed</fullName>
                </value>
                <value>
                    <fullName>Thur</fullName>
                </value>
                <value>
                    <fullName>Fri</fullName>
                </value>
                <value>
                    <fullName>Sat</fullName>
                </value>
                <value>
                    <fullName>1</fullName>
                </value>
                <value>
                    <fullName>2</fullName>
                </value>
                <value>
                    <fullName>3</fullName>
                </value>
                <value>
                    <fullName>4</fullName>
                </value>
                <value>
                    <fullName>5</fullName>
                </value>
                <value>
                    <fullName>6</fullName>
                </value>
                <value>
                    <fullName>7</fullName>
                </value>
                <value>
                    <fullName>8</fullName>
                </value>
                <value>
                    <fullName>9</fullName>
                </value>
                <value>
                    <fullName>10</fullName>
                </value>
                <value>
                    <fullName>11</fullName>
                </value>
                <value>
                    <fullName>12</fullName>
                </value>
                <value>
                    <fullName>13</fullName>
                </value>
                <value>
                    <fullName>14</fullName>
                </value>
                <value>
                    <fullName>15</fullName>
                </value>
                <value>
                    <fullName>16</fullName>
                </value>
                <value>
                    <fullName>17</fullName>
                </value>
                <value>
                    <fullName>18</fullName>
                </value>
                <value>
                    <fullName>19</fullName>
                </value>
                <value>
                    <fullName>20</fullName>
                </value>
                <value>
                    <fullName>21</fullName>
                </value>
                <value>
                    <fullName>22</fullName>
                </value>
                <value>
                    <fullName>23</fullName>
                </value>
                <value>
                    <fullName>Last</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Points_Frequency__c</fullName>
        <label>Points Frequency</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Weekly</fullName>
                </value>
                <value>
                    <fullName>Monthly</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Points_Reset_Date__c</fullName>
        <description>This field will be set  by an apex job . This field will be used to determine today&apos;s Current Balance field on student record.</description>
        <label>Points Reset Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Points_Reset_Value__c</fullName>
        <label>Points Reset Value</label>
        <precision>6</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Schedule_End_Date__c</fullName>
        <label>Schedule End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Schedule_Start_Date__c</fullName>
        <label>Schedule Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>School__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>School</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1 OR 2</booleanFilter>
            <filterItems>
                <field>Account.RecordType.Name</field>
                <operation>equals</operation>
                <value>School</value>
            </filterItems>
            <filterItems>
                <field>Account.RecordType.Name</field>
                <operation>equals</operation>
                <value>Summer School</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Setup</relationshipLabel>
        <relationshipName>Setup</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Term__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Term refers to the Term &apos;Template&apos; that the administrator associates to the School; this contains all Semeser/Quarter/Period logic necessary to create Sessions.</description>
        <label>Term</label>
        <referenceTo>Time_Element__c</referenceTo>
        <relationshipLabel>Setup</relationshipLabel>
        <relationshipName>Setup</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Setup</label>
    <nameField>
        <displayFormat>S-{0}</displayFormat>
        <label>Setup ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Setup</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/Staff__c.object
<CustomObject>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <label>Staff</label>
    <nameField>
        <label>Staff Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Staff</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/Student__c.object
<CustomObject>
    <fields>
        <fullName>Setup__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Displays the Setup record associated to this Student record. The Setup record defines the settings for the school in a specific school year.</inlineHelpText>
        <label>Setup</label>
        <referenceTo>Setup__c</referenceTo>
        <relationshipLabel>Students</relationshipLabel>
        <relationshipName>Students</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Student__c</fullName>
        <inlineHelpText>Displays the student&apos;s middle name.</inlineHelpText>
        <label>Student Middle Name</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Today_s_Points_Balance__c</fullName>
        <description>This field will store the sum of all points given/taken from the reset date</description>
        <inlineHelpText>Displays the sum of the student&apos;s points. The Points module uses this field.</inlineHelpText>
        <label>Today&apos;s Points Balance</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Week_To_Date_Points_Balance__c</fullName>
        <inlineHelpText>Displays the student&apos;s point balance for the current week. The Points module uses this field.</inlineHelpText>
        <label>Week-To-Date Points Balance</label>
        <precision>4</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Student</label>
    <nameField>
        <label>Student Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Students</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Time_Element__c.object
<CustomObject>
    <fields>
        <fullName>Date_Start_Date__c</fullName>
        <defaultValue>Today()</defaultValue>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>End_Date__c</fullName>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <label>Time</label>
    <nameField>
        <displayFormat>T-{000000}</displayFormat>
        <label>Time Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Time</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/Points_Utils.cls
public with sharing class Points_Utils {
	
	public static void updatePointsBalance(Map <Id, Points__c> newMap){
		Set<String> studentIds = new Set<String>();
		Map<String,Student__c> updateStudents = new Map<String,Student__c>();
		Date refreshDate;
		Boolean pointsReset = true;
		Setup__c setup;
					
		Date weekStartDate = system.today().toStartofWeek();
		 for(Points__c p: newMap.values()){
		 	studentIds.add(p.Student__c);
		 }
		 
		 if(studentIds!=null){
		 	Integer i = 0;
		 	for(Student__c s: core_SoqlUtils.getStudents(studentIds)){
		 		updateStudents.put(s.Id,s);
		 		if(i == 0){
		 			refreshDate = s.Setup__r.Points_Reset_Date__c;
		 			setup = s.Setup__r;
		 		}
		 		i++;
		 	}
		 }
		List<Schedule__c> firstResetDate = [SELECT Date__c FROM Schedule__c WHERE Setup__c =:setup.Id order by Date__c asc LIMIT 1];
		if(firstResetDate!=null && !firstResetDate.isEmpty()){
			if(System.today()< firstResetDate[0].date__c){
				pointsReset = false;
				refreshDate = setup.Term__r.Date_Start_Date__c;
			}
		}
		else{
			pointsReset = false;
			refreshDate = setup.Term__r.Date_Start_Date__c;
		}
		 
		Map<String,Decimal> studentCurrentPointsBalanceMap = Points_SoqlUtils.getCurrentBalance(refreshDate, System.today(), studentIds);
		Map<String,Decimal> studentWeekToDatePointsBalanceMap = Points_SoqlUtils.getCurrentBalance(weekStartDate, System.today(), studentIds);
		Decimal resetValue = setup.Points_Reset_Value__c;
		 for(String s: studentIds){
		 	if(studentCurrentPointsBalanceMap.get(s)!=null)
		 		updateStudents.get(s).Today_s_Points_Balance__c = studentCurrentPointsBalanceMap.get(s) + ((resetValue != null && pointsReset)?resetValue:0);
		 	
		 	if(studentWeekToDatePointsBalanceMap.get(s)!=null)
		 		updateStudents.get(s).Week_To_Date_Points_Balance__c = studentWeekToDatePointsBalanceMap.get(s)+((resetValue != null && pointsReset)?resetValue:0);
		 	
		 }
		 
		 update updateStudents.values();
	}
	
	public static void updatePointsBalance(List<Student__c> studentsList){
		List<Student__c> updateStudents = new List<Student__c>();
		 for(Student__c s: studentsList){
		 		s.Today_s_Points_Balance__c = s.Setup__r.Points_Reset_Value__c; 
		 		s.Week_To_Date_Points_Balance__c = s.Setup__r.Points_Reset_Value__c;
		 	
		 		updateStudents.add(s);	 
		 }
		 
		 update updateStudents; 
	}
	
	public static Set<String> getSetupsForReset(){
	 	Set<String> setupIds = new Set<String>();
	 	for(Schedule__c sc:[SELECT Id, Setup__c FROM Schedule__c WHERE Date__c =: System.today()]){
	 		setupIds.add(sc.Setup__c);
	 	}
		return setupIds;
	}
	
	public static void deleteOldSchedule(Set<String> setupIds){
		try{
			List<Schedule__c> oldschedules = [SELECT Id FROM Schedule__c WHERE Setup__c in: setupIds];
			if(oldschedules != null)
				delete oldschedules;
		}
		catch(Exception ex){
			ApexPages.addMessage(new apexpages.message(apexpages.severity.ERROR, 'There was an error updating new schedule'));
    		Global_Error__c ge = Error_Handling.handleError('Setup, '+setupIds+ 'Points Reset Schedule Config', 'Error deleting setup old schedules', ex);
			insert ge;
		}
	
	}
	
	public static void createScheduleRecords(Map<Id,Setup__c> oldsetups,Map<Id,Setup__c> newsetups){
		Set<String> setupsIds = new Set<String>();
		Map<String,Schedule__c> pointsScheduleMap ;
		Integer k;
		for(Setup__c s: newsetups.values()){
			//setupsIds.add(s.Id);
			if((s.Schedule_Start_Date__c!=null && s.Schedule_Start_Date__c!=null && s.Points_Frequency__c!=null )&&(s.Schedule_Start_Date__c!=oldsetups.get(s.Id).Schedule_Start_Date__c || s.Schedule_End_Date__c!=oldsetups.get(s.Id).Schedule_End_Date__c || s.Points_Frequency__c!=oldsetups.get(s.Id).Points_Frequency__c || s.Days__c !=oldsetups.get(s.Id).Days__c)){
				if(s.Schedule_Start_Date__c > s.Schedule_End_Date__c)
					s.addError('Start Date cannot be later than End Date. Please enter a valid date.');
				setupsIds.add(s.Id);
				System.debug('$$SetupDays'+s.Days__c);
				if(s.Points_Frequency__c == 'Weekly'){
					k=0;
					List<Integer> dayValues = core_DateUtils.returnWeekDays(s.Days__c.split(';'));
					pointsScheduleMap = new Map<String,Schedule__c>();	
					for(Date startDate = s.Schedule_Start_Date__c;startDate <= s.Schedule_End_Date__c;startDate= startDate.addDays(7)){
						System.debug('StartDate$$$$'+startDate.format());
						for(Integer i: dayValues){System.debug('StartDate$$$$'+startDate.format());
							if(startDate.toStartofWeek().addDays(i) >= s.Schedule_Start_Date__c && startDate.toStartofWeek().addDays(i) <= s.Schedule_End_Date__c){
								Date d = startDate.toStartofWeek().addDays(i);
								pointsScheduleMap.put(s.Id+'_'+d.format(),new Schedule__c(Setup__c=s.Id,Reference_Id__c=s.Id+'_'+d.format(),Date__c = d));
								if(k==0){
									s.Points_Reset_Date__c = d;
									k++;
									System.debug('s.Points_Reset_Date__c$$$$'+s.Points_Reset_Date__c);
								}
							}
						}
					}
				}
				else if(s.Points_Frequency__c == 'Monthly'){
						k=0;
						pointsScheduleMap = new Map<String,Schedule__c>();	
						for(Date startDate = s.Schedule_Start_Date__c;startDate <= s.Schedule_End_Date__c;startDate=startDate.addmonths(1)){
							for(String day: s.Days__c.split(';')){   
								Date monthdate;
								if(day == 'last' || day=='Last'){ 
									Integer lastDay = date.daysInMonth(startDate.Year(), startDate.month());
									
									monthdate = date.newinstance(startDate.year(), startDate.month(), lastDay);
								}
								else{	
									monthdate = date.newinstance(startDate.year(), startDate.month(), Integer.valueOf(day));
								}
								if(monthdate >= s.Schedule_Start_Date__c && monthdate <= s.Schedule_End_Date__c){
									pointsScheduleMap.put(s.Id+'_'+monthdate.format(),new Schedule__c(Setup__c=s.Id,Reference_Id__c=s.Id+'_'+monthdate.format(),Date__c = monthdate));
									if(k==0){
												s.Points_Reset_Date__c = monthdate;
												k++;
									}
								}
							}
						}
					}
					
		}
		}
		System.debug('$$@@@SetupIDs2'+setupsIds); 
		System.debug('$$SetupIDs2'+setupsIds.size());
		if(setupsIds.size() > 0){
			Points_Utils.deleteOldSchedule(setupsIds);
			System.debug('Deleted&&&&&&&&&&'); 
		}
		if(pointsScheduleMap!=null && !pointsScheduleMap.values().isEmpty())
			upsert pointsScheduleMap.values();
			
	}
	
		public static void pointsNotifications (ID UserID){
		User u = [select id, Email from User where id =: UserID];
		
		List<Threshold__c> thresholds = [select Cumulative__c, Notification__r.Setup__c, Notification__r.Grade__c, Notification__r.Setup__r.School__r.Name
										from Threshold__c
										where Notification__r.Module__c = 'Points'
										and Notification__r.Start_Date__c <= today
										and Notification__r.End_Date__c >= today
										order by Cumulative__c];
		if(!thresholds.isEmpty()){
			Set<Id> setups = new Set<ID>();
			boolean hasNullSetup = false;
			for(Threshold__c t:thresholds){
				if(t.Notification__r.Setup__c == null){
					hasNullSetup = true;
					break;
				} else {
					setups.add(t.Notification__r.Setup__c);
				}
			}
			
			string query = 'select id, Name, Setup__c, Today_s_Points_Balance__c,Grade__c'+
							' From Student__c'+
							' Where Active__c = true'+
							' and Today_s_Points_Balance__c >=' + thresholds[0].Cumulative__c;
			query += (hasNullSetup)?'':(' and Setup__c in: setups');
			query += ' order by Name';
			system.debug(query);
			List<Student__c> students = Database.query(query);
			
			string emailbody = '';
			Messaging.SingleEmailMessage email = new Messaging.SingleEmailMessage();
			email.setUseSignature(false);
			system.debug(u.Email);
			email.setToAddresses(new List<String>{String.valueOf(u.Email)});
			email.setSubject('Points Notifications for ' + system.today().format());
			
			for(Threshold__c t:thresholds){
				if(t.Notification__r.Setup__c == null){
					emailbody += 'All Schools: ';
				} else {
					emailbody += t.Notification__r.Setup__r.School__r.Name + ': ';
				}
				emailbody += 'Students Over ' + t.Cumulative__c + ' Points: \n';
				
				Set<String> grades = new Set<String>();
				if(t.Notification__r.Grade__c != null){
					grades = new Set<String>(StringUtils.splitAndTrim(t.Notification__r.Grade__c, ';'));
				}
				for(Student__c s:students){
					if(s.Today_s_Points_Balance__c >= t.Cumulative__c){
						if(grades.isEmpty() || grades.contains(s.Grade__c)){
							emailbody += '\t' + s.Name + '\n';
						}
					}
				}
				emailbody += '\n';
			}
			email.setPlainTextBody(emailbody);
			Messaging.SendEmailResult[] results = new Messaging.SendEmailResult[]{};
			results.addAll(Messaging.sendEmail(new Messaging.SingleEmailMessage[]{email}, false));
			
			for(Messaging.SendEmailResult result:results){
				if(!result.isSuccess()){ //note: this is a method, not a field.
					system.debug(result.getErrors()[0].getMessage());
					Error_Handling.schoolForceException e = new Error_Handling.schoolforceexception();
				}	
			}
		}
	}
	
	@isTest
	private static void testPointsNotifications(){
		testDataSetupUtil_v2.setUPCoreData(2);
		testDataSetupUtil_v2.setUPStaffData(2);
		testDataSetupUtil_v2.setUPStudentData(2);
		TestDataSetupUtil_v2.activeSetUp.Schedule_Start_Date__c = TestDataSetupUtil_v2.term.Date_Start_Date__c;
        TestDataSetupUtil_v2.activeSetUp.Schedule_End_Date__c = TestDataSetupUtil_v2.term.End_Date__c;
        TestDataSetupUtil_v2.activeSetUp.Points_Frequency__c = 'Monthly';
        TestDataSetupUtil_v2.activeSetUp.Points_Reset_Value__c = 0;
        TestDataSetupUtil_v2.activeSetUp.Days__c = '1';
        update TestDataSetupUtil_v2.activeSetUp;
		List<Picklist_Value__c> cats = testDataSetupUtil_v2.createPointsCats(null);
		
		string refID = (String)testDataSetupUtil_v2.studentsList[0].id+(String)cats[0].id+String.valueOf(system.today())+'';
		Points__c point = new Points__c(Student__c = testDataSetupUtil_v2.studentsList[0].id
										,Points_Date__c = system.today()
										,Points__c = 35
						 				,Staff__c = testDataSetupUtil_v2.teachersList[0].id
										,Category__c = cats[0].id
										,Reference_Id__c = refID);
		
		insert point;
		
		Notification__c notification = new Notification__c(Module__c = 'Points'
										,Setup__c = testDataSetupUtil_v2.activeSetUp.id
										,Start_Date__c = system.today().addDays(-7)
										,End_Date__c = system.today().addDays(7)
										,Grade__c = '1;2;3;4;5;6;7;8;9;10;11;12');
		
		insert notification;
		
		Threshold__c thresh = new Threshold__c(Notification__c = notification.id
										,Cumulative__c = 30);
										
		insert thresh;
		
		Test.startTest();
			Points_Utils.pointsNotifications(testDataSetupUtil_v2.staffUsersList[0].id);
		Test.stopTest();
	}
}