objects/Account_Program__c.object
<CustomObject>
    <description>The Account/Program object is part of the Interventions App and links Programs and Schools/Accounts.  This linking occurs in the Interventions Setup when a school selects which interventions Programs they will enroll in for a specific year.  This object tracks the relationships of Programs and Schools and whether the Programs are active.</description>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Is this Program active for this School in this year?</inlineHelpText>
        <label>Active?</label>
        <type>Checkbox</type>
    </fields>
    <label>Account/Program</label>
    <nameField>
        <label>School Program Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Accounts/Programs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Data_Load_Log__c.object
<CustomObject>
    <description>Logs information about data loads such as status and success/failure statistics.</description>
    <fields>
        <fullName>Batch_ID__c</fullName>
        <description>This is the id of the batch that the Data Load Log was created for</description>
        <label>Batch ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Class_Name__c</fullName>
        <label>Class Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>End_Time__c</fullName>
        <description>Date/time this load finished processing.</description>
        <label>End Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Failed_Records__c</fullName>
        <description>Number of failed records.</description>
        <label>Failed Records</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Messages__c</fullName>
        <description>Any messages generated during the load.</description>
        <label>Messages</label>
        <length>32000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Processed_Record_Type__c</fullName>
        <label>Processed Record Type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Processed_Records__c</fullName>
        <description>The total number of records processed successfully by this batch.</description>
        <inlineHelpText>The total number of records processed successfully by this batch.</inlineHelpText>
        <label>Processed Records</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Reporting_Period__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>the reporting period that created this data load log</description>
        <label>Reporting Period</label>
        <referenceTo>Time_Element__c</referenceTo>
        <relationshipLabel>Data Load Log</relationshipLabel>
        <relationshipName>Data_Load_Log</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Start_Time__c</fullName>
        <description>Date/time this load was started.</description>
        <label>Start Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Status of this data load.</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Pending</fullName>
                </value>
                <value>
                    <fullName>Running</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Total_Records__c</fullName>
        <description>Total number of records processed.</description>
        <label>Total Records</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <description>Type of data loaded.</description>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Section</fullName>
                </value>
                <value>
                    <fullName>Session</fullName>
                </value>
                <value>
                    <fullName>Staff</fullName>
                </value>
                <value>
                    <fullName>Staff/Section</fullName>
                </value>
                <value>
                    <fullName>Student</fullName>
                </value>
                <value>
                    <fullName>Student/Section</fullName>
                </value>
                <value>
                    <fullName>Interventions Data Deactivation</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Data Load Log</label>
    <nameField>
        <displayFormat>DLL-{0000000}</displayFormat>
        <label>Data Load Log #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Data Load Log</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/EOY_Progress__c.object
<CustomObject>
    <description>This object is used to determine the current completion progress in the EOY Wizard.</description>
    <fields>
        <fullName>Is_Complete__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Complete</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Module_Name__c</fullName>
        <label>Module Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Year__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>The year that the EOY Wizard process is for.</description>
        <inlineHelpText>The year for the EOY Wizard to process.</inlineHelpText>
        <label>Year</label>
        <referenceTo>Time_Element__c</referenceTo>
        <relationshipLabel>EOY Progresses</relationshipLabel>
        <relationshipName>EOY_Progresses</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>EOY Progress</label>
    <nameField>
        <label>EOY Save State Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>EOY Progresses</pluralLabel>
    <recordTypes>
        <fullName>EOY</fullName>
        <active>true</active>
        <label>EOY</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Indicator_Area_Student__c.object
<CustomObject>
    <description>The Indicator Area/Student object is a joiner object that associates an Indicator Area and a Student.</description>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>true</defaultValue>
        <inlineHelpText>Is the Indicator Area associated to this Student active? If this box is unchecked then the Student no longer requires intervention in this area.</inlineHelpText>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <label>Indicator Area/Student</label>
    <nameField>
        <displayFormat>IA/S -{000}</displayFormat>
        <label>IA/Student ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Indicator Area/Student</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Section__c.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Check this box if the section is a currently active section</description>
        <inlineHelpText>Check this box if the section is a currently active section</inlineHelpText>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Archived__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Archived</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Reporting_Period__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Usually the only reporting period; could be the first if the section spans multiple reporting periods.</description>
        <label>Reporting Period</label>
        <referenceTo>Time_Element__c</referenceTo>
        <relationshipLabel>Sections (First Reporting Period)</relationshipLabel>
        <relationshipName>Sections1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Section__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Recursive lookup for groups</description>
        <label>Section</label>
        <referenceTo>Section__c</referenceTo>
        <relationshipLabel>Groups in Section</relationshipLabel>
        <relationshipName>Sections1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Time__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Time</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Time_Element__c.Picklist_Value__r.Name</field>
                <operation>equals</operation>
                <value>Year</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Time_Element__c</referenceTo>
        <relationshipLabel>Sections</relationshipLabel>
        <relationshipName>Sections</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <description>Section or Standard Group or Custom Group</description>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Section</fullName>
                </value>
                <value>
                    <fullName>Standard Group</fullName>
                </value>
                <value>
                    <fullName>Custom Group</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Section</label>
    <nameField>
        <label>Section Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sections</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Staff_Section__c.object
<CustomObject>
    <fields>
        <fullName>Archived__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Archived</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Is_Active__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Is Active?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Section__c</fullName>
        <label>Section</label>
        <referenceTo>Section__c</referenceTo>
        <relationshipLabel>Staff</relationshipLabel>
        <relationshipName>Staff_Section</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Staff/Section</label>
    <nameField>
        <displayFormat>SfS-{000000}</displayFormat>
        <label>Staff/Section ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Staff/Section</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Student__c.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>true</defaultValue>
        <inlineHelpText>Indicates whether or not this Student record is active. If checked, then this is the current Student record. If unchecked, this is an old Student record.</inlineHelpText>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Archived__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Displays whether or not this Student record is archived. SchoolForce archives Student records in the Process Data Step of the EOY Wizard. You should never manually update this field.</inlineHelpText>
        <label>Archived</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Is_Active__c</fullName>
        <defaultValue>true</defaultValue>
        <inlineHelpText>Do not use this field; it is no longer used by SchoolForce.</inlineHelpText>
        <label>Is Active?*Retired*</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Section__c</fullName>
        <inlineHelpText>Displays the student&apos;s current homeroom name or room number. This field can be used for reporting purposes.</inlineHelpText>
        <label>Current Homeroom</label>
        <type>TextArea</type>
    </fields>
    <label>Student</label>
    <nameField>
        <label>Student Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Students</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Student_Section__c.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Archived__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Archived</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Section__c</fullName>
        <label>Section</label>
        <referenceTo>Section__c</referenceTo>
        <relationshipLabel>Student</relationshipLabel>
        <relationshipName>Student_Section</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Student/Section</label>
    <nameField>
        <displayFormat>SS-{000000}</displayFormat>
        <label>Student/Section ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Student/Section</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/Batch_DeactivateData.cls
global class Batch_DeactivateData implements Database.Batchable<sObject>, Database.Stateful{
	private final ID currentYearID = CYUtil.getCurrentYearID();
	public String query;
	public boolean continueAfter;
	public String processObject;
	Data_Load_Log__c log;
	Boolean hasHadErrors = false;

	//tracks errors back over batch. This allows later batches to be marked completed but have the overall process fail.
	public boolean hasHadErrorsBefore = false;

	//defines the order of processing for deactivation, each object is deactivated in turn, with it's own log
	public List<String> objectDeactivationOrder			{get;set;}
	//This holds the default queries for each object processed by the deaction process
	public Map<String, String> defaultObjectQueryMap	{get;set;}
	
	global Batch_DeactivateData(ID logID){
		populateDeactivationProcessData();
		this.continueAfter = true;
		this.query = defaultObjectQueryMap.get(objectDeactivationOrder[0]);
		this.processObject = objectDeactivationOrder[0];
		initLogs(logID);
	}

	global Batch_DeactivateData(ID logid, String processObject, boolean continueAfter){
		populateDeactivationProcessData();
		this.continueAfter = continueAfter;
		this.processObject = processObject;
		initLogs(logID);
	}
	
	global Database.QueryLocator start(Database.BatchableContext BC) {
		try{
			if(query == null){
			if(defaultObjectQueryMap.containsKey(processObject)) {
				query = defaultObjectQueryMap.get(processObject);
			} else {
				throw new CYUtil.InterventionsException('Unable to find query for provided object. Process aborted.');
			}
			}
			log.Batch_ID__c = BC.getJobId();
			log.Status__c = 'In Progress';
			updateLog();
			return Database.getQueryLocator(query);
		} catch(Exception e){
			handleException(e,'start');
			throw e;
		}
	}

   	global void execute(Database.BatchableContext BC, List<sObject> scope){
   		try{
   			for(sObject s:scope){
				try {
					if(s.get('Active__c') != null){
						s.put('Active__c',false);
					}
				}
				catch(Exception e) {
					
				}
				try {
					if(s.get('Archived__c') != null){
						s.put('Archived__c', true);
					}
				}
				catch(Exception e) {
					
				}
				try {
					if(s.get('Active__c') != null){
						s.put('Active__c', false);
					}
				}
				catch(Exception e) {
					
				}

				try{
					if(s.get('Is_Active__c') != null){
						s.put('Is_Active__c', false);
					}
				} catch(Exception e){}
				//If you need to work with addtional fields, add them here.
				//If you want that field to be processed on only one object type, getSObjectType() should work
			}
			Database.SaveResult[] results = DMLManager.updateAsUser(scope,false);
			processDMLResults(results);

			updateLog();
   		} catch(Exception e){
			handleException(e,'execute');
			throw e;
		}
		
	}
	
	global void finish(Database.BatchableContext BC) {
		try{
			if(continueAfter){
				startNextBatch();
			}

			if(!hasHadErrors){
				log.Status__c = 'Completed';
			} else {
				log.Status__c = 'Failed';
			}
			
			log.End_Time__c = system.now();
			updateLog();
		} catch(Exception e){
			handleException(e,'finish');
			throw e;
		}
		
	}

	private void initLogs(ID logID){
		//indicator area deactivation doesn't use logging, so we bypass
		if(logID == null){ 
			log = new Data_Load_Log__c();
			log.Failed_Records__c = 0;
			log.Total_Records__c = 0;
			log.Processed_Records__c = 0;
			return;
		}
		try{
			log = [select Batch_ID__c, Class_Name__c, End_Time__c, Failed_Records__c, Messages__c,
					Start_Time__c, Status__c, Total_Records__c, Type__c, Processed_Records__c
				from Data_Load_Log__c
				where ID =: logID];
			log.Failed_Records__c = 0;
			log.Messages__c ='';
			log.Start_Time__c = system.now();
			log.Total_Records__c = 0;
			log.Processed_Records__c = 0;
			log.Processed_Record_Type__c = processObject;
		}catch(System.QueryException e){
			throw new CyUtil.InterventionsException('Unable to find the provided log.');
		}
		updateLog();
	}

	private void updateLog(){
		if(log.id != null){
			if(log.Messages__c.length() > 32000){
				log.Messages__c = log.Messages__c.subString(0,31000);
			}
			try{
				DMLManager.updateAsUser(new Data_Load_Log__c[]{log});
			} catch(DMLManager.CRUDException e){
				throw new CyUtil.InterventionsException('User lacks permissions to update Data Load Logs.');
			} catch(DMLManager.FLSException e){
				throw new CyUtil.InterventionsException('User lacks permissions to update Data Load Logs.');
			} catch(System.DMLException e){
				throw new CYUtil.InterventionsException('Unexpected exception while updating runtime log.');
			}
		}
	}

	private void processDMLResults(Database.SaveResult[] results){
		for(Database.SaveResult r:results){
			if(!r.isSuccess()){
				log.Messages__c += 'DML Failed for '+r.getID()+': '+r.getErrors()[0].getMessage()+'\n';
				log.Failed_Records__c++;
			} else {
				log.Processed_Records__c++;
			}
			log.Total_Records__c++;
		}
	}

	private void startNextBatch(){
		String nextObject;
		Data_Load_Log__c newLog = new Data_Load_Log__c();

		for(Integer i=0;i<objectDeactivationOrder.size();i++){
			if(objectDeactivationOrder[i] == processObject){
				if(i != objectDeactivationOrder.size()-1){
					nextObject = objectDeactivationOrder[i+1];
				}
				else {
					continueAfter = false;
				}
			}
		}
		
		if(continueAfter) {
			if(nextObject != null && log.ID != null){		
				newLog.Type__c = 'Interventions Data Deactivation';
				newLog.Status__c = 'Pending';
				newLog.Failed_Records__c = 0;
				newLog.Total_Records__c = 0;
				newLog.Processed_Records__c = 0;
				newLog.Reporting_Period__c = currentYearID;
					
				try{
					DMLManager.insertAsUser(new List<Data_Load_Log__c>{newLog});
				} catch(DMLManager.CRUDException e){
					throw new CyUtil.InterventionsException('User lacks permissions to update Data Load Logs.');
				} catch(DMLManager.FLSException e){
					throw new CyUtil.InterventionsException('User lacks permissions to update Data Load Logs.');
				} catch(System.DMLException e){
					throw new CyUtil.InterventionsException('Failed to make new log for next batch.');
				}
			}
	
			Batch_DeactivateData batch = new Batch_DeactivateData(newLog.id,nextObject,continueAfter);
			batch.objectDeactivationOrder = objectDeactivationOrder;
			batch.defaultObjectQueryMap = defaultObjectQueryMap;
			batch.hasHadErrorsBefore = hasHadErrorsBefore;
			Database.executeBatch(batch);
		} else if(log.id != null && !hasHadErrorsBefore) {
			List<EOY_Progress__c> eoyProgress = [select id, Is_Complete__c from EOY_Progress__c where Module_Name__c='Interventions' and Year__c =: currentYearID limit 1];
			if(!eoyProgress.isEmpty()){
				eoyProgress[0].Is_Complete__c = true;
				try{
					update eoyProgress;
				} catch(System.DMLException e){
					throw new CYUtil.InterventionsException('Unable to update EOY Progress.');
				}
			}
		}
	}

	private void populateDeactivationProcessData(){
		objectDeactivationOrder = new List<String>{
			'Student_Section__c',
			'Staff_Section__c',
			'Section__c',
			'Indicator_Area_Student__c',
			'Account_Program__c'
		};

		//because we need to escape querried IDs apparently
		String escapedYear = String.escapeSingleQuotes(currentYearID);

		defaultObjectQueryMap = new Map<String,String>{
			'Student_Section__c'=>'select id, Active__c, Archived__c '+
												'from Student_Section__c '+
												'where Section__r.Time__c = \''+escapedYear+'\' '+
												'and Section__r.RecordType.Name=\'Intervention Section\' '+
												'and Archived__c = false',
			'Staff_Section__c'=>'select id, Is_Active__c, Archived__c '+
												'from Staff_Section__c '+
												'where Section__r.Time__c = \''+escapedYear+'\' '+
												'and Section__r.RecordType.Name=\'Intervention Section\' '+
												'and Archived__c = false',
			'Section__c'=>'select id, Active__c, Archived__c '+
										'from Section__c '+
										'where Time__c = \''+escapedYear+'\' '+
										'and RecordType.Name=\'Intervention Section\' '+
										'and Archived__c = false',
			'Indicator_Area_Student__c'=>'select id, Active__c '+
											'from Indicator_Area_Student__c '+
											'where Student__r.School_Year__c = \''+escapedYear+'\' '+
											'and Active__c = true',
			'Account_Program__c'=>'select id, Active__c '+
									'from Account_Program__c '+
									'where Current_Year_ID__c = \''+escapedYear+'\' '+
									'and Active__c = true'
		};
	}

	private void handleException(Exception e, String location){
		system.debug(e.getMessage()+e.getStackTraceString());
		log.Messages__c += 'Exception: '+e.getMessage()+e.getStackTraceString();
		updateLog();
		hasHadErrors = true;
		hasHadErrorsBefore = true;
		throw e;
	}	
}