objects/Account.object
<CustomObject>
    <fields>
        <fullName>Site__c</fullName>
        <label>Location</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Baton Rouge</fullName>
                </value>
                <value>
                    <fullName>Boston</fullName>
                </value>
                <value>
                    <fullName>Buffalo</fullName>
                </value>
                <value>
                    <fullName>Chicago</fullName>
                </value>
                <value>
                    <fullName>City Year</fullName>
                </value>
                <value>
                    <fullName>Cleveland</fullName>
                </value>
                <value>
                    <fullName>Columbia</fullName>
                </value>
                <value>
                    <fullName>Columbus</fullName>
                </value>
                <value>
                    <fullName>Dallas</fullName>
                </value>
                <value>
                    <fullName>Denver</fullName>
                </value>
                <value>
                    <fullName>Detroit</fullName>
                </value>
                <value>
                    <fullName>Jacksonville</fullName>
                </value>
                <value>
                    <fullName>Kansas City</fullName>
                </value>
                <value>
                    <fullName>Little Rock</fullName>
                </value>
                <value>
                    <fullName>Los Angeles</fullName>
                </value>
                <value>
                    <fullName>Memphis</fullName>
                </value>
                <value>
                    <fullName>Miami</fullName>
                </value>
                <value>
                    <fullName>Milwaukee</fullName>
                </value>
                <value>
                    <fullName>New Hampshire</fullName>
                </value>
                <value>
                    <fullName>New Orleans</fullName>
                </value>
                <value>
                    <fullName>New York City</fullName>
                </value>
                <value>
                    <fullName>Orlando</fullName>
                </value>
                <value>
                    <fullName>Philadelphia</fullName>
                </value>
                <value>
                    <fullName>Providence</fullName>
                </value>
                <value>
                    <fullName>Rhode Island</fullName>
                </value>
                <value>
                    <fullName>Sacramento</fullName>
                </value>
                <value>
                    <fullName>San Antonio</fullName>
                </value>
                <value>
                    <fullName>San Jose/Silicon Valley</fullName>
                </value>
                <value>
                    <fullName>Seattle/King County</fullName>
                </value>
                <value>
                    <fullName>Tulsa</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <recordTypes>
        <fullName>School</fullName>
        <active>true</active>
        <description>This record type is for physical school locations.</description>
        <label>School</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Account_Program__c.object
<CustomObject>
    <description>The Account/Program object is part of the Interventions App and links Programs and Schools/Accounts.  This linking occurs in the Interventions Setup when a school selects which interventions Programs they will enroll in for a specific year.  This object tracks the relationships of Programs and Schools and whether the Programs are active.</description>
    <fields>
        <fullName>Program__c</fullName>
        <inlineHelpText>This field joins the Account/Program record to the correct intervention Program</inlineHelpText>
        <label>Program</label>
        <referenceTo>Program__c</referenceTo>
        <relationshipLabel>School Programs</relationshipLabel>
        <relationshipName>Accounts_Programs</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Account/Program</label>
    <nameField>
        <label>School Program Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Accounts/Programs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Student__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>This field provides a link to the most recent Student record.</inlineHelpText>
        <label>Student</label>
        <referenceTo>Student__c</referenceTo>
        <relationshipLabel>Contacts</relationshipLabel>
        <relationshipName>Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <recordTypes>
        <fullName>Staff</fullName>
        <active>true</active>
        <description>This record type is for staff members.</description>
        <label>Staff</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Indicator_Area__c.object
<CustomObject>
    <description>This object is part of the Interventions app. Indicator Area defines a high-level intervention focus area (e.g., Behavior, Attendance, English Language Arts). Students are assigned to Indicator Areas in order to schedule them in Intervention Programs and Sections.</description>
    <label>Indicator Area</label>
    <nameField>
        <label>Indicator Area</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Indicator Areas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Program__c.object
<CustomObject>
    <description>Program is an Intervention object. Intervention Programs are aligned with Indicator Areas and are a high level set of activities with defined dosage goals. Each Program has its own frequency, target dosage, and recommended time per session. An example Program is one-on-one reading.</description>
    <fields>
        <fullName>Indicator_Area__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>You must select an Indicator Area that aligns with this Program.</inlineHelpText>
        <label>Indicator Area</label>
        <referenceTo>Indicator_Area__c</referenceTo>
        <relationshipLabel>Programs</relationshipLabel>
        <relationshipName>Programs</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Program</label>
    <nameField>
        <label>Program Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/Section__c.object
<CustomObject>
    <fields>
        <fullName>Account_Program__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>What intervention Program is this intervention Section associated to?</inlineHelpText>
        <label>School Program</label>
        <lookupFilter>
            <active>false</active>
            <filterItems>
                <field>Account_Program__c.Program__c</field>
                <operation>equals</operation>
                <valueField>$Source.Program__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account_Program__c</referenceTo>
        <relationshipLabel>Sections</relationshipLabel>
        <relationshipName>Sections</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Indicator_Area__c</fullName>
        <formula>Program__r.Indicator_Area__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>What Indicator Area is this Program addressing? This field cannot be modified here.</inlineHelpText>
        <label>Indicator Area</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Program__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>What intervention Program is this Intervention Section for?</inlineHelpText>
        <label>Program</label>
        <referenceTo>Program__c</referenceTo>
        <relationshipLabel>Sections</relationshipLabel>
        <relationshipName>Sections</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Section__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Recursive lookup for groups</description>
        <label>Section</label>
        <referenceTo>Section__c</referenceTo>
        <relationshipLabel>Groups in Section</relationshipLabel>
        <relationshipName>Sections1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Staff__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Staff</label>
        <referenceTo>Staff__c</referenceTo>
        <relationshipLabel>Sections</relationshipLabel>
        <relationshipName>Sections</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Section</label>
    <nameField>
        <label>Section Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sections</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Skill__c.object
<CustomObject>
    <fields>
        <fullName>Category__c</fullName>
        <label>Category</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Literacy</fullName>
                </value>
                <value>
                    <fullName>Math</fullName>
                </value>
                <value>
                    <fullName>SEL/Behavior and Attendance Interventions</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>IsPrimary__c</fullName>
        <defaultValue>false</defaultValue>
        <label>IsPrimary</label>
        <type>Checkbox</type>
    </fields>
    <label>Skill</label>
    <nameField>
        <label>Skill Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Skills</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Staff__c.object
<CustomObject>
    <fields>
        <fullName>Site__c</fullName>
        <formula>TEXT(Organization__r.Site__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Location</label>
        <type>Text</type>
    </fields>
    <label>Staff</label>
    <nameField>
        <label>Staff Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Staff</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/Student__c.object
<CustomObject>
    <fields>
        <fullName>Section__c</fullName>
        <inlineHelpText>Displays the student&apos;s current homeroom name or room number. This field can be used for reporting purposes.</inlineHelpText>
        <label>Current Homeroom</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Staff__c</fullName>
        <inlineHelpText>Displays the name of the student&apos;s homeroom teacher.  You can use this field for reporting purposes.</inlineHelpText>
        <label>Current Homeroom Teacher</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Student__c</fullName>
        <inlineHelpText>Displays the student&apos;s middle name.</inlineHelpText>
        <label>Student Middle Name</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <label>Student</label>
    <nameField>
        <label>Student Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Students</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/User.object
<CustomObject>
    <fields>
        <fullName>Site__c</fullName>
        <label>Location</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Baton Rouge</fullName>
                </value>
                <value>
                    <fullName>Boston</fullName>
                </value>
                <value>
                    <fullName>Buffalo</fullName>
                </value>
                <value>
                    <fullName>Chicago</fullName>
                </value>
                <value>
                    <fullName>Cleveland</fullName>
                </value>
                <value>
                    <fullName>Columbia</fullName>
                </value>
                <value>
                    <fullName>Columbus</fullName>
                </value>
                <value>
                    <fullName>Dallas</fullName>
                </value>
                <value>
                    <fullName>Denver</fullName>
                </value>
                <value>
                    <fullName>Detroit</fullName>
                </value>
                <value>
                    <fullName>Headquarters</fullName>
                </value>
                <value>
                    <fullName>Jacksonville</fullName>
                </value>
                <value>
                    <fullName>Kansas City</fullName>
                </value>
                <value>
                    <fullName>Little Rock</fullName>
                </value>
                <value>
                    <fullName>Los Angeles</fullName>
                </value>
                <value>
                    <fullName>Memphis</fullName>
                </value>
                <value>
                    <fullName>Miami</fullName>
                </value>
                <value>
                    <fullName>Milwaukee</fullName>
                </value>
                <value>
                    <fullName>New Hampshire</fullName>
                </value>
                <value>
                    <fullName>New Orleans</fullName>
                </value>
                <value>
                    <fullName>New York City</fullName>
                </value>
                <value>
                    <fullName>Orlando</fullName>
                </value>
                <value>
                    <fullName>Philadelphia</fullName>
                </value>
                <value>
                    <fullName>Providence</fullName>
                </value>
                <value>
                    <fullName>Sacramento</fullName>
                </value>
                <value>
                    <fullName>San Antonio</fullName>
                </value>
                <value>
                    <fullName>San Jose/Silicon Valley</fullName>
                </value>
                <value>
                    <fullName>Seattle/King County</fullName>
                </value>
                <value>
                    <fullName>Tulsa</fullName>
                </value>
                <value>
                    <fullName>Washington, D.C.</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

classes/Test_StudentDetailComponent.cls
@isTest
private class Test_StudentDetailComponent {
	
	private static Account school;
	private static Section__c section;
	private static List<Student__c> students;
	private static Skill__c skill;

	static testMethod void Test_Constructor() {
		setupData();
		
		Test.setCurrentPage(Page.IM_StudentDetail);
		ApexPages.currentPage().getParameters().put('StudentId',students[0].id);

		Test.startTest();
			StudentDetailComponent controller = new StudentDetailComponent();
			system.assertEquals(2, controller.sectionList.size());

			controller.selectedSectionId = controller.sectionList[1].getValue();
			controller.changeSection();
		Test.stopTest();
	}

	static testMethod void Test_ErrorConstructor() {
		setupData();

		Test.setCurrentPage(Page.IM_StudentDetail);

		Test.startTest();
			StudentDetailComponent controller = new StudentDetailComponent();
		Test.stopTest();

		system.assertEquals(true, controller != null);

	}

	static testMethod void Test_AddTime(){
		setupData();
		
		Test.setCurrentPage(Page.IM_StudentDetail);
		ApexPages.currentPage().getParameters().put('StudentId',students[0].id);

		Test.startTest();
			StudentDetailComponent controller = new StudentDetailComponent();
			
			controller.sessionHolder.Date__c = Date.today();
			controller.primarySkill = skill.id;
			//controller.sessionHolder.Skills_Covered_for_the_Session__c = 'Test Skills';
			controller.sessionHolder.All_avenues__c = 'In-Person Service';
			controller.selectedFields.add(new SelectOption('Self-Awareness: Identifying strengths and weaknesses','Self-Awareness: Identifying strengths and weaknesses'));
			controller.resultHolder.Amount_of_Time__c = 10;

			controller.saveTime();
			system.assertEquals(10, controller.selectedStudentSection.Dosage_to_Date__c);
		Test.stopTest();
	}

	static testMethod void Test_modalCancel(){
		setupData();

		Test.setCurrentPage(Page.IM_StudentDetail);
		ApexPages.currentPage().getParameters().put('StudentId',students[0].id);

		Test.startTest();
			StudentDetailComponent controller = new StudentDetailComponent();
			controller.modalCancel();
		Test.stopTest();

		system.assertEquals(true, controller.resultHolder != null);
		system.assertEquals(true, controller.sessionHolder != null);
	}



	static testMethod void Test_EditTime(){
		setupData();
		
		Test.setCurrentPage(Page.IM_StudentDetail);
		ApexPages.currentPage().getParameters().put('StudentId',students[0].id);

		Test.startTest();
			StudentDetailComponent setupController = new StudentDetailComponent();
			
			setupController.sessionHolder.Date__c = Date.today();
			setupController.sessionHolder.Skills_Covered_for_the_Session__c = 'Test Skills';
			setupController.primarySkill = skill.id;
			setupController.sessionHolder.Skill_Primary__c = skill.id;
			setupController.sessionHolder.All_avenues__c = 'In-Person Service';
			setupController.resultHolder.Amount_of_Time__c = 10;

			setupController.saveTime();

			StudentDetailComponent controller = new StudentDetailComponent();
			system.assertEquals(1, controller.sessions.size());

			controller.selectedSessionID = controller.sessions[0].session.ID;
			controller.editSession();

			controller.resultHolder.Amount_of_Time__c = 50;
			controller.saveTime();

			system.assertEquals(50, controller.selectedStudentSection.Dosage_to_Date__c);
		Test.stopTest();
	}
	
	static void setupData(){
		skill = new Skill__c();
		skill.Name = 'Self-Awareness: Identifying strengths and weaknesses';
		skill.Category__c = 'SEL/Behavior and Attendance Interventions';
		skill.IsPrimary__c = true;
		insert skill;
		TestDataUtil.setupSharingControls();
		TestDataUtil.setupTime();
		school = TestDataUtil.createSchool('ApexTestSchool1');
		school.Site__c = 'Boston';
		insert school;
		TestDataUtil.schoolList.add(school);
		TestDataUtil.setupSetupRecord();
		List<Indicator_Area__c> ia = TestDataUtil.createIndicatorAreas();
		insert ia;
		
		List<Program__c> programs = TestDataUtil.createPrograms(1,true,ia[0]);
		programs.addAll(TestDataUtil.createPrograms(1,true,ia[1]));
		programs.addAll(TestDataUtil.createPrograms(1,false,ia[2]));
		programs.addAll(TestDataUtil.createPrograms(1,false,ia[3]));
		insert programs;
		Account_Program__c accProg = TestDataUtil.createAccountProgram(school, programs[0]);
		insert accProg;
		//students = TestDataUtil.createStudents(1, school);
		//insert students;
		
		Contact c = TestDataUtil.createContact('ApexTest','User',null);
		insert c;
		Staff__c staff = TestDataUtil.createStaff(c,school,1);
		insert staff;
		
		students = TestDataUtil.createStudents(1, school);
		insert students;
		
		section = TestDataUtil.createSection(school, accProg, students, staff, programs[0]);
		TestDataUtil.createSection(school, accProg, students, staff, programs[0]);
	}
}