objects/Account.object
<CustomObject>
    <recordTypes>
        <fullName>School</fullName>
        <active>true</active>
        <description>This record type is for physical school locations.</description>
        <label>School</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Indicator_Area__c.object
<CustomObject>
    <description>This object is part of the Interventions app. Indicator Area defines a high-level intervention focus area (e.g., Behavior, Attendance, English Language Arts). Students are assigned to Indicator Areas in order to schedule them in Intervention Programs and Sections.</description>
    <label>Indicator Area</label>
    <nameField>
        <label>Indicator Area</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Indicator Areas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Picklist_Value__c.object
<CustomObject>
    <fields>
        <fullName>Indicator_Area__c</fullName>
        <label>Indicator Area</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Indicator_Area_Types</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Setup__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Setup</label>
        <referenceTo>Setup__c</referenceTo>
        <relationshipLabel>Picklist Values</relationshipLabel>
        <relationshipName>Picklist_Values</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Picklist Value</label>
    <nameField>
        <label>Display Value</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Picklist Values</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Setup__c.object
<CustomObject>
    <description>This object is used to setup Schoolforce and is referenced in multiple pieces of code.  There should be one setup object per school.</description>
    <fields>
        <fullName>School__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>School</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1 OR 2</booleanFilter>
            <filterItems>
                <field>Account.RecordType.Name</field>
                <operation>equals</operation>
                <value>School</value>
            </filterItems>
            <filterItems>
                <field>Account.RecordType.Name</field>
                <operation>equals</operation>
                <value>Summer School</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Setup</relationshipLabel>
        <relationshipName>Setup</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Year__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>School Year associated to the Setup</description>
        <label>Year</label>
        <referenceTo>Time_Element__c</referenceTo>
        <relationshipLabel>Setup (Year)</relationshipLabel>
        <relationshipName>Setup_Year</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Setup</label>
    <nameField>
        <displayFormat>S-{0}</displayFormat>
        <label>Setup ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Setup</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/Time_Element__c.object
<CustomObject>
    <fields>
        <fullName>Date_Start_Date__c</fullName>
        <defaultValue>Today()</defaultValue>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Name__c</fullName>
        <label>Name</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Picklist_Value__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Picklist Value</label>
        <referenceTo>Picklist_Value__c</referenceTo>
        <relationshipLabel>Time</relationshipLabel>
        <relationshipName>Time</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>School__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>School</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Time</relationshipLabel>
        <relationshipName>Time</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Time</label>
    <nameField>
        <displayFormat>T-{000000}</displayFormat>
        <label>Time Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Time</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/User.object
<CustomObject>
    <fields>
        <fullName>School__c</fullName>
        <label>School</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

globalValueSets/Indicator_Area_Types.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Attendance</fullName>
    </customValue>
    <customValue>
        <fullName>Behavior</fullName>
        <label>SEL/SED</label>
    </customValue>
    <customValue>
        <fullName>ELA/Literacy</fullName>
    </customValue>
    <customValue>
        <fullName>Math</fullName>
    </customValue>
    <customValue>
        <fullName>Non-specific IA</fullName>
        <isActive>false</isActive>
        <label>Non-specific IA</label>
    </customValue>
    <masterLabel>Indicator Area Types</masterLabel>
</GlobalValueSet>

classes/InterventionsSetup.cls
public with sharing class InterventionsSetup {
	public String iaPrefix;
	public List<SelectOption> schools	{get;set;}
	public String selectedSchool		{get;set;}
	
	public List<SelectOption> years		{get;set;}
	public String selectedYear			{get;set;}
	
	public String getiaPrefix(){
		return Indicator_Area__c.SObjectType.getDescribe().getKeyPrefix();
	}
	
	public InterventionsSetup(){
		List<Account> schoolList = [select id, name from Account where recordType.name = 'School' order by Name];
		List<Time_Element__c> yearsList = [SELECT Name__c, Id FROM Time_Element__c WHERE Picklist_Value__r.Name = 'Year' ORDER BY Date_Start_Date__c DESC];
		schools = new List<SelectOption>();
		years = new List<SelectOption>();
		if(schoolList.size()>0 && yearsList.size()>0){
			for(Account a: schoolList){
				schools.add(new SelectOption(a.id,a.Name));
			}
			for(Time_Element__c te: yearsList){
				years.add(new SelectOption(te.id,te.Name__c));
			}
		}
	}
	
	public PageReference goToStaffStudentLoad(){
		boolean bError = false;
		if(selectedSchool==null || selectedSchool==''){
			ApexPages.addMessage(new apexpages.message(apexpages.severity.ERROR,'Please select a school to set up.'));
			bError = true;
		}
		if(selectedYear==null || selectedYear==''){
			ApexPages.addMessage(new apexpages.message(apexpages.severity.ERROR,'Please select a year for which the setup will be valid.'));
			bError = true;
		}
		if(!bError){
			List<Setup__c> setupList = [SELECT id FROM Setup__c WHERE School__c=:selectedSchool AND Year__c=:selectedYear];
			Setup__c schoolSetup;
			if(setupList.size()==0){
				schoolSetup = new Setup__c(School__c=selectedSchool, Year__c=selectedYear);
				try{
					DMLManager.insertAsUser(new Setup__c[]{schoolSetup});
				} catch(DMLManager.CRUDException e){
					CyUtil.errorMessage('User lacks permissions to create setup records.');
				} catch(DMLManager.FLSException e){
					CyUtil.errorMessage('User lacks permissions to key fields on Setup.');
				} catch(System.DMLException e){
					CyUtil.errorMessage('Unexpected exception while creating setup.');
				}
			} else if(setupList.size()==1){
				schoolSetup = setupList[0];
			} else{
				//DE3540
				//more than 1 setup, throw error
				String schoolName='';
				String yearName='';
				for(SelectOption so: schools){
					if(so.getValue()==selectedSchool) schoolName = so.getLabel();
				}
				for(SelectOption so: years){
					if(so.getValue()==selectedYear) yearName = so.getLabel();
				}
				ApexPages.addMessage(new apexpages.message(apexpages.severity.ERROR,'There are multiple setup objects for '+schoolName+' for the year '+yearName+'.  You may only have 1 setup record.  Please go to the Setup Object to delete any unwanted setups and try again.'));
				return null;
			}
			PageReference pr = Page.SchoolSetup_Staff;
			pr.getParameters().put('setupId',schoolSetup.id);
			pr.setRedirect(true);
			return pr;
		}
		else{
			return null;
		}
	}
}