objects/Account.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <label>Active</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>No</fullName>
                </value>
                <value>
                    <fullName>Yes</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Is_Active__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Is Active?</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Course__c.object
<CustomObject>
    <fields>
        <fullName>Subject_Area_Lookup__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Select the applicable subject area for this course. You can use the subject area for reporting purposes as well as for cohort requirements.</inlineHelpText>
        <label>Subject Area Lookup</label>
        <referenceTo>Course__c</referenceTo>
        <relationshipLabel>Courses (Subject Area Lookup)</relationshipLabel>
        <relationshipName>Course</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Course</label>
    <nameField>
        <label>Course Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Courses</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/Section__c.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Check this box if the section is a currently active section</description>
        <inlineHelpText>Check this box if the section is a currently active section</inlineHelpText>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Course__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Select the course associated to the section you want to create.</inlineHelpText>
        <label>Course</label>
        <referenceTo>Course__c</referenceTo>
        <relationshipLabel>Sections</relationshipLabel>
        <relationshipName>Sections</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>School__c</fullName>
        <label>School</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Sections</relationshipLabel>
        <relationshipName>Sections</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Section__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Recursive lookup for groups</description>
        <label>Section</label>
        <referenceTo>Section__c</referenceTo>
        <relationshipLabel>Groups in Section</relationshipLabel>
        <relationshipName>Sections1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Staff__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Staff</label>
        <referenceTo>Staff__c</referenceTo>
        <relationshipLabel>Sections</relationshipLabel>
        <relationshipName>Sections</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Section</label>
    <nameField>
        <label>Section Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sections</pluralLabel>
    <recordTypes>
        <fullName>Published</fullName>
        <active>true</active>
        <description>Sections that have been Published and are Viewable by Standard Users</description>
        <label>Published</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Staff__c.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Is_Active__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Active?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Organization__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Staff Member&apos;s employer</description>
        <label>Organization</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Staff</relationshipLabel>
        <relationshipName>Staff</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Staff_Last_Name__c</fullName>
        <label>Staff Last Name</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <label>Staff</label>
    <nameField>
        <label>Staff Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Staff</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/Staff_Section__c.object
<CustomObject>
    <fields>
        <fullName>Is_Active__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Is Active?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>School__c</fullName>
        <formula>Section__r.School__r.Id</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>The School related to this Section</inlineHelpText>
        <label>School</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Section__c</fullName>
        <label>Section</label>
        <referenceTo>Section__c</referenceTo>
        <relationshipLabel>Staff</relationshipLabel>
        <relationshipName>Staff_Section</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Staff__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Staff</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Staff__c.Organization__r.Id</field>
                <operation>equals</operation>
                <valueField>$Source.Account__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Staff__c</referenceTo>
        <relationshipLabel>Sections</relationshipLabel>
        <relationshipName>Staff_Section</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Staff/Section</label>
    <nameField>
        <displayFormat>SfS-{000000}</displayFormat>
        <label>Staff/Section ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Staff/Section</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/Gradebook_AddStaff.cls
public with sharing class Gradebook_AddStaff {

	public List<SelectWrapper> options1 	{get;set;}
	public List<SelectWrapper> options2 	{get;set;}

	public Gradebook_AddStaff(){
		options1 = new List<SelectWrapper>();//staff
		options2 = new List<SelectWrapper>();//sections
		for(Staff__c s : [Select ID, Organization__c, Organization__r.name, Name from Staff__c order by Organization__r.Name, Staff_Last_Name__c]){
			SelectWrapper isw = new SelectWrapper();
			isw.name=s.Name;
			isw.selected = false;
			isw.data1 = s.Organization__r.name;
			isw.data2 = s.Organization__c;
			isw.id = s.id;
			options1.add(isw);	
		}
		
		options2 = new List<SelectWrapper>();//staff list
		for(Section__c s : [Select ID, Name, School__c, Course__r.Name, School__r.Name from Section__c where Active__c = true and (RecordType.DeveloperName='Published' or RecordType.DeveloperName='Scheduled_Group') order by School__r.Name, Course__r.Name]){
			SelectWrapper isw = new SelectWrapper();
			string temp;
			if(s.School__c ==null)temp='';
			else temp=s.School__r.Name;
			isw.data1 = s.School__r.Name;				
			isw.name=s.Name;
			isw.selected = false;
			isw.id = s.id;
			options2.add(isw);
		}
	}

	public void addStaff(){
		list<Staff_Section__c> toInsert = new List<Staff_Section__c>();
		set<string> existingStaffSections = new set<String>();
		set<id> sectionsToAdd = new Set<ID>();
		set<ID> staffToAdd	  = new Set<ID>();
		boolean atLeastOneSelected = false;
		for(SelectWrapper sw : options1){
			if(sw.selected){
				staffToAdd.add(sw.id);
				sw.selected = false;
			}
		}
		for(SelectWrapper sw: options2){
			if(sw.selected){
				sectionsToAdd.add(sw.id);
				sw.selected = false;
			}
		}
		//check the existing staff sections
		for(Staff_Section__c ss : [Select ID, Staff__c, Section__c from Staff_Section__c where Staff__c IN : staffToAdd AND Section__c IN: sectionsToAdd]){
			existingStaffSections.add(string.valueOf(ss.Staff__c) + string.valueOf(ss.Section__c));
		}
		for(string staff : staffToAdd){
			for(String section : sectionsToAdd){
				if(!existingStaffSections.contains(staff+section)){
					//no dupes plz
					toInsert.add(new Staff_Section__c(Is_Active__c = true, Staff__c = staff, Section__c=section));
				}
			}
		}
		system.debug(toInsert);
		insert toInsert;
		
	}
		
		public class SelectWrapper{
		public string selectAllClass			{get;set;}//jquery class helper for select all functionality
		public string id						{get;set;}//id for the data
		public boolean selected					{get;set;}//checkbox for selecting
		public boolean flag						{get;set;}
		public string data1						{get;set;}
		public string data2						{get;set;}
		public string data3						{get;set;}
		public string data4						{get;set;}
		public List<List<String>> tableData		{get;set;}//dynamic list of strings for columns
		public string Name						{get;set;}
		
		public SelectWrapper(){
			selected = false;
			tableData = new List<List<String>>();//dynamic list of strings for columns
		}
	}
	
	static testMethod void testAddStaff(){
		 testDataSetupUtil_v2.setUpCoreData(5);
         testDataSetupUtil_v2.setUpStaffData(5);
         testDataSetupUtil_v2.setUpStudentData(5);
        
        Test.startTest();
        Gradebook_AddStaff controller = new Gradebook_AddStaff();
        for(selectWrapper sw : controller.options1){
        	sw.selected = true;
        }
        for(selectWrapper sw : controller.options2){
        	sw.selected = true;
        }
        controller.addStaff();
	}
}