objects/Account.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <label>Active</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>No</fullName>
                </value>
                <value>
                    <fullName>Yes</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <recordTypes>
        <fullName>School</fullName>
        <active>true</active>
        <description>This record type is for physical school locations.</description>
        <label>School</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Indicator_Area__c.object
<CustomObject>
    <description>This object is part of the Interventions app. Indicator Area defines a high-level intervention focus area (e.g., Behavior, Attendance, English Language Arts). Students are assigned to Indicator Areas in order to schedule them in Intervention Programs and Sections.</description>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>true</defaultValue>
        <inlineHelpText>Indicates whether or not this indicator area is available to assign to students on the Add Students to Indicator Areas screen. If you uncheck this field, SchoolForce deactivates any associated Program, Staff/Section, and Student/Section records.</inlineHelpText>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <label>Indicator Area</label>
    <nameField>
        <label>Indicator Area</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Indicator Areas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Program__c.object
<CustomObject>
    <description>Program is an Intervention object. Intervention Programs are aligned with Indicator Areas and are a high level set of activities with defined dosage goals. Each Program has its own frequency, target dosage, and recommended time per session. An example Program is one-on-one reading.</description>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>If this box is checked then the Program is currently available for use.</inlineHelpText>
        <label>Active?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Indicator_Area__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>You must select an Indicator Area that aligns with this Program.</inlineHelpText>
        <label>Indicator Area</label>
        <referenceTo>Indicator_Area__c</referenceTo>
        <relationshipLabel>Programs</relationshipLabel>
        <relationshipName>Programs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Required_Program__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Is this Program required for your school or organization? Administrators can select whether Programs should be required or not. If yes, then each school will automatically be associated with this Program. Schools can opt of required Programs.</inlineHelpText>
        <label>Required Program</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <inlineHelpText>This field is automatically updated based on whether your organization has setup approval processes for Programs.</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Pending</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Program</label>
    <nameField>
        <label>Program Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

classes/TestSchoolProgramController.cls
@isTest
private class TestSchoolProgramController {
/*
	static testMethod void myUnitTest() {
		TestDataUtil.setupData(2);
		User sysAdmin = TestDataUtil.testData[0].sysAdmin.userRecord;
		Account school_1 = TestDataUtil.testData[0].school;
		Account school_2 = TestDataUtil.testData[1].school;
		Indicator_Area__c ia = new Indicator_Area__c(Name = 'IA');	
		insert ia;
		List<Program__c> programs = new List<Program__c>();
		programs.add(new Program__c(Name = 'Program', Required_Program__c =true, Status__c = 'Approved',Indicator_Area__c = ia.Id, Active__c=true));
		programs.add(new Program__c(Name = 'Not Required Program', Required_Program__c =false, Status__c = 'Approved',Indicator_Area__c = ia.Id, Active__c=true));
		insert programs;
		test.startTest();
		system.runAs(TestDataUtil.testData[0].sysAdmin.userRecord) {
			SchoolProgramController cont = new SchoolProgramController();
			cont.selectedSchool = school_1.id;
			cont.getIAList();
			cont.selectSchool();
			system.assert(cont.getHasChanges());
			cont.readyExclusionReasons();
			cont.updateSchool();
		}
		test.stopTest();
	}

	static testMethod void testProgramCreation(){
		TestDataUtil.setupData(2);
		User sysAdmin = TestDataUtil.testData[0].sysAdmin.userRecord;
		Account school_1 = TestDataUtil.testData[0].school;
		Account school_2 = TestDataUtil.testData[1].school;
		Indicator_Area__c ia = new Indicator_Area__c(Name = 'IA');	
		insert ia;

		system.runAs(TestDataUtil.testData[0].sysAdmin.userRecord) {
			Test.startTest();
				SchoolProgramController controller = new SchoolProgramController();
				//this would be called from the page on load
				controller.getAreaOptions();

				controller.createProgram();
				system.assert(controller.bProgram, 'Expected bProgram to be true.');
				controller.newProgram.Name = 'Program';
				controller.newProgram.Required_Program__c = true;
				controller.newProgram.Status__c = 'Approved';
				controller.newProgram.Indicator_Area__c = ia.Id;
				system.assert(controller.newProgram.Active__c, 'Expected the new program to be active');

				controller.saveProgram();
				system.assertNotEquals(null, controller.newProgram.ID, 'If the program saved, it should have an ID.');
				system.assertEquals(1, [select id from Program__c where ID=:controller.newProgram.ID].size(),'We should have been able to find the program in the database.');

				controller.createProgram();
				controller.cancelProgram();
				system.assertEquals(false, controller.bProgram,'bProgram should be false after we cancel.');
			Test.stopTest();
		}
	}

	static testMethod void testAccountProgramCreation(){
		TestDataUtil.setupData(2);
		User sysAdmin = TestDataUtil.testData[0].sysAdmin.userRecord;
		Account school_1 = TestDataUtil.testData[0].school;
		Account school_2 = TestDataUtil.testData[1].school;
		Indicator_Area__c ia = new Indicator_Area__c(Name = 'IA');	
		insert ia;
		List<Program__c> programs = new List<Program__c>();
		programs.add(new Program__c(Name = 'Program', Required_Program__c =true, Status__c = 'Approved',Indicator_Area__c = ia.Id, Active__c=true));
		programs.add(new Program__c(Name = 'Not Required Program', Required_Program__c =false, Status__c = 'Approved',Indicator_Area__c = ia.Id, Active__c=true));
		insert programs;

		system.runAs(TestDataUtil.testData[0].sysAdmin.userRecord) {
			Test.startTest();
				SchoolProgramController controller = new SchoolProgramController();
				controller.getAreaOptions();

				controller.selectedSchool = TestDataUtil.testData[0].school.ID;
				controller.selectSchool();

				system.assertEquals(1, controller.requiredProgramsDisplay.size(),'Expected there to be at least one required program.');
				controller.requiredProgramsDisplay[0].checked = false;
				controller.requiredProgramsDisplay[0].exclusionReason = 'You can\'t make me';
				controller.updateSchool();
				controller.validateReasons();
				controller.readyExclusionReasons();

				controller.saveChanges();
			Test.stopTest();
		}
	}
	*/
}