objects/Account.object
<CustomObject>
    <fields>
        <fullName>Holding_Source__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Holding Source</label>
        <referenceTo>HoldingObj__c</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Reference_Id__c</fullName>
        <externalId>true</externalId>
        <label>Reference Id</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <recordTypes>
        <fullName>School</fullName>
        <active>true</active>
        <description>This record type is for physical school locations.</description>
        <label>School</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Disability_Flag__c</fullName>
        <inlineHelpText>This field is automatically updated if the Disability Flag field on the Student record is updated.</inlineHelpText>
        <label>Disability Flag</label>
        <length>1</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ELL__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Check this field if the student is an English Language Learner. This field is automatically populated if the field is included in the initial CSV Loader load of the student.</inlineHelpText>
        <label>ELL</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Holding_Source__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Do not modify this field; it is used for internal purposes only.</inlineHelpText>
        <label>Holding Source</label>
        <referenceTo>HoldingObj__c</referenceTo>
        <relationshipLabel>Contacts</relationshipLabel>
        <relationshipName>Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Reference_Id__c</fullName>
        <description>To store Student/Parent Id as External Id</description>
        <externalId>true</externalId>
        <inlineHelpText>Displays the unique reference ID for the student.  This value should be the same as the Student Id on the associated Student record(s).</inlineHelpText>
        <label>Reference Id</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Staff_Code__c</fullName>
        <inlineHelpText>This field is currently not being used in SchoolForce.</inlineHelpText>
        <label>Staff Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Student_Id__c</fullName>
        <formula>Student__r.Id</formula>
        <inlineHelpText>Displays the 15-digit Salesforce ID of the Student record associated with this contact.</inlineHelpText>
        <label>Student Id</label>
        <type>Text</type>
    </fields>
    <recordTypes>
        <fullName>Staff</fullName>
        <active>true</active>
        <description>This record type is for staff members.</description>
        <label>Staff</label>
    </recordTypes>
    <recordTypes>
        <fullName>Student</fullName>
        <active>true</active>
        <description>This record type is for students</description>
        <label>Student</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/HoldingObj__c.object
<CustomObject>
    <description>Generic holding object for importing Students/Staff records from a .CSV file.</description>
    <fields>
        <fullName>Class_Id__c</fullName>
        <label>Section Name</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Course_Name__c</fullName>
        <description>Type of Course for the Class</description>
        <label>Course Name</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Disability_Flag__c</fullName>
        <inlineHelpText>Y/N</inlineHelpText>
        <label>Disability Flag</label>
        <length>1</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ELL__c</fullName>
        <label>ELL</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>First_Name__c</fullName>
        <label>First Name</label>
        <length>24</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Last_Name__c</fullName>
        <label>Last Name</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Reference_Id__c</fullName>
        <description>Unique key for Holding Record</description>
        <externalId>true</externalId>
        <label>Reference Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Reporting_Period_Id__c</fullName>
        <description>Id for the Reporting Period; needs to be written from Scheduler and then picked up in the publish process.</description>
        <label>Reporting Period Id</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>School_Dbn__c</fullName>
        <label>School Dbn</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>School_Year__c</fullName>
        <label>School Year</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sex__c</fullName>
        <label>Gender</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Staff_Code__c</fullName>
        <label>Staff Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Student_Id__c</fullName>
        <label>Student Id</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <description>Student or Staff</description>
        <label>Type</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>HoldingObj</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>HoldingObjs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Section__c.object
<CustomObject>
    <fields>
        <fullName>Holding_Source__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Holding Source</label>
        <referenceTo>HoldingObj__c</referenceTo>
        <relationshipLabel>Sections</relationshipLabel>
        <relationshipName>Sections</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Reference_Id__c</fullName>
        <externalId>true</externalId>
        <label>Reference Id</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <description>Section or Standard Group or Custom Group</description>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Section</fullName>
                </value>
                <value>
                    <fullName>Standard Group</fullName>
                </value>
                <value>
                    <fullName>Custom Group</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Section</label>
    <nameField>
        <label>Section Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sections</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Staff__c.object
<CustomObject>
    <fields>
        <fullName>Holding_Source__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Holding Source</label>
        <referenceTo>HoldingObj__c</referenceTo>
        <relationshipLabel>Staff</relationshipLabel>
        <relationshipName>Staff</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Reference_Id__c</fullName>
        <externalId>true</externalId>
        <label>Reference Id</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Role__c</fullName>
        <label>Role</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Staff_Code__c</fullName>
        <label>Staff Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Staff</label>
    <nameField>
        <label>Staff Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Staff</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/Student__c.object
<CustomObject>
    <fields>
        <fullName>Class_ID__c</fullName>
        <description>This is only for internal use.</description>
        <inlineHelpText>This field is used by SchoolForce&apos;s CSV Loader.</inlineHelpText>
        <label>Class ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Disability_Flag__c</fullName>
        <inlineHelpText>Indicates whether or not the student has a disability.</inlineHelpText>
        <label>Disability Flag</label>
        <length>1</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ELL__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Indicates whether or not the student is an English language learner (ELL).</inlineHelpText>
        <label>ELL</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Holding_Source__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Do not modify this field; it is used for internal purposes only.</inlineHelpText>
        <label>Holding Source</label>
        <referenceTo>HoldingObj__c</referenceTo>
        <relationshipLabel>Students</relationshipLabel>
        <relationshipName>Students</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Reference_Id__c</fullName>
        <externalId>true</externalId>
        <inlineHelpText>Displays the Salesforce ID for this Student record. Do not modify this field.</inlineHelpText>
        <label>Reference Id</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>School_Year__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Displays the Time record for the school year. You can view the name of this Time record in the School Year Name field.</inlineHelpText>
        <label>School Year</label>
        <referenceTo>Time_Element__c</referenceTo>
        <relationshipLabel>Students</relationshipLabel>
        <relationshipName>Students1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Student_Id__c</fullName>
        <inlineHelpText>Displays the student&apos;s ID. This field displays on report cards, progress reports, and transcripts. It must be unique; SchoolForce uses this ID to link the Student record with the correct Contact record.</inlineHelpText>
        <label>Student Id</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>Student</label>
    <nameField>
        <label>Student Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Students</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Student_Section__c.object
<CustomObject>
    <fields>
        <fullName>Holding_Source__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Holding Source</label>
        <referenceTo>HoldingObj__c</referenceTo>
        <relationshipLabel>Student/Section</relationshipLabel>
        <relationshipName>Student_Section</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Reference_ID__c</fullName>
        <description>Concatenated unique id = StudentReference_ID__c + Reference Legacy_ID__c</description>
        <externalId>true</externalId>
        <label>Reference ID</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Student_Id__c</fullName>
        <formula>Student__r.Student_Id__c</formula>
        <label>Student Id</label>
        <type>Text</type>
    </fields>
    <label>Student/Section</label>
    <nameField>
        <displayFormat>SS-{000000}</displayFormat>
        <label>Student/Section ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Student/Section</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Time_Element__c.object
<CustomObject>
    <fields>
        <fullName>Reference_Id__c</fullName>
        <externalId>true</externalId>
        <label>Reference Id</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Year</fullName>
                </value>
                <value>
                    <fullName>Semester</fullName>
                </value>
                <value>
                    <fullName>Trimester</fullName>
                </value>
                <value>
                    <fullName>Quarter</fullName>
                </value>
                <value>
                    <fullName>Period</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Time</label>
    <nameField>
        <displayFormat>T-{000000}</displayFormat>
        <label>Time Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Time</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/User.object
<CustomObject>
    <fields>
        <fullName>Reference_Id__c</fullName>
        <externalId>true</externalId>
        <label>Reference Id</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

classes/Test_DataPropagator.cls
@isTest
public with sharing class Test_DataPropagator {

	private static List<HoldingObj__c> batch;
	
	testMethod static void testExecute() {
		   testDataSetupUtil_v2.setUPCoreData(5);
		setUp(testDataSetupUtil_v2.semester.Id);
		setUp2();
		Test.StartTest();
		Scheduler_HoldingProcessor target = new Scheduler_HoldingProcessor();
		target.mode = 'Staff';
		target.cSetup = new core_SetupWrapper(TestDataSetupUtil_v2.activeSetup,''); 
		    		string staffquery = Scheduler_HoldingProcessor.processQueryForPropagator(target.mode, null, 'TESTSCHL1');
		List <HoldingObj__c> staffList = database.Query(staffquery);
		target.log.Total_Records__c = 0;
		target.log.Failed_Records__c = 0; 
		target.execute(null, staffList);
		
		Scheduler_HoldingProcessor shp = new Scheduler_HoldingProcessor();
    		shp.mode = 'Student'; //Set the mode to student so it kicks off specific student processing
    		shp.cSetup = new core_SetupWrapper(TestDataSetupUtil_v2.activeSetup,''); 
    		string query = Scheduler_HoldingProcessor.processQueryForPropagator(shp.mode, null, 'TESTSCHL1');
		List <HoldingObj__c> hoList = database.Query(query);
		
		shp.log.Total_Records__c = 0;
		shp.log.Failed_Records__c=0;
		shp.execute(null, hoList);
		Test.stopTest();				
	}

	private static void setUp(Id rpid) {
		system.debug('$$$$RPID$$$'+rpId);
	
		
		batch = new List<HoldingObj__c>();
		HoldingObj__c hos = new HoldingObj__c();
		hos.Type__c='Student';
		hos.Student_ID__c = 'BATCH-TEST-1';
		hos.First_Name__c = 'Jon';
		hos.Last_Name__c = 'Doe';
		hos.Sex__c = 'M';
		hos.School_Dbn__c = 'TESTSCHL1';
		hos.Class_Id__c = 'CLS-1';
		hos.Course_Name__c = 'Course';
		hos.Reporting_Period_Id__c = rpid;
		hos.School_Year__c ='123456';
		hos.Reference_Id__c=ImportUtils.createClassSectionKey(hos);
		batch.add(hos);
		
		hos = new HoldingObj__c();
		hos.Type__c='Student';
		hos.Student_ID__c = 'BATCH-TEST-2';
		hos.First_Name__c = 'Amy';
		hos.Last_Name__c = 'Smith';
		hos.Sex__c = 'F';
		hos.School_Dbn__c = 'TESTSCHL1';
		hos.Class_Id__c = 'CLS-1';
		hos.ELL__c = 'y';
		hos.Course_Name__c = 'Course';
		hos.Reporting_Period_Id__c = rpid;
				hos.School_Year__c ='123456';
		hos.Reference_Id__c=ImportUtils.createClassSectionKey(hos);
		batch.add(hos);
		
		hos = new HoldingObj__c();
		hos.Type__c='Student';
		hos.Student_ID__c = 'BATCH-TEST-3';
		hos.First_Name__c = 'John';
		hos.Last_Name__c = 'Adams';
		hos.Sex__c = 'M';
		hos.School_Dbn__c = 'TESTSCHL1';
		hos.Class_Id__c = 'CLS-1';
		hos.Disability_Flag__c = 'y';
		hos.Course_Name__c = 'Course';  
		hos.Reporting_Period_Id__c = rpid;
				hos.School_Year__c ='123456';
		hos.Reference_Id__c=ImportUtils.createClassSectionKey(hos);
		batch.add(hos);
		
		insert batch;
	}
	

	
	testMethod static void testExecute2() {
		setUp2();
		
		Test.startTest();	
		Scheduler_HoldingProcessor target = new Scheduler_HoldingProcessor();
		target.mode = 'Staff';
		target.log.Total_Records__c = 0;
		target.log.Failed_Records__c = 0;
		target.execute(null, batch);
		Test.stopTest();
		
		Account school = [SELECT Id FROM Account WHERE Reference_Id__c = :batch[0].School_DBN__c];
		//Role__c role = [SELECT Id FROM Role__c WHERE Role_Name__c = :batch[0].Staff_Code__c];
		
		Contact staff = [SELECT LastName, FirstName, Holding_Source__c, User__c, User__r.LastName FROM Contact WHERE Reference_Id__c = :batch[0].Staff_ID__c];
		System.assertEquals(batch[0].Id, staff.Holding_Source__c);
		System.assert(staff.User__c != null);
		//System.assertEquals(batch[0].Last_Name__c, staff.User__r.LastName);
		
		//System.assertEquals(1, [SELECT count() FROM Staff_School__c WHERE School__c = :school.Id AND Role__c = :role.Id AND Staff__c = :staff.Id]);
	}
	
	testMethod static void testFinish2() {
		/* Tests deactivation of Staff*/
		setUp2();
		
		Contact staff = new Contact(LastName='Doe',Is_Active__c=true,FirstName='John',User_Name__c='testdoe');
		User usr = createUser(staff);
		insert usr;
		staff.User__c = usr.Id;
		insert staff;
		
				
		Scheduler_HoldingProcessor target = new Scheduler_HoldingProcessor();
		target.mode = 'Staff';
		target.finish(null);
		usr = [SELECT IsActive FROM User WHERE Id = :usr.Id];
		System.assert(!staff.Active__c);
	}
	
	private static void setUp2() {
		batch = new List<HoldingObj__c>();

		
		HoldingObj__c hos = new HoldingObj__c(School_DBN__c='TST123');
		hos.Type__c='Staff';
		hos.First_Name__c = 'John';
		hos.Last_Name__c = 'Smith';
		hos.Staff_ID__c='TST123';
		hos.Staff_Code__c = 'TST Teacher';
		hos.Class_Id__c = 'TST999';
		hos.CLass_Name__c = 'Class 999';
		hos.Network__c = 'TST-NET';
		hos.Username__c = 'TST1';
				hos.School_Dbn__c = 'TESTSCHL1';
		hos.Course_Name__c = 'Course1';
		hos.Reference_Id__c=ImportUtils.createClassSectionKey(hos);
		batch.add(hos);
		
		hos = new HoldingObj__c(School_DBN__c='TST123');
		hos.Type__c='Staff';
		hos.First_Name__c = 'Anne';
		hos.Last_Name__c = 'Porter';
		hos.Staff_ID__c='0TST123';
		hos.Staff_Code__c = 'TST Administrator';
		hos.Class_Id__c = 'TST878';
		hos.CLass_Name__c = 'Class 878';
		hos.Network__c = 'TST-NET';
		hos.Username__c = 'TST2';
				hos.School_Dbn__c = 'TESTSCHL1';
		hos.Course_Name__c = 'Course1';
		hos.Reference_Id__c=ImportUtils.createClassSectionKey(hos);
		batch.add(hos);
		
		hos = new HoldingObj__c(School_DBN__c='TST123');
		hos.Type__c='Staff';
		hos.First_Name__c = 'Mary';
		hos.Last_Name__c = 'Jane';
		hos.Staff_ID__c='0TST124';
		hos.Staff_Code__c = 'TST Teacher';
		hos.Class_Id__c = 'TST878';
		hos.CLass_Name__c = 'Class 878';
		hos.Network__c = 'TST-NET';
		hos.Username__c = 'TST3';
				hos.School_Dbn__c = 'TESTSCHL1';
		hos.Course_Name__c = 'Course1';
		hos.Reference_Id__c=ImportUtils.createClassSectionKey(hos);
		batch.add(hos);
		
		insert batch;
	}
	
	public static User createUser(Contact staffContact) {
		User usr = new User(IsActive=true);
		usr.Alias = staffContact.FirstName.substring(0,1) + staffContact.LastName;
		if (usr.Alias.length() > 4) {
			usr.Alias = usr.Alias.substring(0,4);
		}
		usr.Email = 'nycdoedev@gmail.com';
		usr.EmailEncodingKey = 'UTF-8';
		usr.FirstName = staffContact.FirstName;
		usr.LastName =staffContact.LastName; 
		usr.LanguageLocaleKey = 'en_US';
		usr.LocaleSidKey = 'en_US'; 
		usr.ProfileId = [select id from Profile where Name ='Standard User'].id;
		//usr.ProfileId = Reading_Tracker_Settings__c.getInstance().Staff_Profile_Id__c;
		usr.TimeZoneSidKey = 'America/Los_Angeles';
		usr.Username = staffContact.User_Name__c + '@schools.nyc.gov.dev';
		usr.Reference_Id__c = staffContact.Reference_Id__c;
		//usr.FederationIdentifier = staffContact.User_Name__c;
		return usr;
	}
	
	testMethod static void testExecute_SectionGrades() {
		setUp_SectionGrades();

		Test.startTest();
		Scheduler_HoldingProcessor shp = new Scheduler_HoldingProcessor();
    		shp.mode = 'Student'; //Set the mode to staff so it kicks off specific Staff processing
    		shp.cSetup = new core_SetupWrapper(TestDataSetupUtil_v2.activeSetup,''); 
    		string query = Scheduler_HoldingProcessor.processQueryForPropagator(shp.mode, null, 'TESTSCHL1');
		List <HoldingObj__c> hoList = database.Query(query);
		
		shp.log.Total_Records__c = 0;
		shp.log.Failed_Records__c=0;
		shp.execute(null, hoList);
		Test.stopTest();
		
		//Account school = [SELECT Id, Name FROM Account WHERE Holding_Source__c = :batch[0].Id];
		//Student__c student = [SELECT Id, Name, Student_First_Name__c, Gender__c, School__c FROM Student__c WHERE Holding_Source__c = :batch[0].Id];
		//Student__c student = [SELECT Id, Name, Student_First_Name__c, Gender__c, School__c FROM Student__c ];
		//System.assertEquals(school.Id, student.School__c);
		
		//String classKey = ImportUtils.createClassSectionKey(batch[0]);
		//system.debug('classKey:'+classKey);
		//Section__c classSection = [SELECT Id, Name FROM Section__c WHERE Reference_Id__c = :classKey];
		//List<Student_Section__c> studentSections = [SELECT Id FROM Student_Section__c WHERE Section__c = :classSection.Id AND Student__r.School__c = :school.Id];
		//System.assertEquals(3, studentSections.size());
				
	}
	
	private static void setUp_SectionGrades() {
		batch = new List<HoldingObj__c>();
		TestDataSetupUtil_v2.setUPCoreData(5);
		Time_Element__c sem = 		TestDataSetupUtil_v2.semester;

		
		
	batch = new List<HoldingObj__c>();
		HoldingObj__c hos = new HoldingObj__c();
		hos.Type__c='Student';
		hos.Student_ID__c = 'BATCH-TEST-1';
		hos.First_Name__c = 'Jon';
		hos.Last_Name__c = 'Doe';
		hos.Sex__c = 'M';
		hos.School_Dbn__c = 'TESTSCHL1';
		hos.Class_Id__c = 'CLS-1';
		hos.Course_Name__c = 'Course';
				hos.School_Year__c ='123456';
		hos.Reporting_Period_Id__c=sem.id;
		hos.Reference_Id__c=ImportUtils.createClassSectionKey(hos);
		batch.add(hos);
		
		hos = new HoldingObj__c();
		hos.Type__c='Student';
		hos.Student_ID__c = 'BATCH-TEST-2';
		hos.First_Name__c = 'Amy';
		hos.Last_Name__c = 'Smith';
		hos.Sex__c = 'F';
		hos.School_Dbn__c = 'TESTSCHL1';
		hos.Class_Id__c = 'CLS-1';
				hos.School_Year__c ='123456';
		hos.ELL__c = 'y';
		hos.Course_Name__c = 'Course';
		hos.Reporting_Period_Id__c=sem.id;
		hos.Reference_Id__c=ImportUtils.createClassSectionKey(hos);
		batch.add(hos);
		
		hos = new HoldingObj__c();
		hos.Type__c='Student';
		hos.Student_ID__c = 'BATCH-TEST-3';
		hos.First_Name__c = 'John';
		hos.Last_Name__c = 'Adams';
		hos.Sex__c = 'M';
		hos.School_Dbn__c = 'TESTSCHL1';
		hos.Class_Id__c = 'CLS-1';
				hos.School_Year__c ='123456';
		hos.Disability_Flag__c = 'y';
		hos.Course_Name__c = 'Course';
		hos.Reporting_Period_Id__c=sem.id;
		batch.add(hos);
		
		
		insert batch;
	}
	

}