objects/Alert__c.object
<CustomObject>
    <description>Used by teachers to create alerts or notifications related to Students, Sections, or Schools</description>
    <fields>
        <fullName>Student__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Student</label>
        <referenceTo>Student__c</referenceTo>
        <relationshipLabel>Alerts</relationshipLabel>
        <relationshipName>Alerts</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Alert</label>
    <nameField>
        <displayFormat>A-{000000}</displayFormat>
        <label>Alert ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Alerts</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/Attendance__c.object
<CustomObject>
    <description>This object will capture all student attendance.</description>
    <fields>
        <fullName>Session_Date__c</fullName>
        <formula>Session__r.Session_Date__c</formula>
        <inlineHelpText>Displays the date and time of the Session record. This field should not be modified.</inlineHelpText>
        <label>Session Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Session__c</fullName>
        <description>This is a lookup to the sessions that attendance is being captured for.</description>
        <inlineHelpText>Displays the date and time of the Session. Do not update this field.</inlineHelpText>
        <label>Session</label>
        <referenceTo>Session__c</referenceTo>
        <relationshipLabel>Attendance</relationshipLabel>
        <relationshipName>Attendance</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Student__c</fullName>
        <description>This is a lookup to the student record.</description>
        <inlineHelpText>This field provides a link to the Student record for the year. Do not update this field.</inlineHelpText>
        <label>Student</label>
        <referenceTo>Student__c</referenceTo>
        <relationshipLabel>Attendance</relationshipLabel>
        <relationshipName>Attendance</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Attendance</label>
    <nameField>
        <displayFormat>A-{0}</displayFormat>
        <label>Attendance ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Attendance</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>true</defaultValue>
        <inlineHelpText>Schools/organizations can choose to use this field when a Contact record is active. When Contact records are created through SchoolForce Setup, this check box is selected.</inlineHelpText>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Student__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>This field provides a link to the most recent Student record.</inlineHelpText>
        <label>Student</label>
        <referenceTo>Student__c</referenceTo>
        <relationshipLabel>Contacts</relationshipLabel>
        <relationshipName>Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <recordTypes>
        <fullName>Student</fullName>
        <active>true</active>
        <description>This record type is for students</description>
        <label>Student</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Enrollment_Tracking__c.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Active?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Student__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Student</label>
        <referenceTo>Student__c</referenceTo>
        <relationshipLabel>Enrollment Tracking</relationshipLabel>
        <relationshipName>Enrollment_Tracking</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Enrollment Tracking</label>
    <nameField>
        <displayFormat>ET-{0000000}</displayFormat>
        <label>Enrollment Tracking Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Enrollment Tracking</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Grade__c.object
<CustomObject>
    <fields>
        <fullName>Student__c</fullName>
        <label>Student</label>
        <referenceTo>Student__c</referenceTo>
        <relationshipLabel>Grades</relationshipLabel>
        <relationshipName>Grades</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Grade</label>
    <nameField>
        <displayFormat>G-{0}</displayFormat>
        <label>Grade Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Grades</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Picklist_Value__c.object
<CustomObject>
    <fields>
        <fullName>Grade__c</fullName>
        <label>Grade</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>PS</fullName>
                </value>
                <value>
                    <fullName>PK</fullName>
                </value>
                <value>
                    <fullName>K</fullName>
                </value>
                <value>
                    <fullName>1</fullName>
                </value>
                <value>
                    <fullName>2</fullName>
                </value>
                <value>
                    <fullName>3</fullName>
                </value>
                <value>
                    <fullName>4</fullName>
                </value>
                <value>
                    <fullName>5</fullName>
                </value>
                <value>
                    <fullName>6</fullName>
                </value>
                <value>
                    <fullName>7</fullName>
                </value>
                <value>
                    <fullName>8</fullName>
                </value>
                <value>
                    <fullName>9</fullName>
                </value>
                <value>
                    <fullName>10</fullName>
                </value>
                <value>
                    <fullName>11</fullName>
                </value>
                <value>
                    <fullName>12</fullName>
                </value>
                <value>
                    <fullName>UN Ungraded</fullName>
                </value>
                <value>
                    <fullName>PK-3</fullName>
                </value>
                <value>
                    <fullName>PK-4</fullName>
                </value>
                <value>
                    <fullName>PK Pre-K</fullName>
                </value>
                <value>
                    <fullName>Kindergarten/Preschool</fullName>
                </value>
                <value>
                    <fullName>KG Kindergarten</fullName>
                </value>
                <value>
                    <fullName>PG Postgraduate/Adult</fullName>
                </value>
                <value>
                    <fullName>Kindergarten</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Picklist Value</label>
    <nameField>
        <label>Display Value</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Picklist Values</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Section__c.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Check this box if the section is a currently active section</description>
        <inlineHelpText>Check this box if the section is a currently active section</inlineHelpText>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <label>Section</label>
    <nameField>
        <label>Section Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sections</pluralLabel>
    <recordTypes>
        <fullName>Published</fullName>
        <active>true</active>
        <description>Sections that have been Published and are Viewable by Standard Users</description>
        <label>Published</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Session__c.object
<CustomObject>
    <description>This object captures the daily session for each section.</description>
    <fields>
        <fullName>Session_Date__c</fullName>
        <formula>DATEVALUE( End_DateTime__c )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Session Date</label>
        <type>Date</type>
    </fields>
    <label>Session</label>
    <nameField>
        <label>Session Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sessions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Student__c.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>true</defaultValue>
        <inlineHelpText>Indicates whether or not this Student record is active. If checked, then this is the current Student record. If unchecked, this is an old Student record.</inlineHelpText>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Grade__c</fullName>
        <inlineHelpText>Displays the student&apos;s current grade level.</inlineHelpText>
        <label>Grade</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>PS</fullName>
                </value>
                <value>
                    <fullName>PK</fullName>
                    <color>#78C953</color>
                    <label>PK</label>
                </value>
                <value>
                    <fullName>K</fullName>
                </value>
                <value>
                    <fullName>1</fullName>
                    <color>#A845DC</color>
                    <label>1</label>
                </value>
                <value>
                    <fullName>2</fullName>
                    <color>#F3D904</color>
                    <label>2</label>
                </value>
                <value>
                    <fullName>3</fullName>
                    <color>#A53711</color>
                    <label>3</label>
                </value>
                <value>
                    <fullName>4</fullName>
                    <color>#66E9BD</color>
                    <label>4</label>
                </value>
                <value>
                    <fullName>5</fullName>
                    <color>#0B24BE</color>
                    <label>5</label>
                </value>
                <value>
                    <fullName>6</fullName>
                    <color>#419249</color>
                    <label>6</label>
                </value>
                <value>
                    <fullName>7</fullName>
                    <color>#B6E32E</color>
                    <label>7</label>
                </value>
                <value>
                    <fullName>8</fullName>
                    <color>#641CCF</color>
                    <label>8</label>
                </value>
                <value>
                    <fullName>9</fullName>
                    <color>#F96FB7</color>
                    <label>9</label>
                </value>
                <value>
                    <fullName>10</fullName>
                    <color>#2F5D85</color>
                    <label>10</label>
                </value>
                <value>
                    <fullName>11</fullName>
                    <color>#AFCADF</color>
                    <label>11</label>
                </value>
                <value>
                    <fullName>12</fullName>
                    <color>#8F6429</color>
                    <label>12</label>
                </value>
                <value>
                    <fullName>UN Ungraded</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Individual__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Displays the name for the Contact record associated to this Student record. You can click the link to view the student&apos;s Contact record.</inlineHelpText>
        <label>Individual Record</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Student Records</relationshipLabel>
        <relationshipName>Students</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Student_First_Name__c</fullName>
        <inlineHelpText>Displays the student&apos;s first name.</inlineHelpText>
        <label>Student First Name</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Student_Last_Name__c</fullName>
        <inlineHelpText>Displays the student&apos;s last name.</inlineHelpText>
        <label>Student Last Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Student__c</fullName>
        <inlineHelpText>Displays the student&apos;s middle name.</inlineHelpText>
        <label>Student Middle Name</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <label>Student</label>
    <nameField>
        <label>Student Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Students</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Student_Section__c.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Student_First_Name__c</fullName>
        <formula>Student__r.Student_First_Name__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Student First Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Student__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Student</label>
        <referenceTo>Student__c</referenceTo>
        <relationshipLabel>Section</relationshipLabel>
        <relationshipName>Student_Section</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Student/Section</label>
    <nameField>
        <displayFormat>SS-{000000}</displayFormat>
        <label>Student/Section ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Student/Section</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/Attendance_SoqlUtils.cls
global class Attendance_SoqlUtils {
		public static List <Student__c> getStudentByName (String sFirstName, String sLastName){
			String tempFirst = core_SoqlUtils.getSearchName(sFirstName);
			String tempLast = core_SoqlUtils.getSearchName(sLastName);
			List <Student__c> studentList = new List <Student__c>();
			String queryString = 'SELECT ID, Student_First_Name__c, Student_Last_Name__c, Grade__c, Individual__r.MailingStreet FROM Student__c';
			if(sFirstName!=null||sLastName!=null){
				queryString +=' Where active__c = true ';
			}
			if(sFirstName!=null){
				queryString += 'AND Student_First_Name__c LIKE '+'\''+tempFirst+'\'';
			}
			if(sLastName!=null){
				queryString += 'AND Student_Last_Name__c LIKE '+'\''+tempLast+'\'';
			}
			studentList = database.query(queryString);
			return studentList;
		}

	public static List <Session__c> getSessionBySection(String selectedSection, Date startDate, Date endDate){
		List <Session__c> sessionList = new List <Session__c>();
		for (Session__c s: [SELECT s.ID, s.Name, s.Session_Date__c, s.Section__r.Daily_Attendance__c
							FROM Session__c s
							WHERE Record_Attendance__c = true
							AND Section__c = :selectedSection ]){
			if (startDate!=null && endDate !=null){
				if (s.Session_Date__c >= startDate && s.Session_Date__c <= endDate){
					sessionList.add(s);
				}
			}
			else sessionList.add(s);
		}
		return sessionList;
	}

	public static List<Student_Section__c> getStudentSectionListByStudent (String selectedStudentID, boolean bAttendance){
		List <Student_Section__c> studSectionList = new List <Student_Section__c>();
		for (Student_Section__c ss: [SELECT ID, Name, Section__r.Name, Section__c, Section__r.Record_Attendance__c
									  FROM Student_Section__c
									  WHERE Student__c = :selectedStudentID
									  AND active__c=true
									  and Section__r.RecordType.DeveloperName = 'Published']){
			if (bAttendance){
				if (ss.Section__r.Record_Attendance__c){
					studSectionList.add(ss);
				}
			}
			else studSectionList.add(ss);
		}
		return studSectionList;
	}

	public static Map<ID,Integer> getTardyMap(Set<ID> studIDSet, ID sectionId){
		Map<ID, Integer> tempMap = new Map<ID, Integer>();
		for(AggregateResult ag : [SELECT Student__c s, count(Name) cnt
									FROM Attendance__c
									WHERE Student__c IN :studIDSet
									AND Picklist_Value__r.Is_Tardy__c = true
									AND Session__r.Section__c =: sectionID
									GROUP BY Student__c]){
			tempMap.put((ID)ag.get('s'),(Integer)ag.get('cnt'));
		}
		return tempMap;
	}

	public static Map<ID,Integer> getAbsentMap(Set<ID> studIDSet, ID sectionId){
		Map<ID, Integer> tempMap = new Map<ID, Integer>();
		for(AggregateResult ag : [SELECT Student__c s, count(Name) cnt
									FROM Attendance__c
									WHERE Student__c IN :studIDSet
									AND Picklist_Value__r.Category__c = 'Absent'
									AND Session__r.Section__c =: sectionId
									GROUP BY Student__c]){
			tempMap.put((ID)ag.get('s'),(Integer)ag.get('cnt'));
		}
		return tempMap;
	}

	public static List<Attendance__c> getAttendanceFromDates(String section, Alert__c startDate, Alert__c endDate, ID student){
		List<Attendance__c> att = [Select   ID, Comments__c, Student__c, Picklist_Value__c, Session__c, Daily__c , external_id__c
										From Attendance__c where Student__c =:student
										AND (Session_Date__c >= :startDate.Expiration_Date__c AND Session_Date__c <= :endDate.Expiration_Date__c)
										AND Session__r.Section__c = :section];
		return att;
	}

	public static Map <ID, List <Enrollment_Tracking__c>> getEnrollmentTrackingMap(Set <Id> studSecIdSet){
		Map <ID, List <Enrollment_Tracking__c>> etMap = new Map <ID, List <Enrollment_Tracking__c>>();
		for (Enrollment_Tracking__c et: [select Active__c, student_section__c, id, start_date__c, end_date__c from Enrollment_Tracking__c where Student_Section__c in: studSecIdSet]){
			if (etMap.get(et.student_section__c)==null){
				etMap.put(et.student_section__c, new List <Enrollment_Tracking__c>{et});
			}
			else etMap.get(et.student_section__c).add(et);
		}
		return etMap;
	}
}