objects/Assesment__c.object
<CustomObject>
    <fields>
        <fullName>Assessment_Results__c</fullName>
        <label>Assessment Results</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipName>Assessments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Student_Id__c</fullName>
        <label>Student_Id</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Student__c</fullName>
        <label>Student Assessment</label>
        <referenceTo>Student__c</referenceTo>
        <relationshipLabel>Assessments</relationshipLabel>
        <relationshipName>Assesment</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Year_Over_Year__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Year over year?</label>
        <type>Checkbox</type>
    </fields>
    <label>Assessment</label>
    <nameField>
        <label>Assessments Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Assessments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Student__c.object
<CustomObject>
    <fields>
        <fullName>Individual__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Displays the name for the Contact record associated to this Student record. You can click the link to view the student&apos;s Contact record.</inlineHelpText>
        <label>Individual Record</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Student Records</relationshipLabel>
        <relationshipName>Students</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Student_Id__c</fullName>
        <inlineHelpText>Displays the student&apos;s ID. This field displays on report cards, progress reports, and transcripts. It must be unique; SchoolForce uses this ID to link the Student record with the correct Contact record.</inlineHelpText>
        <label>Student Id</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Student__c</fullName>
        <inlineHelpText>Displays the student&apos;s middle name.</inlineHelpText>
        <label>Student Middle Name</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <label>Student</label>
    <nameField>
        <label>Student Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Students</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/Test_AssessmentTrigger.cls
@isTest
private class Test_AssessmentTrigger {

    static testMethod void test() {
        testDataSetupUtil_v2.setUPCoreData(0);
        testDataSetupUtil_v2.setUPStaffData(0);
        testDataSetupUtil_v2.setUPStudentData(1);
        
        Test.startTest();
        	Assesment__c sfId = new Assesment__c(Assessment_Results__c = '1', Student__c = testDataSetupUtil_v2.studentsList[0].id);
        	Assesment__c cId = new Assesment__c(Assessment_Results__c = '2', Student__c = testDataSetupUtil_v2.studentsList[0].id, Year_Over_Year__c = true);
        	
        	List<Assesment__c> tempList = new List<Assesment__c>{sfId, cId};
        	insert tempList;
        	
        	tempList.clear();
        	tempList = [select Student_Id__c, Student__c, Contact__c, Year_Over_Year__c from Assesment__c where Student__c =: testDataSetupUtil_v2.studentsList[0].id];
        	//There should be two assessments.
        	system.assertEquals(2, tempList.size());
        	for(Assesment__c a: tempList){
                //CY workflows makes this always invalid as they don't change in the memory after insert.
        		//system.assertEquals(testDataSetupUtil_v2.studentsList[0].Student_ID__c, a.Student_ID__c);
        		if(a.Year_Over_Year__c)
        			system.assertEquals(testDataSetupUtil_v2.studentsList[0].Individual__c, a.Contact__c);
        		else
        			system.assertEquals(null, a.Contact__c);
        	}
        Test.stopTest();
    }
}