objects/Assignment__c.object
<CustomObject>
    <label>Assignment</label>
    <nameField>
        <label>Assignment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Assignments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Grade__c.object
<CustomObject>
    <fields>
        <fullName>Assignment__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Assignment</label>
        <referenceTo>Assignment__c</referenceTo>
        <relationshipLabel>Grades</relationshipLabel>
        <relationshipName>Grades</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Standard__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Standard</label>
        <referenceTo>Standard__c</referenceTo>
        <relationshipLabel>Grades</relationshipLabel>
        <relationshipName>Grades</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Grade</label>
    <nameField>
        <displayFormat>G-{0}</displayFormat>
        <label>Grade Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Grades</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Standard__c.object
<CustomObject>
    <fields>
        <fullName>Long_Text__c</fullName>
        <inlineHelpText>Long text description of the standard that displays in the hover over in the Gradebook and on Portal/PGV. Max of 32,000 characters to describe the Standard.</inlineHelpText>
        <label>Long Text</label>
        <length>32000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Parent_Standard__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Indicates if a standard hierarchy is present and what the parent standard is</inlineHelpText>
        <label>Parent Standard</label>
        <referenceTo>Standard__c</referenceTo>
        <relationshipLabel>Standards</relationshipLabel>
        <relationshipName>Standards</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Strand__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Indicates if a standard looks up to a Strand.  Strand grades are only calculated for the Standards-Only Gradebook.</inlineHelpText>
        <label>Strand</label>
        <referenceTo>Standard__c</referenceTo>
        <relationshipLabel>Standards (Strand)</relationshipLabel>
        <relationshipName>Strands</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Subject__c</fullName>
        <inlineHelpText>retired field</inlineHelpText>
        <label>Subject</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>Standard</label>
    <nameField>
        <label>Standard Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Standards</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/Assignment_StandardsListController.cls
//Most of the code is based off of Section_StandardsListController
public with sharing class Assignment_StandardsListController {
	public Assignment__c assignment			{get;set;}
	public List<standardWrapper> standards	{get;set;}
	public boolean displayList				{get;set;}
	
	public Assignment_StandardsListController(ApexPages.StandardController stdCon){
		assignment = (Assignment__c) stdCon.getRecord();
		displayList = false;
		standards = new List<standardWrapper>();
		
		List<Grade__c> linkingList = [SELECT ID, Standard__c FROM Grade__c WHERE Assignment__c =: assignment.id];
		Set<Id> standardIds = new Set<Id>();
		for(Grade__c g : linkingList){
			if(g.Standard__c != null) {
				standardIds.add(g.Standard__c);
			}
		}
		
		List<Standard__c> standardList = [select id, Name, Subject__c, Long_Text__c,Parent_Standard__c, Strand__c 
											from Standard__c
											where id IN: standardIds];
												
		Set<Id> strandIds = new Set<Id>();
		Map<id, List<Standard__c>> strandStandardMap = new Map<id, List<Standard__c>>();
		for(Standard__c s: standardList){
			if(s.Strand__c != null){
				strandIds.add(s.Strand__c);
			}
			
			if(strandStandardMap.containsKey(s.Strand__c)){
				strandStandardMap.get(s.Strand__c).add(s);
			} else {
				strandStandardMap.put(s.Strand__c, new List<Standard__c>{s});
			}
		}
		
		List<Standard__c> strandList = [select id, Name, Subject__c, Long_Text__c 
										from Standard__c
										where id IN:strandIds];
		
		for(Standard__c s:strandList){
			standards.add(new standardWrapper(s, StrandStandardMap.get(s.id)));
		}
		
		 displayList = (standards.isEmpty())? false:true;
	}

	public class standardWrapper {
		public Standard__c standard					{get;set;}
		public List<Standard__c> childStandards		{get;set;}
		
		public standardWrapper(Standard__c strand, List<Standard__c> standards){
			standard = strand;
			childStandards = standards;
		}
	}
}