objects/Assignment__c.object
<CustomObject>
    <fields>
        <fullName>Section__c</fullName>
        <label>Section</label>
        <referenceTo>Section__c</referenceTo>
        <relationshipLabel>Assignments</relationshipLabel>
        <relationshipName>Assignments</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Time__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Reporting Period</label>
        <referenceTo>Time_Element__c</referenceTo>
        <relationshipLabel>Assignments</relationshipLabel>
        <relationshipName>Assignments</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Assignment</label>
    <nameField>
        <label>Assignment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Assignments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Student__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>This field provides a link to the most recent Student record.</inlineHelpText>
        <label>Student</label>
        <referenceTo>Student__c</referenceTo>
        <relationshipLabel>Contacts</relationshipLabel>
        <relationshipName>Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <recordTypes>
        <fullName>Staff</fullName>
        <active>true</active>
        <description>This record type is for staff members.</description>
        <label>Staff</label>
    </recordTypes>
    <recordTypes>
        <fullName>Student</fullName>
        <active>true</active>
        <description>This record type is for students</description>
        <label>Student</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Grade__c.object
<CustomObject>
    <fields>
        <fullName>Assignment__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Assignment</label>
        <referenceTo>Assignment__c</referenceTo>
        <relationshipLabel>Grades</relationshipLabel>
        <relationshipName>Grades</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Reporting_Period_Name__c</fullName>
        <formula>Time__r.Name__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Reporting Period Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Section__c</fullName>
        <formula>CASESAFEID(Student_Section__r.Section__c)</formula>
        <label>Section</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Student__c</fullName>
        <label>Student</label>
        <referenceTo>Student__c</referenceTo>
        <relationshipLabel>Grades</relationshipLabel>
        <relationshipName>Grades</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Time__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to Time Object</description>
        <inlineHelpText>What Grade Reporting Period is this grade entry reported in?</inlineHelpText>
        <label>Reporting Period</label>
        <referenceTo>Time_Element__c</referenceTo>
        <relationshipLabel>Grades</relationshipLabel>
        <relationshipName>Grades</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Grade</label>
    <nameField>
        <displayFormat>G-{0}</displayFormat>
        <label>Grade Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Grades</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Scheduled_Section__c.object
<CustomObject>
    <fields>
        <fullName>Reporting_Period__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Reporting Period</label>
        <referenceTo>Time_Element__c</referenceTo>
        <relationshipLabel>Scheduled Sections</relationshipLabel>
        <relationshipName>Scheduled_Sections</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Section__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Section</label>
        <referenceTo>Section__c</referenceTo>
        <relationshipLabel>Scheduled Sections</relationshipLabel>
        <relationshipName>Scheduled_Sections</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Scheduled Section</label>
    <nameField>
        <label>Scheduled Section Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Scheduled Sections</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Section__c.object
<CustomObject>
    <fields>
        <fullName>Reporting_Period_Name__c</fullName>
        <description>Maps to a valid reporting period based on the year and school</description>
        <label>Reporting Period Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Reporting_Period__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Usually the only reporting period; could be the first if the section spans multiple reporting periods.</description>
        <label>Reporting Period</label>
        <referenceTo>Time_Element__c</referenceTo>
        <relationshipLabel>Sections (First Reporting Period)</relationshipLabel>
        <relationshipName>Sections1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Section__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Recursive lookup for groups</description>
        <label>Section</label>
        <referenceTo>Section__c</referenceTo>
        <relationshipLabel>Groups in Section</relationshipLabel>
        <relationshipName>Sections1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Time__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Time</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Time_Element__c.Picklist_Value__r.Name</field>
                <operation>equals</operation>
                <value>Year</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Time_Element__c</referenceTo>
        <relationshipLabel>Sections</relationshipLabel>
        <relationshipName>Sections</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Year_Name__c</fullName>
        <description>Must map to a valid Year Name__c value.</description>
        <label>Year Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>Section</label>
    <nameField>
        <label>Section Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sections</pluralLabel>
    <recordTypes>
        <fullName>Published</fullName>
        <active>true</active>
        <description>Sections that have been Published and are Viewable by Standard Users</description>
        <label>Published</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Section_ReportingPeriod__c.object
<CustomObject>
    <fields>
        <fullName>Section__c</fullName>
        <label>Section</label>
        <referenceTo>Section__c</referenceTo>
        <relationshipLabel>Section/ReportingPeriod</relationshipLabel>
        <relationshipName>Section_ReportingPeriod</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Time__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Time</label>
        <referenceTo>Time_Element__c</referenceTo>
        <relationshipLabel>Section/ReportingPeriod</relationshipLabel>
        <relationshipName>Section_ReportingPeriod</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Section/ReportingPeriod</label>
    <nameField>
        <displayFormat>SR-{000000}</displayFormat>
        <label>Section/ReportingPeriod</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Section/ReportingPeriod</pluralLabel>
    <recordTypes>
        <fullName>Published</fullName>
        <active>true</active>
        <label>Published</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Session__c.object
<CustomObject>
    <description>This object captures the daily session for each section.</description>
    <fields>
        <fullName>Section__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This is a lookup to the section that the session belongs to.</description>
        <label>Section</label>
        <referenceTo>Section__c</referenceTo>
        <relationshipLabel>Sessions</relationshipLabel>
        <relationshipName>Sessions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Time__c</fullName>
        <description>This is a lookup to the time when this session is held.</description>
        <label>Time</label>
        <referenceTo>Time_Element__c</referenceTo>
        <relationshipLabel>Sessions</relationshipLabel>
        <relationshipName>Sessions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Session</label>
    <nameField>
        <label>Session Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sessions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Staff_Section__c.object
<CustomObject>
    <fields>
        <fullName>Section__c</fullName>
        <label>Section</label>
        <referenceTo>Section__c</referenceTo>
        <relationshipLabel>Staff</relationshipLabel>
        <relationshipName>Staff_Section</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Staff/Section</label>
    <nameField>
        <displayFormat>SfS-{000000}</displayFormat>
        <label>Staff/Section ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Staff/Section</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Student__c.object
<CustomObject>
    <fields>
        <fullName>Section__c</fullName>
        <inlineHelpText>Displays the student&apos;s current homeroom name or room number. This field can be used for reporting purposes.</inlineHelpText>
        <label>Current Homeroom</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Student__c</fullName>
        <inlineHelpText>Displays the student&apos;s middle name.</inlineHelpText>
        <label>Student Middle Name</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <label>Student</label>
    <nameField>
        <label>Student Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Students</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Student_Section__c.object
<CustomObject>
    <fields>
        <fullName>Section__c</fullName>
        <label>Section</label>
        <referenceTo>Section__c</referenceTo>
        <relationshipLabel>Student</relationshipLabel>
        <relationshipName>Student_Section</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Student__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Student</label>
        <referenceTo>Student__c</referenceTo>
        <relationshipLabel>Section</relationshipLabel>
        <relationshipName>Student_Section</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Student/Section</label>
    <nameField>
        <displayFormat>SS-{000000}</displayFormat>
        <label>Student/Section ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Student/Section</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Time_Element__c.object
<CustomObject>
    <fields>
        <fullName>Name__c</fullName>
        <label>Name</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Reporting_Period__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Reporting Period?</label>
        <type>Checkbox</type>
    </fields>
    <label>Time</label>
    <nameField>
        <displayFormat>T-{000000}</displayFormat>
        <label>Time Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Time</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/Test_SectionTrigger.cls
@isTest
private class Test_SectionTrigger {

	static testMethod void beforeInsert_ExternalSection(){
        testDataSetupUtil_v2.setUPCoreData(3);
        testDataSetupUtil_v2.setUPStaffData(3);
        testDataSetupUtil_v2.setUPStudentData(3);
        Id rtId = core_SoqlUtils.getRecordTypesBySobject('Section__c').get('Published');
        Id cId = testdataSetupUtil_v2.coursesList[0].Id;

        Test.startTest();
            Section__c newSect = testDataSetupUtil_v2.getSection(rtId, ' test', cId, null, null);
            newSect.Year_Name__c = testDataSetupUtil_v2.activeSetUp.year__r.name__c;
            newSect.Reporting_Period_Name__c = testDataSetupUtil_v2.semester.name__c;
            insert newSect;
            system.assert([select reporting_period__c, id from section__c where id=:newSect.id].reporting_period__c!=null);

            Section__c failedSect = testDataSetupUtil_v2.getSection(rtId, ' test', cId, null, null);
            try {
                insert failedSect;
            } catch (exception e){
                System.assert(e.getMessage()!=null);
            }
        Test.stopTest();
	}
    
    //When there are grades, should throw an error.
    //Assignments should not be deleted.
    static testMethod void beforeDeleteWithGrades(){
        testDataSetupUtil_v2.setUPCoreData(3);
        testDataSetupUtil_v2.setUPStaffData(3);
        testDataSetupUtil_v2.setUPStudentData(3);
        Section__c s = testDataSetupUtil_v2.sectionsList[0];
    	
    	Assignment__c a1 = new Assignment__c(Section__c = s.id, Time__c=testDataSetupUtil_v2.semester.id);
    	Assignment__c a2 = new Assignment__c(Section__c = s.id,Time__c=testDataSetupUtil_v2.semester.id);
    	Assignment__c a3 = new Assignment__c(Section__c = s.id,Time__c=testDataSetupUtil_v2.semester.id);
    	insert a1;
    	insert a2;
    	insert a3;
    	
    	Student__c student = testDataSetupUtil_v2.studentsList[0];
    	
    	Grade__c g1 = new Grade__c(Assignment__c = a2.id, Time__c=testDataSetupUtil_v2.semester.id, Student_Section__c=testDataSetupUtil_v2.studSectionsList[0].id, Student__c=student.Id);
    	insert g1;
    	
    	Test.startTest();
    	
    	List<Assignment__c> assign = [SELECT id FROM Assignment__c WHERE Section__c=:s.id];
    	System.assertEquals(3, assign.size());
    	try{
    		delete s;
    		System.assert(false);
    	}
    	catch(Exception e){
    		//should throw an error if attempting to delete a section whose assignments still have grades
    		System.assert(true);
    	}    	
    	//assignments should not be deleted
    	assign = [SELECT id FROM Assignment__c WHERE Section__c=:s.id];
    	System.assertEquals(3, assign.size());
    	
    	Test.stopTest();
    }
    
   
    //	When there are no grades, assignments should be deleted
    
    static testMethod void beforeDeleteNoGrades(){
    	testDataSetupUtil_v2.setUPCoreData(3);
        testDataSetupUtil_v2.setUPStaffData(3);
        Section__c s = testDataSetupUtil_v2.sectionsList[0];
    	
    	Assignment__c a1 = new Assignment__c(Section__c = s.id);
    	Assignment__c a2 = new Assignment__c(Section__c = s.id);
    	Assignment__c a3 = new Assignment__c(Section__c = s.id);
    	insert a1;
    	insert a2;
    	insert a3;
    	
    	Test.startTest();
    	
    	List<Assignment__c> assign = [SELECT id FROM Assignment__c WHERE Section__c=:s.id];
    	System.assertEquals(3, assign.size());
    	
    	delete s;
    	
    	//assignments should be deleted
    	assign = [SELECT id FROM Assignment__c WHERE Section__c=:s.id];
    	System.assertEquals(0, assign.size());
    	
    	Test.stopTest();
    }
     
    static testMethod void testStaffSectionTrigger(){
    	TestDataSetupUtil_v2.setupCoreData(5);
    	TestDataSetupUtil_v2.setUPStaffData(5);
        TestDataSetupUtil_v2.setUPStudentData(5);
        
//        Staff_Section__c ss = new Staff_Section__c(Staff__c=TestDataSetupUtil_v2.teachersList[0].id, Section__c=TestDataSetupUtil_v2.sectionsList[0].id);
//        insert ss;
        Staff_Section__c ss = [SELECT section__r.name, staff__r.Individual__r.reference_id__c, section__r.Time__r.Name__c, reference_id__c FROM Staff_Section__c WHERE Staff__c=:TestDataSetupUtil_v2.teachersList[0].id AND Section__c=:TestDataSetupUtil_v2.sectionsList[0].id order by CreatedDate ASC LIMIT 1];
        system.assertEquals(ss.staff__r.Individual__r.reference_id__c+'_'+ss.section__r.name+'_'+ss.section__r.Time__r.Name__c, ss.reference_id__c);
        //staff.Individual__r.reference_id__c+'_'+sect.name+'_'+sect.Time__r.Name__c;
        
        ss.Staff__c = TestDataSetupUtil_v2.teachersList[1].id;
        update ss;
        ss = [SELECT section__r.name, staff__r.Individual__r.reference_id__c, section__r.Time__r.Name__c, reference_id__c FROM Staff_Section__c WHERE Staff__c=:TestDataSetupUtil_v2.teachersList[1].id AND Section__c=:TestDataSetupUtil_v2.sectionsList[0].id order by CreatedDate ASC LIMIT 1];
        system.assertEquals(ss.staff__r.Individual__r.reference_id__c+'_'+ss.section__r.name+'_'+ss.section__r.Time__r.Name__c, ss.reference_id__c);
        
        ss.reference_id__c = 'banana';
        update ss;
        ss = [SELECT section__r.name, staff__r.Individual__r.reference_id__c, section__r.Time__r.Name__c, reference_id__c FROM Staff_Section__c WHERE Staff__c=:TestDataSetupUtil_v2.teachersList[1].id AND Section__c=:TestDataSetupUtil_v2.sectionsList[0].id order by CreatedDate ASC LIMIT 1];
        system.assertEquals(ss.staff__r.Individual__r.reference_id__c+'_'+ss.section__r.name+'_'+ss.section__r.Time__r.Name__c, ss.reference_id__c);
    }
    
    static testMethod void testMarkCompleted(){
    	TestDataSetupUtil_v2.setupCoreData(5);
    	TestDataSetupUtil_v2.setUPStaffData(5);
        TestDataSetupUtil_v2.setUPStudentData(5);
        Id sectionId = TestDataSetupUtil_v2.sectionsList[0].id;
        test.startTest();
        List <Section_ReportingPeriod__c> srpList = [select id, completed__c from Section_ReportingPeriod__c where section__c =:sectionId];
        srpList[0].completed__c = true;
        update srpList;
        system.assert([select completed__c from Section__c where id=:sectionId ].completed__c==false);
        srpList[1].completed__c = true;
        update srpList;
        system.assert([select completed__c from Section__c where id=:sectionId ].completed__c==true);
           srpList[0].completed__c = false;
        update srpList;
        system.assert([select completed__c from Section__c where id=:sectionId ].completed__c==false);
    }

    static testMethod void testCheckReportingPeriodDeletion(){
        TestDataSetupUtil_v2.setupCoreData(5);
        TestDataSetupUtil_v2.setUPStaffData(5);
        TestDataSetupUtil_v2.setUPStudentData(5);
        
        Id sectionId = TestDataSetupUtil_v2.sectionsList[0].id;
        List <Section_ReportingPeriod__c> srpList = [select id, Time__c, Section__c, Section__r.Name, Completed__c from Section_ReportingPeriod__c where section__c =:sectionId];
        srpList[0].completed__c = true;
        srpList[1].completed__c = true;
        update srpList;

        Assignment__c testAssignment = new Assignment__c();
        testAssignment.Name = 'hope';
        testAssignment.Section__c = testDataSetupUtil_v2.sectionsList[0].ID;
        testAssignment.Due_Date__c = Date.newInstance(system.today().year()+30, 8, 5);
        testAssignment.Weighting_Value__c = 5;
        testAssignment.Name_In_Gradebook__c = 'tHope';
        testAssignment.Include_in_Final_Grade__c = true;
        testAssignment.Time__c = srpList[0].Time__c; //testDataSetupUtil_v2.semester.ID;
        insert testAssignment;

        List<Scheduled_Section__c> ss = new List<Scheduled_Section__c>();
        for(integer i = 0; i<TestDataSetupUtil_v2.teachersList.size(); i++){
            Scheduled_Section__c s = new Scheduled_Section__c(
                Staff__c = TestDataSetupUtil_v2.teachersList[i].id,
                Staff__r = TestDataSetupUtil_v2.teachersList[i],
                Account__r = TestDataSetupUtil_v2.school,
                Room__c = TestDataSetupUtil_v2.roomList[i].id,
                Needs_Publish__c = true,
                Section__c = TestDataSetupUtil_v2.sectionsList[i].Id
            );
            Section_ReportingPeriod__c srp = srpList[Integer.valueOf(math.floor(math.random()*srpList.size()))];
            s.Period_Key__c = ''+i;
            s.Section_ReportingPeriod__c = srp.id;
            s.Section_ReportingPeriod__r = srp;
            ss.add(s);
        }
        insert ss;

        List<Session__c> lstSess = new List<Session__c>();
        for(Section_ReportingPeriod__c srp: srpList){
            lstSess.add(new Session__c(
                Name = srp.Section__r.Name.length()>60? srp.Section__r.Name.substring(0,60): srp.Section__r.Name,
                Section__c = srp.Section__c,
                Start_DateTime__c = Datetime.now(),
                Time__c = srp.Time__c));
        }
        insert lstSess;

        Test.startTest();
            String msgError = '';
            try{
                delete srpList;
            }catch(Exception e){
                msgError = e.getMessage();
            }
        Test.stopTest();
        System.assert(msgError.contains('Deletion of Section Reporting Period not allowed. Please delete all assignments & attendance related to the reporting period and section being purged'));
    }
}