objects/Assignment__c.object
<CustomObject>
    <fields>
        <fullName>Due_Date__c</fullName>
        <inlineHelpText>When is Assignment due to be completed?</inlineHelpText>
        <label>Due Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Time__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Reporting Period</label>
        <referenceTo>Time_Element__c</referenceTo>
        <relationshipLabel>Assignments</relationshipLabel>
        <relationshipName>Assignments</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Assignment</label>
    <nameField>
        <label>Assignment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Assignments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Grade__c.object
<CustomObject>
    <fields>
        <fullName>Assignment__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Assignment</label>
        <referenceTo>Assignment__c</referenceTo>
        <relationshipLabel>Grades</relationshipLabel>
        <relationshipName>Grades</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Due_Date__c</fullName>
        <description>The date the assignment was due for the grade given</description>
        <formula>Assignment__r.Due_Date__c</formula>
        <label>Due Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Standard__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Standard</label>
        <referenceTo>Standard__c</referenceTo>
        <relationshipLabel>Grades</relationshipLabel>
        <relationshipName>Grades</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Student_Section__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Student/Section</label>
        <referenceTo>Student_Section__c</referenceTo>
        <relationshipLabel>Grades</relationshipLabel>
        <relationshipName>Grades</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Student__c</fullName>
        <label>Student</label>
        <referenceTo>Student__c</referenceTo>
        <relationshipLabel>Grades</relationshipLabel>
        <relationshipName>Grades</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Time__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to Time Object</description>
        <inlineHelpText>What Grade Reporting Period is this grade entry reported in?</inlineHelpText>
        <label>Reporting Period</label>
        <referenceTo>Time_Element__c</referenceTo>
        <relationshipLabel>Grades</relationshipLabel>
        <relationshipName>Grades</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Grade</label>
    <nameField>
        <displayFormat>G-{0}</displayFormat>
        <label>Grade Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Grades</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Section_Grade__c.object
<CustomObject>
    <fields>
        <fullName>Grade__c</fullName>
        <label>Grade</label>
        <precision>5</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Student_Section__c</fullName>
        <label>Student/Section</label>
        <referenceTo>Student_Section__c</referenceTo>
        <relationshipLabel>Section Grades</relationshipLabel>
        <relationshipName>Section_Grades</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Time__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Reporting Period</label>
        <referenceTo>Time_Element__c</referenceTo>
        <relationshipLabel>Section Grades</relationshipLabel>
        <relationshipName>Section_Grades</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Section Grade</label>
    <nameField>
        <displayFormat>SECG-{000}</displayFormat>
        <label>Section Grade Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Section Grades</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Standard__c.object
<CustomObject>
    <label>Standard</label>
    <nameField>
        <label>Standard Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Standards</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Student__c.object
<CustomObject>
    <fields>
        <fullName>Grade__c</fullName>
        <inlineHelpText>Displays the student&apos;s current grade level.</inlineHelpText>
        <label>Grade</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>PS</fullName>
                </value>
                <value>
                    <fullName>PK</fullName>
                    <color>#78C953</color>
                    <label>PK</label>
                </value>
                <value>
                    <fullName>K</fullName>
                </value>
                <value>
                    <fullName>1</fullName>
                    <color>#A845DC</color>
                    <label>1</label>
                </value>
                <value>
                    <fullName>2</fullName>
                    <color>#F3D904</color>
                    <label>2</label>
                </value>
                <value>
                    <fullName>3</fullName>
                    <color>#A53711</color>
                    <label>3</label>
                </value>
                <value>
                    <fullName>4</fullName>
                    <color>#66E9BD</color>
                    <label>4</label>
                </value>
                <value>
                    <fullName>5</fullName>
                    <color>#0B24BE</color>
                    <label>5</label>
                </value>
                <value>
                    <fullName>6</fullName>
                    <color>#419249</color>
                    <label>6</label>
                </value>
                <value>
                    <fullName>7</fullName>
                    <color>#B6E32E</color>
                    <label>7</label>
                </value>
                <value>
                    <fullName>8</fullName>
                    <color>#641CCF</color>
                    <label>8</label>
                </value>
                <value>
                    <fullName>9</fullName>
                    <color>#F96FB7</color>
                    <label>9</label>
                </value>
                <value>
                    <fullName>10</fullName>
                    <color>#2F5D85</color>
                    <label>10</label>
                </value>
                <value>
                    <fullName>11</fullName>
                    <color>#AFCADF</color>
                    <label>11</label>
                </value>
                <value>
                    <fullName>12</fullName>
                    <color>#8F6429</color>
                    <label>12</label>
                </value>
                <value>
                    <fullName>UN Ungraded</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Student_First_Name__c</fullName>
        <inlineHelpText>Displays the student&apos;s first name.</inlineHelpText>
        <label>Student First Name</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Student_Last_Name__c</fullName>
        <inlineHelpText>Displays the student&apos;s last name.</inlineHelpText>
        <label>Student Last Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Student__c</fullName>
        <inlineHelpText>Displays the student&apos;s middle name.</inlineHelpText>
        <label>Student Middle Name</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <label>Student</label>
    <nameField>
        <label>Student Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Students</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Student_Section__c.object
<CustomObject>
    <fields>
        <fullName>Student_First_Name__c</fullName>
        <formula>Student__r.Student_First_Name__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Student First Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Student__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Student</label>
        <referenceTo>Student__c</referenceTo>
        <relationshipLabel>Section</relationshipLabel>
        <relationshipName>Student_Section</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Student/Section</label>
    <nameField>
        <displayFormat>SS-{000000}</displayFormat>
        <label>Student/Section ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Student/Section</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/GradebookWrapper.cls
public with sharing class GradebookWrapper {

	public string		sectionName						{get;set;}
	public Map<String, Grade__c> StudentGradeMap;
	transient public cStudentWrapper header 						{get;set;}
	transient public List<cStudentWrapper> studentWrapperList 	{get;set;}			
   	public Map<Id, Assignment__c> assignmentMap;
   	public Map<Id, Standard__c> standardMap;
	public Map<Id, cStudentWrapper> swMap;
	public Map<Id, Section_Grade__c> sectGradeMap;
	public Map<Id, String> singleAssignmentMap;
	public Map<Id, String> singleStandardMap;
	public string 	sectionId;
	public string   timeId;
	public string 	assignmentTypeId;
	public string	selectedAssignmentID 				{get;set;}
	public string	selectedStandardID					{get;set;}
	public string	selectedStudentId					{get;set;}
	public boolean bHasStandards						{get;set;}
	


	
	public GradebookWrapper(){
		this.bHasStandards = false;
		this.assignmentMap = new Map<Id, Assignment__c>();
		this.standardMap = new Map<Id, Standard__c>();
		this.swMap = new Map<Id, cStudentWrapper>();	
		this.selectedAssignmentID = 'All';
		this.selectedStandardID = 'All';
		this.AssignmentTypeId = 'All';
		this.header = new cStudentWrapper();
		this.studentWrapperList = new List<cStudentWrapper>();
		this.sectGradeMap = new Map<Id, Section_Grade__c>();
		this.singleAssignmentMap = new Map<Id, String>();
		this.singleStandardMap = new Map<Id, String>();

	}
	public class cStudentWrapper{
		transient public Student__c		student								{get;set;}
		transient public Section_Grade__c sectionGrade						{get;set;}
		transient public List<cStandardWrapper> standardWrapperList			{get;set;}
		transient public Map<String, cStandardWrapper> standardMap			{get;set;}
		transient public List<cAssignmentWrapper> assignmentWrapperList		{get;set;}
		transient public Map<String, cAssignmentWrapper> assignmentMap		{get;set;}
		transient public integer gradeListSize								{get;set;}
		transient public string	rowStyle									{get;set;}
		transient public string	sectGradeStyle								{get;set;}
		transient public integer totalSessions {get;set;}
		transient public integer absentSessions {get;set;}
		transient public integer tardySessions{get;set;}
		
		public cStudentWrapper(Grade__c grade, Standard__c standard, Section_Grade__c sectgrade){
			init(grade, sectGrade);
			
			if(standard==null){
				this.standardMap = new Map<String, cStandardWrapper>{null=>new cStandardWrapper(grade, standard)};
			}
			else{
				this.standardMap = new Map<String, cStandardWrapper>{standard.Id=>new cStandardWrapper(grade, standard)};
			}
			
			this.standardWrapperList = new List<cStandardWrapper>();
		}
	
		public cStudentWrapper(Grade__c grade, Assignment__c assignment, String nebel, Section_Grade__c sectgrade){
			init(grade, sectGrade);
			this.assignmentMap = new Map<String, cAssignmentWrapper>{assignment.Id=>new cAssignmentWrapper(grade, assignment)};
			this.assignmentWrapperList = new List<cAssignmentWrapper>();
		}
		
		private void init(Grade__c grade, Section_Grade__c sectGrade)
		{
			this.gradeListSize = 0;
			this.student = grade.Student_Section__r.Student__r;
			if (sectGrade==null) sectGrade = new Section_Grade__c(Student_Section__c=grade.Student_Section__c, Time__c=grade.Time__c);
			this.sectionGrade = sectGrade;
			totalSessions = 0;
			absentSessions = 0;
			tardySessions = 0;
		}
	
		public cStudentWrapper(){
			this.gradeListSize = 0;
			this.standardWrapperList = new List<cStandardWrapper>();
			this.standardMap = new Map<String, cStandardWrapper>();
			this.assignmentWrapperList = new List<cAssignmentWrapper>();
			this.assignmentMap = new Map<String, cAssignmentWrapper>();
		}
	}

public List<cStudentWrapper> sortDisplayData(List<cStudentWrapper> pList, Boolean standardDisp){
        // utility lists
        List<String> names                  = new List<String>();               // list of student names
        List<cStudentWrapper> retList   = new List<cStudentWrapper>();  // sorted list ready to be returned
        Map <String, cStudentWrapper> studentWrapperMap = new Map<String, cStudentWrapper>();
      		
        
        // obtain the student's name 
        for(cStudentWrapper h : pList){
        	string key  = h.student.student_last_name__c+h.student.student_first_Name__c+h.student.id;
            names.add(key);         // add the student's name to the list for sorting purposes
             if (h.student.name.length() >= 25) h.student.name = h.student.student_first_Name__c.substring(0,1)+'. '+h.student.student_last_name__c;
            studentWrapperMap.put(key, h);
        }
        
        names.sort();       // sort the list of names
        
        // prepare the output data list to match the order of sorted name list
        for(String s : names) {
            retList.add(studentWrapperMap.get(s));
        }
        
        if(!standardDisp){
	        for(cStudentWrapper sw: retList){
	        	List<String> awKeyList = new List<String>();
	        	Map <String, cAssignmentWrapper> swMap = new Map<String, cAssignmentWrapper>();
	        	List<cAssignmentWrapper> tempList = new List <cAssignmentWrapper>();
	        	for(cAssignmentWrapper aw: sw.assignmentMap.values()){
	        		string swKey = aw.assignment.Due_Date__c+'-'+aw.assignment.id;
	        		awKeyList.add(swKey);
	        		swMap.put(swKey, aw);	        		
	        	}
	        	
	        	awKeyList.sort();
	        	
	        	
	        	for(String key: awKeyList){
		      	tempList.add(swMap.get(key));		      	
	        	}
	        	sw.assignmentWrapperList.clear();
	        	sw.assignmentWrapperList = tempList;
	        }
        }
        return retList;
    }
    
public class cStandardWrapper{
	public ID assignmentID			{get;set;}
	public Standard__c standard 	{get;set;}
	public String standardName		{get;set;}
	public List<Grade__c> gradeList {get;set;}
	public Integer gradeListSize;	
	
	public cStandardWrapper(Grade__c grade, Standard__c standard){
		this.assignmentID = grade.Assignment__c;
	 	if (standard==null){
	 		this.standardName='';
	 	}
	 	else {
	 		this.standard=standard;
	 		this.standardName=standard.Name;
	 	}
	 	this.gradeList = new List <Grade__c>{grade};
		this.gradeListSize=1;
	}
	
	public cStandardWrapper(){
		
		this.gradeList = new List <Grade__c>();
		this.standard = new Standard__c();
		this.gradeListSize=0;
	}
	
	public integer getgradeListSize(){
		gradeListSize = gradeList.size();
		return gradeListSize;
	}
}

public class cAssignmentWrapper{
	public Assignment__c assignment {get;set;}
	public String assignmentName;
	public List<Grade__c> gradeList {get;set;}
	public Integer gradeListSize;
	

	public cAssignmentWrapper(Grade__c grade, Assignment__c assignment){
	 		this.assignment=assignment;
	 		this.assignmentName=assignment.Name;
	 		this.gradeList = new List <Grade__c>{grade};
	 		this.gradeListSize=0;
	}
	
	public cAssignmentWrapper(){
		this.gradeList = new List <Grade__c>();
		this.assignment = new Assignment__c();
		this.gradeListSize=0;
	}
	
	public integer getgradeListSize(){
		gradeListSize = gradeList.size();
		return gradeListSize;
	}
	
		
}

}