objects/Assignment__c.object
<CustomObject>
    <fields>
        <fullName>Section__c</fullName>
        <label>Section</label>
        <referenceTo>Section__c</referenceTo>
        <relationshipLabel>Assignments</relationshipLabel>
        <relationshipName>Assignments</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Time__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Reporting Period</label>
        <referenceTo>Time_Element__c</referenceTo>
        <relationshipLabel>Assignments</relationshipLabel>
        <relationshipName>Assignments</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Assignment</label>
    <nameField>
        <label>Assignment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Assignments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Course__c.object
<CustomObject>
    <label>Course</label>
    <nameField>
        <label>Course Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Courses</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/Grade__c.object
<CustomObject>
    <fields>
        <fullName>Assignment__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Assignment</label>
        <referenceTo>Assignment__c</referenceTo>
        <relationshipLabel>Grades</relationshipLabel>
        <relationshipName>Grades</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Course__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>We store course here as well so we can calculate final grade using aggregate queries</description>
        <label>Course</label>
        <referenceTo>Course__c</referenceTo>
        <relationshipLabel>Grades</relationshipLabel>
        <relationshipName>Grades</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Section__c</fullName>
        <formula>CASESAFEID(Student_Section__r.Section__c)</formula>
        <label>Section</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Standard_Gradebook_Grade__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Standard Gradebook Grade</label>
        <referenceTo>Grade__c</referenceTo>
        <relationshipLabel>Grades</relationshipLabel>
        <relationshipName>Grades</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Standard_Weighting__c</fullName>
        <label>Standard Weighting</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Standard__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Standard</label>
        <referenceTo>Standard__c</referenceTo>
        <relationshipLabel>Grades</relationshipLabel>
        <relationshipName>Grades</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Student_Section__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Student/Section</label>
        <referenceTo>Student_Section__c</referenceTo>
        <relationshipLabel>Grades</relationshipLabel>
        <relationshipName>Grades</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Student__c</fullName>
        <label>Student</label>
        <referenceTo>Student__c</referenceTo>
        <relationshipLabel>Grades</relationshipLabel>
        <relationshipName>Grades</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Time__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to Time Object</description>
        <inlineHelpText>What Grade Reporting Period is this grade entry reported in?</inlineHelpText>
        <label>Reporting Period</label>
        <referenceTo>Time_Element__c</referenceTo>
        <relationshipLabel>Grades</relationshipLabel>
        <relationshipName>Grades</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Grade</label>
    <nameField>
        <displayFormat>G-{0}</displayFormat>
        <label>Grade Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Grades</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Section__c.object
<CustomObject>
    <fields>
        <fullName>Course__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Select the course associated to the section you want to create.</inlineHelpText>
        <label>Course</label>
        <referenceTo>Course__c</referenceTo>
        <relationshipLabel>Sections</relationshipLabel>
        <relationshipName>Sections</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Section__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Recursive lookup for groups</description>
        <label>Section</label>
        <referenceTo>Section__c</referenceTo>
        <relationshipLabel>Groups in Section</relationshipLabel>
        <relationshipName>Sections1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Time__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Time</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Time_Element__c.Picklist_Value__r.Name</field>
                <operation>equals</operation>
                <value>Year</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Time_Element__c</referenceTo>
        <relationshipLabel>Sections</relationshipLabel>
        <relationshipName>Sections</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Section</label>
    <nameField>
        <label>Section Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sections</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Standard__c.object
<CustomObject>
    <fields>
        <fullName>Course__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Not required.  A standard can be associated with 1 course (only 1, not many).  The Course is not visible when searching for standards in the Gradebook.</inlineHelpText>
        <label>Course</label>
        <referenceTo>Course__c</referenceTo>
        <relationshipLabel>Standards</relationshipLabel>
        <relationshipName>Standards</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Standard</label>
    <nameField>
        <label>Standard Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Standards</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Standard_Weight_Config__c.object
<CustomObject>
    <fields>
        <fullName>Default_Weighting__c</fullName>
        <defaultValue>1</defaultValue>
        <label>Default Weighting</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Section__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Section</label>
        <referenceTo>Section__c</referenceTo>
        <relationshipLabel>Standard Weights/Configs</relationshipLabel>
        <relationshipName>Standard_Weights_Configs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Standard__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Standard</label>
        <referenceTo>Standard__c</referenceTo>
        <relationshipLabel>Standard Weights/Configs</relationshipLabel>
        <relationshipName>Standard_Weights_Configs</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Standard Weight/Config</label>
    <nameField>
        <displayFormat>SSW{0}</displayFormat>
        <label>Standard Weight/Config Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Standard Weights/Configs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Student__c.object
<CustomObject>
    <fields>
        <fullName>Grade__c</fullName>
        <inlineHelpText>Displays the student&apos;s current grade level.</inlineHelpText>
        <label>Grade</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>PS</fullName>
                </value>
                <value>
                    <fullName>PK</fullName>
                    <color>#78C953</color>
                    <label>PK</label>
                </value>
                <value>
                    <fullName>K</fullName>
                </value>
                <value>
                    <fullName>1</fullName>
                    <color>#A845DC</color>
                    <label>1</label>
                </value>
                <value>
                    <fullName>2</fullName>
                    <color>#F3D904</color>
                    <label>2</label>
                </value>
                <value>
                    <fullName>3</fullName>
                    <color>#A53711</color>
                    <label>3</label>
                </value>
                <value>
                    <fullName>4</fullName>
                    <color>#66E9BD</color>
                    <label>4</label>
                </value>
                <value>
                    <fullName>5</fullName>
                    <color>#0B24BE</color>
                    <label>5</label>
                </value>
                <value>
                    <fullName>6</fullName>
                    <color>#419249</color>
                    <label>6</label>
                </value>
                <value>
                    <fullName>7</fullName>
                    <color>#B6E32E</color>
                    <label>7</label>
                </value>
                <value>
                    <fullName>8</fullName>
                    <color>#641CCF</color>
                    <label>8</label>
                </value>
                <value>
                    <fullName>9</fullName>
                    <color>#F96FB7</color>
                    <label>9</label>
                </value>
                <value>
                    <fullName>10</fullName>
                    <color>#2F5D85</color>
                    <label>10</label>
                </value>
                <value>
                    <fullName>11</fullName>
                    <color>#AFCADF</color>
                    <label>11</label>
                </value>
                <value>
                    <fullName>12</fullName>
                    <color>#8F6429</color>
                    <label>12</label>
                </value>
                <value>
                    <fullName>UN Ungraded</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Section__c</fullName>
        <inlineHelpText>Displays the student&apos;s current homeroom name or room number. This field can be used for reporting purposes.</inlineHelpText>
        <label>Current Homeroom</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Student__c</fullName>
        <inlineHelpText>Displays the student&apos;s middle name.</inlineHelpText>
        <label>Student Middle Name</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <label>Student</label>
    <nameField>
        <label>Student Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Students</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Student_Section__c.object
<CustomObject>
    <fields>
        <fullName>Section__c</fullName>
        <label>Section</label>
        <referenceTo>Section__c</referenceTo>
        <relationshipLabel>Student</relationshipLabel>
        <relationshipName>Student_Section</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Student__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Student</label>
        <referenceTo>Student__c</referenceTo>
        <relationshipLabel>Section</relationshipLabel>
        <relationshipName>Student_Section</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Student/Section</label>
    <nameField>
        <displayFormat>SS-{000000}</displayFormat>
        <label>Student/Section ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Student/Section</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/Gradebook_ManageStandardWeights.cls
public class Gradebook_ManageStandardWeights {

	public static void isafterupdate(Map<Id, Standard_Weight_Config__c> newamap, Map<Id, Standard_Weight_Config__c> oldamap ) {
		Map<String, Double> standardWeightMap = new Map<String, Double>();
		Set<ID> sectionsToProcess = new Set<ID>();
		Set<ID> standardsToProcess = new Set<ID>();
		for (Standard_Weight_Config__c s: newamap.values() ) {
			system.debug('IN THE LOOP: ' + s);
		//check if standard weight was changed, if so update grade records
			if (newamap.get(s.Id).Default_Weighting__c <> oldamap.get(s.Id).Default_Weighting__c ) {
			//need to update Grade Records
				sectionsToProcess.add(s.Section__c);
				standardsToProcess.add(s.Standard__c);
				standardWeightMap.put(string.valueOf(s.Section__c)+string.valueOf(s.Standard__c), s.Default_Weighting__c);
			}
		}
	
		
		
		
		
		List<Grade__c> gradestoupdate = [Select Id, 
												Standard_Weighting__c,
												Standard__c,
												Student_Section__r.Section__c from Grade__c 
												where Student_Section__r.Section__c in : sectionsToProcess 
												AND Standard__c in : standardsToProcess
												AND Standard_Gradebook_Grade__c = null];
												
		for (Grade__c g: gradestoupdate ) {
			g.Standard_Weighting__c = standardWeightMap.get(String.valueOf(g.Student_Section__r.Section__c)+String.valueOf(g.Standard__c));
		}
		try{
			update gradestoupdate;
		}
		catch (Exception Ex) {
			system.debug(Ex);
		}
	} //end after update
	static testMethod Void test_core_GradeScaleCatalogController(){
    	
    			TestDataSetupUtil_v2.isGradebook=true;
		TestDataSetupUtil_v2.setUPCoreData(3);
		TestDataSetupUtil_v2.setUpStaffData(5);
		TestDataSetupUtil_v2.setUpStudentData(5);
		TestDataSetupUtil_v2.setUpStandards();
		List<Standard__c> standard = [SELECT id,Name FROM Standard__c WHERE Course__c=:TestDataSetupUtil_v2.coursesList[0].id];
		

    	system.runAs(testDataSetupUtil_v2.staffUsersList[1]){
    		

    		Standard_Weight_Config__c swc = new Standard_Weight_Config__c(Default_Weighting__c = 1, Section__c = testdatasetuputil_v2.sectionsList[1].id, Standard__c = standard[0].id);
    		insert swc;
    		system.assert(swc.id!=null);

    		
    				Assignment__c a1 = new Assignment__c(Time__c=TestDataSetupUtil_v2.semester.id, Name='Test Assignment', Section__c=		TestDataSetupUtil_v2.sectionsList[1].id);
		insert a1;
		
		Student__c student = testDataSetupUtil_v2.studentsList[0];
		Grade__c g1 = new Grade__c(Time__c=TestDataSetupUtil_v2.semester.id,Assignment__c=a1.id, Course__c=		TestDataSetupUtil_v2.coursesList[0].id, Standard__c=standard[0].id, Student_Section__c=TestDataSetupUtil_v2.studSectionsList[1].id, Student__c=student.Id);

			g1.standard__c = standard[0].id;
    		g1.Student_Section__c = testdatasetuputil_v2.studSectionsList[1].id;
    		insert g1;
    		swc.default_weighting__c = 2;
    		update swc;
    		
    		
    		
    	}
	}
}