objects/Assignment__c.object
<CustomObject>
    <fields>
        <fullName>Include_in_Final_Grade__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Determines whether or not a grade will be used in the calculation of a final grade or not</description>
        <label>Include in Final Grade</label>
        <type>Checkbox</type>
    </fields>
    <label>Assignment</label>
    <nameField>
        <label>Assignment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Assignments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Grade__c.object
<CustomObject>
    <fields>
        <fullName>Assignment__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Assignment</label>
        <referenceTo>Assignment__c</referenceTo>
        <relationshipLabel>Grades</relationshipLabel>
        <relationshipName>Grades</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Grade_Update__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Grade Update</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Standard__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Standard</label>
        <referenceTo>Standard__c</referenceTo>
        <relationshipLabel>Grades</relationshipLabel>
        <relationshipName>Grades</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Student_Section__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Student/Section</label>
        <referenceTo>Student_Section__c</referenceTo>
        <relationshipLabel>Grades</relationshipLabel>
        <relationshipName>Grades</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Student__c</fullName>
        <label>Student</label>
        <referenceTo>Student__c</referenceTo>
        <relationshipLabel>Grades</relationshipLabel>
        <relationshipName>Grades</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>exclude_From_Section_Grade__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Simple flag that keeps the assignment from being used in the calculation of the section grade</description>
        <label>Exclude From Section Grade</label>
        <type>Checkbox</type>
    </fields>
    <label>Grade</label>
    <nameField>
        <displayFormat>G-{0}</displayFormat>
        <label>Grade Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Grades</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Setup__c.object
<CustomObject>
    <description>This object is used to setup Schoolforce and is referenced in multiple pieces of code.  There should be one setup object per school.</description>
    <fields>
        <fullName>Law_of_Decaying_Average_Weight__c</fullName>
        <description>This field is only used for the standard calculation type: Law of Decaying Average.  A value of 1.00 to 0.00 is desired in determining the weight.</description>
        <label>Law of Decaying Average Weight</label>
        <precision>6</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>Setup</label>
    <nameField>
        <displayFormat>S-{0}</displayFormat>
        <label>Setup ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Setup</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/Standard__c.object
<CustomObject>
    <label>Standard</label>
    <nameField>
        <label>Standard Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Standards</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Student__c.object
<CustomObject>
    <fields>
        <fullName>Grade__c</fullName>
        <inlineHelpText>Displays the student&apos;s current grade level.</inlineHelpText>
        <label>Grade</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>PS</fullName>
                </value>
                <value>
                    <fullName>PK</fullName>
                    <color>#78C953</color>
                    <label>PK</label>
                </value>
                <value>
                    <fullName>K</fullName>
                </value>
                <value>
                    <fullName>1</fullName>
                    <color>#A845DC</color>
                    <label>1</label>
                </value>
                <value>
                    <fullName>2</fullName>
                    <color>#F3D904</color>
                    <label>2</label>
                </value>
                <value>
                    <fullName>3</fullName>
                    <color>#A53711</color>
                    <label>3</label>
                </value>
                <value>
                    <fullName>4</fullName>
                    <color>#66E9BD</color>
                    <label>4</label>
                </value>
                <value>
                    <fullName>5</fullName>
                    <color>#0B24BE</color>
                    <label>5</label>
                </value>
                <value>
                    <fullName>6</fullName>
                    <color>#419249</color>
                    <label>6</label>
                </value>
                <value>
                    <fullName>7</fullName>
                    <color>#B6E32E</color>
                    <label>7</label>
                </value>
                <value>
                    <fullName>8</fullName>
                    <color>#641CCF</color>
                    <label>8</label>
                </value>
                <value>
                    <fullName>9</fullName>
                    <color>#F96FB7</color>
                    <label>9</label>
                </value>
                <value>
                    <fullName>10</fullName>
                    <color>#2F5D85</color>
                    <label>10</label>
                </value>
                <value>
                    <fullName>11</fullName>
                    <color>#AFCADF</color>
                    <label>11</label>
                </value>
                <value>
                    <fullName>12</fullName>
                    <color>#8F6429</color>
                    <label>12</label>
                </value>
                <value>
                    <fullName>UN Ungraded</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Setup__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Displays the Setup record associated to this Student record. The Setup record defines the settings for the school in a specific school year.</inlineHelpText>
        <label>Setup</label>
        <referenceTo>Setup__c</referenceTo>
        <relationshipLabel>Students</relationshipLabel>
        <relationshipName>Students</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Student__c</fullName>
        <inlineHelpText>Displays the student&apos;s middle name.</inlineHelpText>
        <label>Student Middle Name</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <label>Student</label>
    <nameField>
        <label>Student Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Students</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Student_Section__c.object
<CustomObject>
    <fields>
        <fullName>Student__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Student</label>
        <referenceTo>Student__c</referenceTo>
        <relationshipLabel>Section</relationshipLabel>
        <relationshipName>Student_Section</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Student/Section</label>
    <nameField>
        <displayFormat>SS-{000000}</displayFormat>
        <label>Student/Section ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Student/Section</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/Batch_GradeRecalc.cls
global class Batch_GradeRecalc implements Database.Batchable<sObject>{
	   global String query;
		
	   global Database.QueryLocator start(Database.BatchableContext BC){
	      return Database.getQueryLocator(query);
	   }
	
	   global void execute(Database.BatchableContext BC, List<Grade__c> scope){	
	   	//Batch query needs to include Grade_Update__c, ID, Student_Section__r.Student__c, Standard__c, Student_Section__r.Student__r.Setup__r.Law_of_Decaying_Average_Weight__c
	   		List<Grade__c> gList = new List<Grade__c>();
	   		for(Grade__c g : scope){
	   			g.Grade_Update__c = !g.Grade_Update__c;
	   			//g.exclude_From_Section_Grade__c = !g.Assignment__r.Include_in_final_grade__c; Should not be considered the same; exclude is specifically used for 'drop' grades US2794
	   			gList.add(g);
	   		}
	   		core_triggerUtils.calculationTriggerUpdate(true);
	   		update gList;
	   		core_triggerUtils.calculationTriggerUpdate(false);	
	   }
	
	   global void finish(Database.BatchableContext BC){
	   		AsyncApexJob a = [Select Id, Status, NumberOfErrors, JobItemsProcessed,
	        						 TotalJobItems, CreatedBy.Email
	        						 from AsyncApexJob where Id =:BC.getJobId()];
	        
	        // Send an email to the Apex job's submitter notifying of job completion.  
	    
	        Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
	        String[] toAddresses = new String[] {a.CreatedBy.Email};
	        mail.setToAddresses(toAddresses);
	        mail.setSubject('Grade Recalculation - ' + a.Status);
	        
		   	mail.setPlainTextBody
	   		('The Grade Recalculation job processed ' + a.TotalJobItems +
	   		' batches with '+ a.NumberOfErrors + ' failures.');
	  		Messaging.sendEmail(new Messaging.SingleEmailMessage[] { mail });
	   }
}