objects/Attendance__c.object
<CustomObject>
    <description>This object will capture all student attendance.</description>
    <fields>
        <fullName>Student__c</fullName>
        <description>This is a lookup to the student record.</description>
        <inlineHelpText>This field provides a link to the Student record for the year. Do not update this field.</inlineHelpText>
        <label>Student</label>
        <referenceTo>Student__c</referenceTo>
        <relationshipLabel>Attendance</relationshipLabel>
        <relationshipName>Attendance</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Attendance</label>
    <nameField>
        <displayFormat>A-{0}</displayFormat>
        <label>Attendance ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Attendance</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Student__c.object
<CustomObject>
    <fields>
        <fullName>Attendance__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Attendance</label>
        <precision>1</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Student__c</fullName>
        <inlineHelpText>Displays the student&apos;s middle name.</inlineHelpText>
        <label>Student Middle Name</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <label>Student</label>
    <nameField>
        <label>Student Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Students</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/Attendance_Utils.cls
public with sharing class Attendance_Utils {
	//attendances key -> value is: studentID -> Attendance
	public static Boolean isAttendanceTaken(List<Student__c> students, Map<ID, Attendance__c> attendances) {
		Boolean b = true;
		try {
			if(students.size() != attendances.size() ) {
				b = false;
			}	
		}
		catch(Exception e) {
			throw(e);
		}
		return b;
	}

	public static String setLastModified(String sectionName) {
		Datetime dt = System.now();
		String s = UserInfo.getName() + ' took attendance for ' + sectionName + ' on ' + dt.format('MM/dd/yyyy h:mm a');
		return s;
	}
}