objects/Attendance__c.object
<CustomObject>
    <description>This object will capture all student attendance.</description>
    <fields>
        <fullName>Date_Time_of_Parental_Notification__c</fullName>
        <inlineHelpText>Displays the date and time the system sent an alert to parent/guardian informing them that their child had an unexcused absence/tardy. Parent notification must be setup or this field will always be blank.</inlineHelpText>
        <label>Date/Time of Parental Notification</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Student__c</fullName>
        <description>This is a lookup to the student record.</description>
        <inlineHelpText>This field provides a link to the Student record for the year. Do not update this field.</inlineHelpText>
        <label>Student</label>
        <referenceTo>Student__c</referenceTo>
        <relationshipLabel>Attendance</relationshipLabel>
        <relationshipName>Attendance</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Attendance</label>
    <nameField>
        <displayFormat>A-{0}</displayFormat>
        <label>Attendance ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Attendance</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Email_to_SMS_Address__c</fullName>
        <formula>IF (
AND (
NOT(ISBLANK( MobilePhone )),
NOT(ISBLANK( TEXT(Wireless_Provider__c )))
),
Case ( Wireless_Provider__c,
&quot;ATT&quot;, SUBSTITUTE( SUBSTITUTE( SUBSTITUTE( SUBSTITUTE( SUBSTITUTE( MobilePhone , &apos;.&apos;, &apos;&apos;) , &apos; &apos;, &apos;&apos;) , &apos;-&apos;, &apos;&apos;) , &apos;)&apos;, &apos;&apos;) , &apos;(&apos;, &apos;&apos;)&amp;&quot;@txt.att.net&quot;,
&quot;Verizon&quot;, SUBSTITUTE( SUBSTITUTE( SUBSTITUTE( SUBSTITUTE( SUBSTITUTE( MobilePhone , &apos;.&apos;, &apos;&apos;) , &apos; &apos;, &apos;&apos;) , &apos;-&apos;, &apos;&apos;) , &apos;)&apos;, &apos;&apos;) , &apos;(&apos;, &apos;&apos;)&amp;&quot;@vtext.com&quot;,
&quot;Sprint&quot;,SUBSTITUTE( SUBSTITUTE( SUBSTITUTE( SUBSTITUTE( SUBSTITUTE( MobilePhone , &apos;.&apos;, &apos;&apos;) , &apos; &apos;, &apos;&apos;) , &apos;-&apos;, &apos;&apos;) , &apos;)&apos;, &apos;&apos;) , &apos;(&apos;, &apos;&apos;)&amp;&quot;@messaging.sprintpcs.com&quot;,
&quot;T-Mobile&quot;,SUBSTITUTE( SUBSTITUTE( SUBSTITUTE( SUBSTITUTE( SUBSTITUTE( MobilePhone , &apos;.&apos;, &apos;&apos;) , &apos; &apos;, &apos;&apos;) , &apos;-&apos;, &apos;&apos;) , &apos;)&apos;, &apos;&apos;) , &apos;(&apos;, &apos;&apos;)&amp;&quot;@tmomail.net&quot;,
&quot;Virgin Mobile&quot;, SUBSTITUTE( SUBSTITUTE( SUBSTITUTE( SUBSTITUTE( SUBSTITUTE( MobilePhone , &apos;.&apos;, &apos;&apos;) , &apos; &apos;, &apos;&apos;) , &apos;-&apos;, &apos;&apos;) , &apos;)&apos;, &apos;&apos;) , &apos;(&apos;, &apos;&apos;)&amp;&quot;@vmobl.com&quot;,
&quot;&quot;),

&quot;&quot;)</formula>
        <inlineHelpText>SchoolForce automatically updates this field using the information you enter into the Mobile Phone and Mobile Carrier fields. It is used for sending attendance alerts to parents via SMS.</inlineHelpText>
        <label>Email to SMS Address</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Notify_via_Email__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Select if the parent would prefer to receve notifications via email.</inlineHelpText>
        <label>Notify via Email</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Notify_via_SMS__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Select if parent would prefer to receve notifications via SMS text message.</inlineHelpText>
        <label>Notify via SMS</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Preferred_Language__c</fullName>
        <description>Used for parent/guardian to determine what language to send notifications/written information. Replacing &quot;Receive written information in Spanish?&quot; checkbox so as to make more modular and allow for multiple possible languages.</description>
        <inlineHelpText>Displays the language that the student or parent/guardian wishes to receive emails and/or SMS notifications in. Current options are English and Spanish.</inlineHelpText>
        <label>Preferred Language</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>English</fullName>
                    <default>true</default>
                    <label>English</label>
                </value>
                <value>
                    <fullName>Spanish</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Student__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>This field provides a link to the most recent Student record.</inlineHelpText>
        <label>Student</label>
        <referenceTo>Student__c</referenceTo>
        <relationshipLabel>Contacts</relationshipLabel>
        <relationshipName>Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <recordTypes>
        <fullName>Student</fullName>
        <active>true</active>
        <description>This record type is for students</description>
        <label>Student</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Student__c.object
<CustomObject>
    <fields>
        <fullName>Attendance__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Attendance</label>
        <precision>1</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>School__c</fullName>
        <inlineHelpText>Displays the name of the student&apos;s current SchoolForce school. You can click on the link to see the details of this school.</inlineHelpText>
        <label>School</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Students</relationshipLabel>
        <relationshipName>Students</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Student__c</fullName>
        <inlineHelpText>Displays the student&apos;s middle name.</inlineHelpText>
        <label>Student Middle Name</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <label>Student</label>
    <nameField>
        <label>Student Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Students</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Student_PG__c.object
<CustomObject>
    <fields>
        <fullName>Parent_Guardian_c__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Parent/Guardian (c)</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Students</relationshipLabel>
        <relationshipName>Student_PG</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Student__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Student</label>
        <referenceTo>Student__c</referenceTo>
        <relationshipLabel>Parents/Guardians</relationshipLabel>
        <relationshipName>Student_PG</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Student/PG</label>
    <nameField>
        <displayFormat>SPG-{000000}</displayFormat>
        <label>Student/PG ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Student/PG</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/Attendance_PGNotification.cls
global class Attendance_PGNotification implements Database.Batchable<sObject>,Database.Stateful{
	public String query;
	public String email;
	global Set<Id> uattendance = new Set<Id>();
	global Map<String, Map<String, String>> mNotificationText;

	global Attendance_PGNotification (String alerttype) {
		mNotificationText = core_SoqlUtils.getnotifymap(alerttype);
	}


	global database.querylocator start(Database.BatchableContext BC){
		return Database.getQueryLocator(query);
	}

	global void execute(Database.BatchableContext BC, List<sObject> scope){
		Set<ID> studs = new Set<ID>();
		for(sObject s : scope){
			Attendance__c uas = (Attendance__c) s;
			studs.add(uas.Student__c);
		}
		String pgQuery = core_SoqlUtils.getMainPGQuery()+' WHERE Student__c IN :studs';
		List<Student_PG__c> pgList = Database.query(pgQuery);
		Map<ID, List<Student_PG__c>> studIdToPG = new Map<ID, List<Student_PG__c>>();
		for(Student_PG__c pg: pgList){
			if(studIdToPG.containsKey(pg.Student__c)) studIdToPG.get(pg.Student__c).add(pg);
			else studIdToPG.put(pg.Student__c, new List<Student_PG__c>{pg});
		}

		for(sObject s : scope) {
    		Attendance__c uas = (Attendance__c ) s;
			//Query for Parents of Student who was absent. 
			if(studIdToPG.containsKey(uas.Student__c)){
   				for (Student_PG__c pgc: studIdToPG.get(uas.Student__c)) {
	        		if ((pgc.Parent_Guardian_c__r.Notify_via_Email__c == true && pgc.Parent_Guardian_c__r.Email != null) 
        				||
        				(pgc.Parent_Guardian_c__r.Notify_via_SMS__c == true && pgc.Parent_Guardian_c__r.Email_to_SMS_Address__c != null)) 
        				//only execute if parent requested notification
                	{
                		NotificationUtils.sendnotification sn;
	               		if (mNotificationText.containsKey(pgc.Parent_Guardian_c__r.Preferred_Language__c + pgc.Student__r.School__c))
                			sn = new NotificationUtils.sendnotification(pgc, mNotificationText.get(pgc.Parent_Guardian_c__r.Preferred_Language__c + pgc.Student__r.School__c));
                		else {sn = new NotificationUtils.sendnotification(pgc, mNotificationText.get('English' + pgc.Student__r.School__c));}
                		//And only set first alert true if they are notified by this process
                		uattendance.add(uas.Id);
                	}
        		}
			}
		}
	}// end execute   

	global void finish(Database.BatchableContext BC){
		List<Attendance__c> uupdateattendance = new List<Attendance__c> ();
		for (Id a : uattendance) {
			uupdateattendance.add(New Attendance__c (Id = a, Date_Time_of_Parental_Notification__c = system.now() ));
		}
		System.debug('\n\n uupdateattendance => ' + uupdateattendance + '\n');
		try {Database.update(uupdateattendance, false); }
		catch (Exception Ex) {
			System.debug(ex.getMessage());
		}
	} // end finish

}