objects/Attendance__c.object
<CustomObject>
    <description>This object will capture all student attendance.</description>
    <fields>
        <fullName>Student__c</fullName>
        <description>This is a lookup to the student record.</description>
        <inlineHelpText>This field provides a link to the Student record for the year. Do not update this field.</inlineHelpText>
        <label>Student</label>
        <referenceTo>Student__c</referenceTo>
        <relationshipLabel>Attendance</relationshipLabel>
        <relationshipName>Attendance</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Attendance</label>
    <nameField>
        <displayFormat>A-{0}</displayFormat>
        <label>Attendance ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Attendance</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Course__c.object
<CustomObject>
    <fields>
        <fullName>Include_in_section_snapshot__c</fullName>
        <defaultValue>true</defaultValue>
        <inlineHelpText>Select if you want SchoolForce to include the information for this course in the Section snapshots that are created in the End of Year Wizard</inlineHelpText>
        <label>Include in section snapshot</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Subject_Area_Lookup__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Select the applicable subject area for this course. You can use the subject area for reporting purposes as well as for cohort requirements.</inlineHelpText>
        <label>Subject Area Lookup</label>
        <referenceTo>Course__c</referenceTo>
        <relationshipLabel>Courses (Subject Area Lookup)</relationshipLabel>
        <relationshipName>Course</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Course</label>
    <nameField>
        <label>Course Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Courses</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/Picklist_Value__c.object
<CustomObject>
    <fields>
        <fullName>Setup__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Setup</label>
        <referenceTo>Setup__c</referenceTo>
        <relationshipLabel>Picklist Values</relationshipLabel>
        <relationshipName>Picklist_Values</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Picklist Value</label>
    <nameField>
        <label>Display Value</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Picklist Values</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Schedule_Template__c.object
<CustomObject>
    <fields>
        <fullName>Setup__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Setup</label>
        <referenceTo>Setup__c</referenceTo>
        <relationshipLabel>Schedule Templates</relationshipLabel>
        <relationshipName>Schedule_Templates</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Schedule Template</label>
    <nameField>
        <label>Schedule Template Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Schedule Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Section__c.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Check this box if the section is a currently active section</description>
        <inlineHelpText>Check this box if the section is a currently active section</inlineHelpText>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Course__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Select the course associated to the section you want to create.</inlineHelpText>
        <label>Course</label>
        <referenceTo>Course__c</referenceTo>
        <relationshipLabel>Sections</relationshipLabel>
        <relationshipName>Sections</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Section__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Recursive lookup for groups</description>
        <label>Section</label>
        <referenceTo>Section__c</referenceTo>
        <relationshipLabel>Groups in Section</relationshipLabel>
        <relationshipName>Sections1</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Section</label>
    <nameField>
        <label>Section Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sections</pluralLabel>
    <recordTypes>
        <fullName>Published</fullName>
        <active>true</active>
        <description>Sections that have been Published and are Viewable by Standard Users</description>
        <label>Published</label>
    </recordTypes>
    <recordTypes>
        <fullName>Unpublished</fullName>
        <active>true</active>
        <description>Unpublished Sections Used for Scheduler</description>
        <label>Unpublished</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Setup__c.object
<CustomObject>
    <description>This object is used to setup Schoolforce and is referenced in multiple pieces of code.  There should be one setup object per school.</description>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Is this school setup active for this school year?</inlineHelpText>
        <label>Active?</label>
        <type>Checkbox</type>
    </fields>
    <label>Setup</label>
    <nameField>
        <displayFormat>S-{0}</displayFormat>
        <label>Setup ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Setup</pluralLabel>
    <recordTypes>
        <fullName>Published</fullName>
        <active>true</active>
        <description>For Published Setups - Not Editable</description>
        <label>Published</label>
    </recordTypes>
    <recordTypes>
        <fullName>Unpublished</fullName>
        <active>true</active>
        <description>Default Setup Record prior to when Setup is published.</description>
        <label>Unpublished</label>
    </recordTypes>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/Snapshot_Log__c.object
<CustomObject>
    <fields>
        <fullName>Setup__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Setup</label>
        <referenceTo>Setup__c</referenceTo>
        <relationshipLabel>Snapshot Log</relationshipLabel>
        <relationshipName>Snapshot_Log</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Snapshot Log</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Snapshot ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Snapshot Log</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Snapshot_Summary__c.object
<CustomObject>
    <fields>
        <fullName>Free_Breakfasts__c</fullName>
        <label>Free Breakfasts</label>
        <precision>6</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Free_Lunches__c</fullName>
        <label>Free Lunches</label>
        <precision>6</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Full_Price_Breakfasts__c</fullName>
        <label>Full Price Breakfasts</label>
        <precision>6</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Full_Price_Lunches__c</fullName>
        <label>Full Price Lunches</label>
        <precision>6</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>In_School_Suspension_Days__c</fullName>
        <label>In School Suspension Days</label>
        <precision>6</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>In_School_Suspensions__c</fullName>
        <label>In School Suspensions</label>
        <precision>6</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Out_School_Suspension_Days__c</fullName>
        <label>Out of School Suspension Days</label>
        <precision>6</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Out_School_Suspensions__c</fullName>
        <label>Out of School Suspensions</label>
        <precision>4</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Reduced_Price_Breakfasts__c</fullName>
        <label>Reduced Price Breakfasts</label>
        <precision>6</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Reduced_Price_Lunches__c</fullName>
        <label>Reduced Price Lunches</label>
        <precision>6</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Student__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Student</label>
        <referenceTo>Student__c</referenceTo>
        <relationshipLabel>Snapshot Summaries</relationshipLabel>
        <relationshipName>Snapshot_Summaries</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Snapshot Summary</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Snapshot Summary ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Snapshot Summaries</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Staff__c.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <label>Staff</label>
    <nameField>
        <label>Staff Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Staff</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/Student__c.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>true</defaultValue>
        <inlineHelpText>Indicates whether or not this Student record is active. If checked, then this is the current Student record. If unchecked, this is an old Student record.</inlineHelpText>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Section__c</fullName>
        <inlineHelpText>Displays the student&apos;s current homeroom name or room number. This field can be used for reporting purposes.</inlineHelpText>
        <label>Current Homeroom</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Setup__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Displays the Setup record associated to this Student record. The Setup record defines the settings for the school in a specific school year.</inlineHelpText>
        <label>Setup</label>
        <referenceTo>Setup__c</referenceTo>
        <relationshipLabel>Students</relationshipLabel>
        <relationshipName>Students</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Student__c</fullName>
        <inlineHelpText>Displays the student&apos;s middle name.</inlineHelpText>
        <label>Student Middle Name</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <label>Student</label>
    <nameField>
        <label>Student Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Students</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Student_Section__c.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Section__c</fullName>
        <label>Section</label>
        <referenceTo>Section__c</referenceTo>
        <relationshipLabel>Student</relationshipLabel>
        <relationshipName>Student_Section</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Student__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Student</label>
        <referenceTo>Student__c</referenceTo>
        <relationshipLabel>Section</relationshipLabel>
        <relationshipName>Student_Section</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Student/Section</label>
    <nameField>
        <displayFormat>SS-{000000}</displayFormat>
        <label>Student/Section ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Student/Section</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/BatchSnapshotSchoolCalcs.cls
global class BatchSnapshotSchoolCalcs {
	
	global Snapshot_Log__c log {
		get; private set;
	}
	
	global Setup__c setup {
		get; private set;
	}
	
	global Date startDate {
		get; private set;
	}
	
	global Date endDate {
		get; private set;
	}
	
	global List<AggregateResult> studentAggregates {
		get; private set;
	}
	
	global Map<String, Integer> attendanceMap {
		get; private set;
	}
	
	global List<AggregateResult> classSizes {
		get; private set;
	}
	
	global static final String TOTAL_DAYS_KEY = 'totalDays';
	global static final String PRESENT_KEY = 'present';
	global static final String UNEXCUSED_ABSENT_KEY = 'unexcusedAbsences';
	global static final String EXCUSED_ABSENT_KEY = 'excusedAbsences';
	global static final String UNEXCUSED_TARDY_KEY = 'unexcusedTardies';
	global static final String EXCUSED_TARDY_KEY = 'excusedTardies';
	global static final String TOTAL_ATTENDANCE = 'totalAttendance';
	
	//US3508
	public static final Set<String> legalSectionRT = new Set<String>{'Gradebook Group', 'Published', 'Unpublished', 'Schedule Group'};
	
	global BatchSnapshotSchoolCalcs(){
	}
	
	global BatchSnapshotSchoolCalcs(Snapshot_Log__c someLog,
									Setup__c someSetup, 
									Date someStartDate, 
									Date someEndDate) {
		initialize(someLog, someSetup, someStartDate, someEndDate);
	}
	
	global void initialize(Snapshot_Log__c someLog,
							Setup__c someSetup, 
							Date someStartDate, 
							Date someEndDate) {
		log = someLog;
		setup = someSetup;
		startDate = someStartDate;
		endDate = someEndDate;
		studentAggregates = getStudentAggregates(log.id);
		classSizes = getClassSizes(setup.Id);	
		 //PU: Hitting Query row limits,will be fixed later
        //attendanceMap = getAttendanceMap(setup.id, startDate, endDate);	
	}
	
	global List<AggregateResult> getClassSizes(Id setupId) {
		List<AggregateResult> results = [select 
											count(Id) studentCount, 
											Section__c section
										from Student_Section__c 
										where 
											Student__r.Setup__c = :setupId and 
											Section__r.Course__r.Include_in_section_snapshot__c = true and
											//US3508
											section__r.RecordType.Name IN: legalSectionRT and
											Active__c = true
										group by Section__c];
		return results;
	}
	
	global List<AggregateResult> getStudentAggregates(ID logId) {
		List<AggregateResult> results = [SELECT 
											SUM(Free_Breakfasts__c) freeBreakfasts,
											SUM(Full_Price_Breakfasts__c) fullBreakfasts,
											SUM(Reduced_Price_Breakfasts__c) reducedBreakfasts,
											SUM(Free_Lunches__c) freeLunches,
											SUM(Full_Price_Lunches__c) fullLunches,
											SUM(Reduced_Price_Lunches__c) reducedLunches,
											SUM(In_School_Suspensions__c) inSchoolSusp,
											SUM(Out_School_Suspensions__c) outSchoolSusp,
											SUM(In_School_Suspension_Days__c) inSchoolDays,
											SUM(Out_School_Suspension_Days__c) outSchoolDays,
											SUM(Positive_Behavior__c) positiveIncidents,
											SUM(Neutral_Behavior__c) neutralIncidents,
											SUM(Negative_Behavior__c) negativeIncidents
										FROM Snapshot_Summary__c
										WHERE Snapshot_ID__c = :logId];
	    return results;
	}
	
	global Map<String, Integer> getAttendanceMap(ID setupId, 
														Date someStartDate,
														Date someEndDate) {
		/*PU Code hitting no. of query rows limits 
		Integer totalAttendance = 0;
		Map<String, Integer> results = new Map<String, Integer>();
		List<AggregateResult> dayCount = [select count(id) days
											from Schedule_Day__c 
											where Schedule_Template__r.Has_Class__c = true and 
												Schedule_Template__r.Setup__c = :setupId and 
												Day__c >= :someStartDate and
												Day__c <= :someEndDate];
		if (dayCount.size() > 0) {
			results.put(TOTAL_DAYS_KEY, (Integer)dayCount.get(0).get('days'));
		}												

		List<AggregateResult> attend = [select Picklist_Value__r.Category__c cat, 
												Picklist_Value__r.Is_Unexcused__c unexcused, 
												Picklist_Value__r.Is_Tardy__c tardy, 
												count(id) cnt 
										from Attendance__c
										where Student__r.Setup__c = :setupId and
												Session_Date__c >= :someStartDate and
												Session_Date__c <= :someEndDate and
												Daily__c = true and 
												isDeleted = false
										group by Picklist_Value__r.Category__c, 
												Picklist_Value__r.Is_Unexcused__c, 
												Picklist_Value__r.Is_Tardy__c];

		for (AggregateResult ar : attend) {
			Integer cnt = (Integer)ar.get('cnt');
			String cat = (String) ar.get('cat');
			Boolean unexcused = (Boolean) ar.get('unexcused');
			Boolean tardy = (Boolean) ar.get('tardy');
			totalAttendance += cnt;
			if (cat == 'Present') {
				results.put(PRESENT_KEY, cnt);
			} else if (cat == 'Absent') {
				if (unexcused == true) {
					results.put(UNEXCUSED_ABSENT_KEY, cnt);
				}
				else {
					results.put(EXCUSED_ABSENT_KEY,  cnt);
				}
			} else if (cat == 'Partial') {
				if (tardy == true) {
					if (unexcused == true) {
						results.put(UNEXCUSED_TARDY_KEY, cnt);
					}
					else {
						results.put(EXCUSED_TARDY_KEY, cnt);
					}
				}				
			}
		}
		results.put(TOTAL_ATTENDANCE, totalAttendance);
		return results;			*/
		return null;									
	}
	
	global Decimal zeroIfNull(Decimal num) {
		if (num == null) {
			return 0;
		}
		else {
			return num;
		}
	}
	
	
	global Decimal getStaffCount(Id schoolId) {
		List<AggregateResult> results = [select count(id) staffCount
										from Staff__c
										where Organization__c = :schoolId and
										Active__c = true and
										Instructional_Staff__c = true];
		if (results != null && results.size() > 0) {
			return zeroIfNull((Decimal)results.get(0).get('staffCount'));
		}
		else {
			return 0;
		}
	}
	
	global Decimal avgDailyAttendance() {
		/*PU Code hitting no. of query rows limits
		Decimal present = zeroIfNull(attendanceMap.get(PRESENT_KEY));
		Decimal total = zeroIfNull(attendanceMap.get(TOTAL_DAYS_KEY));
		if (total > 0) {
			return present/total;
		}
		else {
			return 0;
		}*/
		return 0;
		
	}
	
	global Decimal percentUnexcusedAbsences() {
		/*PU Code hitting no. of query rows limits
		Decimal unexcused = zeroIfNull(attendanceMap.get(UNEXCUSED_ABSENT_KEY));
		Decimal total = zeroIfNull(attendanceMap.get(TOTAL_ATTENDANCE));
		if (total > 0) {
			return unexcused/total;
		}
		else {
			return 0;
		}*/
		return 0;
	}

	global Decimal percentExcusedAbsences() {
		/*PU Code hitting no. of query rows limits
		Decimal excused = zeroIfNull(attendanceMap.get(EXCUSED_ABSENT_KEY));
		Decimal total = zeroIfNull(attendanceMap.get(TOTAL_ATTENDANCE));
		if (total > 0) {
			return excused/total;
		}
		else {
			return 0;
		}*/
		return 0;
	}

	global Decimal percentUnexcusedTardies() {
		/*PU Code hitting no. of query rows limits
		Decimal unexcused = zeroIfNull(attendanceMap.get(UNEXCUSED_TARDY_KEY));
		Decimal total = zeroIfNull(attendanceMap.get(TOTAL_ATTENDANCE));
		if (total > 0) {
			return unexcused/total;
		}
		else {
			return 0;
		}*/
		return 0;
	}

	global Decimal percentExcusedTardies() {
		/*PU Code hitting no. of query rows limits
		Decimal excused = zeroIfNull(attendanceMap.get(EXCUSED_TARDY_KEY));
		Decimal total = zeroIfNull(attendanceMap.get(TOTAL_ATTENDANCE));
		if (total > 0) {
			return excused/total;
		}
		else {
			return 0;
		}*/
		return 0;
	}
	
	global Decimal avgClassSize() {
		Decimal students = 0;
		
		for (AggregateResult ar : classSizes) {
			students += zeroIfNull((Decimal)ar.get('studentCount'));
		}
		
		if (classSizes != null && classSizes.size() > 0) {
			return students/classSizes.size();
		}
		else {
			return 0;
		} 
	}
	
	global Decimal studentTeacherRatio(Decimal studentCount) {
		Decimal staffCount = getStaffCount(setup.School__c);
		if (staffCount == 0) {
			return 0;
		}
		else {
			return studentCount/staffCount;
		}
	}
	
	global Setup__c findPreviousSetup(Setup__c currentSetup) {
		Setup__c prevSetup = [select Id 
								from Setup__c 
								where School__c = :currentSetup.School__c and
								Year__r.End_Date__c <> null and 
								Year__r.End_Date__c < :currentSetup.Year__r.Date_Start_Date__c 
								order by Year__r.End_Date__c desc limit 1];
		return prevSetup;
	}
	
	global List<Student__c> getEligibleForEnrollment(Setup__c setup) {
		List<Student__c> students = [select Individual__c
									from Student__c
									where Eligible_For_Enrollment__c = true and
									Setup__c = :setup.id];
		return students;
	}
	
	global Decimal getEnrollmentPercent(List<Student__c> students, Setup__c currSetup) {
		Decimal enrollment = 0;

		if (students != null && students.size() > 0) {
			List<ID> ids = new List<ID>();
			for (Student__c s : students) {
				ids.add(s.Individual__c);
			} 
			
			AggregateResult ar = [select count(id) c
									from Student__c 
									where Setup__c = :currSetup.id and
									Active__c = true and
									Individual__c in :ids];
			Decimal reenrollCount = (Decimal)ar.get('c');
			enrollment = reenrollCount/students.size();
		}
		
		return enrollment;
	}

}