objects/Attendance__c.object
<CustomObject>
    <description>This object will capture all student attendance.</description>
    <fields>
        <fullName>Picklist_Value__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Displays the value that users select to describe the student&apos;s attendance using the Attendance tab or Attendance Wizard. These picklist options are chosen by your school.</inlineHelpText>
        <label>Status</label>
        <referenceTo>Picklist_Value__c</referenceTo>
        <relationshipLabel>Attendance</relationshipLabel>
        <relationshipName>Attendance</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Session__c</fullName>
        <description>This is a lookup to the sessions that attendance is being captured for.</description>
        <inlineHelpText>Displays the date and time of the Session. Do not update this field.</inlineHelpText>
        <label>Session</label>
        <referenceTo>Session__c</referenceTo>
        <relationshipLabel>Attendance</relationshipLabel>
        <relationshipName>Attendance</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Student__c</fullName>
        <description>This is a lookup to the student record.</description>
        <inlineHelpText>This field provides a link to the Student record for the year. Do not update this field.</inlineHelpText>
        <label>Student</label>
        <referenceTo>Student__c</referenceTo>
        <relationshipLabel>Attendance</relationshipLabel>
        <relationshipName>Attendance</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Attendance</label>
    <nameField>
        <displayFormat>A-{0}</displayFormat>
        <label>Attendance ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Attendance</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Course__c.object
<CustomObject>
    <fields>
        <fullName>Include_in_section_snapshot__c</fullName>
        <defaultValue>true</defaultValue>
        <inlineHelpText>Select if you want SchoolForce to include the information for this course in the Section snapshots that are created in the End of Year Wizard</inlineHelpText>
        <label>Include in section snapshot</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Subject_Area_Lookup__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Select the applicable subject area for this course. You can use the subject area for reporting purposes as well as for cohort requirements.</inlineHelpText>
        <label>Subject Area Lookup</label>
        <referenceTo>Course__c</referenceTo>
        <relationshipLabel>Courses (Subject Area Lookup)</relationshipLabel>
        <relationshipName>Course</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Course</label>
    <nameField>
        <label>Course Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Courses</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/Picklist_Value__c.object
<CustomObject>
    <fields>
        <fullName>Setup__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Setup</label>
        <referenceTo>Setup__c</referenceTo>
        <relationshipLabel>Picklist Values</relationshipLabel>
        <relationshipName>Picklist_Values</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Picklist Value</label>
    <nameField>
        <label>Display Value</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Picklist Values</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Section__c.object
<CustomObject>
    <fields>
        <fullName>Course__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Select the course associated to the section you want to create.</inlineHelpText>
        <label>Course</label>
        <referenceTo>Course__c</referenceTo>
        <relationshipLabel>Sections</relationshipLabel>
        <relationshipName>Sections</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>School__c</fullName>
        <label>School</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Sections</relationshipLabel>
        <relationshipName>Sections</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Section__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Recursive lookup for groups</description>
        <label>Section</label>
        <referenceTo>Section__c</referenceTo>
        <relationshipLabel>Groups in Section</relationshipLabel>
        <relationshipName>Sections1</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Section</label>
    <nameField>
        <label>Section Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sections</pluralLabel>
    <recordTypes>
        <fullName>Published</fullName>
        <active>true</active>
        <description>Sections that have been Published and are Viewable by Standard Users</description>
        <label>Published</label>
    </recordTypes>
    <recordTypes>
        <fullName>Unpublished</fullName>
        <active>true</active>
        <description>Unpublished Sections Used for Scheduler</description>
        <label>Unpublished</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Section_Grade__c.object
<CustomObject>
    <fields>
        <fullName>Section_Weighted_GPA__c</fullName>
        <label>Section Weighted GPA</label>
        <precision>4</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Section__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Section</label>
        <referenceTo>Section__c</referenceTo>
        <relationshipLabel>Section Grades</relationshipLabel>
        <relationshipName>Section_Grades</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Student_Section__c</fullName>
        <label>Student/Section</label>
        <referenceTo>Student_Section__c</referenceTo>
        <relationshipLabel>Section Grades</relationshipLabel>
        <relationshipName>Section_Grades</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>isFinal__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Final?</label>
        <type>Checkbox</type>
    </fields>
    <label>Section Grade</label>
    <nameField>
        <displayFormat>SECG-{000}</displayFormat>
        <label>Section Grade Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Section Grades</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Session__c.object
<CustomObject>
    <description>This object captures the daily session for each section.</description>
    <fields>
        <fullName>Section__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This is a lookup to the section that the session belongs to.</description>
        <label>Section</label>
        <referenceTo>Section__c</referenceTo>
        <relationshipLabel>Sessions</relationshipLabel>
        <relationshipName>Sessions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Start_DateTime__c</fullName>
        <description>Date and time that session starts</description>
        <label>Start Date Time</label>
        <type>DateTime</type>
    </fields>
    <label>Session</label>
    <nameField>
        <label>Session Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sessions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Setup__c.object
<CustomObject>
    <description>This object is used to setup Schoolforce and is referenced in multiple pieces of code.  There should be one setup object per school.</description>
    <fields>
        <fullName>School__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>School</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1 OR 2</booleanFilter>
            <filterItems>
                <field>Account.RecordType.Name</field>
                <operation>equals</operation>
                <value>School</value>
            </filterItems>
            <filterItems>
                <field>Account.RecordType.Name</field>
                <operation>equals</operation>
                <value>Summer School</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Setup</relationshipLabel>
        <relationshipName>Setup</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Setup</label>
    <nameField>
        <displayFormat>S-{0}</displayFormat>
        <label>Setup ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Setup</pluralLabel>
    <recordTypes>
        <fullName>Published</fullName>
        <active>true</active>
        <description>For Published Setups - Not Editable</description>
        <label>Published</label>
    </recordTypes>
    <recordTypes>
        <fullName>Unpublished</fullName>
        <active>true</active>
        <description>Default Setup Record prior to when Setup is published.</description>
        <label>Unpublished</label>
    </recordTypes>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/Staff_Section__c.object
<CustomObject>
    <fields>
        <fullName>School__c</fullName>
        <formula>Section__r.School__r.Id</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>The School related to this Section</inlineHelpText>
        <label>School</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Section__c</fullName>
        <label>Section</label>
        <referenceTo>Section__c</referenceTo>
        <relationshipLabel>Staff</relationshipLabel>
        <relationshipName>Staff_Section</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Staff/Section</label>
    <nameField>
        <displayFormat>SfS-{000000}</displayFormat>
        <label>Staff/Section ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Staff/Section</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Student__c.object
<CustomObject>
    <fields>
        <fullName>School__c</fullName>
        <inlineHelpText>Displays the name of the student&apos;s current SchoolForce school. You can click on the link to see the details of this school.</inlineHelpText>
        <label>School</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Students</relationshipLabel>
        <relationshipName>Students</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Section__c</fullName>
        <inlineHelpText>Displays the student&apos;s current homeroom name or room number. This field can be used for reporting purposes.</inlineHelpText>
        <label>Current Homeroom</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Setup__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Displays the Setup record associated to this Student record. The Setup record defines the settings for the school in a specific school year.</inlineHelpText>
        <label>Setup</label>
        <referenceTo>Setup__c</referenceTo>
        <relationshipLabel>Students</relationshipLabel>
        <relationshipName>Students</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Student__c</fullName>
        <inlineHelpText>Displays the student&apos;s middle name.</inlineHelpText>
        <label>Student Middle Name</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <label>Student</label>
    <nameField>
        <label>Student Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Students</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Student_Section__c.object
<CustomObject>
    <fields>
        <fullName>School__c</fullName>
        <formula>Student__r.School__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>School</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Section__c</fullName>
        <label>Section</label>
        <referenceTo>Section__c</referenceTo>
        <relationshipLabel>Student</relationshipLabel>
        <relationshipName>Student_Section</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Student__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Student</label>
        <referenceTo>Student__c</referenceTo>
        <relationshipLabel>Section</relationshipLabel>
        <relationshipName>Student_Section</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Student/Section</label>
    <nameField>
        <displayFormat>SS-{000000}</displayFormat>
        <label>Student/Section ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Student/Section</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/BatchSnapshotSectionCalcs.cls
global class BatchSnapshotSectionCalcs {
	
	global static final String TOTAL_DAYS_KEY = 'totalDays';
	global static final String PRESENT_KEY = 'present';
	global static final String UNEXCUSED_ABSENT_KEY = 'unexcusedAbsences';
	global static final String EXCUSED_ABSENT_KEY = 'excusedAbsences';
	global static final String UNEXCUSED_TARDY_KEY = 'unexcusedTardies';
	global static final String EXCUSED_TARDY_KEY = 'excusedTardies';
	global static final String TOTAL_ATTENDANCE = 'totalAttendance';
	
	//US3508
	public static final Set<String> legalSectionRT = new Set<String>{'Gradebook Group', 'Published', 'Unpublished', 'Schedule Group'};
	
	global Setup__c setup {
		get; private set;
	}
	
	global Date startDate {
		get; private set;
	}
	
	global Date endDate {
		get; private set;
	}
	
	global Map<ID, Map<String, Integer>> attendanceMap {
		get; private set;
	}
	
	global Map<ID, Decimal> gpaMap {
		get; private set;
	}
	
	global Map<ID, List<Staff_Section__c>> staffMap {
		get; private set;
	}
	
	global BatchSnapshotSectionCalcs(){
	}
	
	global BatchSnapshotSectionCalcs(Setup__c someSetup, Date someStartDate, Date someEndDate) {
		initialize(someSetup, someStartDate, someEndDate);
	}
	
	global void initialize(Setup__c someSetup, Date someStartDate, Date someEndDate) {
		setup = someSetup;
		startDate = someStartDate;
		endDate = someEndDate;
		attendanceMap = getAttendanceMap(setup, startDate, endDate);
		gpaMap = getGPAMap(setup.id, startDate, endDate);
		staffMap = getAssignedStaff(setup.School__c);
	}
	
	global Map<ID, Decimal> getGPAMap(ID setupId, Date sdate, Date edate) {
		Map<ID, Decimal> gMap = new Map<ID, Decimal>();
		List<AggregateResult> results = [select Student_Section__r.Section__c section,
											AVG(Section_Weighted_GPA__c) avgGpa 
										from Section_Grade__c
										where Student_Section__r.Student__r.Setup__c = :setupId and
											Student_Section__r.Section__r.Course__r.Include_in_section_snapshot__c = true 
											//This is not used at all... in anywhere
											//AND isFinal__c = true
										group by Student_Section__r.Section__c];
		for (AggregateResult ar : results) {
			gMap.put((ID)ar.get('section'), (Decimal)ar.get('avgGpa'));
		}
		
		return gMap;
	}
	
	global Map<ID, List<SObject>> splitByField(List<SObject> alist, String fieldName) {
		ID lastValue;
		List<SObject> newList;
		Map<ID, List<SObject>> smap = new Map<ID, List<SObject>>();
		
		for (SObject ag : alist) {
			if ((ID)ag.get(fieldName) != lastValue) {
				if (lastValue != null) {
					smap.put(lastvalue, newList);
				}
				lastvalue = (ID)ag.get(fieldName);
				newList = new List<SObject>();
			}
			
			newList.add(ag);
		}
		if (lastValue != null) {
			smap.put(lastvalue, newList);
		}
		
		return smap;
	}
	
	global Map<String, Integer> calcAttendanceMap(List<AggregateResult> dayCount,
													List<AggregateResult> attend) {
		Integer totalAttendance = 0;
		Map<String, Integer> results = new Map<String, Integer>();

		if (dayCount.size() > 0) {
			results.put(TOTAL_DAYS_KEY, (Integer)dayCount.get(0).get('days'));
		}												
														
		for (AggregateResult ar : attend) {
			Integer cnt = (Integer)ar.get('cnt');
			String cat = (String) ar.get('cat');
			Boolean unexcused = (Boolean) ar.get('unexcused');
			Boolean tardy = (Boolean) ar.get('tardy');
			totalAttendance += cnt;
			if (cat == 'Present') {
				results.put(PRESENT_KEY, cnt);
			} else if (cat == 'Absent') {
				if (unexcused == true) {
					results.put(UNEXCUSED_ABSENT_KEY, cnt);
				}
				else {
					results.put(EXCUSED_ABSENT_KEY,  cnt);
				}
			} else if (cat == 'Partial') {
				if (tardy == true) {
					if (unexcused == true) {
						results.put(UNEXCUSED_TARDY_KEY, cnt);
					} 
					else {
						results.put(EXCUSED_TARDY_KEY, cnt);
					}
				}				
			}
		}
		results.put(TOTAL_ATTENDANCE, totalAttendance);
		return results;						 						
	}
	
	global Map<ID, List<AggregateResult>> getSplitDayCount(ID schoolId, Date sdate, Date edate) {
		List<AggregateResult> dcList = [select Section__c section, 
											count(id) days
										from Session__c 
										where Section__r.School__c = :schoolId and
											Section__r.Course__r.Include_in_section_snapshot__c = true and 
											Start_DateTime__C >= :sdate and
											Start_DateTime__c <= :edate
										group by Section__c];
		Map<ID, List<AggregateResult>> dcMap = splitByField(dcList, 'section');

		return dcMap;		
	}

	global Map<ID, List<AggregateResult>> getSplitAttendance(ID setupId, Date sdate, Date edate) {
		List<AggregateResult> atList = [select Session__r.Section__c section,
											Picklist_Value__r.Category__c cat, 
											Picklist_Value__r.Is_Unexcused__c unexcused, 
											Picklist_Value__r.Is_Tardy__c tardy, 
											count(id) cnt 
										from Attendance__c
										where Student__r.Setup__c = :setupId and
											Session__r.Start_DateTime__c >= :sdate and
											Session__r.Start_DateTime__c <= :edate and
											Session__r.Section__r.Course__r.Include_in_section_snapshot__c = true and
											Daily__c = false and 
											isDeleted = false
										group by Session__r.Section__c,
											Picklist_Value__r.Category__c, 
											Picklist_Value__r.Is_Unexcused__c, 
											Picklist_Value__r.Is_Tardy__c];
		Map<ID, List<AggregateResult>> atMap = splitByField(atList, 'section');
		
		return atMap;
	}

	global Map<ID, Map<String, Integer>> getAttendanceMap(Setup__c someSetup, Date sdate, Date edate) {
		Integer totalAttendance = 0;
		Map<ID, Map<String, Integer>> results = new Map<ID, Map<String, Integer>>();
		Map<ID, List<AggregateResult>> dcMap = getSplitDayCount(someSetup.School__c, sdate, edate);
		Map<ID, List<AggregateResult>> atMap = getSplitAttendance(someSetup.id, sdate, edate);

		for (ID key : dcMap.keySet()) {
			List<AggregateResult> dc = dcMap.get(key);
			List<AggregateResult> attnd = atMap.get(key);
			if (dc != null && attnd != null && dc.size() > 0 && attnd.size() > 0) {
				Map<String, Integer> rmap = calcAttendanceMap(dc, attnd);
				results.put(key, rmap);
			}
		}

		return results;												
	}
	
	global Decimal zeroIfNull(Decimal num) {
		if (num == null) {
			return 0;
		}
		else {
			return num;
		}
	}
	
	global Decimal getAttendStat(ID sectionId, String key) {
		Map<String, Integer> amap = attendanceMap.get(sectionId);
		if (amap == null) {
			system.debug('amap is null');
			return -1;
		}
		else {
			return zeroIfNull(amap.get(key));
		}
	}
	
	global Decimal avgAttendance(ID sectionId) {
		Decimal present = getAttendStat(sectionId, PRESENT_KEY);
		Decimal total = getAttendStat(sectionId, TOTAL_DAYS_KEY);
		if (total > 0) {
			return present/total;
		}
		else {
			return 0;
		}
	}
	
	global Decimal percentPresent(ID sectionId) {
		Decimal present = getAttendStat(sectionId, PRESENT_KEY);
		Decimal total = getAttendStat(sectionId, TOTAL_ATTENDANCE);
		if (total > 0) {
			return (present/total)*100;
		}
		else {
			return 0;
		}
	}

	global Decimal percentUnexcusedAbsences(ID sectionId) {
		Decimal unexcused = getAttendStat(sectionId, UNEXCUSED_ABSENT_KEY);
		Decimal total = getAttendStat(sectionId, TOTAL_ATTENDANCE);
		if (total > 0) {
			return (unexcused/total)*100;
		}
		else {
			return 0;
		}
	}

	global Decimal percentExcusedAbsences(ID sectionId) {
		Decimal excused = getAttendStat(sectionId, EXCUSED_ABSENT_KEY);
		Decimal total = getAttendStat(sectionId, TOTAL_ATTENDANCE);
		if (total > 0) {
			return (excused/total)*100;
		}
		else {
			return 0;
		}
	}

	global Decimal percentUnexcusedTardies(ID sectionId) {
		Decimal unexcused = getAttendStat(sectionId, UNEXCUSED_TARDY_KEY);
		Decimal total = getAttendStat(sectionId, TOTAL_ATTENDANCE);
		if (total > 0) {
			return (unexcused/total)*100;
		}
		else {
			return 0;
		}
	}

	global Decimal percentExcusedTardies(ID sectionId) {
		Decimal excused = getAttendStat(sectionId, EXCUSED_TARDY_KEY);
		Decimal total = getAttendStat(sectionId, TOTAL_ATTENDANCE);
		if (total > 0) {
			return (excused/total)*100;
		}
		else {
			return 0;
		}
	}
	
	global Decimal avgGPA(ID sectionId) { 

		Decimal gpa = gpaMap.get(sectionId);
		if (gpa == null) {
			return 0;
		}
		else {
			return gpa;
		}	
	}

	global Map<ID, List<Staff_Section__c>> getAssignedStaff(ID schoolId) {
		List<Staff_Section__c> dcList = [select Section__c,
											Staff__r.First_Name_Staff__c,
											Staff__r.Middle_Name_Staff__c,
											Staff__r.Staff_Last_Name__c 
										from Staff_Section__c 
										where Staff__r.Organization__c = :schoolId and 
											Staff__r.Instructional_Staff__c = true and
											Section__r.Course__r.Include_in_section_snapshot__c = true and
											//US3508
											Section__r.RecordType.Name IN: legalSectionRT and
											Staff__r.Active__c = true
										order by Section__c,
											Staff__r.Staff_Last_Name__c, 
											Staff__r.First_Name_Staff__c,
											Staff__r.Middle_Name_Staff__c];
		Map<ID, List<Staff_Section__c>> dcMap = splitByField(dcList, 'Section__c');
		return dcMap;
	}
	
	global String getStaff(ID sectionId) {
		List<Staff_Section__c> staffList = staffMap.get(sectionId);
		String staff = '';
		Boolean firstTime = true;
		
		if (staffList != null && staffList.size() > 0) {
			for (Staff_Section__c s : staffList) {
				if (!firstTime) {
					staff = staff + ', ';
				}
				firstTime = false;
				if (StringUtils.blankNull(s.Staff__r.First_Name_Staff__c).length() > 0) {
					staff = staff + s.Staff__r.First_Name_Staff__c + ' ';
				}
				
				if (StringUtils.blankNull(s.Staff__r.Middle_Name_Staff__c).length() > 0) {
					staff = staff + s.Staff__r.Middle_Name_Staff__c + ' ';
				}
	
				if (StringUtils.blankNull(s.Staff__r.Staff_Last_Name__c).length() > 0) {
					staff = staff + s.Staff__r.Staff_Last_Name__c;
				}
			}
		}
		
		return staff;
	}	

}