objects/Attendance__c.object
<CustomObject>
    <description>This object will capture all student attendance.</description>
    <fields>
        <fullName>Picklist_Value__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Displays the value that users select to describe the student&apos;s attendance using the Attendance tab or Attendance Wizard. These picklist options are chosen by your school.</inlineHelpText>
        <label>Status</label>
        <referenceTo>Picklist_Value__c</referenceTo>
        <relationshipLabel>Attendance</relationshipLabel>
        <relationshipName>Attendance</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Student__c</fullName>
        <description>This is a lookup to the student record.</description>
        <inlineHelpText>This field provides a link to the Student record for the year. Do not update this field.</inlineHelpText>
        <label>Student</label>
        <referenceTo>Student__c</referenceTo>
        <relationshipLabel>Attendance</relationshipLabel>
        <relationshipName>Attendance</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Attendance</label>
    <nameField>
        <displayFormat>A-{0}</displayFormat>
        <label>Attendance ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Attendance</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Grade__c.object
<CustomObject>
    <fields>
        <fullName>Section__c</fullName>
        <formula>CASESAFEID(Student_Section__r.Section__c)</formula>
        <label>Section</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Student__c</fullName>
        <label>Student</label>
        <referenceTo>Student__c</referenceTo>
        <relationshipLabel>Grades</relationshipLabel>
        <relationshipName>Grades</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Grade</label>
    <nameField>
        <displayFormat>G-{0}</displayFormat>
        <label>Grade Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Grades</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Notification__c.object
<CustomObject>
    <description>This object captures notification data which allows administrators to schedule system notifications.</description>
    <fields>
        <fullName>Picklist_Value__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Status</label>
        <referenceTo>Picklist_Value__c</referenceTo>
        <relationshipLabel>Notifications</relationshipLabel>
        <relationshipName>Notifications</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Setup__c</fullName>
        <description>This is a lookup to the setup object that the notifications are for.</description>
        <label>Setup</label>
        <referenceTo>Setup__c</referenceTo>
        <relationshipLabel>Notifications</relationshipLabel>
        <relationshipName>Notifications</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Notification</label>
    <nameField>
        <label>Notification Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Notifications</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Notification_Settings__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <fields>
        <fullName>Display_Name__c</fullName>
        <description>Display name recipient will see when receiving notification from Schoolforce</description>
        <label>Display Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Reply_To__c</fullName>
        <description>Sets the reply To for notifications from Schoolforce to Parent/Guardians</description>
        <label>Reply To</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Subject__c</fullName>
        <description>Subject of the notification</description>
        <label>Subject</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>Notification Settings</label>
</CustomObject>

objects/Picklist_Value__c.object
<CustomObject>
    <fields>
        <fullName>Setup__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Setup</label>
        <referenceTo>Setup__c</referenceTo>
        <relationshipLabel>Picklist Values</relationshipLabel>
        <relationshipName>Picklist_Values</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Attendance</fullName>
                </value>
                <value>
                    <fullName>Time</fullName>
                </value>
                <value>
                    <fullName>Assignment</fullName>
                </value>
                <value>
                    <fullName>Grade Scale</fullName>
                </value>
                <value>
                    <fullName>Homework</fullName>
                </value>
                <value>
                    <fullName>Behavior Type</fullName>
                </value>
                <value>
                    <fullName>Behavior Consequence</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Picklist Value</label>
    <nameField>
        <label>Display Value</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Picklist Values</pluralLabel>
    <recordTypes>
        <fullName>Attendance</fullName>
        <active>true</active>
        <label>Attendance</label>
    </recordTypes>
    <recordTypes>
        <fullName>Time</fullName>
        <active>true</active>
        <label>Time</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Section__c.object
<CustomObject>
    <fields>
        <fullName>Daily_Attendance__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This should be checked if this section is recording daily attendance rather than sectional attendance.</description>
        <inlineHelpText>Select if staff members will take daily attendance in this section. The section will display in the All Day grid and you will not be able to add it to a specific period in your schedule. You must also select the Record Attendance check box.</inlineHelpText>
        <label>Daily Attendance?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Record_Attendance__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Should attendance be recorded for this section?</description>
        <inlineHelpText>Leave this check box selected if staff members will take daily or sectional attendance in this section. This field determines whether or not this section is available in the Attendance Wizard.</inlineHelpText>
        <label>Record Attendance</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Section__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Recursive lookup for groups</description>
        <label>Section</label>
        <referenceTo>Section__c</referenceTo>
        <relationshipLabel>Groups in Section</relationshipLabel>
        <relationshipName>Sections1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Subject__c</fullName>
        <label>Subject</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Math</fullName>
                </value>
                <value>
                    <fullName>Science</fullName>
                </value>
                <value>
                    <fullName>Reading</fullName>
                </value>
                <value>
                    <fullName>Writing</fullName>
                </value>
                <value>
                    <fullName>Social Studies</fullName>
                </value>
                <value>
                    <fullName>Spanish</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <description>Section or Standard Group or Custom Group</description>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Section</fullName>
                </value>
                <value>
                    <fullName>Standard Group</fullName>
                </value>
                <value>
                    <fullName>Custom Group</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Section</label>
    <nameField>
        <label>Section Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sections</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Student__c.object
<CustomObject>
    <fields>
        <fullName>Attendance__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Attendance</label>
        <precision>1</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Section__c</fullName>
        <inlineHelpText>Displays the student&apos;s current homeroom name or room number. This field can be used for reporting purposes.</inlineHelpText>
        <label>Current Homeroom</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Setup__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Displays the Setup record associated to this Student record. The Setup record defines the settings for the school in a specific school year.</inlineHelpText>
        <label>Setup</label>
        <referenceTo>Setup__c</referenceTo>
        <relationshipLabel>Students</relationshipLabel>
        <relationshipName>Students</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Student__c</fullName>
        <inlineHelpText>Displays the student&apos;s middle name.</inlineHelpText>
        <label>Student Middle Name</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <label>Student</label>
    <nameField>
        <label>Student Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Students</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Value__c.object
<CustomObject>
    <fields>
        <fullName>Communication_Type__c</fullName>
        <label>Communication Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Email</fullName>
                </value>
                <value>
                    <fullName>SMS</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Language__c</fullName>
        <label>Language</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>English</fullName>
                    <default>true</default>
                    <label>English</label>
                </value>
                <value>
                    <fullName>Spanish</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Setup__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Setup</label>
        <referenceTo>Setup__c</referenceTo>
        <relationshipLabel>Values</relationshipLabel>
        <relationshipName>Values</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Text_Alert__c</fullName>
        <label>Text Alert</label>
        <length>32000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Homework Alerts</fullName>
                </value>
                <value>
                    <fullName>Attendance Alerts</fullName>
                </value>
                <value>
                    <fullName>Attendance Threshold Alerts</fullName>
                </value>
                <value>
                    <fullName>Tardy Alerts</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Value</label>
    <nameField>
        <label>Values Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Values</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/Test_Attendance_PGNotify.cls
@isTest
private class Test_Attendance_PGNotify{

	static List<Picklist_Value__c> pvl;
	static List<Notification__c> n;
	static testMethod void test_AttendancePNotifier(){
		core_triggerUtils.studentTriggerUpdate(false); 
		testDataSetupUtil_v2.setUPCoreData(5);
		testDataSetupUtil_v2.setUPStaffData(5);
		testDataSetupUtil_v2.setUPStudentData(5);

		Date startDate = testDataSetupUtil_v2.semester.Date_Start_Date__c;
		for (Section__c sect: testDataSetupUtil_v2.sectionsList){
			for(integer i=0;i<10;i++){
				testDataSetupUtil_v2.semester.Date_Start_Date__c = testDataSetupUtil_v2.semester.Date_Start_Date__c.addDays(i);
				if (!sect.daily_attendance__c) testDataSetupUtil_v2.getSessions(10,testDataSetupUtil_v2.semester,sect.Id, i);
				else testDataSetupUtil_v2.getSessions(10,testDataSetupUtil_v2.semester,sect.Id,  null);
				testDataSetupUtil_v2.semester.Date_Start_Date__c = startDate;
			}
		}
		
		pvl = testDataSetupUtil_v2.createDefaultAttendanceTypes(testDataSetupUtil_v2.activeSetup);
		
		List <Value__c> tvalues = new List<Value__c> ();
		tvalues.add(new Value__c (Setup__c = testDataSetupUtil_v2.activeSetUp.id, Communication_Type__c = 'SMS', Language__c = 'English', Type__c = 'Tardy Alerts', Text_Alert__c = 'TEST ALERT 1'));
		tvalues.add(new Value__c (Setup__c = testDataSetupUtil_v2.activeSetUp.id, Communication_Type__c = 'SMS', Language__c = 'English', Type__c = 'Attendance Alerts', Text_Alert__c = 'TEST ALERT 1'));
		tvalues.add(new Value__c (Setup__c = testDataSetupUtil_v2.activeSetUp.id, Communication_Type__c = 'SMS', Language__c = 'Spanish', Type__c = 'Tardy Alerts', Text_Alert__c = 'ES TEST ALERT 1'));
		tvalues.add(new Value__c (Setup__c = testDataSetupUtil_v2.activeSetUp.id, Communication_Type__c = 'SMS', Language__c = 'Spanish', Type__c = 'Attendance Alerts', Text_Alert__c = 'ES TEST ALERT 1'));
		insert tvalues;

List<Notification_Settings__c> ns = [Select Reply_To__c from Notification_Settings__c];

if (ns.size() == 0) {
	ns.add(new Notification_Settings__c (Reply_To__c = 'testschoolforce@acumensolutions.com', Subject__c =  'SchoolForce Notification', Display_Name__c = 'SchoolForce Test'));
	insert ns;
}
 
		test.startTest();
		Date testdate = TestDataSetupUtil_v2.semester.date_start_Date__c;
		system.runAs(TestDataSetupUtil_v2.staffUsersList[1]){
			PageReference p = Page.Attendance;
			test.setCurrentPage(p);
		 
			AttendanceController testac = new AttendanceController ();
				testac.timeEl.Date_Start_Date__c = testdate;
				testac.getSectList();
				testac.section = testac.sectionList[0].Id;
				testac.retrieveStudents();
				List<AttendanceWrapper> testaw = testac.atnWrapList;
				//Move this to DataSetup once we know where to set it...
				Section__c usection = [Select Id from Section__c where Id = :testac.section];
				//we need one of the sections to be a daily attendance section...we'll set the first one for now
					 usection.Daily_Attendance__c = true;
					 usection.Record_Attendance__c = true;
					 update usection;

					 Id tstudentId = testaw[0].studID;
					 Student__c tests = new Student__c (Id = tstudentId, grade__c = '6');
					  update tests;

	testac.getSectList();
	testac.section = testac.sectionList[0].Id;
	testac.retrieveStudents();
	testaw = testac.atnWrapList;
	testaw[0].Statusval = pvl[4].Name;
	//Set arrival time = 30 mins after day 2 of daily start time
	testaw[0].te.StartTime__c = testac.selectedSession.Start_DateTime__c.addminutes(30).format('h:mm a');
	testac.save();
	//we need to reset the trigger helper
	core_triggerUtils.recursiveHelper(false);

	testac.timeEl.Date_Start_Date__c = testdate.adddays(1);
	testac.getSectList();
	testac.section = testac.sectionList[0].Id;
	testac.retrieveStudents();
	testaw = testac.atnWrapList;
	testaw[0].Statusval = pvl[2].Name;
	//Set arrival time = 30 mins after day 2 of daily start time
	testaw[0].te.StartTime__c = null;
	testac.save();
	//we need to reset the trigger helper
	core_triggerUtils.recursiveHelper(false);


	Attendance_PGNotification pgn1  =  new Attendance_PGNotification('Tardy Alerts');
	pgn1.query  =  core_SoqlUtils.getMainTardyQuery(testdate, true) ;
	Database.executeBatch(pgn1,1);

	Attendance_PGNotification pgn2  =  new Attendance_PGNotification('Attendance Alerts');
	pgn2.query  =  core_SoqlUtils.getMainAbsentQuery(testdate.adddays(1), true) ;
	Database.executeBatch(pgn2,1);


	test.stoptest();
	//check date set
	Attendance__c [] testda  =  [
	Select Id, Date_Time_of_Parental_Notification__c
	FROM Attendance__c where Student__c  =  :tstudentId];
	system.debug('testda'+testda);
	system.assertnotequals(null, testda[0].Date_Time_of_Parental_Notification__c);
	system.assertnotequals(null, testda[1].Date_Time_of_Parental_Notification__c);


	}//end run as
	} //end test
	} //end test class