objects/Attendance__c.object
<CustomObject>
    <description>This object will capture all student attendance.</description>
    <fields>
        <fullName>Arrival_Time_Text__c</fullName>
        <inlineHelpText>Displays the time the student arrived to class. This field displays in the Attendance tab and the Attendance Wizard.</inlineHelpText>
        <label>Arrival Time</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Arrival_Time__c</fullName>
        <description>The time the student arrived for the session.</description>
        <inlineHelpText>Displays the date and time the student arrived to class. This value is used to calculate the time lost displayed in the Instructional Time Lost field.</inlineHelpText>
        <label>Arrival Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Daily__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This checkbox denotes whether the attendance record is a daily attendance record or a sectional attendance record.</description>
        <inlineHelpText>Indicates the Attendance record is for daily attendance. Otherwise, it is for sectional attendance.</inlineHelpText>
        <label>Daily</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Departure_Time__c</fullName>
        <description>The time the student departs from class if it is an early departure.</description>
        <inlineHelpText>Displays the date and time the student departed from class. This value is used to calculate the time lost displayed in the Instructional Time Lost field.</inlineHelpText>
        <label>Departure Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Picklist_Value__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Displays the value that users select to describe the student&apos;s attendance using the Attendance tab or Attendance Wizard. These picklist options are chosen by your school.</inlineHelpText>
        <label>Status</label>
        <referenceTo>Picklist_Value__c</referenceTo>
        <relationshipLabel>Attendance</relationshipLabel>
        <relationshipName>Attendance</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Session__c</fullName>
        <description>This is a lookup to the sessions that attendance is being captured for.</description>
        <inlineHelpText>Displays the date and time of the Session. Do not update this field.</inlineHelpText>
        <label>Session</label>
        <referenceTo>Session__c</referenceTo>
        <relationshipLabel>Attendance</relationshipLabel>
        <relationshipName>Attendance</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Student__c</fullName>
        <description>This is a lookup to the student record.</description>
        <inlineHelpText>This field provides a link to the Student record for the year. Do not update this field.</inlineHelpText>
        <label>Student</label>
        <referenceTo>Student__c</referenceTo>
        <relationshipLabel>Attendance</relationshipLabel>
        <relationshipName>Attendance</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Attendance</label>
    <nameField>
        <displayFormat>A-{0}</displayFormat>
        <label>Attendance ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Attendance</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Entry_Date__c</fullName>
        <inlineHelpText>Displays the student&apos;s date of entry. This field is automatically updated if the same field on the Student record is updated.</inlineHelpText>
        <label>Entry Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Relationship__c</fullName>
        <inlineHelpText>Do not use this field; it is no longer used by SchoolForce.</inlineHelpText>
        <label>Relationship *Retired*</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Guardian</fullName>
                </value>
                <value>
                    <fullName>Aunt</fullName>
                </value>
                <value>
                    <fullName>Uncle</fullName>
                </value>
                <value>
                    <fullName>Grandmother</fullName>
                </value>
                <value>
                    <fullName>Grandfather</fullName>
                </value>
                <value>
                    <fullName>Brother</fullName>
                </value>
                <value>
                    <fullName>Sister</fullName>
                </value>
                <value>
                    <fullName>Neighbor</fullName>
                </value>
                <value>
                    <fullName>Friend</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>Need Values Here</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Student__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>This field provides a link to the most recent Student record.</inlineHelpText>
        <label>Student</label>
        <referenceTo>Student__c</referenceTo>
        <relationshipLabel>Contacts</relationshipLabel>
        <relationshipName>Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <recordTypes>
        <fullName>Staff</fullName>
        <active>true</active>
        <description>This record type is for staff members.</description>
        <label>Staff</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Picklist_Value__c.object
<CustomObject>
    <fields>
        <fullName>Category__c</fullName>
        <label>Category</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Type__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Absent</fullName>
                </value>
                <value>
                    <fullName>Reporting Period</fullName>
                </value>
                <value>
                    <fullName>Custom Period</fullName>
                </value>
                <value>
                    <fullName>In School Suspension</fullName>
                </value>
                <value>
                    <fullName>Out of School Suspension</fullName>
                </value>
                <value>
                    <fullName>Present</fullName>
                </value>
                <value>
                    <fullName>Partial</fullName>
                </value>
                <value>
                    <fullName>Tardy</fullName>
                </value>
                <value>
                    <fullName>Excused Absence</fullName>
                </value>
                <value>
                    <fullName>Unexcused Absence</fullName>
                </value>
                <value>
                    <fullName>Excused Tardy</fullName>
                </value>
                <value>
                    <fullName>Unexcused Tardy</fullName>
                </value>
                <value>
                    <fullName>Missing</fullName>
                </value>
                <value>
                    <fullName>Exempt</fullName>
                </value>
                <value>
                    <fullName>Complete</fullName>
                </value>
                <value>
                    <fullName>Late</fullName>
                </value>
                <value>
                    <fullName>Incomplete</fullName>
                </value>
                <value>
                    <fullName>Default</fullName>
                </value>
                <value>
                    <fullName>Standards</fullName>
                </value>
                <value>
                    <fullName>Credit/No Credit</fullName>
                </value>
                <value>
                    <fullName>Points</fullName>
                </value>
                <value>
                    <fullName>0-100</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Set_as_Default__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Set this check box for the default value for Attendance (usually Present)</inlineHelpText>
        <label>Set as Default</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Attendance</fullName>
                </value>
                <value>
                    <fullName>Time</fullName>
                </value>
                <value>
                    <fullName>Assignment</fullName>
                </value>
                <value>
                    <fullName>Grade Scale</fullName>
                </value>
                <value>
                    <fullName>Homework</fullName>
                </value>
                <value>
                    <fullName>Behavior Type</fullName>
                </value>
                <value>
                    <fullName>Behavior Consequence</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Picklist Value</label>
    <nameField>
        <label>Display Value</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Picklist Values</pluralLabel>
    <recordTypes>
        <fullName>Attendance</fullName>
        <active>true</active>
        <label>Attendance</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Proactive_Demographics__c.object
<CustomObject>
    <fields>
        <fullName>Entry_Date__c</fullName>
        <label>Entry Date</label>
        <type>Date</type>
    </fields>
    <label>Proactive Demographics</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Proactive Demographics</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Student__c.object
<CustomObject>
    <fields>
        <fullName>Attendance__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Attendance</label>
        <precision>1</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Individual__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Displays the name for the Contact record associated to this Student record. You can click the link to view the student&apos;s Contact record.</inlineHelpText>
        <label>Individual Record</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Student Records</relationshipLabel>
        <relationshipName>Students</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>School__c</fullName>
        <inlineHelpText>Displays the name of the student&apos;s current SchoolForce school. You can click on the link to see the details of this school.</inlineHelpText>
        <label>School</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Students</relationshipLabel>
        <relationshipName>Students</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Student__c</fullName>
        <inlineHelpText>Displays the student&apos;s middle name.</inlineHelpText>
        <label>Student Middle Name</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <label>Student</label>
    <nameField>
        <label>Student Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Students</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Student_PG__c.object
<CustomObject>
    <fields>
        <fullName>Parent_Guardian_c__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Parent/Guardian (c)</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Students</relationshipLabel>
        <relationshipName>Student_PG</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Primary_Contact__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Please check this box if this Parent/Guardian is the main point of contact for this student.</inlineHelpText>
        <label>Primary Contact?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Student__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Student</label>
        <referenceTo>Student__c</referenceTo>
        <relationshipLabel>Parents/Guardians</relationshipLabel>
        <relationshipName>Student_PG</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Student_c__c</fullName>
        <label>Student (c)</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Parents/Guardians</relationshipLabel>
        <relationshipName>Student_PG1</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Student/PG</label>
    <nameField>
        <displayFormat>SPG-{000000}</displayFormat>
        <label>Student/PG ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Student/PG</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/User.object
<CustomObject>
    <fields>
        <fullName>School__c</fullName>
        <label>School</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

classes/ProactiveTest.cls
@isTest
private class ProactiveTest {
	
	static void setupTest() {
		testDataSetupUtil_v2.setUPCoreData(1);
    	testDataSetupUtil_v2.setUpStaffData(1);
    	testDataSetupUtil_v2.setUpStudentData(20);
    	testDataSetupUtil_v2.setupSessiondata();
	}

    static testMethod void ProactiveControllerTest() {
    	setupTest();
    	
    	system.runAs(testDataSetupUtil_v2.staffUsersList[0]){
	    	ID recType = core_SoqlUtils.getRecordTypesBySobject('Picklist_Value__c').get('Attendance');
	    	Picklist_Value__c  pickV = new Picklist_Value__c(); 
	    	pickV.Name = 'Present';
	    	pickV.Type__c = 'Attendance';
	    	pickV.RecordTypeId = recType;
	    	pickV.Set_as_Default__c = true;
	    	pickV.Category__c = 'Present';
	    	insert pickV;
	    	
	    	List<Attendance__c> attList = new List<Attendance__c>();
	    	
	    	for(Student__c s : testDataSetupUtil_v2.studentsList){
	    		for(Integer i=0; i<5; i++){
	    			Attendance__c att = new Attendance__c();
	    			att.Student__c = s.Id;
	    			att.Arrival_Time__c = datetime.now();
	    			att.Arrival_Time_Text__c = 'test' + String.valueOf(i);
	    			att.Daily__c = true;
	    			att.Departure_Time__c = datetime.now().addHours(1);
	    			att.Session__c = testDataSetupUtil_v2.sessionsList[0].Id;
	    			att.Picklist_Value__c = pickV.Id;
	    			attList.add(att);
	    		}
	    	}
	    	insert attList;
	    	
	    	Id rec = core_SoqlUtils.getRecordTypesBySobject('Contact').get('Staff');
	    	
	    	List<Contact> cnt = new List<Contact>();
	    	Integer i = 0;
	    	for(Student__c s : testDataSetupUtil_v2.studentsList){
	    		Contact c = new Contact();
	    		c.RecordTypeId = rec;
	    		c.Student__c = s.Id;
	    		c.FirstName = 'Test' + string.valueOf(i);
	    		c.LastName = 'test' + string.valueOf(i);
	    		c.AccountId = s.School__c;
	    		c.Relationship__c = 'Guardian';
	    		cnt.add(c);
	    		i++;
	    	}
	    	insert cnt;
	    	
	    	List<Student_PG__c> spg = new List<Student_PG__c>();
	    	Integer x = 0;
	    	for(Student__c s : testDataSetupUtil_v2.studentsList){
	    		Student_PG__c c = new Student_PG__c();
	    		c.Student_c__c = s.Individual__c;
	    		c.Student__c = s.Id;
	    		c.Primary_Contact__c = true;
	    		c.Parent_Guardian_c__c = cnt[x].Id;
	    		spg.add(c);
	    		x++;
	    	}
	    	insert spg;
	    	
	    	test.startTest();
	    	//UserRole userRole = [SELECT Id FROM UserRole WHERE DeveloperName = 'Admin' LIMIT 1];
	    	Profile profile = [SELECT Id FROM Profile WHERE Name = 'System Administrator' LIMIT 1];
	    	User adminUser = [SELECT Id FROM User WHERE isActive = true AND ProfileId = :profile.Id LIMIT 1];
	    	
	    	ProactiveController con = new ProactiveController();
	        con.getItems();
	        con.startDate = date.today().addDays(-1);
	        con.pDemo.Entry_Date__c = date.today().addDays(-1);
	        con.endDate = date.today().addDays(1);
	        con.pDemo.Exit_Date__c = date.today().addDays(1);
	        con.demographics = true;
	        con.attendance = true;
	    	con.userStr = adminUser.Id;
	        con.schoolId = testDataSetupUtil_v2.school.Id;
	        con.buttonClick();
	        con.qryStr = 'SELECT  Id, Student__r.Student_Last_Name__c, Student__r.Student_First_Name__c, Student__c, Session_Date__c, Attendance_Status_Read_Only__c, Student__r.Legacy_ID__c FROM Attendance__c WHERE Session_Date__c >=: startDate AND Session_Date__c <=: endDate AND Student__r.School__c = :schoolId LIMIT 100';
	        ProactiveBatch proactiveBatch = new ProactiveBatch(con.userStr, con.qryStr, con.attendance, con.demographics, con.startDate, con.endDate, con.schoolId);
	        Id batchprocessId = Database.executeBatch(proactiveBatch, 200);
	        proactiveBatch.execute(null, attList);
	        system.assert(true, con.endDate != null);
	        test.stopTest();
    	}
    }
    
    static testMethod void TestSetupSchedule(){
    	List<Proactive_Demographics__c> a = new List<Proactive_Demographics__c>();
    	List<Proactive_Attendance__c> b = new List<Proactive_Attendance__c>();
    	
    	for(Integer i=0;i<5000;i++){
    		Proactive_Attendance__c c = new Proactive_Attendance__c();
    		c.First_Name__c = 'First' + string.valueOf(i);
    		c.Last_Name__c = 'Last' + string.valueOf(i);
    		c.USI_ID__c = 'a' + string.valueOf(i);
    		b.add(c);
    	}
    	insert b;
    	
    	for(Integer i=0;i<5000;i++){
    		Proactive_Demographics__c c = new Proactive_Demographics__c();
    		c.First_Name__c = 'First' + string.valueOf(i);
    		c.Last_Name__c = 'Last' + string.valueOf(i);
    		c.USI_ID__c = 'a' + string.valueOf(i);
    		a.add(c);
    	}
    	insert a;
    	ProactiveController.setupSchedule();
    	ProactiveController con = new ProactiveController();
    	test.startTest();
    	con.DeleteProactive();
    	test.stopTest();
    	
    }
    
    static testMethod void TestOnDemandDelete(){
    	List<Proactive_Demographics__c> a = new List<Proactive_Demographics__c>();
    	List<Proactive_Attendance__c> b = new List<Proactive_Attendance__c>();
    	
    	for(Integer i=0;i<6000;i++){
    		Proactive_Attendance__c c = new Proactive_Attendance__c();
    		c.First_Name__c = 'First' + string.valueOf(i);
    		c.Last_Name__c = 'Last' + string.valueOf(i);
    		c.USI_ID__c = 'a' + string.valueOf(i);
    		b.add(c);
    	}
    	insert b;
    	
    	for(Integer i=0;i<2000;i++){
    		Proactive_Demographics__c c = new Proactive_Demographics__c();
    		c.First_Name__c = 'First' + string.valueOf(i);
    		c.Last_Name__c = 'Last' + string.valueOf(i);
    		c.USI_ID__c = 'a' + string.valueOf(i);
    		a.add(c);
    	}
    	insert a;
    	
    	ProactiveController con = new ProactiveController();
    	test.startTest();
    	con.DeleteProactive();
    	test.stopTest();
    }
    
    static testMethod void TestOnDemandDelete2(){
    	List<Proactive_Demographics__c> a = new List<Proactive_Demographics__c>();
    	List<Proactive_Attendance__c> b = new List<Proactive_Attendance__c>();
    	
    	for(Integer i=0;i<2000;i++){
    		Proactive_Attendance__c c = new Proactive_Attendance__c();
    		c.First_Name__c = 'First' + string.valueOf(i);
    		c.Last_Name__c = 'Last' + string.valueOf(i);
    		c.USI_ID__c = 'a' + string.valueOf(i);
    		b.add(c);
    	}
    	insert b;
    	
    	for(Integer i=0;i<6000;i++){
    		Proactive_Demographics__c c = new Proactive_Demographics__c();
    		c.First_Name__c = 'First' + string.valueOf(i);
    		c.Last_Name__c = 'Last' + string.valueOf(i);
    		c.USI_ID__c = 'a' + string.valueOf(i);
    		a.add(c);
    	}
    	insert a;
    	
    	ProactiveController con = new ProactiveController();
    	test.startTest();
    	con.DeleteProactive();
    	con.DeleteProactive();
    	test.stopTest();
    }
}