objects/AWSKey__c.object
<CustomObject>
    <description>Store keys used to communicate with Amazon Web Services</description>
    <fields>
        <fullName>Key__c</fullName>
        <label>Key</label>
        <length>64</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Secret__c</fullName>
        <label>Secret</label>
        <length>128</length>
        <type>Text</type>
    </fields>
    <label>AWS Credential</label>
    <nameField>
        <label>Credential Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>AWS Credentials</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/Test_AWSKeys.cls
@isTest
private class Test_AWSKeys {
	@isTest static void testInstance() {
		try{
			AWSKeys k = new AWSKeys('badname');
		}catch(AWSKeys.AWSKeysException AWSExcept){
			system.debug('here: ' +AWSExcept.getTypeName());
		   	system.assert(AWSExcept.getTypeName().contains('AWSKeys.AWSKeysException'));
		}
		
		AWSKey__c t1 = new AWSKey__c( key__c='s1', secret__c='s1', name='test' );
		insert t1;
		AWSKeys k = new AWSKeys('test');
		system.assert(k.key == 's1');
		system.assert(k.secret == 's1');
		
		
		try{
			AWSKey__c t2 = new AWSKey__c( secret__c='s1', name='test2' );
			insert t2;
			k = new AWSKeys('test2');
		}catch(AWSKeys.AWSKeysException AWSExcept){
		   	system.assert(AWSExcept.getTypeName().contains('AWSKeys.AWSKeysException'));
		   	
		}
		
		try{
			AWSKey__c t3 = new AWSKey__c( key__c='s1', name='test3' );
			insert t3;
			k = new AWSKeys('test3');
		}catch(AWSKeys.AWSKeysException AWSExcept){
		   	system.assert(AWSExcept.getTypeName().contains('AWSKeys.AWSKeysException'));
		   	
		}		
	}
}