objects/Behavior_Incident__c.object
<CustomObject>
    <fields>
        <fullName>Selected_Behavior_Incident_Type__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Selected Behavior Incident Type</label>
        <referenceTo>Picklist_Value__c</referenceTo>
        <relationshipLabel>Behavior</relationshipLabel>
        <relationshipName>Behavior</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Behavior</label>
    <nameField>
        <displayFormat>BI-{000000}</displayFormat>
        <label>Behavior Incident ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Behavior</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Consequence__c.object
<CustomObject>
    <fields>
        <fullName>Consequence__c</fullName>
        <label>Consequence</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Awaiting Admin Decision</fullName>
                </value>
                <value>
                    <fullName>Buddy Classroom/Reflection Room</fullName>
                </value>
                <value>
                    <fullName>Conference with Administrator</fullName>
                </value>
                <value>
                    <fullName>Conference with BCC</fullName>
                </value>
                <value>
                    <fullName>Fieldwork Restriction</fullName>
                </value>
                <value>
                    <fullName>Lose Free Time (Choice Time)</fullName>
                </value>
                <value>
                    <fullName>Lose Free Time (Recess)</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>Other Loss of Privilege</fullName>
                </value>
                <value>
                    <fullName>Other Time Away</fullName>
                </value>
                <value>
                    <fullName>Refocus Center (Time after school)</fullName>
                </value>
                <value>
                    <fullName>Saturday Detention</fullName>
                </value>
                <value>
                    <fullName>Service (Break It Fix it)</fullName>
                </value>
                <value>
                    <fullName>Silent Lunch</fullName>
                </value>
                <value>
                    <fullName>Student Sent Home (Not Suspended)</fullName>
                </value>
                <value>
                    <fullName>Suspendable (Waived)</fullName>
                </value>
                <value>
                    <fullName>Suspension (In School)</fullName>
                </value>
                <value>
                    <fullName>Suspension (Out of School)</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Picklist_Value__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Picklist Value</label>
        <referenceTo>Picklist_Value__c</referenceTo>
        <relationshipLabel>Consequences</relationshipLabel>
        <relationshipName>Consequences</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Consequence</label>
    <nameField>
        <displayFormat>CQ-{000000}</displayFormat>
        <label>Consequence ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Consequences</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/EOY_Progress__c.object
<CustomObject>
    <description>This object is used to determine the current completion progress in the EOY Wizard.</description>
    <fields>
        <fullName>Behavior_Wizard_Completed__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Behavior Wizard Completed</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Behavior_Wizard_Started__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Behavior Wizard Started</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Setup__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Look up to the setup record, since a setup represents an active configuration for a school.</description>
        <inlineHelpText>Determine the progress for an active setup to a school.</inlineHelpText>
        <label>Setup</label>
        <referenceTo>Setup__c</referenceTo>
        <relationshipLabel>EOY Progresses</relationshipLabel>
        <relationshipName>EOY_Progresses</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>EOY Progress</label>
    <nameField>
        <label>EOY Save State Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>EOY Progresses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Picklist_Value__c.object
<CustomObject>
    <fields>
        <fullName>Behavior_Category__c</fullName>
        <label>Behavior Category</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <controllingField>Behavior_Incident_Level__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Non-compliant / Not Prepared</fullName>
                </value>
                <value>
                    <fullName>Not In Class or With Group / Truancy</fullName>
                </value>
                <value>
                    <fullName>Misusing Materials / Damaging Property</fullName>
                </value>
                <value>
                    <fullName>Inappropriate Contact / Unsafe Behavior</fullName>
                </value>
                <value>
                    <fullName>Lying / Cheating / Stealing</fullName>
                </value>
                <value>
                    <fullName>Disruptive / Disrespectful</fullName>
                </value>
                <value>
                    <fullName>Bullying / Threatening / Planning Harm</fullName>
                </value>
                <value>
                    <fullName>Fighting</fullName>
                </value>
                <value>
                    <fullName>Having / Using Potential or Real Weapon</fullName>
                </value>
                <value>
                    <fullName>Drugs / Alcohol</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>Positive #1</fullName>
                </value>
                <value>
                    <fullName>Positive #2</fullName>
                </value>
                <value>
                    <fullName>Neutral #1</fullName>
                </value>
                <value>
                    <fullName>Neutral #2</fullName>
                </value>
                <value>
                    <fullName>Medical</fullName>
                </value>
                <value>
                    <fullName>Positive Behaviors</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Setup__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Setup</label>
        <referenceTo>Setup__c</referenceTo>
        <relationshipLabel>Picklist Values</relationshipLabel>
        <relationshipName>Picklist_Values</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Attendance</fullName>
                </value>
                <value>
                    <fullName>Time</fullName>
                </value>
                <value>
                    <fullName>Assignment</fullName>
                </value>
                <value>
                    <fullName>Grade Scale</fullName>
                </value>
                <value>
                    <fullName>Homework</fullName>
                </value>
                <value>
                    <fullName>Behavior Type</fullName>
                </value>
                <value>
                    <fullName>Behavior Consequence</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Picklist Value</label>
    <nameField>
        <label>Display Value</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Picklist Values</pluralLabel>
    <recordTypes>
        <fullName>Behavior_Consequence</fullName>
        <active>true</active>
        <label>Behavior Consequence</label>
    </recordTypes>
    <recordTypes>
        <fullName>Behavior_Type</fullName>
        <active>true</active>
        <label>Behavior Type</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Setup__c.object
<CustomObject>
    <description>This object is used to setup Schoolforce and is referenced in multiple pieces of code.  There should be one setup object per school.</description>
    <label>Setup</label>
    <nameField>
        <displayFormat>S-{0}</displayFormat>
        <label>Setup ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Setup</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

classes/SchoolSetup_Behavior.cls
public with sharing class SchoolSetup_Behavior {	
	public core_SetupWrapper cSetup					{get;set;}
	public List<Picklist_Value__c> behaviorTypes	{get;set;}
	public List<Picklist_Value__c> consequences		{get;set;}
	public String selectedValue						{get;set;}
	public Picklist_Value__c editHolder				{get;set;}
	public boolean isEdit							{get;set;}
	public boolean isManaged						{get;set;}
	public EOY_Progress__c stateTracker				{get;set;}
	public List<SelectOption> behaviorCats			{get;set;}

	/* INTERNAL VARS */
	private Set<ID> behaviorIDs = new Set<ID>();
	private Set<ID> consequenceIDs = new Set<ID>();
	private ID behaviorTypeRTID;
	private ID consequenceRTID;
	private ID setupID;

	public SchoolSetup_Behavior() {
		behaviorTypeRTID = core_SoqlUtils.getRecordTypesBySobject('Picklist_Value__c').get('Behavior_Type');
		consequenceRTID = core_SoqlUtils.getRecordTypesBySobject('Picklist_Value__c').get('Behavior_Consequence');

		setupID = ApexPages.currentPage().getParameters().get('setupId');
		if(setupID != null){
			cSetup = new core_SetupWrapper(core_SoqlUtils.getSetupById(setupId),null);
			loadValues();
			isEdit = false;
			isManaged = Schema.SObjectType.Setup__c.getName().replace('__c', '').contains('__');
			stateTracker = SetupWizard_Utils.getEOYProgressRecord(cSetup.setup);
		} else {
			SetupWizard_Utils.addMessage(apexpages.severity.ERROR,SetupWizard_Utils.NO_SETUP_MESSAGE);
		}
	}

	/*
		Checks the valididity of the behavior setup and marks the behavior setup as finalized.
	*/
	public void finalize(){
		if(behaviorTypes.isEmpty()){
			SetupWizard_Utils.addMessage(apexpages.severity.ERROR,'You must have one behavior type in order to finalize your behavior setup.');
		}
		if(consequences.isEmpty()){
			SetupWizard_Utils.addMessage(apexpages.severity.ERROR,'You must have one consequence in order to finalize your behavior setup.');
		}

		if(ApexPages.hasMessages(apexpages.severity.ERROR)){
			return;
		} else {
			stateTracker.Behavior_Wizard_Started__c = true;
			stateTracker.Behavior_Wizard_Completed__c = true;
			upsert stateTracker;
			SetupWizard_Utils.addMessage(apexpages.severity.CONFIRM,'Your behavior setup has been finalized. You may return here to make changes as needed.');
		}
	}

	/*
		Deletes the picklist value selected on the page.
	*/
	public void deleteValue(){
		Picklist_Value__c toDelete = getValue(true);

		if(toDelete != null){
			try{
				List<Behavior_Incident__c> incidents;
				List<Consequence__c> cons;
				if(toDelete.RecordTypeID == behaviorTypeRTID){
					incidents = [select id from Behavior_Incident__c where Selected_Behavior_Incident_Type__c=:toDelete.id limit 1];
				} else {
					cons = [select id from Consequence__c where Picklist_Value__c =: toDelete.id limit 1];
				}
				if((toDelete.RecordTypeID == behaviorTypeRTID && incidents.isEmpty()) || (toDelete.RecordTypeID != behaviorTypeRTID && cons.isEmpty())){
					delete toDelete;
				} else {
					SetupWizard_Utils.addMessage(apexpages.severity.ERROR,'There are behavior records filed against this value. Please update these records before deleting.');
					addValue(toDelete);
				}
			} catch (System.DMLException e){
				addValue(toDelete);
			}
		} 
	}

	/*
		Loads the picklist value selected on the page into editHolder.
	*/
	public void editValue(){
		editHolder = getValue(false);

		if(editHolder != null){
			selectedValue = (editHolder.RecordTypeID == behaviorTypeRTID)?'behavior':'consequences';
			editHolder.Type__c = (editHolder.RecordTypeID == behaviorTypeRTID)?'Behavior Type':'Behavior Consequence';
			isEdit = true;
		}
	}

	/*
		Sets editHolder to a new picklist value for population by the user.
	*/
	public void newValue(){
		editHolder = new Picklist_Value__c(Setup__c = setupID);
		editHolder.RecordTypeID = (selectedValue == 'behavior')?behaviorTypeRTID:consequenceRTID;
		editHolder.Type__c = (editHolder.RecordTypeID == behaviorTypeRTID)?'Behavior Type':'Behavior Consequence';
		isEdit = true;
	}
	
	/*
		Saves both new values and edited values
	*/
	public void saveValue(){
		isEdit = false;
		boolean isNew = editHolder.id == null;
		upsert editHolder;
		if(isNew)
			addValue(editHolder);

		stateTracker.Behavior_Wizard_Started__c = true;
		upsert stateTracker;
		editHolder = null;
	}
	
	/*
		Cancels a edit/new. Basically used to turn off the modal.
	*/
	public void cancelEdit(){
		isEdit = false;
	}

	/*
		Saves the setup options changed by the user.
	*/
	public void saveOptions(){
		try{
			update cSetup.setup;
			SetupWizard_Utils.addMessage(apexpages.severity.CONFIRM,'Changes saved successfully.');
		} catch(System.DMLException e){
			SetupWizard_Utils.addMessage(apexpages.severity.ERROR,'An error occured while trying to save your changes.');
		}
	}
	
	/*
		Moves the user to the School setup home page
	*/
	public PageReference prev(){
		PageReference p = Page.SchoolSetup_Home;
		p.getParameters().put('setupId',setupID);
		return p;
	}

	/*
		Loads all existing picklist values for this setup for display. It also initializes the csvLoader.
	*/
	private void loadValues(){
		behaviorTypes = Behavior_SoqlUtils.getPlValuesListByRecordType(behaviorTypeRTID,setupID);
		consequences = Behavior_SoqlUtils.getPlValuesListByRecordType(consequenceRTID,setupID);

		behaviorCats = new List<SelectOption>();
		Schema.DescribeFieldResult fieldResult = Picklist_Value__c.Behavior_Category__c.getDescribe();
        
		for( Schema.PicklistEntry f : fieldResult.getPicklistValues()){
			behaviorCats.add(new SelectOption(f.getLabel(), f.getValue()));
		}


		behaviorIds.addAll(new Map<ID, Picklist_Value__c>(behaviorTypes).keySet());
		consequenceIDs.addAll(new Map<ID, Picklist_Value__c>(consequences).keySet());
	}

	/*
		Searches through the lists of picklist values to find the value the user was interested in. Pulls the record id from selectedValue

		@param remove Should the value be removed from the list or not?
	*/
	private Picklist_Value__c getValue(boolean remove){
		if(behaviorIDs.contains(selectedValue)){
			for(Integer i=0;i<behaviorTypes.size();i++){
				if(behaviorTypes[i].id == selectedValue){
					if(remove) behaviorIDs.remove(selectedValue);
					return (remove)?behaviorTypes.remove(i):behaviorTypes[i];
				}
			}
		} else {
			for(Integer i=0;i<consequences.size();i++){
				if(consequences[i].id == selectedValue){
					if(remove) consequenceIDs.remove(selectedValue);
					return (remove)?consequences.remove(i):consequences[i];
				}
			}
		}
		return null;
	}

	/*
		Adds a new picklist value into the correct list for it's type.

		@param pv The picklist value to be added.
	*/
	private void addValue(Picklist_Value__c pv){
		if(pv.RecordTypeID == behaviorTypeRTID){
			behaviorTypes.add(pv);
			behaviorIDs.add(pv.id);
		} else {
			consequences.add(pv);
			consequenceIDs.add(pv.id);
		}
	}
}