objects/Behavior_Incident__c.object
<CustomObject>
    <fields>
        <fullName>Context_Location__c</fullName>
        <label>Context Location</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Classroom</fullName>
                </value>
                <value>
                    <fullName>Hallway</fullName>
                </value>
                <value>
                    <fullName>Stairwell</fullName>
                </value>
                <value>
                    <fullName>Bathroom</fullName>
                </value>
                <value>
                    <fullName>Cafeteria</fullName>
                </value>
                <value>
                    <fullName>Gym</fullName>
                </value>
                <value>
                    <fullName>Playground</fullName>
                </value>
                <value>
                    <fullName>Sidewalk/Street</fullName>
                </value>
                <value>
                    <fullName>Park</fullName>
                </value>
                <value>
                    <fullName>Fieldwork</fullName>
                </value>
                <value>
                    <fullName>Office</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>Lobby</fullName>
                </value>
                <value>
                    <fullName>Specialist Room</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Context_Time__c</fullName>
        <inlineHelpText>Time at which the incident occurred.</inlineHelpText>
        <label>Context-Time</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Context_Location__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Before School</fullName>
                </value>
                <value>
                    <fullName>After School</fullName>
                </value>
                <value>
                    <fullName>Arrival</fullName>
                </value>
                <value>
                    <fullName>Class-Lesson/Meeting</fullName>
                </value>
                <value>
                    <fullName>Class-Indep/Group Work</fullName>
                </value>
                <value>
                    <fullName>Class-Transition</fullName>
                </value>
                <value>
                    <fullName>Class-Other</fullName>
                </value>
                <value>
                    <fullName>Room/Hall Transition</fullName>
                </value>
                <value>
                    <fullName>Lunch</fullName>
                </value>
                <value>
                    <fullName>Recess</fullName>
                </value>
                <value>
                    <fullName>Dismissal</fullName>
                </value>
                <value>
                    <fullName>Evening Event</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>Transition In Room</fullName>
                </value>
                <value>
                    <fullName>Transition In Hall/Stairs</fullName>
                </value>
                <value>
                    <fullName>Transition In/Out Building</fullName>
                </value>
                <value>
                    <fullName>Pull Out</fullName>
                </value>
                <value>
                    <fullName>After Hours Event</fullName>
                </value>
                <value>
                    <fullName>Community Circle/All School Meeting</fullName>
                </value>
                <value>
                    <fullName>Fieldwork</fullName>
                </value>
                <value>
                    <fullName>Special Class</fullName>
                </value>
                <value>
                    <fullName>Special Block</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Incident_Date__c</fullName>
        <label>Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Incident_Description__c</fullName>
        <label>Incident Description</label>
        <length>32000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Incident_Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Open</fullName>
                    <default>true</default>
                    <label>Open</label>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
                <value>
                    <fullName>Awaiting Add&apos;l Info</fullName>
                </value>
                <value>
                    <fullName>Awaiting Admin Decision</fullName>
                </value>
                <value>
                    <fullName>Draft</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Incident_Time__c</fullName>
        <label>Time</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>7:00 AM</fullName>
                </value>
                <value>
                    <fullName>7:30 AM</fullName>
                </value>
                <value>
                    <fullName>8:00 AM</fullName>
                </value>
                <value>
                    <fullName>8:30 AM</fullName>
                </value>
                <value>
                    <fullName>9:00 AM</fullName>
                </value>
                <value>
                    <fullName>9:30 AM</fullName>
                </value>
                <value>
                    <fullName>10:00 AM</fullName>
                </value>
                <value>
                    <fullName>10:30 AM</fullName>
                </value>
                <value>
                    <fullName>11:00 AM</fullName>
                </value>
                <value>
                    <fullName>11:30 AM</fullName>
                </value>
                <value>
                    <fullName>12:00 PM</fullName>
                </value>
                <value>
                    <fullName>12:30 PM</fullName>
                </value>
                <value>
                    <fullName>1:00 PM</fullName>
                </value>
                <value>
                    <fullName>1:30 PM</fullName>
                </value>
                <value>
                    <fullName>2:00 PM</fullName>
                </value>
                <value>
                    <fullName>2:30 PM</fullName>
                </value>
                <value>
                    <fullName>3:00 PM</fullName>
                </value>
                <value>
                    <fullName>3:30 PM</fullName>
                </value>
                <value>
                    <fullName>4:00 PM</fullName>
                </value>
                <value>
                    <fullName>4:30 PM</fullName>
                </value>
                <value>
                    <fullName>5:00 PM</fullName>
                </value>
                <value>
                    <fullName>5:30 PM</fullName>
                </value>
                <value>
                    <fullName>6:00 PM</fullName>
                </value>
                <value>
                    <fullName>6:30 PM</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Incident_Title__c</fullName>
        <inlineHelpText>Enter the subject of the incident. (Example: Student running in hallway)</inlineHelpText>
        <label>Title</label>
        <length>150</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Incident_Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Positive</fullName>
                </value>
                <value>
                    <fullName>Negative</fullName>
                    <default>true</default>
                    <label>Negative</label>
                </value>
                <value>
                    <fullName>Quick Hit</fullName>
                </value>
                <value>
                    <fullName>Neutral</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Other_Notes__c</fullName>
        <label>Other Notes</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Other__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Other</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Preserve__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>If selected, this behavior incident will be permanently stored for the students involved in this incident.</inlineHelpText>
        <label>Keep Permanently?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Selected_Behavior_Category__c</fullName>
        <label>Selected Behavior Category</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Selected_Behavior_Incident_Type__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Selected Behavior Incident Type</label>
        <referenceTo>Picklist_Value__c</referenceTo>
        <relationshipLabel>Behavior</relationshipLabel>
        <relationshipName>Behavior</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Weapon_Type__c</fullName>
        <label>Weapon Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Airguns (BB or Pellet)</fullName>
                </value>
                <value>
                    <fullName>Biological Agent</fullName>
                </value>
                <value>
                    <fullName>Bomb</fullName>
                </value>
                <value>
                    <fullName>Chemical Agent</fullName>
                </value>
                <value>
                    <fullName>Handguns (Include Zip Guns And Pistols)</fullName>
                </value>
                <value>
                    <fullName>Rifle Or Shotgun</fullName>
                </value>
                <value>
                    <fullName>Other Firearms (Not Handguns, Rifles or Shotgun)</fullName>
                </value>
                <value>
                    <fullName>Knife (Blade Longer Than 2 Inches)</fullName>
                </value>
                <value>
                    <fullName>Other Weapon</fullName>
                </value>
                <value>
                    <fullName>Unknown Weapon</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Behavior</label>
    <nameField>
        <displayFormat>BI-{000000}</displayFormat>
        <label>Behavior Incident ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Behavior</pluralLabel>
    <recordTypes>
        <fullName>Negative</fullName>
        <active>true</active>
        <label>Negative</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Consequence__c.object
<CustomObject>
    <fields>
        <fullName>Picklist_Value__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Picklist Value</label>
        <referenceTo>Picklist_Value__c</referenceTo>
        <relationshipLabel>Consequences</relationshipLabel>
        <relationshipName>Consequences</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Student__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Student Behavior Lookup</label>
        <referenceTo>Student_Behavior__c</referenceTo>
        <relationshipLabel>Consequences</relationshipLabel>
        <relationshipName>Consequences</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Consequence</label>
    <nameField>
        <displayFormat>CQ-{000000}</displayFormat>
        <label>Consequence ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Consequences</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Student__c.object
<CustomObject>
    <fields>
        <fullName>Student__c</fullName>
        <inlineHelpText>Displays the student&apos;s middle name.</inlineHelpText>
        <label>Student Middle Name</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <label>Student</label>
    <nameField>
        <label>Student Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Students</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Student_Behavior__c.object
<CustomObject>
    <fields>
        <fullName>Behavior_Incident__c</fullName>
        <label>Behavior Incident</label>
        <referenceTo>Behavior_Incident__c</referenceTo>
        <relationshipLabel>Student</relationshipLabel>
        <relationshipName>Student_Behavior</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Student__c</fullName>
        <label>Student</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Student__c.Active__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Student__c</referenceTo>
        <relationshipLabel>Behavior</relationshipLabel>
        <relationshipName>Student_Behavior</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Student/Behavior</label>
    <nameField>
        <displayFormat>SB-{000000}</displayFormat>
        <label>Student/Behavior</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Student/Behavior</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/Test_Behavior_YOYDisplayController.cls
@isTest
private class Test_Behavior_YOYDisplayController {
	@isTest static void testDisplayController(){
		testDataSetupUtil_v2.isBehavior=true;
		testDataSetupUtil_v2.setUPCoreData(2);
		testDataSetupUtil_v2.setUPStaffData(2);
		testDataSetupUtil_v2.setUPStudentData(2);
		List<Picklist_Value__c> plList = testDataSetupUtil_v2.behaviorPicklistVals;
		
		Behavior_Incident__c bi = new Behavior_Incident__c(Incident_Type__c = 'Negative'
                                                            ,Incident_Date__c = system.today()
                                                            ,Incident_Description__c = 'This is a test incident'
                                                            ,Incident_Title__c = 'Test Incident'
                                                            ,Incident_Time__c = '0730'
                                                            ,Context_Time__c = 'EDP-BeforeSchool'
                                                            ,Context_Location__c = 'Sidewalk/Street'
                                                            ,Weapon_Type__c = 'Bomb'
                                                            ,Other__c = true
                                                            ,Incident_Status__c = 'Draft'
                                                            ,Other_Notes__c = 'Test'
                                                            ,Selected_Behavior_Incident_Type__c = plList[2].id
                                                            ,Selected_Behavior_Category__c = 'Disruptive / Disrespectful'
                                                            ,Preserve__c = true
                                                          );
        insert bi;
        
        Student_Behavior__c sb = new Student_Behavior__c(Student__c = testDataSetupUtil_v2.studentsList[0].id,
        													Contact__c = testDataSetupUtil_v2.studContactsList[0].id,
                                                           Incident_Role__c = 'Instigator',
                                                           Behavior_Incident__c = bi.Id);
        insert sb;
        
        List<Consequence__c> consequences = new List<Consequence__c>();
        Map<String,Picklist_Value__c> pvString1 = core_SoqlUtils.getPlStringValues('Behavior Consequence', testDataSetupUtil_v2.activeSetUp.id);
        
        Consequence__c consequence1 = new Consequence__c(Student__c = sb.Id
                                                        ,Picklist_Value__c = pvString1.get('Other').id
                                                        ,Final_Consequence__c = false
                                                        ,Student_Consequence__c = sb.Student__c
                                                        );
        consequences.add(consequence1);
        
        Consequence__c consequence2 = new Consequence__c(Student__c = sb.Id
                                                        ,Picklist_Value__c = pvString1.get('Suspension').id
                                                        ,Final_Consequence__c = true
                                                        ,Student_Consequence__c = sb.Student__c
                                                      );
        consequences.add(consequence2);
        
        insert consequences;
        ApexPages.StandardController con = new ApexPages.StandardController(testDataSetupUtil_v2.studContactsList[0]);
        Behavior_YoyDisplayController controller = new Behavior_YoyDisplayController(con);
        
        system.assertEquals(1, controller.sbList.size());
        controller.selectedIncident = bi.id;
        controller.viewSingle();
        system.assertEquals(controller.redirectString, Page.BehaviorIncidentDetail.getURL() + '?id='+bi.id);
	}
	
}