objects/Cohort__c.object
<CustomObject>
    <description>Links and tracks a group of students through their career in an individual school.</description>
    <fields>
        <fullName>School__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>School</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Cohorts</relationshipLabel>
        <relationshipName>Cohorts</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Cohort</label>
    <nameField>
        <label>Cohort Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Cohorts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Cohort__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Student contacts relationship to their cohort</description>
        <inlineHelpText>Displays student cohort. This field is initially entered by the Cohort Wizard. If a student&apos;s cohort changes then this field must be manually updated.</inlineHelpText>
        <label>Cohort</label>
        <referenceTo>Cohort__c</referenceTo>
        <relationshipLabel>Student Contacts</relationshipLabel>
        <relationshipName>Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Entry_Date__c</fullName>
        <inlineHelpText>Displays the student&apos;s date of entry. This field is automatically updated if the same field on the Student record is updated.</inlineHelpText>
        <label>Entry Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Exit_Date__c</fullName>
        <description>The date a student left the school or discontinued schooling prior to graduation or matriculation.</description>
        <inlineHelpText>Displays the date a student left the school or discontinued schooling prior to graduation or matriculation. This field is automatically updated if the same field on the Student record is updated.</inlineHelpText>
        <label>Exit Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Home_Language__c</fullName>
        <inlineHelpText>Displays the language spoken at home by the student contact and family. This field is automatically updated if the same field on the Student record is updated.</inlineHelpText>
        <label>Home Language</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>English</fullName>
                </value>
                <value>
                    <fullName>Spanish</fullName>
                </value>
                <value>
                    <fullName>Chinese</fullName>
                </value>
                <value>
                    <fullName>Amharic</fullName>
                </value>
                <value>
                    <fullName>French</fullName>
                </value>
                <value>
                    <fullName>Vietnamese</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>Mandarin</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Student_Id__c</fullName>
        <formula>Student__r.Id</formula>
        <inlineHelpText>Displays the 15-digit Salesforce ID of the Student record associated with this contact.</inlineHelpText>
        <label>Student Id</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Student__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>This field provides a link to the most recent Student record.</inlineHelpText>
        <label>Student</label>
        <referenceTo>Student__c</referenceTo>
        <relationshipLabel>Contacts</relationshipLabel>
        <relationshipName>Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Grade__c.object
<CustomObject>
    <fields>
        <fullName>Student__c</fullName>
        <label>Student</label>
        <referenceTo>Student__c</referenceTo>
        <relationshipLabel>Grades</relationshipLabel>
        <relationshipName>Grades</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Grade</label>
    <nameField>
        <displayFormat>G-{0}</displayFormat>
        <label>Grade Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Grades</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Proactive_CS__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Proactive Conversion Values</description>
    <fields>
        <fullName>Proactive_Student_Exit__c</fullName>
        <label>Proactive Student Exit</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SF_Student_Exit__c</fullName>
        <label>SF Student Exit</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Student_Exit_Type__c</fullName>
        <label>Student Exit Type</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>Proactive Attendance/Demographics</label>
</CustomObject>

objects/Snapshot_Child__c.object
<CustomObject>
    <fields>
        <fullName>Entry_Date__c</fullName>
        <label>Entry Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Student_Exit_Type__c</fullName>
        <label>Student Exit Type</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>Snapshot Child</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Snapshot Child ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Snapshot Children</pluralLabel>
    <recordTypes>
        <fullName>Cohort</fullName>
        <active>true</active>
        <label>Cohort</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Student__c.object
<CustomObject>
    <fields>
        <fullName>Cohort__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Students relationship to their cohort</description>
        <inlineHelpText>Displays the cohort to which the student is assigned. You can click on the cohort link to see all students within the cohort.</inlineHelpText>
        <label>Cohort</label>
        <referenceTo>Cohort__c</referenceTo>
        <relationshipLabel>Students</relationshipLabel>
        <relationshipName>Students</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Entry_Date__c</fullName>
        <inlineHelpText>Displays the student&apos;s first day of school in the current school year.</inlineHelpText>
        <label>Entry Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Exit_Date__c</fullName>
        <inlineHelpText>Displays the date the student was withdrawn. SchoolForce updates this field when a student is withdrawn through the Section Wizard.</inlineHelpText>
        <label>Exit Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Exit_Reason__c</fullName>
        <inlineHelpText>Displays the reason the student was withdrawn/exited from the school. SchoolForce updates this field when a student is withdrawn through the Section Wizard.</inlineHelpText>
        <label>Exit Code</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>NI (No Information)</fullName>
                </value>
                <value>
                    <fullName>TSS (Transfer to Silings School)</fullName>
                </value>
                <value>
                    <fullName>DE (Dissatisfaction with Education)</fullName>
                </value>
                <value>
                    <fullName>DS (Dissatisfaction with Staff)</fullName>
                </value>
                <value>
                    <fullName>TSI (Transfer to Special Interest School)</fullName>
                </value>
                <value>
                    <fullName>DL (Dissatisfaction with Location)</fullName>
                </value>
                <value>
                    <fullName>TC (Transfer to Closer School)</fullName>
                </value>
                <value>
                    <fullName>DE (Death)</fullName>
                </value>
                <value>
                    <fullName>EX (Expulsion)</fullName>
                </value>
                <value>
                    <fullName>TO (Transfer Out Of State)</fullName>
                </value>
                <value>
                    <fullName>TS (Transfer in State)</fullName>
                </value>
                <value>
                    <fullName>TSS (Transfer to Siblings School)</fullName>
                </value>
                <value>
                    <fullName>Student is in a different public school in the same local education agency</fullName>
                </value>
                <value>
                    <fullName>Transferred to a public school in a different local education agency in the same state</fullName>
                </value>
                <value>
                    <fullName>Transferred to a public school in a different state</fullName>
                </value>
                <value>
                    <fullName>Transferred to a private, non-religiously-affiliated school in the same local education agency</fullName>
                </value>
                <value>
                    <fullName>Transferred to a private, non-religiously-affiliated school in the same state</fullName>
                </value>
                <value>
                    <fullName>Transferred to a private, non-religiously-affiliated school in a different state</fullName>
                </value>
                <value>
                    <fullName>Transferred to a private, religiously-affiliated school in the same local education agency</fullName>
                </value>
                <value>
                    <fullName>Transferred to a private, religiously-affiliated school in the same state</fullName>
                </value>
                <value>
                    <fullName>Transferred to a private, religiouslyaffiliated school in a different state</fullName>
                </value>
                <value>
                    <fullName>Transferred to an institution</fullName>
                </value>
                <value>
                    <fullName>Transferred to home schooling</fullName>
                </value>
                <value>
                    <fullName>Matriculation to another school</fullName>
                </value>
                <value>
                    <fullName>Graduated with regular, advanced, International Baccalaureate, or other type of diploma</fullName>
                </value>
                <value>
                    <fullName>Completed school with other credentials</fullName>
                </value>
                <value>
                    <fullName>Died or is permanently incapacitated</fullName>
                </value>
                <value>
                    <fullName>Withdrawn due to illness</fullName>
                </value>
                <value>
                    <fullName>Expelled or involuntarily withdrawn</fullName>
                </value>
                <value>
                    <fullName>Reached maximum age for services</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Exit_Type__c</fullName>
        <inlineHelpText>Displays the student&apos;s exit type. The values in this field are determined by your school. You can use this field for reporting purposes.</inlineHelpText>
        <label>Exit Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>D</fullName>
                </value>
                <value>
                    <fullName>T</fullName>
                </value>
                <value>
                    <fullName>W</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Home_Language__c</fullName>
        <inlineHelpText>Select the language(s) spoken in the student&apos;s home. If you select Spanish, report
cards and progress reports print in Spanish. For any non-English language, the
text in the Alt Lang Comments field displays for Section Comments and Overall Comments.</inlineHelpText>
        <label>Home Language</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>English</fullName>
                </value>
                <value>
                    <fullName>Spanish</fullName>
                </value>
                <value>
                    <fullName>Chinese</fullName>
                </value>
                <value>
                    <fullName>Amharic</fullName>
                </value>
                <value>
                    <fullName>French</fullName>
                </value>
                <value>
                    <fullName>Vietnamese</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>Mandarin</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Student_Id__c</fullName>
        <inlineHelpText>Displays the student&apos;s ID. This field displays on report cards, progress reports, and transcripts. It must be unique; SchoolForce uses this ID to link the Student record with the correct Contact record.</inlineHelpText>
        <label>Student Id</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Student__c</fullName>
        <inlineHelpText>Displays the student&apos;s middle name.</inlineHelpText>
        <label>Student Middle Name</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <label>Student</label>
    <nameField>
        <label>Student Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Students</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/BatchSnapshotCohortCalcs.cls
global class BatchSnapshotCohortCalcs {
	global Cohort__c cohort                                 {get; private set;} 
	global integer totalStudentsInOriginalCohort            {get; private set;}
	global integer newStudentsNotInOriginalCohort           {get; private set;}
	global integer totalStudentsToday                       {get; private set;}
	global integer origCohortStudentsTransferredCount       {get; private set;}
	global integer origCohortYOYStudentsTransferredCount    {get; private set;}
	global integer origCohortStudentsWithdrawnCount         {get; private set;}
	global integer origCohortStudentsDropOutCount           {get; private set;}
	global integer origCohortStudentsRetainedCount          {get; private set;}
	global double withdrawnStudentsPercent					{get; private set;}
	global double yoyTransferredStudentsPercent				{get; private set;}
	global double transferredStudentsPercent				{get; private set;}
	global double dropOutStudentsStudentsPercent			{get; private set;}
	global double retainedStudentsPercent					{get; private set;}
	global Map<String,Integer> exitCodeCountMap 			{get;set;}
	global Map<String, Proactive_CS__c> exitCodesmap 		{get;set;}
	
	// The below global variables are depricated
	global integer originalActiveStudents 					{get; private set;}
    global integer originalTotalStudents 					{get; private set;}
    global integer newStudents 								{get; private set;}
    global integer currentStudents 							{get; private set;}
    global integer numStudentsWithdrawn 					{get; private set;}
    global double percentOriginalStudentsWithdrawn 			{get; private set;}
    global integer numStudentsWithdrawnFromOriginal			{get; private set;}
    global List<Student__c> originalStudentsList			{get; private set;}
    global List<Student__c> currentStudentsList				{get; private set;}
	
	// This method has been added back as they cannot be removed from Managed package
	global List<Snapshot_Child__c> setCohortStats(Cohort__c c){return null;}

	global List<Snapshot_Child__c> setCohortStats(Cohort__c c,String year){
		List<Snapshot_Child__c> snapshotChildren = new List<Snapshot_Child__c>();
		Map<String,Student__c>  contactStudentsOriginalCohortMap = new Map<String,Student__c>();
		exitCodeCountMap = new Map<String,Integer>();
		exitCodesmap = new Map<String,Proactive_CS__c >();
		originalTotalStudents = 0;
		totalStudentsInOriginalCohort = 0;
		newStudentsNotInOriginalCohort=0;
		totalStudentsToday = 0;
		origCohortStudentsTransferredCount = 0;
		origCohortYOYStudentsTransferredCount = 0;
		origCohortStudentsWithdrawnCount = 0;
		origCohortStudentsDropOutCount = 0;
		origCohortStudentsRetainedCount = 0;
		
		withdrawnStudentsPercent = 0;
		yoyTransferredStudentsPercent = 0;
		retainedStudentsPercent = 0;
		transferredStudentsPercent = 0;
		dropOutStudentsStudentsPercent = 0;
		
		for(Proactive_CS__c ec :[SELECT SF_Student_Exit__c,Student_Exit_Type__c,Proactive_Student_Exit__c FROM Proactive_CS__c WHERE Proactive_Student_Exit__c <> null]){
			exitCodesmap.put(ec.Proactive_Student_Exit__c, ec);
			exitCodeCountMap.put(ec.Proactive_Student_Exit__c,0);
		}
		List<Snapshot_Child__c> childrenRecords = new List<Snapshot_Child__c>();
		for(Student__c stu : [Select Name,Entry_Date__c,Exit_Reason__c,Exit_Date__c,Student_ID__c,Home_Language__c,School__c,Grade__c,OSSE_Code_Text__c,
								Original_Member_Of_Cohort__c,Active__c,Individual__c,Exit_Type__c,School_Year__c
							from Student__c 
							where Individual__r.Cohort__c = : c.id 
							AND School_Year__c =: year]){
			
			if(stu.Original_Member_Of_Cohort__c){ 
				if(stu.Exit_Type__c !='' && stu.Exit_Type__c !=null){
					Integer exitStudCount = exitCodeCountMap.get(stu.OSSE_Code_Text__c);
					exitCodeCountMap.put(stu.OSSE_Code_Text__c,exitStudCount++);
				}

				if(stu.Exit_Type__c=='Transfer'){
					origCohortStudentsTransferredCount++;
					if(stu.School_Year__c == year){
						origCohortYOYStudentsTransferredCount++;
					}
				} else if(stu.Exit_Type__c=='Withdraw'){
					origCohortStudentsWithdrawnCount++;
				} else if(stu.Exit_Type__c=='Dropout'){
					origCohortStudentsDropOutCount++;
				}

				if(stu.School_Year__c == year && stu.Active__c) {
					originalTotalStudents++;
				}
				
				contactStudentsOriginalCohortMap.put(stu.Individual__c,stu); 
			} else if(stu.School_Year__c == year && stu.Active__c){
				newStudentsNotInOriginalCohort++;
			}
			
			if(stu.School_Year__c == year && stu.Active__c) {
				totalStudentsToday++;
			}
			
			//generate a snapshot child regardless
			Snapshot_Child__c sn = new Snapshot_Child__c();
			sn.Original_Member_Of_Cohort__c = stu.Original_Member_Of_Cohort__c;
			sn.Withdraw_Date__c             = (Date)stu.Exit_Date__c;
			sn.Entry_Date__c                = stu.Entry_Date__c;
			sn.Student_OSSE_Exit_Code__c    = stu.OSSE_Code_Text__c;
			sn.Student_Exit_Reason__c       = stu.Exit_Reason__c;
			sn.Student_Name__c              = stu.Name;
			sn.RecordTypeId = core_SoqlUtils.getRecordTypesBySobject('Snapshot_Child__c').get('Cohort');            
			snapshotChildren.add(sn);
			System.debug('Snapshot children$$'+sn); 
		}

		//Total Count of Students (original)
		totalStudentsInOriginalCohort = contactStudentsOriginalCohortMap.keyset().size();
		origCohortStudentsRetainedCount = totalStudentsInOriginalCohort - origCohortStudentsTransferredCount - origCohortStudentsWithdrawnCount - origCohortStudentsDropOutCount;
		
		if(totalStudentsInOriginalCohort>0){
			withdrawnStudentsPercent = double.valueOf(origCohortStudentsWithdrawnCount/totalStudentsInOriginalCohort*100);
			yoyTransferredStudentsPercent = double.valueOf(origCohortYOYStudentsTransferredCount/totalStudentsInOriginalCohort*100);
			transferredStudentsPercent = double.valueOf(origCohortStudentsTransferredCount/totalStudentsInOriginalCohort*100);
			dropOutStudentsStudentsPercent = double.valueOf(origCohortStudentsDropOutCount/totalStudentsInOriginalCohort*100);
			retainedStudentsPercent = double.valueOf(origCohortStudentsRetainedCount/totalStudentsInOriginalCohort*100);
		}
		
		return snapshotChildren;
	}
}