objects/Cohort__c.object
<CustomObject>
    <description>Links and tracks a group of students through their career in an individual school.</description>
    <fields>
        <fullName>Expired__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Expired</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>School__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>School</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Cohorts</relationshipLabel>
        <relationshipName>Cohorts</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Cohort</label>
    <nameField>
        <label>Cohort Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Cohorts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/sched_CohortSnapshot.cls
global class sched_CohortSnapshot implements Schedulable {
	

	global void execute(SchedulableContext sc) {
		Set<Id> schoolIds = new Set<Id>();
			for(AggregateResult ag : [SELECT School__c a
						                FROM Cohort__c 
						                WHERE Expired__c = false
						                GROUP BY School__c]){
				schoolIds.add((ID)ag.get('a'));	
			}
			
			Batch_CohortSnapshot cs = new	Batch_CohortSnapshot(schoolIds);	
			ID batchprocessid =Database.executeBatch(cs, 1);
	}
}