objects/Community_Service__c.object
<CustomObject>
    <fields>
        <fullName>Organization_Name__c</fullName>
        <inlineHelpText>What is the name of the organization that facilitated this project?</inlineHelpText>
        <label>Organization Name</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Service_Hours_Completed__c</fullName>
        <inlineHelpText>How many hours of community service did the student complete for this project?</inlineHelpText>
        <label>Service Hours Completed</label>
        <precision>6</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Service_Start_Date__c</fullName>
        <inlineHelpText>When did this project begin?</inlineHelpText>
        <label>Service Start Date</label>
        <type>Date</type>
    </fields>
    <label>Community Service</label>
    <nameField>
        <label>Project</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Community Service</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/TestCommunityServiceEditController.cls
@isTest
private class TestCommunityServiceEditController {

    static testMethod void myUnitTest() {
        TestDataSetupUtil_v2.setUPCoreData(0);
        TestDataSetupUtil_v2.setUpStaffData(1);
        TestDataSetupUtil_v2.setUPStudentData(1);
        
        PageReference pref = Page.CommunityServiceEdit;
        pref.getParameters().put('sid',TestDataSetupUtil_v2.studentsList[0].id);
        Test.setCurrentPage(pref);
        
        Test.startTest();
        ApexPages.StandardController con = new ApexPages.StandardController(new Community_Service__c());
        CommunityServiceEditController controller = new CommunityServiceEditController(con);
        
        controller.communityService.Service_Hours_Completed__c = 24;
        controller.communityService.Organization_Name__c = 'test';
        controller.communityService.Service_Start_Date__c = system.today();
        controller.saveNewCommunityService();
        controller.saveCommunityService();
        controller.cancelCommunityService();
        
    }
}