objects/Community_Service__c.object
<CustomObject>
    <fields>
        <fullName>Contact__c</fullName>
        <label>Master Student Record</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Community Service</relationshipLabel>
        <relationshipName>Community_Service</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Service_Hours_Completed__c</fullName>
        <inlineHelpText>How many hours of community service did the student complete for this project?</inlineHelpText>
        <label>Service Hours Completed</label>
        <precision>6</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Student__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Student</label>
        <referenceTo>Student__c</referenceTo>
        <relationshipLabel>Community Service</relationshipLabel>
        <relationshipName>Community_Service</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Community Service</label>
    <nameField>
        <label>Project</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Community Service</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Student__c.object
<CustomObject>
    <fields>
        <fullName>Service_Hours_YTD__c</fullName>
        <defaultValue>0</defaultValue>
        <description>The total number of community service hours the student has completed during the current school year (i.e. Student__c.Current_School_Year__c).</description>
        <inlineHelpText>Displays the total number of community service hours the student has completed during the current school year. SchoolForce automatically updates this field and related fields on the Contact record when you enter community service information.</inlineHelpText>
        <label>Service Hours To Date</label>
        <precision>6</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Student__c</fullName>
        <inlineHelpText>Displays the student&apos;s middle name.</inlineHelpText>
        <label>Student Middle Name</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <label>Student</label>
    <nameField>
        <label>Student Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Students</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/TestCommunityServiceTrigger.cls
@isTest
private class TestCommunityServiceTrigger {

	static Community_Service__c testCommunityService = new Community_Service__c();
	
	static void setupTest(){
		
		testDataSetupUtil_v2.setUPCoreData(0);
		testDataSetupUtil_v2.setUpStaffData(0);
		testDataSetupUtil_v2.setUpStudentData(1);
		testDataSetupUtil_v2.studentsList[0].Service_Hours_YTD__c = null;
		
		testCommunityService.Name = 'Test Project';
		testCommunityService.Contact__c = testDataSetupUtil_v2.studContactsList[0].Id;
		testCommunityService.Student__c = testDataSetupUtil_v2.studentsList[0].Id;
		testCommunityService.Service_Hours_Completed__c = 0;
		insert testCommunityService;
		
	}

	static testMethod void testCommunityServiceInsert() {
		setupTest();
    }
    
    static testMethod void testCommunityServiceUpdate() {
    	setupTest();
		testCommunityService.Service_Hours_Completed__c += 4;
		update testCommunityService;
    }
    
    static testMethod void testCommunityServiceDelete() {
    	setupTest();
		delete testCommunityService;
    }

}