objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>true</defaultValue>
        <inlineHelpText>Schools/organizations can choose to use this field when a Contact record is active. When Contact records are created through SchoolForce Setup, this check box is selected.</inlineHelpText>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Exit_Date__c</fullName>
        <description>The date a student left the school or discontinued schooling prior to graduation or matriculation.</description>
        <inlineHelpText>Displays the date a student left the school or discontinued schooling prior to graduation or matriculation. This field is automatically updated if the same field on the Student record is updated.</inlineHelpText>
        <label>Exit Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Reference_Id__c</fullName>
        <description>To store Student/Parent Id as External Id</description>
        <externalId>true</externalId>
        <inlineHelpText>Displays the unique reference ID for the student.  This value should be the same as the Student Id on the associated Student record(s).</inlineHelpText>
        <label>Reference Id</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Student_Id__c</fullName>
        <formula>Student__r.Id</formula>
        <inlineHelpText>Displays the 15-digit Salesforce ID of the Student record associated with this contact.</inlineHelpText>
        <label>Student Id</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Student__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>This field provides a link to the most recent Student record.</inlineHelpText>
        <label>Student</label>
        <referenceTo>Student__c</referenceTo>
        <relationshipLabel>Contacts</relationshipLabel>
        <relationshipName>Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <recordTypes>
        <fullName>Student</fullName>
        <active>true</active>
        <description>This record type is for students</description>
        <label>Student</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Student__c.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>true</defaultValue>
        <inlineHelpText>Indicates whether or not this Student record is active. If checked, then this is the current Student record. If unchecked, this is an old Student record.</inlineHelpText>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Exit_Date__c</fullName>
        <inlineHelpText>Displays the date the student was withdrawn. SchoolForce updates this field when a student is withdrawn through the Section Wizard.</inlineHelpText>
        <label>Exit Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Reference_Id__c</fullName>
        <externalId>true</externalId>
        <inlineHelpText>Displays the Salesforce ID for this Student record. Do not modify this field.</inlineHelpText>
        <label>Reference Id</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>School_Reference_Id__c</fullName>
        <formula>School__r.Reference_Id__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>School Reference Id</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Student_Id__c</fullName>
        <inlineHelpText>Displays the student&apos;s ID. This field displays on report cards, progress reports, and transcripts. It must be unique; SchoolForce uses this ID to link the Student record with the correct Contact record.</inlineHelpText>
        <label>Student Id</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Student__c</fullName>
        <inlineHelpText>Displays the student&apos;s middle name.</inlineHelpText>
        <label>Student Middle Name</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <label>Student</label>
    <nameField>
        <label>Student Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Students</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/Test_ContactTrigger.cls
@isTest
private class Test_ContactTrigger {
	public static void createTestData(){
		testDataSetupUtil_v2.setUPCoreData(5);
        testDataSetupUtil_v2.setUPStaffData(5);
        testDataSetupUtil_v2.setUPStudentData(5);
	}
    static testMethod void testOnDelete() {
    	createTestData();

    	
    	
    	Contact c=testDataSetupUtil_v2.studContactsList[1];
    	Student__c s = testDataSetupUtil_v2.studentsList[1];
        
        Test.startTest();
	        delete c;
	        integer k = [SELECT count() FROM Student__c WHERE id =: s.id];
	        system.assertEquals(k , 0);
	    Test.stopTest();
    }

    static testMethod void testChangeActivation() {
        createTestData();
        Contact c=testDataSetupUtil_v2.studContactsList[2];
    	Student__c s = testDataSetupUtil_v2.studentsList[2];
        Test.startTest();
            c.Active__c = false;
            c.Exit_Date__c = testDataSetupUtil_v2.semester.date_start_date__c.addMonths(2);
            update c;
            system.assert(![SELECT id, Active__c FROM Student__c WHERE id =: s.id].Active__c);
            
            c.Active__c = true;
            update c;
            system.assert([SELECT id, Active__c FROM Student__c WHERE id =: s.id].Active__c);
            
        Test.stopTest();
    }
    
    static testMethod void testUpdateRefId() {
        createTestData();
          Contact c=testDataSetupUtil_v2.studContactsList[0];
    	Student__c s = testDataSetupUtil_v2.studentsList[0];
        Test.startTest();
            c.Reference_Id__c = 'newRefID';
            update c;
            
            Student__c student = [SELECT id, Student_Id__c, School_Reference_Id__c, Reference_Id__c FROM Student__c WHERE id =: s.id];
            system.assert(student.Reference_Id__c == 'newRefID'+'_'+student.School_Reference_Id__c+'_'+testDataSetupUtil_v2.activeSetup.year__r.name__c);
            system.assert(student.Student_Id__c == 'newRefID');
             
        Test.stopTest();
    }
}