objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Email_to_SMS_Address__c</fullName>
        <formula>IF (
AND (
NOT(ISBLANK( MobilePhone )),
NOT(ISBLANK( TEXT(Wireless_Provider__c )))
),
Case ( Wireless_Provider__c,
&quot;ATT&quot;, SUBSTITUTE( SUBSTITUTE( SUBSTITUTE( SUBSTITUTE( SUBSTITUTE( MobilePhone , &apos;.&apos;, &apos;&apos;) , &apos; &apos;, &apos;&apos;) , &apos;-&apos;, &apos;&apos;) , &apos;)&apos;, &apos;&apos;) , &apos;(&apos;, &apos;&apos;)&amp;&quot;@txt.att.net&quot;,
&quot;Verizon&quot;, SUBSTITUTE( SUBSTITUTE( SUBSTITUTE( SUBSTITUTE( SUBSTITUTE( MobilePhone , &apos;.&apos;, &apos;&apos;) , &apos; &apos;, &apos;&apos;) , &apos;-&apos;, &apos;&apos;) , &apos;)&apos;, &apos;&apos;) , &apos;(&apos;, &apos;&apos;)&amp;&quot;@vtext.com&quot;,
&quot;Sprint&quot;,SUBSTITUTE( SUBSTITUTE( SUBSTITUTE( SUBSTITUTE( SUBSTITUTE( MobilePhone , &apos;.&apos;, &apos;&apos;) , &apos; &apos;, &apos;&apos;) , &apos;-&apos;, &apos;&apos;) , &apos;)&apos;, &apos;&apos;) , &apos;(&apos;, &apos;&apos;)&amp;&quot;@messaging.sprintpcs.com&quot;,
&quot;T-Mobile&quot;,SUBSTITUTE( SUBSTITUTE( SUBSTITUTE( SUBSTITUTE( SUBSTITUTE( MobilePhone , &apos;.&apos;, &apos;&apos;) , &apos; &apos;, &apos;&apos;) , &apos;-&apos;, &apos;&apos;) , &apos;)&apos;, &apos;&apos;) , &apos;(&apos;, &apos;&apos;)&amp;&quot;@tmomail.net&quot;,
&quot;Virgin Mobile&quot;, SUBSTITUTE( SUBSTITUTE( SUBSTITUTE( SUBSTITUTE( SUBSTITUTE( MobilePhone , &apos;.&apos;, &apos;&apos;) , &apos; &apos;, &apos;&apos;) , &apos;-&apos;, &apos;&apos;) , &apos;)&apos;, &apos;&apos;) , &apos;(&apos;, &apos;&apos;)&amp;&quot;@vmobl.com&quot;,
&quot;&quot;),

&quot;&quot;)</formula>
        <inlineHelpText>SchoolForce automatically updates this field using the information you enter into the Mobile Phone and Mobile Carrier fields. It is used for sending attendance alerts to parents via SMS.</inlineHelpText>
        <label>Email to SMS Address</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Notify_via_Email__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Select if the parent would prefer to receve notifications via email.</inlineHelpText>
        <label>Notify via Email</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Notify_via_SMS__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Select if parent would prefer to receve notifications via SMS text message.</inlineHelpText>
        <label>Notify via SMS</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Preferred_Language__c</fullName>
        <description>Used for parent/guardian to determine what language to send notifications/written information. Replacing &quot;Receive written information in Spanish?&quot; checkbox so as to make more modular and allow for multiple possible languages.</description>
        <inlineHelpText>Displays the language that the student or parent/guardian wishes to receive emails and/or SMS notifications in. Current options are English and Spanish.</inlineHelpText>
        <label>Preferred Language</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>English</fullName>
                    <default>true</default>
                    <label>English</label>
                </value>
                <value>
                    <fullName>Spanish</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Student__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>This field provides a link to the most recent Student record.</inlineHelpText>
        <label>Student</label>
        <referenceTo>Student__c</referenceTo>
        <relationshipLabel>Contacts</relationshipLabel>
        <relationshipName>Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/HW_Tracker__c.object
<CustomObject>
    <fields>
        <fullName>Received_First_Alert__c</fullName>
        <defaultValue>false</defaultValue>
        <description>When checks, removes it from the second alert</description>
        <inlineHelpText>Did Parent/Guardian of this Student receive the an Alert?</inlineHelpText>
        <label>Received Today&apos;s Alert?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Student__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Student</label>
        <referenceTo>Student__c</referenceTo>
        <relationshipName>Homework_Tracking</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Homework</label>
    <nameField>
        <displayFormat>HT-{000000}</displayFormat>
        <label>HT ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Homework</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Notification_Settings__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <fields>
        <fullName>Display_Name__c</fullName>
        <description>Display name recipient will see when receiving notification from Schoolforce</description>
        <label>Display Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Reply_To__c</fullName>
        <description>Sets the reply To for notifications from Schoolforce to Parent/Guardians</description>
        <label>Reply To</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Subject__c</fullName>
        <description>Subject of the notification</description>
        <label>Subject</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>Notification Settings</label>
</CustomObject>

objects/Setup__c.object
<CustomObject>
    <description>This object is used to setup Schoolforce and is referenced in multiple pieces of code.  There should be one setup object per school.</description>
    <fields>
        <fullName>School__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>School</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1 OR 2</booleanFilter>
            <filterItems>
                <field>Account.RecordType.Name</field>
                <operation>equals</operation>
                <value>School</value>
            </filterItems>
            <filterItems>
                <field>Account.RecordType.Name</field>
                <operation>equals</operation>
                <value>Summer School</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Setup</relationshipLabel>
        <relationshipName>Setup</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Setup</label>
    <nameField>
        <displayFormat>S-{0}</displayFormat>
        <label>Setup ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Setup</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/Student__c.object
<CustomObject>
    <fields>
        <fullName>School__c</fullName>
        <inlineHelpText>Displays the name of the student&apos;s current SchoolForce school. You can click on the link to see the details of this school.</inlineHelpText>
        <label>School</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Students</relationshipLabel>
        <relationshipName>Students</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Setup__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Displays the Setup record associated to this Student record. The Setup record defines the settings for the school in a specific school year.</inlineHelpText>
        <label>Setup</label>
        <referenceTo>Setup__c</referenceTo>
        <relationshipLabel>Students</relationshipLabel>
        <relationshipName>Students</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Student__c</fullName>
        <inlineHelpText>Displays the student&apos;s middle name.</inlineHelpText>
        <label>Student Middle Name</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <label>Student</label>
    <nameField>
        <label>Student Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Students</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Student_PG__c.object
<CustomObject>
    <fields>
        <fullName>Parent_Guardian_c__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Parent/Guardian (c)</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Students</relationshipLabel>
        <relationshipName>Student_PG</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Student__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Student</label>
        <referenceTo>Student__c</referenceTo>
        <relationshipLabel>Parents/Guardians</relationshipLabel>
        <relationshipName>Student_PG</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Student/PG</label>
    <nameField>
        <displayFormat>SPG-{000000}</displayFormat>
        <label>Student/PG ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Student/PG</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Value__c.object
<CustomObject>
    <fields>
        <fullName>Communication_Type__c</fullName>
        <label>Communication Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Email</fullName>
                </value>
                <value>
                    <fullName>SMS</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Language__c</fullName>
        <label>Language</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>English</fullName>
                    <default>true</default>
                    <label>English</label>
                </value>
                <value>
                    <fullName>Spanish</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Setup__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Setup</label>
        <referenceTo>Setup__c</referenceTo>
        <relationshipLabel>Values</relationshipLabel>
        <relationshipName>Values</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Text_Alert__c</fullName>
        <label>Text Alert</label>
        <length>32000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Homework Alerts</fullName>
                </value>
                <value>
                    <fullName>Attendance Alerts</fullName>
                </value>
                <value>
                    <fullName>Attendance Threshold Alerts</fullName>
                </value>
                <value>
                    <fullName>Tardy Alerts</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Value</label>
    <nameField>
        <label>Values Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Values</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/Homework_PGNotification.cls
global class Homework_PGNotification implements Database.Batchable<sObject>,Database.Stateful{
    public String query;
    public String email;
    global Set<Id> ustudents = new Set<Id>();
    global Map<String, Map<String, String>> mNotificationText;

    global Homework_PGNotification (String alerttype) {
        mNotificationText = core_SoqlUtils.getnotifymap(alerttype);
    }

    global database.querylocator start(Database.BatchableContext BC){
        return Database.getQueryLocator(query);
    }

    global void execute(Database.BatchableContext BC, List<sObject> scope){
        for(sObject s : scope) {
            HW_Tracker__c hwTracker = (HW_Tracker__c ) s;
            for (Student_PG__c pg: Homework_SoqlUtils.getParentalInfo(hwTracker.Student__c)) {
                if ((pg.Parent_Guardian_c__r.Notify_via_Email__c && pg.Parent_Guardian_c__r.Email != null) 
                		||(pg.Parent_Guardian_c__r.Notify_via_SMS__c && pg.Parent_Guardian_c__r.Email_to_SMS_Address__c != null)){
                	
                	NotificationUtils.sendnotification sn;		
                    if (mNotificationText.containsKey(pg.Parent_Guardian_c__r.Preferred_Language__c + pg.Student__r.School__c)){
                		sn = new NotificationUtils.sendnotification(pg, mNotificationText.get(pg.Parent_Guardian_c__r.Preferred_Language__c + pg.Student__r.School__c));
                    } else {
                    	sn = new NotificationUtils.sendnotification(pg, mNotificationText.get('English' + pg.Student__r.School__c));
                    }
                    
                    ustudents.add(hwTracker.Student__c);
                }
            }
        }
    }// end execute   

    global void finish(Database.BatchableContext BC){
        List<HW_Tracker__c> updatehw = new List<HW_Tracker__c>();
        //Mark all HW Notifications as sent since even though First Notify only goes to missing, we don't want to send again on same day

        for (HW_Tracker__c hw : [Select Id, Student__c From HW_Tracker__c WHERE Student__c IN : ustudents]) {
            hw.Received_First_Alert__c = true;
            updatehw.add(hw);
        }
    
        try {
        	Database.update(updatehw, false); 
        } catch (Exception Ex) {
        }
    } // end finish

    @isTest static void testBatch(){
        TestDataSetupUtil_v2.setupCoreData(5);
        TestDataSetupUtil_v2.setupStaffData(5);
        TestDataSetupUtil_v2.setupStudentData(5);
        Test_Report_Card_Controller.generateHomework();
        Value__c hwNotification = new Value__c(Type__c='Homework Alerts', Communication_Type__c='Email', Language__c='English',Setup__c=TestDataSetupUtil_v2.activeSetup.id, Text_Alert__c='Test');
        insert hwNotification;
        Notification_Settings__c ns = new Notification_Settings__c(reply_to__c='test@test.com',display_name__c='Tester',Subject__c='Homework test');
        insert ns;

        Test.startTest();
            Homework_PGNotification batch = new Homework_PGNotification('Homework Alerts');
            batch.query='select id, Student__c from HW_Tracker__c';
            Database.executeBatch(batch);
        Test.stopTest();
    }
}