objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>true</defaultValue>
        <inlineHelpText>Schools/organizations can choose to use this field when a Contact record is active. When Contact records are created through SchoolForce Setup, this check box is selected.</inlineHelpText>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Student_Id__c</fullName>
        <formula>Student__r.Id</formula>
        <inlineHelpText>Displays the 15-digit Salesforce ID of the Student record associated with this contact.</inlineHelpText>
        <label>Student Id</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Student_Picture__c</fullName>
        <inlineHelpText>Do not use this field; it is no longer used by SchoolForce.</inlineHelpText>
        <label>Student Picture *Retired*</label>
        <length>32000</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Student__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>This field provides a link to the most recent Student record.</inlineHelpText>
        <label>Student</label>
        <referenceTo>Student__c</referenceTo>
        <relationshipLabel>Contacts</relationshipLabel>
        <relationshipName>Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <recordTypes>
        <fullName>Staff</fullName>
        <active>true</active>
        <description>This record type is for staff members.</description>
        <label>Staff</label>
    </recordTypes>
    <recordTypes>
        <fullName>Student</fullName>
        <active>true</active>
        <description>This record type is for students</description>
        <label>Student</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Global_Error__c.object
<CustomObject>
    <label>Global Error</label>
    <nameField>
        <label>Global Error Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Global Errors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Meal_Transaction__c.object
<CustomObject>
    <fields>
        <fullName>Meal_Type__c</fullName>
        <label>Meal Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Breakfast</fullName>
                </value>
                <value>
                    <fullName>Lunch</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Student__c</fullName>
        <label>Student</label>
        <referenceTo>Student__c</referenceTo>
        <relationshipLabel>Meal Transactions</relationshipLabel>
        <relationshipName>Meal_Transactions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Transaction_Amount__c</fullName>
        <description>This is the amount the student is required to pay for their meal.</description>
        <inlineHelpText>This is the amount the student is required to pay for their meal.</inlineHelpText>
        <label>Transaction Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Transaction_Date__c</fullName>
        <defaultValue>Now()</defaultValue>
        <label>Transaction Date</label>
        <required>true</required>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Transaction_Type__c</fullName>
        <label>Transaction Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Sale</fullName>
                </value>
                <value>
                    <fullName>Credit</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Void__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This should be checked if a transaction is voided.</description>
        <inlineHelpText>This should be checked if a transaction is voided.</inlineHelpText>
        <label>Void</label>
        <type>Checkbox</type>
    </fields>
    <label>Meal Transaction</label>
    <nameField>
        <displayFormat>T-{0}</displayFormat>
        <label>Meal Transaction Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Meal Transactions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Meals_Setup__c.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Full_Price_Breakfast_Price__c</fullName>
        <defaultValue>0</defaultValue>
        <description>This is the amount a student pays for a full-priced breakfast.</description>
        <inlineHelpText>This is the amount a student pays for a full-priced breakfast.</inlineHelpText>
        <label>Full-Price Breakfast Price</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Full_Price_Lunch_Price__c</fullName>
        <defaultValue>0</defaultValue>
        <description>This is the amount a student pays for a full-priced lunch.</description>
        <inlineHelpText>This is the amount a student pays for a full-priced lunch.</inlineHelpText>
        <label>Full-Price Lunch Price</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Reduced_Breakfast_Price__c</fullName>
        <defaultValue>0</defaultValue>
        <description>This is the amount a student pays for a reduced breakfast.</description>
        <inlineHelpText>This is the amount a student pays for a reduced breakfast.</inlineHelpText>
        <label>Reduced Breakfast Price</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Reduced_Lunch_Price__c</fullName>
        <defaultValue>0</defaultValue>
        <description>This is the amount a student pays for a reduced lunch.</description>
        <inlineHelpText>This is the amount a student pays for a reduced lunch.</inlineHelpText>
        <label>Reduced Lunch Price</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Schoolwide_Free_Breakfast__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This should be checked if breakfast is free for all students.</description>
        <inlineHelpText>This should be checked if breakfast is free for all students.</inlineHelpText>
        <label>Schoolwide Free Breakfast</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Setup__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Setup</label>
        <referenceTo>Setup__c</referenceTo>
        <relationshipLabel>Meals Setup</relationshipLabel>
        <relationshipName>Meals_Setup</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Meals Setup</label>
    <nameField>
        <displayFormat>MS-{0}</displayFormat>
        <label>Meals Setup Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Meals Setup</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Setup__c.object
<CustomObject>
    <description>This object is used to setup Schoolforce and is referenced in multiple pieces of code.  There should be one setup object per school.</description>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Is this school setup active for this school year?</inlineHelpText>
        <label>Active?</label>
        <type>Checkbox</type>
    </fields>
    <label>Setup</label>
    <nameField>
        <displayFormat>S-{0}</displayFormat>
        <label>Setup ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Setup</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/Student__c.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>true</defaultValue>
        <inlineHelpText>Indicates whether or not this Student record is active. If checked, then this is the current Student record. If unchecked, this is an old Student record.</inlineHelpText>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Current_Meals_Balance__c</fullName>
        <description>This is the current balance for the student&apos;s meals account. Additional money can be added by adding a credit transaction.</description>
        <inlineHelpText>Displays the current balance for the student&apos;s meals account if your school uses the Meals module. You can add additional money by adding a credit transaction in the Meals related list.</inlineHelpText>
        <label>Current Meals Balance</label>
        <summarizedField>Meal_Transaction__c.Transaction_Amount_Rollup__c</summarizedField>
        <summaryFilterItems>
            <field>Meal_Transaction__c.Void__c</field>
            <operation>equals</operation>
            <value>False</value>
        </summaryFilterItems>
        <summaryForeignKey>Meal_Transaction__c.Student__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Meals_Category__c</fullName>
        <inlineHelpText>Displays the type of meal program assigned to this student. The Meals module uses this field. You can also use it for reporting purposes.</inlineHelpText>
        <label>Meals Category</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Full-Priced</fullName>
                </value>
                <value>
                    <fullName>Reduced</fullName>
                </value>
                <value>
                    <fullName>Free</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Setup__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Displays the Setup record associated to this Student record. The Setup record defines the settings for the school in a specific school year.</inlineHelpText>
        <label>Setup</label>
        <referenceTo>Setup__c</referenceTo>
        <relationshipLabel>Students</relationshipLabel>
        <relationshipName>Students</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Student_Id__c</fullName>
        <inlineHelpText>Displays the student&apos;s ID. This field displays on report cards, progress reports, and transcripts. It must be unique; SchoolForce uses this ID to link the Student record with the correct Contact record.</inlineHelpText>
        <label>Student Id</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Student_Picture__c</fullName>
        <formula>IF(ISNULL(IMAGE(&quot;/resource/&quot; &amp; $Setup.pictureHelper__c.pictureURL__c &amp; &quot;/pictures/&quot; &amp;  Student_Id__c  &amp; &quot;.jpg&quot;, &quot;Student Picture&quot;)),IMAGE(&quot;/resource/&quot; &amp; $Setup.pictureHelper__c.picture2URL__c &amp; &quot;/picture2s/&quot; &amp;  Student_Id__c  &amp; &quot;.jpg&quot;, &quot;Student Picture&quot;),IMAGE(&quot;/resource/&quot; &amp; $Setup.pictureHelper__c.pictureURL__c &amp; &quot;/pictures/&quot; &amp;  Student_Id__c  &amp; &quot;.jpg&quot;, &quot;Student Picture&quot;))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Displays the student&apos;s picture. You cannot manually update this field.</inlineHelpText>
        <label>Student Picture</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Student__c</fullName>
        <inlineHelpText>Displays the student&apos;s middle name.</inlineHelpText>
        <label>Student Middle Name</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <label>Student</label>
    <nameField>
        <label>Student Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Students</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/MealsController.cls
public with sharing class MealsController{
	public String 						mealType		{get;set;}
	public String						studID			{get;set;}
	public List <SelectOption>			mealList		{get;set;}
	public Student__c 					student			{get;set;}
	public core_BaseInfo_v2.cSchool_BaseInfo baseObj	{get;set;}
	public Meals_Setup__c 				mealSetup;
	public Meal_Transaction__c 			dummyMT			{get;set;}
	public Double 						cost			{get;set;}
	public boolean 						showMeal		{get;set;}
	public boolean 						pastDate		{get;set;}
	public List<Meal_Transaction__c> 	studentMealList	{get;set;}
	public DateTime 					daystart		{get;set;}
	public DateTime 					dayend			{get;set;}
	public Integer 						breakfastCnt;
	public Integer 						lunchCnt;
	public String 						studentMealType	{get;set;}
	public boolean 						displayEverything	{get;set;}//boolean to keep the rest of the page showing when the user does not have all the proper credentials
	public boolean 						firstClick			{get;set;}//boolean used to make sure if a different meal type is chosen, it is updated
	public Meal_Transaction__c 			mealTime {get;set;}

	public MealsController(){
		try{
			mealTime = new Meal_Transaction__c();
			pastDate = false;
			firstClick = false;
			displayEverything = false;
			dummyMt = new Meal_Transaction__c();
			breakfastCnt = 0;
			lunchCnt = 0;
			student = new Student__c();
			studentMealList = new List <Meal_Transaction__c>();
			showMeal = false;
			mealList = new List<SelectOption>{new SelectOption('Lunch','Lunch'),new SelectOption('Breakfast','Breakfast')};
			core_BaseInfo_v2.initBaseInfo();
			baseObj = core_BaseInfo_v2.baseInfoObj;
			try {
				Id setupID = baseObj.activeSetup.Id;
				mealSetup = [select m.Id, m.Name, m.Schoolwide_Free_Breakfast__c, m.Reduced_Lunch_Price__c, m.Reduced_Breakfast_Price__c, m.Full_Price_Lunch_Price__c, m.Full_Price_Breakfast_Price__c from Meals_Setup__c m where Setup__c = :setupID Limit 1];
				displayEverything = true;
			} catch(Exception e) {
				Apexpages.addMessage(new apexpages.message(apexpages.severity.error, 'Please contact your system administrator to verify that ' + userInfo.getFirstName() + ' ' + userInfo.getLastName() + ' is associated with a Staff record, an active Setup record, and an active Meals Setup record.'));
			}

		}
		catch(Exception e){
			ApexPages.addMessage(new apexpages.message(apexpages.severity.ERROR,'There was an error loading the page.'));
		}
	}

	public void pullStudent(){
		try{
			Integer year;
			Integer month;
			Integer day;

			if(pastDate&&mealTime.Transaction_Date__c!=null){
				year = mealTime.Transaction_Date__c.year();
				month = mealTime.Transaction_Date__c.month();
				day = mealTime.Transaction_Date__c.day();

			}
			else{
				year = system.now().year();
				month = system.now().month();
				day = system.now().day();
			}
			daystart = datetime.newInstance(year, month, day, 0, 0, 0);
			dayend = datetime.newInstance(year, month, day, 23, 59, 59);

			firstClick = true;
			breakfastCnt = 0;
			lunchCnt = 0;
			studentMealType = 'Free';
			if(studID==''){
				Apexpages.addMessage(new apexpages.message(apexpages.severity.error, 'Please enter a student ID.'));
			}else{
				list<Student__c> tempList = [select ID, Name, Student_Picture__c, Meals_Category__c, Current_Meals_Balance__c from Student__c where Student_Id__c = :studID and Active__c=true and Setup__C =:baseObj.activeSetup.Id];
				if(tempList.size()>0){
					student = tempList[0];
					showMeal=true;
				}else{
					Apexpages.addMessage(new apexpages.message(apexpages.severity.error, 'No active student found for the ID that was entered.'));
				}
				if(student.Meals_Category__c=='--None--' || student.Meals_Category__c==null){
					Apexpages.addMessage(new apexpages.message(apexpages.severity.error, student.Name+' has not been assigned a meal category.'));
				}
			}

			cost = 0;
			if(mealType=='Lunch'){
				if(student.Meals_Category__c=='Reduced'){
					cost = mealSetup.Reduced_Lunch_Price__c;
				}
				else if(student.Meals_Category__c=='Full-Priced'){
					cost = mealSetup.Full_Price_Lunch_Price__c;
				}
			}else if(mealType=='Breakfast'){
				if(mealSetup.Schoolwide_Free_Breakfast__c){
					cost = 0;
				}
				else if(student.Meals_Category__c=='Reduced'){
					cost = mealSetup.Reduced_Breakfast_Price__c;
				}
				else if(student.Meals_Category__c=='Full-Priced'){
					cost = mealSetup.Full_Price_Breakfast_Price__c;
				}
			}

			if(mealType=='Lunch'||!mealSetup.Schoolwide_Free_Breakfast__c){
				studentMealType = student.Meals_Category__c;
			}


			studentMealList = [select m.Id, m.Name, m.Void__c, m.Transaction_Date__c, m.Transaction_Amount__c, m.Meal_Type__c From Meal_Transaction__c m where Student__c = :student.ID AND Transaction_Date__c > :daystart AND Transaction_Date__c < :dayend order by Transaction_Date__c asc];


			for(Meal_Transaction__c ms:studentMealList){
				if(!ms.Void__c&&ms.Meal_Type__c=='Lunch'&&(student.Meals_Category__c=='Free'||student.Meals_Category__c=='Reduced')){
					lunchCnt++;
				}
				if(!ms.Void__c&&ms.Meal_Type__c=='Breakfast'&&(student.Meals_Category__c=='Free'||student.Meals_Category__c=='Reduced'||mealSetup.Schoolwide_Free_Breakfast__c)){
					breakfastCnt++;
				}
			}
			dummyMT.Transaction_Amount__c = cost;
		}
		catch(Exception e){
			Global_Error__c ge = Error_Handling.handleError('Setup, '+baseObj.activeSetup.id+'; Student, '+studID+'; Meals Setup, '+mealSetup.id, 'Meals', 'error finding student information', e);
			insert ge;
		}
	}

	public void buyMeal(){
		try{
			String errorText = student.Name+' was already served ' + mealType.toLowerCase() + ' today.';
			if(pastDate&&mealTime.Transaction_Date__c!=null){
				errorText = student.Name + ' already has a ' + mealType.toLowerCase() + ' transaction for the date selected.';
			}
			if(mealType=='Lunch'&&lunchCnt>0){
				Apexpages.addMessage(new apexpages.message(apexpages.severity.error, errorText));
			}
			else if(mealType=='Breakfast'&&breakfastCnt>0){
				Apexpages.addMessage(new apexpages.message(apexpages.severity.error, errorText));
			}
			else if(student.Meals_Category__c=='--None--' || student.Meals_Category__c==null){
				Apexpages.addMessage(new apexpages.message(apexpages.severity.error, student.Name+' has not been assigned a meal category.'));
			}
			else{
				Meal_Transaction__c meal = new Meal_Transaction__c();
				meal.student__c = student.Id;
				if(!pastDate||mealTime.Transaction_Date__c==null){
					meal.Transaction_Date__c = system.now();
				}
				else{
					meal.Transaction_Date__c = mealTime.Transaction_Date__c;
				}

				meal.Transaction_Type__c = 'Sale';
				meal.Meal_Type__c = mealType;
				meal.Transaction_Amount__c = cost;
				try{
					insert meal;
				}
				catch(exception e){
					ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, 'There was an error saving the meal transaction.'));
					throw e;
				}
				ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.CONFIRM, 'You successfully bought ' + mealType.toLowerCase() + ' for ' + student.Name + '.'));
				showMeal = false;
				studID = '';
				studentMealList.clear();
				student = new Student__c();
				studentMealType='Free';
			}
		}
		catch(Exception e){
			Global_Error__c ge = Error_Handling.handleError('Setup, '+baseObj.activeSetup.id+'; Student, '+studID+'; Meals Setup, '+mealSetup.id, 'Meals', 'error saving meal transaction', e);
			Error_Handling.errorMessage('There was an error processing your request.');
			insert ge;
		}
	}

	public void voidTransactions(){
		try{
			try{
				upsert studentMealList;
			}
			catch(exception e){
				Apexpages.addMessage(new apexpages.message(apexpages.severity.error, 'There was an error voiding the meal transaction.'));
				throw e;
			}
			pullStudent();
		}
		catch(Exception e){
			Global_Error__c ge = Error_Handling.handleError('Setup, '+baseObj.activeSetup.id+'; Student, '+studID+'; Meals Setup, '+mealSetup.id, 'Meals', 'error voiding transactions', e);
			insert ge;
		}
	}
}