objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Email_to_SMS_Address__c</fullName>
        <formula>IF (
AND (
NOT(ISBLANK( MobilePhone )),
NOT(ISBLANK( TEXT(Wireless_Provider__c )))
),
Case ( Wireless_Provider__c,
&quot;ATT&quot;, SUBSTITUTE( SUBSTITUTE( SUBSTITUTE( SUBSTITUTE( SUBSTITUTE( MobilePhone , &apos;.&apos;, &apos;&apos;) , &apos; &apos;, &apos;&apos;) , &apos;-&apos;, &apos;&apos;) , &apos;)&apos;, &apos;&apos;) , &apos;(&apos;, &apos;&apos;)&amp;&quot;@txt.att.net&quot;,
&quot;Verizon&quot;, SUBSTITUTE( SUBSTITUTE( SUBSTITUTE( SUBSTITUTE( SUBSTITUTE( MobilePhone , &apos;.&apos;, &apos;&apos;) , &apos; &apos;, &apos;&apos;) , &apos;-&apos;, &apos;&apos;) , &apos;)&apos;, &apos;&apos;) , &apos;(&apos;, &apos;&apos;)&amp;&quot;@vtext.com&quot;,
&quot;Sprint&quot;,SUBSTITUTE( SUBSTITUTE( SUBSTITUTE( SUBSTITUTE( SUBSTITUTE( MobilePhone , &apos;.&apos;, &apos;&apos;) , &apos; &apos;, &apos;&apos;) , &apos;-&apos;, &apos;&apos;) , &apos;)&apos;, &apos;&apos;) , &apos;(&apos;, &apos;&apos;)&amp;&quot;@messaging.sprintpcs.com&quot;,
&quot;T-Mobile&quot;,SUBSTITUTE( SUBSTITUTE( SUBSTITUTE( SUBSTITUTE( SUBSTITUTE( MobilePhone , &apos;.&apos;, &apos;&apos;) , &apos; &apos;, &apos;&apos;) , &apos;-&apos;, &apos;&apos;) , &apos;)&apos;, &apos;&apos;) , &apos;(&apos;, &apos;&apos;)&amp;&quot;@tmomail.net&quot;,
&quot;Virgin Mobile&quot;, SUBSTITUTE( SUBSTITUTE( SUBSTITUTE( SUBSTITUTE( SUBSTITUTE( MobilePhone , &apos;.&apos;, &apos;&apos;) , &apos; &apos;, &apos;&apos;) , &apos;-&apos;, &apos;&apos;) , &apos;)&apos;, &apos;&apos;) , &apos;(&apos;, &apos;&apos;)&amp;&quot;@vmobl.com&quot;,
&quot;&quot;),

&quot;&quot;)</formula>
        <inlineHelpText>SchoolForce automatically updates this field using the information you enter into the Mobile Phone and Mobile Carrier fields. It is used for sending attendance alerts to parents via SMS.</inlineHelpText>
        <label>Email to SMS Address</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Notify_via_Email__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Select if the parent would prefer to receve notifications via email.</inlineHelpText>
        <label>Notify via Email</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Notify_via_SMS__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Select if parent would prefer to receve notifications via SMS text message.</inlineHelpText>
        <label>Notify via SMS</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Preferred_Language__c</fullName>
        <description>Used for parent/guardian to determine what language to send notifications/written information. Replacing &quot;Receive written information in Spanish?&quot; checkbox so as to make more modular and allow for multiple possible languages.</description>
        <inlineHelpText>Displays the language that the student or parent/guardian wishes to receive emails and/or SMS notifications in. Current options are English and Spanish.</inlineHelpText>
        <label>Preferred Language</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>English</fullName>
                    <default>true</default>
                    <label>English</label>
                </value>
                <value>
                    <fullName>Spanish</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Student__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>This field provides a link to the most recent Student record.</inlineHelpText>
        <label>Student</label>
        <referenceTo>Student__c</referenceTo>
        <relationshipLabel>Contacts</relationshipLabel>
        <relationshipName>Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/HW_Tracker__c.object
<CustomObject>
    <fields>
        <fullName>Notification_Required__c</fullName>
        <description>Checks if HW Assignment Record requires notification today</description>
        <formula>IF(
AND (
Responsibility_Center__c = TODAY(),
Due_Date__c = TODAY(),
TEXT(Picklist_Value__r.Internal_Code__c) = &quot;sf_missing&quot;
),
&quot;Yes&quot;,
&quot;No&quot;
)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>First Notification Required?</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Picklist_Value__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Status</label>
        <referenceTo>Picklist_Value__c</referenceTo>
        <relationshipName>Homework_Tracking</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Received_First_Alert__c</fullName>
        <defaultValue>false</defaultValue>
        <description>When checks, removes it from the second alert</description>
        <inlineHelpText>Did Parent/Guardian of this Student receive the an Alert?</inlineHelpText>
        <label>Received Today&apos;s Alert?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Second_Notification_Required__c</fullName>
        <formula>IF(
AND (
Responsibility_Center__c = TODAY(),
Due_Date__c = TODAY(),

Case(Picklist_Value__r.Internal_Code__c, 
&quot;sf_missing&quot;, &quot;Yes&quot;,
&quot;sf_incomplete&quot;, &quot;Yes&quot;,
&quot;No&quot;) = &quot;Yes&quot;),

&quot;Yes&quot;,
&quot;No&quot;
)</formula>
        <label>Second Notification Required?</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Student__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Student</label>
        <referenceTo>Student__c</referenceTo>
        <relationshipName>Homework_Tracking</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Homework</label>
    <nameField>
        <displayFormat>HT-{000000}</displayFormat>
        <label>HT ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Homework</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Section__c.object
<CustomObject>
    <fields>
        <fullName>School__c</fullName>
        <label>School</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Sections</relationshipLabel>
        <relationshipName>Sections</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Section</label>
    <nameField>
        <label>Section Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sections</pluralLabel>
    <recordTypes>
        <fullName>Published</fullName>
        <active>true</active>
        <description>Sections that have been Published and are Viewable by Standard Users</description>
        <label>Published</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Student__c.object
<CustomObject>
    <fields>
        <fullName>School__c</fullName>
        <inlineHelpText>Displays the name of the student&apos;s current SchoolForce school. You can click on the link to see the details of this school.</inlineHelpText>
        <label>School</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Students</relationshipLabel>
        <relationshipName>Students</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Student_Last_Name__c</fullName>
        <inlineHelpText>Displays the student&apos;s last name.</inlineHelpText>
        <label>Student Last Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Student__c</fullName>
        <inlineHelpText>Displays the student&apos;s middle name.</inlineHelpText>
        <label>Student Middle Name</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <label>Student</label>
    <nameField>
        <label>Student Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Students</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Student_PG__c.object
<CustomObject>
    <fields>
        <fullName>Parent_Guardian_c__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Parent/Guardian (c)</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Students</relationshipLabel>
        <relationshipName>Student_PG</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Student__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Student</label>
        <referenceTo>Student__c</referenceTo>
        <relationshipLabel>Parents/Guardians</relationshipLabel>
        <relationshipName>Student_PG</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Student_c__c</fullName>
        <label>Student (c)</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Parents/Guardians</relationshipLabel>
        <relationshipName>Student_PG1</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Student/PG</label>
    <nameField>
        <displayFormat>SPG-{000000}</displayFormat>
        <label>Student/PG ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Student/PG</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Student_Section__c.object
<CustomObject>
    <fields>
        <fullName>School__c</fullName>
        <formula>Student__r.School__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>School</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Student__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Student</label>
        <referenceTo>Student__c</referenceTo>
        <relationshipLabel>Section</relationshipLabel>
        <relationshipName>Student_Section</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Student/Section</label>
    <nameField>
        <displayFormat>SS-{000000}</displayFormat>
        <label>Student/Section ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Student/Section</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Time_Element__c.object
<CustomObject>
    <fields>
        <fullName>Picklist_Value__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Picklist Value</label>
        <referenceTo>Picklist_Value__c</referenceTo>
        <relationshipLabel>Time</relationshipLabel>
        <relationshipName>Time</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>School__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>School</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Time</relationshipLabel>
        <relationshipName>Time</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Time</label>
    <nameField>
        <displayFormat>T-{000000}</displayFormat>
        <label>Time Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Time</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/Homework_SoqlUtils.cls
global class Homework_SoqlUtils {
	public static String HWAlertQuery1 = 'Select Student__c, Student__r.Student_Last_Name__c'+
										' From HW_Tracker__c'+ 
										' WHERE Received_First_Alert__c = FALSE'+
										' AND Notification_Required__c = \'Yes\''+
										' AND Student__c != null';	  
	
	public static String HWAlertQuery2 = 'Select Student__c, Student__r.Student_Last_Name__c'+
										' From HW_Tracker__c'+ 
										' WHERE Received_First_Alert__c = FALSE'+
										' AND Second_Notification_Required__c = \'Yes\''+
										' AND Student__c != null';	  
	
    
			
	public static List<Student_PG__c> getParentalInfo(id studentId){
		List<Student_PG__c> pgList = new List<Student_PG__c>();
		try{
			pgList = [select Student_c__r.FirstName, Student_c__r.LastName, Student_c__c, Student__c
							,Student__r.School__c, Student__r.Student_Last_Name__c
							,Parent_Guardian_c__r.Preferred_Language__c, Parent_Guardian_c__r.Notify_via_SMS__c
							,Parent_Guardian_c__r.Notify_via_Email__c, Parent_Guardian_c__r.Email_to_SMS_Address__c
							,Parent_Guardian_c__r.Email, Parent_Guardian_c__c, Id
						from Student_PG__c
						where Student__c = :studentID];
		} catch (Exception e) {
		}
		return pgList;
	}
	
	public static List<AggregateResult> getHWStatInfo(Set<Id> studentIds){
		List<AggregateResult> groupedResults = new List<AggregateResult>();
		try{
			groupedResults = [Select Student__c s, Picklist_Value__r.Category__c pv, count(Id) scount 
							  From HW_Tracker__c
							  WHERE Student__c IN :studentIds
							  GROUP BY Student__c, Picklist_Value__r.Category__c];
		}catch (Exception e){
		}
		return groupedResults;
	}
	
	public static List<Time_Element__c> getDueReportingPeriod(date dueDate){
		List<Time_Element__c> reportingPeriods = new List<Time_Element__c>();
		try{
			reportingPeriods = [Select Id 
								from Time_Element__c 
								WHERE Date_Start_Date__c <= :dueDate 
								AND End_Date__c >= :dueDate
								AND Reporting_Period__c = true];
		} catch (Exception e){
		}
		return reportingPeriods;
	}
	
	public static List<Student__c> getStudentList(boolean isHomeroom, String section){
		List<Student__c> students = new List<Student__c>();
		try{
			string query = 'Select of_Missing_Homework__c, of_Late_Homework__c, Name, Id'+
						   ',Student__c.Student_Last_Name__c,Student_First_Name__c'+
								',(Select Id, Section__c, section__r.Has_Homework__c, section__r.name'+
										  ',Section__r.Active__c, Section__r.Course__r.Name, Section__r.Course__c'+ 
								' From Student_Section__r'+
								' WHERE section__r.Has_Homework__c = true'+ 
 								' AND section__r.Active__c = true'+
								' AND Active__c = true' +
								' AND Section__r.RecordType.DeveloperName = \'Published\'';
			if(!isHomeroom){
				query +=		' AND Section__c = :section';
			}
			query +=			' Order By Section__r.Course__r.Name ASC)'+
							' From Student__c '+ 
							' WHERE Id IN (Select Student__c'+
											' from Student_Section__c'+
											' WHERE Section__c = :section'+
											' AND Active__c = true)'+
							' AND Active__c = true' + 
							' Order BY Student_Last_Name__c ASC, Student_First_Name__c ASC';
			students = database.query(query);
		} catch (Exception e) {
		}
		return students;
	}
	
	public static List<HW_Tracker__c> getHomework(Date dueDate, id section){
		List<HW_Tracker__c> hw = new List<HW_Tracker__c>();
		try{
			hw = [Select Student__c, Student_Section__c, Student_Section__r.Section__c, Extension_Date__c, Due_Date__c
						 ,Responsibility_Center__c, Id, HW_Status__c, Comments__c, Picklist_Value__c, Student_Section__r.Section__r.Course__c
				  From HW_Tracker__c 
				  WHERE due_date__c = :dueDate
				  AND Student__c IN (Select Student__c 
											from Student_Section__c 
											where Section__c = :section)];
		} catch (Exception e) {
		}
		return hw;
	}
}