objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Student__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>This field provides a link to the most recent Student record.</inlineHelpText>
        <label>Student</label>
        <referenceTo>Student__c</referenceTo>
        <relationshipLabel>Contacts</relationshipLabel>
        <relationshipName>Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <recordTypes>
        <fullName>Student</fullName>
        <active>true</active>
        <description>This record type is for students</description>
        <label>Student</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Student__c.object
<CustomObject>
    <fields>
        <fullName>External_Evaluation_ID__c</fullName>
        <label>External Evaluation ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Student__c</fullName>
        <inlineHelpText>Displays the student&apos;s middle name.</inlineHelpText>
        <label>Student Middle Name</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <label>Student</label>
    <nameField>
        <label>Student Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Students</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/StudentUpdateBatchTest.cls
@IsTest
public without sharing class StudentUpdateBatchTest {

    public static testMethod void testBatch() {
        testDataSetupUtil_v2.setUPCoreData(5);
        testDataSetupUtil_v2.setUPStaffData(5);
        List<Contact> studContactsList = testDataSetupUtil_v2.getContacts(5, 'Student', null);
        List<sObject> studentsList = testDataSetupUtil_v2.getStudentsWithLocalId('123abc', 5, 'Student', studContactsList);
        for (sObject stud : studentsList) {
            stud.put('External_Evaluation_ID__c','');
        }
        Test.StartTest();
            StudentUpdateBatch studentUpdateBatchJob = new StudentUpdateBatch();
            Database.QueryLocator ql = studentUpdateBatchJob.start(null);
            studentUpdateBatchJob.execute(null, studentsList);
            studentUpdateBatchJob.finish(null);
        Test.StopTest();

        System.AssertEquals(
                Database.countquery('SELECT COUNT()'
                        +' FROM Student__c WHERE External_Evaluation_ID__c = \'\''),
                0);
    }
}