objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Email_to_SMS_Address__c</fullName>
        <formula>IF (
AND (
NOT(ISBLANK( MobilePhone )),
NOT(ISBLANK( TEXT(Wireless_Provider__c )))
),
Case ( Wireless_Provider__c,
&quot;ATT&quot;, SUBSTITUTE( SUBSTITUTE( SUBSTITUTE( SUBSTITUTE( SUBSTITUTE( MobilePhone , &apos;.&apos;, &apos;&apos;) , &apos; &apos;, &apos;&apos;) , &apos;-&apos;, &apos;&apos;) , &apos;)&apos;, &apos;&apos;) , &apos;(&apos;, &apos;&apos;)&amp;&quot;@txt.att.net&quot;,
&quot;Verizon&quot;, SUBSTITUTE( SUBSTITUTE( SUBSTITUTE( SUBSTITUTE( SUBSTITUTE( MobilePhone , &apos;.&apos;, &apos;&apos;) , &apos; &apos;, &apos;&apos;) , &apos;-&apos;, &apos;&apos;) , &apos;)&apos;, &apos;&apos;) , &apos;(&apos;, &apos;&apos;)&amp;&quot;@vtext.com&quot;,
&quot;Sprint&quot;,SUBSTITUTE( SUBSTITUTE( SUBSTITUTE( SUBSTITUTE( SUBSTITUTE( MobilePhone , &apos;.&apos;, &apos;&apos;) , &apos; &apos;, &apos;&apos;) , &apos;-&apos;, &apos;&apos;) , &apos;)&apos;, &apos;&apos;) , &apos;(&apos;, &apos;&apos;)&amp;&quot;@messaging.sprintpcs.com&quot;,
&quot;T-Mobile&quot;,SUBSTITUTE( SUBSTITUTE( SUBSTITUTE( SUBSTITUTE( SUBSTITUTE( MobilePhone , &apos;.&apos;, &apos;&apos;) , &apos; &apos;, &apos;&apos;) , &apos;-&apos;, &apos;&apos;) , &apos;)&apos;, &apos;&apos;) , &apos;(&apos;, &apos;&apos;)&amp;&quot;@tmomail.net&quot;,
&quot;Virgin Mobile&quot;, SUBSTITUTE( SUBSTITUTE( SUBSTITUTE( SUBSTITUTE( SUBSTITUTE( MobilePhone , &apos;.&apos;, &apos;&apos;) , &apos; &apos;, &apos;&apos;) , &apos;-&apos;, &apos;&apos;) , &apos;)&apos;, &apos;&apos;) , &apos;(&apos;, &apos;&apos;)&amp;&quot;@vmobl.com&quot;,
&quot;&quot;),

&quot;&quot;)</formula>
        <inlineHelpText>SchoolForce automatically updates this field using the information you enter into the Mobile Phone and Mobile Carrier fields. It is used for sending attendance alerts to parents via SMS.</inlineHelpText>
        <label>Email to SMS Address</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Notify_via_Email__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Select if the parent would prefer to receve notifications via email.</inlineHelpText>
        <label>Notify via Email</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Notify_via_SMS__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Select if parent would prefer to receve notifications via SMS text message.</inlineHelpText>
        <label>Notify via SMS</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Notification_Settings__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <fields>
        <fullName>Display_Name__c</fullName>
        <description>Display name recipient will see when receiving notification from Schoolforce</description>
        <label>Display Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Reply_To__c</fullName>
        <description>Sets the reply To for notifications from Schoolforce to Parent/Guardians</description>
        <label>Reply To</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Subject__c</fullName>
        <description>Subject of the notification</description>
        <label>Subject</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>Notification Settings</label>
</CustomObject>

objects/Student_PG__c.object
<CustomObject>
    <fields>
        <fullName>Parent_Guardian_c__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Parent/Guardian (c)</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Students</relationshipLabel>
        <relationshipName>Student_PG</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Student_c__c</fullName>
        <label>Student (c)</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Parents/Guardians</relationshipLabel>
        <relationshipName>Student_PG1</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Student/PG</label>
    <nameField>
        <displayFormat>SPG-{000000}</displayFormat>
        <label>Student/PG ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Student/PG</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/NotificationUtils.cls
public class NotificationUtils{

	public class sendnotification {

		public sendnotification (Student_PG__c pgnotifier, Map<String, String> sComms) {
			//Check they have a Email address, should receive email alerts, and that there is text for an email alert for this notification
			Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
			List<String> aemail = new List<String>();
			Notification_Settings__c ns = Notification_Settings__c.getOrgDefaults();
			
			mail.setReplyTo(ns.reply_to__c);  
			mail.setSenderDisplayName(ns.display_name__c);  
			mail.setSubject(ns.Subject__c);  
			if (pgnotifier.Parent_Guardian_c__r.Notify_via_Email__c == true && pgnotifier.Parent_Guardian_c__r.Email != null && sComms.containskey('Email')) {
				aemail.add(pgnotifier.Parent_Guardian_c__r.Email);
				mail.setPlainTextBody(pgnotifier.Student_c__r.FirstName + ' ' + pgnotifier.Student_c__r.LastName + ' ' + sComms.get('Email'));
				}
				//Check they have a SMS address, should receive alerts, and that there is text for an sms alert for this notification
			if (pgnotifier.Parent_Guardian_c__r.Notify_via_SMS__c == true && pgnotifier.Parent_Guardian_c__r.Email_to_SMS_Address__c != null && sComms.containskey('SMS')) {
				aemail.add(pgnotifier.Parent_Guardian_c__r.Email_to_SMS_Address__c);			
				mail.setPlainTextBody(pgnotifier.Student_c__r.FirstName + ' ' + pgnotifier.Student_c__r.LastName + ' ' + sComms.get('SMS'));
			}
			mail.setToAddresses(aemail);
			Messaging.sendEmail(new Messaging.SingleEmailMessage[] { mail });

			
		} //end send Notification constructor
	} //end send Notification class
}