objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>true</defaultValue>
        <inlineHelpText>Schools/organizations can choose to use this field when a Contact record is active. When Contact records are created through SchoolForce Setup, this check box is selected.</inlineHelpText>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Entry_Date__c</fullName>
        <inlineHelpText>Displays the student&apos;s date of entry. This field is automatically updated if the same field on the Student record is updated.</inlineHelpText>
        <label>Entry Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Exit_Date__c</fullName>
        <description>The date a student left the school or discontinued schooling prior to graduation or matriculation.</description>
        <inlineHelpText>Displays the date a student left the school or discontinued schooling prior to graduation or matriculation. This field is automatically updated if the same field on the Student record is updated.</inlineHelpText>
        <label>Exit Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Gender__c</fullName>
        <inlineHelpText>Displays the contact&apos;s gender. This field is automatically updated if the same field on the Student record is updated.</inlineHelpText>
        <label>Gender</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Male</fullName>
                </value>
                <value>
                    <fullName>Female</fullName>
                </value>
                <value>
                    <fullName>Gender Neutral</fullName>
                </value>
                <value>
                    <fullName>U</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Reference_Id__c</fullName>
        <description>To store Student/Parent Id as External Id</description>
        <externalId>true</externalId>
        <inlineHelpText>Displays the unique reference ID for the student.  This value should be the same as the Student Id on the associated Student record(s).</inlineHelpText>
        <label>Reference Id</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Student_Id__c</fullName>
        <formula>Student__r.Id</formula>
        <inlineHelpText>Displays the 15-digit Salesforce ID of the Student record associated with this contact.</inlineHelpText>
        <label>Student Id</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Student__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>This field provides a link to the most recent Student record.</inlineHelpText>
        <label>Student</label>
        <referenceTo>Student__c</referenceTo>
        <relationshipLabel>Contacts</relationshipLabel>
        <relationshipName>Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <recordTypes>
        <fullName>Student</fullName>
        <active>true</active>
        <description>This record type is for students</description>
        <label>Student</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Student__c.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>true</defaultValue>
        <inlineHelpText>Indicates whether or not this Student record is active. If checked, then this is the current Student record. If unchecked, this is an old Student record.</inlineHelpText>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>CY_YOY_Student_EEID__c</fullName>
        <label>CY YOY Student EEID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Entry_Date__c</fullName>
        <inlineHelpText>Displays the student&apos;s first day of school in the current school year.</inlineHelpText>
        <label>Entry Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Exit_Date__c</fullName>
        <inlineHelpText>Displays the date the student was withdrawn. SchoolForce updates this field when a student is withdrawn through the Section Wizard.</inlineHelpText>
        <label>Exit Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>External_Evaluation_ID__c</fullName>
        <label>External Evaluation ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Gender__c</fullName>
        <inlineHelpText>Displays the student&apos;s gender.</inlineHelpText>
        <label>Gender</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Male</fullName>
                </value>
                <value>
                    <fullName>Female</fullName>
                </value>
                <value>
                    <fullName>Neutral</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Individual__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Displays the name for the Contact record associated to this Student record. You can click the link to view the student&apos;s Contact record.</inlineHelpText>
        <label>Individual Record</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Student Records</relationshipLabel>
        <relationshipName>Students</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Reference_Id__c</fullName>
        <externalId>true</externalId>
        <inlineHelpText>Displays the Salesforce ID for this Student record. Do not modify this field.</inlineHelpText>
        <label>Reference Id</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>School_Reference_Id__c</fullName>
        <formula>School__r.Reference_Id__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>School Reference Id</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Setup_Year_Name__c</fullName>
        <formula>Setup__r.Year__r.Name__c</formula>
        <label>Setup Year Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Student_Exit_Reason__c</fullName>
        <label>Student Exit Reason</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>SS_Exit_Reason</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Student_Id__c</fullName>
        <inlineHelpText>Displays the student&apos;s ID. This field displays on report cards, progress reports, and transcripts. It must be unique; SchoolForce uses this ID to link the Student record with the correct Contact record.</inlineHelpText>
        <label>Student Id</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Student__c</fullName>
        <inlineHelpText>Displays the student&apos;s middle name.</inlineHelpText>
        <label>Student Middle Name</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <label>Student</label>
    <nameField>
        <label>Student Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Students</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Student_Section__c.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Reference_ID__c</fullName>
        <description>Concatenated unique id = StudentReference_ID__c + Reference Legacy_ID__c</description>
        <externalId>true</externalId>
        <label>Reference ID</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>School_Reference_Id__c</fullName>
        <formula>Student__r.School__r.Reference_Id__c</formula>
        <label>School Reference Id</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Setup_Year_Name__c</fullName>
        <formula>Student__r.Setup__r.Year__r.Name__c</formula>
        <label>Setup Year Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Student_Id__c</fullName>
        <formula>Student__r.Student_Id__c</formula>
        <label>Student Id</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Student__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Student</label>
        <referenceTo>Student__c</referenceTo>
        <relationshipLabel>Section</relationshipLabel>
        <relationshipName>Student_Section</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Student/Section</label>
    <nameField>
        <displayFormat>SS-{000000}</displayFormat>
        <label>Student/Section ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Student/Section</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

globalValueSets/SS_Exit_Reason.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Accidental Enrollment</fullName>
    </customValue>
    <customValue>
        <fullName>Student no longer available</fullName>
    </customValue>
    <customValue>
        <fullName>School Year ended</fullName>
    </customValue>
    <customValue>
        <fullName>ACM no longer available</fullName>
    </customValue>
    <customValue>
        <fullName>Deactivated by trigger.</fullName>
    </customValue>
    <customValue>
        <fullName>Teacher scheduling change/reassignment</fullName>
        <isActive>false</isActive>
        <label>Teacher scheduling change/reassignment</label>
    </customValue>
    <customValue>
        <fullName>Chronic absenteeism</fullName>
        <isActive>false</isActive>
        <label>Chronic absenteeism</label>
    </customValue>
    <customValue>
        <fullName>Student referred for more intensive services by other personnel</fullName>
        <isActive>false</isActive>
        <label>Student referred for more intensive services by other personnel</label>
    </customValue>
    <customValue>
        <fullName>Transferred to another City Year school</fullName>
        <isActive>false</isActive>
        <label>Transferred to another City Year school</label>
    </customValue>
    <customValue>
        <fullName>Behavior significantly distracts sessions</fullName>
        <isActive>false</isActive>
        <label>Behavior significantly distracts sessions</label>
    </customValue>
    <customValue>
        <fullName>Student scheduling change prevents regular participation</fullName>
        <isActive>false</isActive>
        <label>Student scheduling change prevents regular participation</label>
    </customValue>
    <customValue>
        <fullName>Student met exit criteria</fullName>
        <isActive>false</isActive>
        <label>Student met exit criteria</label>
    </customValue>
    <customValue>
        <fullName>Student completed participation criteria, though should be reenrolled in subsequent section</fullName>
        <isActive>false</isActive>
        <label>Student completed participation criteria, though should be reenrolled in subsequent section</label>
    </customValue>
    <customValue>
        <fullName>Corps member has left the school or service</fullName>
        <isActive>false</isActive>
        <label>Corps member has left the school or service</label>
    </customValue>
    <masterLabel>SS Exit Reason</masterLabel>
</GlobalValueSet>

classes/Test_StudentTrigger.cls
@isTest
private class Test_StudentTrigger {

	public static void createTestData(){
		testDataSetupUtil_v2.setUPCoreData(5);
        testDataSetupUtil_v2.setUPStaffData(5);
        testDataSetupUtil_v2.setUPStudentData(5);
	}
	
    static testMethod void testOnDelete() {
        createTestData();
        
        Test.startTest();
            delete TestDataSetupUtil_v2.studentsList[0];
            
            List<Student_Section__c> ss = [select id from Student_Section__c where Student__c =:TestDataSetupUtil_v2.studentsList[0].id];
            system.assert(ss.size() == 0);
        Test.stopTest();
    }
     
    static testMethod void testIdUpdateOnContacts() {
     createTestData();       
       Test.startTest();
       TestDataSetupUtil_v2.studentsList[0].Reference_Id__c = 'something random';
       TestDataSetupUtil_v2.studentsList[0].Student_Id__c = 'NCC1701';
       update TestDataSetupUtil_v2.studentsList[0];
    
       Contact c = [select id, Reference_Id__c from Contact where id =: TestDataSetupUtil_v2.studentsList[0].Individual__c];
       Student__c s = [select id, Student_Id__c, Reference_Id__c, School_Reference_Id__c, Setup_Year_Name__c from Student__c where id =: TestDataSetupUtil_v2.studentsList[0].id];
       system.assertEquals('NCC1701'+'_'+s.School_Reference_Id__c+'_'+s.Setup_Year_Name__c, s.Reference_Id__c);
       system.assertEquals(s.Student_Id__c, c.Reference_Id__c);

       Test.stopTest();
    }
  
    static testMethod void testStudentSectionActivation() {
        createTestData();
        Test.startTest();
            TestDataSetupUtil_v2.studentsList[0].Active__c = false;
            TestDataSetupUtil_v2.studentsList[0].exit_date__c = TestDataSetupUtil_v2.semester.date_start_date__c.addMonths(1);
            TestDataSetupUtil_v2.studentsList[0].Student_Exit_Reason__c = CT_core_triggerUtils.SECTIONEXITREASONBYTRIGGER;
            update TestDataSetupUtil_v2.studentsList[0];
            
            List<Student_Section__c> ss = [select id, Active__c from Student_Section__c where Student__c =: TestDataSetupUtil_v2.studentsList[0].id];
            system.assert(ss.size()>0);
            system.assert(!ss[0].Active__c);
            
            TestDataSetupUtil_v2.studentsList[0].Active__c = true;
            TestDataSetupUtil_v2.studentsList[0].Entry_Date__c = TestDataSetupUtil_v2.semester.date_start_date__c.addMonths(1);
            update TestDataSetupUtil_v2.studentsList[0];
            
            ss = [select id, Active__c from Student_Section__c where Student__c =: TestDataSetupUtil_v2.studentsList[0].id];
            system.assert(ss.size()>0);
            system.assert(!ss[0].Active__c);
    }
    
    static testMethod void testIdAndFieldUpdateOnContacts() {
    	createTestData();
        
        Test.startTest();
            TestDataSetupUtil_v2.studentsList[0].Reference_Id__c = 'something random';
            TestDataSetupUtil_v2.studentsList[0].Student_Id__c = 'NCC1701';
            
            system.assert(TestDataSetupUtil_v2.studentsList[0].Gender__c != 'Male');
            system.assert(TestDataSetupUtil_v2.studentsList[0].Active__c);
            TestDataSetupUtil_v2.studentsList[0].Gender__c = 'Male';
            update TestDataSetupUtil_v2.studentsList[0];
            
            Contact c = [select id, Reference_Id__c, Gender__c from Contact where id =: TestDataSetupUtil_v2.studentsList[0].Individual__c];
	       Student__c s = [select id, Student_Id__c, Reference_Id__c, School_Reference_Id__c, Setup_Year_Name__c from Student__c where id =: TestDataSetupUtil_v2.studentsList[0].id];
       		system.assertEquals('NCC1701'+'_'+s.School_Reference_Id__c+'_'+s.Setup_Year_Name__c, s.Reference_Id__c);
            system.assertEquals('NCC1701', c.Reference_Id__c);
            system.assertEquals('Male', c.Gender__c);
        Test.stopTest();
    }

    static testMethod void testExternalEvaluatedProcessEndsWithError() {
        testDataSetupUtil_v2.setUPCoreData(5);
        testDataSetupUtil_v2.setUPStaffData(5);
        List<Contact> studContactsList = testDataSetupUtil_v2.getContacts(5, 'Student', null);
        Test.startTest();
            List<Student__c> studentsList = testDataSetupUtil_v2.getStudentsWithLocalId('!!!!!!', 5, 'Student', studContactsList);
        Test.stopTest();
        studentsList = [SELECT External_Evaluation_ID__c, CY_YOY_Student_EEID__c
                        FROM Student__c WHERE Id IN:studentsList];
        for(Student__c student : studentsList) {
            System.assertEquals('Invalid - Local Student ID is not valid, unable to calculate', student.External_Evaluation_ID__c);
            System.assertEquals('Invalid - Local Student ID is not valid, unable to calculate', student.CY_YOY_Student_EEID__c);
        }
    }

    static testMethod void testExternalEvaluatedProcessEndsWithErrorNotEnoughCharacters() {
        testDataSetupUtil_v2.setUPCoreData(5);
        testDataSetupUtil_v2.setUPStaffData(5);
        List<Contact> studContactsList = testDataSetupUtil_v2.getContacts(5, 'Student', null);
        Test.startTest();
            List<Student__c> studentsList = testDataSetupUtil_v2.getStudentsWithLocalId('123', 5, 'Student', studContactsList);
        Test.stopTest();
        studentsList = [SELECT External_Evaluation_ID__c, CY_YOY_Student_EEID__c
                        FROM Student__c WHERE Id IN:studentsList];
        for(Student__c student : studentsList) {
            System.assertEquals('767778767778', student.External_Evaluation_ID__c);
            System.assertEquals('Invalid - Local Student ID Less Than 5 characters', student.CY_YOY_Student_EEID__c);
        }
    }

    static testMethod void testExternalEvaluatedProcessSuccess() {
        testDataSetupUtil_v2.setUPCoreData(5);
        testDataSetupUtil_v2.setUPStaffData(5);
        List<Contact> studContactsList = testDataSetupUtil_v2.getContacts(5, 'Student', null);
        Test.startTest();
        List<Student__c> studentsList = testDataSetupUtil_v2.getStudentsWithLocalId('123abc', 5, 'Student', studContactsList);
        Test.stopTest();
        studentsList = [SELECT External_Evaluation_ID__c, CY_YOY_Student_EEID__c
        FROM Student__c WHERE Id IN:studentsList];
        for(Student__c student : studentsList) {
            System.assertEquals('77785051527677785051', student.External_Evaluation_ID__c);
            System.assertEquals('7141717171717171717171715357585871717171526949505154', student.CY_YOY_Student_EEID__c);
        }
    }
    
	 
}