objects/Course__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Links Courses to the School</description>
        <label>School</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Courses</relationshipLabel>
        <relationshipName>Courses</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Reference_Id__c</fullName>
        <description>School-Course Name Unique Key</description>
        <externalId>true</externalId>
        <label>Reference Id</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>Course</label>
    <nameField>
        <label>Course Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Courses</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/Period__c.object
<CustomObject>
    <fields>
        <fullName>Schedule_Template__c</fullName>
        <label>Schedule Template</label>
        <referenceTo>Schedule_Template__c</referenceTo>
        <relationshipLabel>Periods</relationshipLabel>
        <relationshipName>Periods</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Time__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Time</label>
        <referenceTo>Time_Element__c</referenceTo>
        <relationshipLabel>Periods</relationshipLabel>
        <relationshipName>Periods</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Period</label>
    <nameField>
        <label>Period Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Periods</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Room__c.object
<CustomObject>
    <fields>
        <fullName>Reference_Id__c</fullName>
        <externalId>true</externalId>
        <label>Reference Id</label>
        <length>200</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>School__c</fullName>
        <label>School</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Rooms</relationshipLabel>
        <relationshipName>Rooms</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Room</label>
    <nameField>
        <label>Room Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Rooms</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Schedule_Template__c.object
<CustomObject>
    <fields>
        <fullName>Reference_Id__c</fullName>
        <externalId>true</externalId>
        <label>Reference Id</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Reporting_Period__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Reporting Period</label>
        <referenceTo>Time_Element__c</referenceTo>
        <relationshipLabel>Schedule Templates</relationshipLabel>
        <relationshipName>Schedule_Templates</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Schedule Template</label>
    <nameField>
        <label>Schedule Template Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Schedule Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Scheduled_Section__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>School associated to the scheduled section</description>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Scheduled Sections</relationshipLabel>
        <relationshipName>Scheduled_Sections</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Course__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Course</label>
        <referenceTo>Course__c</referenceTo>
        <relationshipName>Schedule_Templates</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Needs_Publish__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Indicator of whether this scheduled section has been published since its creation (or, if a scheduled section has been edited, whether it has been re-published)</description>
        <label>Needs Publish</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Period_Key__c</fullName>
        <description>Key that links the scheduled section to a Period if Setup is period based.</description>
        <label>Period Key</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Reference_Id__c</fullName>
        <description>Key for Section Scheduled: Setup-Reporting Period-Teacher-Group/Period</description>
        <externalId>true</externalId>
        <label>Reference Id</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Reporting_Period__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Reporting Period</label>
        <referenceTo>Time_Element__c</referenceTo>
        <relationshipLabel>Scheduled Sections</relationshipLabel>
        <relationshipName>Scheduled_Sections</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Room__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Room</label>
        <referenceTo>Room__c</referenceTo>
        <relationshipName>Schedule_Templates</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Schedule_Group_Section__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup field to Section object populated with the related Schedule Group</description>
        <label>Schedule Group (Section)</label>
        <referenceTo>Section__c</referenceTo>
        <relationshipLabel>Scheduled Sections (Schedule Group (Section))</relationshipLabel>
        <relationshipName>Scheduled_Sections1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Schedule_Template__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Schedule Template</label>
        <referenceTo>Schedule_Template__c</referenceTo>
        <relationshipLabel>Scheduled Sections</relationshipLabel>
        <relationshipName>Scheduled_Sections</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Section_Reference_Id__c</fullName>
        <externalId>true</externalId>
        <label>Section Reference Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Section_ReportingPeriod__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Section/ReportingPeriod</label>
        <referenceTo>Section_ReportingPeriod__c</referenceTo>
        <relationshipLabel>Scheduled Sections</relationshipLabel>
        <relationshipName>Scheduled_Sections</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Section__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Section</label>
        <referenceTo>Section__c</referenceTo>
        <relationshipLabel>Scheduled Sections</relationshipLabel>
        <relationshipName>Scheduled_Sections</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Staff__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Staff</label>
        <referenceTo>Staff__c</referenceTo>
        <relationshipName>Schedule_Templates</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Scheduled Section</label>
    <nameField>
        <label>Scheduled Section Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Scheduled Sections</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Section__c.object
<CustomObject>
    <fields>
        <fullName>Course__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Select the course associated to the section you want to create.</inlineHelpText>
        <label>Course</label>
        <referenceTo>Course__c</referenceTo>
        <relationshipLabel>Sections</relationshipLabel>
        <relationshipName>Sections</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Period__c</fullName>
        <label>Period</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Reference_Id__c</fullName>
        <externalId>true</externalId>
        <label>Reference Id</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Reporting_Period__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Usually the only reporting period; could be the first if the section spans multiple reporting periods.</description>
        <label>Reporting Period</label>
        <referenceTo>Time_Element__c</referenceTo>
        <relationshipLabel>Sections (First Reporting Period)</relationshipLabel>
        <relationshipName>Sections1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Room__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Room</label>
        <referenceTo>Room__c</referenceTo>
        <relationshipLabel>Sections</relationshipLabel>
        <relationshipName>Sections</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Section__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Recursive lookup for groups</description>
        <label>Section</label>
        <referenceTo>Section__c</referenceTo>
        <relationshipLabel>Groups in Section</relationshipLabel>
        <relationshipName>Sections1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Staff__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Staff</label>
        <referenceTo>Staff__c</referenceTo>
        <relationshipLabel>Sections</relationshipLabel>
        <relationshipName>Sections</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Time__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Time</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Time_Element__c.Picklist_Value__r.Name</field>
                <operation>equals</operation>
                <value>Year</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Time_Element__c</referenceTo>
        <relationshipLabel>Sections</relationshipLabel>
        <relationshipName>Sections</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Section</label>
    <nameField>
        <label>Section Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sections</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Section_ReportingPeriod__c.object
<CustomObject>
    <fields>
        <fullName>Period__c</fullName>
        <label>Period</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Section__c</fullName>
        <label>Section</label>
        <referenceTo>Section__c</referenceTo>
        <relationshipLabel>Section/ReportingPeriod</relationshipLabel>
        <relationshipName>Section_ReportingPeriod</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Time__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Time</label>
        <referenceTo>Time_Element__c</referenceTo>
        <relationshipLabel>Section/ReportingPeriod</relationshipLabel>
        <relationshipName>Section_ReportingPeriod</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Section/ReportingPeriod</label>
    <nameField>
        <displayFormat>SR-{000000}</displayFormat>
        <label>Section/ReportingPeriod</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Section/ReportingPeriod</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Staff__c.object
<CustomObject>
    <fields>
        <fullName>Reference_Id__c</fullName>
        <externalId>true</externalId>
        <label>Reference Id</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>Staff</label>
    <nameField>
        <label>Staff Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Staff</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

classes/Scheduled_Section_Utils.cls
public with sharing class Scheduled_Section_Utils {



	public static void processBeforeInsert(List <Scheduled_Section__c> newList){
		updSsFieldsForGroupAgenda(newList);
		updSsFieldsfromSrp(newList, null, null);
		validateGroupAgendaView(newList);
	}
	public static void processAfterInsert(Map <Id, Scheduled_Section__c> newMap){
	
	}
	public static void processBeforeUpdate(Map <Id, Scheduled_Section__c> newMap, Map<Id, Scheduled_Section__c> oldMap){
		updSsFieldsfromSrp(null, newMap, oldMap);
		validateGroupAgendaView(newMap.values());
		updateNeedsPublishFlag(newMap, oldMap);
	}
	public static void processAfterUpdate(Map <Id, Scheduled_Section__c> newMap, Map<Id, Scheduled_Section__c> oldMap){
	
	}
	public static void processBeforeDelete(Map <Id, Scheduled_Section__c> oldMap){
	
	}
	
	public static void updateNeedsPublishFlag (Map <Id, Scheduled_Section__c> newMap, Map<Id, Scheduled_Section__c> oldMap){
		for (Scheduled_Section__c ss: newMap.values()){
			Scheduled_Section__c oldSs = oldMap.get(ss.id);
			if (ss.Staff__c!=oldSs.Staff__c) ss.needs_publish__c = true;
			else if (ss.Room__c!=oldSs.Room__c) ss.needs_publish__c = true;
			else if (ss.Period_Key__c!=oldSs.Period_Key__c) ss.needs_publish__c = true;
		}
	}
	
		public static void updSsFieldsForGroupAgenda(List <Scheduled_Section__c> ssList){
	 		if (core_TriggerUtils.bGroupAgenda){
				for (Scheduled_Section__c ss: ssList){
					ss.Reference_Id__c = ImportUtils.createScheduledSectionKey(ss.Account__c,ss.Schedule_Group_Section__c,ss.Course__c,ss.Reporting_Period__c,ss.Schedule_Template__c);
					ss.Section_Reference_Id__c = ImportUtils.createSectionReferenceKey(ss.Account__c,ss.Schedule_Group_Section__c,ss.course__c,ss.Reporting_Period__c);
				}
			}
	}
	
	public static String generateScheduledSectionReference(Scheduled_Section__c ss){
        return ss.Section_ReportingPeriod__c+'-'+ss.Period_key__c+ss.Staff__c;
    }

	public static void updSsFieldsfromSrp (List <Scheduled_Section__c> ssList, Map <Id, Scheduled_Section__c> newMap, Map<Id, Scheduled_Section__c> oldMap){
		if (!core_TriggerUtils.bGroupAgenda){
			Set <Id> sectionRpIdSet = new Set <Id>();
			if (ssList!=null){
				for (Scheduled_Section__c ss: ssList){
					if (ss.section_reportingPeriod__c!=null){
						sectionRpIdSet.add(ss.section_reportingPeriod__c);
					}
				}
			} 
			else {
				for (Scheduled_Section__c ss: newMap.values()){
					if (ss.Section_ReportingPeriod__c!=null&& ss.Section_ReportingPeriod__c!=oldMap.get(ss.id).Section_ReportingPeriod__c)
						sectionRpIdSet.add(ss.Section_ReportingPeriod__c);
					//EE 8/30 if period changes, update SRP
					if(ss.Period_Key__c!=oldMap.get(ss.id).Period_Key__c){
						sectionRpIdSet.add(ss.Section_ReportingPeriod__c);
					}
				}
				ssList = newMap.values();
			} 
			
			if (!sectionRpIdSet.isEmpty()){
				Map <Id, Section_ReportingPeriod__c> sectionRpMap = new Map<Id, Section_ReportingPeriod__c>([select id, period__c, time__c, section__r.school__c, section__c, section__r.course__c from Section_ReportingPeriod__c where id in:sectionRpIdSet]);
				
				for (Scheduled_Section__c ss: ssList){
					if (sectionRpMap.keySet().contains(ss.Section_ReportingPeriod__c)){
						Section_ReportingPeriod__c srp = sectionRpMap.get(ss.section_reportingPeriod__c);
						ss.Account__c=srp.section__r.school__c;
						ss.Course__c=srp.section__r.course__c;
						ss.Reporting_Period__c= srp.time__c;
						ss.Section__c = srp.section__c;
						ss.reference_id__c = generateScheduledSectionReference(ss);
						if (srp.period__c!=null){
							if (srp.period__c.contains(',')){
								string [] periodArray = srp.period__c.split(',');
								Set <String> periodSet = new Set <String>();
								for (String s: periodArray)	periodSet.add(s);
								if (!periodSet.contains(ss.period_key__c)){
									srp.period__c+=','+ss.period_key__c; //handles multiple periods appropriately DE2482
								}
							}
							else {
								if (!srp.period__c.contains(ss.period_key__c)){
									srp.period__c+=','+ss.period_key__c;
								}
							}
							//EE 8/30 if period changes, remove old period from srp.Period__c DE3571
							if(oldMap!=null && oldMap.get(ss.id).Period_Key__c!=ss.Period_Key__c){
								String[] periods = srp.Period__c.split(',');
								srp.Period__c='';
								for(integer i=0; i<periods.size(); i++){
									if(periods[i]!=oldMap.get(ss.id).Period_Key__c){
										if(srp.Period__c!='') srp.Period__c += ',';
										srp.Period__c+=periods[i]; 
									}
								}
							}
						}
						else srp.period__c=ss.period_key__c;
					}
				}
				if (!sectionRpMap.keySet().isEmpty()){
					update sectionRpMap.values();
				}
			}
			updateKeys(ssList);
		}
	}
	
	public static void updateKeys(List<Scheduled_Section__c> ssList){
		for(Scheduled_Section__c ss: ssList){
			if (ss.Room__c!=null)  ss.room_key__c = ss.reporting_period__c+'-'+ss.Period_Key__c+'-'+ss.Room__c;
			ss.staff_key__c=ss.Reporting_Period__c+'-'+ss.Period_Key__c+'-'+ss.Staff__c;
		}
	}
	
	public static void validateGroupAgendaView ( List <Scheduled_Section__c> ssList){
		if (core_TriggerUtils.bGroupAgenda){
			Scheduled_Section__c enteredSs;
			for (Scheduled_Section__c ss: ssList){
					enteredSs = ss;
					if (enteredSS.start_time_text__c==null ||enteredSs.start_time_text__c==''){
						enteredSS.No_Meeting__c=true;
					}
					break;
			}
			boolean bError = false;
			boolean bTemplateError = false;
			for (Scheduled_Section__c ss: scheduler_SoqlUtils.getScheduledSectionsByTempId(enteredSS.schedule_template__c)){
					if (!enteredSS.No_Meeting__c){
					DateTime templateStartTime = core_TimeUtils.processTimeText(ss.schedule_template__r.start_time_text__c);
					DateTime templateEndTime = core_TimeUtils.processTimeText(ss.schedule_template__r.end_time_text__c);
					DateTime enteredStartTime = core_TimeUtils.processTimeText(enteredSS.start_time_text__c);
					DateTime enteredEndTime = core_TimeUtils.processTimeText(enteredSS.end_time_text__c);
					if (templateStartTime > enteredStartTime){
						bTemplateError = true;
						break;
					}	
					if (templateEndTime < enteredEndTime){ 
						bTemplateError = true;
						break; 
					}
					if (ss.Schedule_Group_Section__c==enteredSs.Schedule_Group_Section__c){
						if (enteredSS.id !=ss.id){
							if (!enteredSS.Daily_Attendance__c&&!ss.Daily_Attendance__c){
								if (enteredSS.end_time_text__c!=null&&enteredSS.end_time_text__c!=null&& ss.start_time_text__c!=null&&ss.end_time_text__c!=null){
									DateTime thisStartTime = core_TimeUtils.processTimeText(ss.start_time_text__c);
									DateTime thisEndTime = core_TimeUtils.processTimeText(ss.end_time_text__c);
								
									if (enteredStartTime< thisStartTime && enteredEndTime>thisStartTime){
										bError = true;
										break; 
									}
									else if (enteredEndTime> thisEndTime&& enteredStartTime < thisEndTime){
										bError = true;
										break;
									}
								}
							}
						}
					}
				}
			}
			if (bError) enteredSs.addError('Section cannot have overlapping times with other sections in the same template & group');
			if (bTemplateError) enteredSs.addError('Section cannot start or end outside of the associated Schedule Template start and end times');
		}
	}
	
}