objects/Course__c.object
<CustomObject>
    <fields>
        <fullName>Type__c</fullName>
        <inlineHelpText>Select the type of course. For example, the type of course may include options such as honors, AP, international baccalaureate. You can use this field for reporting purposes as well as for cohort requirements.</inlineHelpText>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>AP</fullName>
                </value>
                <value>
                    <fullName>Honors</fullName>
                </value>
                <value>
                    <fullName>IB</fullName>
                </value>
                <value>
                    <fullName>Remedial</fullName>
                </value>
                <value>
                    <fullName>Credit/No Credit</fullName>
                </value>
                <value>
                    <fullName>Points</fullName>
                </value>
                <value>
                    <fullName>Standard</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Course</label>
    <nameField>
        <label>Course Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Courses</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/Default_Assignment_Weighting__c.object
<CustomObject>
    <fields>
        <fullName>Course__c</fullName>
        <label>Course</label>
        <referenceTo>Course__c</referenceTo>
        <relationshipLabel>Default Assignment Weighting</relationshipLabel>
        <relationshipName>Default_Assignment_Weighting</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Picklist_Value__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Assignment Type</label>
        <referenceTo>Picklist_Value__c</referenceTo>
        <relationshipLabel>Default Assignment Weighting</relationshipLabel>
        <relationshipName>Default_Assignment_Weighting</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Default Assignment Weighting</label>
    <nameField>
        <displayFormat>DEFAW-{000}</displayFormat>
        <label>Default Assignment Weighting Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Default Assignment Weighting</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Meals_Setup__c.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>School__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>School</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Meals</relationshipLabel>
        <relationshipName>Meals_Setup</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Setup__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Setup</label>
        <referenceTo>Setup__c</referenceTo>
        <relationshipLabel>Meals Setup</relationshipLabel>
        <relationshipName>Meals_Setup</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Meals Setup</label>
    <nameField>
        <displayFormat>MS-{0}</displayFormat>
        <label>Meals Setup Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Meals Setup</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Picklist_Value__c.object
<CustomObject>
    <fields>
        <fullName>Setup__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Setup</label>
        <referenceTo>Setup__c</referenceTo>
        <relationshipLabel>Picklist Values</relationshipLabel>
        <relationshipName>Picklist_Values</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Attendance</fullName>
                </value>
                <value>
                    <fullName>Time</fullName>
                </value>
                <value>
                    <fullName>Assignment</fullName>
                </value>
                <value>
                    <fullName>Grade Scale</fullName>
                </value>
                <value>
                    <fullName>Homework</fullName>
                </value>
                <value>
                    <fullName>Behavior Type</fullName>
                </value>
                <value>
                    <fullName>Behavior Consequence</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Picklist Value</label>
    <nameField>
        <label>Display Value</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Picklist Values</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Setup__c.object
<CustomObject>
    <description>This object is used to setup Schoolforce and is referenced in multiple pieces of code.  There should be one setup object per school.</description>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Is this school setup active for this school year?</inlineHelpText>
        <label>Active?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>New_School_Year__c</fullName>
        <defaultValue>false</defaultValue>
        <label>New School Year</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Published__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Published</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>School__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>School</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1 OR 2</booleanFilter>
            <filterItems>
                <field>Account.RecordType.Name</field>
                <operation>equals</operation>
                <value>School</value>
            </filterItems>
            <filterItems>
                <field>Account.RecordType.Name</field>
                <operation>equals</operation>
                <value>Summer School</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Setup</relationshipLabel>
        <relationshipName>Setup</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Year__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>School Year associated to the Setup</description>
        <label>Year</label>
        <referenceTo>Time_Element__c</referenceTo>
        <relationshipLabel>Setup (Year)</relationshipLabel>
        <relationshipName>Setup_Year</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Setup</label>
    <nameField>
        <displayFormat>S-{0}</displayFormat>
        <label>Setup ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Setup</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/Time_Element__c.object
<CustomObject>
    <fields>
        <fullName>Current__c</fullName>
        <defaultValue>false</defaultValue>
        <description>If this flag is checked, this value is the current years value; will uncheck when new year is created.</description>
        <label>Current</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Date_Start_Date__c</fullName>
        <defaultValue>Today()</defaultValue>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>End_Date__c</fullName>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>New_School_Year__c</fullName>
        <defaultValue>false</defaultValue>
        <label>New School Year</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Picklist_Value__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Picklist Value</label>
        <referenceTo>Picklist_Value__c</referenceTo>
        <relationshipLabel>Time</relationshipLabel>
        <relationshipName>Time</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>School__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>School</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Time</relationshipLabel>
        <relationshipName>Time</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Year</fullName>
                </value>
                <value>
                    <fullName>Semester</fullName>
                </value>
                <value>
                    <fullName>Trimester</fullName>
                </value>
                <value>
                    <fullName>Quarter</fullName>
                </value>
                <value>
                    <fullName>Period</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Time</label>
    <nameField>
        <displayFormat>T-{000000}</displayFormat>
        <label>Time Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Time</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Value__c.object
<CustomObject>
    <fields>
        <fullName>Language__c</fullName>
        <label>Language</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>English</fullName>
                    <default>true</default>
                    <label>English</label>
                </value>
                <value>
                    <fullName>Spanish</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Setup__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Setup</label>
        <referenceTo>Setup__c</referenceTo>
        <relationshipLabel>Values</relationshipLabel>
        <relationshipName>Values</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Text_Alert__c</fullName>
        <label>Text Alert</label>
        <length>32000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Homework Alerts</fullName>
                </value>
                <value>
                    <fullName>Attendance Alerts</fullName>
                </value>
                <value>
                    <fullName>Attendance Threshold Alerts</fullName>
                </value>
                <value>
                    <fullName>Tardy Alerts</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Value</label>
    <nameField>
        <label>Values Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Values</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/Test_BatchCloneSetupData.cls
@isTest
private class Test_BatchCloneSetupData {

	private static Meals_Setup__c mealsSetup;
	private static Value__c testValue;
	private static void setupData(){
		TestDataSetupUtil_v2.setUPCoreData(5);

		TestDataSetupUtil_v2.activeSetup.Published__c = true;
		update TestDataSetupUtil_v2.activeSetup;

		mealsSetup = new Meals_Setup__c(Setup__c = TestDataSetupUtil_v2.activeSetup.ID, Active__c = true);
		insert mealsSetup;

		testValue = new Value__c(Language__c = 'English',Type__c='Targy Alerts',Text_Alert__c='This is a test value.', Setup__c = TestDataSetupUtil_v2.activeSetup.ID);
		insert testValue;
		List<Picklist_Value__c> assignmentTypes = TestDataSetupUtil_v2.createDefaultAssignmentTypes();
		for(Picklist_Value__c assignmentType: assignmentTypes){
			assignmentType.Setup__c = TestDataSetupUtil_v2.activeSetup.ID;
		}
		update assignmentTypes;

		TestDataSetupUtil_v2.createDefaultAssignmentWeightings(TestDataSetupUtil_v2.coursesList, assignmentTypes);
	}
	
	@isTest static void Test_DataCloning() {
		setupData();
		Time_Element__c newYear;
		Test.startTest();
			newYear = TestDataSetupUtil_v2.getTimeElements_NoInsert(
				1,
				'Year',
				TestDataSetupUtil_v2.masterYear.Picklist_Value__c,
				null,
				TestDataSetupUtil_v2.masterYear.Date_Start_Date__c.addYears(1).format(),
				TestDataSetupUtil_v2.masterYear.End_Date__c.addYears(1).format(),
				false
			)[0];
			newYear.New_School_Year__c = true;
			newYear.Current__c = false;

			insert newYear;
		Test.stopTest();

		Setup__c newSetup = [select id from Setup__c where Year__c=: newYear.ID and School__c =: TestDataSetupUtil_v2.school.ID];
		
		System.assertEquals(1, [select id from Meals_Setup__c where Setup__c=: newSetup.ID].size());
		System.assertEquals(1, [select id from Value__c where Setup__c=: newSetup.ID].size());
		System.assertEquals([select id from Picklist_Value__c where Setup__c =: TestDataSetupUtil_v2.activeSetup.ID].size(), 
			[select id from Picklist_Value__c where Setup__c =: newSetup.ID].size());

		ID courseID  =TestDataSetupUtil_v2.coursesList[0].ID;
		System.assertEquals([select id from Default_Assignment_Weighting__c where Picklist_Value__r.Setup__c=:TestDataSetupUtil_v2.activeSetup.ID and Course__c =: courseID].size(),
			[select id from Default_Assignment_Weighting__c where Picklist_Value__r.Setup__c =:newSetup.ID and Course__c =: courseID].size());

	}
}