objects/Course__c.object
<CustomObject>
    <fields>
        <fullName>Grade_Scale_Lookup__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Not active until the Hawaii release.</description>
        <inlineHelpText>Select the grade scale this course will use to calculate grades.</inlineHelpText>
        <label>Grade Scale</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Grade Scale field must be of Record Type Grade Scale</errorMessage>
            <filterItems>
                <field>Picklist_Value__c.RecordTypeId</field>
                <operation>equals</operation>
                <value>Grade Scale</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Picklist_Value__c</referenceTo>
        <relationshipLabel>Courses</relationshipLabel>
        <relationshipName>Courses</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Course</label>
    <nameField>
        <label>Course Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Courses</pluralLabel>
    <recordTypes>
        <fullName>Course</fullName>
        <active>true</active>
        <label>Course</label>
    </recordTypes>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/Final_Grade__c.object
<CustomObject>
    <description>Stores Final Grades for a course - rollup to Student to get Final GPA</description>
    <fields>
        <fullName>Course__c</fullName>
        <label>Course</label>
        <referenceTo>Course__c</referenceTo>
        <relationshipLabel>Final Grades</relationshipLabel>
        <relationshipName>Final_Grades</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Final_Grade_Value__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Final Grade Value</label>
        <precision>17</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Grade_Overridden__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Grade Overridden</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Student__c</fullName>
        <label>Student</label>
        <referenceTo>Student__c</referenceTo>
        <relationshipLabel>Final Grades</relationshipLabel>
        <relationshipName>Final_Grades</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <label>Final Grade</label>
    <nameField>
        <displayFormat>FG-{0000}</displayFormat>
        <label>Final Grade Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Final Grades</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Grade__c.object
<CustomObject>
    <fields>
        <fullName>Course__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>We store course here as well so we can calculate final grade using aggregate queries</description>
        <label>Course</label>
        <referenceTo>Course__c</referenceTo>
        <relationshipLabel>Grades</relationshipLabel>
        <relationshipName>Grades</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Student__c</fullName>
        <label>Student</label>
        <referenceTo>Student__c</referenceTo>
        <relationshipLabel>Grades</relationshipLabel>
        <relationshipName>Grades</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Grade</label>
    <nameField>
        <displayFormat>G-{0}</displayFormat>
        <label>Grade Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Grades</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Picklist_Value__c.object
<CustomObject>
    <fields>
        <fullName>Grade__c</fullName>
        <label>Grade</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>PS</fullName>
                </value>
                <value>
                    <fullName>PK</fullName>
                </value>
                <value>
                    <fullName>K</fullName>
                </value>
                <value>
                    <fullName>1</fullName>
                </value>
                <value>
                    <fullName>2</fullName>
                </value>
                <value>
                    <fullName>3</fullName>
                </value>
                <value>
                    <fullName>4</fullName>
                </value>
                <value>
                    <fullName>5</fullName>
                </value>
                <value>
                    <fullName>6</fullName>
                </value>
                <value>
                    <fullName>7</fullName>
                </value>
                <value>
                    <fullName>8</fullName>
                </value>
                <value>
                    <fullName>9</fullName>
                </value>
                <value>
                    <fullName>10</fullName>
                </value>
                <value>
                    <fullName>11</fullName>
                </value>
                <value>
                    <fullName>12</fullName>
                </value>
                <value>
                    <fullName>UN Ungraded</fullName>
                </value>
                <value>
                    <fullName>PK-3</fullName>
                </value>
                <value>
                    <fullName>PK-4</fullName>
                </value>
                <value>
                    <fullName>PK Pre-K</fullName>
                </value>
                <value>
                    <fullName>Kindergarten/Preschool</fullName>
                </value>
                <value>
                    <fullName>KG Kindergarten</fullName>
                </value>
                <value>
                    <fullName>PG Postgraduate/Adult</fullName>
                </value>
                <value>
                    <fullName>Kindergarten</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Picklist Value</label>
    <nameField>
        <label>Display Value</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Picklist Values</pluralLabel>
    <recordTypes>
        <fullName>Grade_Scale</fullName>
        <active>true</active>
        <label>Grade Scale</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Section_Grade__c.object
<CustomObject>
    <fields>
        <fullName>Grade_Overridden__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This field will be checked if a grade is manually overridden by a user.</description>
        <label>Grade Overridden</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Grade__c</fullName>
        <label>Grade</label>
        <precision>5</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>Section Grade</label>
    <nameField>
        <displayFormat>SECG-{000}</displayFormat>
        <label>Section Grade Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Section Grades</pluralLabel>
    <recordTypes>
        <fullName>Quarter</fullName>
        <active>true</active>
        <description>Differentiate between quarter-based and semester-based sectional grades.</description>
        <label>Quarter</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Standard__c.object
<CustomObject>
    <fields>
        <fullName>Course__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Not required.  A standard can be associated with 1 course (only 1, not many).  The Course is not visible when searching for standards in the Gradebook.</inlineHelpText>
        <label>Course</label>
        <referenceTo>Course__c</referenceTo>
        <relationshipLabel>Standards</relationshipLabel>
        <relationshipName>Standards</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Standard</label>
    <nameField>
        <label>Standard Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Standards</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Standard_Grade__c.object
<CustomObject>
    <fields>
        <fullName>Grade_Overridden__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Has this standard grade been overridden?</inlineHelpText>
        <label>Grade Overridden</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Grade__c</fullName>
        <defaultValue>0</defaultValue>
        <description>Retired field.</description>
        <inlineHelpText>Retired field.</inlineHelpText>
        <label>Grade *Retired*</label>
        <precision>4</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Student__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Student</label>
        <referenceTo>Student__c</referenceTo>
        <relationshipLabel>Standard Grades</relationshipLabel>
        <relationshipName>Standard_Grades</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Standard Grade</label>
    <nameField>
        <displayFormat>STDG-{000}</displayFormat>
        <label>Standard Grade Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Standard Grades</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Strand_Grade__c.object
<CustomObject>
    <description>Stores strand grades per student/reporting period/strand (Standard object)</description>
    <fields>
        <fullName>Grade__c</fullName>
        <description>Standards Based Grade of the Strand for the Student/Reporting Period/Strand</description>
        <label>Calculated Grade</label>
        <precision>2</precision>
        <scale>1</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Student__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Student</label>
        <referenceTo>Student__c</referenceTo>
        <relationshipLabel>Strand Grades</relationshipLabel>
        <relationshipName>Strand_Grades</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Strand Grade</label>
    <nameField>
        <displayFormat>SG-{000000}</displayFormat>
        <label>Strand Grade Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Strand Grades</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Student__c.object
<CustomObject>
    <fields>
        <fullName>Grade__c</fullName>
        <inlineHelpText>Displays the student&apos;s current grade level.</inlineHelpText>
        <label>Grade</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>PS</fullName>
                </value>
                <value>
                    <fullName>PK</fullName>
                    <color>#78C953</color>
                    <label>PK</label>
                </value>
                <value>
                    <fullName>K</fullName>
                </value>
                <value>
                    <fullName>1</fullName>
                    <color>#A845DC</color>
                    <label>1</label>
                </value>
                <value>
                    <fullName>2</fullName>
                    <color>#F3D904</color>
                    <label>2</label>
                </value>
                <value>
                    <fullName>3</fullName>
                    <color>#A53711</color>
                    <label>3</label>
                </value>
                <value>
                    <fullName>4</fullName>
                    <color>#66E9BD</color>
                    <label>4</label>
                </value>
                <value>
                    <fullName>5</fullName>
                    <color>#0B24BE</color>
                    <label>5</label>
                </value>
                <value>
                    <fullName>6</fullName>
                    <color>#419249</color>
                    <label>6</label>
                </value>
                <value>
                    <fullName>7</fullName>
                    <color>#B6E32E</color>
                    <label>7</label>
                </value>
                <value>
                    <fullName>8</fullName>
                    <color>#641CCF</color>
                    <label>8</label>
                </value>
                <value>
                    <fullName>9</fullName>
                    <color>#F96FB7</color>
                    <label>9</label>
                </value>
                <value>
                    <fullName>10</fullName>
                    <color>#2F5D85</color>
                    <label>10</label>
                </value>
                <value>
                    <fullName>11</fullName>
                    <color>#AFCADF</color>
                    <label>11</label>
                </value>
                <value>
                    <fullName>12</fullName>
                    <color>#8F6429</color>
                    <label>12</label>
                </value>
                <value>
                    <fullName>UN Ungraded</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Student__c</fullName>
        <inlineHelpText>Displays the student&apos;s middle name.</inlineHelpText>
        <label>Student Middle Name</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <label>Student</label>
    <nameField>
        <label>Student Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Students</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Student_Section__c.object
<CustomObject>
    <fields>
        <fullName>Student__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Student</label>
        <referenceTo>Student__c</referenceTo>
        <relationshipLabel>Section</relationshipLabel>
        <relationshipName>Student_Section</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Student/Section</label>
    <nameField>
        <displayFormat>SS-{000000}</displayFormat>
        <label>Student/Section ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Student/Section</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/Test_OverrideGradeTriggers.cls
@isTest
private class Test_OverrideGradeTriggers {

    public static void createTestData(){
    	TestDataSetupUtil_v2.isGradebook=true;
        TestDataSetupUtil_v2.setUPCoreData(2);
        testDataSetupUtil_v2.setUPStaffData(2);       
        TestDataSetupUtil_v2.setUpStudentData(2);  
     	Picklist_Value__c stdPlV =   [select id from Picklist_value__c where RecordType.DeveloperName = 'Grade_Scale' AND name = 'Standard' limit 1 ];
        	Course__c co = new Course__c (Id = testDataSetupUtil_v2.coursesList[0].Id, Grade_scale_lookup__c = stdPlV.id);
    		update co; 
    }

    static testMethod void testFinalGrade_BU() {
        test.startTest();
        createTestData();
        Student__c student = TestDataSetupUtil_v2.studentsList[0];
        Course__c course = TestDataSetupUtil_v2.coursesList[0];
        Final_Grade__c finalgrade = new Final_Grade__c(Student__c=student.Id, Final_Grade_Value__c = 80, Course__c=course.Id, Grade_Overridden__c = false,  Final_Grade_Letter_v2__c = 'A', Unweighted_GPA__c =4.0, Weighted_GPA__c=4.0);
        insert finalgrade;
        finalgrade.Grade_Override__c = '4';
        update finalgrade;
        Student__c s=[select id, Grades_Overridden__c from Student__c where ID = :student.Id];
        system.assert(s.Grades_Overridden__c==true);
        test.stopTest();
    }
    
    static testMethod void testSectionGrade_BU() {
        
        createTestData();
        test.startTest();
        system.runAs(testDataSetupUtil_v2.staffUsersList[0]){
	        Student_Section__c studentsection = TestDataSetupUtil_v2.studSectionsList[0];
	        Section_Grade__c sectiongrade = new Section_Grade__c(Student_Section__c=studentsection.Id, Grade__c = 80, Grade_Overridden__c = false);
	        insert sectiongrade;
	        sectiongrade.Grade_Override__c = 'B';
	        system.debug('sectionGrade ID: ' + sectiongrade.Id);
	        update sectiongrade;
	        system.debug('sectionGrade overridden: ' + sectiongrade.Grade_Overridden__c);
	        //US1284 quarters
	        List<Section_Grade__c> sg = [select id, Grade_Overridden__c from Section_Grade__c where Id =: sectiongrade.Id AND (RecordTypeID = null OR RecordType.Name = 'Quarter')];
	        
	        //it's broken 4/27/2012, it doesn't make sense that it cannot find the data in the above query
	        //used this for now (@isTest(seeAllData=true)
	        system.assert(sg[0].Grade_Overridden__c==true);   
        }     
        test.stopTest();
    }
    
    static testMethod void testStandardGrade_BU() {
        test.startTest();
        createTestData();
        Student__c student = TestDataSetupUtil_v2.studentsList[0];
        Standard__c standard = new Standard__c();
        insert standard;
        Standard_Grade__c standardgrade = new Standard_Grade__c(Student__c=student.Id, Standard__c=standard.Id, Grade_Override__c = 80, Grade_Overridden__c = false);
        insert standardgrade;
        standardgrade.Grade_Override__c = 85;
        update standardgrade;
        Standard_Grade__c sg=[select id, Grade_Overridden__c from Standard_Grade__c where Id = :standardgrade.Id];
        system.assert(sg.Grade_Overridden__c==true);
        test.stopTest();
    }
    
    static testMethod void testStrandGrade_BU() {
        test.startTest();
        createTestData();
        Student__c student = TestDataSetupUtil_v2.studentsList[0];
        Standard__c strand = new Standard__c();
        insert strand;
        Strand_Grade__c strandgrade = new Strand_Grade__c(Student__c=student.Id, Strand__c=strand.Id, Grade__c = 3.5, Grade_Overridden__c = false);
        insert strandgrade;
        strandgrade.Grade_Override__c = 3.2;
        update strandgrade;
        Strand_Grade__c sg=[select id, Grade_Overridden__c from Strand_Grade__c where Id = :strandgrade.Id];
        system.assert(sg.Grade_Overridden__c==true);
        test.stopTest();
    }
}