objects/Course__c.object
<CustomObject>
    <label>Course</label>
    <nameField>
        <label>Course Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Courses</pluralLabel>
    <recordTypes>
        <fullName>Course</fullName>
        <active>true</active>
        <label>Course</label>
    </recordTypes>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/Final_Grade__c.object
<CustomObject>
    <description>Stores Final Grades for a course - rollup to Student to get Final GPA</description>
    <fields>
        <fullName>Course__c</fullName>
        <label>Course</label>
        <referenceTo>Course__c</referenceTo>
        <relationshipLabel>Final Grades</relationshipLabel>
        <relationshipName>Final_Grades</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Current_Grade_Letter_v2__c</fullName>
        <inlineHelpText>Current Letter Grade Equivalent</inlineHelpText>
        <label>Current Grade Letter</label>
        <length>15</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Current_Grade_Value__c</fullName>
        <defaultValue>0</defaultValue>
        <inlineHelpText>Year to Date Grade Value, with no time/course weightings applied</inlineHelpText>
        <label>Current Grade Value</label>
        <precision>17</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Key__c</fullName>
        <caseSensitive>true</caseSensitive>
        <description>Stores Unique Key for Student/Course Association to enable update via upsert</description>
        <externalId>true</externalId>
        <label>Key</label>
        <length>40</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Student__c</fullName>
        <label>Student</label>
        <referenceTo>Student__c</referenceTo>
        <relationshipLabel>Final Grades</relationshipLabel>
        <relationshipName>Final_Grades</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <label>Final Grade</label>
    <nameField>
        <displayFormat>FG-{0000}</displayFormat>
        <label>Final Grade Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Final Grades</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Grade__c.object
<CustomObject>
    <fields>
        <fullName>Assignment_Weighting__c</fullName>
        <defaultValue>1</defaultValue>
        <label>Assignment Weighting</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Course__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>We store course here as well so we can calculate final grade using aggregate queries</description>
        <label>Course</label>
        <referenceTo>Course__c</referenceTo>
        <relationshipLabel>Grades</relationshipLabel>
        <relationshipName>Grades</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Entered_Grade__c</fullName>
        <label>Entered Grade</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Standard__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Standard</label>
        <referenceTo>Standard__c</referenceTo>
        <relationshipLabel>Grades</relationshipLabel>
        <relationshipName>Grades</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Student__c</fullName>
        <label>Student</label>
        <referenceTo>Student__c</referenceTo>
        <relationshipLabel>Grades</relationshipLabel>
        <relationshipName>Grades</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Weighted_Grade_Value__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Weighted Grade Value</label>
        <precision>8</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>Grade</label>
    <nameField>
        <displayFormat>G-{0}</displayFormat>
        <label>Grade Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Grades</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Grade_Normalization__c.object
<CustomObject>
    <fields>
        <fullName>GP_Value__c</fullName>
        <label>GP Value</label>
        <precision>4</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Transformed_Grade__c</fullName>
        <label>Transformed Grade</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <label>Grade Normalization</label>
    <nameField>
        <label>Grade Normalization Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Grade Normalizations</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/Standard__c.object
<CustomObject>
    <fields>
        <fullName>Course__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Not required.  A standard can be associated with 1 course (only 1, not many).  The Course is not visible when searching for standards in the Gradebook.</inlineHelpText>
        <label>Course</label>
        <referenceTo>Course__c</referenceTo>
        <relationshipLabel>Standards</relationshipLabel>
        <relationshipName>Standards</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Standard</label>
    <nameField>
        <label>Standard Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Standards</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Student__c.object
<CustomObject>
    <fields>
        <fullName>Grade__c</fullName>
        <inlineHelpText>Displays the student&apos;s current grade level.</inlineHelpText>
        <label>Grade</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>PS</fullName>
                </value>
                <value>
                    <fullName>PK</fullName>
                    <color>#78C953</color>
                    <label>PK</label>
                </value>
                <value>
                    <fullName>K</fullName>
                </value>
                <value>
                    <fullName>1</fullName>
                    <color>#A845DC</color>
                    <label>1</label>
                </value>
                <value>
                    <fullName>2</fullName>
                    <color>#F3D904</color>
                    <label>2</label>
                </value>
                <value>
                    <fullName>3</fullName>
                    <color>#A53711</color>
                    <label>3</label>
                </value>
                <value>
                    <fullName>4</fullName>
                    <color>#66E9BD</color>
                    <label>4</label>
                </value>
                <value>
                    <fullName>5</fullName>
                    <color>#0B24BE</color>
                    <label>5</label>
                </value>
                <value>
                    <fullName>6</fullName>
                    <color>#419249</color>
                    <label>6</label>
                </value>
                <value>
                    <fullName>7</fullName>
                    <color>#B6E32E</color>
                    <label>7</label>
                </value>
                <value>
                    <fullName>8</fullName>
                    <color>#641CCF</color>
                    <label>8</label>
                </value>
                <value>
                    <fullName>9</fullName>
                    <color>#F96FB7</color>
                    <label>9</label>
                </value>
                <value>
                    <fullName>10</fullName>
                    <color>#2F5D85</color>
                    <label>10</label>
                </value>
                <value>
                    <fullName>11</fullName>
                    <color>#AFCADF</color>
                    <label>11</label>
                </value>
                <value>
                    <fullName>12</fullName>
                    <color>#8F6429</color>
                    <label>12</label>
                </value>
                <value>
                    <fullName>UN Ungraded</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Student__c</fullName>
        <inlineHelpText>Displays the student&apos;s middle name.</inlineHelpText>
        <label>Student Middle Name</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <label>Student</label>
    <nameField>
        <label>Student Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Students</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/Gradebook_CurrentCourseGradeCalculation.cls
global  class Gradebook_CurrentCourseGradeCalculation implements Database.Batchable<sObject>,Database.Stateful {

global Map<String, Grade_Normalization__c> gtransform;
public String query;
public String email;

global Gradebook_CurrentCourseGradeCalculation () {
gtransform = new Map<String, Grade_Normalization__c> ();
for (Grade_Normalization__c gn: [Select Name, GP_Value__c, Transformed_Grade__c from Grade_Normalization__c where GP_Value__c != NULL]) {
gtransform.put(gn.Name, gn);
}

}


global database.querylocator start(Database.BatchableContext BC){
return Database.getQueryLocator(query);
}

global void execute(Database.BatchableContext BC, List<sObject> scope){
//Assumes one student per execution
for(sObject s : scope) {
    Student__c std = (Student__c ) s;
    List<Final_Grade__c> finalgrades = new List<Final_Grade__c> () ;

//Final Grade selects all grades for the student and groups by course and time
  
AggregateResult[] groupedResults = 
                [
                SELECT Course__c c,
                sum(Assignment_Weighting__c) aw, sum(Weighted_Grade_Value__c) wgv
                FROM Grade__c 
                WHERE Student__c = :std.Id
                AND Standard__c = null
                AND Entered_Grade__c != null AND Entered_Grade__c != 'N/A' AND Entered_Grade__c != 'N' AND Entered_Grade__c != 'I'
                GROUP BY Course__c];
for (AggregateResult ar : groupedResults)  {
/*Each record returned is a unique comination of grade per course for year to date per student
to course weights, and then add that number to course/final grade total
*/
        Double sgrade = (Decimal)ar.get('wgv') / (Decimal)ar.get('aw');
        
                    //Transform final grade to letter and GPA Value
                    Long roundedgrade = sgrade.round();
                    if (roundedgrade>100) {roundedgrade = 100;} //Grade cannot be more than 100 for transform purposes; extra credit or mistake entries when points possible was used was likely the cause of this
                    
                    String lettergrade =  gtransform.get(string.valueof(roundedgrade)).Transformed_Grade__c;
                    
                    
           //write to final grade table                  
                    finalgrades.add (new Final_Grade__c (
                            Student__c = std.Id, 
                            Course__c = (String)ar.get('c'), 
                            key__c = string.valueof(std.Id) + (String)ar.get('c'), 
                            Current_Grade_Letter_v2__c = lettergrade,
                            Current_Grade_Value__c = sgrade ) );
        }
      //upsert based on key field ( Student + Course ) 
        upsert finalgrades key__c;
}

}// end execute   

global void finish(Database.BatchableContext BC){
} // end finish

}