objects/Course__c.object
<CustomObject>
    <fields>
        <fullName>Subject_Area__c</fullName>
        <label>Subject Area</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Citizenship</fullName>
                </value>
                <value>
                    <fullName>Cognitive Development</fullName>
                </value>
                <value>
                    <fullName>Computer Science Programming</fullName>
                </value>
                <value>
                    <fullName>Computer Skills/Literacy</fullName>
                </value>
                <value>
                    <fullName>Elective Activities</fullName>
                </value>
                <value>
                    <fullName>English as a Second Language</fullName>
                </value>
                <value>
                    <fullName>Fine Arts - Art</fullName>
                </value>
                <value>
                    <fullName>Fine Arts - Dance</fullName>
                </value>
                <value>
                    <fullName>Fine Arts - Drama/Theater</fullName>
                </value>
                <value>
                    <fullName>Fine Arts - Music</fullName>
                </value>
                <value>
                    <fullName>Fitness</fullName>
                </value>
                <value>
                    <fullName>Foreign Language and Literature</fullName>
                </value>
                <value>
                    <fullName>Geography</fullName>
                </value>
                <value>
                    <fullName>Handwriting/Penmanship</fullName>
                </value>
                <value>
                    <fullName>Health</fullName>
                </value>
                <value>
                    <fullName>History</fullName>
                </value>
                <value>
                    <fullName>Home Economics</fullName>
                </value>
                <value>
                    <fullName>Homework</fullName>
                </value>
                <value>
                    <fullName>Industrial Arts</fullName>
                </value>
                <value>
                    <fullName>Keyboarding/typing</fullName>
                </value>
                <value>
                    <fullName>Language Arts</fullName>
                </value>
                <value>
                    <fullName>Library Skills</fullName>
                </value>
                <value>
                    <fullName>Listening &amp; Speaking</fullName>
                </value>
                <value>
                    <fullName>Literacy</fullName>
                </value>
                <value>
                    <fullName>Math</fullName>
                </value>
                <value>
                    <fullName>Mathematics/Arithmetic</fullName>
                </value>
                <value>
                    <fullName>Military Science</fullName>
                </value>
                <value>
                    <fullName>Multi/Interdisciplinary Studies</fullName>
                </value>
                <value>
                    <fullName>Physical Development</fullName>
                </value>
                <value>
                    <fullName>Physical Education</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Course</label>
    <nameField>
        <label>Course Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Courses</pluralLabel>
    <recordTypes>
        <fullName>Subject_Area</fullName>
        <active>true</active>
        <label>Subject Area</label>
    </recordTypes>
    <sharingModel>Read</sharingModel>
</CustomObject>

classes/Test_CourseSubjectAreaHelper.cls
@isTest
private class Test_CourseSubjectAreaHelper
{
	private final static String SUB_AREA = 'Citizenship';
	static testMethod void testCreateSubAreas()
	{
		testDataSetupUtil_v2.setupCoreData(2);
		testDataSetupUtil_v2.coursesList[0].subject_area__c = SUB_AREA;
		update testDataSetupUtil_v2.coursesList[0];
		
		Test.startTest(); 
		Course_SubjectAreaHelper.createSubjectAreas();
		Course_SubjectAreaHelper.createSubjectAreas();
		Test.stopTest();
		
		Id subjAreaId = core_SoqlUtils.getRecordTypesBySobject('Course__c').get('Subject_Area');
		System.assert([SELECT Id FROM Course__c WHERE RecordTypeId = :subjAreaId].size() > 0);
	}
}