objects/Course__c.object
<CustomObject>
    <label>Course</label>
    <nameField>
        <label>Course Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Courses</pluralLabel>
    <recordTypes>
        <fullName>Course</fullName>
        <active>true</active>
        <label>Course</label>
    </recordTypes>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/Grade_Scale_Catalog__c.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Active?</label>
        <type>Checkbox</type>
    </fields>
    <label>Grade Scale Catalog</label>
    <nameField>
        <label>Grade Scale Catalog Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Grade Scale Catalogs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Grade_Scale_Catalog_Scale__c.object
<CustomObject>
    <fields>
        <fullName>Grade_Scale_Catalog__c</fullName>
        <label>Grade Scale Catalog</label>
        <referenceTo>Grade_Scale_Catalog__c</referenceTo>
        <relationshipLabel>Grade Scale Catalog/Scales</relationshipLabel>
        <relationshipName>Grade_Scale_Catalog_Scales</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Picklist_Value__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Grade Scale</label>
        <referenceTo>Picklist_Value__c</referenceTo>
        <relationshipLabel>Grade Scale Catalog/Scales</relationshipLabel>
        <relationshipName>Grade_Scale_Catalog_Scales</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Grade Scale Catalog/Scale</label>
    <nameField>
        <displayFormat>GSC-{000000}</displayFormat>
        <label>Grade Scale Catalog/Scale Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Grade Scale Catalog/Scales</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Picklist_Value__c.object
<CustomObject>
    <label>Picklist Value</label>
    <nameField>
        <label>Display Value</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Picklist Values</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Section__c.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Check this box if the section is a currently active section</description>
        <inlineHelpText>Check this box if the section is a currently active section</inlineHelpText>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>All_Grades__c</fullName>
        <inlineHelpText>Select the grade(s) for which the section is available. SchoolForce uses this field to determine the available sectons into which you can schedule a student when you use the Section Wizard.</inlineHelpText>
        <label>All Grades</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>PS</fullName>
                </value>
                <value>
                    <fullName>PK</fullName>
                </value>
                <value>
                    <fullName>K</fullName>
                </value>
                <value>
                    <fullName>1</fullName>
                </value>
                <value>
                    <fullName>2</fullName>
                </value>
                <value>
                    <fullName>3</fullName>
                </value>
                <value>
                    <fullName>4</fullName>
                </value>
                <value>
                    <fullName>5</fullName>
                </value>
                <value>
                    <fullName>6</fullName>
                </value>
                <value>
                    <fullName>7</fullName>
                </value>
                <value>
                    <fullName>8</fullName>
                </value>
                <value>
                    <fullName>9</fullName>
                </value>
                <value>
                    <fullName>10</fullName>
                </value>
                <value>
                    <fullName>11</fullName>
                </value>
                <value>
                    <fullName>12</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Course__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Select the course associated to the section you want to create.</inlineHelpText>
        <label>Course</label>
        <referenceTo>Course__c</referenceTo>
        <relationshipLabel>Sections</relationshipLabel>
        <relationshipName>Sections</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Is_Section__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Section</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>School__c</fullName>
        <label>School</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Sections</relationshipLabel>
        <relationshipName>Sections</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Section__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Recursive lookup for groups</description>
        <label>Section</label>
        <referenceTo>Section__c</referenceTo>
        <relationshipLabel>Groups in Section</relationshipLabel>
        <relationshipName>Sections1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Staff__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Staff</label>
        <referenceTo>Staff__c</referenceTo>
        <relationshipLabel>Sections</relationshipLabel>
        <relationshipName>Sections</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Time__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Time</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Time_Element__c.Picklist_Value__r.Name</field>
                <operation>equals</operation>
                <value>Year</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Time_Element__c</referenceTo>
        <relationshipLabel>Sections</relationshipLabel>
        <relationshipName>Sections</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Section</label>
    <nameField>
        <label>Section Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sections</pluralLabel>
    <recordTypes>
        <fullName>Gradebook_Group</fullName>
        <active>true</active>
        <description>Used for custom gradebook groups</description>
        <label>Gradebook Group</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Staff__c.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Is_Active__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Active?</label>
        <type>Checkbox</type>
    </fields>
    <label>Staff</label>
    <nameField>
        <label>Staff Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Staff</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/Staff_Section__c.object
<CustomObject>
    <fields>
        <fullName>Is_Active__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Is Active?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>School__c</fullName>
        <formula>Section__r.School__r.Id</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>The School related to this Section</inlineHelpText>
        <label>School</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Section__c</fullName>
        <label>Section</label>
        <referenceTo>Section__c</referenceTo>
        <relationshipLabel>Staff</relationshipLabel>
        <relationshipName>Staff_Section</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Staff__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Staff</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Staff__c.Organization__r.Id</field>
                <operation>equals</operation>
                <valueField>$Source.Account__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Staff__c</referenceTo>
        <relationshipLabel>Sections</relationshipLabel>
        <relationshipName>Staff_Section</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Staff/Section</label>
    <nameField>
        <displayFormat>SfS-{000000}</displayFormat>
        <label>Staff/Section ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Staff/Section</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Student__c.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>true</defaultValue>
        <inlineHelpText>Indicates whether or not this Student record is active. If checked, then this is the current Student record. If unchecked, this is an old Student record.</inlineHelpText>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Is_Active__c</fullName>
        <defaultValue>true</defaultValue>
        <inlineHelpText>Do not use this field; it is no longer used by SchoolForce.</inlineHelpText>
        <label>Is Active?*Retired*</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>School__c</fullName>
        <inlineHelpText>Displays the name of the student&apos;s current SchoolForce school. You can click on the link to see the details of this school.</inlineHelpText>
        <label>School</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Students</relationshipLabel>
        <relationshipName>Students</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Section__c</fullName>
        <inlineHelpText>Displays the student&apos;s current homeroom name or room number. This field can be used for reporting purposes.</inlineHelpText>
        <label>Current Homeroom</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Staff__c</fullName>
        <inlineHelpText>Displays the name of the student&apos;s homeroom teacher.  You can use this field for reporting purposes.</inlineHelpText>
        <label>Current Homeroom Teacher</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Student__c</fullName>
        <inlineHelpText>Displays the student&apos;s middle name.</inlineHelpText>
        <label>Student Middle Name</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <label>Student</label>
    <nameField>
        <label>Student Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Students</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Student_Section__c.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Is_Section__c</fullName>
        <formula>Section__r.Is_Section__c</formula>
        <label>Is Section</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>School__c</fullName>
        <formula>Student__r.School__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>School</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Section__c</fullName>
        <label>Section</label>
        <referenceTo>Section__c</referenceTo>
        <relationshipLabel>Student</relationshipLabel>
        <relationshipName>Student_Section</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Student__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Student</label>
        <referenceTo>Student__c</referenceTo>
        <relationshipLabel>Section</relationshipLabel>
        <relationshipName>Student_Section</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Student/Section</label>
    <nameField>
        <displayFormat>SS-{000000}</displayFormat>
        <label>Student/Section ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Student/Section</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/Test_Gradebook_AssignmentController_v2.cls
@isTest
public class Test_Gradebook_AssignmentController_v2 {

    public static void createTestData() {
        TestDataSetupUtil_v2.isGradebook = true;
        TestDataSetupUtil_v2.setUPCoreData(3);
        TestDataSetupUtil_v2.setUpStaffData(5);
        TestDataSetupUtil_v2.setUpStudentData(5);      
        
        //missing this
        List<Grade_Scale_Catalog_Scale__c> gscsList = new List<Grade_Scale_Catalog_Scale__c>();
        for(ID gsID:TestDataSetupUtil_v2.scaleMap.values()){
            gscsList.add(new Grade_Scale_Catalog_Scale__c(Picklist_Value__c = gsID, Grade_Scale_Catalog__c = TestDataSetupUtil_v2.activeSetup.Grade_Scale_Catalog__c));
        }
        insert gscsList;
        
        
        Map <String, Id> sectionRtMap = core_SoqlUtils.getRecordTypesBySobject('Section__c');
        //create gradebook groups   
        //create section, staff/section, student/section
        //List<Section__c> sectionToUses = [SELECT ID, Course__c, All_Grades__c, (SELECT Student__c, Section__c FROM Student_Section__r), (SELECT Staff__c, Section__c FROM Staff_Section__r) FROM Section__c WHERE Is_Section__c = true AND Active__c = true];

        Section__c createGroup = new Section__c(
            Section__c = TestDataSetupUtil_v2.sectionsList[0].ID,
            Is_Section__c = false,
            Course__c = TestDataSetupUtil_v2.sectionsList[0].Course__c,
            Active__c = true,
            All_Grades__c = TestDataSetupUtil_v2.sectionsList[0].All_Grades__c,
            Name = 'testGroup0',
            RecordTypeId = sectionRtMap.get('Gradebook_Group'),
            Time__c = testDataSetupUtil_v2.masterYear.ID,
            School__c = testDataSetupUtil_v2.School.ID
        );
        insert createGroup;

        for(Staff_Section__c s:TestDataSetupUtil_v2.staffSectionsList){
            if(s.Section__c == TestDataSetupUtil_v2.sectionsList[0].ID){
                Staff_Section__c createGroupStaff = new Staff_Section__c(
                    Staff__c = s.Staff__c, 
                    Section__c = createGroup.ID, 
                    Is_Active__c = true);
                insert createGroupStaff;
                break;
            }
        }
        
        for(Student_Section__c s:TestDataSetupUtil_v2.studSectionsList){
            if(s.Section__c == TestDataSetupUtil_v2.sectionsList[0].ID){
                Student_Section__c createGroupStudent = new Student_Section__c(
                    Active__c = true, 
                    Student__c = s.Student__c, 
                    Section__c = createGroup.ID);
                insert createGroupStudent;
                break;
            }
        }
    }
    
    static testMethod void testSO_v2_addToGB() {
        createTestData();   
        Test.startTest(); 
        system.runAs(testDataSetupUtil_v2.staffUsersList[0]) {              
            Gradebook_AssignmentController_v2 newAssignmentController = new Gradebook_AssignmentController_v2();
            newAssignmentController.standardBased = true;
            newAssignmentController.standardOnly = true;
            newAssignmentController.newAssignmentFlow();
            string newsection='section';
            newAssignmentController.rPoints = true;
            newAssignmentController.validateSubmit(newsection);
            newAssignmentController.addStandards();
            newAssignmentController.removeStandards();
            newAssignmentController.doNotAddStandards();
            newAssignmentController.newFlowChoice();
            newAssignmentController.submit();
            
            newAssignmentController.assignmentWrapper.createAssignmentLibrary();
            newAssignmentController.assignmentWrapper.createNewLibraryFromExisting();
            newAssignmentController.assignmentWrapper.assignmentName = 'testing';
            newAssignmentController.assignmentWrapper.assignmentCourse = newAssignmentController.courseOptions[0].getValue();
            newAssignmentController.rPoints=true;
            newAssignmentController.setSelectedAssignmentTypeOptions();
            newAssignmentController.setDefaultAssignmentWeighting();
            newAssignmentController.assignmentWrapper.assignmentType = newAssignmentController.selectedAssignmentTypeOptions[0].getValue();
            //search for standards
            newAssignmentController.searchFeature.attributeSearch='All';
            newAssignmentController.searchFeature.searchMethod();
            
            //select two standards
            newAssignmentController.searchFeature.searchStandardResults[0].selected = true;
            newAssignmentController.searchFeature.searchStandardResults[1].selected = true;
            newAssignmentController.searchFeature.addMethod();
            
            //remove one standard
            newAssignmentController.searchFeature.selectedStandardsList[0].selected = true;
            newAssignmentController.searchFeature.removeMethod();
            
            //selecting section or course
            newAssignmentController.sectionOrCourseChoice = 'section';
            newAssignmentController.newFlowChoice();
            newAssignmentController.renderPointsField();  //render just to get the call on page
            
            //ensure section assignment details are populated
            newAssignmentController.assignmentWrapper.attachAssignment = false;
            
            //select a section
            newAssignmentController.sections[0].selected = true;
            //select a reportingPeriod
            newAssignmentController.sections[0].reportingPeriod = testDataSetupUtil_v2.semester.ID;
            //select a dueDate
            newAssignmentController.sections[0].dueDate = testDataSetupUtil_v2.semester.Date_Start_Date__c.addDays(1).format();
            
            //hit submit!
            newAssignmentController.submit();
            newAssignmentController.rNew=true;
            newAssignmentController.rExisting=false;
            newAssignmentController.submitAndNew();
            Id devRecordTypeId = Schema.SObjectType.Picklist_Value__c.getRecordTypeInfosByName().get('Assignment Assessment Type').getRecordTypeId();
            newAssignmentController.assessmentRecordType=devRecordTypeId;
             newAssignmentController.selectedAssignmentTypeOptions.add(null);
        }
        Test.stopTest();
    }
    
    static testMethod void testSO_v2_addToCourse() {
        createTestData();   
        Test.startTest();
        system.runAs(testDataSetupUtil_v2.staffUsersList[0]) {
            Gradebook_AssignmentController_v2 newAssignmentController = new Gradebook_AssignmentController_v2();
            newAssignmentController.standardBased = true;
            newAssignmentController.standardOnly = false;
            newAssignmentController.newAssignmentFlow();
            newAssignmentController.addStandards();
            newAssignmentController.removeStandards();
           
            newAssignmentController.assignmentWrapper.createAssignmentLibrary();
            newAssignmentController.assignmentWrapper.createNewLibraryFromExisting();
            newAssignmentController.assignmentWrapper.assignmentName = 'testing';
            newAssignmentController.assignmentWrapper.assignmentCourse = newAssignmentController.courseOptions[0].getValue();
            newAssignmentController.rPoints=true;
            newAssignmentController.setSelectedAssignmentTypeOptions();
            newAssignmentController.setDefaultAssignmentWeighting();
            newAssignmentController.assignmentWrapper.assignmentType = newAssignmentController.selectedAssignmentTypeOptions[0].getValue();
            //search for standards
            newAssignmentController.searchFeature.attributeSearch='All';
            newAssignmentController.searchFeature.searchMethod();
            
            //select two standards
            newAssignmentController.searchFeature.searchStandardResults[0].selected = true;
            newAssignmentController.searchFeature.searchStandardResults[1].selected = true;
            newAssignmentController.searchFeature.addMethod();
            
            //remove one standard
            newAssignmentController.searchFeature.selectedStandardsList[0].selected = true;
            newAssignmentController.searchFeature.removeMethod();
            
            //selecting section or course
            newAssignmentController.sectionOrCourseChoice = 'course';
            newAssignmentController.newFlowChoice();
            newAssignmentController.renderPointsField();  //render just to get the call on page
            
            //ensure section assignment details are populated
            newAssignmentController.assignmentWrapper.attachAssignment = false;

            //hit submit!
            newAssignmentController.submit();
           newAssignmentController.rNew=true;
            newAssignmentController.rExisting=false;
            newAssignmentController.submitAndNew();
           Id devRecordTypeId = Schema.SObjectType.Picklist_Value__c.getRecordTypeInfosByName().get('Assignment Assessment Type').getRecordTypeId();
           newAssignmentController.assessmentRecordType=devRecordTypeId;
           newAssignmentController.selectedAssignmentTypeOptions.add(null);
           newAssignmentController.setGradebookName();
        }
        Test.stopTest();
    }   
    
    static testMethod void testhybrid_v2() {
        createTestData();
        Test.startTest();
        system.runAs(testDataSetupUtil_v2.staffUsersList[0]) {
            Gradebook_AssignmentController_v2 newAssignmentController = new Gradebook_AssignmentController_v2();
            newAssignmentController.standardBased = true;
            newAssignmentController.standardOnly = false;
            newAssignmentController.newAssignmentFlow();
           newAssignmentController.addStandards();
            newAssignmentController.removeStandards();
             newAssignmentController.assignmentWrapper.createAssignmentLibrary();
            newAssignmentController.assignmentWrapper.createNewLibraryFromExisting();
            newAssignmentController.assignmentWrapper.assignmentName = 'testing';
            
            newAssignmentController.assignmentWrapper.assignmentCourse = newAssignmentController.courseOptions[0].getValue();
            newAssignmentController.rPoints=true;
            newAssignmentController.setSelectedAssignmentTypeOptions();
            newAssignmentController.setDefaultAssignmentWeighting();
            newAssignmentController.assignmentWrapper.assignmentType = newAssignmentController.selectedAssignmentTypeOptions[0].getValue();
            //search for standards
            newAssignmentController.searchFeature.attributeSearch='All';
            newAssignmentController.searchFeature.searchMethod();
            
            //select two standards
            newAssignmentController.searchFeature.searchStandardResults[0].selected = true;
            newAssignmentController.searchFeature.searchStandardResults[1].selected = true;
            newAssignmentController.searchFeature.addMethod();
            
            //remove one standard
            newAssignmentController.searchFeature.selectedStandardsList[0].selected = true;
            newAssignmentController.searchFeature.removeMethod();
            
            //selecting section or course
            newAssignmentController.sectionOrCourseChoice = 'section';
            newAssignmentController.newFlowChoice();
            newAssignmentController.renderPointsField();  //render just to get the call on page
            
            //ensure section assignment details are populated
            newAssignmentController.assignmentWrapper.gradeScale = newAssignmentController.gradeScaleOptions[0].getValue();
            newAssignmentController.assignmentWrapper.standardGradeScale = newAssignmentController.standardScaleOptions[0].getValue();
            newAssignmentController.assignmentWrapper.attachAssignment = false;
            
            //select a section
            newAssignmentController.sections[0].selected = true;
            //select a reportingPeriod
            newAssignmentController.sections[0].reportingPeriod = testDataSetupUtil_v2.semester.ID;
            //select a dueDate
            newAssignmentController.sections[0].dueDate = testDataSetupUtil_v2.semester.Date_Start_Date__c.addDays(1).format();
            
            //hit submit! 
            newAssignmentController.rNew=true;
            newAssignmentController.rExisting=false;
            newAssignmentController.submitAndNew();
            Id devRecordTypeId = Schema.SObjectType.Picklist_Value__c.getRecordTypeInfosByName().get('Assignment Assessment Type').getRecordTypeId();
            newAssignmentController.assessmentRecordType=devRecordTypeId;
            newAssignmentController.selectedAssignmentTypeOptions.add(null);
        }   
        Test.stopTest();            
    }
    
    static testMethod void testhybrid_v2_existing() {
        createTestData();
        Test.startTest();
        system.runAs(testDataSetupUtil_v2.staffUsersList[0]) {      
            Gradebook_AssignmentController_v2 newAssignmentController = new Gradebook_AssignmentController_v2();
            newAssignmentController.standardBased = true;
            newAssignmentController.standardOnly = false;
            newAssignmentController.newAssignmentFlow();
            newAssignmentController.addStandards();
            newAssignmentController.removeStandards();
             newAssignmentController.assignmentWrapper.createAssignmentLibrary();
            newAssignmentController.assignmentWrapper.createNewLibraryFromExisting();
            newAssignmentController.assignmentWrapper.assignmentCourse = newAssignmentController.courseOptions[0].getValue();  
            newAssignmentController.rPoints=true;
            newAssignmentController.setSelectedAssignmentTypeOptions();
            newAssignmentController.assignmentWrapper.assignmentName = 'testing';
            newAssignmentcontroller.assignmentWrapper.gradebookName = 'test';
            newAssignmentController.assignmentWrapper.assignmentType = newAssignmentController.selectedAssignmentTypeOptions[0].getValue();
            newAssignmentController.assignmentWrapper.assignmentWeighting = 1;          
            newAssignmentController.setDefaultAssignmentWeighting();
            //ensure section assignment details are populated
            newAssignmentController.assignmentWrapper.gradeScale = newAssignmentController.gradeScaleOptions[0].getValue();
            newAssignmentController.assignmentWrapper.standardGradeScale = newAssignmentController.standardScaleOptions[0].getValue();
            newAssignmentController.assignmentWrapper.attachAssignment = false;
            
            //select a section
            newAssignmentController.sections[0].selected = true;
            //select a reportingPeriod
            newAssignmentController.sections[0].reportingPeriod = testDataSetupUtil_v2.semester.ID;
            //select a dueDate
            newAssignmentController.sections[0].dueDate = testDataSetupUtil_v2.semester.Date_Start_Date__c.addDays(1).format();
            
            //hit submit! want this data
            //Test.startTest();
            //newAssignmentController.Submit();
            
            //instantiate GB, and then run the test
            pageReference setGBAssignmentCreation = new pageReference('/apex/Gradebook_AddAssignments_v2');
            Test.setCurrentPage(setGBAssignmentCreation);
            Gradebook_AssignmentController_v2 exist = new Gradebook_assignmentController_v2();
            
                exist.standardBased = true;
                exist.standardOnly = false;
                exist.existingAssignmentFlow();
                
                //search for assignments
                //exist.assignmentWrapper.courseSearch = exist.courseOptions[0].getLabel();
                exist.assignmentWrapper.courseSearch = 'All';
                exist.assignmentWrapper.assignmentTypeSearch = 'Any';
                exist.assignmentWrapper.searchMethod(); 
                
                //select first assignment, should be the one created before test.start
                //System.assert(exist.assignmentWrapper.searchAssignmentResults.size()==0,'Search failed to return a result. Clear test history and try again.');
//              setGBAssignmentCreation.getParameters().put('assignmentLibraryID', exist.assignmentWrapper.searchAssignmentResults[0].ID);
                exist.selectAssignment();
                
                //doNotUseStandards
                exist.doNotAddStandards();
                        
                //selecting section or course
                exist.sectionOrCourseChoice = 'course';
                exist.newFlowChoice();
                
                //ensure section assignment details are populated
                exist.assignmentWrapper.attachAssignment = false;
    
                //hit submit!
                exist.submit();                             
            Test.stopTest();            
        }   
                
    }       
    
    static testMethod void testTraditional_v2() {   
        createTestData();
        Test.startTest();
        system.runAs(testDataSetupUtil_v2.staffUsersList[0]) {      
            Gradebook_AssignmentController_v2 newAssignmentController = new Gradebook_AssignmentController_v2();
            newAssignmentController.newAssignmentFlow();
            newAssignmentController.standardBased=true;
            newAssignmentController.standardOnly = true;
            newAssignmentController.addStandards();
            newAssignmentController.removeStandards();
             newAssignmentController.assignmentWrapper.createAssignmentLibrary();
            newAssignmentController.assignmentWrapper.createNewLibraryFromExisting();
            newAssignmentController.assignmentWrapper.assignmentName = 'testing';
            newAssignmentController.assignmentWrapper.assignmentCourse = newAssignmentController.courseOptions[0].getValue();
             newAssignmentController.rPoints=true;
            newAssignmentController.setSelectedAssignmentTypeOptions();
            newAssignmentController.assignmentWrapper.assignmentType = newAssignmentController.selectedAssignmentTypeOptions[0].getValue();
            
            //selecting section or course
            newAssignmentController.sectionOrCourseChoice = 'section';
            newAssignmentController.newFlowChoice();
            newAssignmentController.renderPointsField();  //render just to get the call on page
            
            //ensure section assignment details are populated
            //select gradescales
            newAssignmentController.assignmentWrapper.gradeScale = newAssignmentController.gradeScaleOptions[0].getValue();
            newAssignmentController.assignmentWrapper.attachAssignment = false;
            
            //select a section
            newAssignmentController.sections[0].selected = true;
            //select a reportingPeriod
            newAssignmentController.sections[0].reportingPeriod = testDataSetupUtil_v2.semester.ID;
            //select a dueDate
            newAssignmentController.sections[0].dueDate = testDataSetupUtil_v2.semester.Date_Start_Date__c.addDays(1).format();
            
            //hit submit!
            newAssignmentController.Cancel();                       
        }   
        Test.stopTest();                
    }
    
    static testMethod void testTraditional_v2_existingToSection() { 
        createTestData();
        Test.startTest();
        system.runAs(testDataSetupUtil_v2.staffUsersList[0]) {      
            Gradebook_AssignmentController_v2 newAssignmentController = new Gradebook_AssignmentController_v2();
            newAssignmentController.newAssignmentFlow();
            newAssignmentController.assignmentWrapper.assignmentCourse = newAssignmentController.courseOptions[0].getValue();
            newAssignmentController.rPoints=true;
            newAssignmentController.setSelectedAssignmentTypeOptions();
            newAssignmentController.assignmentWrapper.assignmentName = 'testing';
            newAssignmentcontroller.assignmentWrapper.gradebookName = 'test';
            newAssignmentController.standardBased=true;
            newAssignmentController.standardOnly = true;
            newAssignmentController.addStandards();
            newAssignmentController.removeStandards();
             newAssignmentController.assignmentWrapper.createAssignmentLibrary();
            newAssignmentController.assignmentWrapper.createNewLibraryFromExisting();
            newAssignmentController.assignmentWrapper.assignmentType = newAssignmentController.selectedAssignmentTypeOptions[0].getValue();
            newAssignmentController.assignmentWrapper.assignmentWeighting = 1;
            newAssignmentController.addStandards();
            newAssignmentController.removeStandards();
            newAssignmentController.setDefaultAssignmentWeighting();
            //ensure section assignment details are populated
            //select gradescales
            newAssignmentController.assignmentWrapper.gradeScale = newAssignmentController.gradeScaleOptions[0].getValue();
            newAssignmentController.assignmentWrapper.attachAssignment = false;
            
            //select a section
            newAssignmentController.sections[0].selected = true;
            //select a reportingPeriod
            newAssignmentController.sections[0].reportingPeriod = testDataSetupUtil_v2.semester.ID;
            //select a dueDate
            newAssignmentController.sections[0].dueDate = testDataSetupUtil_v2.semester.Date_Start_Date__c.addDays(1).format();
            
            //hit submit!, want this data
            //Test.startTest();
            newAssignmentController.Submit();
            
                //instantiate GB, then run the test
                pageReference setGBAssignmentCreation = new pageReference('/apex/Gradebook_AddAssignments_v2');
                Test.setCurrentPage(setGBAssignmentCreation);
                Gradebook_AssignmentController_v2 exist = new Gradebook_assignmentController_v2();
            
                exist.standardBased = false;
                exist.standardOnly = false;
                exist.existingAssignmentFlow();
                
                //search for assignments
                //exist.assignmentWrapper.courseSearch = exist.courseOptions[0].getLabel();
                exist.assignmentWrapper.courseSearch = 'All';
                exist.assignmentWrapper.assignmentTypeSearch = 'Any';
                exist.assignmentWrapper.searchMethod(); 
                
                //select first assignment, should be the one created before test.start

                //System.assert(exist.assignmentWrapper.searchAssignmentResults.size()==0);
//              setGBAssignmentCreation.getParameters().put('assignmentLibraryID', exist.assignmentWrapper.searchAssignmentResults[0].ID);
                exist.selectAssignment();
                        
                //selecting section or course
                exist.sectionOrCourseChoice = 'section';
                exist.newFlowChoice();
                
                //ensure section assignment details are populated
                //select gradescales
                exist.assignmentWrapper.gradeScale = newAssignmentController.gradeScaleOptions[0].getValue();
                exist.assignmentWrapper.attachAssignment = false;
                
                //select a section
//              exist.sections[0].selected = true;
//              //select a reportingPeriod
//              exist.sections[0].reportingPeriod = testDataSetupUtil_v2.semester.ID;
//              //select a dueDate
//              exist.sections[0].dueDate = testDataSetupUtil_v2.semester.Date_Start_Date__c.addDays(2).format();
            
                //hit submit!
                exist.submit();             
            Test.stopTest();                        
        }           
    }   
}