objects/Course__c.object
<CustomObject>
    <label>Course</label>
    <nameField>
        <label>Course Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Courses</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/Period__c.object
<CustomObject>
    <label>Period</label>
    <nameField>
        <label>Period Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Periods</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Room__c.object
<CustomObject>
    <label>Room</label>
    <nameField>
        <label>Room Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Rooms</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Scheduled_Section__c.object
<CustomObject>
    <fields>
        <fullName>Color__c</fullName>
        <label>Color</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Course__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Course</label>
        <referenceTo>Course__c</referenceTo>
        <relationshipName>Schedule_Templates</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Room__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Room</label>
        <referenceTo>Room__c</referenceTo>
        <relationshipName>Schedule_Templates</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Section_ReportingPeriod__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Section/ReportingPeriod</label>
        <referenceTo>Section_ReportingPeriod__c</referenceTo>
        <relationshipLabel>Scheduled Sections</relationshipLabel>
        <relationshipName>Scheduled_Sections</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Section__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Section</label>
        <referenceTo>Section__c</referenceTo>
        <relationshipLabel>Scheduled Sections</relationshipLabel>
        <relationshipName>Scheduled_Sections</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Staff__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Staff</label>
        <referenceTo>Staff__c</referenceTo>
        <relationshipName>Schedule_Templates</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Scheduled Section</label>
    <nameField>
        <label>Scheduled Section Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Scheduled Sections</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Section__c.object
<CustomObject>
    <fields>
        <fullName>Color__c</fullName>
        <inlineHelpText>Select the color you want to display for this section in the Scheduled Sections grid. This color only appears on the schedule grid and is meant to help you differentiate between sections.</inlineHelpText>
        <label>Color</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Course__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Select the course associated to the section you want to create.</inlineHelpText>
        <label>Course</label>
        <referenceTo>Course__c</referenceTo>
        <relationshipLabel>Sections</relationshipLabel>
        <relationshipName>Sections</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Period__c</fullName>
        <label>Period</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Room__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Room</label>
        <referenceTo>Room__c</referenceTo>
        <relationshipLabel>Sections</relationshipLabel>
        <relationshipName>Sections</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Section__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Recursive lookup for groups</description>
        <label>Section</label>
        <referenceTo>Section__c</referenceTo>
        <relationshipLabel>Groups in Section</relationshipLabel>
        <relationshipName>Sections1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Staff__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Staff</label>
        <referenceTo>Staff__c</referenceTo>
        <relationshipLabel>Sections</relationshipLabel>
        <relationshipName>Sections</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Section</label>
    <nameField>
        <label>Section Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sections</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Section_ReportingPeriod__c.object
<CustomObject>
    <fields>
        <fullName>Period__c</fullName>
        <label>Period</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Section__c</fullName>
        <label>Section</label>
        <referenceTo>Section__c</referenceTo>
        <relationshipLabel>Section/ReportingPeriod</relationshipLabel>
        <relationshipName>Section_ReportingPeriod</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Section/ReportingPeriod</label>
    <nameField>
        <displayFormat>SR-{000000}</displayFormat>
        <label>Section/ReportingPeriod</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Section/ReportingPeriod</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Staff__c.object
<CustomObject>
    <fields>
        <fullName>Supervisor__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Supervisor</label>
        <referenceTo>Staff__c</referenceTo>
        <relationshipLabel>Staff</relationshipLabel>
        <relationshipName>Staff</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Staff</label>
    <nameField>
        <label>Staff Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Staff</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/Time_Element__c.object
<CustomObject>
    <label>Time</label>
    <nameField>
        <displayFormat>T-{000000}</displayFormat>
        <label>Time Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Time</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/SchedulerGrid_SectionWrapper.cls
public with sharing class SchedulerGrid_SectionWrapper {


    public string sTextColor {get;set;}
    public string sDisplay {get;set;}
    public Room__c room {get;set;}
    public Staff__c staff {get;set;}
    public Period__c    period {get;set;}
    public List <Scheduled_Section__c> ssList {get;set;}
    public string RoomId {get;set;}
    public string StaffId {get;set;}
    public string courseId {get;set;}
    public string sectId {get;set;}
    public string sectRpId {get;set;}
    public boolean hasError {get;set;}
    public SchedulerGrid_SectionWrapper (List <Scheduled_Section__c> tempSsList, Period__c p){
        this.sslist = tempSsList;
     //   Scheduled_Section__c schedSec = tempSsList[0];
       // this.staff = schedSec.staff__r;
       // this.room = schedSec.room__r;
       // if (schedSec.room__c!=null) this.roomId =this.room.id;
        //this.staffId = schedSec.Staff__c;
       // this.courseId = schedSec.course__c;
       // this.sectId = schedSec.section__c;
       // this.sectRpId = schedSec.Section_ReportingPeriod__c;
        //if (schedSec.section__r.color__c==null){
           //     this.sTextColor = '';
       // }
       // else      {
          //      if (schedSec.section__r.color__c.contains('#')==false) this.sTextColor = '#000000';
             //   else  this.sTextColor = core_coloringUtils.getTextColor(schedSec.section__r.color__c);
        //}
        this.period=p;
    }
    public SchedulerGrid_SectionWrapper(sObject s, Period__c p, Time_Element__c rp, boolean bRoomView){
        this.ssList = new List <Scheduled_Section__c>{};
        if (!bRoomView)             {
                this.staff = (Staff__c)s;
       //         this.ssList[0].staff__c = s.id;
        }
                  else                        {
                                this.room = (Room__c)s;
                                this.roomId = s.id;
                     //           this.ssList[0].room__c = s.id;
                  }
        this.period = p;
        this.sDisplay = 'none;';
   //     this.staffId = ssList[0].Staff__c;
    }
    public SchedulerGrid_SectionWrapper(Staff__c s, Period__c p, Time_Element__c rp){
        this.staff = s;
         this.ssList = new List <Scheduled_Section__c>{};

        this.period = p;
        this.sDisplay = 'none;';
   //     this.staffId = ssList[0].Staff__c;
    }
    public SchedulerGrid_SectionWrapper(Room__c r, Period__c p, Time_Element__c rp){
        this.room = r;
          this.ssList = new List <Scheduled_Section__c>{};

        this.period = p;
        this.sDisplay = 'none;';
        this.roomId = r.id;
    }
    
   
    
    


}