objects/Course__c.object
<CustomObject>
    <fields>
        <fullName>Number_of_Reporting_Periods__c</fullName>
        <defaultValue>1</defaultValue>
        <inlineHelpText>Select the default number of reporting periods over which the sections in this course will meet. If the number of reporting periods for this course is variable, you can define additional reporting period durations by clicking Edit Grade Weightings.</inlineHelpText>
        <label>Number of Reporting Periods</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Course</label>
    <nameField>
        <label>Course Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Courses</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/Course_Weightings__c.object
<CustomObject>
    <description>Stores Weightings for a course per reporting period when Final Grade is calculated</description>
    <fields>
        <fullName>Course__c</fullName>
        <label>Course</label>
        <referenceTo>Course__c</referenceTo>
        <relationshipLabel>Course Weightings</relationshipLabel>
        <relationshipName>Course_Weightings</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Key__c</fullName>
        <description>Key/Indicator for Reporting Period # that Aligns to the Weighting</description>
        <label>Reporting Period</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Reporting_Period_Type__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The reporting period picklist value (Time Record Type) that the Course Weighting is related to</description>
        <label>Reporting Period Type</label>
        <referenceTo>Picklist_Value__c</referenceTo>
        <relationshipLabel>Course Weightings</relationshipLabel>
        <relationshipName>Course_Weightings</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Time__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Reporting Period</label>
        <referenceTo>Time_Element__c</referenceTo>
        <relationshipLabel>Course Weightings</relationshipLabel>
        <relationshipName>Course_Weightings</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Weighting__c</fullName>
        <defaultValue>0</defaultValue>
        <label>% Weighting</label>
        <precision>5</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <label>Course Weighting</label>
    <nameField>
        <displayFormat>CWGHT-{000}</displayFormat>
        <label>Course Weightings Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Course Weightings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Period__c.object
<CustomObject>
    <fields>
        <fullName>Key__c</fullName>
        <label>Key</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Time__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Time</label>
        <referenceTo>Time_Element__c</referenceTo>
        <relationshipLabel>Periods</relationshipLabel>
        <relationshipName>Periods</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Period</label>
    <nameField>
        <label>Period Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Periods</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Picklist_Value__c.object
<CustomObject>
    <fields>
        <fullName>Corresponding_Value__c</fullName>
        <description>Used for Behavior values to relate a time value to the consequence type.</description>
        <label>Corresponding Value</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Picklist Value</label>
    <nameField>
        <label>Display Value</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Picklist Values</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Section__c.object
<CustomObject>
    <fields>
        <fullName>Course__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Select the course associated to the section you want to create.</inlineHelpText>
        <label>Course</label>
        <referenceTo>Course__c</referenceTo>
        <relationshipLabel>Sections</relationshipLabel>
        <relationshipName>Sections</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Number_of_Periods__c</fullName>
        <inlineHelpText>Select the number of periods over which you will schedule the section. SchoolForce will create a section square for the number of periods you select, enabling you to add the section to the schedule for multiple periods.</inlineHelpText>
        <label>Number of Periods</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>1</fullName>
                    <default>true</default>
                    <label>1</label>
                </value>
                <value>
                    <fullName>2</fullName>
                </value>
                <value>
                    <fullName>3</fullName>
                </value>
                <value>
                    <fullName>4</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Number_of_Reporting_Periods__c</fullName>
        <inlineHelpText>Select the number of reporting periods this section meets. SchoolForce will create a section square in each reporting period for the number you select. A grade weighting must be set up in the course for the selected number of reporting periods.</inlineHelpText>
        <label>Number of Reporting Periods</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>1</fullName>
                    <default>true</default>
                    <label>1</label>
                </value>
                <value>
                    <fullName>2</fullName>
                </value>
                <value>
                    <fullName>3</fullName>
                </value>
                <value>
                    <fullName>4</fullName>
                </value>
                <value>
                    <fullName>5</fullName>
                </value>
                <value>
                    <fullName>6</fullName>
                </value>
                <value>
                    <fullName>7</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Period__c</fullName>
        <label>Period</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Reporting_Period__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Usually the only reporting period; could be the first if the section spans multiple reporting periods.</description>
        <label>Reporting Period</label>
        <referenceTo>Time_Element__c</referenceTo>
        <relationshipLabel>Sections (First Reporting Period)</relationshipLabel>
        <relationshipName>Sections1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>School__c</fullName>
        <label>School</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Sections</relationshipLabel>
        <relationshipName>Sections</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Section__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Recursive lookup for groups</description>
        <label>Section</label>
        <referenceTo>Section__c</referenceTo>
        <relationshipLabel>Groups in Section</relationshipLabel>
        <relationshipName>Sections1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Time__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Time</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Time_Element__c.Picklist_Value__r.Name</field>
                <operation>equals</operation>
                <value>Year</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Time_Element__c</referenceTo>
        <relationshipLabel>Sections</relationshipLabel>
        <relationshipName>Sections</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Section</label>
    <nameField>
        <label>Section Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sections</pluralLabel>
    <recordTypes>
        <fullName>Unpublished</fullName>
        <active>true</active>
        <description>Unpublished Sections Used for Scheduler</description>
        <label>Unpublished</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Section_ReportingPeriod__c.object
<CustomObject>
    <fields>
        <fullName>Course_Weighting__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Course Weighting</label>
        <referenceTo>Course_Weightings__c</referenceTo>
        <relationshipLabel>Section/ReportingPeriod</relationshipLabel>
        <relationshipName>Section_ReportingPeriod</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Number_of_periods__c</fullName>
        <label>Number of periods</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>1</fullName>
                </value>
                <value>
                    <fullName>2</fullName>
                </value>
                <value>
                    <fullName>3</fullName>
                </value>
                <value>
                    <fullName>4</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Period__c</fullName>
        <label>Period</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ReferenceId__c</fullName>
        <externalId>true</externalId>
        <label>ReferenceId</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Scheduler_ReferenceId__c</fullName>
        <label>Scheduler ReferenceId</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Section__c</fullName>
        <label>Section</label>
        <referenceTo>Section__c</referenceTo>
        <relationshipLabel>Section/ReportingPeriod</relationshipLabel>
        <relationshipName>Section_ReportingPeriod</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Time__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Time</label>
        <referenceTo>Time_Element__c</referenceTo>
        <relationshipLabel>Section/ReportingPeriod</relationshipLabel>
        <relationshipName>Section_ReportingPeriod</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Section/ReportingPeriod</label>
    <nameField>
        <displayFormat>SR-{000000}</displayFormat>
        <label>Section/ReportingPeriod</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Section/ReportingPeriod</pluralLabel>
    <recordTypes>
        <fullName>UnPublished</fullName>
        <active>true</active>
        <label>Unpublished</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Time_Element__c.object
<CustomObject>
    <fields>
        <fullName>Reporting_Period__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Reporting Period?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>School__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>School</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Time</relationshipLabel>
        <relationshipName>Time</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Time</label>
    <nameField>
        <displayFormat>T-{000000}</displayFormat>
        <label>Time Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Time</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/Scheduler_TriggerUtils.cls
public with sharing class Scheduler_TriggerUtils {
	public static Map <String, Id> srpRecordTypeMap;
    
	public static void createSectionRPs(List<Section__c> sectionsList){
		Set<Id> courseIds = new Set<Id>();
		Set<Id> sectionIds = new Set<Id>();
		Map<Id,Id> sectionIdToGroupId = new Map<Id,Id>();
		srpRecordTypeMap = core_SoqlUtils.getRecordTypesBySobject('Section_ReportingPeriod__c');
		Map <Id, Map <Id, Section_ReportingPeriod__c>> sectionToSectionRpMap= new Map <Id, Map <Id, Section_ReportingPeriod__c>> ();

		
		List <Section_ReportingPeriod__c> upsertSrpList = new List <Section_ReportingPeriod__c>();
		List <Section_ReportingPeriod__c> deleteSrpList = new List <Section_ReportingPeriod__c>();
		Map <String,Map<String, Course_Weightings__c>> courseWeightingsByCourseConfig = new Map <String, Map<String, Course_Weightings__c>>(); //New for US1250

		
		for(Section__c s : sectionsList){
			sectionIds.add(s.Id);
			sectionToSectionRpMap.put(s.id, new Map <Id, Section_ReportingPeriod__c>{});
			courseIds.add(s.course__c);
		}
		sectionIdToGroupId = scheduler_SoqlUtils.getGroupsBySections(sectionIds);
		
		for(Course_Weightings__c cw:[select Id, Name,Time__c, Key__c, Weighting__c, Course__c , Reporting_Period_Type__r.corresponding_Value__c
	        	                                 from Course_Weightings__c 
	        	                                 where Course__c in :courseIds
	        	                                 order by Key__c]) {
	    	     String cwConfigKey = cw.course__c+'-'+cw.Reporting_Period_Type__r.corresponding_Value__c;
	    	     if (courseWeightingsByCourseConfig.get(cwConfigKey)==null){
	    	     	courseWeightingsByCourseConfig.put(cwConfigKey, new Map <String, Course_Weightings__c>{cw.key__c=>cw});
	    	     }
	    	     else {
	    	     	courseWeightingsByCourseConfig.get(cwConfigKey).put(cw.key__c, cw);     
	    	     }                       	
	    }
		
		for (Section_ReportingPeriod__c srp : [select id, time__c, period__c, section__c, course_weighting__c from Section_ReportingPeriod__c where section__c in:sectionIds]){
			sectionToSectionRpMap.get(srp.section__c).put(srp.time__c, srp);
		}
		
            for(Section__c sec : sectionsList){
                integer i=0; 
                String lastPeriod;              
                Id termId = Section_Utils.parentTeMap.get(sec.reporting_period__c);
                List <Time_Element__c> teList = Section_Utils.termRpMap.get(termId);
                for (Time_Element__c te: teList){
                    if (te.id == sec.Reporting_Period__c|| i!=0 && i<Integer.valueOf(sec.number_of_reporting_periods__c)){
              			 if (sectionToSectionRpMap.get(sec.id).get(te.id)!=null){
                			lastPeriod = sectionToSectionRpMap.get(sec.id).get(te.id).period__c;
                		}
                        i++;
                        String cwConfigKey = sec.course__c+'-'+sec.number_of_reporting_periods__c;
	                        if (courseWeightingsByCourseConfig.get(cwConfigKey)!=null){
	                        Course_Weightings__c cw = courseWeightingsByCourseConfig.get(cwConfigKey).get(string.valueOf(i));
	                        Section_ReportingPeriod__c sectionRp = createSectionRp(sec, te.id, cw);
	                        sectionRp.period__c = lastPeriod;
	                        if(sectionIdToGroupId != null){
		                        if(sectionIdToGroupId.containskey(sec.Id))
		                        sectionRp.Scheduler_ReferenceId__c = sec.School__c+'-'+sectionIdToGroupId.get(sec.Id)+'-'+sec.Course__c+'-'+te.Id;
	                        }
	                        upsertSrpList.add(sectionRp);
	                        //Check for finals
	                        //Add for Finals
	                        if (courseWeightingsByCourseConfig.get(cwConfigKey).get(string.valueOf(i+'-Final'))!=null){//First check if weightings actually have a final
	                        	Course_Weightings__c finalCw = courseWeightingsByCourseConfig.get(cwConfigKey).get(string.valueOf(i+'-Final'));
	                        	Section_ReportingPeriod__c finalsectionRp = createSectionRp(sec, Section_Utils.finalRpMap.get(te.id), finalCw);
	                        	upsertSrpList.add(finalsectionRp);
	                        }
	                        else {//If not & sectionrp has one delete it
	                        	if (sectionToSectionRpMap.get(sec.id).get(Section_Utils.finalRpMap.get(te.id))!=null){ //Do current section reporting periods have a final thats no longer valid?
	                        		deleteSrpList.add(sectionToSectionRpMap.get(sec.id).get(Section_Utils.finalRpMap.get(te.id)));  //Then add it to the list to delete
	                        	}
	                        }
	                    }
                    }
                    else {
                    	//check for existing ones that are no longer valid and puge them
                    	if (sectionToSectionRpMap.get(sec.id).get(te.id)!=null){
                    		deleteSrpList.add(sectionToSectionRpMap.get(sec.id).get(te.id));
                    		if (sectionToSectionRpMap.get(sec.id).get(Section_Utils.finalRpMap.get(te.id))!=null){ //Does bad section reporting periods have a final thats no longer valid?
                        		deleteSrpList.add(sectionToSectionRpMap.get(sec.id).get(Section_Utils.finalRpMap.get(te.id)));  //Then add it to the list to delete
                        	}
                    	}
                    }
                }
            }
                if(upsertSrpList.size() > 0){
                    try{
                        upsert upsertSrpList ReferenceId__c;
                            
                        //Summer 2014: need to verify this
                        //Gradebook_ManageGradebook.createSectionGradesForStudents(upsertSrpList);
                    }catch(Exception ex){
                        System.debug('Upsert failed'+ex.getmessage());
                    }       
                }
                if(deleteSrpList.size() > 0){
                    Set <Id> failedSectionRdIds = new Set <Id>();
                    Set <Id> failedSectionIds = new Set <Id>();
                    List<Database.deleteResult> dResults =Database.delete(deleteSrpList,false);
                    core_triggerUtils.b = true;
                    for(Database.DeleteResult d: dResults){
                        if (!d.isSuccess()){
                            failedSectionIds.add(d.getId());
                        }
                    }
                    core_triggerUtils.b = false;
                    for (Section_ReportingPeriod__c srp: deleteSrpList){
                        if(failedSectionIds.contains(srp.id)){
                            failedSectionIds.add(srp.section__c);
                        }
                    }
                    for (Section__c sect: sectionsList){
                        if(failedSectionIds.contains(sect.id)){
                            sect.addError('Not Allowed');
                        }
                    }
                    system.debug('----------deleteSrpList--------------'+deleteSrpList);
                }
                 
     			if (!upsertSrpList.isEmpty()){
     				//Summer 2014: need to verify this
     				Gradebook_ManageGradebook.createSectionGradesForStudents(upsertSrpList);
     			}
    } 
    
    public static Section_ReportingPeriod__c createSectionRp(Section__c sec, Id teId, Course_Weightings__c cw){
    	Section_ReportingPeriod__c sectionRp = new Section_ReportingPeriod__c();
        if(sec.Number_of_Periods__c != null)  sectionRp.Number_of_Periods__c= sec.Number_of_Periods__c;
        sectionRp.Section__c = sec.Id;
        sectionRp.Time__c = teId;     
        sectionRp.RecordTypeId = srpRecordTypeMap.get('UnPublished');
        sectionRp.ReferenceId__c = sec.Id+'-'+teId;
        sectionRp.Course_Weighting__c = cw.id;
        return sectionRp;
    }
    
    public static void processAfterInsert(Map<Id,Section_ReportingPeriod__c> newSectionRPMap){
    	Scheduler_TriggerUtils.updateSectionPeriod(newSectionRPMap,null);
    }
    
     public static void processAfterUpdate(Map<Id,Section_ReportingPeriod__c> newSectionRPMap, Map<Id,Section_ReportingPeriod__c> oldSectionRPMap){
    	Scheduler_TriggerUtils.updateSectionPeriod(newSectionRPMap,oldSectionRPMap);
    }
    
    public static void updateSectionPeriod(Map<Id,Section_ReportingPeriod__c> newSectionRPMap, Map<Id,Section_ReportingPeriod__c> oldSectionRPMap){
    	Map<Id, Section__c> sectionMap = new Map<Id, Section__c>();
    	for(Section_ReportingPeriod__c srp: [SELECT Period__c, Time__c,Section__r.Period__c,Section__r.Reporting_Period__c
    										 FROM Section_ReportingPeriod__c WHERE Id in: newSectionRPMap.keyset() AND Period__c <> null]){
    		if((oldSectionRPMap == null) || (oldSectionRPMap!=null && oldSectionRPMap.get(srp.Id).Period__c != newSectionRPMap.get(srp.Id).Period__c)	){							 	
	    		if(srp.Time__c == srp.Section__r.Reporting_Period__c && srp.Period__c != '' && srp.Period__c != null){
	    			srp.Section__r.Period__c = srp.Period__c;
	    			sectionMap.put(srp.Section__c,srp.Section__r);
	    		}									 	
    		}
    	}
		if(sectionMap.values().size() > 0){
			update sectionMap.values();
		}
    } 
}