objects/Course__c.object
<CustomObject>
    <fields>
        <fullName>Number_of_Reporting_Periods__c</fullName>
        <defaultValue>1</defaultValue>
        <inlineHelpText>Select the default number of reporting periods over which the sections in this course will meet. If the number of reporting periods for this course is variable, you can define additional reporting period durations by clicking Edit Grade Weightings.</inlineHelpText>
        <label>Number of Reporting Periods</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Course</label>
    <nameField>
        <label>Course Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Courses</pluralLabel>
    <recordTypes>
        <fullName>Course</fullName>
        <active>true</active>
        <label>Course</label>
    </recordTypes>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/Course_Weightings__c.object
<CustomObject>
    <description>Stores Weightings for a course per reporting period when Final Grade is calculated</description>
    <fields>
        <fullName>Course__c</fullName>
        <label>Course</label>
        <referenceTo>Course__c</referenceTo>
        <relationshipLabel>Course Weightings</relationshipLabel>
        <relationshipName>Course_Weightings</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Reporting_Period_Type__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The reporting period picklist value (Time Record Type) that the Course Weighting is related to</description>
        <label>Reporting Period Type</label>
        <referenceTo>Picklist_Value__c</referenceTo>
        <relationshipLabel>Course Weightings</relationshipLabel>
        <relationshipName>Course_Weightings</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Course Weighting</label>
    <nameField>
        <displayFormat>CWGHT-{000}</displayFormat>
        <label>Course Weightings Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Course Weightings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Picklist_Value__c.object
<CustomObject>
    <fields>
        <fullName>Corresponding_Value__c</fullName>
        <description>Used for Behavior values to relate a time value to the consequence type.</description>
        <label>Corresponding Value</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Picklist Value</label>
    <nameField>
        <label>Display Value</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Picklist Values</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Section__c.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Check this box if the section is a currently active section</description>
        <inlineHelpText>Check this box if the section is a currently active section</inlineHelpText>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Course__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Select the course associated to the section you want to create.</inlineHelpText>
        <label>Course</label>
        <referenceTo>Course__c</referenceTo>
        <relationshipLabel>Sections</relationshipLabel>
        <relationshipName>Sections</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Number_of_Periods__c</fullName>
        <inlineHelpText>Select the number of periods over which you will schedule the section. SchoolForce will create a section square for the number of periods you select, enabling you to add the section to the schedule for multiple periods.</inlineHelpText>
        <label>Number of Periods</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>1</fullName>
                    <default>true</default>
                    <label>1</label>
                </value>
                <value>
                    <fullName>2</fullName>
                </value>
                <value>
                    <fullName>3</fullName>
                </value>
                <value>
                    <fullName>4</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Number_of_Reporting_Periods__c</fullName>
        <inlineHelpText>Select the number of reporting periods this section meets. SchoolForce will create a section square in each reporting period for the number you select. A grade weighting must be set up in the course for the selected number of reporting periods.</inlineHelpText>
        <label>Number of Reporting Periods</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>1</fullName>
                    <default>true</default>
                    <label>1</label>
                </value>
                <value>
                    <fullName>2</fullName>
                </value>
                <value>
                    <fullName>3</fullName>
                </value>
                <value>
                    <fullName>4</fullName>
                </value>
                <value>
                    <fullName>5</fullName>
                </value>
                <value>
                    <fullName>6</fullName>
                </value>
                <value>
                    <fullName>7</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Reporting_Period__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Usually the only reporting period; could be the first if the section spans multiple reporting periods.</description>
        <label>Reporting Period</label>
        <referenceTo>Time_Element__c</referenceTo>
        <relationshipLabel>Sections (First Reporting Period)</relationshipLabel>
        <relationshipName>Sections1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>School__c</fullName>
        <label>School</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Sections</relationshipLabel>
        <relationshipName>Sections</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Section__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Recursive lookup for groups</description>
        <label>Section</label>
        <referenceTo>Section__c</referenceTo>
        <relationshipLabel>Groups in Section</relationshipLabel>
        <relationshipName>Sections1</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Section</label>
    <nameField>
        <label>Section Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sections</pluralLabel>
    <recordTypes>
        <fullName>Published</fullName>
        <active>true</active>
        <description>Sections that have been Published and are Viewable by Standard Users</description>
        <label>Published</label>
    </recordTypes>
    <recordTypes>
        <fullName>Unpublished</fullName>
        <active>true</active>
        <description>Unpublished Sections Used for Scheduler</description>
        <label>Unpublished</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Time_Element__c.object
<CustomObject>
    <fields>
        <fullName>Parent_Time_Element__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Parent Time Element</label>
        <referenceTo>Time_Element__c</referenceTo>
        <relationshipLabel>Children Time Elements</relationshipLabel>
        <relationshipName>Time</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Picklist_Value__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Picklist Value</label>
        <referenceTo>Picklist_Value__c</referenceTo>
        <relationshipLabel>Time</relationshipLabel>
        <relationshipName>Time</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Reporting_Period__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Reporting Period?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>School__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>School</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Time</relationshipLabel>
        <relationshipName>Time</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Time</label>
    <nameField>
        <displayFormat>T-{000000}</displayFormat>
        <label>Time Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Time</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/Course_Weightings_Utils.cls
public with sharing class Course_Weightings_Utils {


	/***************** Start of Course Weightings Util methods***********************************/
			
	public static void processBeforeInsert(List <Course_Weightings__c> newList){
	}
	public static void processAfterInsert(Map <Id, Course_Weightings__c> newMap){
		createSectionRps(newMap);
	}
	public static void processBeforeUpdate(Map <Id, Course_Weightings__c> newMap, Map<Id, Course_Weightings__c> oldMap){
	}
	public static void processAfterUpdate(Map <Id, Course_Weightings__c> newMap, Map<Id, Course_Weightings__c> oldMap){
		
	}
	public static void processBeforeDelete(Map <Id, Course_Weightings__c> oldMap){
		createSectionRps(oldMap);
	}  
	
	
	
	public static void createSectionRps(Map <Id, Course_Weightings__c> newMap){
		Set <String> courseWeightingConfigKeySet = new Set <String>();
		Set <Id>		courseIds  = new Set <Id>();
		Set <Id> rpPlValueSet = new Set <Id>();
		Set <Id>	sectionIds = new Set <Id>();
		List <Section__c> sectionList = new List <Section__c>();
		Map <Id, Picklist_Value__c> rpPlValueMap = new Map <Id, Picklist_Value__c>();
		for (Course_Weightings__c cw: newMap.values()){
			rpPlValueSet.add(cw.reporting_period_Type__c);
		}
		for (Picklist_Value__c plv: [select id, corresponding_value__c from Picklist_Value__c where id in:rpPlValueSet]){
			rpPlValueMap.put(plv.id, plv);
		}
		system.debug('rpPlValueMap~~~~'+rpPlValueMap);
		for (Course_Weightings__c cw: newMap.values()){
			courseIds.add(cw.course__c);
			system.debug('cw.reporting_period_type__c~~~'+cw.reporting_period_type__c);
			courseWeightingConfigKeySet.add(cw.course__c+'-'+rpPlValueMap.get(cw.reporting_period_type__c).corresponding_value__c);
		}	
		system.debug('courseWeightingConfigKeySet~~~'+courseWeightingConfigKeySet);
		for (Section__c sect : [select id , course__c, School__c, number_of_reporting_periods__c, Reporting_Period__c,Number_of_Periods__c , Reporting_Period__r.Parent_Time_Element__c,  Section__c.RecordTypeId
													from Section__c 
													where Active__c = true 
											and (RecordType.DeveloperName='Published' or RecordType.DeveloperName='Unpublished')
											and course__c in:courseIds]	){
			string sectionCwKey = sect.course__c+'-'+sect.number_of_reporting_periods__c;
			system.debug('sectionCwKey~~~~'+sectionCwKey);
			if (courseWeightingConfigKeySet.contains(sectionCwKey)){
				sectionList.add(sect);
			}
		}
		
		Section_Utils.reportingPeriodIds = new Set <Id>();
		for (Section__c sect: sectionList) Section_Utils.reportingPeriodIds.add(sect.reporting_period__c);
		
		if (!Section_Utils.reportingPeriodIds.isEmpty()){
			if (section_Utils.termRpMap==null){
				Section_Utils.getTeConfig();
			}
		}
		
		if (!sectionList.isEmpty()){
			Scheduler_TriggerUtils.createSectionRPs(sectionList); 
			
		}
			
	
	}
}