objects/Course__c.object
<CustomObject>
    <fields>
        <fullName>Include_in_section_snapshot__c</fullName>
        <defaultValue>true</defaultValue>
        <inlineHelpText>Select if you want SchoolForce to include the information for this course in the Section snapshots that are created in the End of Year Wizard</inlineHelpText>
        <label>Include in section snapshot</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Subject_Area_Lookup__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Select the applicable subject area for this course. You can use the subject area for reporting purposes as well as for cohort requirements.</inlineHelpText>
        <label>Subject Area Lookup</label>
        <referenceTo>Course__c</referenceTo>
        <relationshipLabel>Courses (Subject Area Lookup)</relationshipLabel>
        <relationshipName>Course</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Course</label>
    <nameField>
        <label>Course Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Courses</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/Section__c.object
<CustomObject>
    <fields>
        <fullName>Course__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Select the course associated to the section you want to create.</inlineHelpText>
        <label>Course</label>
        <referenceTo>Course__c</referenceTo>
        <relationshipLabel>Sections</relationshipLabel>
        <relationshipName>Sections</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>School__c</fullName>
        <label>School</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Sections</relationshipLabel>
        <relationshipName>Sections</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Section__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Recursive lookup for groups</description>
        <label>Section</label>
        <referenceTo>Section__c</referenceTo>
        <relationshipLabel>Groups in Section</relationshipLabel>
        <relationshipName>Sections1</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Section</label>
    <nameField>
        <label>Section Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sections</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Session__c.object
<CustomObject>
    <description>This object captures the daily session for each section.</description>
    <fields>
        <fullName>Section__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This is a lookup to the section that the session belongs to.</description>
        <label>Section</label>
        <referenceTo>Section__c</referenceTo>
        <relationshipLabel>Sessions</relationshipLabel>
        <relationshipName>Sessions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Start_DateTime__c</fullName>
        <description>Date and time that session starts</description>
        <label>Start Date Time</label>
        <type>DateTime</type>
    </fields>
    <label>Session</label>
    <nameField>
        <label>Session Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sessions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Setup__c.object
<CustomObject>
    <description>This object is used to setup Schoolforce and is referenced in multiple pieces of code.  There should be one setup object per school.</description>
    <fields>
        <fullName>School__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>School</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1 OR 2</booleanFilter>
            <filterItems>
                <field>Account.RecordType.Name</field>
                <operation>equals</operation>
                <value>School</value>
            </filterItems>
            <filterItems>
                <field>Account.RecordType.Name</field>
                <operation>equals</operation>
                <value>Summer School</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Setup</relationshipLabel>
        <relationshipName>Setup</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Setup</label>
    <nameField>
        <displayFormat>S-{0}</displayFormat>
        <label>Setup ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Setup</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/Snapshot_Summary__c.object
<CustomObject>
    <fields>
        <fullName>School__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>School</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Snapshot Summaries</relationshipLabel>
        <relationshipName>Snapshot_Summaries</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Snapshot Summary</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Snapshot Summary ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Snapshot Summaries</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/Batch_SchoolSnapshotSessionCalc.cls
global class Batch_SchoolSnapshotSessionCalc implements Database.Batchable<SObject>, Database.Stateful{	
	private String setupID;
	private Date startDate {get; set;}
	private Date endDate {get; set;}
	
	private Snapshot_Summary__c summary;
	private DataLoadLogList dataLogs;
	
	public Map<ID, Integer> sessionMap {get; set;}
	private Setup__c currentSetup {get; set;}
	private ID SchoolID {get; set;}
	
	global Batch_SchoolSnapshotSessionCalc(Snapshot_Summary__c s, DataLoadLogList d, String sID, Date sDate, Date eDate){
		summary = s;
		dataLogs = d;
		setupID = sID;
		startDate = sDate;
		endDate = eDate;
		sessionMap = new Map<ID, Integer>();
		currentSetup = core_SoqlUtils.getSetupById(setupID);
		schoolID = currentSetup.School__c;
	}
	
	global Database.QueryLocator start(Database.BatchableContext ctx){
		String query = '';
		try {
			query += 'SELECT ID, Section__c FROM Session__c '+
					'WHERE Section__r.School__c =: schoolID '+
					'AND Section__r.Course__r.Include_in_Section_Snapshot__c = TRUE '+
					'AND Start_DateTime__c >=: startDate '+
					'AND Start_DateTime__c <=: endDate '+
					'ORDER BY Section__c ASC';

			return Database.getQueryLocator(query);
		} catch(Exception e) {
			dataLogs.incrFailed(DataLoadLogList.SCHOOL_SECTION_SUMMARY);
			dataLogs.addLogMessage(null,'Failure when starting session batch.');
			insert Error_Handling.handleError('','Batch_SchoolSnapshotSessionCalc','Failure in start method',e);
		} finally{
			dataLogs.saveLogs();
		}
		return Database.getQueryLocator('select id from Session__c where ID = null');
	}
	
	global void execute(Database.BatchableContext ctx, List<SObject> scope){
		try{
			for(Session__c s : (List<Session__c>)scope) {
				if(!sessionMap.containsKey(s.ID)) {
					sessionMap.put(s.ID, 1);
				} else {
					Integer i = sessionMap.get(s.ID) + 1;
					sessionMap.put(s.ID, i);
				}
			}
		} catch (Exception e){
			dataLogs.incrFailed(DataLoadLogList.SCHOOL_SECTION_SUMMARY);
			dataLogs.addLogMessage(DataLoadLogList.SCHOOL_SECTION_SUMMARY,'Failure when loading session map.');
			insert Error_Handling.handleError('','Batch_SchoolSnapshotSessionCalc','Exception starting Batch_SchoolSnapshotAttendanceCalc',e);
			sessionMap = null;
		} finally{
			dataLogs.saveLogs();
		}
	}
	
	global void finish(Database.BatchableContext ctx){
		try{
			Batch_SchoolSnapshotAttendanceCalc attendanceBatch = new Batch_SchoolSnapshotAttendanceCalc(summary, dataLogs, setupID, startDate, endDate, sessionMap);
			Database.executeBatch(attendanceBatch);		
		} catch(Exception e){
			dataLogs.incrFailed(DataLoadLogList.SCHOOL_SECTION_SUMMARY);
			dataLogs.addLogMessage(DataLoadLogList.SCHOOL_SECTION_SUMMARY,'Failure starting attendance calculations.');
			insert Error_Handling.handleError('','Batch_SchoolSnapshotSessionCalc','Exception starting Batch_SchoolSnapshotAttendanceCalc',e);
		} finally {
			dataLogs.saveLogs();
		}
	}
}