objects/Curriculum__c.object
<CustomObject>
    <fields>
        <fullName>Curriculum_Name__c</fullName>
        <defaultValue>&quot;Do The Math&quot;</defaultValue>
        <label>Curriculum Name</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Do The Math</fullName>
                </value>
                <value>
                    <fullName>Do the Math Now!</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Date_of_Module__c</fullName>
        <label>Date of Assignment</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Module_Assignments__c</fullName>
        <label>Module Assignments</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Module_Name__c</controllingField>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Beginning of Module Assessment</fullName>
                </value>
                <value>
                    <fullName>SWYK: Lesson 5</fullName>
                </value>
                <value>
                    <fullName>SWYK: Lesson 10</fullName>
                </value>
                <value>
                    <fullName>SWYK: Lesson 15</fullName>
                </value>
                <value>
                    <fullName>SWYK: Lesson 20</fullName>
                </value>
                <value>
                    <fullName>SWYK: Lesson 25</fullName>
                </value>
                <value>
                    <fullName>SWYK: Lesson 30</fullName>
                </value>
                <value>
                    <fullName>End of Module Assessment</fullName>
                </value>
                <value>
                    <fullName>End</fullName>
                    <isActive>false</isActive>
                    <label>End</label>
                </value>
                <value>
                    <fullName>LLI Assignment 1</fullName>
                    <isActive>false</isActive>
                    <label>LLI Assignment 1</label>
                </value>
                <value>
                    <fullName>LLI Assignment 2</fullName>
                    <isActive>false</isActive>
                    <label>LLI Assignment 2</label>
                </value>
                <value>
                    <fullName>LLI Assignment 3</fullName>
                    <isActive>false</isActive>
                    <label>LLI Assignment 3</label>
                </value>
                <value>
                    <fullName>SWYK 1</fullName>
                    <isActive>false</isActive>
                    <label>SWYK 1</label>
                </value>
                <value>
                    <fullName>SWYK 2</fullName>
                    <isActive>false</isActive>
                    <label>SWYK 2</label>
                </value>
                <value>
                    <fullName>SWYK 3</fullName>
                    <isActive>false</isActive>
                    <label>SWYK 3</label>
                </value>
                <value>
                    <fullName>SWYK 4</fullName>
                    <isActive>false</isActive>
                    <label>SWYK 4</label>
                </value>
                <value>
                    <fullName>SWYK 5</fullName>
                    <isActive>false</isActive>
                    <label>SWYK 5</label>
                </value>
                <value>
                    <fullName>SWYK 6</fullName>
                    <isActive>false</isActive>
                    <label>SWYK 6</label>
                </value>
                <value>
                    <fullName>Start</fullName>
                    <isActive>false</isActive>
                    <label>Start</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Module_Name__c</fullName>
        <label>Module Name</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Curriculum_Name__c</controllingField>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Addition &amp; Subtraction: Number Core</fullName>
                </value>
                <value>
                    <fullName>Addition &amp; Subtraction: Module A</fullName>
                </value>
                <value>
                    <fullName>Addition &amp; Subtraction: Module B</fullName>
                </value>
                <value>
                    <fullName>Addition &amp; Subtraction: Module C</fullName>
                </value>
                <value>
                    <fullName>Multiplication: Module A</fullName>
                </value>
                <value>
                    <fullName>Multiplication: Module B</fullName>
                </value>
                <value>
                    <fullName>Multiplication: Module C</fullName>
                </value>
                <value>
                    <fullName>Division: Module A</fullName>
                </value>
                <value>
                    <fullName>Division: Module B</fullName>
                </value>
                <value>
                    <fullName>Division: Module C</fullName>
                </value>
                <value>
                    <fullName>Fractions: Module A</fullName>
                </value>
                <value>
                    <fullName>Fractions: Module B</fullName>
                </value>
                <value>
                    <fullName>Fractions: Module C</fullName>
                </value>
                <value>
                    <fullName>Unit 1: Build a Foundation for Multiplication</fullName>
                </value>
                <value>
                    <fullName>Unit 2: Develop Multiplication Number Sense</fullName>
                </value>
                <value>
                    <fullName>Unit 3: Use Place-Value Strategies to Multiply</fullName>
                </value>
                <value>
                    <fullName>Unit 4: Connect Multiplication and Division</fullName>
                </value>
                <value>
                    <fullName>Unit 5: Use Place Value Strategies to Divide</fullName>
                </value>
                <value>
                    <fullName>Unit 6: Develop Understanding of Fractions</fullName>
                </value>
                <value>
                    <fullName>Unit 7: Reason with Fractions</fullName>
                </value>
                <value>
                    <fullName>Unit 8: Extend Fraction Concepts and Comparing Strategies</fullName>
                </value>
                <value>
                    <fullName>Unit 9: Build on Equivalence to Estimate, Compare, Add, and Subtract</fullName>
                </value>
                <value>
                    <fullName>Unit 10: Develop Fraction Number Sense</fullName>
                </value>
                <value>
                    <fullName>LLI 1</fullName>
                    <isActive>false</isActive>
                    <label>LLI 1</label>
                </value>
                <value>
                    <fullName>LLI 2</fullName>
                    <isActive>false</isActive>
                    <label>LLI 2</label>
                </value>
                <value>
                    <fullName>LLI 3</fullName>
                    <isActive>false</isActive>
                    <label>LLI 3</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Module_Score__c</fullName>
        <label>Score</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Section__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Section</label>
        <referenceTo>Section__c</referenceTo>
        <relationshipLabel>Curricula</relationshipLabel>
        <relationshipName>Curriculums</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Student_Section__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Student/Section</label>
        <referenceTo>Student_Section__c</referenceTo>
        <relationshipLabel>Curricula</relationshipLabel>
        <relationshipName>Curriculums</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Curriculum</label>
    <nameField>
        <displayFormat>C-{0000}</displayFormat>
        <label>Curriculum ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Curricula</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Section__c.object
<CustomObject>
    <fields>
        <fullName>Section__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Recursive lookup for groups</description>
        <label>Section</label>
        <referenceTo>Section__c</referenceTo>
        <relationshipLabel>Groups in Section</relationshipLabel>
        <relationshipName>Sections1</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Section</label>
    <nameField>
        <label>Section Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sections</pluralLabel>
    <recordTypes>
        <fullName>Curriculum</fullName>
        <active>true</active>
        <label>Curriculum</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Skill__c.object
<CustomObject>
    <label>Skill</label>
    <nameField>
        <label>Skill Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Skills</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Student_Section__c.object
<CustomObject>
    <fields>
        <fullName>Section__c</fullName>
        <label>Section</label>
        <referenceTo>Section__c</referenceTo>
        <relationshipLabel>Student</relationshipLabel>
        <relationshipName>Student_Section</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Student/Section</label>
    <nameField>
        <displayFormat>SS-{000000}</displayFormat>
        <label>Student/Section ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Student/Section</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/ModalAddCurriculaControllerTest.cls
/**
 * Created by YuriyRudenko on 9/30/2020.
 */
@IsTest
public with sharing class ModalAddCurriculaControllerTest {
    private static Skill__c skill;
    public static Student_Section__c studentSections;
    private static final Integer COUNT = 5;
    private static final Integer AMOUNT = 30;

    private static void setupData() {
        testDataSetupUtil_v2.setUPCoreData(COUNT);
        testDataSetupUtil_v2.setUPStaffData(COUNT);
        testDataSetupUtil_v2.setUPStudentData(COUNT);
        testDataSetupUtil_v2.setUPProgramData(testDataSetupUtil_v2.sectionsList, testDataSetupUtil_v2.school);
        testDataSetupUtil_v2.setUPExistingSessionResults(AMOUNT);
        testDataSetupUtil_v2.setUpCurriculumData(COUNT);


        List<Section__c> groups = TestDataSetupUtil_v2.getScheduleGroups_Section();
    }

    static testMethod void testStartAddCurricula() {
        setupData();
        Test.startTest();
        ModalAddCurriculaController controller = new ModalAddCurriculaController();
        controller.section = testDataSetupUtil_v2.sectionsList[0];
        StudentInfoWrapper siw = new StudentInfoWrapper(testDataSetupUtil_v2.studSectionsList[0]);
        controller.studentSections = new List<StudentInfoWrapper>{
                siw
        };
        controller.studentSections[0].selected = true;
        controller.startAddCurricula();
        System.assertEquals(1, controller.curriculumStudents.size(), 'Expected all enrolled students to be loaded.');
        controller.curriculumStudents = new List<Curriculum__c>{
                controller.curriculum
        };

        controller.saveCurricula();
        controller.curriculum.Date_of_Module__c = null;
        controller.saveCurricula();
        controller.curriculum.Date_of_Module__c = Date.today();
        controller.curriculum.Curriculum_Name__c = 'test';
        controller.curriculum.Module_Name__c = '';
        controller.saveCurricula();
        controller.curriculum.Module_Name__c = 'test';
        controller.curriculum.Module_Assignments__c = '';
        controller.saveCurricula();
        controller.curriculum.Module_Assignments__c = 'test';
        controller.saveCurricula();
        controller.curriculumStudents[0].Module_Score__c = 21.1;
        controller.saveCurricula();

        Test.stopTest();
    }


    static testMethod void testStartEditCurricula() {
        setupData();

        Test.startTest();
        ModalAddCurriculaController controller = new ModalAddCurriculaController();
        StudentInfoWrapper siw = new StudentInfoWrapper(testDataSetupUtil_v2.studSectionsList[0]);
        controller.studentSections = new List<StudentInfoWrapper>{
                siw
        };
        controller.curriculumId = testDataSetupUtil_v2.curriculumList[0].Id;
        controller.startEditCurricula();
        System.assertEquals(1, controller.curriculumStudents.size(), 'Expected all enrolled students to be loaded.');
        Test.stopTest();
    }
}