objects/Daily_Meal_Summary__c.object
<CustomObject>
    <fields>
        <fullName>Key__c</fullName>
        <description>This field is a concatenation of the school ID and the date.</description>
        <label>Key</label>
        <length>36</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Non_Scan_Reimbursable_Breakfasts__c</fullName>
        <defaultValue>0</defaultValue>
        <description>Breakfast that is not scanned should be manually totalled and entered here.</description>
        <inlineHelpText>Breakfast that is not scanned should be manually totalled and entered here.</inlineHelpText>
        <label>Non-Scan Reimbursable Breakfasts</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>School__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>School</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Daily Meal Summaries</relationshipLabel>
        <relationshipName>Daily_Meal_Summaries</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Summary_Date__c</fullName>
        <description>This is the date the transaction records are being aggregated for .</description>
        <inlineHelpText>This is the date the transaction records are being aggregated for .</inlineHelpText>
        <label>Summary Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Total_Free_Breakfasts__c</fullName>
        <description>This is the total number of free breakfasts served that day.</description>
        <inlineHelpText>This is the total number of free breakfasts served that day.</inlineHelpText>
        <label>Total Free Breakfasts</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Total_Free_Lunches__c</fullName>
        <description>This is the total number of free lunches served that day.</description>
        <inlineHelpText>This is the total number of free lunches served that day.</inlineHelpText>
        <label>Total Free Lunches</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Total_Full_Price_Breakfasts__c</fullName>
        <description>This is the total number of full-priced breakfasts served that day.</description>
        <inlineHelpText>This is the total number of full-priced breakfasts served that day.</inlineHelpText>
        <label>Total Full-Price Breakfasts</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Total_Full_Price_Lunches__c</fullName>
        <description>This is the total number of full-priced lunches served that day.</description>
        <inlineHelpText>This is the total number of full-priced lunches served that day.</inlineHelpText>
        <label>Total Full-Price Lunches</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Total_Monies_Received__c</fullName>
        <description>This is the total amount received from students paying for either full-priced or reduced meals for the day.</description>
        <inlineHelpText>This is the total amount received from students paying for either full-priced or reduced meals for the day.</inlineHelpText>
        <label>Total Monies Received</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Total_Reduced_Breakfasts__c</fullName>
        <description>This is the total number of reduced breakfasts served that day.</description>
        <inlineHelpText>This is the total number of reduced breakfasts served that day.</inlineHelpText>
        <label>Total Reduced Breakfasts</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Total_Reduced_Lunches__c</fullName>
        <description>This is the total number of reduced lunches served that day.</description>
        <inlineHelpText>This is the total number of reduced lunches served that day.</inlineHelpText>
        <label>Total Reduced Lunches</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Daily Meal Summary</label>
    <nameField>
        <displayFormat>DMS-{0}</displayFormat>
        <label>Daily Meal Summary Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Daily Meal Summaries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Meal_Transaction__c.object
<CustomObject>
    <fields>
        <fullName>Daily_Meal_Summary__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Daily Meal Summary</label>
        <referenceTo>Daily_Meal_Summary__c</referenceTo>
        <relationshipLabel>Meal Transactions</relationshipLabel>
        <relationshipName>Meal_Transactions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Student__c</fullName>
        <label>Student</label>
        <referenceTo>Student__c</referenceTo>
        <relationshipLabel>Meal Transactions</relationshipLabel>
        <relationshipName>Meal_Transactions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Transaction_Amount__c</fullName>
        <description>This is the amount the student is required to pay for their meal.</description>
        <inlineHelpText>This is the amount the student is required to pay for their meal.</inlineHelpText>
        <label>Transaction Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Transaction_Date__c</fullName>
        <defaultValue>Now()</defaultValue>
        <label>Transaction Date</label>
        <required>true</required>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Transaction_Type__c</fullName>
        <label>Transaction Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Sale</fullName>
                </value>
                <value>
                    <fullName>Credit</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Void__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This should be checked if a transaction is voided.</description>
        <inlineHelpText>This should be checked if a transaction is voided.</inlineHelpText>
        <label>Void</label>
        <type>Checkbox</type>
    </fields>
    <label>Meal Transaction</label>
    <nameField>
        <displayFormat>T-{0}</displayFormat>
        <label>Meal Transaction Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Meal Transactions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Meals_Setup__c.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>School__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>School</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Meals</relationshipLabel>
        <relationshipName>Meals_Setup</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Setup__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Setup</label>
        <referenceTo>Setup__c</referenceTo>
        <relationshipLabel>Meals Setup</relationshipLabel>
        <relationshipName>Meals_Setup</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Students_Eligible_for_Free_Reduced__c</fullName>
        <description>This is the percentage of students who are eligible to receive free or reduced meals.</description>
        <inlineHelpText>This is the percentage of students who are eligible to receive free or reduced meals.</inlineHelpText>
        <label>% Students Eligible for Free/Reduced</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>of_Students_Receiving_Free_Meals__c</fullName>
        <label># of Students Receiving Free Meals</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>of_Students_Receiving_Full_Price_Meals__c</fullName>
        <label># of Students Receiving Full-Price Meals</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>of_Students_Receiving_Reduced_Meals__c</fullName>
        <label># of Students Receiving Reduced Meals</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Meals Setup</label>
    <nameField>
        <displayFormat>MS-{0}</displayFormat>
        <label>Meals Setup Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Meals Setup</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Setup__c.object
<CustomObject>
    <description>This object is used to setup Schoolforce and is referenced in multiple pieces of code.  There should be one setup object per school.</description>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Is this school setup active for this school year?</inlineHelpText>
        <label>Active?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>School__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>School</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1 OR 2</booleanFilter>
            <filterItems>
                <field>Account.RecordType.Name</field>
                <operation>equals</operation>
                <value>School</value>
            </filterItems>
            <filterItems>
                <field>Account.RecordType.Name</field>
                <operation>equals</operation>
                <value>Summer School</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Setup</relationshipLabel>
        <relationshipName>Setup</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Setup</label>
    <nameField>
        <displayFormat>S-{0}</displayFormat>
        <label>Setup ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Setup</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/Student__c.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>true</defaultValue>
        <inlineHelpText>Indicates whether or not this Student record is active. If checked, then this is the current Student record. If unchecked, this is an old Student record.</inlineHelpText>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Meals_Category__c</fullName>
        <inlineHelpText>Displays the type of meal program assigned to this student. The Meals module uses this field. You can also use it for reporting purposes.</inlineHelpText>
        <label>Meals Category</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Full-Priced</fullName>
                </value>
                <value>
                    <fullName>Reduced</fullName>
                </value>
                <value>
                    <fullName>Free</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>School__c</fullName>
        <inlineHelpText>Displays the name of the student&apos;s current SchoolForce school. You can click on the link to see the details of this school.</inlineHelpText>
        <label>School</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Students</relationshipLabel>
        <relationshipName>Students</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Setup__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Displays the Setup record associated to this Student record. The Setup record defines the settings for the school in a specific school year.</inlineHelpText>
        <label>Setup</label>
        <referenceTo>Setup__c</referenceTo>
        <relationshipLabel>Students</relationshipLabel>
        <relationshipName>Students</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Student__c</fullName>
        <inlineHelpText>Displays the student&apos;s middle name.</inlineHelpText>
        <label>Student Middle Name</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <label>Student</label>
    <nameField>
        <label>Student Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Students</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/Meals_ProcessTransactions.cls
public with sharing class Meals_ProcessTransactions {

	public static void isafter(List <Meal_Transaction__c> mtList, Boolean isDeleted, Meals_Setup__c mealSetup, ID schoolID){
	
		Set<String> dailyKeySet = new Set<String>();
		Set<ID> dailyIDSet = new Set<ID>();
		Set<ID> studentIDs = new Set<ID>();
		Map<String, Daily_Meal_Summary__c> dailyMap = new Map<String, Daily_Meal_Summary__c>();
		List<Daily_Meal_Summary__c> newDailyList = new List<Daily_Meal_Summary__c>();
		Map<String, Date> sumDateMap = new Map<String, Date>();
		List<Meal_Transaction__c> updateMealList = new List<Meal_Transaction__c>();
		
		
		for(Meal_Transaction__c mt: mtList){
			if(mt.Transaction_Type__c == 'Sale'){
				dailyKeySet.add((String) schoolID + mt.Transaction_Date__c.format('MM/dd/yyy'));
				sumDateMap.put((String) schoolID + mt.Transaction_Date__c.format('MM/dd/yyy'),mt.Transaction_Date__c.date());
				studentIDs.add(mt.Student__c);
			}
		}
		for(Daily_Meal_Summary__c dms:[select ID, Key__c, Name from Daily_Meal_Summary__c where Key__c IN :dailyKeySet]){
			dailyMap.put(dms.Key__c, dms);
			dailyIDSet.add(dms.Id);
		}
		
		if(!isDeleted){
			
			for(String s:dailyKeySet){
				if(!dailyMap.keyset().contains(s)){
					newDailyList.add(new Daily_Meal_Summary__c(School__c=schoolID, Key__c=s, Summary_Date__c = sumDateMap.get(s)));
				}
			}
			if(newDailyList.size()>0){
				insert newDailyList;
			}
			
			for(Daily_Meal_Summary__c dms:newDailyList){
				dailyMap.put(dms.Key__c, dms);
				dailyIDSet.add(dms.Id);
			}
			for(Meal_Transaction__c mt:mtList){
				if(mt.Daily_Meal_Summary__c==null&&mt.Transaction_Type__c == 'Sale'){
					updateMealList.add(new Meal_Transaction__c(Id=mt.Id, Daily_Meal_Summary__c = dailyMap.get((String) schoolID + mt.Transaction_Date__c.format('MM/dd/yyy')).Id));
				}
			}
			try{
				core_triggerUtils.recursiveHelper(true);
				update updateMealList;
				core_triggerUtils.recursiveHelper(false);
			}
			catch(exception e){
				system.debug('#### An error occurred while updating the link from Meal Transaction to Daily Meal Summary');
			}
		}
		
		rollupDMSTotals(dailyIDSet, mealSetup);

		if(!studentIDs.isEmpty()){
			Map<Id, Student__c> students = new Map<ID, Student__c>([select id, Setup__c from Student__C where ID IN: studentIDs]);
			rollupStats(students);
		}		
	}
	
	public static void rollupStats(Map<ID,Student__c> studMap){
		Map<ID,Meals_Setup__c> mealsSetupMap = new Map<ID, Meals_Setup__c>();
		Map<ID,Double> totalMap = new Map<ID, Double>();
		Map<ID,Double> freeReducedMap = new Map<ID, Double>();
		Set<ID> schoolIDSet = new Set<ID>();
		for(ID sid:studMap.keyset()){
			schoolIDSet.add(studMap.get(sid).Setup__c);
		}
		for(Meals_Setup__c ms : [Select Id, Setup__r.School__c, of_Students_Receiving_Free_Meals__c, of_Students_Receiving_Reduced_Meals__c, of_Students_Receiving_Full_Price_Meals__c, Students_Eligible_for_Free_Reduced__c From Meals_Setup__c where Setup__c IN :schoolIDSet AND Active__c = true]){
			mealsSetupMap.put(ms.Setup__r.School__c, ms);
			totalMap.put(ms.Setup__r.School__c,0);
			freeReducedMap.put(ms.Setup__r.School__c,0);
			mealsSetupMap.get(ms.Setup__r.School__c).of_Students_Receiving_Free_Meals__c = 0;
			mealsSetupMap.get(ms.Setup__r.School__c).of_Students_Receiving_Reduced_Meals__c = 0;
			mealsSetupMap.get(ms.Setup__r.School__c).of_Students_Receiving_Full_Price_Meals__c = 0;
		}
		
		AggregateResult[] groupedResults = 
            [
            SELECT School__c s, Meals_Category__c m,
            count(ID) cnt
            FROM Student__c 
            WHERE School__c IN :mealsSetupMap.keyset()
            AND School__c != null 
            AND Active__c = true
            GROUP BY School__c, Meals_Category__c];
			
		
		for (AggregateResult ar : groupedResults)  { 
			Meals_Setup__c msTemp = new Meals_Setup__c();
			msTemp = mealsSetupMap.get((ID)ar.get('s'));
			Integer arCount = (Integer)ar.get('cnt');
			double tempTotal = totalMap.get((ID)ar.get('s'));
			double tempFreeTotal = freeReducedMap.get((ID)ar.get('s'));
			
			if((ID)ar.get('s')==null){}
			else{
				if((String)ar.get('m')=='Free'){
					msTemp.of_Students_Receiving_Free_Meals__c = arCount;
					tempTotal += arCount;
					tempFreeTotal += arCount;
				}
				else if((String)ar.get('m')=='Reduced'){
					msTemp.of_Students_Receiving_Reduced_Meals__c = arCount;
					tempTotal += arCount;
					tempFreeTotal += arCount;
				}
				else if((String)ar.get('m')=='Full-Priced'){
					msTemp.of_Students_Receiving_Full_Price_Meals__c = arCount;
					tempTotal += arCount;
				}
				else if((String)ar.get('m')==null){
					tempTotal += arCount;
				}
			}
			totalMap.put((ID)ar.get('s'),tempTotal);
			freeReducedMap.put((ID)ar.get('s'),tempFreeTotal);
		}
		
		for(ID sid:mealsSetupMap.keyset()){
			if(totalMap.get(sid)==0){
				//?
			}
			else{
				mealsSetupMap.get(sid).Students_Eligible_for_Free_Reduced__c = (freeReducedMap.get(sid)/totalMap.get(sid))*100;
			}
			
		}
		
		try{
			update mealsSetupMap.values();
		}
		catch(exception e){
			system.debug('##### Error while updating MealSetup object.'+e);
		}
		
	}
	
	public static void rollupDMSTotals(Set<ID> dailyIDSet, Meals_Setup__c mealsetup){
		
		Map<ID,Daily_Meal_Summary__c> updateDailyMap = new Map<ID,Daily_Meal_Summary__c>();
		Map<ID,Double> nonScanMap = new Map<ID,Double>();
		
		for(ID dailyid : dailyIDSet){
			nonScanMap.put(dailyid,0);
		}
		
		for(Daily_Meal_Summary__c dms:[Select Id, Non_Scan_Reimbursable_Breakfasts__c from Daily_Meal_Summary__c where Id IN :nonScanMap.keyset()]){
				nonScanMap.put(dms.Id, dms.Non_Scan_Reimbursable_Breakfasts__c);
		}
		
		AggregateResult[] groupedResults = 
                [
                SELECT Daily_Meal_Summary__c d, 
                sum(Transaction_Amount__c) ta
                FROM Meal_Transaction__c 
                WHERE Daily_Meal_Summary__c IN :dailyIDSet
                AND Transaction_Type__c = 'Sale'
                AND Void__c = false
                GROUP BY Daily_Meal_Summary__c];		
				
			for (AggregateResult ar : groupedResults)  {								
				updateDailyMap.put((ID)ar.get('d'),new Daily_Meal_Summary__c(Id = (ID)ar.get('d'), Total_Monies_Received__c = (Decimal)ar.get('ta'), Total_Free_Breakfasts__c = 0,
				Total_Reduced_Breakfasts__c = 0,
				Total_Full_Price_Breakfasts__c = 0,
				Total_Free_Lunches__c = 0,
				Total_Reduced_Lunches__c = 0,
				Total_Full_Price_Lunches__c = 0,
				Total_Federal_Reimbursement__c = 0,
				Total_State_Local_Reimbursement__c = 0));
			}
			
			
			AggregateResult[] groupedResults2 = 
                [
                SELECT Daily_Meal_Summary__c d, Meal_Type__c m, Cost_Type__c c,
                count(Name) cnt
                FROM Meal_Transaction__c 
                WHERE Daily_Meal_Summary__c IN :dailyIDSet
                AND Transaction_Type__c = 'Sale'
                AND Void__c = false
                GROUP BY ROLLUP(Daily_Meal_Summary__c, Meal_Type__c, Cost_Type__c)];
				
			
			for (AggregateResult ar : groupedResults2)  {	
				Daily_Meal_Summary__c tempDMS = new Daily_Meal_Summary__c();
				tempDMS = updateDailyMap.get((ID)ar.get('d'));
				Integer arCount = (Integer)ar.get('cnt');
											
				if((String)ar.get('m')=='Breakfast'){
					if((String)ar.get('c')=='Free'){
						tempDMS.Total_Free_Breakfasts__c = arCount;
					}
					if((String)ar.get('c')=='Reduced'){
						tempDMS.Total_Reduced_Breakfasts__c = arCount;
					}
					if((String)ar.get('c')=='Full-Priced'){
						tempDMS.Total_Full_Price_Breakfasts__c = arCount;
					}					
				}
				else if((String)ar.get('m')=='Lunch'){
					if((String)ar.get('c')=='Free'){
						tempDMS.Total_Free_Lunches__c = arCount;
					}
					if((String)ar.get('c')=='Reduced'){
						tempDMS.Total_Reduced_Lunches__c = arCount;
					}
					if((String)ar.get('c')=='Full-Priced'){
						tempDMS.Total_Full_Price_Lunches__c = arCount;
					}					
				}
			}
			
			for(ID dmsID: updateDailyMap.keyset()){
				Double fedamt = 0;
				Double stateamt = 0;
				Daily_Meal_Summary__c tempDMS = updateDailyMap.get(dmsID);
				fedamt = (tempDMS.Total_Reduced_Lunches__c * mealSetup.Fed_Reduced_Lunch_Reimbursement__c) + 
						 (tempDMS.Total_Free_Lunches__c * mealSetup.Fed_Free_Lunch_Reimbursement__c) + 
						 (tempDMS.Total_Full_Price_Lunches__c * mealSetup.Fed_Full_Price_Lunch_Reimbursement__c) +
						 (tempDMS.Total_Reduced_Breakfasts__c * mealSetup.Fed_Reduced_Breakfast_Reimbursement__c) +
						 (tempDMS.Total_Free_Breakfasts__c * mealSetup.Fed_Free_Breakfast_Reimbursement__c) +
						 (tempDMS.Total_Full_Price_Breakfasts__c * mealSetup.Fed_Full_Price_Breakfast_Reimbursement__c) +
						 (nonScanMap.get(dmsID) * mealSetup.Fed_Free_Breakfast_Reimbursement__c);
						 
				Double temptotalLunch = tempDMS.Total_Reduced_Lunches__c + tempDMS.Total_Free_Lunches__c + tempDMS.Total_Full_Price_Lunches__c;
				Double temptotalBreakfast = tempDMS.Total_Reduced_Breakfasts__c + tempDMS.Total_Free_Breakfasts__c + tempDMS.Total_Full_Price_Breakfasts__c + nonScanMap.get(dmsID);
				Double additional1total = 0;
				Double additional2total = 0;
				Double additional3total = 0;
				
				if(mealSetup.Additional_Reimbursement_1_Applies_To__c=='Lunch'||mealSetup.Additional_Reimbursement_1_Applies_To__c=='Both'){
					additional1total += temptotalLunch*mealSetup.Additional_Reimbursement_1_Amount__c;
				}
				if(mealSetup.Additional_Reimbursement_1_Applies_To__c=='Breakfast'||mealSetup.Additional_Reimbursement_1_Applies_To__c=='Both'){
					additional1total += temptotalBreakfast*mealSetup.Additional_Reimbursement_1_Amount__c;
				}
				if(mealSetup.Additional_Reimbursement_2_Applies_To__c=='Lunch'||mealSetup.Additional_Reimbursement_2_Applies_To__c=='Both'){
					additional2total += temptotalLunch*mealSetup.Additional_Reimbursement_2_Amount__c;
				}
				if(mealSetup.Additional_Reimbursement_2_Applies_To__c=='Breakfast'||mealSetup.Additional_Reimbursement_2_Applies_To__c=='Both'){
					additional2total += temptotalBreakfast*mealSetup.Additional_Reimbursement_2_Amount__c;
				}
				if(mealSetup.Additional_Reimbursement_3_Applies_To__c=='Lunch'||mealSetup.Additional_Reimbursement_3_Applies_To__c=='Both'){
					additional3total += temptotalLunch*mealSetup.Additional_Reimbursement_3_Amount__c;
				}
				if(mealSetup.Additional_Reimbursement_3_Applies_To__c=='Breakfast'||mealSetup.Additional_Reimbursement_3_Applies_To__c=='Both'){
					additional3total += temptotalBreakfast*mealSetup.Additional_Reimbursement_3_Amount__c;
				}
				
				stateamt = (tempDMS.Total_Reduced_Lunches__c * mealSetup.State_Reduced_Lunch_Reimbursement__c) + 
						   (tempDMS.Total_Free_Lunches__c * mealSetup.State_Free_Lunch_Reimbursement__c) + 
						   (tempDMS.Total_Full_Price_Lunches__c * mealSetup.State_Full_Price_Lunch_Reimbursement__c) +
						   (tempDMS.Total_Reduced_Breakfasts__c * mealSetup.State_Reduced_Breakfast_Reimbursement__c) +
						   (tempDMS.Total_Free_Breakfasts__c * mealSetup.State_Free_Breakfast_Reimbursement__c) +
						   (tempDMS.Total_Full_Price_Breakfasts__c * mealSetup.State_Full_Price_Breakfast_Reimbursement__c) +
						   (nonScanMap.get(dmsID) * mealSetup.State_Free_Breakfast_Reimbursement__c) +
						   (additional1total + additional2total + additional3total);
				
				tempDMS.Total_Federal_Reimbursement__c = fedamt;
				tempDMS.Total_State_Local_Reimbursement__c = stateamt;   
			}
			
			if(groupedResults.size()==0){
				Double additional = 0;
				if(mealSetup.Additional_Reimbursement_1_Applies_To__c=='Breakfast'||mealSetup.Additional_Reimbursement_1_Applies_To__c=='Both'){
					additional += mealSetup.Additional_Reimbursement_1_Amount__c;
				}
				if(mealSetup.Additional_Reimbursement_2_Applies_To__c=='Breakfast'||mealSetup.Additional_Reimbursement_2_Applies_To__c=='Both'){
					additional += mealSetup.Additional_Reimbursement_2_Amount__c;
				}
				if(mealSetup.Additional_Reimbursement_3_Applies_To__c=='Breakfast'||mealSetup.Additional_Reimbursement_3_Applies_To__c=='Both'){
					additional += mealSetup.Additional_Reimbursement_3_Amount__c;
				}
				Double fedamt = mealSetup.Fed_Free_Breakfast_Reimbursement__c;
				Double stateamt = mealSetup.State_Free_Breakfast_Reimbursement__c + additional;
			
				for(ID dailyid : nonScanMap.keyset()){
					updateDailyMap.put(dailyid,new Daily_Meal_Summary__c(Id = dailyid, Total_Monies_Received__c = 0, Total_Free_Breakfasts__c = 0,
					Total_Reduced_Breakfasts__c = 0,
					Total_Full_Price_Breakfasts__c = 0,
					Total_Free_Lunches__c = 0,
					Total_Reduced_Lunches__c = 0,
					Total_Full_Price_Lunches__c = 0,
					Total_Federal_Reimbursement__c = fedamt * nonScanMap.get(dailyid),
					Total_State_Local_Reimbursement__c = stateamt * nonScanMap.get(dailyid)));
				}
			}
			
			try{
				update updateDailyMap.values();
			}
			catch(exception e){
				system.debug('##### Error updating the Daily Meal Summary records.');
			}
	}
	
	
}