objects/Data_Load_Log__c.object
<CustomObject>
    <description>Logs information about data loads such as status and success/failure statistics.</description>
    <fields>
        <fullName>Batch_ID__c</fullName>
        <description>This is the id of the batch that the Data Load Log was created for</description>
        <label>Batch ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Class_Name__c</fullName>
        <label>Class Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>End_Time_Text__c</fullName>
        <description>text representation of the end time field</description>
        <label>End Time Text</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>End_Time__c</fullName>
        <description>Date/time this load finished processing.</description>
        <label>End Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Failed_Records__c</fullName>
        <description>Number of failed records.</description>
        <label>Failed Records</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Messages__c</fullName>
        <description>Any messages generated during the load.</description>
        <label>Messages</label>
        <length>32000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Setup__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>the setup object whose publish created this data load log</description>
        <label>Setup</label>
        <referenceTo>Setup__c</referenceTo>
        <relationshipLabel>Data Load Log</relationshipLabel>
        <relationshipName>Data_Load_Log</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Start_Time_Text__c</fullName>
        <description>text representation of the start time field</description>
        <label>Start Time Text</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Start_Time__c</fullName>
        <description>Date/time this load was started.</description>
        <label>Start Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Status of this data load.</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Pending</fullName>
                </value>
                <value>
                    <fullName>Running</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Total_Records__c</fullName>
        <description>Total number of records processed.</description>
        <label>Total Records</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <description>Type of data loaded.</description>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Section</fullName>
                </value>
                <value>
                    <fullName>Session</fullName>
                </value>
                <value>
                    <fullName>Staff</fullName>
                </value>
                <value>
                    <fullName>Staff/Section</fullName>
                </value>
                <value>
                    <fullName>Student</fullName>
                </value>
                <value>
                    <fullName>Student/Section</fullName>
                </value>
                <value>
                    <fullName>Interventions Data Deactivation</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Data Load Log</label>
    <nameField>
        <displayFormat>DLL-{0000000}</displayFormat>
        <label>Data Load Log #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Data Load Log</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/EOY_Progress__c.object
<CustomObject>
    <description>This object is used to determine the current completion progress in the EOY Wizard.</description>
    <fields>
        <fullName>School_Next_Year_Students_Completed__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Schools will create the next year student records here.</description>
        <inlineHelpText>This will be checked when the net new student records are generated for the next year.</inlineHelpText>
        <label>School Next Year Students Completed</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>School_Next_Year_Students_Last_Modified__c</fullName>
        <description>To keep track of the individual who last modified, the time, and the date.</description>
        <inlineHelpText>Last user to modify and the time.</inlineHelpText>
        <label>School Next Year Students Last Modified</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>School__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field is required to keep track of the EOY progression for a school.</description>
        <inlineHelpText>This field is required for EOY Progression on schools.</inlineHelpText>
        <label>School</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>EOY Progresses</relationshipLabel>
        <relationshipName>EOY_Progresses</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Setup__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Look up to the setup record, since a setup represents an active configuration for a school.</description>
        <inlineHelpText>Determine the progress for an active setup to a school.</inlineHelpText>
        <label>Setup</label>
        <referenceTo>Setup__c</referenceTo>
        <relationshipLabel>EOY Progresses</relationshipLabel>
        <relationshipName>EOY_Progresses</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Year__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>The year that the EOY Wizard process is for.</description>
        <inlineHelpText>The year for the EOY Wizard to process.</inlineHelpText>
        <label>Year</label>
        <referenceTo>Time_Element__c</referenceTo>
        <relationshipLabel>EOY Progresses</relationshipLabel>
        <relationshipName>EOY_Progresses</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>EOY Progress</label>
    <nameField>
        <label>EOY Save State Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>EOY Progresses</pluralLabel>
    <recordTypes>
        <fullName>EOY</fullName>
        <active>true</active>
        <label>EOY</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Grade__c.object
<CustomObject>
    <fields>
        <fullName>Student__c</fullName>
        <label>Student</label>
        <referenceTo>Student__c</referenceTo>
        <relationshipLabel>Grades</relationshipLabel>
        <relationshipName>Grades</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Grade</label>
    <nameField>
        <displayFormat>G-{0}</displayFormat>
        <label>Grade Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Grades</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Setup__c.object
<CustomObject>
    <description>This object is used to setup Schoolforce and is referenced in multiple pieces of code.  There should be one setup object per school.</description>
    <fields>
        <fullName>School__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>School</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1 OR 2</booleanFilter>
            <filterItems>
                <field>Account.RecordType.Name</field>
                <operation>equals</operation>
                <value>School</value>
            </filterItems>
            <filterItems>
                <field>Account.RecordType.Name</field>
                <operation>equals</operation>
                <value>Summer School</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Setup</relationshipLabel>
        <relationshipName>Setup</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Students_Created__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Students Created</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Term__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Term refers to the Term &apos;Template&apos; that the administrator associates to the School; this contains all Semeser/Quarter/Period logic necessary to create Sessions.</description>
        <label>Term</label>
        <referenceTo>Time_Element__c</referenceTo>
        <relationshipLabel>Setup</relationshipLabel>
        <relationshipName>Setup</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Year__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>School Year associated to the Setup</description>
        <label>Year</label>
        <referenceTo>Time_Element__c</referenceTo>
        <relationshipLabel>Setup (Year)</relationshipLabel>
        <relationshipName>Setup_Year</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Setup</label>
    <nameField>
        <displayFormat>S-{0}</displayFormat>
        <label>Setup ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Setup</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/Student__c.object
<CustomObject>
    <fields>
        <fullName>School__c</fullName>
        <inlineHelpText>Displays the name of the student&apos;s current SchoolForce school. You can click on the link to see the details of this school.</inlineHelpText>
        <label>School</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Students</relationshipLabel>
        <relationshipName>Students</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Setup__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Displays the Setup record associated to this Student record. The Setup record defines the settings for the school in a specific school year.</inlineHelpText>
        <label>Setup</label>
        <referenceTo>Setup__c</referenceTo>
        <relationshipLabel>Students</relationshipLabel>
        <relationshipName>Students</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Student_Id__c</fullName>
        <inlineHelpText>Displays the student&apos;s ID. This field displays on report cards, progress reports, and transcripts. It must be unique; SchoolForce uses this ID to link the Student record with the correct Contact record.</inlineHelpText>
        <label>Student Id</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Student__c</fullName>
        <inlineHelpText>Displays the student&apos;s middle name.</inlineHelpText>
        <label>Student Middle Name</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <label>Student</label>
    <nameField>
        <label>Student Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Students</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Time_Element__c.object
<CustomObject>
    <fields>
        <fullName>End_Time__c</fullName>
        <description>This is the time that the time element ends.</description>
        <label>End Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Name__c</fullName>
        <label>Name</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>School__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>School</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Time</relationshipLabel>
        <relationshipName>Time</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Start_Time__c</fullName>
        <description>This is the time that this time element begins.</description>
        <label>Start Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Year</fullName>
                </value>
                <value>
                    <fullName>Semester</fullName>
                </value>
                <value>
                    <fullName>Trimester</fullName>
                </value>
                <value>
                    <fullName>Quarter</fullName>
                </value>
                <value>
                    <fullName>Period</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Time</label>
    <nameField>
        <displayFormat>T-{000000}</displayFormat>
        <label>Time Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Time</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/EOYWiz_SchoolNextYearStudents.cls
public with sharing class EOYWiz_SchoolNextYearStudents {
	public EOY_Progress__c schoolProgress {get; set;}
	public ID EOYrecordType {get; set;}

	//passed in parameters
	private String EOYID {get; set;}
	private String activeYear {get; set;}
	private String nextYear {get; set;}

	public List<thousandLimitWrapper> thousandBlocks {get; set;}
	private final Integer listLimit = 999;
	public List<Data_Load_Log__c> dataLogs {get; set;}

	public ID batchID {get; set;}
	public ID logID {get; set;}
	public Boolean batchComplete {get; set;}

	private Boolean initializationError {get; set;}

	public EOYWiz_SchoolNextYearStudents() {
		schoolProgress = new EOY_Progress__c();
		activeYear = apexPages.currentPage().getParameters().get('activeYear');
		nextYear = apexPages.currentPage().getParameters().get('nextYear');
		EOYID = apexPages.currentPage().getParameters().get('selectedProgress');

		dataLogs = new List<Data_Load_Log__c>();

		batchComplete = true;
		initializationError = false;

		EOYrecordType = core_SoqlUtils.getRecordTypesBySobject('EOY_Progress__c').get('EOY');

		initialize();
	}

	private void initialize(){
		//load EOY Progress
		getSchoolProgress();
		//populate student list
		getNextYearStudents();
		//load data logs and display status messages
		getDataLogs();
	}

	public pageReference gotoSchoolStudentPromotional() {
		pageReference p = new pageReference('/apex/EOYWiz_SchoolStudentPromotional');
		p.getParameters().put('selectedProgress', EOYID);
		p.getParameters().put('activeYear', activeYear);
		p.getParameters().put('nextYear', nextYear);
		p.setRedirect(true);
		return p;
	}

	public pageReference gotoSchoolSnapshots() {
		pageReference p = new pageReference('/apex/EOYWiz_SchoolSnapshots');
		p.getParameters().put('selectedProgress', EOYID);
		p.getParameters().put('activeYear', activeYear);
		p.getParameters().put('nextYear', nextYear);
		p.setRedirect(true);
		return p;
	}

	public void setLastModified() {
		String timeZone = UserInfo.getTimeZone().getID();
		String userName = UserInfo.getFirstName()+' '+ UserInfo.getLastName();
		schoolProgress.School_Next_Year_Students_Last_Modified__c = userName+' '+dateTime.now().format('MM/dd/yyyy hh:mm:ss a', timeZone);

		try{
			upsert schoolProgress;
		} catch(Exception e){
			Error_Handling.errorMessage('Failed to updated last modified date:'+e);
		}
		
	}

	private void getSchoolProgress() {
		if(!initializationError) {
			if(EOYID != null) {
				system.debug('eoyID: ' + EOYID);
				try{
					schoolProgress = [SELECT ID, School_Next_Year_Students_Completed__c, School_Next_Year_Students_Last_Modified__c, School__c, School__r.Name, Setup__c, Setup__r.Students_Created__c, Year__c FROM EOY_Progress__c WHERE ID =: EOYID AND RecordTypeID =: EOYrecordType];
				} catch(System.QueryException e){
					initializationError = true;
					Error_Handling.errorMessage('The system was unable to find a EOY Progress record for your school for the current year. Please start from the EOY home page.');
				}
			} else {
				initializationError = true;
				Error_Handling.errorMessage('Error: There was a problem with initialization. Please start from the EOY home page.');
			}
		}
	}

	public void getNextYearStudents() {
		getThousandBlocks();
	}

	public void getDataLogs(){
		List<Data_Load_Log__c> logs = new List<Data_Load_Log__c>();
		dataLogs = new List<Data_Load_Log__c>();
		try{
			logs = [select id, Type__c, Total_Records__c, Status__c, Start_Time__c, Start_Time_Text__c,
							Setup__c, Setup__r.School__c, Setup__r.School__r.Name, Messages__c, Failed_Records__c,
							End_Time__c, End_Time_Text__c, Class_Name__c, LastModifiedDate, Batch_ID__c
						from Data_Load_Log__c
						WHERE Class_Name__c ='Batch_CreateStudents'
						AND Setup__c =: schoolProgress.Setup__c
						ORDER BY createdDate DESC];
		} catch (System.DMLException e){
			Error_Handling.errorMessage('Failed to get logs from last run.');
		}

		//assume the batch is not running until the logs say otherwise.
		batchComplete = true;
		if(logs.isEmpty()){
			Error_Handling.warningMessage('Please create students for next year here.');
			return;
		}

		//we're only keeping the logs from the last run, so we want the last created batch id.
		if(batchId == null){
			batchID = logs[0].Batch_ID__c;
		}

		boolean hasErrors = false;
		for(Data_Load_Log__c d : logs) {
			if(d.Batch_ID__c != batchID){
				continue;
			} else {
				if(d.Status__c != 'Completed' && d.Status__c != 'Failed'){
					Error_Handling.infoMessage('The batch is still running');
					batchComplete = false;
				} else if (d.Status__c == 'Failed' && !hasErrors){
					hasErrors = true;
					batchComplete = d.End_Time__c != null;
					Error_Handling.errorMessage('One or more of the batches below have failed. Please review the messages in the table below for assistance in resolving the failure. You will not be able to continue until this error is resolved.');
				}
				dataLogs.add(d);
				break;
			}
		}

		if(batchComplete){
			if(!hasErrors)
				Error_Handling.infoMessage('The batch is complete.');
			getSchoolProgress();
			getNextYearStudents();
		}
	}

	public void processNextYearStudent() {
		try{
			Batch_CreateStudents batch = new Batch_CreateStudents(null, (String)schoolProgress.Setup__c, nextYear);
			batchID = Database.executeBatch(batch);
		} catch(Error_Handling.schoolForceException e){
			Error_Handling.errorMessage('The grade span field for your current setup has not been defined. Please define a grade span before continuing.');
			return;
		} catch(Exception e){
			Error_Handling.errorMessage('An error occured while trying to start the batch.');
			return;
		}
		setLastModified();
		batchComplete = false;
		Error_Handling.infoMessage('Started batch job.');
	}

	public class thousandLimitWrapper {
		public Student__c [] students {get; set;}
		public integer blockNumber {get; set;}

		public thousandLimitWrapper (Student__c [] sl, Integer i) {
			students = sl;
			blockNumber = i;
		}
	}

	public thousandLimitWrapper[] getThousandBlocks() {
		thousandBLocks = new thousandLimitWrapper[] {};

		integer counter = 0;
		integer loopcount = 0;
		Student__c[] local = new Student__c[] {};

		Set<String> studentIDs = new Set<String>();
		for(Student__c s : [SELECT ID, Student_ID__c, School_Year__c FROM Student__c WHERE Setup__c =: schoolProgress.Setup__c]) {
			studentIDs.add(s.Student_ID__c);
		}

		for(List<Student__c> ls : [SELECT ID, Student_ID__c, Name, School_Year__c, School_Year__r.Name__c, School__c, Grade__c FROM Student__c WHERE School_Year__c =: nextYear AND Student_ID__c IN: studentIDs]) {
			for(Student__c s : ls) {
				if(counter < listLimit) {
					local.add(s);
					counter++;
				}
				else {
					loopCount++;
					local.add(s);
					thousandBlocks.add(new thousandLimitWrapper(local, loopCount));
					local = new Student__c []{};
					counter = 0;
				}
			}
		}

		loopCount++;
		thousandBlocks.add(new thousandLimitWrapper(local, loopCount));

		return thousandBlocks;
	}
}