objects/Data_Load_Log__c.object
<CustomObject>
    <description>Logs information about data loads such as status and success/failure statistics.</description>
    <fields>
        <fullName>Setup__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>the setup object whose publish created this data load log</description>
        <label>Setup</label>
        <referenceTo>Setup__c</referenceTo>
        <relationshipLabel>Data Load Log</relationshipLabel>
        <relationshipName>Data_Load_Log</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <description>Type of data loaded.</description>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Section</fullName>
                </value>
                <value>
                    <fullName>Session</fullName>
                </value>
                <value>
                    <fullName>Staff</fullName>
                </value>
                <value>
                    <fullName>Staff/Section</fullName>
                </value>
                <value>
                    <fullName>Student</fullName>
                </value>
                <value>
                    <fullName>Student/Section</fullName>
                </value>
                <value>
                    <fullName>Interventions Data Deactivation</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Data Load Log</label>
    <nameField>
        <displayFormat>DLL-{0000000}</displayFormat>
        <label>Data Load Log #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Data Load Log</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/EOY_Progress__c.object
<CustomObject>
    <description>This object is used to determine the current completion progress in the EOY Wizard.</description>
    <fields>
        <fullName>Is_Complete__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Complete</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Module_Name__c</fullName>
        <label>Module Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>School__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field is required to keep track of the EOY progression for a school.</description>
        <inlineHelpText>This field is required for EOY Progression on schools.</inlineHelpText>
        <label>School</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>EOY Progresses</relationshipLabel>
        <relationshipName>EOY_Progresses</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Setup__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Look up to the setup record, since a setup represents an active configuration for a school.</description>
        <inlineHelpText>Determine the progress for an active setup to a school.</inlineHelpText>
        <label>Setup</label>
        <referenceTo>Setup__c</referenceTo>
        <relationshipLabel>EOY Progresses</relationshipLabel>
        <relationshipName>EOY_Progresses</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Year__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>The year that the EOY Wizard process is for.</description>
        <inlineHelpText>The year for the EOY Wizard to process.</inlineHelpText>
        <label>Year</label>
        <referenceTo>Time_Element__c</referenceTo>
        <relationshipLabel>EOY Progresses</relationshipLabel>
        <relationshipName>EOY_Progresses</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>EOY Progress</label>
    <nameField>
        <label>EOY Save State Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>EOY Progresses</pluralLabel>
    <recordTypes>
        <fullName>EOY</fullName>
        <active>true</active>
        <label>EOY</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Picklist_Value__c.object
<CustomObject>
    <fields>
        <fullName>Setup__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Setup</label>
        <referenceTo>Setup__c</referenceTo>
        <relationshipLabel>Picklist Values</relationshipLabel>
        <relationshipName>Picklist_Values</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Picklist Value</label>
    <nameField>
        <label>Display Value</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Picklist Values</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Section__c.object
<CustomObject>
    <fields>
        <fullName>End_Date__c</fullName>
        <inlineHelpText>When does the Intervention Section end?</inlineHelpText>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>School__c</fullName>
        <label>School</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Sections</relationshipLabel>
        <relationshipName>Sections</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Section__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Recursive lookup for groups</description>
        <label>Section</label>
        <referenceTo>Section__c</referenceTo>
        <relationshipLabel>Groups in Section</relationshipLabel>
        <relationshipName>Sections1</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Section</label>
    <nameField>
        <label>Section Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sections</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Setup__c.object
<CustomObject>
    <description>This object is used to setup Schoolforce and is referenced in multiple pieces of code.  There should be one setup object per school.</description>
    <fields>
        <fullName>School__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>School</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1 OR 2</booleanFilter>
            <filterItems>
                <field>Account.RecordType.Name</field>
                <operation>equals</operation>
                <value>School</value>
            </filterItems>
            <filterItems>
                <field>Account.RecordType.Name</field>
                <operation>equals</operation>
                <value>Summer School</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Setup</relationshipLabel>
        <relationshipName>Setup</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Year__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>School Year associated to the Setup</description>
        <label>Year</label>
        <referenceTo>Time_Element__c</referenceTo>
        <relationshipLabel>Setup (Year)</relationshipLabel>
        <relationshipName>Setup_Year</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Setup</label>
    <nameField>
        <displayFormat>S-{0}</displayFormat>
        <label>Setup ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Setup</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/Staff_Section__c.object
<CustomObject>
    <fields>
        <fullName>School__c</fullName>
        <formula>Section__r.School__r.Id</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>The School related to this Section</inlineHelpText>
        <label>School</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Section__c</fullName>
        <label>Section</label>
        <referenceTo>Section__c</referenceTo>
        <relationshipLabel>Staff</relationshipLabel>
        <relationshipName>Staff_Section</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Staff/Section</label>
    <nameField>
        <displayFormat>SfS-{000000}</displayFormat>
        <label>Staff/Section ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Staff/Section</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Student__c.object
<CustomObject>
    <fields>
        <fullName>School__c</fullName>
        <inlineHelpText>Displays the name of the student&apos;s current SchoolForce school. You can click on the link to see the details of this school.</inlineHelpText>
        <label>School</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Students</relationshipLabel>
        <relationshipName>Students</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Section__c</fullName>
        <inlineHelpText>Displays the student&apos;s current homeroom name or room number. This field can be used for reporting purposes.</inlineHelpText>
        <label>Current Homeroom</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Setup__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Displays the Setup record associated to this Student record. The Setup record defines the settings for the school in a specific school year.</inlineHelpText>
        <label>Setup</label>
        <referenceTo>Setup__c</referenceTo>
        <relationshipLabel>Students</relationshipLabel>
        <relationshipName>Students</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Student__c</fullName>
        <inlineHelpText>Displays the student&apos;s middle name.</inlineHelpText>
        <label>Student Middle Name</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <label>Student</label>
    <nameField>
        <label>Student Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Students</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Student_Section__c.object
<CustomObject>
    <fields>
        <fullName>School__c</fullName>
        <formula>Student__r.School__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>School</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Section__c</fullName>
        <label>Section</label>
        <referenceTo>Section__c</referenceTo>
        <relationshipLabel>Student</relationshipLabel>
        <relationshipName>Student_Section</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Student__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Student</label>
        <referenceTo>Student__c</referenceTo>
        <relationshipLabel>Section</relationshipLabel>
        <relationshipName>Student_Section</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Student/Section</label>
    <nameField>
        <displayFormat>SS-{000000}</displayFormat>
        <label>Student/Section ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Student/Section</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Time_Element__c.object
<CustomObject>
    <fields>
        <fullName>Date_Start_Date__c</fullName>
        <defaultValue>Today()</defaultValue>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>End_Date__c</fullName>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Name__c</fullName>
        <label>Name</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Picklist_Value__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Picklist Value</label>
        <referenceTo>Picklist_Value__c</referenceTo>
        <relationshipLabel>Time</relationshipLabel>
        <relationshipName>Time</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>School__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>School</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Time</relationshipLabel>
        <relationshipName>Time</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Time</label>
    <nameField>
        <displayFormat>T-{000000}</displayFormat>
        <label>Time Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Time</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/User.object
<CustomObject>
    <fields>
        <fullName>School__c</fullName>
        <label>School</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

classes/SchoolSetup_ActivateData.cls
/*
	This class is the controller for the Activate Data step in the School Setup - Core Setup wizard.
	  Its main function is to run the Batch_ProcessEOYData batch to activate data (Students, Sections, Staff/Sections,
	 Student/Sections) and to set the current setup to Active.
	
	@author Elizabeth Ellis <eellis@acumensolutions.com>
	@since	2013-04-10
*/
public class SchoolSetup_ActivateData {
	public Setup__c schoolSetup			{get;set;} //the current setup
	public BatchWrapper batch			{get;set;} //the wrapper that contains the running batch's data
	public boolean bDisable				{get;set;} //boolean indicating whether or not to disable the button
	public boolean bProcessing			{get;set;} //boolean indicating that a batch is currently processing
	public List<Data_Load_Log__c> logs	{get;set;} //list of logs populated from previous run of activation, if applicable
	
	/*
		Constructor
		Checks to see if a setupId was passed to the page.  If not, error message.
		Populates the global schoolSetup variable using the passed in setupId.
		Using the global schoolSetup, finds the most recent previous year (End Date < this year's Start Date, ordered by Start Date desc).
		This is passed to check if there is a setup for the previous school year and, if so, that it has completed the EOY process.
		If EOY is not complete, error.
		Else check to see if the setup has already had its data activated.  If so, get the data logs to display.
		Otherwise, warning message to activate data.
	*/
	public SchoolSetup_ActivateData(){
		bProcessing = false;
		bDisable = false;
		if(System.currentPageReference().getParameters().containsKey('setupid')){
			Id setupId = System.currentPageReference().getParameters().get('setupid');
			if(setupId!=null){
				schoolSetup = SetupWizard_Utils.getSetupById(setupId);
				Time_Element__c prevYear;
				try{
					prevYear = [SELECT id, Name__c FROM Time_Element__c WHERE Picklist_Value__r.Name='Year' AND End_Date__c < :schoolSetup.Year__r.Date_Start_Date__c ORDER BY Date_Start_Date__c desc limit 1];
				} catch(QueryException qe){
					prevYear = null;
				}
				if(prevEOYComplete(prevYear)){
					if(!SetupWizard_Utils.checkActivation(schoolSetup)){
						SetupWizard_Utils.addMessage(apexpages.severity.CONFIRM,'Your data has been activated.  No further action is required.');
						getLogs();
					}
					else{
						SetupWizard_Utils.addMessage(apexpages.severity.WARNING,'School data must be activated before the setup process can be completed.');
					}
				}
				else{
					bDisable = true;
					SetupWizard_Utils.addMessage(apexpages.severity.ERROR,'Your school has not completed the EOY process for the '+prevYear.Name__c+' school year.  Please complete this process before activating your data.');
				}
			}
			else SetupWizard_Utils.addMessage(apexpages.severity.ERROR,SetupWizard_Utils.NO_SETUP_MESSAGE);
		}
		else SetupWizard_Utils.addMessage(apexpages.severity.ERROR,SetupWizard_Utils.NO_SETUP_MESSAGE);
	}
	
	/*
		If a year was found, checks to see if there is a setup for the same school (schoolSetup.School__c) for the previous year.
		If a setup was found, checks to see if the EOY process is complete.
		If either a year or a setup is not found, returns true.

		For summer school we check the completion of the main year.
		
		@param prevYear the most recent previous year element in the org
		@return boolean to determine whether or not the previous year's EOY process is complete
	*/
	public boolean prevEOYComplete(Time_Element__c prevYear){
		if(prevYear!=null){
			try{
				EOY_Progress__c eoy = [SELECT id, Is_Complete__c FROM EOY_Progress__c WHERE Year__c=:prevYear.id AND RecordType.Name='EOY' and School__c = null and (Module_Name__c = 'SchoolForce' or Module_Name__c = null)];
				return eoy.Is_Complete__c;
			} catch(QueryException qe){
				//if an EOY progress record doesn't exist, school never went through EOY process
				return false;
			}
		}
		else return true;
	}
	
	/*
		Gets the most recent log of each type (Section__c, Student__c, Staff_Section__c, Student_Section__c) for this setup.
		These are saved to the logs variable for display to the user on the page.
	*/
	public void getLogs(){
		logs = new List<Data_Load_Log__c>();
		Map<String,Data_Load_Log__c> logsByType = new Map<String,Data_Load_Log__c>();
		for(Data_Load_Log__c dll: [SELECT id, Type__c, Start_Time_Text__c, End_Time_Text__c, Total_Records__c, Failed_Records__c, Messages__c, LastModifiedDate FROM Data_Load_Log__c WHERE Setup__c=:schoolSetup.id AND Class_Name__c='Batch_ProcessEOYData']){
			system.debug('~~~~~ log: Type='+dll.Type__c+', LastModifiedDate='+dll.LastModifiedDate);
			if(logsByType.containsKey(dll.Type__c)){
				if(dll.LastModifiedDate > logsByType.get(dll.Type__c).LastModifiedDate)
					logsByType.put(dll.Type__c,dll);
			}
			else logsByType.put(dll.Type__c,dll);
		}
		if(!logsByType.isEmpty()){
			//alphabetize logs by type
			List<String> types = new List<String>();
			types.addAll(logsByType.keySet());
			types.sort();
			for(String s: types){
				logs.add(logsByType.get(s));
			}
		}
	}
	
	/*
	
	*/
	public PageReference continueBatch(){
		try{
			boolean failed = batch.continueBatch();
			if(failed!=null) return SetupWizard_Utils.refreshPage(schoolSetup.id,failed);
		}
		catch(Exception e){
			ApexPages.addMessage(new apexpages.message(apexpages.severity.ERROR, 'There was an error while checking the status of the batch.'));
			createGlobalError('batch check failed',e);
		}
		return null;
	}
	
	/*
	
	*/
	public void processData(){
		try{
			bProcessing = true;
			
			schoolSetup.New_School_Year__c = false;
			schoolSetup.Active__c = true;

			List<Setup__c> setups = [select id, Active__c from Setup__c where School__r.ParentId =: schoolSetup.School__c and Year__c =: schoolSetup.Year__c];
			for(Setup__c s:setups){
				s.New_School_Year__c = false;
				s.Active__c = true;
			}
			setups.add(schoolSetup);
			update setups;
			
			Batch_ProcessEOYData processEOYBatch = new Batch_ProcessEOYData('Student__c');  
			processEOYBatch.setupId = schoolSetup.id;
			processEOYBatch.bFlag = true;
			processEOYBatch.continueBatch = true;
			
			Id batchId = Database.executeBatch(processEOYBatch,10);
			batch = new BatchWrapper(batchId,schoolSetup.id);
			batch.needsStudents = true;
			//This method validates whether the batch has to be invoked again for another school or another mode(Student or Section)
			continueBatch();
		}
		catch(Exception e){
			ApexPages.addMessage(new apexpages.message(apexpages.severity.ERROR, 'A processing error has occurred'));
			createGlobalError('error during activating new year data', e);
		}
	}
	
	/*
	
	*/
	public PageReference prev(){
		return SetupWizard_Utils.goToSchoolStep(SetupWizard_Utils.PUBLISH,false,schoolSetup);
	}
	
	/*
	
	*/
	public PageReference next(){
		if(!SetupWizard_Utils.checkActivation(schoolSetup)) return SetupWizard_Utils.goToSchoolHome(schoolSetup.id);
		else{
			SetupWizard_Utils.addMessage(apexpages.severity.WARNING,'School data must be activated before the setup process can be completed.');
			return null;
		}
	}
	
	public void createGlobalError(String message, Exception e){
		String links='';
		if(batch!=null) links+='Batch,'+batch.batchId;
		if(schoolSetup!=null){
			if(links!='') links+=';';
			links+='Setup,'+schoolSetup.id;
		}
		Global_Error__c ge = Error_Handling.handleError(links, 'Activate Data', message, e);
		insert ge;
	}
}