objects/Data_Load_Log__c.object
<CustomObject>
    <description>Logs information about data loads such as status and success/failure statistics.</description>
    <fields>
        <fullName>Batch_ID__c</fullName>
        <description>This is the id of the batch that the Data Load Log was created for</description>
        <label>Batch ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Class_Name__c</fullName>
        <label>Class Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>End_Time_Text__c</fullName>
        <description>text representation of the end time field</description>
        <label>End Time Text</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>End_Time__c</fullName>
        <description>Date/time this load finished processing.</description>
        <label>End Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Failed_Records__c</fullName>
        <description>Number of failed records.</description>
        <label>Failed Records</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Messages__c</fullName>
        <description>Any messages generated during the load.</description>
        <label>Messages</label>
        <length>32000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Setup__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>the setup object whose publish created this data load log</description>
        <label>Setup</label>
        <referenceTo>Setup__c</referenceTo>
        <relationshipLabel>Data Load Log</relationshipLabel>
        <relationshipName>Data_Load_Log</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Start_Time_Text__c</fullName>
        <description>text representation of the start time field</description>
        <label>Start Time Text</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Start_Time__c</fullName>
        <description>Date/time this load was started.</description>
        <label>Start Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Status of this data load.</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Pending</fullName>
                </value>
                <value>
                    <fullName>Running</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Total_Records__c</fullName>
        <description>Total number of records processed.</description>
        <label>Total Records</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <description>Type of data loaded.</description>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Section</fullName>
                </value>
                <value>
                    <fullName>Session</fullName>
                </value>
                <value>
                    <fullName>Staff</fullName>
                </value>
                <value>
                    <fullName>Staff/Section</fullName>
                </value>
                <value>
                    <fullName>Student</fullName>
                </value>
                <value>
                    <fullName>Student/Section</fullName>
                </value>
                <value>
                    <fullName>Interventions Data Deactivation</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Data Load Log</label>
    <nameField>
        <displayFormat>DLL-{0000000}</displayFormat>
        <label>Data Load Log #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Data Load Log</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/EOY_Progress__c.object
<CustomObject>
    <description>This object is used to determine the current completion progress in the EOY Wizard.</description>
    <fields>
        <fullName>School_Purge_EOY_Data_Completed__c</fullName>
        <defaultValue>false</defaultValue>
        <description>School EOY Data purge process.</description>
        <inlineHelpText>This will be checked when the EOY Data has successfully been purged.</inlineHelpText>
        <label>School Purge EOY Data Completed</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>School_Purge_EOY_Data_Last_Modified__c</fullName>
        <description>To keep track of the individual who last modified, the time, and the date.</description>
        <inlineHelpText>Last user to modify and the time.</inlineHelpText>
        <label>School Purge EOY Data Last Modified</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>School__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field is required to keep track of the EOY progression for a school.</description>
        <inlineHelpText>This field is required for EOY Progression on schools.</inlineHelpText>
        <label>School</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>EOY Progresses</relationshipLabel>
        <relationshipName>EOY_Progresses</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Setup__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Look up to the setup record, since a setup represents an active configuration for a school.</description>
        <inlineHelpText>Determine the progress for an active setup to a school.</inlineHelpText>
        <label>Setup</label>
        <referenceTo>Setup__c</referenceTo>
        <relationshipLabel>EOY Progresses</relationshipLabel>
        <relationshipName>EOY_Progresses</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Year__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>The year that the EOY Wizard process is for.</description>
        <inlineHelpText>The year for the EOY Wizard to process.</inlineHelpText>
        <label>Year</label>
        <referenceTo>Time_Element__c</referenceTo>
        <relationshipLabel>EOY Progresses</relationshipLabel>
        <relationshipName>EOY_Progresses</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>EOY Progress</label>
    <nameField>
        <label>EOY Save State Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>EOY Progresses</pluralLabel>
    <recordTypes>
        <fullName>EOY</fullName>
        <active>true</active>
        <label>EOY</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Setup__c.object
<CustomObject>
    <description>This object is used to setup Schoolforce and is referenced in multiple pieces of code.  There should be one setup object per school.</description>
    <fields>
        <fullName>Purged_EOY_Data__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Purged EOY Data</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>School__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>School</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1 OR 2</booleanFilter>
            <filterItems>
                <field>Account.RecordType.Name</field>
                <operation>equals</operation>
                <value>School</value>
            </filterItems>
            <filterItems>
                <field>Account.RecordType.Name</field>
                <operation>equals</operation>
                <value>Summer School</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Setup</relationshipLabel>
        <relationshipName>Setup</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Year__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>School Year associated to the Setup</description>
        <label>Year</label>
        <referenceTo>Time_Element__c</referenceTo>
        <relationshipLabel>Setup (Year)</relationshipLabel>
        <relationshipName>Setup_Year</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Setup</label>
    <nameField>
        <displayFormat>S-{0}</displayFormat>
        <label>Setup ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Setup</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

classes/EOYWiz_SchoolPurgeEOYData.cls
public with sharing class EOYWiz_SchoolPurgeEOYData {
	public EOY_Progress__c schoolProgress {get; set;}
	public ID EOYrecordType {get; set;}

	private String EOYID {get; set;}
	private String activeYear {get; set;}
	private String nextYear {get; set;}

	public ID batchID {get; set;}
	public List<Data_Load_Log__c> dataLogs {get; set;}
	public Set<ID> dataLogIDs {get; set;}

	public Boolean batchComplete {get; set;}
	private Boolean initializationError {get; set;}

	public static String error1 = 'Error! There was a problem with initialzation. Please start from the EOY home page.';

	public EOYWiz_SchoolPurgeEOYData() {
		schoolProgress = new EOY_Progress__c();
		EOYID = '';
		activeYear = apexPages.currentPage().getParameters().get('activeYear');
		nextYear = apexPages.currentPage().getParameters().get('nextYear');

		dataLogs = new List<Data_Load_Log__c>();
		dataLogIDs = new Set<ID>();

		batchComplete = true;
		initializationError = false;

		EOYrecordType = core_SoqlUtils.getRecordTypesBySobject('EOY_Progress__c').get('EOY');

		initialize();
	}

	private void initialize() {
		getSchoolProgress();
		if(!initializationError) {
			getDataLogs();
		}
	}

	public pageReference gotoSchoolProcessData() {
		pageReference p = new PageReference('/apex/EOYWiz_SchoolProcessData');
		p.getParameters().put('selectedProgress', EOYID);
		p.getParameters().put('activeYear', activeYear);
		p.getParameters().put('nextYear', nextYear);
		p.setRedirect(true);
		return p;
	}

	public pageReference gotoSchoolPurgeHistoricalData() {
		pageReference p = new PageReference('/apex/EOYWiz_SchoolPurgeHistoricalData');
		p.getParameters().put('selectedProgress', EOYID);
		p.getParameters().put('activeYear', activeYear);
		p.getParameters().put('nextYear', nextYear);
		p.setRedirect(true);
		return p;
	}

	public void setLastModified() {
		String timeZone = UserInfo.getTimeZone().getID();
		schoolProgress.School_Purge_EOY_Data_Last_Modified__c = UserInfo.getName() + ' ' + dateTime.now().format('MM/dd/yyyy hh:mm:ss a', timeZone);
		try{
			upsert SchoolProgress;
		} catch(Exception e){
			system.debug('Failed to updated last modified date:'+e);
		}
		
	}

	public void purgeEOYData(){
		try{
			Batch_SchoolPurgeEOYData batch = new Batch_SchoolPurgeEOYData((String)schoolProgress.Setup__c, activeYear, null, 0);
			batchID = Database.executeBatch(batch);
		} catch(Exception e){
			insert Error_Handling.handleError('','EOYWiz_SchoolPurgeEOYData','Failed to initialize Batch_SchoolPurgeEOYData', e);
			Error_Handling.errorMessage('An error occured while starting the batch.');
			return;
		}
		

		setLastModified();
		batchComplete = false;
		apexPages.addMessage(new apexPages.Message(apexPages.Severity.INFO, 'Started batch job'));
	}

	private void getSchoolProgress() {
		if(!initializationError) {
			EOYID = apexPages.currentPage().getParameters().get('selectedProgress');
			if(EOYID != null) {
				system.debug('eoyID: ' + EOYID);
				schoolProgress = [SELECT ID, School_Purge_EOY_Data_Completed__c, School_Purge_EOY_Data_Last_Modified__c, School__c, School__r.Name, Setup__c, Year__c, Setup__r.Purged_EOY_Data__c FROM EOY_Progress__c WHERE ID =: EOYID AND RecordTypeID =: EOYrecordType];
			}
			else {
				initializationError = true;
				apexPages.addMessage(new apexPages.message(apexPages.Severity.ERROR, error1));
			}
		}
	}

	public void getDataLogs(){
		List<Data_Load_Log__c> logs;
		try {
			logs = [SELECT ID, Type__c, Total_Records__c, Status__c, Start_Time__c, Start_Time_Text__c, Setup__c, Setup__r.School__c,
							Setup__r.School__r.Name, Messages__c, Failed_Records__c, End_Time__c, End_Time_Text__c, Class_Name__c, LastModifiedDate, Batch_ID__c
						FROM Data_Load_Log__c
						WHERE Class_Name__c = 'Batch_SchoolPurgeEOYData'
						AND Setup__c =: schoolProgress.Setup__c ORDER BY createdDate DESC];
		}catch(Exception e) {
			Error_Handling.errorMessage('Failure retriving data logs: ' + e.getMessage());
			return;
		}

		for(Data_Load_Log__c log:logs){
			system.debug(log);
		}

		batchComplete = true;
		boolean hasErrors = false;
		if(logs.isEmpty()){
			Error_Handling.infoMessage('Please Purge EOY Data here.');
			return;
		}
 
		if(batchID == null){
			batchID = logs[0].Batch_ID__c;
		}
		dataLogs = new List<Data_Load_Log__c>();
		for(Data_Load_Log__c d : logs){
			if(d.Batch_ID__c == batchID){
				dataLogs.add(d);
				if(d.Status__c != 'Completed'){
					if(d.Status__c == 'Failed' && !hasErrors){
						hasErrors = true;
						Error_Handling.errorMessage('One or more of the batches below have failed. Please review the messages in the table below for assistance in resolving the failure.');
					} else if(d.Status__c != 'Failed' && batchComplete){
						batchComplete = false;
						Error_Handling.infoMessage('The batch is still running.');
					}
				}
			} else if(d.Batch_ID__c == null){
				Error_Handling.infoMessage('The batch is still running.');
				batchComplete = false;
			}
		}

		if(batchComplete){
			Error_Handling.infoMessage('The batch is complete.');
			getSchoolProgress();
		}
	}
}