objects/Data_Load_Log__c.object
<CustomObject>
    <description>Logs information about data loads such as status and success/failure statistics.</description>
    <fields>
        <fullName>Class_Name__c</fullName>
        <label>Class Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Data Load Log</label>
    <nameField>
        <displayFormat>DLL-{0000000}</displayFormat>
        <label>Data Load Log #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Data Load Log</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Document_Log__c.object
<CustomObject>
    <fields>
        <fullName>Document_Log__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Document Log</label>
        <referenceTo>Document_Log__c</referenceTo>
        <relationshipLabel>Document Logs</relationshipLabel>
        <relationshipName>Document_Logs</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Document Log</label>
    <nameField>
        <label>Document Batch Log Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Document Logs</pluralLabel>
    <recordTypes>
        <fullName>Batch</fullName>
        <active>true</active>
        <label>Batch</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Global_Error__c.object
<CustomObject>
    <label>Global Error</label>
    <nameField>
        <label>Global Error Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Global Errors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/HoldingObj__c.object
<CustomObject>
    <description>Generic holding object for importing Students/Staff records from a .CSV file.</description>
    <fields>
        <fullName>Class_Name__c</fullName>
        <label>Class Name</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <label>HoldingObj</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>HoldingObjs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/Batch_EOYDataCleanup.cls
global with sharing class Batch_EOYDataCleanup implements Database.Batchable<SObject>, Database.Stateful{
	public Integer mode {get; set;}
	
	public Batch_EOYDataCleanup() {
		mode = 0;
	}
	
	public Batch_EOYDataCleanup(Integer m) {
		mode = m;
	}
	
	global Database.QueryLocator start(Database.BatchableContext ctx){
		try{
			String query = setQuery();
			return Database.getQueryLocator(query);
		} catch(Exception e){
			insert Error_Handling.handleError('','Batch_EOYDataCleanup','Failure starting batch for mode '+mode,e);
		}
		return Database.getQueryLocator('');
	}
	
	global void execute(Database.BatchableContext ctx, List<SObject> scope){
		List<Database.deleteResult> results = database.delete(scope,false);
	}
	
	global void finish(Database.BatchableContext ctx) {
		mode++;
		if(getObjectString(mode) != null){
			try{
				Batch_EOYDataCleanup newBatch = new Batch_EOYDataCleanup(mode);
				Database.executeBatch(newBatch);
			} catch(Exception e){
				insert Error_Handling.handleError('','Batch_EOYDataCleanup','Failure initalizing batch for mode '+mode,e);
			}
		}
	}
	
	private String setQuery() {
		String returnQuery = 'SELECT ID FROM ' + String.escapeSingleQuotes(getObjectString(mode));
		if(mode == 1) { //Data_Load_Log__c
			returnQuery += ' WHERE Class_Name__c = \'Batch_SchoolProcessData\' OR';
			returnQuery += ' Class_Name__c = \'Batch_SchoolPurgeEOYData\' OR';
			returnQuery += ' Class_Name__c = \'Batch_SchoolPurgeHistoricalData\' OR';
			returnQuery += ' Class_Name__c = \'Batch_SchoolSnapshotAttendanceCalc\' OR';
			returnQuery += ' Class_Name__c = \'BatchSnapshot\' OR';
			returnQuery += ' Class_Name__c = \'Batch_CohortSnapshot\' OR';
			returnQuery += ' Class_Name__c = \'Batch_CreateStudents\' ';
		}
		return returnQuery;
	}

	private String getObjectString(Integer i) {
		if(i == 0) return 'Global_Error__c';
		else if(i == 1) return 'Data_Load_Log__c';
		else if(i == 2) return 'HoldingObj__c';
		else if(i == 3) return 'Document_Log__c';
		else {
			return null;
		}
	}
}