objects/Data_Load_Log__c.object
<CustomObject>
    <description>Logs information about data loads such as status and success/failure statistics.</description>
    <fields>
        <fullName>Batch_ID__c</fullName>
        <description>This is the id of the batch that the Data Load Log was created for</description>
        <label>Batch ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Class_Name__c</fullName>
        <label>Class Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>End_Time_Text__c</fullName>
        <description>text representation of the end time field</description>
        <label>End Time Text</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>End_Time__c</fullName>
        <description>Date/time this load finished processing.</description>
        <label>End Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Failed_Records__c</fullName>
        <description>Number of failed records.</description>
        <label>Failed Records</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Messages__c</fullName>
        <description>Any messages generated during the load.</description>
        <label>Messages</label>
        <length>32000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Setup__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>the setup object whose publish created this data load log</description>
        <label>Setup</label>
        <referenceTo>Setup__c</referenceTo>
        <relationshipLabel>Data Load Log</relationshipLabel>
        <relationshipName>Data_Load_Log</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Start_Time_Text__c</fullName>
        <description>text representation of the start time field</description>
        <label>Start Time Text</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Start_Time__c</fullName>
        <description>Date/time this load was started.</description>
        <label>Start Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Status of this data load.</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Pending</fullName>
                </value>
                <value>
                    <fullName>Running</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Total_Records__c</fullName>
        <description>Total number of records processed.</description>
        <label>Total Records</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <description>Type of data loaded.</description>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Section</fullName>
                </value>
                <value>
                    <fullName>Session</fullName>
                </value>
                <value>
                    <fullName>Staff</fullName>
                </value>
                <value>
                    <fullName>Staff/Section</fullName>
                </value>
                <value>
                    <fullName>Student</fullName>
                </value>
                <value>
                    <fullName>Student/Section</fullName>
                </value>
                <value>
                    <fullName>Interventions Data Deactivation</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Data Load Log</label>
    <nameField>
        <displayFormat>DLL-{0000000}</displayFormat>
        <label>Data Load Log #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Data Load Log</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Section__c.object
<CustomObject>
    <fields>
        <fullName>School__c</fullName>
        <label>School</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Sections</relationshipLabel>
        <relationshipName>Sections</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Section__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Recursive lookup for groups</description>
        <label>Section</label>
        <referenceTo>Section__c</referenceTo>
        <relationshipLabel>Groups in Section</relationshipLabel>
        <relationshipName>Sections1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <description>Section or Standard Group or Custom Group</description>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Section</fullName>
                </value>
                <value>
                    <fullName>Standard Group</fullName>
                </value>
                <value>
                    <fullName>Custom Group</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Section</label>
    <nameField>
        <label>Section Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sections</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Setup__c.object
<CustomObject>
    <description>This object is used to setup Schoolforce and is referenced in multiple pieces of code.  There should be one setup object per school.</description>
    <fields>
        <fullName>School__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>School</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1 OR 2</booleanFilter>
            <filterItems>
                <field>Account.RecordType.Name</field>
                <operation>equals</operation>
                <value>School</value>
            </filterItems>
            <filterItems>
                <field>Account.RecordType.Name</field>
                <operation>equals</operation>
                <value>Summer School</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Setup</relationshipLabel>
        <relationshipName>Setup</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Year__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>School Year associated to the Setup</description>
        <label>Year</label>
        <referenceTo>Time_Element__c</referenceTo>
        <relationshipLabel>Setup (Year)</relationshipLabel>
        <relationshipName>Setup_Year</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Setup</label>
    <nameField>
        <displayFormat>S-{0}</displayFormat>
        <label>Setup ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Setup</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/Staff_Section__c.object
<CustomObject>
    <fields>
        <fullName>School__c</fullName>
        <formula>Section__r.School__r.Id</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>The School related to this Section</inlineHelpText>
        <label>School</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Section__c</fullName>
        <label>Section</label>
        <referenceTo>Section__c</referenceTo>
        <relationshipLabel>Staff</relationshipLabel>
        <relationshipName>Staff_Section</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Staff/Section</label>
    <nameField>
        <displayFormat>SfS-{000000}</displayFormat>
        <label>Staff/Section ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Staff/Section</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Student__c.object
<CustomObject>
    <fields>
        <fullName>School__c</fullName>
        <inlineHelpText>Displays the name of the student&apos;s current SchoolForce school. You can click on the link to see the details of this school.</inlineHelpText>
        <label>School</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Students</relationshipLabel>
        <relationshipName>Students</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Section__c</fullName>
        <inlineHelpText>Displays the student&apos;s current homeroom name or room number. This field can be used for reporting purposes.</inlineHelpText>
        <label>Current Homeroom</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Setup__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Displays the Setup record associated to this Student record. The Setup record defines the settings for the school in a specific school year.</inlineHelpText>
        <label>Setup</label>
        <referenceTo>Setup__c</referenceTo>
        <relationshipLabel>Students</relationshipLabel>
        <relationshipName>Students</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Student__c</fullName>
        <inlineHelpText>Displays the student&apos;s middle name.</inlineHelpText>
        <label>Student Middle Name</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <label>Student</label>
    <nameField>
        <label>Student Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Students</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Student_Section__c.object
<CustomObject>
    <fields>
        <fullName>School__c</fullName>
        <formula>Student__r.School__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>School</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Section__c</fullName>
        <label>Section</label>
        <referenceTo>Section__c</referenceTo>
        <relationshipLabel>Student</relationshipLabel>
        <relationshipName>Student_Section</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Student__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Student</label>
        <referenceTo>Student__c</referenceTo>
        <relationshipLabel>Section</relationshipLabel>
        <relationshipName>Student_Section</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Student/Section</label>
    <nameField>
        <displayFormat>SS-{000000}</displayFormat>
        <label>Student/Section ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Student/Section</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/BatchProcessor.cls
/**
 * Created by Torubka Taras on 11/11/2019.
 */

public virtual class BatchProcessor{
    protected Map<String, Data_Load_Log__c> log;
    protected Map<Id, Id> mapSchool2Setup;
    protected Map<Id, CT_core_SetupWrapper> setups;
    protected Set<Id> setupIds;
    protected String fldSetActive;
    protected String logClassName;
    public String className;
    public Boolean bFlag;
    protected final Map<String, String> mapSOBJECT2SCHOOL = new Map<String, String>{
            'Student__c'=>'School__c',
            'Section__c'=>'School__c',
            'Student_Section__c'=>'Section__r.School__c',
            'Staff_Section__c'=>'School__c'
    };

    public BatchProcessor(){}

    public virtual void init(Set<Id> setupIds, String logClassName){this.setupIds = setupIds; this.logClassName=logClassName;}
    public virtual void process(List<SObject> scope){}
    public virtual String processQuery(Set<String> currYears, Set<Id> schoolIds){return '';}
    public virtual Boolean execLogic(){return true;}

    public String startProcess(Id jobId){
        setups = new Map<Id, CT_core_SetupWrapper>();
        mapSchool2Setup = new Map<Id, Id>();
        Set<String> years = new Set<String>();

        List<Setup__c> lstSetups = CT_core_SoqlUtils.getSetupByIds(setupIds);
        for(Setup__c s: lstSetups){
            setups.put(s.Id, new CT_core_SetupWrapper(s, ''));
            mapSchool2Setup.put(s.School__c, s.Id);
            years.add(s.Year__c);
        }

        String query = processQuery(years, mapSchool2Setup.keySet());
        System.debug('@@@ query ='+query);

        execLogic();
        logsStart(jobId);

        return query;
    }

    protected void logsInit(List<String> objs, Set<Id> setupIds){
        log = new Map<String, Data_Load_Log__c>();

        for(String obj: objs){
            for(Id idx: setupIds) {
                log.put(idx + '#' + obj, new Data_Load_Log__c(Setup__c = idx, Type__c = obj, Status__c = 'Pending', Class_Name__c = logClassName));
            }
        }

        insert log.values();
    }

    public void logsFinish(){
        for (Data_Load_Log__c d : log.values()) {
            d.Status__c = 'Completed';
            d.End_Time__c = System.now();
            d.End_Time_Text__c = d.End_Time__c.format('MM/dd/yyyy hh:mm a');
        }
        update log.values();
    }

    protected void logsStart(Id jobId){
        for (Data_Load_Log__c d : log.values()) {
//				d.Setup__c = cSetup.setup.id;
            d.Batch_ID__c = jobId;//ctx.getJobId();
            d.Status__c = 'Running';
            d.Total_Records__c = 0;
            d.Failed_Records__c = 0;
            d.Start_Time__c = System.now();
            d.Start_Time_Text__c = d.Start_Time__c.format('MM/dd/yyyy hh:mm a');
        }
        update log.values();
    }

    protected void processErrors(List<SObject> records, List<Database.SaveResult> results) {
        System.assertEquals(records.size(), results.size(), 'Records and results arrays must of equal size');
        String sobjName = String.valueOf(records[0].getSObjectType());
        sobjName = sobjName.contains('SchoolForce')? sobjName.replace('SchoolForce__', ''): sobjName;
        String fldSchool = mapSOBJECT2SCHOOL.containsKey(sobjName)? mapSOBJECT2SCHOOL.get(sobjName): '';
        Map<Id, Setup__c> mapUpdateSetups = new Map<Id, Setup__c>();

        for (Integer i = 0; i < results.size(); i++) {
            String setupId = (String)mapSchool2Setup.get((String)getFieldValue(records[i], fldSchool));
            String key = setupId + '#' + sobjName;
            Data_Load_Log__c clog = log.get(key);
            clog.Total_Records__c += 1;//records.size();
            if (!results[i].isSuccess()) {
                clog.Failed_Records__c++;
                for (Database.Error err : results[i].getErrors()) {
                    if (clog.Messages__c != '' && clog.Messages__c != null)
                        clog.Messages__c += '\n';
                    clog.Messages__c += results[i].getId() + ' - ' + err.getMessage();
                }

                if(String.isNotBlank(fldSetActive) && setups.containsKey(setupId)){
                    System.debug('@@@ fldSetActive false: '+setupId);
                    Setup__c s = setups.get(setupId).setup;
                    s.put(fldSetActive, false);
                    mapUpdateSetups.put(s.Id, s);
                }
            }
        }

        update log.values();
        if(!mapUpdateSetups.isEmpty()){
            update mapUpdateSetups.values();
        }
    }

    protected Object getFieldValue(SObject o, String fld){
        if(o==null && String.isBlank(fld)){ return null;}
        if(fld.contains('.')){
            String nextField = fld.substringAfter('.');
            String relation = fld.substringBefore('.');
            return getFieldValue((SObject)o.getSObject(relation),nextField);
        }else{
            return o.get(fld);
        }
    }
}