objects/Data_Load_Log__c.object
<CustomObject>
    <description>Logs information about data loads such as status and success/failure statistics.</description>
    <fields>
        <fullName>Batch_ID__c</fullName>
        <description>This is the id of the batch that the Data Load Log was created for</description>
        <label>Batch ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>End_Time__c</fullName>
        <description>Date/time this load finished processing.</description>
        <label>End Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Failed_Records__c</fullName>
        <description>Number of failed records.</description>
        <label>Failed Records</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Processed_Record_Type__c</fullName>
        <label>Processed Record Type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Processed_Records__c</fullName>
        <description>The total number of records processed successfully by this batch.</description>
        <inlineHelpText>The total number of records processed successfully by this batch.</inlineHelpText>
        <label>Processed Records</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Reporting_Period__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>the reporting period that created this data load log</description>
        <label>Reporting Period</label>
        <referenceTo>Time_Element__c</referenceTo>
        <relationshipLabel>Data Load Log</relationshipLabel>
        <relationshipName>Data_Load_Log</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Start_Time__c</fullName>
        <description>Date/time this load was started.</description>
        <label>Start Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Status of this data load.</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Pending</fullName>
                </value>
                <value>
                    <fullName>Running</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Total_Records__c</fullName>
        <description>Total number of records processed.</description>
        <label>Total Records</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <description>Type of data loaded.</description>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Section</fullName>
                </value>
                <value>
                    <fullName>Session</fullName>
                </value>
                <value>
                    <fullName>Staff</fullName>
                </value>
                <value>
                    <fullName>Staff/Section</fullName>
                </value>
                <value>
                    <fullName>Student</fullName>
                </value>
                <value>
                    <fullName>Student/Section</fullName>
                </value>
                <value>
                    <fullName>Interventions Data Deactivation</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Data Load Log</label>
    <nameField>
        <displayFormat>DLL-{0000000}</displayFormat>
        <label>Data Load Log #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Data Load Log</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/EOY_Progress__c.object
<CustomObject>
    <description>This object is used to determine the current completion progress in the EOY Wizard.</description>
    <fields>
        <fullName>Is_Complete__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Complete</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Module_Name__c</fullName>
        <label>Module Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Parent_Progress__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This is the parent progress tracking record for this record.</description>
        <label>Parent Progress</label>
        <referenceTo>EOY_Progress__c</referenceTo>
        <relationshipLabel>EOY Progresses</relationshipLabel>
        <relationshipName>EOY_Progresses</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>School__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field is required to keep track of the EOY progression for a school.</description>
        <inlineHelpText>This field is required for EOY Progression on schools.</inlineHelpText>
        <label>School</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>EOY Progresses</relationshipLabel>
        <relationshipName>EOY_Progresses</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Year__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>The year that the EOY Wizard process is for.</description>
        <inlineHelpText>The year for the EOY Wizard to process.</inlineHelpText>
        <label>Year</label>
        <referenceTo>Time_Element__c</referenceTo>
        <relationshipLabel>EOY Progresses</relationshipLabel>
        <relationshipName>EOY_Progresses</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>EOY Progress</label>
    <nameField>
        <label>EOY Save State Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>EOY Progresses</pluralLabel>
    <recordTypes>
        <fullName>EOY</fullName>
        <active>true</active>
        <label>EOY</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Time_Element__c.object
<CustomObject>
    <fields>
        <fullName>End_Time__c</fullName>
        <description>This is the time that the time element ends.</description>
        <label>End Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Reporting_Period__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Reporting Period?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>School__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>School</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Time</relationshipLabel>
        <relationshipName>Time</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Start_Time__c</fullName>
        <description>This is the time that this time element begins.</description>
        <label>Start Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Year</fullName>
                </value>
                <value>
                    <fullName>Semester</fullName>
                </value>
                <value>
                    <fullName>Trimester</fullName>
                </value>
                <value>
                    <fullName>Quarter</fullName>
                </value>
                <value>
                    <fullName>Period</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Time</label>
    <nameField>
        <displayFormat>T-{000000}</displayFormat>
        <label>Time Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Time</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/User.object
<CustomObject>
    <fields>
        <fullName>School__c</fullName>
        <label>School</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

classes/EOY_InterventionsLanding.cls
public with sharing class EOY_InterventionsLanding {
	public Time_Element__c currentYear {get;set;}
	public List<Data_Load_Log__c> logs {get;set;}
	public Boolean deactivationAvailable			{get;set;}
	public boolean batchRunning						{get;set;}

	public EOY_InterventionsLanding(){
		currentYear = CYUtil.getCurrentYear();
		logs = new List<Data_Load_Log__c>();

		if(currentYear == null){
			CYUtil.errorMessage('Unable to locate the current year record. Please check your setup.');
			deactivationAvailable = false;
		} else {
			checkStatus();
		}
	}

	public void startDeactivation(){
		Data_Load_Log__c log = new Data_Load_Log__c(
			Type__c = 'Interventions Data Deactivation',
			Status__c = 'Pending',
			Failed_Records__c = 0,
			Total_Records__c = 0,
			Processed_Records__c = 0,
			Reporting_Period__c = currentYear.id
		);

		try{
			batchRunning = true;
			checkStatus();
			delete logs;
			insert log;

			checkStatus();
			batchRunning = true;
			deactivationAvailable = false;
		} catch(System.DMLException e){
			CYUtil.errorMessage('An unexpected error occured when trying to create a log for the deactivation process.');
			return;
		}

		Batch_DeactivateData batch = new Batch_DeactivateData(log.id);
		Database.executeBatch(batch);
		ApexPages.getMessages().clear();
		CYUtil.infoMessage('The batch has been started.');
	}

	public void checkStatus(){
		logs = [select id, Status__c, Start_Time__c, End_Time__c, Processed_Record_Type__c,
				Total_Records__c, Processed_Records__c, Failed_Records__c, Batch_ID__c
			from Data_Load_Log__c 
			where Type__c = 'Interventions Data Deactivation' 
			and Reporting_Period__c =: currentYear.id
			order by CreatedDate desc];

		if(logs.isEmpty()){
			deactivationAvailable = true;
			return;
		}

		boolean isComplete = true;
		boolean hasHadErrorMessage = false;
		for(Data_Load_Log__c log:logs){
			if(!log.Status__c.contains('Completed')){
				if(log.Status__c.contains('Failed') && !hasHadErrorMessage){
					hasHadErrorMessage = true;
					CYUtil.errorMessage('One or more of the batches below have failed. Please review the messages in the table below for assistance in resolving the failure.');
				}
				if(!log.Status__c.contains('Failed')){
					isComplete = false;
					batchRunning = true;
					CYUtil.infoMessage('The batch is still running.');
				}
			}
		}

		if(batchRunning == null || isComplete){
			batchRunning = false;
		}

		if(isComplete && !hasHadErrorMessage){
			deactivationAvailable = false;
			finalizeBatch();
		} else if(isComplete && hasHadErrorMessage) {
			deactivationAvailable = true;
		}
	}

	public void finalizeBatch(){
		List<EOY_Progress__c> eoyProgress = [select id, Is_Complete__c from EOY_Progress__c where Module_Name__c='Interventions' and Year__c =:currentYear.id limit 1];
		deactivationAvailable = !eoyProgress[0].Is_Complete__c;
		if(eoyProgress[0].Is_Complete__c){
			CYUtil.successMessage('The EOY process for Interventions has been completed for this year.');
		}
	}

	public void checkForEOYProgress(){
		List<EOY_Progress__c> eoyProgress = [select id, Is_Complete__c from EOY_Progress__c where Module_Name__c='Interventions' and Year__c =:currentYear.id limit 1];

		if(eoyProgress.isEmpty()){
			makeNewEOYProgress();
		}
	}

	private void makeNewEOYProgress(){
		List<EOY_Progress__c> sfEOYProgress = 
				[select id from EOY_Progress__c 
				where School__c = null 
				and Year__c =: currentYear.id 
				and (Module_Name__c = 'Schoolforce' OR Module_Name__c = null)];

		EOY_Progress__c progress = new EOY_Progress__c(
			Module_Name__c = 'Interventions',
			Year__c = currentYear.id,
			Parent_Progress__c = (sfEOYProgress.isEmpty())?null:sfEOYProgress[0].id,
			RecordTypeID = CYUtil.getRecordTypeID('EOY')
		);

		try{
			DMLManager.insertAsUser(new EOY_Progress__c[]{progress});
			deactivationAvailable = true;
		} catch(DMLManager.CRUDException e){
			CYUtil.errorMessage('User lacks permission to create new EOY Progress records.');
		} catch(DMLManager.FLSException e){
			CYUtil.errorMessage('User lacks permission to edit required fields on EOY Progress records');
		} catch(System.DMLException e){
			CYUtil.errorMessage('Unable to create EOY tracking records. Please resolve this issue before continuing.');
			deactivationAvailable = false;
		}
	}
}