objects/Data_Load_Log__c.object
<CustomObject>
    <description>Logs information about data loads such as status and success/failure statistics.</description>
    <fields>
        <fullName>Batch_ID__c</fullName>
        <description>This is the id of the batch that the Data Load Log was created for</description>
        <label>Batch ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Class_Name__c</fullName>
        <label>Class Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Reporting_Period__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>the reporting period that created this data load log</description>
        <label>Reporting Period</label>
        <referenceTo>Time_Element__c</referenceTo>
        <relationshipLabel>Data Load Log</relationshipLabel>
        <relationshipName>Data_Load_Log</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Setup__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>the setup object whose publish created this data load log</description>
        <label>Setup</label>
        <referenceTo>Setup__c</referenceTo>
        <relationshipLabel>Data Load Log</relationshipLabel>
        <relationshipName>Data_Load_Log</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Start_Time__c</fullName>
        <description>Date/time this load was started.</description>
        <label>Start Time</label>
        <type>DateTime</type>
    </fields>
    <label>Data Load Log</label>
    <nameField>
        <displayFormat>DLL-{0000000}</displayFormat>
        <label>Data Load Log #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Data Load Log</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Setup__c.object
<CustomObject>
    <description>This object is used to setup Schoolforce and is referenced in multiple pieces of code.  There should be one setup object per school.</description>
    <label>Setup</label>
    <nameField>
        <displayFormat>S-{0}</displayFormat>
        <label>Setup ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Setup</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

classes/BatchWrapper.cls
/*
	@author Elizabeth Ellis <eellis@acumensolutions.com>
	@since	2013-04-10
*/
public class BatchWrapper {
	public ID batchId				{get;set;}
	public ID rpId					{get;set;}
	public ID setupId				{get;set;}
	public boolean needsStudents	{get;set;}
	public String status			{get;set;}
	public integer processed		{get;set;}
	public integer totalItems		{get;set;}
	
	public BatchWrapper(ID batchId, ID setupId){
		this.batchId = batchId;
		this.setupId = setupId;
	}
	
	/*
		Continue processing an already running batch
	*/
	public boolean continueBatch(){
		system.debug('~~~~~ batchId '+batchId);
		AsyncApexJob batch = [SELECT ID, ApexClassId, Status, TotalJobItems, JobItemsProcessed, CompletedDate FROM AsyncApexJob WHERE id=:batchId];
		status = batch.Status;
		processed = batch.JobItemsProcessed;
		totalItems = batch.TotalJobItems;
		if(status=='Completed'){
			String className = [SELECT Name FROM ApexClass WHERE id=:batch.ApexClassId].Name;
			List<Data_Load_Log__c> dll = [SELECT id, Batch_ID__c, Start_Time__c FROM Data_Load_Log__c WHERE Batch_ID__c=:batch.Id];
			if(className=='Scheduler_HoldingProcessor'){
				checkForLogs('Scheduler_HoldingProcessor',true,dll[0].Start_Time__c);
			}
			else if(className=='Batch_ProcessEOYData'){
				if(needsStudents){
					checkForLogs('Batch_ProcessEOYData',false,dll[0].Start_Time__c);
				}
				else{
					return false;
				}
			}		
			else{
				return false;
			}	
		}
		else if(status=='Failed'){
			return true;
		}
		return null;
	}
	
	/*
		Check for the logs for subsequent batch runs if the completed batch is part of a synchronous batch process.
		These include publishing batches, data activation batches, and some EOY batches.
		
		@param className the name of the next apex class that is supposed to run
		@param useRPs determines whether the logs should be filtered on reporting period
		@param prevBatchEndTime the time when the last batch finished running.  The start time on the next batch should be later than this.
	*/
	public void checkForLogs(String className,boolean useRPs,DateTime prevBatchStartTime){
		List<Data_Load_Log__c> dll;
		if(useRPs)
			dll = [SELECT id, Batch_ID__c FROM Data_Load_Log__c WHERE Setup__c=:setupId AND Reporting_Period__c=:rpId AND Class_Name__c=:className AND Start_Time__c >= :prevBatchStartTime AND Batch_ID__c!=:batchId ORDER BY CreatedDate DESC];
		else
			dll = [SELECT id, Batch_ID__c FROM Data_Load_Log__c WHERE Setup__c=:setupId AND Class_Name__c=:className AND Start_Time__c >= :prevBatchStartTime AND Batch_ID__c!=:batchId ORDER BY CreatedDate DESC];
		system.debug('~~~~~ dll: '+dll);
		if(dll.size()==0){
			setupWaitingMessage();
		}
		else if(dll[0].Batch_ID__c!=null){
			batchId = dll[0].Batch_ID__c;
			needsStudents = false;
			continueBatch();
		}
	}
	
	/*
		Set up the user message if the next batch isn't found.
	*/
	public void setupWaitingMessage(){
		status = 'Waiting for next batch';
		processed = 0;
		totalItems = 0;
	}
}