objects/Document_Log__c.object
<CustomObject>
    <fields>
        <fullName>Staff__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This is a staff lookup for schedule generation logs.</description>
        <label>Staff</label>
        <referenceTo>Staff__c</referenceTo>
        <relationshipLabel>Document Logs</relationshipLabel>
        <relationshipName>Document_Logs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Student__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>The student the document was generated for.</inlineHelpText>
        <label>Student</label>
        <referenceTo>Student__c</referenceTo>
        <relationshipLabel>Document Logs</relationshipLabel>
        <relationshipName>Document_Logs1</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Document Log</label>
    <nameField>
        <label>Document Batch Log Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Document Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Section__c.object
<CustomObject>
    <fields>
        <fullName>End_Date__c</fullName>
        <inlineHelpText>When does the Intervention Section end?</inlineHelpText>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Grade_Level__c</fullName>
        <inlineHelpText>Select the grade level of the course, if desired. SchoolForce uses the All Grades list box to determine the grade level(s) for which the section is available. You can use the Grade Level drop-down list on reports.</inlineHelpText>
        <label>Grade Level</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>PS</fullName>
                </value>
                <value>
                    <fullName>PK</fullName>
                </value>
                <value>
                    <fullName>K</fullName>
                </value>
                <value>
                    <fullName>1</fullName>
                </value>
                <value>
                    <fullName>2</fullName>
                </value>
                <value>
                    <fullName>3</fullName>
                </value>
                <value>
                    <fullName>4</fullName>
                </value>
                <value>
                    <fullName>5</fullName>
                </value>
                <value>
                    <fullName>6</fullName>
                </value>
                <value>
                    <fullName>7</fullName>
                </value>
                <value>
                    <fullName>8</fullName>
                </value>
                <value>
                    <fullName>9</fullName>
                </value>
                <value>
                    <fullName>10</fullName>
                </value>
                <value>
                    <fullName>11</fullName>
                </value>
                <value>
                    <fullName>12</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>School__c</fullName>
        <label>School</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Sections</relationshipLabel>
        <relationshipName>Sections</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Staff__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Staff</label>
        <referenceTo>Staff__c</referenceTo>
        <relationshipLabel>Sections</relationshipLabel>
        <relationshipName>Sections</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Section</label>
    <nameField>
        <label>Section Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sections</pluralLabel>
    <recordTypes>
        <fullName>Published</fullName>
        <active>true</active>
        <description>Sections that have been Published and are Viewable by Standard Users</description>
        <label>Published</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Setup__c.object
<CustomObject>
    <description>This object is used to setup Schoolforce and is referenced in multiple pieces of code.  There should be one setup object per school.</description>
    <fields>
        <fullName>Evaluation_Documents__c</fullName>
        <description>This controls what is allowed to be selected in the document generation page</description>
        <inlineHelpText>Which documents should this setup be using?</inlineHelpText>
        <label>Evaluation Documents</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Report Card - High School</fullName>
                </value>
                <value>
                    <fullName>Report Card - Elementary School</fullName>
                </value>
                <value>
                    <fullName>Progress Report - High School</fullName>
                </value>
                <value>
                    <fullName>Progress Report - Elementary School</fullName>
                </value>
                <value>
                    <fullName>Transcript</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>School__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>School</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1 OR 2</booleanFilter>
            <filterItems>
                <field>Account.RecordType.Name</field>
                <operation>equals</operation>
                <value>School</value>
            </filterItems>
            <filterItems>
                <field>Account.RecordType.Name</field>
                <operation>equals</operation>
                <value>Summer School</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Setup</relationshipLabel>
        <relationshipName>Setup</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Term__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Term refers to the Term &apos;Template&apos; that the administrator associates to the School; this contains all Semeser/Quarter/Period logic necessary to create Sessions.</description>
        <label>Term</label>
        <referenceTo>Time_Element__c</referenceTo>
        <relationshipLabel>Setup</relationshipLabel>
        <relationshipName>Setup</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Setup</label>
    <nameField>
        <displayFormat>S-{0}</displayFormat>
        <label>Setup ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Setup</pluralLabel>
    <recordTypes>
        <fullName>Published</fullName>
        <active>true</active>
        <description>For Published Setups - Not Editable</description>
        <label>Published</label>
    </recordTypes>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/Staff__c.object
<CustomObject>
    <fields>
        <fullName>Organization__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Staff Member&apos;s employer</description>
        <label>Organization</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Staff</relationshipLabel>
        <relationshipName>Staff</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Staff</label>
    <nameField>
        <label>Staff Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Staff</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/Student__c.object
<CustomObject>
    <fields>
        <fullName>School__c</fullName>
        <inlineHelpText>Displays the name of the student&apos;s current SchoolForce school. You can click on the link to see the details of this school.</inlineHelpText>
        <label>School</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Students</relationshipLabel>
        <relationshipName>Students</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Setup__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Displays the Setup record associated to this Student record. The Setup record defines the settings for the school in a specific school year.</inlineHelpText>
        <label>Setup</label>
        <referenceTo>Setup__c</referenceTo>
        <relationshipLabel>Students</relationshipLabel>
        <relationshipName>Students</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Staff__c</fullName>
        <inlineHelpText>Displays the name of the student&apos;s homeroom teacher.  You can use this field for reporting purposes.</inlineHelpText>
        <label>Current Homeroom Teacher</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Student__c</fullName>
        <inlineHelpText>Displays the student&apos;s middle name.</inlineHelpText>
        <label>Student Middle Name</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <label>Student</label>
    <nameField>
        <label>Student Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Students</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Student_Reporting_Period__c.object
<CustomObject>
    <fields>
        <fullName>Student__c</fullName>
        <label>Student</label>
        <referenceTo>Student__c</referenceTo>
        <relationshipLabel>Student Reporting Periods</relationshipLabel>
        <relationshipName>Student_Reporting_Periods</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Student Reporting Period</label>
    <nameField>
        <displayFormat>SRP-{00}</displayFormat>
        <label>Student Reporting Period Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Student Reporting Periods</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Term__c.object
<CustomObject>
    <description>Junction object  between Time and Setup.</description>
    <fields>
        <fullName>Setup__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Setup</label>
        <referenceTo>Setup__c</referenceTo>
        <relationshipLabel>Terms</relationshipLabel>
        <relationshipName>Terms</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Time_Element__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Time Element</label>
        <referenceTo>Time_Element__c</referenceTo>
        <relationshipLabel>Terms</relationshipLabel>
        <relationshipName>Terms</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Term</label>
    <nameField>
        <displayFormat>Term-{000000}</displayFormat>
        <label>Term Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Terms</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Time_Element__c.object
<CustomObject>
    <fields>
        <fullName>Date_Start_Date__c</fullName>
        <defaultValue>Today()</defaultValue>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>End_Date__c</fullName>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Name__c</fullName>
        <label>Name</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>School__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>School</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Time</relationshipLabel>
        <relationshipName>Time</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Time</label>
    <nameField>
        <displayFormat>T-{000000}</displayFormat>
        <label>Time Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Time</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/User.object
<CustomObject>
    <fields>
        <fullName>School__c</fullName>
        <label>School</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

classes/Gradebook_RunReportCardsWrapper.cls
public with sharing class Gradebook_RunReportCardsWrapper {

	public class schoolWrapper{
		public String displayName					{get;set;}
		public Setup__c setup						{get;set;}
		public boolean selected						{get;set;}
		public List<SelectOption> reportingPeriods	{get;set;}
		public string selectedReportingPeriod		{get;set;}
		public string selectedDocument				{get;set;}
		public string selectedTime					{get;set;}
		public string startDate						{get;set;}
		public string endDate						{get;set;}
		public List<SelectOption> allowedDocuments	{get;set;}
		public ID recordID							{get;set;}
		public Student__c searchOptionWrapper		{get;set;}
		public Staff__c staffOptionWrapper			{get;set;}
		public ID SchoolId;
		public boolean bTimeFilter = false;
		//DE3640
		public Boolean bOfficialTranscript			{get;set;}
		
		public List<sectionWrapper> sections		{get;set;}

		public schoolWrapper(Setup__c s, boolean checkDocuments, List<Time_Element__c> rps){
			this.setup = s;
			this.schoolID = s.School__c;
			this.selected = false;
			this.recordID = s.id;
			this.displayName = s.School__r.Name + ' (' + s.Term__r.Name__c + ')';
			//DE3640
			this.bOfficialTranscript = true;
			
			this.searchOptionWrapper = new Student__c(Setup__r = this.setup);
			this.staffOptionWrapper = new Staff__c(Organization__c = this.schoolID);

			selectedReportingPeriod = null;
			this.reportingPeriods = new List<selectOption>();
			for(Time_Element__c rp:rps){
				if(selectedReportingPeriod == null){
					selectedReportingPeriod = rp.id;
					startDate = rp.Date_Start_Date__c.format();
					endDate = rp.End_Date__c.format();
				}
				this.reportingPeriods.add(new selectOption(rp.id,rp.Name__c));
			}
			
			//setup available documents list
			if(checkDocuments){
				this.allowedDocuments = new List<selectOption>();
				for(String docType:s.Evaluation_Documents__c.split(';')){
					this.allowedDocuments.add(new SelectOption(docType,docType));
				}
			}
			//if no documents option, user selected schedule creation
			else {
				this.selectedDocument = 'Schedule';
			}
		}

		public void loadSections(){
			if(sections == null || bTimeFilter){
				sections = new List<sectionWrapper>();
				String query = 'SELECT ID, School__r.Name, Name, Grade_Level__c, All_Grades__c, Section__r.Course__c';
				query += (bTimeFilter)?',(Select id, time__r.name__c, completed__c'+
									' from Section_ReportingPeriod__r'+
									' WHERE Time__c =: selectedReportingPeriod'+
									' and RecordType.DeveloperName = \'Published\' limit 1 )':'';
				query+= ' FROM Section__c'+
						' WHERE Active__c = true'+
						' AND School__c = \''+this.setup.School__c+'\''+
						' AND RecordType.DeveloperName = \'Published\'';

				for(Section__c s:Database.query(query)){
					if(!bTimeFilter || (s.section_reportingPeriod__r!=null && s.section_reportingPeriod__r.size()>0))
						sections.add(new sectionWrapper(s));
				}
			}
		}
	}

	public class sectionWrapper{
		public boolean selected					{get;set;}
		public Section__c section				{get;set;}
		public Section_ReportingPeriod__c srp	{get;set;}

		public sectionWrapper(Section__c s){
			this.section = s;
			this.selected = true;
			if (s.section_reportingPeriod__r!=null && !s.Section_ReportingPeriod__r.isEmpty())
				srp = s.section_reportingPeriod__r[0];
		}
	}

	public class personWrapper{
		public boolean selected		{get;set;}
		public ID attachmentID		{get;set;}
		public Student__c student	{get;set;}
		public Staff__c staff		{get;set;}
		public Document_Log__c log	{get;set;}
		public Student_Reporting_Period__c srp {get;set;}

		public personWrapper(Student__c s){
			this.student = s;
			this.selected = false;
		}
		
		public personWrapper(Staff__c s){
			this.staff = s;
			this.selected = false;
		}
	}

	@isTest static void testWrapper(){
		TestDataSetupUtil_v2.setupCoreData(5);
		TestDataSetupUtil_v2.setupStaffData(5); //sections
		TestDataSetupUtil_v2.setupStudentData(5);

		Test.startTest();
			Gradebook_RunReportCardsWrapper.schoolWrapper school = new Gradebook_RunReportCardsWrapper.schoolWrapper(Gradebook_ReportCard_Utils.getDocumentSchools(false)[0], true,Gradebook_ReportCard_Utils.getReportingPeriods(TestDataSetupUtil_v2.activeSetup.Term__c));
			school.loadSections();
			System.assertEquals(false, school.sections.isEmpty());
			Gradebook_RunReportCardsWrapper.personWrapper student = new Gradebook_RunReportCardsWrapper.personWrapper(TestDataSetupUtil_v2.studentsList[0]);
			System.assertNotEquals(null, student.student);
		Test.stopTest();
	}
}