objects/Enrollment_Tracking__c.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Active?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Exit_Reason__c</fullName>
        <description>Exit reason from Student at time of withdrawl</description>
        <label>Exit Reason</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Student_Section__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Student/Section</label>
        <referenceTo>Student_Section__c</referenceTo>
        <relationshipLabel>Enrollment Tracking</relationshipLabel>
        <relationshipName>Enrollment_Tracking</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Student__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Student</label>
        <referenceTo>Student__c</referenceTo>
        <relationshipLabel>Enrollment Tracking</relationshipLabel>
        <relationshipName>Enrollment_Tracking</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Enrollment Tracking</label>
    <nameField>
        <displayFormat>ET-{0000000}</displayFormat>
        <label>Enrollment Tracking Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Enrollment Tracking</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Schedule_Day__c.object
<CustomObject>
    <fields>
        <fullName>Day__c</fullName>
        <label>Day</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Reporting_Period__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Reporting Period</label>
        <referenceTo>Time_Element__c</referenceTo>
        <relationshipLabel>Schedule Days</relationshipLabel>
        <relationshipName>Schedule_Days</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Schedule_Template__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Schedule Template</label>
        <referenceTo>Schedule_Template__c</referenceTo>
        <relationshipLabel>Schedule Days</relationshipLabel>
        <relationshipName>Schedule_Days</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Schedule Day</label>
    <nameField>
        <label>Schedule Day Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Schedule Days</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Schedule_Template__c.object
<CustomObject>
    <fields>
        <fullName>Has_Class__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Has Class?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Reporting_Period__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Reporting Period</label>
        <referenceTo>Time_Element__c</referenceTo>
        <relationshipLabel>Schedule Templates</relationshipLabel>
        <relationshipName>Schedule_Templates</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Setup__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Setup</label>
        <referenceTo>Setup__c</referenceTo>
        <relationshipLabel>Schedule Templates</relationshipLabel>
        <relationshipName>Schedule_Templates</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Schedule Template</label>
    <nameField>
        <label>Schedule Template Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Schedule Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Section__c.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Check this box if the section is a currently active section</description>
        <inlineHelpText>Check this box if the section is a currently active section</inlineHelpText>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Reporting_Period__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Usually the only reporting period; could be the first if the section spans multiple reporting periods.</description>
        <label>Reporting Period</label>
        <referenceTo>Time_Element__c</referenceTo>
        <relationshipLabel>Sections (First Reporting Period)</relationshipLabel>
        <relationshipName>Sections1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Section__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Recursive lookup for groups</description>
        <label>Section</label>
        <referenceTo>Section__c</referenceTo>
        <relationshipLabel>Groups in Section</relationshipLabel>
        <relationshipName>Sections1</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Section</label>
    <nameField>
        <label>Section Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sections</pluralLabel>
    <recordTypes>
        <fullName>Published</fullName>
        <active>true</active>
        <description>Sections that have been Published and are Viewable by Standard Users</description>
        <label>Published</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Setup__c.object
<CustomObject>
    <description>This object is used to setup Schoolforce and is referenced in multiple pieces of code.  There should be one setup object per school.</description>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Is this school setup active for this school year?</inlineHelpText>
        <label>Active?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Term__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Term refers to the Term &apos;Template&apos; that the administrator associates to the School; this contains all Semeser/Quarter/Period logic necessary to create Sessions.</description>
        <label>Term</label>
        <referenceTo>Time_Element__c</referenceTo>
        <relationshipLabel>Setup</relationshipLabel>
        <relationshipName>Setup</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Setup</label>
    <nameField>
        <displayFormat>S-{0}</displayFormat>
        <label>Setup ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Setup</pluralLabel>
    <recordTypes>
        <fullName>Published</fullName>
        <active>true</active>
        <description>For Published Setups - Not Editable</description>
        <label>Published</label>
    </recordTypes>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/Student__c.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>true</defaultValue>
        <inlineHelpText>Indicates whether or not this Student record is active. If checked, then this is the current Student record. If unchecked, this is an old Student record.</inlineHelpText>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Entry_Date__c</fullName>
        <inlineHelpText>Displays the student&apos;s first day of school in the current school year.</inlineHelpText>
        <label>Entry Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Exit_Date__c</fullName>
        <inlineHelpText>Displays the date the student was withdrawn. SchoolForce updates this field when a student is withdrawn through the Section Wizard.</inlineHelpText>
        <label>Exit Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Exit_Reason__c</fullName>
        <inlineHelpText>Displays the reason the student was withdrawn/exited from the school. SchoolForce updates this field when a student is withdrawn through the Section Wizard.</inlineHelpText>
        <label>Exit Code</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>NI (No Information)</fullName>
                </value>
                <value>
                    <fullName>TSS (Transfer to Silings School)</fullName>
                </value>
                <value>
                    <fullName>DE (Dissatisfaction with Education)</fullName>
                </value>
                <value>
                    <fullName>DS (Dissatisfaction with Staff)</fullName>
                </value>
                <value>
                    <fullName>TSI (Transfer to Special Interest School)</fullName>
                </value>
                <value>
                    <fullName>DL (Dissatisfaction with Location)</fullName>
                </value>
                <value>
                    <fullName>TC (Transfer to Closer School)</fullName>
                </value>
                <value>
                    <fullName>DE (Death)</fullName>
                </value>
                <value>
                    <fullName>EX (Expulsion)</fullName>
                </value>
                <value>
                    <fullName>TO (Transfer Out Of State)</fullName>
                </value>
                <value>
                    <fullName>TS (Transfer in State)</fullName>
                </value>
                <value>
                    <fullName>TSS (Transfer to Siblings School)</fullName>
                </value>
                <value>
                    <fullName>Student is in a different public school in the same local education agency</fullName>
                </value>
                <value>
                    <fullName>Transferred to a public school in a different local education agency in the same state</fullName>
                </value>
                <value>
                    <fullName>Transferred to a public school in a different state</fullName>
                </value>
                <value>
                    <fullName>Transferred to a private, non-religiously-affiliated school in the same local education agency</fullName>
                </value>
                <value>
                    <fullName>Transferred to a private, non-religiously-affiliated school in the same state</fullName>
                </value>
                <value>
                    <fullName>Transferred to a private, non-religiously-affiliated school in a different state</fullName>
                </value>
                <value>
                    <fullName>Transferred to a private, religiously-affiliated school in the same local education agency</fullName>
                </value>
                <value>
                    <fullName>Transferred to a private, religiously-affiliated school in the same state</fullName>
                </value>
                <value>
                    <fullName>Transferred to a private, religiouslyaffiliated school in a different state</fullName>
                </value>
                <value>
                    <fullName>Transferred to an institution</fullName>
                </value>
                <value>
                    <fullName>Transferred to home schooling</fullName>
                </value>
                <value>
                    <fullName>Matriculation to another school</fullName>
                </value>
                <value>
                    <fullName>Graduated with regular, advanced, International Baccalaureate, or other type of diploma</fullName>
                </value>
                <value>
                    <fullName>Completed school with other credentials</fullName>
                </value>
                <value>
                    <fullName>Died or is permanently incapacitated</fullName>
                </value>
                <value>
                    <fullName>Withdrawn due to illness</fullName>
                </value>
                <value>
                    <fullName>Expelled or involuntarily withdrawn</fullName>
                </value>
                <value>
                    <fullName>Reached maximum age for services</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Setup__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Displays the Setup record associated to this Student record. The Setup record defines the settings for the school in a specific school year.</inlineHelpText>
        <label>Setup</label>
        <referenceTo>Setup__c</referenceTo>
        <relationshipLabel>Students</relationshipLabel>
        <relationshipName>Students</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Student__c</fullName>
        <inlineHelpText>Displays the student&apos;s middle name.</inlineHelpText>
        <label>Student Middle Name</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <label>Student</label>
    <nameField>
        <label>Student Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Students</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Student_Section__c.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Student__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Student</label>
        <referenceTo>Student__c</referenceTo>
        <relationshipLabel>Section</relationshipLabel>
        <relationshipName>Student_Section</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Student/Section</label>
    <nameField>
        <displayFormat>SS-{000000}</displayFormat>
        <label>Student/Section ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Student/Section</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Time_Element__c.object
<CustomObject>
    <fields>
        <fullName>Reporting_Period__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Reporting Period?</label>
        <type>Checkbox</type>
    </fields>
    <label>Time</label>
    <nameField>
        <displayFormat>T-{000000}</displayFormat>
        <label>Time Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Time</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/BatchStudentDaysEnrolled.cls
global class BatchStudentDaysEnrolled implements Database.Batchable<sObject> {
	private final  Map <Id, List <Schedule_Day__c>> scheduleDayMap {get;set;}
	private final 	Map <Id, Date> scheduleStartMap {get;set;}
	public  Set <Id> setupIds {get;set;}

	global BatchStudentDaysEnrolled(){
		scheduleDayMap = new Map <Id, List<Schedule_Day__c>>();
		scheduleStartMap = new Map <Id, Date>();
		for (Schedule_Day__c sd:
				[SELECT s.schedule_template__r.reporting_period__c, s.schedule_template__r.setup__c, s.Day__c
				FROM Schedule_Day__c s 
				WHERE s.Schedule_Template__r.Setup__r.Active__c = true 
				AND s.Schedule_Template__r.Has_Class__c = true 
				ORDER BY s.Day__c]){
			if (scheduleDayMap.get(sd.schedule_template__r.setup__c)==null){
				scheduleDayMap.put(sd.schedule_template__r.setup__c, new List <Schedule_Day__c>{sd});
				scheduleStartMap.put(sd.schedule_template__r.setup__c, sd.day__c);
			} else {
				scheduleDayMap.get(sd.schedule_template__r.setup__c).add(sd);
			}
		}
	}


	global Database.QueryLocator start(Database.BatchableContext BC) {
		for (Id setupId: scheduleDayMap.keySet()){
			populateDaysElapsed(scheduleDayMap.get(setupId));
		}
		setupIds = scheduleDayMap.keySet();
		String query = 'SELECT entry_date__c, exit_date__c, exit_reason__c, active__c, Setup__c from Student__c where setup__c in :setupIds';

		return Database.getQueryLocator(query);
	}

	global void execute(Database.BatchableContext BC, List<Student__c> studentList){
		List <Enrollment_Tracking__c> etList = new List <Enrollment_Tracking__c>();
		Set <Id> studentIds								= new Set <Id>();
		List <Student_Section__c>			ssList = new List <Student_Section__c>();
		Map <Id, List <Enrollment_Tracking__c>> etMap;
		for (Student__c student : studentList) {
			etList.add(CT_Student_Utils.processEnrollmentRecords(student, scheduleStartMap.get(student.setup__c)));
			studentIds.add(student.id);
		}

		for (Student_Section__c ss:
				[SELECT id, Student_Section__c.Student__r.entry_date__c, section__r.reporting_period__r.date_start_date__c, 
					enrollment_start_date__c, enrollment_end_date__c, active__c, Section_Exit_Reason__c, Student_Entry_Date__c
				FROM Student_Section__c
				WHERE student__c in :studentIds
				AND 	Section__r.Active__c=true
				AND	Section__r.RecordType.Name = 'Published'])	{
			etList.add(Student_Section_Utils.processEnrollmentRecords_StudentSection(ss, ss.section__r.reporting_period__r.date_start_date__c));
		}

		upsert etList reference_id__c;

		etMap = CT_Student_Utils.getStudentEnrollmentMap(studentIds); //Gets the Enrollment Tracking Data for Students

		for (Student__c student: studentList){
			populateDaysEnrolled(scheduleDayMap.get(student.setup__c), student, System.today(), etMap.get(student.id));
		}

		update studentList;
	}

	global void populateDaysEnrolled(List<Schedule_Day__c> scheduleDayList, Student__c student, Date someDate, List <Enrollment_Tracking__c> etList) {
		Integer counter = 0;
		if (student.entry_date__c==null) student.entry_date__c = scheduleStartMap.get(student.setup__c);
		for (Schedule_Day__c scheduleDay : scheduleDayList) {
			if (scheduleDay.Day__c >= student.Entry_Date__c && scheduleDay.Day__c <= someDate) {
				if (etList==null)	counter++;
				else if (CT_Student_Utils.checkEnrollmentTracking(etList, scheduleDay.Day__c)) counter++;
			}
		}

		student.Days_Enrolled__c = counter;
	}

	global void populateDaysElapsed(List<Schedule_Day__c> scheduleDayList){
		for (Integer i = 0; i < scheduleDayList.size(); i++) {
			scheduleDayList[i].Days_Elapsed__c = (i + 1);
		}
		upsert scheduleDayList;
	}

	global void finish(Database.BatchableContext BC){}
}