objects/EOY_Progress__c.object
<CustomObject>
    <description>This object is used to determine the current completion progress in the EOY Wizard.</description>
    <fields>
        <fullName>Documents_Wizard_Completed__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Documents Wizard Completed</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Documents_Wizard_Started__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Documents Wizard Started</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Setup__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Look up to the setup record, since a setup represents an active configuration for a school.</description>
        <inlineHelpText>Determine the progress for an active setup to a school.</inlineHelpText>
        <label>Setup</label>
        <referenceTo>Setup__c</referenceTo>
        <relationshipLabel>EOY Progresses</relationshipLabel>
        <relationshipName>EOY_Progresses</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>EOY Progress</label>
    <nameField>
        <label>EOY Save State Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>EOY Progresses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Setup__c.object
<CustomObject>
    <description>This object is used to setup Schoolforce and is referenced in multiple pieces of code.  There should be one setup object per school.</description>
    <fields>
        <fullName>Evaluation_Documents__c</fullName>
        <description>This controls what is allowed to be selected in the document generation page</description>
        <inlineHelpText>Which documents should this setup be using?</inlineHelpText>
        <label>Evaluation Documents</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Report Card - High School</fullName>
                </value>
                <value>
                    <fullName>Report Card - Elementary School</fullName>
                </value>
                <value>
                    <fullName>Progress Report - High School</fullName>
                </value>
                <value>
                    <fullName>Progress Report - Elementary School</fullName>
                </value>
                <value>
                    <fullName>Transcript</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Standard_Legend_4_Spanish__c</fullName>
        <inlineHelpText>What is the title that should display in Spanish for a Standard Level 4? (ie: Advanced) This will display on Report Cards and Progress Reports if user selects &quot;Show Standards&quot; on the &quot;Generate Student Documents&quot; page.</inlineHelpText>
        <label>Standard Title 4 Spanish</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <label>Setup</label>
    <nameField>
        <displayFormat>S-{0}</displayFormat>
        <label>Setup ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Setup</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

classes/SchoolSetup_Documents.cls
public with sharing class SchoolSetup_Documents {
	public core_SetupWrapper cSetup	{get;set;}
	public EOY_Progress__c progress	{get;set;}
	private ID setupID;

	public SchoolSetup_Documents() {
		setupID = ApexPages.currentPage().getParameters().get('setupId');
		if(setupID != null){
			cSetup = new core_SetupWrapper(core_SoqlUtils.getSetupById(setupId),null);
			progress = SetupWizard_Utils.getEOYProgressRecord(cSetup.setup);
		}
	}

	/*
		Saves the assoicated setup. 
	*/
	public void save(){
		try{
			update cSetup.setup;
			progress.Documents_Wizard_Started__c = true;
			upsert progress; //upsert incase this is the first module they visit.
			SetupWizard_Utils.addMessage(apexpages.severity.CONFIRM,'Changes saved successfully.');
		} catch(System.DMLException e){
			SetupWizard_Utils.addMessage(apexpages.severity.ERROR,'An error occured while trying to save your changes.');
		}
	}

	/*
		Save the assoicated setup and finalizes the module.
	*/
	public void finalize(){
		if(cSetup.setup.Evaluation_Documents__c == null || cSetup.setup.Evaluation_Documents__c == ''){
			SetupWizard_Utils.addMessage(apexpages.severity.ERROR,'You must select at least one evaluation document before finalizing this module.');
			return;
		}
		progress.Documents_Wizard_Completed__c = true;
		save();
		if(ApexPages.hasMessages(ApexPages.severity.ERROR)){
			progress.Documents_Wizard_Completed__c = false;
		} else {
			SetupWizard_Utils.addMessage(apexpages.severity.CONFIRM,'Your changes have been finalized. You may return here to update settings as needed.');
		}
	}

	/*
		Moves the user to the previous module page
	*/
	public PageReference prev(){
		PageReference p = Page.SchoolSetup_Home;
		p.getParameters().put('setupId',setupID);
		return p;
	}

	@isTest static void test(){
		TestDataSetupUtil_v2.setupCoreData(5);

		PageReference p = Page.SchoolSetup_Documents;
		p.getParameters().put('setupId', TestDataSetupUtil_v2.activeSetup.id);
		Test.setCurrentPage(p);

		Test.startTest();
			SchoolSetup_Documents controller = new SchoolSetup_Documents();
			controller.cSetup.setup.Standard_Legend_4_Spanish__c = 'Something unique';
			controller.save();
			System.assertEquals('Something unique', [select Standard_Legend_4_Spanish__c from Setup__c where ID=:TestDataSetupUtil_v2.activeSetup.id].Standard_Legend_4_Spanish__c);
			controller.finalize();
			controller.prev();
	}
}