objects/EOY_Progress__c.object
<CustomObject>
    <description>This object is used to determine the current completion progress in the EOY Wizard.</description>
    <fields>
        <fullName>School_Selections_Completed__c</fullName>
        <defaultValue>false</defaultValue>
        <description>In the setup wizard, schools must make selections indicating their preferences for the school year.  This field indicates whether these selections have been completed.</description>
        <label>School Selections Completed</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Setup__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Look up to the setup record, since a setup represents an active configuration for a school.</description>
        <inlineHelpText>Determine the progress for an active setup to a school.</inlineHelpText>
        <label>Setup</label>
        <referenceTo>Setup__c</referenceTo>
        <relationshipLabel>EOY Progresses</relationshipLabel>
        <relationshipName>EOY_Progresses</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>EOY Progress</label>
    <nameField>
        <label>EOY Save State Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>EOY Progresses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Global_Error__c.object
<CustomObject>
    <label>Global Error</label>
    <nameField>
        <label>Global Error Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Global Errors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Setup__c.object
<CustomObject>
    <description>This object is used to setup Schoolforce and is referenced in multiple pieces of code.  There should be one setup object per school.</description>
    <label>Setup</label>
    <nameField>
        <displayFormat>S-{0}</displayFormat>
        <label>Setup ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Setup</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

classes/CT_SchoolSetup_Selections.cls
public class CT_SchoolSetup_Selections {
	public Setup__c schoolSetup		{get;set;}
	public boolean settingsSaved	{get;set;}
	
	public CT_SchoolSetup_Selections(){
		if(ApexPages.currentPage().getParameters().containsKey('setupId')){
			Id setupId = ApexPages.currentPage().getParameters().get('setupId');
			if(setupId!=null){
				schoolSetup = CT_SetupWizard_Utils.getSetupById(setupId);
				if(CT_SetupWizard_Utils.checkSelections(schoolSetup)){
					CT_SetupWizard_Utils.addMessage(apexpages.severity.WARNING,'School preferences must be saved before moving on to the next step.');
					settingsSaved = false;
				}
				else{
					CT_SetupWizard_Utils.addMessage(apexpages.severity.CONFIRM,'School selections have been saved.  No action required.');
					settingsSaved = true;
				}
			}
			else CT_SetupWizard_Utils.addMessage(apexpages.severity.ERROR,CT_SetupWizard_Utils.NO_SETUP_MESSAGE);
		}
		else CT_SetupWizard_Utils.addMessage(apexpages.severity.ERROR,CT_SetupWizard_Utils.NO_SETUP_MESSAGE);
	}
	
	/*
		Saves the selections that the user has made for Group/Period based and Room Dependence.
		Also saves the progress record indicating that these selections have been completed (School_Selections_Completed__c).
		If there is an error, a Global Error will be created and an error message thrown to the user 
		('There was an error while saving your selections.  Please have your system administrator verify any global errors.').
	*/
	public void saveSetup(){
		try{
			EOY_Progress__c progress = CT_SetupWizard_Utils.getEOYProgressRecord(schoolSetup);
			update schoolSetup;
			progress.School_Selections_Completed__c=true;
			settingsSaved = true;
			upsert progress;
			CT_SetupWizard_Utils.addMessage(apexpages.severity.CONFIRM,'Selections saved successfully!');
		}
		catch(Exception e){
			CT_SetupWizard_Utils.addMessage(apexpages.severity.ERROR,'There was an error while saving your selections.  Please have your system administrator verify any global errors.');
			String links='';
			if(schoolSetup!=null){
				EOY_Progress__c progress = CT_SetupWizard_Utils.getEOYProgressRecord(schoolSetup);
				links = 'Setup,'+schoolSetup.id+';Progress Record,'+progress.id;
			}
			Global_Error__c ge = CT_Error_Handling.handleError(links,'Setup Wizard','Error saving school selections', e);
			insert ge;
		}
	}
	
	/*
		Redirects the user to the previous step of the setup process, terms and reporting periods.
		
		@return the PageReference for the core_TermSetup_v2 page
	*/
	public PageReference prev(){
		return CT_SetupWizard_Utils.goToSchoolStep(CT_SetupWizard_Utils.TERMS,false,schoolSetup);
	}
	
	/*
		Redirects the user to the next step of the setup process, schedule template configuration.
		
		@return the PageReference for the core_ScheduleTemplate page
	*/
	public PageReference next(){
		if(!CT_SetupWizard_Utils.checkSelections(schoolSetup)) return CT_SetupWizard_Utils.goToSchoolStep(CT_SetupWizard_Utils.TEMPLATES,true,schoolSetup);
		else{
			CT_SetupWizard_Utils.addMessage(apexpages.severity.WARNING,'School preferences must be saved before moving on to the next step.');
			return null;
		}
	}
}