objects/Global_Error__c.object
<CustomObject>
    <label>Global Error</label>
    <nameField>
        <label>Global Error Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Global Errors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Staff__c.object
<CustomObject>
    <fields>
        <fullName>Organization__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Staff Member&apos;s employer</description>
        <label>Organization</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Staff</relationshipLabel>
        <relationshipName>Staff</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Staff</label>
    <nameField>
        <label>Staff Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Staff</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/User.object
<CustomObject>
    <fields>
        <fullName>School__c</fullName>
        <label>School</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

classes/core_ChangeSchoolController.cls
public class core_ChangeSchoolController {
	public List<SelectOption> schoolListChoices    {get;set;}
	public String selectedSchoolID                 {get;set;}
	public User loggedInUser                       {get;set;}

	public core_ChangeSchoolController(){
		loggedInUser = [select id, School__c from User where id =: UserInfo.getUserId()];
		if(String.isNotBlank(loggedInUser.School__c)){
			selectedSchoolID = loggedInUser.School__c;
		}
		schoolListChoices = new List<SelectOption>();
		Contact con = core_SoqlUtils.getLoggedInContact();
		if(con==null){
			schoolListChoices.add(new SelectOption('none', '-None-'));
		} else {
			for(Staff__c s:core_SoqlUtils.getContactStaffList(con.id)){
				if(s.Organization__c!=null){
					schoolListChoices.add(new SelectOption(s.organization__c, s.Organization__r.Name));
				}
			}
		}
	}
	
	public void change(){
		try{
			if(String.isBlank(loggedInUser.School__c)){
				loggedInUser.School__c = schoolListChoices[0].getValue();
				update loggedInUser;
			}else{
				loggedInUser.School__c = selectedSchoolID;
				update loggedInUser;
			}
		}catch(Exception e){
			Global_Error__c ge = Error_Handling.handleError('', 'Other', 'error updating user', e);
			insert ge;
		}
	}
}