objects/Grade__c.object
<CustomObject>
    <fields>
        <fullName>Student__c</fullName>
        <label>Student</label>
        <referenceTo>Student__c</referenceTo>
        <relationshipLabel>Grades</relationshipLabel>
        <relationshipName>Grades</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Grade</label>
    <nameField>
        <displayFormat>G-{0}</displayFormat>
        <label>Grade Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Grades</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Notification__c.object
<CustomObject>
    <description>This object captures notification data which allows administrators to schedule system notifications.</description>
    <fields>
        <fullName>End_Date__c</fullName>
        <description>This is the date that the notification period ends.</description>
        <label>End Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Picklist_Value__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Status</label>
        <referenceTo>Picklist_Value__c</referenceTo>
        <relationshipLabel>Notifications</relationshipLabel>
        <relationshipName>Notifications</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Setup__c</fullName>
        <description>This is a lookup to the setup object that the notifications are for.</description>
        <label>Setup</label>
        <referenceTo>Setup__c</referenceTo>
        <relationshipLabel>Notifications</relationshipLabel>
        <relationshipName>Notifications</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <description>This is the date that the notification period starts.</description>
        <label>Start Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <label>Notification</label>
    <nameField>
        <label>Notification Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Notifications</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Picklist_Value__c.object
<CustomObject>
    <fields>
        <fullName>Category__c</fullName>
        <label>Category</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Type__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Absent</fullName>
                </value>
                <value>
                    <fullName>Reporting Period</fullName>
                </value>
                <value>
                    <fullName>Custom Period</fullName>
                </value>
                <value>
                    <fullName>In School Suspension</fullName>
                </value>
                <value>
                    <fullName>Out of School Suspension</fullName>
                </value>
                <value>
                    <fullName>Present</fullName>
                </value>
                <value>
                    <fullName>Partial</fullName>
                </value>
                <value>
                    <fullName>Tardy</fullName>
                </value>
                <value>
                    <fullName>Excused Absence</fullName>
                </value>
                <value>
                    <fullName>Unexcused Absence</fullName>
                </value>
                <value>
                    <fullName>Excused Tardy</fullName>
                </value>
                <value>
                    <fullName>Unexcused Tardy</fullName>
                </value>
                <value>
                    <fullName>Missing</fullName>
                </value>
                <value>
                    <fullName>Exempt</fullName>
                </value>
                <value>
                    <fullName>Complete</fullName>
                </value>
                <value>
                    <fullName>Late</fullName>
                </value>
                <value>
                    <fullName>Incomplete</fullName>
                </value>
                <value>
                    <fullName>Default</fullName>
                </value>
                <value>
                    <fullName>Standards</fullName>
                </value>
                <value>
                    <fullName>Credit/No Credit</fullName>
                </value>
                <value>
                    <fullName>Points</fullName>
                </value>
                <value>
                    <fullName>0-100</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Setup__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Setup</label>
        <referenceTo>Setup__c</referenceTo>
        <relationshipLabel>Picklist Values</relationshipLabel>
        <relationshipName>Picklist_Values</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Picklist Value</label>
    <nameField>
        <label>Display Value</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Picklist Values</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Points__c.object
<CustomObject>
    <fields>
        <fullName>Category__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Category</label>
        <referenceTo>Picklist_Value__c</referenceTo>
        <relationshipLabel>Points Transactions</relationshipLabel>
        <relationshipName>Points_Transactions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Points_Date__c</fullName>
        <label>Points Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Points__c</fullName>
        <label>Points</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Staff__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Staff</label>
        <referenceTo>Staff__c</referenceTo>
        <relationshipLabel>Points Transactions</relationshipLabel>
        <relationshipName>Points_Transactions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Student__c</fullName>
        <label>Student</label>
        <referenceTo>Student__c</referenceTo>
        <relationshipLabel>Points Transactions</relationshipLabel>
        <relationshipName>Points_Transactions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Points Transaction</label>
    <nameField>
        <displayFormat>PT-{000000}</displayFormat>
        <label>Points Transaction Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Points Transactions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Schedule__c.object
<CustomObject>
    <fields>
        <fullName>Setup__c</fullName>
        <label>Setup</label>
        <referenceTo>Setup__c</referenceTo>
        <relationshipLabel>Points Reset Schedules</relationshipLabel>
        <relationshipName>Schedules</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Schedule</label>
    <nameField>
        <displayFormat>S-{0000}</displayFormat>
        <label>Schedule Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Schedules</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Setup__c.object
<CustomObject>
    <description>This object is used to setup Schoolforce and is referenced in multiple pieces of code.  There should be one setup object per school.</description>
    <fields>
        <fullName>Days__c</fullName>
        <label>Days</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <controllingField>Points_Frequency__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Sun</fullName>
                </value>
                <value>
                    <fullName>Mon</fullName>
                </value>
                <value>
                    <fullName>Tue</fullName>
                </value>
                <value>
                    <fullName>Wed</fullName>
                </value>
                <value>
                    <fullName>Thur</fullName>
                </value>
                <value>
                    <fullName>Fri</fullName>
                </value>
                <value>
                    <fullName>Sat</fullName>
                </value>
                <value>
                    <fullName>1</fullName>
                </value>
                <value>
                    <fullName>2</fullName>
                </value>
                <value>
                    <fullName>3</fullName>
                </value>
                <value>
                    <fullName>4</fullName>
                </value>
                <value>
                    <fullName>5</fullName>
                </value>
                <value>
                    <fullName>6</fullName>
                </value>
                <value>
                    <fullName>7</fullName>
                </value>
                <value>
                    <fullName>8</fullName>
                </value>
                <value>
                    <fullName>9</fullName>
                </value>
                <value>
                    <fullName>10</fullName>
                </value>
                <value>
                    <fullName>11</fullName>
                </value>
                <value>
                    <fullName>12</fullName>
                </value>
                <value>
                    <fullName>13</fullName>
                </value>
                <value>
                    <fullName>14</fullName>
                </value>
                <value>
                    <fullName>15</fullName>
                </value>
                <value>
                    <fullName>16</fullName>
                </value>
                <value>
                    <fullName>17</fullName>
                </value>
                <value>
                    <fullName>18</fullName>
                </value>
                <value>
                    <fullName>19</fullName>
                </value>
                <value>
                    <fullName>20</fullName>
                </value>
                <value>
                    <fullName>21</fullName>
                </value>
                <value>
                    <fullName>22</fullName>
                </value>
                <value>
                    <fullName>23</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Points_Frequency__c</fullName>
        <label>Points Frequency</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Weekly</fullName>
                </value>
                <value>
                    <fullName>Monthly</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Points_Reset_Date__c</fullName>
        <description>This field will be set  by an apex job . This field will be used to determine today&apos;s Current Balance field on student record.</description>
        <label>Points Reset Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Points_Reset_Value__c</fullName>
        <label>Points Reset Value</label>
        <precision>6</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Schedule_End_Date__c</fullName>
        <label>Schedule End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Schedule_Start_Date__c</fullName>
        <label>Schedule Start Date</label>
        <type>Date</type>
    </fields>
    <label>Setup</label>
    <nameField>
        <displayFormat>S-{0}</displayFormat>
        <label>Setup ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Setup</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/Staff__c.object
<CustomObject>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <label>Staff</label>
    <nameField>
        <label>Staff Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Staff</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/Student__c.object
<CustomObject>
    <fields>
        <fullName>Setup__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Displays the Setup record associated to this Student record. The Setup record defines the settings for the school in a specific school year.</inlineHelpText>
        <label>Setup</label>
        <referenceTo>Setup__c</referenceTo>
        <relationshipLabel>Students</relationshipLabel>
        <relationshipName>Students</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Staff__c</fullName>
        <inlineHelpText>Displays the name of the student&apos;s homeroom teacher.  You can use this field for reporting purposes.</inlineHelpText>
        <label>Current Homeroom Teacher</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Student__c</fullName>
        <inlineHelpText>Displays the student&apos;s middle name.</inlineHelpText>
        <label>Student Middle Name</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <label>Student</label>
    <nameField>
        <label>Student Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Students</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/Test_BatchResetPoints.cls
@isTest
private class Test_BatchResetPoints {

     public static void createTestData(){
        
        TestDataSetupUtil_v2.setUPCoreData(3);
        TestDataSetupUtil_v2.setUpStaffData(5);
        TestDataSetupUtil_v2.setUpStudentData(5);
        TestDataSetupUtil_v2.activeSetUp.Schedule_Start_Date__c = TestDataSetupUtil_v2.term.Date_Start_Date__c;
        TestDataSetupUtil_v2.activeSetUp.Schedule_End_Date__c = TestDataSetupUtil_v2.term.End_Date__c;
        TestDataSetupUtil_v2.activeSetUp.Points_Frequency__c = 'Monthly';
        TestDataSetupUtil_v2.activeSetUp.Points_Reset_Value__c = 0;
        TestDataSetupUtil_v2.activeSetUp.Days__c = '1';
        update TestDataSetupUtil_v2.activeSetUp;
       
    }
    
   static testMethod void testCreateWeeklyResetPointsSchedules() {
        createTestData();
        TestDataSetupUtil_v2.activeSetUp.Schedule_Start_Date__c = System.today();
     	TestDataSetupUtil_v2.activeSetUp.Schedule_End_Date__c = System.today().addYears(1); 
     	TestDataSetupUtil_v2.activeSetUp.Points_Frequency__c = 'Weekly';
     	TestDataSetupUtil_v2.activeSetUp.Days__c = 'Sun;Mon;';
     	update TestDataSetupUtil_v2.activeSetUp;
     	Integer scheduledays = [SELECT COUNT() FROM Schedule__c WHERE Setup__c =: TestDataSetupUtil_v2.activeSetUp.Id];
     	System.assertNotEquals(0, scheduledays);
    }
    static testMethod void testCreateMonthlyResetPointsSchedules() {
        createTestData();
        TestDataSetupUtil_v2.activeSetUp.Schedule_Start_Date__c = System.today();
     	TestDataSetupUtil_v2.activeSetUp.Schedule_End_Date__c = System.today().addYears(1); 
     	TestDataSetupUtil_v2.activeSetUp.Points_Frequency__c = 'Monthly';
     	TestDataSetupUtil_v2.activeSetUp.Days__c = '1;2;';
     	update TestDataSetupUtil_v2.activeSetUp;
     	Integer scheduledays = [SELECT COUNT() FROM Schedule__c WHERE Setup__c =: TestDataSetupUtil_v2.activeSetUp.Id];
     	System.assertNotEquals(0, scheduledays);
     	Setup__c setup = [SELECT Points_Reset_Date__c FROM Setup__c WHERE Id =: TestDataSetupUtil_v2.activeSetUp.Id];
     	System.assertNotEquals(null, setup.Points_Reset_Date__c);
    }
    
     static testMethod void testScheduleResetPoints() {
        createTestData();
        List<Picklist_Value__c> cats = testDataSetupUtil_v2.createPointsCats(null);
        string refID = (String)testDataSetupUtil_v2.studentsList[0].id+(String)cats[0].id+String.valueOf(system.today())+'';
        Points__c point = new Points__c(Student__c = testDataSetupUtil_v2.studentsList[0].id
                                        ,Points_Date__c = system.today()
                                        ,Points__c = 35
                                        ,Staff__c = testDataSetupUtil_v2.teachersList[0].id
                                        ,Category__c = cats[0].id
                                        ,Reference_Id__c = refID);
        
        insert point;
        
        Notification__c notification = new Notification__c(Module__c = 'Points'
                                        ,Setup__c = testDataSetupUtil_v2.activeSetUp.id
                                        ,Start_Date__c = system.today().addDays(-7)
                                        ,End_Date__c = system.today().addDays(7)
                                        ,Grade__c = '1;2;3;4;5;6;7;8;9;10;11;12');
        
        insert notification;
        
        Threshold__c thresh = new Threshold__c(Notification__c = notification.id
                                        ,Cumulative__c = 30);
                                        
        insert thresh;
        TestDataSetupUtil_v2.activeSetUp.Schedule_Start_Date__c = System.today();
        TestDataSetupUtil_v2.activeSetUp.Schedule_End_Date__c = System.today().addYears(1); 
        TestDataSetupUtil_v2.activeSetUp.Points_Frequency__c = 'Weekly';
        TestDataSetupUtil_v2.activeSetUp.Days__c = 'Sun;Mon;Tue;Wed;Thur;Fri;Sat';
        update TestDataSetupUtil_v2.activeSetUp;
        //Integer scheduledays = [SELECT COUNT() FROM Schedule__c WHERE Setup__c =: TestDataSetupUtil_v2.activeSetUp.Id];
     
        sched_Points sc = new sched_Points();
        String CRON_EXP = '0 0 13 * * ?';
         Test.startTest(); 
        System.schedule('testCreateWeeklyResetPointsSchedules',CRON_EXP , sc);
         Test.stopTest(); 
     	
    }
    
     static testMethod void testResetPoints() {
        createTestData();
        TestDataSetupUtil_v2.activeSetUp.Schedule_Start_Date__c = System.today();
     	TestDataSetupUtil_v2.activeSetUp.Schedule_End_Date__c = System.today().addYears(1); 
     	TestDataSetupUtil_v2.activeSetUp.Points_Frequency__c = 'Weekly';
     	TestDataSetupUtil_v2.activeSetUp.Days__c = 'Sun;Mon;Tue;Wed;Thur;Fri;Sat';
     	update TestDataSetupUtil_v2.activeSetUp;
     	//Integer scheduledays = [SELECT COUNT() FROM Schedule__c WHERE Setup__c =: TestDataSetupUtil_v2.activeSetUp.Id];
     	 Set<String> setupIds = new Set<String>();
     	 setupIds.add(TestDataSetupUtil_v2.activeSetUp.Id);
     	 Batch_ResetPoints brp = new Batch_ResetPoints ();
		 brp.setupIds = setupIds;
		  System.debug('$$$$$$$BRP'+brp.setupIds);
     	 List<Student__c> studs =[SELECT Id FROM Student__c WHERE Setup__c = : TestDataSetupUtil_v2.activeSetUp.Id AND Setup__r.Active__c = true AND Active__c = true];
     	 System.debug('$$$$$$$$$$$$STUDS$$$$$$$$$$$'+studs);
     	 Test.startTest(); 
         Database.executeBatch(brp,200) ;
     	 Test.stopTest(); 
     	
    }
}