objects/Grade__c.object
<CustomObject>
    <fields>
        <fullName>Course__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>We store course here as well so we can calculate final grade using aggregate queries</description>
        <label>Course</label>
        <referenceTo>Course__c</referenceTo>
        <relationshipLabel>Grades</relationshipLabel>
        <relationshipName>Grades</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Section__c</fullName>
        <formula>CASESAFEID(Student_Section__r.Section__c)</formula>
        <label>Section</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Student_Section__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Student/Section</label>
        <referenceTo>Student_Section__c</referenceTo>
        <relationshipLabel>Grades</relationshipLabel>
        <relationshipName>Grades</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Student__c</fullName>
        <label>Student</label>
        <referenceTo>Student__c</referenceTo>
        <relationshipLabel>Grades</relationshipLabel>
        <relationshipName>Grades</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Grade</label>
    <nameField>
        <displayFormat>G-{0}</displayFormat>
        <label>Grade Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Grades</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/HoldingObj__c.object
<CustomObject>
    <description>Generic holding object for importing Students/Staff records from a .CSV file.</description>
    <fields>
        <fullName>City__c</fullName>
        <label>City</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Disability_Flag__c</fullName>
        <inlineHelpText>Y/N</inlineHelpText>
        <label>Disability Flag</label>
        <length>1</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ELL__c</fullName>
        <label>ELL</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Student_Id__c</fullName>
        <label>Student Id</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>HoldingObj</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>HoldingObjs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Scheduled_Section__c.object
<CustomObject>
    <fields>
        <fullName>Course__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Course</label>
        <referenceTo>Course__c</referenceTo>
        <relationshipName>Schedule_Templates</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Reporting_Period__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Reporting Period</label>
        <referenceTo>Time_Element__c</referenceTo>
        <relationshipLabel>Scheduled Sections</relationshipLabel>
        <relationshipName>Scheduled_Sections</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Schedule_Group_Section__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup field to Section object populated with the related Schedule Group</description>
        <label>Schedule Group (Section)</label>
        <referenceTo>Section__c</referenceTo>
        <relationshipLabel>Scheduled Sections (Schedule Group (Section))</relationshipLabel>
        <relationshipName>Scheduled_Sections1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Section__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Section</label>
        <referenceTo>Section__c</referenceTo>
        <relationshipLabel>Scheduled Sections</relationshipLabel>
        <relationshipName>Scheduled_Sections</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Scheduled Section</label>
    <nameField>
        <label>Scheduled Section Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Scheduled Sections</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Section__c.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Check this box if the section is a currently active section</description>
        <inlineHelpText>Check this box if the section is a currently active section</inlineHelpText>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Course__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Select the course associated to the section you want to create.</inlineHelpText>
        <label>Course</label>
        <referenceTo>Course__c</referenceTo>
        <relationshipLabel>Sections</relationshipLabel>
        <relationshipName>Sections</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Reporting_Period__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Usually the only reporting period; could be the first if the section spans multiple reporting periods.</description>
        <label>Reporting Period</label>
        <referenceTo>Time_Element__c</referenceTo>
        <relationshipLabel>Sections (First Reporting Period)</relationshipLabel>
        <relationshipName>Sections1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Section__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Recursive lookup for groups</description>
        <label>Section</label>
        <referenceTo>Section__c</referenceTo>
        <relationshipLabel>Groups in Section</relationshipLabel>
        <relationshipName>Sections1</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Section</label>
    <nameField>
        <label>Section Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sections</pluralLabel>
    <recordTypes>
        <fullName>Schedule_Group</fullName>
        <active>true</active>
        <description>Groups of Students Used for Scheduling Purposes</description>
        <label>Schedule Group</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Staff__c.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>City__c</fullName>
        <label>Home City</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>Staff</label>
    <nameField>
        <label>Staff Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Staff</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/Student__c.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>true</defaultValue>
        <inlineHelpText>Indicates whether or not this Student record is active. If checked, then this is the current Student record. If unchecked, this is an old Student record.</inlineHelpText>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>City__c</fullName>
        <inlineHelpText>Displays the city in which the student lives.</inlineHelpText>
        <label>City</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Date_of_Birth__c</fullName>
        <inlineHelpText>Displays the student&apos;s birth date.</inlineHelpText>
        <label>Date of Birth</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Disability_Flag__c</fullName>
        <inlineHelpText>Indicates whether or not the student has a disability.</inlineHelpText>
        <label>Disability Flag</label>
        <length>1</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ELL__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Indicates whether or not the student is an English language learner (ELL).</inlineHelpText>
        <label>ELL</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Entry_Date__c</fullName>
        <inlineHelpText>Displays the student&apos;s first day of school in the current school year.</inlineHelpText>
        <label>Entry Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Ethnicity__c</fullName>
        <inlineHelpText>Displays the student&apos;s ethnic background. You can use this field for reporting purposes.</inlineHelpText>
        <label>Ethnicity</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Hispanic / Latino</fullName>
                </value>
                <value>
                    <fullName>Non-Hispanic / Latino</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Section__c</fullName>
        <inlineHelpText>Displays the student&apos;s current homeroom name or room number. This field can be used for reporting purposes.</inlineHelpText>
        <label>Current Homeroom</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Student_First_Name__c</fullName>
        <inlineHelpText>Displays the student&apos;s first name.</inlineHelpText>
        <label>Student First Name</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Student_Id__c</fullName>
        <inlineHelpText>Displays the student&apos;s ID. This field displays on report cards, progress reports, and transcripts. It must be unique; SchoolForce uses this ID to link the Student record with the correct Contact record.</inlineHelpText>
        <label>Student Id</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Student_Last_Name__c</fullName>
        <inlineHelpText>Displays the student&apos;s last name.</inlineHelpText>
        <label>Student Last Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Student__c</fullName>
        <inlineHelpText>Displays the student&apos;s middle name.</inlineHelpText>
        <label>Student Middle Name</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <label>Student</label>
    <nameField>
        <label>Student Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Students</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Student_Section__c.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Section__c</fullName>
        <label>Section</label>
        <referenceTo>Section__c</referenceTo>
        <relationshipLabel>Student</relationshipLabel>
        <relationshipName>Student_Section</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Student_First_Name__c</fullName>
        <formula>Student__r.Student_First_Name__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Student First Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Student_Id__c</fullName>
        <formula>Student__r.Student_Id__c</formula>
        <label>Student Id</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Student__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Student</label>
        <referenceTo>Student__c</referenceTo>
        <relationshipLabel>Section</relationshipLabel>
        <relationshipName>Student_Section</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Student/Section</label>
    <nameField>
        <displayFormat>SS-{000000}</displayFormat>
        <label>Student/Section ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Student/Section</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/Scheduler_UpsertHolding.cls
public with sharing class Scheduler_UpsertHolding {
	public core_SetupWrapper				cSetup					{get;set;}
	public Scheduler_UpsertHolding(core_SetupWrapper inputSetup){
    	
	    if (inputSetup != null){
			cSetup=inputSetup;
	    
	    }
    }
    
     public void upsertHoldingRecordsForScheduledSec(List<Scheduled_Section__c> scheduledSections){
    	Map <String, Scheduled_Section__c> ssMap 	= new Map <String, Scheduled_Section__c>();
    	Set <Id>	 scheduleGroupIds					= new Set <Id>();
    	Map <Id, List <Student_Section__c>> 		    scheduleGroupMap = new Map <Id, List <Student_Section__c>>();//updated for Chicago
    	Map <String, List <String>>	ssPeriodMap	= new Map <String, List <String>>(); //Used if Section is across multiple periods to keep track of which periods it should get
    	List <HoldingObj__c> holdingObjectList 		= new List <HoldingObj__c>();
    	Set <Id> studIds 											= new Set <Id>();
    	Set <Id> studentSectionIds 							= new Set <Id>();
    	Map <Id, Student__c> studentMap				= new Map <Id, Student__c>();

	
		 //Logic specific for group based setup/publish; schedule group section for Chicago
 			for (Scheduled_Section__c ss:  scheduledSections){
 				string scheduleKey = cSetup.school.id+'-'+ss.Reporting_Period__c+'-'+ss.Schedule_Group_Section__c+'-'+ss.Course__c;  
 				ssMap.put(scheduleKey, ss);
 				System.debug('-------ssMap------------'+ssMap);
 				scheduleGroupIds.add(ss.Schedule_Group_Section__c);
 				scheduleGroupMap.put(ss.Schedule_Group_Section__c, new List <Student_Section__c>());
 				system.debug('~~~~~ schedule group section: '+ss.Schedule_Group_Section__c);
 				system.debug('~~~~~ scheduleGroupMap '+scheduleGroupMap);
 			}
 			
			for (Scheduled_Section__c ss: ssMap.values()){
				HoldingObj__c  ho = ImportMappers.createSectionMapper().generate(ss, cSetup.setup.group_based__c); //Create the holding object record for Sections
				holdingObjectList.add(ho ); //Add Holding object section to List
				System.debug('-------ho------------'+ho);
			}

			system.debug('~~~~~ scheduleGroupMap.keySet() '+scheduleGroupMap.keySet());
			system.debug('~~~~~ with active field '+[select  id, section__c, student__c from Student_Section__c where Section__c in:scheduleGroupMap.keySet() AND Active__c=true]);
			system.debug('~~~~~ with record type '+[select  id, section__c, student__c from Student_Section__c where Section__c in:scheduleGroupMap.keySet() AND Section__r.RecordType.DeveloperName = 'Schedule_Group']);
			for (Student_Section__c ss: [select  id, section__c, student__c from Student_Section__c where Section__c in:scheduleGroupMap.keySet() AND Active__c=true and Section__r.RecordType.DeveloperName = 'Schedule_Group']){
				studIds.add(ss.student__c);
				scheduleGroupMap.get(ss.section__c).add(ss);
			}
			
			for (Student__c stu : [select id, Entry_Date__c,Student_Id__c, Disability_Flag__c, Date_of_Birth__c, Ell__c, Student_First_Name__c, Student_Last_Name__c, Ethnicity__c, Lep_Flag__c, Gender__c, Reference_Id__c, Grade__c, Address__c, City__c, State__c, Zip_Code__c, Mobile_Phone__c 
												FROM Student__c
												where Id in: studIds]){
				studentMap.put(stu.id, stu);											
			}
					
			for (Scheduled_Section__c ss: ssMap.values()){
				for (Student_Section__c groupStud: scheduleGroupMap.get(ss.schedule_group_section__c)){
					Student__c stud = studentMap.get(groupStud.student__c);
					system.debug('stud~~~~~'+stud);
					HoldingObj__c  ho = ImportMappers.createStudentSchoolGradeMapper().generate(stud, ss); //Create the holding object record for Sections
					holdingObjectList.add(ho);
				}
			}
			

			if (!holdingObjectList.isEmpty()){

				try {
					upsert holdingObjectList  Reference_Id__c;	
					for(Scheduled_Section__c ss: scheduledSections) ss.Needs_Publish__c = false;
					update scheduledSections;
				//	cSetup.setup.Published__c = true; DE 1202
				//	update cSetup.setup;
					}
				catch (exception e){
					 Global_Error__c ge = Error_Handling.handleError('Scheduler_UpsertHoldingObject', 'Scheduler', 'Upserting to Holding Object for: '+cSetup.setup.Id, e);
					insert ge;
				}
			}
	
	    }
    
    public void upsertHoldingRecordsForPeriods(List<Scheduled_Section__c> scheduledSections){
    	Map <String, Scheduled_Section__c> 		ssMap 					= 	new Map <String, Scheduled_Section__c>();
	    Set <Id>	 							scheduleGroupIds		= 	new Set <Id>();
	    Map <Id, List <Student__c>> 		    scheduleGroupMap 		= 	new Map <Id, List <Student__c>>();
	  //PU   Map <String, List <String>>				ssPeriodMap				= 	new Map <String, List <String>>(); //Used if Section is across multiple periods to keep track of which periods it should get
	    List <HoldingObj__c> 					holdingObjectList 		= 	new List <HoldingObj__c>();
	    	
	    	for (Scheduled_Section__c ss:  scheduledSections){
				string scheduleKey = cSetup.school.id+'-'+ss.Reporting_Period__c+'-'+ss.Section__r.Reference_Id__c+'-'+ss.Course__c+'-'+ss.Staff__c;  //School - Reporting Period - Schedule Group - Course -Staff (US592) Need to add logic for if course spans multiple reporting periods and how we will 'keep' the same section
					System.debug('LE map key: '+scheduleKey+ ' exists in map? '+ssMap.containsKey(scheduleKey));
					ssMap.put(scheduleKey, ss);
 			}
		
	
/* Update the list that is looped over here for proper multiple teacher sections*/ 
    	for (Scheduled_Section__c ss: ssMap.values()){
    		string scheduleKey = cSetup.school.id+'-'+ss.Reporting_Period__c+'-'+ss.Section__r.Reference_Id__c+'-'+ss.Course__c+'-'+ss.Staff__c;
    		HoldingObj__c  ho = ImportMappers.createSectionMapper().generate(ss, cSetup.setup.group_based__c); //Create the holding object record for Sections
    					   ho.Reference_Id__c = scheduleKey;
    		holdingObjectList.add(ho ); //Add Holding object section to List

    	}
	
    	if (!holdingObjectList.isEmpty()){

    		try {
    			upsert holdingObjectList  Reference_Id__c;
    			for(Scheduled_Section__c ss: scheduledSections) ss.Needs_Publish__c = false;
				update scheduledSections;	
    			cSetup.setup.Published__c = true;
    			update cSetup.setup;
    		 	}
    		catch (exception e){
    			  System.debug('Publish failed'+e.getMessage());
    		}
    	}
	
	    }
}