objects/Grade__c.object
<CustomObject>
    <fields>
        <fullName>Strand_Grade__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Strand Grade</label>
        <referenceTo>Strand_Grade__c</referenceTo>
        <relationshipLabel>Grades</relationshipLabel>
        <relationshipName>Grades</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Student__c</fullName>
        <label>Student</label>
        <referenceTo>Student__c</referenceTo>
        <relationshipLabel>Grades</relationshipLabel>
        <relationshipName>Grades</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Grade</label>
    <nameField>
        <displayFormat>G-{0}</displayFormat>
        <label>Grade Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Grades</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Setup__c.object
<CustomObject>
    <description>This object is used to setup Schoolforce and is referenced in multiple pieces of code.  There should be one setup object per school.</description>
    <fields>
        <fullName>Term__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Term refers to the Term &apos;Template&apos; that the administrator associates to the School; this contains all Semeser/Quarter/Period logic necessary to create Sessions.</description>
        <label>Term</label>
        <referenceTo>Time_Element__c</referenceTo>
        <relationshipLabel>Setup</relationshipLabel>
        <relationshipName>Setup</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Setup</label>
    <nameField>
        <displayFormat>S-{0}</displayFormat>
        <label>Setup ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Setup</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/Standard__c.object
<CustomObject>
    <fields>
        <fullName>Description_Spanish__c</fullName>
        <description>The strand and standard description in Spanish language</description>
        <inlineHelpText>The strand and standard description in Spanish</inlineHelpText>
        <label>Description in Spanish</label>
        <length>32000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Long_Text__c</fullName>
        <inlineHelpText>Long text description of the standard that displays in the hover over in the Gradebook and on Portal/PGV. Max of 32,000 characters to describe the Standard.</inlineHelpText>
        <label>Long Text</label>
        <length>32000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Standard_Subject__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>This is the “Subject” that all standards and strands look up to.   Standard/Strand grades are presented on Report Cards and Progress Reports under the specific “Subject.”  Subjects can be imported. NOTE: This is a different field that the “Course Subjec</inlineHelpText>
        <label>Standard Subject</label>
        <referenceTo>Standard__c</referenceTo>
        <relationshipLabel>Standards (Standard Subject)</relationshipLabel>
        <relationshipName>Subject_Standards</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Strand__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Indicates if a standard looks up to a Strand.  Strand grades are only calculated for the Standards-Only Gradebook.</inlineHelpText>
        <label>Strand</label>
        <referenceTo>Standard__c</referenceTo>
        <relationshipLabel>Standards (Strand)</relationshipLabel>
        <relationshipName>Strands</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Subject__c</fullName>
        <inlineHelpText>retired field</inlineHelpText>
        <label>Subject</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>Standard</label>
    <nameField>
        <label>Standard Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Standards</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Strand_Grade__c.object
<CustomObject>
    <description>Stores strand grades per student/reporting period/strand (Standard object)</description>
    <fields>
        <fullName>Grade_Overridden__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Grade Overridden</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Grade_Override__c</fullName>
        <label>Grade Override</label>
        <precision>4</precision>
        <scale>1</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Grade__c</fullName>
        <description>Standards Based Grade of the Strand for the Student/Reporting Period/Strand</description>
        <label>Calculated Grade</label>
        <precision>2</precision>
        <scale>1</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Reporting_Period__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Reporting Period of the Strand Grade</description>
        <label>Reporting Period</label>
        <referenceTo>Time_Element__c</referenceTo>
        <relationshipLabel>Strand Grades</relationshipLabel>
        <relationshipName>Strand_Grades</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Strand_Grade__c</fullName>
        <formula>IF(NOT(ISNULL( Grade_Override__c )), TEXT(ROUND(Grade_Override__c,1)), 
IF(Grade__c&gt;=3.75,&apos;4.0&apos;, 
IF(Grade__c&gt;=3.25,&apos;3.5&apos;, 
IF(Grade__c&gt;=2.75,&apos;3.0&apos;, 
IF(Grade__c&gt;=2.25,&apos;2.5&apos;, 
IF(Grade__c&gt;=1.75,&apos;2.0&apos;, 
IF(Grade__c&gt;=1.25,&apos;1.5&apos;, 
IF(Grade__c&gt;=0.75,&apos;1.0&apos;, 
IF(Grade__c&gt;=0.25,&apos;0.5&apos;, 
IF(Grade__c&gt;=0.0,&apos;0.0&apos;, 
&apos;N/A&apos;))))))))))</formula>
        <label>Grade</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Strand__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Strand related to the Strand Grade</description>
        <label>Strand</label>
        <referenceTo>Standard__c</referenceTo>
        <relationshipLabel>Strand Grades</relationshipLabel>
        <relationshipName>Strand_Grades</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Student__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Student</label>
        <referenceTo>Student__c</referenceTo>
        <relationshipLabel>Strand Grades</relationshipLabel>
        <relationshipName>Strand_Grades</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Subject__c</fullName>
        <formula>TEXT(Strand__r.Course__r.Subject_Area__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Subject</label>
        <type>Text</type>
    </fields>
    <label>Strand Grade</label>
    <nameField>
        <displayFormat>SG-{000000}</displayFormat>
        <label>Strand Grade Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Strand Grades</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Student__c.object
<CustomObject>
    <fields>
        <fullName>Grade__c</fullName>
        <inlineHelpText>Displays the student&apos;s current grade level.</inlineHelpText>
        <label>Grade</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>PS</fullName>
                </value>
                <value>
                    <fullName>PK</fullName>
                    <color>#78C953</color>
                    <label>PK</label>
                </value>
                <value>
                    <fullName>K</fullName>
                </value>
                <value>
                    <fullName>1</fullName>
                    <color>#A845DC</color>
                    <label>1</label>
                </value>
                <value>
                    <fullName>2</fullName>
                    <color>#F3D904</color>
                    <label>2</label>
                </value>
                <value>
                    <fullName>3</fullName>
                    <color>#A53711</color>
                    <label>3</label>
                </value>
                <value>
                    <fullName>4</fullName>
                    <color>#66E9BD</color>
                    <label>4</label>
                </value>
                <value>
                    <fullName>5</fullName>
                    <color>#0B24BE</color>
                    <label>5</label>
                </value>
                <value>
                    <fullName>6</fullName>
                    <color>#419249</color>
                    <label>6</label>
                </value>
                <value>
                    <fullName>7</fullName>
                    <color>#B6E32E</color>
                    <label>7</label>
                </value>
                <value>
                    <fullName>8</fullName>
                    <color>#641CCF</color>
                    <label>8</label>
                </value>
                <value>
                    <fullName>9</fullName>
                    <color>#F96FB7</color>
                    <label>9</label>
                </value>
                <value>
                    <fullName>10</fullName>
                    <color>#2F5D85</color>
                    <label>10</label>
                </value>
                <value>
                    <fullName>11</fullName>
                    <color>#AFCADF</color>
                    <label>11</label>
                </value>
                <value>
                    <fullName>12</fullName>
                    <color>#8F6429</color>
                    <label>12</label>
                </value>
                <value>
                    <fullName>UN Ungraded</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Setup__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Displays the Setup record associated to this Student record. The Setup record defines the settings for the school in a specific school year.</inlineHelpText>
        <label>Setup</label>
        <referenceTo>Setup__c</referenceTo>
        <relationshipLabel>Students</relationshipLabel>
        <relationshipName>Students</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Student__c</fullName>
        <inlineHelpText>Displays the student&apos;s middle name.</inlineHelpText>
        <label>Student Middle Name</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <label>Student</label>
    <nameField>
        <label>Student Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Students</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Term__c.object
<CustomObject>
    <description>Junction object  between Time and Setup.</description>
    <fields>
        <fullName>Setup__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Setup</label>
        <referenceTo>Setup__c</referenceTo>
        <relationshipLabel>Terms</relationshipLabel>
        <relationshipName>Terms</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Time_Element__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Time Element</label>
        <referenceTo>Time_Element__c</referenceTo>
        <relationshipLabel>Terms</relationshipLabel>
        <relationshipName>Terms</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Term</label>
    <nameField>
        <displayFormat>Term-{000000}</displayFormat>
        <label>Term Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Terms</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Time_Element__c.object
<CustomObject>
    <fields>
        <fullName>End_Date__c</fullName>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Name__c</fullName>
        <label>Name</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Reporting_Period__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Reporting Period?</label>
        <type>Checkbox</type>
    </fields>
    <label>Time</label>
    <nameField>
        <displayFormat>T-{000000}</displayFormat>
        <label>Time Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Time</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/Student_StrandGrades.cls
public class Student_StrandGrades {
	
	public  ApexPages.StandardController controller {get; set;}
	public  List<subjectWrapper> subjectWrappers {get; set;}
	public  ID studentID {get; set;}
	public  Student__c currentStudent {get; set;}
	public  List<Time_Element__c> orderedReportingPeriods {get; set;}
	
	private  List<Strand_Grade__c> strandGrades = new List<Strand_Grade__c>();
	
	public Student_StrandGrades(ApexPages.StandardController controller){
		
		//initialize
		subjectWrappers = new List<subjectWrapper>();
		orderedReportingPeriods = new List<Time_Element__c>();
		
		if (System.currentPageReference().getParameters().containsKey('id')!=null) {
			studentID = System.currentPageReference().getParameters().get('id');
			currentStudent = core_SoqlUtils.getStudentById(studentID)[0];
			getStrandGrades();			
		}
	}

	private void getStrandGrades() {
		//we only care about getting the standard grades for the student.
		//we need rp order? requires section-reporting-periods, standard/strand grades
		//are not section tied, so cannot really rely on srp.
		
		//first get all the standard grades.  Figure out what is the latest rp.  Then build off of it
		//reason is because of the possibility that there could be a standard grade on a final rp.
		
		//unfortunately need to loop twice through strandGrades, to find the F-RP Filters.			
		strandGrades = [SELECT ID, Grade_Overridden__c, Grade_Override__c, Strand__r.Standard_Subject__c, 
				Strand__r.Standard_Subject__r.Name, Reporting_Period__c, Grade__c, Strand__r.Subject__c, 
				Strand__r.Description_Spanish__c, Reporting_Period__r.Name__c, Name, Strand__r.Name, 
				Strand__r.Long_Text__c, Strand__c,Reporting_Period__r.Reporting_Period__c
				FROM Strand_Grade__c 
				WHERE student__c = :studentId
				AND Reporting_Period__c != null
				ORDER BY Strand__r.Subject__c, Strand__r.Name, Reporting_Period__r.End_Date__c, Reporting_Period__r.Reporting_Period__c DESC, Name ASC];
		
		//so much work for a filter...
		Set<ID> includeRP = new Set<ID>();
		for(Strand_Grade__c sg : strandGrades) {
			if(!sg.Reporting_Period__r.Reporting_Period__c) {
				includeRP.add(sg.Reporting_Period__c);
			}
		}

		orderedReportingPeriods = Gradebook_ReportCard_Utils.getReportingPeriods(currentStudent.Setup__r.Term__c);	
		for(Integer i = 0; i < orderedReportingPeriods.size(); i++) {
			if(!(orderedReportingPeriods[i].Reporting_Period__c || includeRP.contains(orderedReportingPeriods[i].ID))) {
				orderedReportingPeriods.remove(i);
				i--;
			}
		}
		
		List<standardWrapper> strands = new List<standardWrapper>();
		for(Integer i=0; i < strandGrades.size(); i++){				
			String strand = strandGrades[i].Strand__c;
			standardWrapper sw = new standardWrapper();
			sw.subject = strandGrades[i].Strand__r.Subject__c;
			sw.Name = strandGrades[i].Strand__r.Name;
			sw.Description = strandGrades[i].Strand__r.long_text__c;
			
			for(Time_Element__c rp : orderedReportingPeriods){
				if(i < strandGrades.size()){
					Strand_Grade__c sg = strandGrades[i];
					if(sg.Strand__r.Subject__c == sw.subject && sg.Strand__c == strand && sg.Reporting_Period__c == rp.id) {
						if(i > 0){
							Strand_Grade__c lastProcessed = strandGrades[i-1];
						}
						if(sg.Grade__c == null || (sg.Grade_Overridden__c && sg.Grade_Override__c == null)){
							sw.Grade.add('');
						} else {
							sw.Grade.add(String.valueOf(((sg.Grade_Overridden__c) ? sg.Grade_Override__c : sg.Grade__c).divide(1,1)));
						}
						i++;
					}
					else{
						sw.Grade.add('');
					}
				} 
				else {
					sw.Grade.add('');
				}
			}
			i--;
			strands.add(sw);
			if(i>=strandGrades.size()-1 || sw.subject != strandGrades[i+1].Strand__r.Subject__c){
				subjectWrappers.add(new subjectWrapper(strands));
				strands = new List<standardWrapper>();
			}
		}	
	}
	
	public class subjectWrapper{
		public  List<standardWrapper> standards	{get;set;} //can be strands too
		public  String subject					{get;set;}
		
		public subjectWrapper(List<standardWrapper> standards){
			this.standards = standards;
			this.subject = this.standards[0].subject;
		}
	}
	
	public class standardWrapper{
		public  List<String> grade	{get; set;}
		public  String description	{get; set;}
		public  String strandName	{get; set;}
		public  String Name			{get; set;}
		public  String cssClass		{get; set;}		
		public  String subject 		{get; set;}
		
		public standardWrapper(){
			grade = new List<String>();
		}
	}
}