objects/Grade__c.object
<CustomObject>
    <fields>
        <fullName>Student__c</fullName>
        <label>Student</label>
        <referenceTo>Student__c</referenceTo>
        <relationshipLabel>Grades</relationshipLabel>
        <relationshipName>Grades</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Grade</label>
    <nameField>
        <displayFormat>G-{0}</displayFormat>
        <label>Grade Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Grades</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Student__c.object
<CustomObject>
    <fields>
        <fullName>Grade__c</fullName>
        <inlineHelpText>Displays the student&apos;s current grade level.</inlineHelpText>
        <label>Grade</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>PS</fullName>
                </value>
                <value>
                    <fullName>PK</fullName>
                    <color>#78C953</color>
                    <label>PK</label>
                </value>
                <value>
                    <fullName>K</fullName>
                </value>
                <value>
                    <fullName>1</fullName>
                    <color>#A845DC</color>
                    <label>1</label>
                </value>
                <value>
                    <fullName>2</fullName>
                    <color>#F3D904</color>
                    <label>2</label>
                </value>
                <value>
                    <fullName>3</fullName>
                    <color>#A53711</color>
                    <label>3</label>
                </value>
                <value>
                    <fullName>4</fullName>
                    <color>#66E9BD</color>
                    <label>4</label>
                </value>
                <value>
                    <fullName>5</fullName>
                    <color>#0B24BE</color>
                    <label>5</label>
                </value>
                <value>
                    <fullName>6</fullName>
                    <color>#419249</color>
                    <label>6</label>
                </value>
                <value>
                    <fullName>7</fullName>
                    <color>#B6E32E</color>
                    <label>7</label>
                </value>
                <value>
                    <fullName>8</fullName>
                    <color>#641CCF</color>
                    <label>8</label>
                </value>
                <value>
                    <fullName>9</fullName>
                    <color>#F96FB7</color>
                    <label>9</label>
                </value>
                <value>
                    <fullName>10</fullName>
                    <color>#2F5D85</color>
                    <label>10</label>
                </value>
                <value>
                    <fullName>11</fullName>
                    <color>#AFCADF</color>
                    <label>11</label>
                </value>
                <value>
                    <fullName>12</fullName>
                    <color>#8F6429</color>
                    <label>12</label>
                </value>
                <value>
                    <fullName>UN Ungraded</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Student_First_Name__c</fullName>
        <inlineHelpText>Displays the student&apos;s first name.</inlineHelpText>
        <label>Student First Name</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Student_Id__c</fullName>
        <inlineHelpText>Displays the student&apos;s ID. This field displays on report cards, progress reports, and transcripts. It must be unique; SchoolForce uses this ID to link the Student record with the correct Contact record.</inlineHelpText>
        <label>Student Id</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Student_Last_Name__c</fullName>
        <inlineHelpText>Displays the student&apos;s last name.</inlineHelpText>
        <label>Student Last Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Student__c</fullName>
        <inlineHelpText>Displays the student&apos;s middle name.</inlineHelpText>
        <label>Student Middle Name</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <label>Student</label>
    <nameField>
        <label>Student Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Students</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/studentWrapper.cls
global class studentWrapper{
	public String studentName	{get; set;}
	public String studentId		{get; set;}
	public String gradeLevel	{get; set;}
	public String indicatorArea {get; set;}
	public String iaIds			{get; set;}
	public Date enrollmentDate	{get; set;}
	public Boolean checked		{get;set;}
	public String sfStudentID	{get;set;}
		
	public studentWrapper(String inputStudentName, String inputStudentId, String inputGradeLevel, String inputIndicatorArea, String inputIndicatorAreaIds) {
		this.studentName = inputStudentName;
		this.studentId = inputStudentId;
		this.gradeLevel = inputGradeLevel;
		this.indicatorArea = inputIndicatorArea;
		this.iaIds = inputIndicatorAreaIds;
		this.checked = false;
	}

	public studentWrapper(Student__c student, String inputIndicatorArea, String inputIndicatorAreaIds){
		this.studentName = student.Student_Last_Name__c + ', '+ student.Student_First_Name__c;
		this.studentID = student.id;
		this.gradeLevel = student.Grade__c;
		this.indicatorArea = inputIndicatorArea;
		this.iaIds = inputIndicatorAreaIds;
		this.sfStudentID = student.Student_ID__c;
		this.checked = false;
	}
}