objects/Grade__c.object
<CustomObject>
    <fields>
        <fullName>Section__c</fullName>
        <formula>CASESAFEID(Student_Section__r.Section__c)</formula>
        <label>Section</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Student_Section__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Student/Section</label>
        <referenceTo>Student_Section__c</referenceTo>
        <relationshipLabel>Grades</relationshipLabel>
        <relationshipName>Grades</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Grade</label>
    <nameField>
        <displayFormat>G-{0}</displayFormat>
        <label>Grade Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Grades</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Section__c.object
<CustomObject>
    <fields>
        <fullName>Section__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Recursive lookup for groups</description>
        <label>Section</label>
        <referenceTo>Section__c</referenceTo>
        <relationshipLabel>Groups in Section</relationshipLabel>
        <relationshipName>Sections1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>of_Consecutive_Days_without_Grades__c</fullName>
        <defaultValue>0</defaultValue>
        <description>This field is updated nightly and keeps track of whether grades were entered in the gradebook for that day.</description>
        <inlineHelpText>This field is updated nightly and keeps track of whether grades were entered in the gradebook for that day.</inlineHelpText>
        <label># of Consecutive Days without Grades</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Section</label>
    <nameField>
        <label>Section Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sections</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Student_Section__c.object
<CustomObject>
    <fields>
        <fullName>Section__c</fullName>
        <label>Section</label>
        <referenceTo>Section__c</referenceTo>
        <relationshipLabel>Student</relationshipLabel>
        <relationshipName>Student_Section</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Student/Section</label>
    <nameField>
        <displayFormat>SS-{000000}</displayFormat>
        <label>Student/Section ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Student/Section</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/GradebookUtilizationBatch.cls
global class GradebookUtilizationBatch implements Database.Batchable<sObject>,Database.Stateful{
	public String query;
	public String email;
	public DateTime daystart;
	public DateTime dayend;
	Integer year = system.now().year();
    Integer month = system.now().month();
    Integer day = system.now().day();
	
	global GradebookUtilizationBatch () {
		Integer year = system.now().year();
	    Integer month = system.now().month();
	    Integer day = system.now().day();
	    daystart = datetime.newInstance(year, month, day, 0, 0, 0);
	    dayend = datetime.newInstance(year, month, day, 23, 59, 59);
	}


	global database.querylocator start(Database.BatchableContext BC){
		return Database.getQueryLocator(query);
	}

	global void execute(Database.BatchableContext BC, List<Section__c> scope){
		
		List<Section__c> sList = new List<Section__c>();
		for(Section__c s:scope){
			List<Grade__c> gradeList = new List<Grade__c>();
			List<Grade__c> totgradeList = new List<Grade__c>();
			gradeList = [select Id, Name from Grade__c where Student_Section__r.Section__c = :s.Id AND LastModifiedDate > :daystart AND LastModifiedDate < :dayend];
			totgradeList = [select Id, Name from Grade__c where Student_Section__r.Section__c = :s.Id ];		
		
			if(totgradeList.size()>0){
				if(gradeList.size()>0){
					s.of_Consecutive_Days_without_Grades__c =0;
				}
				else{
					s.of_Consecutive_Days_without_Grades__c ++;
				}
				
				sList.add(s);
			}
		}
		
		try{
			update sList;
		}
		catch(exception e){
			system.debug('#### There was an error updating the section with the missed Grade days.');
		}
	}
	
	global void finish(Database.BatchableContext BC){
		AsyncApexJob a = [Select Id, Status, NumberOfErrors, JobItemsProcessed,
        TotalJobItems, CreatedBy.Email
        from AsyncApexJob where Id =:BC.getJobId()];
         
    	if(a.NumberOfErrors>0){
	        Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
	        String[] toAddresses = new String[] {a.CreatedBy.email};
	        mail.setToAddresses(toAddresses);
	        mail.setSubject('Errors during Update of Sections');
	        
		   	mail.setPlainTextBody
	   		('The batch Apex job processed ' + a.TotalJobItems +
	   		' batches with '+ a.NumberOfErrors + ' failures.');
	  		Messaging.sendEmail(new Messaging.SingleEmailMessage[] { mail });
    	}
	} 
	
}