objects/HoldingObj__c.object
<CustomObject>
    <description>Generic holding object for importing Students/Staff records from a .CSV file.</description>
    <fields>
        <fullName>Propagated__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Propagated</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>School_Dbn__c</fullName>
        <label>School Dbn</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>School_Year__c</fullName>
        <label>School Year</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <label>HoldingObj</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>HoldingObjs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Schedule_Template__c.object
<CustomObject>
    <fields>
        <fullName>Reporting_Period__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Reporting Period</label>
        <referenceTo>Time_Element__c</referenceTo>
        <relationshipLabel>Schedule Templates</relationshipLabel>
        <relationshipName>Schedule_Templates</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Setup__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Setup</label>
        <referenceTo>Setup__c</referenceTo>
        <relationshipLabel>Schedule Templates</relationshipLabel>
        <relationshipName>Schedule_Templates</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Schedule Template</label>
    <nameField>
        <label>Schedule Template Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Schedule Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Scheduled_Section__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>School associated to the scheduled section</description>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Scheduled Sections</relationshipLabel>
        <relationshipName>Scheduled_Sections</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Needs_Publish__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Indicator of whether this scheduled section has been published since its creation (or, if a scheduled section has been edited, whether it has been re-published)</description>
        <label>Needs Publish</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Reporting_Period__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Reporting Period</label>
        <referenceTo>Time_Element__c</referenceTo>
        <relationshipLabel>Scheduled Sections</relationshipLabel>
        <relationshipName>Scheduled_Sections</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Schedule_Template__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Schedule Template</label>
        <referenceTo>Schedule_Template__c</referenceTo>
        <relationshipLabel>Scheduled Sections</relationshipLabel>
        <relationshipName>Scheduled_Sections</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Scheduled Section</label>
    <nameField>
        <label>Scheduled Section Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Scheduled Sections</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Setup__c.object
<CustomObject>
    <description>This object is used to setup Schoolforce and is referenced in multiple pieces of code.  There should be one setup object per school.</description>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Is this school setup active for this school year?</inlineHelpText>
        <label>Active?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>School__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>School</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1 OR 2</booleanFilter>
            <filterItems>
                <field>Account.RecordType.Name</field>
                <operation>equals</operation>
                <value>School</value>
            </filterItems>
            <filterItems>
                <field>Account.RecordType.Name</field>
                <operation>equals</operation>
                <value>Summer School</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Setup</relationshipLabel>
        <relationshipName>Setup</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Term__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Term refers to the Term &apos;Template&apos; that the administrator associates to the School; this contains all Semeser/Quarter/Period logic necessary to create Sessions.</description>
        <label>Term</label>
        <referenceTo>Time_Element__c</referenceTo>
        <relationshipLabel>Setup</relationshipLabel>
        <relationshipName>Setup</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Year__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>School Year associated to the Setup</description>
        <label>Year</label>
        <referenceTo>Time_Element__c</referenceTo>
        <relationshipLabel>Setup (Year)</relationshipLabel>
        <relationshipName>Setup_Year</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Setup</label>
    <nameField>
        <displayFormat>S-{0}</displayFormat>
        <label>Setup ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Setup</pluralLabel>
    <recordTypes>
        <fullName>Published</fullName>
        <active>true</active>
        <description>For Published Setups - Not Editable</description>
        <label>Published</label>
    </recordTypes>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/Snapshot_Log__c.object
<CustomObject>
    <fields>
        <fullName>School__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>School</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Snapshot Log</relationshipLabel>
        <relationshipName>Snapshot_Log</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Setup__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Setup</label>
        <referenceTo>Setup__c</referenceTo>
        <relationshipLabel>Snapshot Log</relationshipLabel>
        <relationshipName>Snapshot_Log</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Snapshot_Taken__c</fullName>
        <defaultValue>NOW()</defaultValue>
        <label>Snapshot Taken</label>
        <required>true</required>
        <type>DateTime</type>
    </fields>
    <label>Snapshot Log</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Snapshot ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Snapshot Log</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Snapshot_Summary__c.object
<CustomObject>
    <fields>
        <fullName>Reenrollment_Rate__c</fullName>
        <label>Reenrollment Rate</label>
        <precision>7</precision>
        <scale>4</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>School__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>School</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Snapshot Summaries</relationshipLabel>
        <relationshipName>Snapshot_Summaries</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Student__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Student</label>
        <referenceTo>Student__c</referenceTo>
        <relationshipLabel>Snapshot Summaries</relationshipLabel>
        <relationshipName>Snapshot_Summaries</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Snapshot Summary</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Snapshot Summary ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Snapshot Summaries</pluralLabel>
    <recordTypes>
        <fullName>School_Summary</fullName>
        <active>true</active>
        <label>School Summary</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Student__c.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>true</defaultValue>
        <inlineHelpText>Indicates whether or not this Student record is active. If checked, then this is the current Student record. If unchecked, this is an old Student record.</inlineHelpText>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>School_Year__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Displays the Time record for the school year. You can view the name of this Time record in the School Year Name field.</inlineHelpText>
        <label>School Year</label>
        <referenceTo>Time_Element__c</referenceTo>
        <relationshipLabel>Students</relationshipLabel>
        <relationshipName>Students1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>School__c</fullName>
        <inlineHelpText>Displays the name of the student&apos;s current SchoolForce school. You can click on the link to see the details of this school.</inlineHelpText>
        <label>School</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Students</relationshipLabel>
        <relationshipName>Students</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Setup__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Displays the Setup record associated to this Student record. The Setup record defines the settings for the school in a specific school year.</inlineHelpText>
        <label>Setup</label>
        <referenceTo>Setup__c</referenceTo>
        <relationshipLabel>Students</relationshipLabel>
        <relationshipName>Students</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Student__c</fullName>
        <inlineHelpText>Displays the student&apos;s middle name.</inlineHelpText>
        <label>Student Middle Name</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <label>Student</label>
    <nameField>
        <label>Student Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Students</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Term__c.object
<CustomObject>
    <description>Junction object  between Time and Setup.</description>
    <fields>
        <fullName>Setup__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Setup</label>
        <referenceTo>Setup__c</referenceTo>
        <relationshipLabel>Terms</relationshipLabel>
        <relationshipName>Terms</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Term</label>
    <nameField>
        <displayFormat>Term-{000000}</displayFormat>
        <label>Term Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Terms</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Time_Element__c.object
<CustomObject>
    <fields>
        <fullName>Date_Start_Date__c</fullName>
        <defaultValue>Today()</defaultValue>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Name__c</fullName>
        <label>Name</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Parent_Time_Element__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Parent Time Element</label>
        <referenceTo>Time_Element__c</referenceTo>
        <relationshipLabel>Children Time Elements</relationshipLabel>
        <relationshipName>Time</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Reporting_Period__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Reporting Period?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>School__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>School</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Time</relationshipLabel>
        <relationshipName>Time</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Time</label>
    <nameField>
        <displayFormat>T-{000000}</displayFormat>
        <label>Time Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Time</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/core_SetupHome.cls
public with sharing class core_SetupHome {
 	  public ApexPages.StandardController 			controller 				{get; set;}
	  public String 													setupId					{get;set;}
	  public Id														tempDeleteId			{get;set;}	
	  public string														selectedGroupId		{get;set;}						
	  public core_SetupWrapper							cSetup					{get;set;}
	
	public core_SetupHome(ApexPages.StandardController controller){
		try{
			if (System.currentPageReference().getParameters().containsKey('id')!=null) setupId = System.currentPageReference().getParameters().get('id');
			if (setupId!=null){ 
				cSetup= new core_SetupWrapper(core_SoqlUtils.getSetupById(setupId),'home');
				if (cSetup.setup.Active__c){
					Integer needPublish = [SELECT count() FROM Scheduled_Section__c WHERE Needs_Publish__c = true AND Account__c = :cSetup.school.id AND reporting_period__r.parent_time_element__c=:cSetup.setup.term__c] + [SELECT count() FROM HoldingObj__c WHERE Propagated__c = false AND School_DBN__c = :cSetup.school.Name AND School_Year__c = :cSetup.setup.Year__r.Name__c];
					if(needPublish > 0) ApexPages.addMessage(new apexpages.message(apexpages.severity.INFO,'There are records for this setup record that have not yet been published.  Please publish at your earliest convenience.'));
				}
			}
		}
		catch(Exception e){
			ApexPages.addMessage(new apexpages.message(apexpages.severity.ERROR, 'An error occurred during initialization.'));
		} 
	}

	/*
	public Pagereference deleteTemplate(){
		try{
			tempDeleteId = System.currentPageReference().getParameters().get('tempDeleteId');
			system.debug (tempDeleteId);
			if (tempDeleteId!=null){ 
				Schedule_Template__c schedTemplate = core_SoqlUtils.getTemplateById(tempDeleteId);
				delete schedTemplate;
				PageReference pr = new PageReference('/apex/core_SetupHome?id='+cSetup.setup.id);
				pr.setRedirect(true);
				return pr;
			}
			else return null;
		}
		catch(Exception e){
			ApexPages.addMessage(new apexpages.message(apexpages.severity.ERROR, 'An error occurred while deleting the schedule template.'));
			//Global_Error__c ge = Error_Handling.handleError('Setup, '+cSetup.setup.id+'; Schedule Template, '+tempDeleteId, 'Core (Setup)', 'error deleting template', e);
			//insert ge;
			return null;
		} 
	}
	*/
	
	public pageReference addScheduleGroup(){
		pageReference pr = Page.core_GroupConfiguration;
		pr.getParameters().put('setupId',cSetup.setup.id);
		pr.setRedirect(true);
		return pr;
	}
	
	public pageReference editGroup(){
		selectedGroupId=System.currentPageReference().getParameters().get('selectedGroupId');
		system.debug('selectedGroupId~~~~'+selectedGroupId);
		pageReference pr = Page.core_GroupConfiguration;
		pr.getParameters().put('setupId',cSetup.setup.id);
		pr.getParameters().put('id',selectedGroupId);
		pr.setRedirect(true);
		return pr;
	}
	
	public pageReference addStudentsToGroup(){
		selectedGroupId=System.currentPageReference().getParameters().get('selectedGroupId');
		pageReference pr = Page.core_GroupConfiguration;
		pr.getParameters().put('setupId',cSetup.setup.id);
		pr.getParameters().put('id',selectedGroupId);
		pr.getParameters().put('add','true');
		pr.setRedirect(true);
		return pr;
	}
	
	public void setReenrollmentRate() {
		try {
			BatchSnapshotSchoolCalcs calcs = new BatchSnapshotSchoolCalcs();
			Setup__c currSetup = [select id, School__c, Year__r.Date_Start_Date__c 
									from Setup__c where id = :setupId];
			Setup__c prevSetup = calcs.findPreviousSetup(currSetup);
			List<Student__c> students = calcs.getEligibleForEnrollment(prevSetup);
			Decimal rate = calcs.getEnrollmentPercent(students, currSetup);
			AggregateResult ar = [select max(Snapshot_Taken__c) maxDate
									from Snapshot_Log__c 
									where Setup__c = :prevSetup.id];
			DateTime maxDate = (DateTime)ar.get('maxDate'); 
			List<Snapshot_Summary__c> snaps = [select id, Reenrollment_Rate__c
												from Snapshot_Summary__c
												where Snapshot_ID__r.Setup__c = :prevSetup.id and
												RecordType.DeveloperName = 'School_Summary' and
												Snapshot_ID__r.Snapshot_Taken__c = :maxDate];
			if (snaps == null || snaps.size() == 0) {
				throw new Error_Handling.schoolForceException('No snapshot found');
			}
			for (Snapshot_Summary__c s : snaps) {
				s.Reenrollment_Rate__c = rate;
			}
			update snaps;
			Apexpages.addMessage(new Apexpages.Message(Apexpages.Severity.INFO, 'Reenrollment rate set to ' + rate));
		}
		catch (Exception e) {
			Apexpages.addMessage(new Apexpages.Message(Apexpages.Severity.ERROR, 'Reenrollment rate not set.  Make sure a snapshot exists for the previous year. (' + e + ')' ));
		}
	}

	static testMethod void test_core_SetupHome(){
		TestDataSetupUtil_v2.setUPCoreData(1);
		PageReference pr = Page.core_SetupHome;
		pr.getParameters().put('id','abcde');
		Test.setCurrentPage(pr);
		Test.startTest();
			ApexPages.StandardController con = new ApexPages.StandardController(TestDataSetupUtil_v2.activeSetup);
			core_SetupHome setupHomecontroller = new core_SetupHome(con);
			system.assertEquals('An error occurred during initialization.',ApexPages.getMessages()[0].getSummary());
			pr.getParameters().put('id',TestDataSetupUtil_v2.activeSetUp.id);
			setupHomecontroller = new core_SetupHome(con);
			system.assertEquals(setupHomecontroller.setupId, TestDataSetupUtil_v2.activeSetUp.id);
			system.assertEquals(setupHomecontroller.cSetup.reportingPeriodList.size(),2);
			
			PageReference returnPR = setupHomeController.addScheduleGroup();
			system.assertEquals(TestDataSetupUtil_v2.activeSetup.id,returnPR.getParameters().get('setupId'));
			
			pr.getParameters().put('selectedGroupId','testid');
			returnPR = setupHomeController.editGroup();
			system.assertEquals(TestDataSetupUtil_v2.activeSetup.id,returnPR.getParameters().get('setupId'));
			system.assertEquals('testid',returnPR.getParameters().get('id'));
			
			returnPR = setupHomeController.addStudentsToGroup();
			system.assertEquals(TestDataSetupUtil_v2.activeSetup.id,returnPR.getParameters().get('setupId'));
			system.assertEquals('testid',returnPR.getParameters().get('id'));
			system.assertEquals('true',returnPR.getParameters().get('add'));
			
			setupHomeController.setReenrollmentRate();
		Test.stopTest();
	}

}