objects/HoldingObj__c.object
<CustomObject>
    <description>Generic holding object for importing Students/Staff records from a .CSV file.</description>
    <fields>
        <fullName>Class_Id__c</fullName>
        <label>Section Name</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Class_Name__c</fullName>
        <label>Class Name</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Grade_Level__c</fullName>
        <label>Grade</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Reference_Id__c</fullName>
        <description>Unique key for Holding Record</description>
        <externalId>true</externalId>
        <label>Reference Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Room__c</fullName>
        <label>Room</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>School_Dbn__c</fullName>
        <label>School Dbn</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>School_Year__c</fullName>
        <label>School Year</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Staff_Code__c</fullName>
        <label>Staff Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Staff_ID__c</fullName>
        <label>Staff ID</label>
        <length>24</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Student_Id__c</fullName>
        <label>Student Id</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>HoldingObj</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>HoldingObjs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Room__c.object
<CustomObject>
    <fields>
        <fullName>Reference_Id__c</fullName>
        <externalId>true</externalId>
        <label>Reference Id</label>
        <length>200</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Room</label>
    <nameField>
        <label>Room Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Rooms</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Time_Element__c.object
<CustomObject>
    <fields>
        <fullName>Parent_Time_Element__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Parent Time Element</label>
        <referenceTo>Time_Element__c</referenceTo>
        <relationshipLabel>Children Time Elements</relationshipLabel>
        <relationshipName>Time</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Reference_Id__c</fullName>
        <externalId>true</externalId>
        <label>Reference Id</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>Time</label>
    <nameField>
        <displayFormat>T-{000000}</displayFormat>
        <label>Time Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Time</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/ImportUtils.cls
public with sharing class ImportUtils {


	public static Time_Element__c yearTe {get;set;}
	
	public static Time_Element__c getYearTe (String ReportingPeriodId){ 
		if (yearTe==null){
			yearTe = [select parent_time_element__r.parent_time_element__c from Time_Element__c where id =:ReportingPeriodId];
		}
		return yearTe;
	} 
	
	public static String normalizeGrade(String grade) {
		if ((grade != null) && 
				(grade.equalsIgnoreCase('0k') || 
						grade.equalsIgnoreCase('k') || 
						grade.equalsIgnoreCase('0') || 
						grade.equalsIgnoreCase('kindergarden'))) {
    		return 'K'; //Updated per Schoolforce we want K not 0
    	}
		return stripLeadingZeroes(grade);
	}
	
	public static String createClassSectionKey(HoldingObj__c holder) {
		//if (holder.Reference_Id__c!=null) {
			//return holder.Reference_Id__c;createClassSectionKey
		//}
		if (isNull(holder.Class_Id__c) || isNull(holder.School_Dbn__c) || isNull(holder.School_Year__c)) {
			return null;
		}
		return holder.Class_Id__c + holder.School_Dbn__c + holder.School_Year__c;
	}

	
	public static String createStudentSectionKey(HoldingObj__c holder) {
		return holder.Student_Id__c +'_'+ holder.Class_Id__c +'_'+ holder.School_Dbn__c +'_'+ holder.School_Year__c;
	}
	public static String createStudentSchoolGradeKey(HoldingObj__c holder) {
		return holder.Student_Id__c +'_' + holder.School_Dbn__c+'_'+ImportUtils.normalizeGrade(holder.Grade_Level__c);
	}
	
	public static String createStudentSchoolYearKey(HoldingObj__c holder, boolean isSummerSchool) {
		if (isNull(holder.Student_Id__c) || isNull(holder.School_Year__c)) {
			return null;
		}
		return holder.Student_Id__c +'_' +holder.School_Year__c +((isSummerSchool)?'SS':'');
	}
	
	public static String createStaffSectionKey(HoldingObj__c holder) {
		if (isNull(holder.Staff_Id__c) || isNull(holder.Class_Id__c) || isNull(holder.School_Year__c)) {
			return null;
		}
		return stripLeadingZeroes(holder.Staff_Id__c) +'_' + holder.Class_Id__c+'_'+holder.School_Year__c;
	}
	
	public static String createStaffSchoolKey(HoldingObj__c holder) {
		if (isNull(holder.Staff_Id__c) || isNull(holder.School_Dbn__c) ) {
			return null;
		}
		return stripLeadingZeroes(holder.Staff_Id__c) +'_' + holder.School_Dbn__c ;
	}
	
	public static String createStaffSchoolRoleKey(HoldingObj__c holder) {
		if (isNull(holder.Staff_Id__c) || isNull(holder.School_Dbn__c) || isNull(holder.Staff_Code__c)) {
			return null;
		}
		return stripLeadingZeroes(holder.Staff_Id__c) +'_'  + holder.School_Dbn__c  +'_' + holder.Staff_Code__c;
	}
	
	public static String createRoomKey(HoldingObj__c holder){
		if (isNull(holder.School_Dbn__c) || isNull(holder.Room__c)) {
			return null;
		}
		return holder.School_Dbn__c  +'-' + holder.Room__c;
	}
	public static String createScheduleGroupKey (HoldingObj__c holder){
			if (isNull(holder.Class_Name__c) || isNull(holder.School_Dbn__c) || isNull(holder.School_Year__c)) {
			return null;
		}
		return holder.Class_Name__c + holder.School_Dbn__c + holder.School_Year__c;
	}
	

	
	public static Boolean isNull(String value) {
		return StringUtils.isBlank(value) || (value.equalsIgnoreCase('null'));
	}
	
	public static Boolean isTrue(String value) {
		return (!StringUtils.isBlank(value) &&
				(value.equalsIgnoreCase('y') || value.equalsIgnoreCase('yes') ||
						value.equalsIgnoreCase('1') || value.equalsIgnoreCase('t') ||
						value.equalsIgnoreCase('true')));
	}
	
	public static String stripLeadingZeroes(String value) {
		if (StringUtils.isBlank(value) || !value.startsWith('0') || (value == '0')) {
			return value;
		}
		return stripLeadingZeroes(value.substring(1));
	}
	
	public static String createScheduledSectionKey(String schoolId,String grpId,String courseId,String rpId,String schedTempId) {
		if (StringUtils.isBlank(schoolId) || StringUtils.isBlank(grpId) || StringUtils.isBlank(courseId) || StringUtils.isBlank(rpId) || StringUtils.isBlank(schedTempId)) {
			return null;
		}
		return schoolId+'-'+grpId+'-'+courseId+'-'+rpId+'-'+schedTempId;
	}
	
	public static String createSectionReferenceKey(String schoolId,String grpId,String courseId,String rpId) {
		if (StringUtils.isBlank(schoolId) || StringUtils.isBlank(grpId) || StringUtils.isBlank(courseId) || StringUtils.isBlank(rpId)) {
			return null;
		}
		return schoolId+'-'+grpId+'-'+courseId+'-'+rpId;
	}
	
}