objects/HW_Tracker__c.object
<CustomObject>
    <fields>
        <fullName>Student__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Student</label>
        <referenceTo>Student__c</referenceTo>
        <relationshipName>Homework_Tracking</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Homework</label>
    <nameField>
        <displayFormat>HT-{000000}</displayFormat>
        <label>HT ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Homework</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Student__c.object
<CustomObject>
    <fields>
        <fullName>Student__c</fullName>
        <inlineHelpText>Displays the student&apos;s middle name.</inlineHelpText>
        <label>Student Middle Name</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>of_Assigned_Homework__c</fullName>
        <defaultValue>0</defaultValue>
        <inlineHelpText>Displays the number of homework assignments assigned to the student if your school uses the Homework module.</inlineHelpText>
        <label># of Assigned Homework</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>of_Completed_Homework__c</fullName>
        <defaultValue>0</defaultValue>
        <inlineHelpText>Displays the number of homework assignments completed by the student if your school uses the Homework module.</inlineHelpText>
        <label># of Completed Homework</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>of_Late_Homework__c</fullName>
        <description>System generated tally of number of late homework assignments for the particular student</description>
        <inlineHelpText>Displays the student&apos;s total number of late homework assignments if your school uses the Homework module.</inlineHelpText>
        <label># of Late Homework</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>of_Missing_Homework__c</fullName>
        <description>System generated tally of number of missing homework assignments for the particular student</description>
        <inlineHelpText>Displays the student&apos;s total number of missing homework assignments if your school uses the Homework module.</inlineHelpText>
        <label># of Missing Homework</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Student</label>
    <nameField>
        <label>Student Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Students</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/Homework_ManageHomework.cls
public class Homework_ManageHomework {
	public static void updatestats (Map<Id, HW_Tracker__c> newmap) {
		Set<Id> studentIDs = new Set<Id>();
		//we neede the ids of the stupdens we neede to push homework updates to
		for (HW_Tracker__c h: newmap.values()) {
			studentIDs.add(h.Student__c);
		}

		Map<Id, Student__c> studentMap = new Map<Id, Student__c> ();
		for(AggregateResult ar : Homework_SoqlUtils.getHWStatInfo(studentIDs)){
			Student__c std;
			Id sid = (Id)ar.get('s');
			if (studentMap.containskey(sid) ) {
				std = studentMap.get(sid); 
			} else {
				std = new Student__c (Id = sid
									  ,of_Completed_Homework__c = 0 
									  ,of_Late_Homework__c = 0
									  ,of_Missing_Homework__c = 0
									  ,of_Assigned_Homework__c = 0);
			}
			
			String pvc = (String)ar.get('pv'); 
			if (pvc.equals('Complete')){
				std.of_Completed_Homework__c = (Decimal)ar.get('scount');
				std.of_Assigned_Homework__c += (Decimal)ar.get('scount');
			} else if (pvc.equals('Incomplete')){
				std.of_Missing_Homework__c = (Decimal)ar.get('scount');
				std.of_Assigned_Homework__c += (Decimal)ar.get('scount');
			} else if (pvc.equals('Late')){
				std.of_Late_Homework__c = (Decimal)ar.get('scount');
				std.of_Assigned_Homework__c += (Decimal)ar.get('scount');
			} else if (!pvc.equals('Exempt') || !pvc.equals('sf_absent') ) {
				std.of_Assigned_Homework__c += (Decimal)ar.get('scount');
			}
			studentMap.put(sid, std);
		}
		
		update studentMap.values();
	}
}