objects/HW_Tracker__c.object
<CustomObject>
    <fields>
        <fullName>Due_Date__c</fullName>
        <label>Due Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Picklist_Value__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Status</label>
        <referenceTo>Picklist_Value__c</referenceTo>
        <relationshipName>Homework_Tracking</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Student__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Student</label>
        <referenceTo>Student__c</referenceTo>
        <relationshipName>Homework_Tracking</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Homework</label>
    <nameField>
        <displayFormat>HT-{000000}</displayFormat>
        <label>HT ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Homework</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Picklist_Value__c.object
<CustomObject>
    <fields>
        <fullName>Category__c</fullName>
        <label>Category</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Type__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Absent</fullName>
                </value>
                <value>
                    <fullName>Reporting Period</fullName>
                </value>
                <value>
                    <fullName>Custom Period</fullName>
                </value>
                <value>
                    <fullName>In School Suspension</fullName>
                </value>
                <value>
                    <fullName>Out of School Suspension</fullName>
                </value>
                <value>
                    <fullName>Present</fullName>
                </value>
                <value>
                    <fullName>Partial</fullName>
                </value>
                <value>
                    <fullName>Tardy</fullName>
                </value>
                <value>
                    <fullName>Excused Absence</fullName>
                </value>
                <value>
                    <fullName>Unexcused Absence</fullName>
                </value>
                <value>
                    <fullName>Excused Tardy</fullName>
                </value>
                <value>
                    <fullName>Unexcused Tardy</fullName>
                </value>
                <value>
                    <fullName>Missing</fullName>
                </value>
                <value>
                    <fullName>Exempt</fullName>
                </value>
                <value>
                    <fullName>Complete</fullName>
                </value>
                <value>
                    <fullName>Late</fullName>
                </value>
                <value>
                    <fullName>Incomplete</fullName>
                </value>
                <value>
                    <fullName>Default</fullName>
                </value>
                <value>
                    <fullName>Standards</fullName>
                </value>
                <value>
                    <fullName>Credit/No Credit</fullName>
                </value>
                <value>
                    <fullName>Points</fullName>
                </value>
                <value>
                    <fullName>0-100</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Order__c</fullName>
        <defaultValue>99</defaultValue>
        <label>Order</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Set_as_Default__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Set this check box for the default value for Attendance (usually Present)</inlineHelpText>
        <label>Set as Default</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Setup__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Setup</label>
        <referenceTo>Setup__c</referenceTo>
        <relationshipLabel>Picklist Values</relationshipLabel>
        <relationshipName>Picklist_Values</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Attendance</fullName>
                </value>
                <value>
                    <fullName>Time</fullName>
                </value>
                <value>
                    <fullName>Assignment</fullName>
                </value>
                <value>
                    <fullName>Grade Scale</fullName>
                </value>
                <value>
                    <fullName>Homework</fullName>
                </value>
                <value>
                    <fullName>Behavior Type</fullName>
                </value>
                <value>
                    <fullName>Behavior Consequence</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Picklist Value</label>
    <nameField>
        <label>Display Value</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Picklist Values</pluralLabel>
    <recordTypes>
        <fullName>Homework</fullName>
        <active>true</active>
        <description>Record Type for Homework Status Values</description>
        <label>Homework</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Section__c.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Check this box if the section is a currently active section</description>
        <inlineHelpText>Check this box if the section is a currently active section</inlineHelpText>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Has_Homework__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Check this box if this section will have homework and should be included on the homework tracker list</description>
        <inlineHelpText>Select if you want to make this section available in the Homework module.</inlineHelpText>
        <label>Has Homework</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Section__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Recursive lookup for groups</description>
        <label>Section</label>
        <referenceTo>Section__c</referenceTo>
        <relationshipLabel>Groups in Section</relationshipLabel>
        <relationshipName>Sections1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <description>Section or Standard Group or Custom Group</description>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Section</fullName>
                </value>
                <value>
                    <fullName>Standard Group</fullName>
                </value>
                <value>
                    <fullName>Custom Group</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>of_Late_Homework__c</fullName>
        <description>System generated tally of number of late homework assignments for the particular section</description>
        <inlineHelpText>System generated tally of number of late homework assignments for the particular section</inlineHelpText>
        <label># of Late Homework</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>of_Missing_Homework__c</fullName>
        <description>System generated tally of number of missing homework assignments for the particular section</description>
        <inlineHelpText>System generated tally of number of missing homework assignments for the particular section</inlineHelpText>
        <label># of Missing Homework</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Section</label>
    <nameField>
        <label>Section Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sections</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Setup__c.object
<CustomObject>
    <description>This object is used to setup Schoolforce and is referenced in multiple pieces of code.  There should be one setup object per school.</description>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Is this school setup active for this school year?</inlineHelpText>
        <label>Active?</label>
        <type>Checkbox</type>
    </fields>
    <label>Setup</label>
    <nameField>
        <displayFormat>S-{0}</displayFormat>
        <label>Setup ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Setup</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/Student__c.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>true</defaultValue>
        <inlineHelpText>Indicates whether or not this Student record is active. If checked, then this is the current Student record. If unchecked, this is an old Student record.</inlineHelpText>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Section__c</fullName>
        <inlineHelpText>Displays the student&apos;s current homeroom name or room number. This field can be used for reporting purposes.</inlineHelpText>
        <label>Current Homeroom</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Setup__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Displays the Setup record associated to this Student record. The Setup record defines the settings for the school in a specific school year.</inlineHelpText>
        <label>Setup</label>
        <referenceTo>Setup__c</referenceTo>
        <relationshipLabel>Students</relationshipLabel>
        <relationshipName>Students</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Student__c</fullName>
        <inlineHelpText>Displays the student&apos;s middle name.</inlineHelpText>
        <label>Student Middle Name</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>of_Assigned_Homework__c</fullName>
        <defaultValue>0</defaultValue>
        <inlineHelpText>Displays the number of homework assignments assigned to the student if your school uses the Homework module.</inlineHelpText>
        <label># of Assigned Homework</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>of_Completed_Homework__c</fullName>
        <defaultValue>0</defaultValue>
        <inlineHelpText>Displays the number of homework assignments completed by the student if your school uses the Homework module.</inlineHelpText>
        <label># of Completed Homework</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>of_Late_Homework__c</fullName>
        <description>System generated tally of number of late homework assignments for the particular student</description>
        <inlineHelpText>Displays the student&apos;s total number of late homework assignments if your school uses the Homework module.</inlineHelpText>
        <label># of Late Homework</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>of_Missing_Homework__c</fullName>
        <description>System generated tally of number of missing homework assignments for the particular student</description>
        <inlineHelpText>Displays the student&apos;s total number of missing homework assignments if your school uses the Homework module.</inlineHelpText>
        <label># of Missing Homework</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Student</label>
    <nameField>
        <label>Student Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Students</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/Test_Homework.cls
@isTest
private class Test_Homework{
	
	private static testmethod void testConstructor(){
		testDataSetupUtil_v2 testUtil = new testDataSetupUtil_v2();
		testDataSetupUtil_v2.setUPCoreData(5);
		testDataSetupUtil_v2.setUPStaffData(5);
        testDataSetupUtil_v2.setUPStudentData(5);
		testDataSetupUtil_v2.setupSessiondata();
       	//testDataSetupUtil_v2.sessionsList = testDataSetupUtil_v2.getSessions(5, testDataSetupUtil_v2.period,testDataSetupUtil_v2.sectionsList[1].id,2);
        List<Picklist_Value__c> hwStatus = testDataSetupUtil_v2.createHomeworkPicklistValues();
        
        
        Date testdate = testDataSetupUtil_v2.semester.date_start_Date__c.addDays(1);
        
        test.startTest();
			system.runAs(testDataSetupUtil_v2.staffUsersList[1]){
	            Homework_HomeworkController controller = new Homework_HomeworkController();
                controller.dueDate.Due_Date__c = testdate;
                
                system.assertEquals(false, controller.bFatalError);
				system.assertEquals(4, controller.statusList.size());
            }
        test.stopTest();
	}
	
	private static testmethod void testGetData(){
		testDataSetupUtil_v2 testUtil = new testDataSetupUtil_v2();
		testDataSetupUtil_v2.setUPCoreData(5);
		testDataSetupUtil_v2.setUPStaffData(5);
        testDataSetupUtil_v2.setUPStudentData(5);
		testDataSetupUtil_v2.setupSessiondata();
       	//testDataSetupUtil_v2.sessionsList = testDataSetupUtil_v2.getSessions(5, testDataSetupUtil_v2.period,testDataSetupUtil_v2.sectionsList[1].id,2);
        List<Picklist_Value__c> hwStatus = testDataSetupUtil_v2.createHomeworkPicklistValues();
        
        
        Date testdate = testDataSetupUtil_v2.semester.date_start_Date__c.addDays(1);
        
        test.startTest();
			system.runAs(testDataSetupUtil_v2.staffUsersList[1]){
	            Homework_HomeworkController controller = new Homework_HomeworkController();
                controller.dueDate.Due_Date__c = testdate;
                
                system.assert(testDataSetupUtil_v2.sectionsList.size() >= 2);
                controller.section = testDataSetupUtil_v2.sectionsList[1].id;
                
                controller.gethwdata();
			}
		test.stopTest();
	}
	
	private static testmethod void testSave(){
		testDataSetupUtil_v2 testUtil = new testDataSetupUtil_v2();
		testDataSetupUtil_v2.setUPCoreData(5);
		testDataSetupUtil_v2.setUPStaffData(5);
        testDataSetupUtil_v2.setUPStudentData(5);
		testDataSetupUtil_v2.setupSessiondata();
       	//testDataSetupUtil_v2.sessionsList = testDataSetupUtil_v2.getSessions(5, testDataSetupUtil_v2.period,testDataSetupUtil_v2.sectionsList[1].id,2);
        List<Picklist_Value__c> hwStatus = testDataSetupUtil_v2.createHomeworkPicklistValues();
        
        
        Date testdate = testDataSetupUtil_v2.semester.date_start_Date__c.addDays(1);
        
        test.startTest();
			system.runAs(testDataSetupUtil_v2.staffUsersList[1]){
	            Homework_HomeworkController controller = new Homework_HomeworkController();
                controller.dueDate.Due_Date__c = testdate;
                
                system.assert(testDataSetupUtil_v2.sectionsList.size() >= 2);
                controller.section = testDataSetupUtil_v2.sectionsList[1].id;
                
                controller.gethwdata();
                //test adding a new homework
                controller.newsectionId = testDataSetupUtil_v2.sessionsList[0].id;
                controller.newhomework();
                
                
                controller.commentSave();
                controller.saverecords();
			}
		test.stopTest();
	}
	
	private static testmethod void testMangageHomework(){
		testDataSetupUtil_v2.setUPCoreData(5);
        testDataSetupUtil_v2.setUPStaffData(5);
        testDataSetupUtil_v2.setUPStudentData(5);
		testDataSetupUtil_v2.setupSessiondata();
        //testDataSetupUtil_v2.createSessions(5, testDataSetupUtil_v2.period,testDataSetupUtil_v2.sectionsList[1].id);
        List<Picklist_Value__c> hwStatus = testDataSetupUtil_v2.createHomeworkPicklistValues();
        Date testdate = testDataSetupUtil_v2.semester.date_start_Date__c.addDays(1);
        
        test.startTest();
			system.runAs(testDataSetupUtil_v2.staffUsersList[1]){
				List<HW_Tracker__c> hwList = new List<HW_Tracker__c>();
	            hwList.add(new HW_Tracker__c(Student__c = testDataSetupUtil_v2.studentsList[0].id,
	            							Picklist_Value__c = hwStatus[1].id));
				hwList.add(new HW_Tracker__c(Student__c = testDataSetupUtil_v2.studentsList[0].id,
	            							Picklist_Value__c = hwStatus[2].id));
	          	hwList.add(new HW_Tracker__c(Student__c = testDataSetupUtil_v2.studentsList[0].id,
	            							Picklist_Value__c = hwStatus[3].id));
	            									
                insert hwList;
                
                Student__c student = [select id, of_Completed_Homework__c, of_Assigned_Homework__c, of_Missing_Homework__c,
                							of_Late_Homework__c
                						From Student__c
                						where id =: testDataSetupUtil_v2.studentsList[0].id];
                system.assertEquals(0, student.of_Completed_Homework__c);
                system.assertEquals(3, student.of_Assigned_Homework__c);
                system.assertEquals(1, student.of_Missing_Homework__c);
                system.assertEquals(1, student.of_Late_Homework__c);
			}
		test.stopTest();
	}
	
	static testMethod void test_HomeworkController(){
        testDataSetupUtil_v2.setUPCoreData(5);
        testDataSetupUtil_v2.setUPStaffData(5);
        testDataSetupUtil_v2.setUPStudentData(5);
        
        testDataSetupUtil_v2.setupSessiondata();
        //testDataSetupUtil_v2.createSessions(5, testDataSetupUtil_v2.period,testDataSetupUtil_v2.sectionsList[1].id);
        
        Map <String, Id> rtMap = core_SoqlUtils.getRecordTypesBySobject('Picklist_Value__c'); 
        
        List<Picklist_Value__c> pvl  =  new List<Picklist_Value__c>();
        pvl.add(new Picklist_Value__c(Setup__c = testDataSetupUtil_v2.activeSetUp.id,RecordTypeId = rtMap.get('Homework'),Type__c = 'Homework',Name = 'XXComplete',Category__c = 'Complete',order__c = 92, Set_as_Default__c = TRUE));
        pvl.add(new Picklist_Value__c(Setup__c = testDataSetupUtil_v2.activeSetUp.id,RecordTypeId = rtMap.get('Homework'),Type__c = 'Homework',Name = 'XXMissing',Category__c = 'Missing',order__c = 93));
        pvl.add(new Picklist_Value__c(Setup__c = testDataSetupUtil_v2.activeSetUp.id,RecordTypeId = rtMap.get('Homework'), Type__c = 'Homework',Name = 'XXLate',Category__c = 'Late',order__c = 94));
        pvl.add(new Picklist_Value__c(Setup__c = testDataSetupUtil_v2.activeSetUp.id,RecordTypeId = rtMap.get('Homework'),Type__c = 'Homework',Name = 'XXAbsent',Category__c = 'Absent',order__c = 95));
          
        insert pvl;
        
        
        
        test.startTest();
            Date testdate = testDataSetupUtil_v2.semester.date_start_Date__c.addDays(1);
            
            system.runAs(testDataSetupUtil_v2.staffUsersList[1]){
        
	            PageReference p = Page.Homework;
	            test.setCurrentPage(p);
	         
	            Homework_HomeworkController controller = new Homework_HomeworkController ();
                controller.dueDate.Due_Date__c = testdate;
                
                section__c testsec = new section__c (Id = testDataSetupUtil_v2.sectionsList[1].Id, active__c = TRUE, has_homework__c = true);
                update testsec;
                
                controller.section = testDataSetupUtil_v2.sectionsList[1].id;
                
                controller.newsectionid = testDataSetupUtil_v2.sectionsList[1].id;
                controller.newhomework();
                controller.pagerefstudentId = testDataSetupUtil_v2.studentsList[0].Id;

                Set<ID> hwTrackIds = new Set<ID>();
                controller.saverecords();
                
                Map<id, HW_Tracker__c> hwTrackerList = new Map<id, HW_Tracker__c>([select id, PickList_Value__c from HW_Tracker__c where id IN :hwTrackIds]);
            }
        Test.stopTest();
    }
}