objects/Indicator_Area__c.object
<CustomObject>
    <description>This object is part of the Interventions app. Indicator Area defines a high-level intervention focus area (e.g., Behavior, Attendance, English Language Arts). Students are assigned to Indicator Areas in order to schedule them in Intervention Programs and Sections.</description>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>true</defaultValue>
        <inlineHelpText>Indicates whether or not this indicator area is available to assign to students on the Add Students to Indicator Areas screen. If you uncheck this field, SchoolForce deactivates any associated Program, Staff/Section, and Student/Section records.</inlineHelpText>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <label>Indicator Area</label>
    <nameField>
        <label>Indicator Area</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Indicator Areas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Indicator_Area_Student__c.object
<CustomObject>
    <description>The Indicator Area/Student object is a joiner object that associates an Indicator Area and a Student.</description>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>true</defaultValue>
        <inlineHelpText>Is the Indicator Area associated to this Student active? If this box is unchecked then the Student no longer requires intervention in this area.</inlineHelpText>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>IA_Effective_Date__c</fullName>
        <label>IA Effective Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Indicator_Area__c</fullName>
        <inlineHelpText>This field joins the Indicator Area/Student record to the correct Indicator Area</inlineHelpText>
        <label>Indicator Area</label>
        <referenceTo>Indicator_Area__c</referenceTo>
        <relationshipLabel>Indicator Area/Student</relationshipLabel>
        <relationshipName>Indicator_Area_Student</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Reference_ID__c</fullName>
        <caseSensitive>true</caseSensitive>
        <externalId>true</externalId>
        <inlineHelpText>System generated reference number that includes the Student Id and the Indicator ID. This field should not be modified.</inlineHelpText>
        <label>Reference ID</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Student__c</fullName>
        <inlineHelpText>This field joins the Indicator Area/Student record to the correct Student</inlineHelpText>
        <label>Student</label>
        <referenceTo>Student__c</referenceTo>
        <relationshipLabel>Indicator Area/Student</relationshipLabel>
        <relationshipName>Indicator_Area_Student</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Indicator Area/Student</label>
    <nameField>
        <displayFormat>IA/S -{000}</displayFormat>
        <label>IA/Student ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Indicator Area/Student</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Program__c.object
<CustomObject>
    <description>Program is an Intervention object. Intervention Programs are aligned with Indicator Areas and are a high level set of activities with defined dosage goals. Each Program has its own frequency, target dosage, and recommended time per session. An example Program is one-on-one reading.</description>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>If this box is checked then the Program is currently available for use.</inlineHelpText>
        <label>Active?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Indicator_Area__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>You must select an Indicator Area that aligns with this Program.</inlineHelpText>
        <label>Indicator Area</label>
        <referenceTo>Indicator_Area__c</referenceTo>
        <relationshipLabel>Programs</relationshipLabel>
        <relationshipName>Programs</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Program</label>
    <nameField>
        <label>Program Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/Section__c.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Check this box if the section is a currently active section</description>
        <inlineHelpText>Check this box if the section is a currently active section</inlineHelpText>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Indicator_Area__c</fullName>
        <formula>Program__r.Indicator_Area__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>What Indicator Area is this Program addressing? This field cannot be modified here.</inlineHelpText>
        <label>Indicator Area</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Program__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>What intervention Program is this Intervention Section for?</inlineHelpText>
        <label>Program</label>
        <referenceTo>Program__c</referenceTo>
        <relationshipLabel>Sections</relationshipLabel>
        <relationshipName>Sections</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Reference_Id__c</fullName>
        <externalId>true</externalId>
        <label>Reference Id</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Section__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Recursive lookup for groups</description>
        <label>Section</label>
        <referenceTo>Section__c</referenceTo>
        <relationshipLabel>Groups in Section</relationshipLabel>
        <relationshipName>Sections1</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Section</label>
    <nameField>
        <label>Section Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sections</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Student__c.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>true</defaultValue>
        <inlineHelpText>Indicates whether or not this Student record is active. If checked, then this is the current Student record. If unchecked, this is an old Student record.</inlineHelpText>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Entry_Date__c</fullName>
        <inlineHelpText>Displays the student&apos;s first day of school in the current school year.</inlineHelpText>
        <label>Entry Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Expiration_Date__c</fullName>
        <inlineHelpText>Do not use this field; it is no longer used by SchoolForce.</inlineHelpText>
        <label>Expiration Date*Retired*</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Reference_Id__c</fullName>
        <externalId>true</externalId>
        <inlineHelpText>Displays the Salesforce ID for this Student record. Do not modify this field.</inlineHelpText>
        <label>Reference Id</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Section__c</fullName>
        <inlineHelpText>Displays the student&apos;s current homeroom name or room number. This field can be used for reporting purposes.</inlineHelpText>
        <label>Current Homeroom</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Student__c</fullName>
        <inlineHelpText>Displays the student&apos;s middle name.</inlineHelpText>
        <label>Student Middle Name</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <label>Student</label>
    <nameField>
        <label>Student Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Students</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/ModalAddIaStudentsCtrl.cls
/**
 * Created by TarasTorubka on 24.09.2020.
 */

public with sharing class ModalAddIaStudentsCtrl {
    public static final String IA_NONSPECIFIC 	= 				'Non-specific IA';
    public Date                     dtIA                        {get;set;}
    public Section__c               section                     {get;set;}
    public List<StudentInfoWrapper> studentSections				{get;set;}
    public Map<String, Indicator_Area_Student__c>   changesIAS;


    public void startAddIAToStudents(){
        Id cidIA = section.Program__r.Indicator_Area__r.Id;
        for(StudentInfoWrapper siw: studentSections){
            if(siw.areaIDs.containsKey(cidIA)) {
                siw.dtIA = siw.areaIDs.get(cidIA).IA_Effective_Date__c;
            }
        }
    }

    public void saveIAToStudents(){
        List<String> errorMessages = new List<String>();
        changesIAS = new Map<String, Indicator_Area_Student__c>();

        List<StudentInfoWrapper> lstStudentSections = new List<StudentInfoWrapper>();
        for(StudentInfoWrapper sew: studentSections){
            if(sew.selected){
                lstStudentSections.add(sew);
                sew.dtIA = dtIA;
                if(sew.student.Entry_Date__c > dtIA || sew.student.Expiration_Date__c < dtIA){
                    errorMessages.add('Student '+sew.name+' should have the IA Effective Date in the range of '+(sew.student.Entry_Date__c!=null?sew.student.Entry_Date__c.format():'-')+' to '+(sew.student.Expiration_Date__c!=null?sew.student.Expiration_Date__c.format():'-')+'.');
                }
                if((sew.studentSection.Intervention_Enrollment_Start_Date__c != null && sew.studentSection.Intervention_Enrollment_Start_Date__c.date() > dtIA) || (sew.studentSection.Enrollment_End_Date__c != null && sew.studentSection.Enrollment_End_Date__c.date() < dtIA)) {
                    errorMessages.add('Student '+sew.name+' should have the IA Effective Date in the range of Intervention Start and Exit dates');
                }
            }
        }

        if(dtIA == null) {
            CyUtil.errorMessage('Please select an IA Effective Date.'); return;
        }
        if(lstStudentSections.isEmpty()){
            CyUtil.errorMessage('Please select a student to Indicator Area.'); return;
        }
        if(String.isBlank(section.Program__r.Indicator_Area__r.Id)){
            CyUtil.errorMessage('Current section has not a Indicator Area.'); return;
        }
        if(section.Program__r.Indicator_Area__r.Name == IA_NONSPECIFIC){
            CyUtil.errorMessage('Non-Specific IA cannot be assigned.'); return;
        }

        Indicator_Area__c curIA = section.Program__r.Indicator_Area__r;
        for(StudentInfoWrapper s: lstStudentSections){
            Indicator_Area_Student__c IA_S = s.areaIds.get(curIA.Id);

            if(IA_S == null){
                IA_S = new Indicator_Area_Student__c();
                IA_S.Indicator_Area__c = curIA.Id;
                IA_S.Indicator_Area__r = curIA;
                IA_S.Student__c = s.studentSection.Student__c;
                IA_S.Student__r = s.student;
                IA_S.Reference_ID__c = s.student.Id+'_'+curIA.Id;
                IA_S.Active__c = true;
                s.addArea(IA_S);
            }

            IA_S.Active__c = true;
            IA_S.IA_Effective_Date__c = dtIA;
            if(!changesIAS.containsKey(IA_S.Reference_ID__c)){
                changesIAS.put(IA_S.Reference_ID__c, IA_S);
            }
            s.refreshIndicatorAreaDisplay();
        }

        if(!changesIAS.isEmpty() && errorMessages.isEmpty()){
            errorMessages.addAll(saveChangesIA());
        }

        if(errorMessages.isEmpty()){
            CYUtil.successMessage('Your changes have been saved.');
        }else{
            CYUtil.errorMessage(String.join(errorMessages, '<br/>')+'<br/>Please verify that your changes have been saved.');
        }
    }

    public List<String> saveChangesIA(){
        List<Database.UpsertResult> results = Database.upsert(changesIAS.values(), Indicator_Area_Student__c.Reference_ID__c.getDescribe().getSObjectField(),false);
        List<String> errorMessages = new List<String>();
        for(integer i=0; i<results.size(); i++){
            List<Database.Error> errors = results[i].getErrors();
            for(Database.Error er : errors){
                errorMessages.add('For student '+changesIAS.values()[i].Student__r.Name+'. '+er.getMessage()+'.');
            }
        }
        changesIAS = new Map<String, Indicator_Area_Student__c>();

        return errorMessages;
    }
}