objects/Indicator_Area__c.object
<CustomObject>
    <description>This object is part of the Interventions app. Indicator Area defines a high-level intervention focus area (e.g., Behavior, Attendance, English Language Arts). Students are assigned to Indicator Areas in order to schedule them in Intervention Programs and Sections.</description>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>true</defaultValue>
        <inlineHelpText>Indicates whether or not this indicator area is available to assign to students on the Add Students to Indicator Areas screen. If you uncheck this field, SchoolForce deactivates any associated Program, Staff/Section, and Student/Section records.</inlineHelpText>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <label>Indicator Area</label>
    <nameField>
        <label>Indicator Area</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Indicator Areas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/Test_IndicatorAreaTrigger.cls
@isTest
private class Test_IndicatorAreaTrigger {
	
	@isTest static void test_method_one() {
		TestDataUtil.setupData(1);
		Indicator_Area__c ia = TestDataUtil.createIndicatorAreas(1)[0];
		insert ia;

		Test.startTest();
			ia.Active__c = false;
			update ia;
		Test.stopTest();

		ia = [select id, Active__c from Indicator_Area__c where ID =: ia.id];
		system.assertEquals(false, ia.Active__c);
	}
}