objects/Indicator_Area__c.object
<CustomObject>
    <description>This object is part of the Interventions app. Indicator Area defines a high-level intervention focus area (e.g., Behavior, Attendance, English Language Arts). Students are assigned to Indicator Areas in order to schedule them in Intervention Programs and Sections.</description>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>true</defaultValue>
        <inlineHelpText>Indicates whether or not this indicator area is available to assign to students on the Add Students to Indicator Areas screen. If you uncheck this field, SchoolForce deactivates any associated Program, Staff/Section, and Student/Section records.</inlineHelpText>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <label>Indicator Area</label>
    <nameField>
        <label>Indicator Area</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Indicator Areas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Indicator_Area_Student__c.object
<CustomObject>
    <description>The Indicator Area/Student object is a joiner object that associates an Indicator Area and a Student.</description>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>true</defaultValue>
        <inlineHelpText>Is the Indicator Area associated to this Student active? If this box is unchecked then the Student no longer requires intervention in this area.</inlineHelpText>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>IA_Effective_Date__c</fullName>
        <label>IA Effective Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Indicator_Area__c</fullName>
        <inlineHelpText>This field joins the Indicator Area/Student record to the correct Indicator Area</inlineHelpText>
        <label>Indicator Area</label>
        <referenceTo>Indicator_Area__c</referenceTo>
        <relationshipLabel>Indicator Area/Student</relationshipLabel>
        <relationshipName>Indicator_Area_Student</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Student__c</fullName>
        <inlineHelpText>This field joins the Indicator Area/Student record to the correct Student</inlineHelpText>
        <label>Student</label>
        <referenceTo>Student__c</referenceTo>
        <relationshipLabel>Indicator Area/Student</relationshipLabel>
        <relationshipName>Indicator_Area_Student</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Indicator Area/Student</label>
    <nameField>
        <displayFormat>IA/S -{000}</displayFormat>
        <label>IA/Student ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Indicator Area/Student</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Program__c.object
<CustomObject>
    <description>Program is an Intervention object. Intervention Programs are aligned with Indicator Areas and are a high level set of activities with defined dosage goals. Each Program has its own frequency, target dosage, and recommended time per session. An example Program is one-on-one reading.</description>
    <label>Program</label>
    <nameField>
        <label>Program Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/Section__c.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Check this box if the section is a currently active section</description>
        <inlineHelpText>Check this box if the section is a currently active section</inlineHelpText>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Indicator_Area__c</fullName>
        <formula>Program__r.Indicator_Area__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>What Indicator Area is this Program addressing? This field cannot be modified here.</inlineHelpText>
        <label>Indicator Area</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Program__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>What intervention Program is this Intervention Section for?</inlineHelpText>
        <label>Program</label>
        <referenceTo>Program__c</referenceTo>
        <relationshipLabel>Sections</relationshipLabel>
        <relationshipName>Sections</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Section_Exit_Reason__c</fullName>
        <label>Section Exit Reason</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>SS_Exit_Reason</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Section__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Recursive lookup for groups</description>
        <label>Section</label>
        <referenceTo>Section__c</referenceTo>
        <relationshipLabel>Groups in Section</relationshipLabel>
        <relationshipName>Sections1</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Section</label>
    <nameField>
        <label>Section Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sections</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Student__c.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>true</defaultValue>
        <inlineHelpText>Indicates whether or not this Student record is active. If checked, then this is the current Student record. If unchecked, this is an old Student record.</inlineHelpText>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Section__c</fullName>
        <inlineHelpText>Displays the student&apos;s current homeroom name or room number. This field can be used for reporting purposes.</inlineHelpText>
        <label>Current Homeroom</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Student_First_Name__c</fullName>
        <inlineHelpText>Displays the student&apos;s first name.</inlineHelpText>
        <label>Student First Name</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Student_Last_Name__c</fullName>
        <inlineHelpText>Displays the student&apos;s last name.</inlineHelpText>
        <label>Student Last Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Student__c</fullName>
        <inlineHelpText>Displays the student&apos;s middle name.</inlineHelpText>
        <label>Student Middle Name</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <label>Student</label>
    <nameField>
        <label>Student Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Students</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Student_Section__c.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Program__c</fullName>
        <formula>CASESAFEID(Section__r.Program__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Program</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Section_Exit_Reason__c</fullName>
        <label>Section Exit Reason</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Accidental Enrollment</fullName>
                </value>
                <value>
                    <fullName>School Year ended</fullName>
                </value>
                <value>
                    <fullName>Deactivated by trigger.</fullName>
                </value>
                <value>
                    <fullName>ACM no longer available</fullName>
                </value>
                <value>
                    <fullName>Student no longer available</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Section__c</fullName>
        <label>Section</label>
        <referenceTo>Section__c</referenceTo>
        <relationshipLabel>Student</relationshipLabel>
        <relationshipName>Student_Section</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Student_First_Name__c</fullName>
        <formula>Student__r.Student_First_Name__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Student First Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Student__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Student</label>
        <referenceTo>Student__c</referenceTo>
        <relationshipLabel>Section</relationshipLabel>
        <relationshipName>Student_Section</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Student/Section</label>
    <nameField>
        <displayFormat>SS-{000000}</displayFormat>
        <label>Student/Section ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Student/Section</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

globalValueSets/SS_Exit_Reason.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Accidental Enrollment</fullName>
    </customValue>
    <customValue>
        <fullName>Student no longer available</fullName>
    </customValue>
    <customValue>
        <fullName>School Year ended</fullName>
    </customValue>
    <customValue>
        <fullName>ACM no longer available</fullName>
    </customValue>
    <customValue>
        <fullName>Deactivated by trigger.</fullName>
    </customValue>
    <customValue>
        <fullName>Teacher scheduling change/reassignment</fullName>
        <isActive>false</isActive>
        <label>Teacher scheduling change/reassignment</label>
    </customValue>
    <customValue>
        <fullName>Chronic absenteeism</fullName>
        <isActive>false</isActive>
        <label>Chronic absenteeism</label>
    </customValue>
    <customValue>
        <fullName>Student referred for more intensive services by other personnel</fullName>
        <isActive>false</isActive>
        <label>Student referred for more intensive services by other personnel</label>
    </customValue>
    <customValue>
        <fullName>Transferred to another City Year school</fullName>
        <isActive>false</isActive>
        <label>Transferred to another City Year school</label>
    </customValue>
    <customValue>
        <fullName>Behavior significantly distracts sessions</fullName>
        <isActive>false</isActive>
        <label>Behavior significantly distracts sessions</label>
    </customValue>
    <customValue>
        <fullName>Student scheduling change prevents regular participation</fullName>
        <isActive>false</isActive>
        <label>Student scheduling change prevents regular participation</label>
    </customValue>
    <customValue>
        <fullName>Student met exit criteria</fullName>
        <isActive>false</isActive>
        <label>Student met exit criteria</label>
    </customValue>
    <customValue>
        <fullName>Student completed participation criteria, though should be reenrolled in subsequent section</fullName>
        <isActive>false</isActive>
        <label>Student completed participation criteria, though should be reenrolled in subsequent section</label>
    </customValue>
    <customValue>
        <fullName>Corps member has left the school or service</fullName>
        <isActive>false</isActive>
        <label>Corps member has left the school or service</label>
    </customValue>
    <masterLabel>SS Exit Reason</masterLabel>
</GlobalValueSet>

classes/StudentInfoWrapper.cls
public class StudentInfoWrapper{
	public Student__c student							{get;set;}
	public Student_Section__c studentSection			{get;set;}
	public String name									{get;set;}
	public Boolean selected								{get;set;}
	public Date	dtIA									{get;set;}
	public String indicatorAreaDisplay					{get;set;}
	public String programsIADisplay						{get;set;}
	public List<Indicator_Area_Student__c> indicators 	{get;set;}
	public Map<Id, Indicator_Area_Student__c> areaIDs 	{get;set;}

	public StudentInfoWrapper(Student_Section__c studentSection){
		this.student = studentSection.Student__r == null? new Student__c(): studentSection.Student__r;
		this.studentSection = studentSection;
		this.selected = false;
	}

	public StudentInfoWrapper(Student__c student, Student_Section__c studentSection, Boolean selected){
		this.student = student;
		this.studentSection = studentSection;
		this.selected = selected;
		this.name = student.Student_First_Name__c+' '+student.Student_Last_Name__c;
	}

	public StudentInfoWrapper(Student__c student, Student_Section__c studentSection, List<Indicator_Area_Student__c> indicators){
		this.student = student;
		this.studentSection = studentSection;
		this.selected = false;
		updateStudentInfoWrapper(student, indicators);
	}

	public StudentInfoWrapper(Student__c student, List<Indicator_Area_Student__c> indicators){
		updateStudentInfoWrapper(student, indicators);
	}

	public void updateStudentInfoWrapper(Student__c student, List<Indicator_Area_Student__c> indicators){
		this.student = student;
		this.indicators = indicators;
		this.name = student.Student_First_Name__c+' '+student.Student_Last_Name__c;
		areaIDs = new Map<Id, Indicator_Area_Student__c>();
		for(Indicator_Area_Student__c ia_s : indicators){
			areaIDs.put(ia_s.Indicator_Area__r.id, ia_s);
			//dtIA = (dtIA==null || ia_s.IA_Effective_Date__c > dtIA)? ia_s.IA_Effective_Date__c: dtIA; //show last date
		}
		refreshIndicatorAreaDisplay();
		refreshProgramsIADisplay();
	}

	public void addArea(Indicator_Area_Student__c ia){
		Integer i;
		for(i = 0; i < indicators.size(); ++i ){
			if(indicators.get(i).Indicator_Area__r.name.compareTo(ia.Indicator_Area__r.name)>0){
				break;
			}
		}
		if(i == indicators.size()){
			indicators.add(ia);
		}else{
			indicators.add(i, ia);
		}
		areaIDs.put(ia.Indicator_Area__r.id, ia);
		this.refreshIndicatorAreaDisplay();
	}

	public void refreshIndicatorAreaDisplay(){
		List<String> iaNames = new List<String>();
		Integer iaAmt = indicators.size();
		for(Integer i = 0; i < iaAmt; ++i){
			if(indicators.get(i).Active__c){
				iaNames.add(indicators.get(i).Indicator_Area__r.Name);
			}
		}
		iaNames.sort();
		indicatorAreaDisplay = String.join(iaNames, ', ');
	}

	public void refreshProgramsIADisplay(){
		Set<String> pIANames = new Set<String>();
		for(Student_Section__c ss: student.Student_Section__r){
			if(String.isNotBlank(ss.Section__r.Program__r.Indicator_Area__r.Name)
					&& ss.Section_Exit_Reason__c!='Accidental Enrollment'){
				pIANames.add(ss.Section__r.Program__r.Indicator_Area__r.Name);
			}
		}
		programsIADisplay = String.join(new List<String>(pIANames), ', ');
	}
}