objects/Intervention_Session__c.object
<CustomObject>
    <description>The Intervention Session object captures that an Intervention Section met on a particular day. The outcome of the session is attached to the Intervention Session record.</description>
    <label>Intervention Session</label>
    <nameField>
        <displayFormat>IS-{000000}</displayFormat>
        <label>Inter. Session ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Intervention Sessions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Student__c.object
<CustomObject>
    <fields>
        <fullName>Student__c</fullName>
        <inlineHelpText>Displays the student&apos;s middle name.</inlineHelpText>
        <label>Student Middle Name</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <label>Student</label>
    <nameField>
        <label>Student Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Students</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Student_Section__c.object
<CustomObject>
    <fields>
        <fullName>Student__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Student</label>
        <referenceTo>Student__c</referenceTo>
        <relationshipLabel>Section</relationshipLabel>
        <relationshipName>Student_Section</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Student/Section</label>
    <nameField>
        <displayFormat>SS-{000000}</displayFormat>
        <label>Student/Section ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Student/Section</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/InterventionSessionUtilsTest.cls
@isTest
private class InterventionSessionUtilsTest {
	private static final Integer COUNT = 5;
	private static final Integer AMOUNT = 30;

	@testSetup
	private static void setupData(){
		testDataSetupUtil_v2.setUPCoreData(COUNT);
		testDataSetupUtil_v2.setUPStaffData(COUNT);
		testDataSetupUtil_v2.setUPStudentData(COUNT);
		testDataSetupUtil_v2.setUPProgramData(testDataSetupUtil_v2.sectionsList, testDataSetupUtil_v2.school);
		testDataSetupUtil_v2.setUPExistingSessionResults(AMOUNT);
	}

	@isTest static void validateCountISRTest() {
		List<Student_Section__c> listSS = [SELECT Id FROM Student_Section__c];
		
		String msg = '';
    	Test.startTest();
    		try{
    			delete listSS;
    		}catch(Exception e){
    			msg = e.getMessage();
    		}
    	Test.stopTest();

    	System.assert(msg.contains(System.Label.Validation_Intervention_Session));
	}

	@isTest static void removeISTest() {
		List<Student__c> listS = [SELECT Id FROM Student__c];

		Test.startTest();
		delete listS;
		Test.stopTest();

		List<Intervention_Session__c> listISs = [SELECT Id FROM Intervention_Session__c];
		System.assert(listISs.isEmpty());
	}

}