objects/Intervention_Session__c.object
<CustomObject>
    <description>The Intervention Session object captures that an Intervention Section met on a particular day. The outcome of the session is attached to the Intervention Session record.</description>
    <label>Intervention Session</label>
    <nameField>
        <displayFormat>IS-{000000}</displayFormat>
        <label>Inter. Session ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Intervention Sessions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Intervention_Session_Result__c.object
<CustomObject>
    <description>The Intervention Session Result is an object that captures the outcome of a student&apos;s participation in an Intervention Session. The result includes duration and notes.</description>
    <fields>
        <fullName>Intervention_Session__c</fullName>
        <inlineHelpText>This field connects the Intervention Session Result record to the correct Intervention Session.</inlineHelpText>
        <label>Intervention Session</label>
        <referenceTo>Intervention_Session__c</referenceTo>
        <relationshipLabel>Intervention Session Results</relationshipLabel>
        <relationshipName>Intervention_Session_Results</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Student_Section__c</fullName>
        <inlineHelpText>This field connects the Intervention Session Result record to the correct Student/Section.</inlineHelpText>
        <label>Student/Section</label>
        <referenceTo>Student_Section__c</referenceTo>
        <relationshipLabel>Intervention Session Results</relationshipLabel>
        <relationshipName>Intervention_Session_Results</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Intervention Session Result</label>
    <nameField>
        <displayFormat>ISR-{000000}</displayFormat>
        <label>Time ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Intervention Session Results</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Student_Section__c.object
<CustomObject>
    <label>Student/Section</label>
    <nameField>
        <displayFormat>SS-{000000}</displayFormat>
        <label>Student/Section ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Student/Section</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/InterventionSessionResultTriggerHandler.cls
public with sharing class InterventionSessionResultTriggerHandler {

    public void isBeforeInsert(List<Intervention_Session_Result__c> onBeforeInsertList) {
        isBeforeInsertHelper(onBeforeInsertList);
    }

    private void isBeforeInsertHelper(List<Intervention_Session_Result__c> onBeforeInsertList) {
        Set<Id> intervensionSessionIds = new Set<Id>();
        for (Intervention_Session_Result__c isr : onBeforeInsertList) {
            intervensionSessionIds.add(isr.Intervention_Session__c);
        }
        List<Intervention_Session__c> sessionsWithISR = [SELECT Id, (SELECT Id, Student_Section__c FROM Intervention_Session_Results__r)
                                                        FROM Intervention_Session__c
                                                        WHERE Id IN: intervensionSessionIds];
        Map<Id, Set<Id>> sessionIdtoStudentSections = new Map<Id, Set<Id>>();
        for(Intervention_Session__c session : sessionsWithISR)
        {
            List<Intervention_Session_Result__c> isrs = session.Intervention_Session_Results__r;
            Set<Id> studentSectionIds = new Set<Id>();
            for (Intervention_Session_Result__c isr : isrs) {
                studentSectionIds.add(isr.Student_Section__c);
            }
            sessionIdtoStudentSections.put(session.Id, studentSectionIds);
        }
        checkIntervensionSessionResultDuplicates(onBeforeInsertList, sessionIdtoStudentSections);
    }

    private void checkIntervensionSessionResultDuplicates(
            List<Intervention_Session_Result__c > onBeforeInsertISR,
            Map<Id, Set<Id>> sessionIdtoStudentSections) {

        for (Intervention_Session_Result__c isr : onBeforeInsertISR) {
            Id sessionId = isr.Intervention_Session__c;
            Set<Id> existingStudentSectionsInSession = sessionIdtoStudentSections.get(sessionId);
            System.debug('existingStudentSectionsInSession ' + existingStudentSectionsInSession);
            System.debug('isr.Student_Section__c ' + isr.Student_Section__c);
            if (existingStudentSectionsInSession != null) {
                if (existingStudentSectionsInSession.size() > 0 && existingStudentSectionsInSession.contains(isr.Student_Section__c)) {
                    isr.addError('Record with this student already exists');
                }
            }
        }
    }


}