objects/Intervention_Session__c.object
<CustomObject>
    <description>The Intervention Session object captures that an Intervention Section met on a particular day. The outcome of the session is attached to the Intervention Session record.</description>
    <fields>
        <fullName>Section__c</fullName>
        <inlineHelpText>This field connects the Intervention Session record to the correct intervention Section.</inlineHelpText>
        <label>Section</label>
        <referenceTo>Section__c</referenceTo>
        <relationshipLabel>Intervention Sessions</relationshipLabel>
        <relationshipName>Intervention_Sessions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Intervention Session</label>
    <nameField>
        <displayFormat>IS-{000000}</displayFormat>
        <label>Inter. Session ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Intervention Sessions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Intervention_Session_Result__c.object
<CustomObject>
    <description>The Intervention Session Result is an object that captures the outcome of a student&apos;s participation in an Intervention Session. The result includes duration and notes.</description>
    <fields>
        <fullName>Amount_of_Time__c</fullName>
        <inlineHelpText>Amount of time spent with a student (in minutes) in a single Intervention Session</inlineHelpText>
        <label>Amount of Time (in minutes)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Intervention_Session__c</fullName>
        <inlineHelpText>This field connects the Intervention Session Result record to the correct Intervention Session.</inlineHelpText>
        <label>Intervention Session</label>
        <referenceTo>Intervention_Session__c</referenceTo>
        <relationshipLabel>Intervention Session Results</relationshipLabel>
        <relationshipName>Intervention_Session_Results</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Student_Section__c</fullName>
        <inlineHelpText>This field connects the Intervention Session Result record to the correct Student/Section.</inlineHelpText>
        <label>Student/Section</label>
        <referenceTo>Student_Section__c</referenceTo>
        <relationshipLabel>Intervention Session Results</relationshipLabel>
        <relationshipName>Intervention_Session_Results</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Intervention Session Result</label>
    <nameField>
        <displayFormat>ISR-{000000}</displayFormat>
        <label>Time ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Intervention Session Results</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Section__c.object
<CustomObject>
    <fields>
        <fullName>Intervention_Primary_Staff__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Who is the primary staff member associated with this Intervention Section?</inlineHelpText>
        <label>Intervention Primary Staff</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Intervention Primary Staff does not match filter criteria.</errorMessage>
            <filterItems>
                <field>$Source.School__c</field>
                <operation>equals</operation>
                <valueField>Staff__c.Organization__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Staff__c</referenceTo>
        <relationshipLabel>Intervention Sections</relationshipLabel>
        <relationshipName>Intervention_Sections</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Section__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Recursive lookup for groups</description>
        <label>Section</label>
        <referenceTo>Section__c</referenceTo>
        <relationshipLabel>Groups in Section</relationshipLabel>
        <relationshipName>Sections1</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Section</label>
    <nameField>
        <label>Section Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sections</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Student_Section__c.object
<CustomObject>
    <fields>
        <fullName>Amount_of_Time__c</fullName>
        <label>Amount of time per section</label>
        <summarizedField>Intervention_Session_Result__c.Amount_of_Time__c</summarizedField>
        <summaryForeignKey>Intervention_Session_Result__c.Student_Section__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Section__c</fullName>
        <label>Section</label>
        <referenceTo>Section__c</referenceTo>
        <relationshipLabel>Student</relationshipLabel>
        <relationshipName>Student_Section</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Student/Section</label>
    <nameField>
        <displayFormat>SS-{000000}</displayFormat>
        <label>Student/Section ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Student/Section</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/InterventionSessionResTriggerHandlerTest.cls
@IsTest
public class InterventionSessionResTriggerHandlerTest {

    @IsTest
    static void isBeforeInsertTest() {
        TestDataSetupUtil_v2.setUPCoreData(3);
        TestDataSetupUtil_v2.setUpStaffData(5);
        TestDataSetupUtil_v2.setUpStudentData(5);

        Test.startTest();
        List<Section__c> section = [SELECT Id, Name, Intervention_Primary_Staff__c From Section__c];
        List<Student_Section__c> studentSectionList = [SELECT Id, Name From Student_Section__c];

        Intervention_Session__c intervensionSession = TestDataUtil.createInterventionSession(
                section[0].Id,
                null,
                TestDataSetupUtil_v2.teachersList[0].Id
            );
        insert intervensionSession;

        Intervention_Session_Result__c intervensionSessionResult = new Intervention_Session_Result__c(Intervention_Session__c = intervensionSession.Id, Student_Section__c = studentSectionList[0].Id, Amount_of_Time__c = 1);
        insert intervensionSessionResult;
        Test.stopTest();

        List<Intervention_Session_Result__c> isr = [SELECT Id, Intervention_Session__c From Intervention_Session_Result__c];
        System.assertEquals(intervensionSession.Id, isr[0].Intervention_Session__c);

    }
}