objects/Intervention_Session__c.object
<CustomObject>
    <description>The Intervention Session object captures that an Intervention Section met on a particular day. The outcome of the session is attached to the Intervention Session record.</description>
    <fields>
        <fullName>All_avenues__c</fullName>
        <label>All avenues</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>In-Person Service</fullName>
                </value>
                <value>
                    <fullName>Virtual Service</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Comments__c</fullName>
        <inlineHelpText>Are there any additional comments for this Intervention Session?</inlineHelpText>
        <label>Add&apos;l Comments for Session</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Date__c</fullName>
        <inlineHelpText>What was the date that this Intervention Session took place?</inlineHelpText>
        <label>Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Section__c</fullName>
        <inlineHelpText>This field connects the Intervention Session record to the correct intervention Section.</inlineHelpText>
        <label>Section</label>
        <referenceTo>Section__c</referenceTo>
        <relationshipLabel>Intervention Sessions</relationshipLabel>
        <relationshipName>Intervention_Sessions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Session_Format__c</fullName>
        <label>Session Format</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Push In</fullName>
                </value>
                <value>
                    <fullName>Pull Out</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Session_Time_Completed_For__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <inlineHelpText>Who was the staff member that led the Intervention Section? This field allows a user to enter Session time on behalf of another user.</inlineHelpText>
        <label>Session Time Completed For</label>
        <referenceTo>Staff__c</referenceTo>
        <relationshipLabel>Intervention Sessions</relationshipLabel>
        <relationshipName>Intervention_Sessions</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Session_Type__c</fullName>
        <label>Session Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>1:1</fullName>
                </value>
                <value>
                    <fullName>Small Group</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Site_Details__c</fullName>
        <label>Site Details</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Skill_Primary__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Primary Skill</label>
        <referenceTo>Skill__c</referenceTo>
        <relationshipLabel>Intervention Sessions</relationshipLabel>
        <relationshipName>Intervention_Sessions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Skills_Covered_for_the_Session__c</fullName>
        <inlineHelpText>What specific skills were covered in this Intervention Session?</inlineHelpText>
        <label>Other Skills</label>
        <length>2000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Tutoring_Model__c</fullName>
        <label>Tutoring Model</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Catch Up</fullName>
                </value>
                <value>
                    <fullName>Keep Up</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Intervention Session</label>
    <nameField>
        <displayFormat>IS-{000000}</displayFormat>
        <label>Inter. Session ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Intervention Sessions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Intervention_Session_Result__c.object
<CustomObject>
    <description>The Intervention Session Result is an object that captures the outcome of a student&apos;s participation in an Intervention Session. The result includes duration and notes.</description>
    <fields>
        <fullName>Amount_of_Time__c</fullName>
        <inlineHelpText>Amount of time spent with a student (in minutes) in a single Intervention Session</inlineHelpText>
        <label>Amount of Time (in minutes)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Exit_Ticket__c</fullName>
        <label>Exit Ticket</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Intervention_Session__c</fullName>
        <inlineHelpText>This field connects the Intervention Session Result record to the correct Intervention Session.</inlineHelpText>
        <label>Intervention Session</label>
        <referenceTo>Intervention_Session__c</referenceTo>
        <relationshipLabel>Intervention Session Results</relationshipLabel>
        <relationshipName>Intervention_Session_Results</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Student_Section__c</fullName>
        <inlineHelpText>This field connects the Intervention Session Result record to the correct Student/Section.</inlineHelpText>
        <label>Student/Section</label>
        <referenceTo>Student_Section__c</referenceTo>
        <relationshipLabel>Intervention Session Results</relationshipLabel>
        <relationshipName>Intervention_Session_Results</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Student__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>This field connects the Student record to the Intervention Session Result</inlineHelpText>
        <label>Student</label>
        <referenceTo>Student__c</referenceTo>
        <relationshipLabel>Intervention Session Results</relationshipLabel>
        <relationshipName>Intervention_Session_Results</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Intervention Session Result</label>
    <nameField>
        <displayFormat>ISR-{000000}</displayFormat>
        <label>Time ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Intervention Session Results</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Section__c.object
<CustomObject>
    <fields>
        <fullName>Section__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Recursive lookup for groups</description>
        <label>Section</label>
        <referenceTo>Section__c</referenceTo>
        <relationshipLabel>Groups in Section</relationshipLabel>
        <relationshipName>Sections1</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Section</label>
    <nameField>
        <label>Section Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sections</pluralLabel>
    <recordTypes>
        <fullName>Curriculum</fullName>
        <active>true</active>
        <label>Curriculum</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Skill__c.object
<CustomObject>
    <fields>
        <fullName>Category__c</fullName>
        <label>Category</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Literacy</fullName>
                </value>
                <value>
                    <fullName>Math</fullName>
                </value>
                <value>
                    <fullName>SEL/Behavior and Attendance Interventions</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>IsPrimary__c</fullName>
        <defaultValue>false</defaultValue>
        <label>IsPrimary</label>
        <type>Checkbox</type>
    </fields>
    <label>Skill</label>
    <nameField>
        <label>Skill Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Skills</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Staff__c.object
<CustomObject>
    <fields>
        <fullName>Site__c</fullName>
        <formula>TEXT(Organization__r.Site__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Location</label>
        <type>Text</type>
    </fields>
    <label>Staff</label>
    <nameField>
        <label>Staff Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Staff</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/Student__c.object
<CustomObject>
    <fields>
        <fullName>Comments__c</fullName>
        <inlineHelpText>Displays the comments teachers enter for the student using the Overall Comments Wizard. This text displays on elementary school report cards and progress reports.</inlineHelpText>
        <label>Comments</label>
        <length>32000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Section__c</fullName>
        <inlineHelpText>Displays the student&apos;s current homeroom name or room number. This field can be used for reporting purposes.</inlineHelpText>
        <label>Current Homeroom</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Student__c</fullName>
        <inlineHelpText>Displays the student&apos;s middle name.</inlineHelpText>
        <label>Student Middle Name</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <label>Student</label>
    <nameField>
        <label>Student Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Students</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Student_Section__c.object
<CustomObject>
    <fields>
        <fullName>Amount_of_Time__c</fullName>
        <label>Amount of time per section</label>
        <summarizedField>Intervention_Session_Result__c.Amount_of_Time__c</summarizedField>
        <summaryForeignKey>Intervention_Session_Result__c.Student_Section__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Dosage_to_Date__c</fullName>
        <inlineHelpText>The total number of minutes to date that this student has had in this particular Intervention Section</inlineHelpText>
        <label>Dosage to Date</label>
        <summarizedField>Intervention_Session_Result__c.Amount_of_Time__c</summarizedField>
        <summaryForeignKey>Intervention_Session_Result__c.Student_Section__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Section__c</fullName>
        <label>Section</label>
        <referenceTo>Section__c</referenceTo>
        <relationshipLabel>Student</relationshipLabel>
        <relationshipName>Student_Section</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Student_Name__c</fullName>
        <formula>Student__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Student Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Student__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Student</label>
        <referenceTo>Student__c</referenceTo>
        <relationshipLabel>Section</relationshipLabel>
        <relationshipName>Student_Section</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Student/Section</label>
    <nameField>
        <displayFormat>SS-{000000}</displayFormat>
        <label>Student/Section ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Student/Section</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/ISTool.cls
public with sharing class ISTool{
    public  static final String SECTION_CURRICULUM = 'Curriculum';
    private Map<ID, SessionWrapper> sessionIDMap;
    private Map<Date, List<SessionWrapper>> sessionDateMap;
    private List<SessionWrapper> orderedSessions;

    private ID sectionID;
    private ID studentSectionID;
    private ID sessionID;
    private ID staffID;
    private Date sessionStartDate;
    private Date sessionEndDate;
    private Boolean hasLoadedData = false;
    private Boolean loadSessionResults = true;

    public ISTool(ID sectionID){
        this(sectionId, null, null, null, true);
    }

    public ISTool(ID sectionID, ID studentSectionID){
        this(sectionID, studentSectionID, null, null, true);
    }

    public ISTool(ID sectionID, ID studentSectionID, Date sessionDate){
        this(sectionID, studentSectionID, sessionDate, null, true);
    }

    public ISTool(ID sectionID, ID studentSectionID, Date sessionStartDate, Date sessionEndDate){
        this(sectionID, studentSectionID, sessionStartDate, sessionEndDate, true);
    }

    public ISTool(ID sectionID, Boolean loadResults){
        this(sectionId, null, null, null,loadResults);
    }

    public ISTool(ID sectionID, ID studentSectionID, Boolean loadResults){
        this(sectionID, studentSectionID, null, null,loadResults);
    }

    public ISTool(ID sectionID, ID studentSectionID, Date sessionDate, Boolean loadResults){
        this(sectionID, studentSectionID, sessionDate, null,loadResults);
    }

    public ISTool(ID sectionID, ID studentSectionID, Date sessionStartDate, Date sessionEndDate, Boolean loadResults){
        this.sectionID = sectionID;
        this.studentSectionID = studentSectionID;
        this.sessionStartDate = sessionStartDate;
        this.sessionEndDate = sessionEndDate;
        this.loadSessionResults = loadResults;
    }

    public void updateSessionSelection(ID sectionID){
        updateSessionSelection(sectionId, null, null, null);
    }

    public void updateSessionSelection(ID sectionID, ID studentSectionID){
        updateSessionSelection(sectionID, studentSectionID, null, null);
    }

    public void updateSessionSelection(ID sectionID, ID studentSectionID, Date sessionDate){
        updateSessionSelection(sectionId, studentSectionID, sessionDate, null);
    }

    public void updateSessionSelection(ID sectionID, ID studentSectionID, Date sessionStartDate, Date sessionEndDate){
        this.sectionID = sectionID;
        this.studentSectionID = studentSectionID;
        this.sessionStartDate = sessionStartDate;
        this.sessionEndDate = sessionEndDate;
        if(hasLoadedData){
            loadSessionData();
        }
    }

    public void updateSessionSelection(ID sectionID, ID studentSectionID, Date sessionStartDate, Date sessionEndDate, ID staffID){
        this.staffID = staffID;
        updateSessionSelection(sectionId, studentSectionID, sessionStartDate, sessionEndDate);
    }

    public void updateResultSelection(Boolean loadResults){
        this.loadSessionResults = loadResults;
    }

    public void setSingleSession(ID sessionID){
        this.sessionID = sessionID;
    }

    public void setAllSessions(){
        this.sessionID = null;
    }

    public void loadSessionData(){
        hasLoadedData = true;
        sessionIDMap = new Map<ID, SessionWrapper>();
        sessionDateMap = new Map<Date, List<SessionWrapper>>();
        orderedSessions = new List<SessionWrapper>();

        List<Intervention_Session__c> sessions = querySessions();
        for(Intervention_Session__c session:sessions){
            SessionWrapper wrapper = new SessionWrapper(session);
            orderedSessions.add(wrapper);
            sessionIDMap.put(wrapper.session.ID, wrapper);
            if(sessionDateMap.containsKey(wrapper.session.Date__c)){
                sessionDateMap.get(wrapper.session.Date__c).add(wrapper);
            } else {
                sessionDateMap.put(wrapper.session.Date__c, new List<SessionWrapper>{wrapper});
            }
        }
    }

    public SessionWrapper getSessionByID(ID sessionID){
        return sessionIDMap.get(sessionID);
    }

    public List<SessionWrapper> getSessionsByDate(Date sessionDate){
        return sessionDateMap.get(sessionDate);
    }

    public List<SessionWrapper> getOrderedSessions(){
        return orderedSessions;
    }

    private List<Intervention_Session__c> querySessions(){
        String query = 
            'select ID, Name,Tutoring_Model__c, Skills_Covered_for_the_Session__c, Date__c, All_avenues__c, Comments__c, Session_Time_Completed_For__c, Site_Details__c, '+
                'Session_Time_Completed_For__r.Name, Skill_Primary__c, Skill_Primary__r.Name, LastModifiedDate, Session_Type__c, Session_Format__c ';

        if(loadSessionResults){
            query += ',(select ID, Amount_of_Time__c, Student_Section__c, Student_Section__r.Dosage_to_Date__c, Student_Section__r.Student_Name__c,Exit_Ticket__c'+
                ' from Intervention_Session_Results__r';
            if(studentSectionID != null){
                query += ' where Student_Section__c =\''+String.escapeSingleQuotes(studentSectionID)+'\'';
            }
            query += ' order by Student_Section__r.Student__r.Name)';
        }
                
        query += ' from Intervention_Session__c';
        
        String[] queryFilters = new String[]{};
        if(sectionID != null){
            queryFilters.add('Section__c=\''+String.escapeSingleQuotes(sectionID)+'\'');
        }
        if(sessionStartDate != null && sessionEndDate == null){
            queryFilters.add('Date__c = '+reformatDate(sessionStartDate));
        } else if(sessionStartDate != null && sessionEndDate != null){
            queryFilters.add('Date__c >= '+reformatDate(sessionStartDate));
            queryFilters.add('Date__c <= '+reformatDate(sessionEndDate));
        }
        if(sessionID != null){
            queryFilters.add('ID = \''+sessionID+'\'');
        }
        if(staffID != null){
            queryFilters.add('Session_Time_Completed_For__c=\''+staffID+'\'');
        }

        if(!queryFilters.isEmpty()){
            query += ' where '+String.join(queryFilters,' AND ');
        }
        query+= ' order by Date__c desc';

        System.debug(query);
        List<Intervention_Session__c> results = Database.query(query);
        return results;
    }

    @TestVisible
    private String reformatDate(Date d){
        String[] vars = d.format().split('/',3);
        if(vars[0].length()==1) vars[0] = '0'+vars[0];
        if(vars[1].length()==1) vars[1] = '0'+vars[1];
        return vars[2]+'-'+vars[0]+'-'+vars[1];
    }

    public static final Map<String, String> mapSchoolProgram2Category = new Map<String, String>{
            'Tutoring: Literacy' => 'Literacy',
            'Tutoring: Math' => 'Math'
    };
    public static final String CATBEHAVIOR = 'SEL/Behavior and Attendance Interventions';
    public static void getAvaliableSkills(String schoolProgram, List<SelectOption> avaliableFields, List<SelectOption> allPrimaryFields){
        String category = mapSchoolProgram2Category.containsKey(schoolProgram)? mapSchoolProgram2Category.get(schoolProgram): CATBEHAVIOR;
        Set<String> categoryList = new Set<String>{CATBEHAVIOR};
        categoryList.add(category);
        System.debug('School Program>>'+schoolProgram);
        System.debug('@@@ categoryList: '+categoryList);

        for(Skill__c s :[SELECT Id, Category__c, Name, IsPrimary__c FROM Skill__c
        WHERE Category__c IN :categoryList ORDER BY Name, Category__c ASC]){
            if(s.IsPrimary__c && s.Category__c == category){
                allPrimaryFields.add(new SelectOption(s.Id, s.Name));
            }
            avaliableFields.add(new SelectOption(s.Id, s.Name));
        }
        System.debug('@@@ Skill List allPrimaryFields>>'+allPrimaryFields);
        System.debug('@@@ Skill List avaliableFields>>'+avaliableFields);
    }

    public static List<SelectOption> getAllAvenues(){
        List<SelectOption> allAvenuesOptions = new List<SelectOption>();
        allAvenuesOptions.add(new SelectOption('', 'None', true));
        Map<String, String> mapValues = CT_core_SoqlUtils.getPicklistValues('Intervention_Session__c' ,'All_avenues__c');
        for(String val: mapValues.keySet()){
            allAvenuesOptions.add(new SelectOption(val, mapValues.get(val)));
        }
         system.debug('@@ allAvenuesOptions'+allAvenuesOptions);
        return allAvenuesOptions;
    }

    public static List<SelectOption> getSiteDetailsOptions(){
        List<SelectOption> siteDetailsOptions = new List<SelectOption>();
        String usersSite = [Select Site__c From User Where Id = :UserInfo.getUserId()][0].Site__c;
        if (usersSite == '' || usersSite == null){
            siteDetailsOptions = null;
        } else {
            List<Site_Details_Mapping__mdt> mappings = [SELECT Values__c
                                                        FROM Site_Details_Mapping__mdt
                                                        WHERE Location__c = :usersSite];
            if (mappings.size() != 0 && mappings[0].Values__c != null && mappings[0].Values__c != '') {
                siteDetailsOptions.add(new SelectOption('', 'None', false));
                List<String> values = mappings[0].Values__c.split(';');
                for(String value : values) {
                    siteDetailsOptions.add(new SelectOption(value, value));
                }
            }
        }
        return siteDetailsOptions;
    }

    public class SessionWrapper{
        public Intervention_Session__c session  {get;set;}
        public List<Intervention_Session_Result__c> studentResults {get;set;}

        public SessionWrapper(Intervention_Session__c session){
            this.session = session;
            if(session.Intervention_Session_Results__r != null){
                this.studentResults = session.Intervention_Session_Results__r;
            } else {
                this.studentResults = new List<Intervention_Session_Result__c>();
            }
        }
    }

}