objects/Link_Settings__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Controls the visibility of custom pages accessible through Links sidebar</description>
    <fields>
        <fullName>Assessment_Wizard__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Assessment Wizard</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Attendance_Wizard__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Attendance Wizard</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Community_Service_Wizard__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Community Service Wizard</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Overall_Comments__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Overall Comments</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Print_Schedule__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Print Schedule</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ProActive_Processor__c</fullName>
        <defaultValue>false</defaultValue>
        <label>ProActive Processor</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Run_Report_Cards__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Run Report Cards</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Section_Wizard__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Section Wizard</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Year_Close_Wizard__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Year Close Wizard</label>
        <type>Checkbox</type>
    </fields>
    <label>Custom Link Settings</label>
</CustomObject>

classes/Test_core_CustomLinksController.cls
@isTest
private class Test_core_CustomLinksController {
	@isTest static void test_core_CustomLinksController(){
		core_CustomLinksController controller = new core_CustomLinksController();
		insertValuesForRelease();
		test.StartTest();
		core_CustomLinksController c = new core_CustomLinksController();
			test.StopTest();
	}
	
	private static void insertValuesForRelease(){
		List <Link_Settings__c> lsList = new List <Link_Settings__c>();
		for (Profile p: [select id, name from Profile]){
			Boolean isAdmin= false;
			Boolean isFrontOffice = false;
			Boolean isTeacher = false;
			system.debug(p.name);
			if (p.name.contains('Office')) isFrontOffice=true;
			else if (p.name.contains('Teacher')) isTeacher = true;
			else if (p.name.contains('Administrator')) isAdmin = true;
			if (isAdmin||isFrontOffice||isTeacher){
			system.debug(isAdmin+'|'+isFrontOffice+'|'+isTeacher);
			Link_Settings__c ls= new Link_Settings__c(SetupOwnerId=p.id);
			if (isTeacher) ls.Overall_Comments__c=true;
			if (isFrontOffice||isAdmin) ls.ProActive_Processor__c=true;
			if (isFrontOffice||isAdmin) ls.Run_Report_Cards__c=true;
			if (isFrontOffice||isAdmin) ls.Section_Wizard__c=true;
			if (isFrontOffice||isAdmin) ls.Attendance_Wizard__c=true;
			ls.Print_Schedule__c=true;
			if (isFrontOffice||isAdmin) ls.Assessment_Wizard__c=true;
			ls.Community_Service_Wizard__c=true;
			if (isAdmin)ls.Year_Close_Wizard__c=true;
			lsList.add(ls);
			}
		}
		upsert lsList;
	}	
}