objects/Link_Settings__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Controls the visibility of custom pages accessible through Links sidebar</description>
    <fields>
        <fullName>Advanced_Reports__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Advanced Reports</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Assessment_Wizard__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Assessment Wizard</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Attendance_Wizard__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Attendance Wizard</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>CSV_Loader__c</fullName>
        <defaultValue>false</defaultValue>
        <label>CSV Loader</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Cohort_Wizard__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Cohort Wizard</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Communities_SSO_URL__c</fullName>
        <description>The unique URL for Communities SSO to work</description>
        <inlineHelpText>This value differs between test and prod orgs.</inlineHelpText>
        <label>Communities SSO URL</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Communities_SSO__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Communities Single Sign On</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Community_Service_Wizard__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Community Service Wizard</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Complete_Sections__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Complete Sections</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Overall_Comments__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Overall Comments</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Points_Matrix__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Points Matrix</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Print_Schedule__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Print Schedule</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ProActive_Processor__c</fullName>
        <defaultValue>false</defaultValue>
        <label>ProActive Processor</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Run_Report_Cards__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Run Report Cards</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Section_Wizard__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Section Wizard</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Transfer_Wizard__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Link to enter transfer courses and grades</description>
        <label>Transfer Wizard</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Year_Close_Wizard__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Year Close Wizard</label>
        <type>Checkbox</type>
    </fields>
    <label>Custom Link Settings</label>
</CustomObject>

objects/Setup__c.object
<CustomObject>
    <description>This object is used to setup Schoolforce and is referenced in multiple pieces of code.  There should be one setup object per school.</description>
    <fields>
        <fullName>Section_Wizard__c</fullName>
        <formula>HYPERLINK(&apos;/apex/Scheduler_SectionWizard&apos;,&apos;Section Wizard for &apos;+ School__r.Name )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Section Wizard</label>
        <type>Text</type>
    </fields>
    <label>Setup</label>
    <nameField>
        <displayFormat>S-{0}</displayFormat>
        <label>Setup ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Setup</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

classes/core_CustomLinksController.cls
public with sharing class core_CustomLinksController {

	public Link_Settings__c linkSetting {get;set;}  
	public List <linkListWrapper> linkList {get;set;}

	public static boolean checkAcademics(Link_Settings__c ls){
		return (ls.Overall_Comments__c||ls.Assessment_Wizard__c||ls.Run_Report_Cards__c||ls.complete_sections__c);
	}

	public static boolean checkAdvancedReports(Link_Settings__c ls){
		return (ls.advanced_reports__c);
	}

	public static boolean checkPoints(Link_Settings__c ls){
		return (ls.Points_Matrix__c);
	}

	public static boolean checkFrontOffice(Link_Settings__c ls){
		return	ls.Attendance_Wizard__c||ls.Section_Wizard__c||ls.Cohort_Wizard__c||ls.Transfer_Wizard__c||ls.Community_Service_Wizard__c||ls.Print_Schedule__c||ls.ProActive_Processor__c;
	}


	public static boolean checkSysAdmin(Link_Settings__c ls){
		return (ls.Year_Close_Wizard__c);
	}

	public static boolean checkSchoolForceCommunity(Link_Settings__c ls){
		return ls.Communities_SSO__c&&ls.Communities_SSO_URL__c!=null;
	}

	public core_CustomLinksController(){ 
		if 			(Link_Settings__c.getInstance(UserInfo.getProfileId())!=null)	linkSetting=Link_Settings__c.getInstance(UserInfo.getProfileId());
		else	if	(Link_Settings__c.getOrgDefaults()!=null) 								linkSetting=Link_Settings__c.getOrgDefaults();
		else {
			linkSetting = new Link_Settings__c(); 
		}
		linkList = new List <linkListWrapper>();
		
		if (checkAcademics(linkSetting)){
				linkListWrapper llw = new linkListWrapper('Academics');
				if (linkSetting.Overall_Comments__c) llw.lwList.add(new linkWrapper('overall_comments', 'Overall Comments'));
				if (linkSetting.Assessment_Wizard__c) llw.lwList.add(new linkWrapper('AssessmentWizard', 'Assessment Wizard'));
				if (linkSetting.Run_Report_Cards__c) llw.lwList.add(new linkWrapper('gradebook_runreportCards', 'Generate Documents'));
				if (linkSetting.Complete_sections__c) llw.lwList.add(new linkWrapper('gradebook_completeSections', 'Mark Sections Completed'));
			linkList.add(llw);
		}
		if (checkAdvancedReports(linkSetting)){
			linkListWrapper llw = new linkListWrapper('Gradebook Advanced Reports');
			if (linkSetting.Advanced_Reports__c) llw.lwList.add(new linkWrapper('Advanced_Reports', 'View Gradebook Advanced Reports'));
			linkList.add(llw);
		}
		if (checkPoints(linkSetting)){
			linkListWrapper llw = new linkListWrapper('Points');
			if (linkSetting.Points_Matrix__c) llw.lwList.add(new linkWrapper('Points_Matrix', 'Points Module'));
			linkList.add(llw);
		}
		if (checkFrontOffice(linkSetting)){
			linkListWrapper llw = new linkListWrapper('Front Office');
			if (linkSetting.Attendance_Wizard__c) llw.lwList.add(new linkWrapper('AttendanceWizard_v2', 'Attendance Wizard'));
			if (linkSetting.Section_Wizard__c) llw.lwList.add(new linkWrapper('Scheduler_SectionWizard', 'Section Wizard'));
			if (linkSetting.Cohort_Wizard__c) llw.lwList.add(new linkWrapper('Cohort_SetupWizard', 'Cohort Wizard'));
			if (linkSetting.Transfer_Wizard__c) llw.lwList.add(new linkWrapper('Transfer_CourseWizard', 'Transfer Wizard'));
			if (linkSetting.Community_Service_Wizard__c) llw.lwList.add(new linkWrapper('CommunityServiceWizard', 'Community Service Wizard'));
			if (linkSetting.Print_Schedule__c) llw.lwList.add(new linkWrapper('printSchedule', 'Email/Print Schedule'));
			if (linkSetting.ProActive_Processor__c) llw.lwList.add(new linkWrapper('proActiveVF', 'ProActive Processor'));
			linkList.add(llw);
		}
		if(checkSchoolForceCommunity(linkSetting)){
			linkListWrapper llw = new linkListWrapper('SchoolForce Community');
			if (linkSetting.Communities_SSO__c) llw.lwList.add(new linkWrapper(linkSetting.Communities_SSO_URL__c,'SchoolForce Community',true));
			linkList.add(llw);
		}
		if (checkSysAdmin(linkSetting)){
			linkListWrapper llw = new linkListWrapper('System Admin');
			//if (linkSetting.Year_Close_Wizard__c) llw.lwList.add(new linkWrapper('EOY_SchoolCloseout', 'Year Close Wizard'));
			if (linkSetting.Csv_Loader__c) llw.lwList.add(new linkWrapper('core_LoadCsvData_v2', 'CSV Loader'));
			linkList.add(llw);
		}
		

	}

	public class linkListWrapper{
		public List <linkWrapper> lwList {get;set;}
		public string sLabel {get;set;}
		public linkListWrapper(string sName){
			this.sLabel= sName;
			this.lwList = new List <linkWrapper>();
		}
		
	}

	public class linkWrapper{
		
		public pageReference redirect {get;set;}
		public string				label		{get;set;}
		
		public linkWrapper(string sLink, string sName){
			this.redirect = dummyReturn(sLink);
			this.label 		= sName;
		}
		
		public linkWrapper(string sLink, string sLabelName, boolean staticURL){
			this.redirect = new PageReference(sLink);
			this.label = sLabelName;
		}
	}
	 
	public static pageReference dummyReturn(string pageName){
		boolean isManagedPackage = Schema.SObjectType.Setup__c.getName().replace('__c', '').contains('__');
		PageReference pr = new PageReference( '/apex/'+ ((isManagedPackage)?'SchoolForce__':'')+pageName);
			
		pr.setRedirect (true); 
		return pr;
	}
}