objects/Meals_Setup__c.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Additional_Reimbursement_1_Amount__c</fullName>
        <defaultValue>0</defaultValue>
        <description>This is the amount for an additional reimbursement applied at the state level.</description>
        <inlineHelpText>This is the amount for an additional reimbursement applied at the state level.</inlineHelpText>
        <label>Additional Reimbursement 1 Amount</label>
        <precision>3</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Additional_Reimbursement_1_Applies_To__c</fullName>
        <label>Additional Reimbursement 1 Applies To</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Breakfast</fullName>
                </value>
                <value>
                    <fullName>Lunch</fullName>
                </value>
                <value>
                    <fullName>Both</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Additional_Reimbursement_2_Amount__c</fullName>
        <defaultValue>0</defaultValue>
        <description>This is the amount for an additional reimbursement applied at the state level.</description>
        <inlineHelpText>This is the amount for an additional reimbursement applied at the state level.</inlineHelpText>
        <label>Additional Reimbursement 2 Amount</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Additional_Reimbursement_2_Applies_To__c</fullName>
        <label>Additional Reimbursement 2 Applies To</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Breakfast</fullName>
                </value>
                <value>
                    <fullName>Lunch</fullName>
                </value>
                <value>
                    <fullName>Both</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Additional_Reimbursement_3_Amount__c</fullName>
        <defaultValue>0</defaultValue>
        <description>This is the amount for an additional reimbursement applied at the state level.</description>
        <inlineHelpText>This is the amount for an additional reimbursement applied at the state level.</inlineHelpText>
        <label>Additional Reimbursement 3 Amount</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Additional_Reimbursement_3_Applies_To__c</fullName>
        <label>Additional Reimbursement 3 Applies To</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Breakfast</fullName>
                </value>
                <value>
                    <fullName>Lunch</fullName>
                </value>
                <value>
                    <fullName>Both</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Fed_Free_Breakfast_Reimbursement__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Fed Free Breakfast Reimbursement</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Fed_Free_Lunch_Reimbursement__c</fullName>
        <defaultValue>0</defaultValue>
        <description>This is the amount of money that the school is reimbursed for free lunches that are served.</description>
        <inlineHelpText>This is the amount of money that the school is reimbursed for free lunches that are served.</inlineHelpText>
        <label>Fed Free Lunch Reimbursement</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Fed_Full_Price_Breakfast_Reimbursement__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Fed Full-Price Breakfast Reimbursement</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Fed_Full_Price_Lunch_Reimbursement__c</fullName>
        <defaultValue>0</defaultValue>
        <description>This is the amount of money that the school is reimbursed for full-priced lunches that are served.</description>
        <inlineHelpText>This is the amount of money that the school is reimbursed for full-priced lunches that are served.</inlineHelpText>
        <label>Fed Full-Price Lunch Reimbursement</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Fed_Reduced_Breakfast_Reimbursement__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Fed Reduced Breakfast Reimbursement</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Fed_Reduced_Lunch_Reimbursement__c</fullName>
        <defaultValue>0</defaultValue>
        <description>This is the amount of money that the school is reimbursed for reduced lunches that are served.</description>
        <inlineHelpText>This is the amount of money that the school is reimbursed for reduced lunches that are served.</inlineHelpText>
        <label>Fed Reduced Lunch Reimbursement</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Full_Price_Breakfast_Price__c</fullName>
        <defaultValue>0</defaultValue>
        <description>This is the amount a student pays for a full-priced breakfast.</description>
        <inlineHelpText>This is the amount a student pays for a full-priced breakfast.</inlineHelpText>
        <label>Full-Price Breakfast Price</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Full_Price_Lunch_Price__c</fullName>
        <defaultValue>0</defaultValue>
        <description>This is the amount a student pays for a full-priced lunch.</description>
        <inlineHelpText>This is the amount a student pays for a full-priced lunch.</inlineHelpText>
        <label>Full-Price Lunch Price</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Reduced_Breakfast_Price__c</fullName>
        <defaultValue>0</defaultValue>
        <description>This is the amount a student pays for a reduced breakfast.</description>
        <inlineHelpText>This is the amount a student pays for a reduced breakfast.</inlineHelpText>
        <label>Reduced Breakfast Price</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Reduced_Lunch_Price__c</fullName>
        <defaultValue>0</defaultValue>
        <description>This is the amount a student pays for a reduced lunch.</description>
        <inlineHelpText>This is the amount a student pays for a reduced lunch.</inlineHelpText>
        <label>Reduced Lunch Price</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Setup__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Setup</label>
        <referenceTo>Setup__c</referenceTo>
        <relationshipLabel>Meals Setup</relationshipLabel>
        <relationshipName>Meals_Setup</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>State_Free_Breakfast_Reimbursement__c</fullName>
        <defaultValue>0</defaultValue>
        <label>State Free Breakfast Reimbursement</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>State_Free_Lunch_Reimbursement__c</fullName>
        <defaultValue>0</defaultValue>
        <description>This is the amount of money that the school is reimbursed for free lunches that are served.</description>
        <inlineHelpText>This is the amount of money that the school is reimbursed for free lunches that are served.</inlineHelpText>
        <label>State Free Lunch Reimbursement</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>State_Full_Price_Breakfast_Reimbursement__c</fullName>
        <defaultValue>0</defaultValue>
        <label>State Full-Price Breakfast Reimbursement</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>State_Full_Price_Lunch_Reimbursement__c</fullName>
        <defaultValue>0</defaultValue>
        <description>This is the amount of money that the school is reimbursed for full-priced lunches that are served.</description>
        <inlineHelpText>This is the amount of money that the school is reimbursed for full-priced lunches that are served.</inlineHelpText>
        <label>State Full-Price Lunch Reimbursement</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>State_Reduced_Breakfast_Reimbursement__c</fullName>
        <defaultValue>0</defaultValue>
        <label>State Reduced Breakfast Reimbursement</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>State_Reduced_Lunch_Reimbursement__c</fullName>
        <defaultValue>0</defaultValue>
        <description>This is the amount of money that the school is reimbursed for reduced lunches that are served.</description>
        <inlineHelpText>This is the amount of money that the school is reimbursed for reduced lunches that are served.</inlineHelpText>
        <label>State Reduced Lunch Reimbursement</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Meals Setup</label>
    <nameField>
        <displayFormat>MS-{0}</displayFormat>
        <label>Meals Setup Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Meals Setup</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Setup__c.object
<CustomObject>
    <description>This object is used to setup Schoolforce and is referenced in multiple pieces of code.  There should be one setup object per school.</description>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Is this school setup active for this school year?</inlineHelpText>
        <label>Active?</label>
        <type>Checkbox</type>
    </fields>
    <label>Setup</label>
    <nameField>
        <displayFormat>S-{0}</displayFormat>
        <label>Setup ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Setup</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/Student__c.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>true</defaultValue>
        <inlineHelpText>Indicates whether or not this Student record is active. If checked, then this is the current Student record. If unchecked, this is an old Student record.</inlineHelpText>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Setup__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Displays the Setup record associated to this Student record. The Setup record defines the settings for the school in a specific school year.</inlineHelpText>
        <label>Setup</label>
        <referenceTo>Setup__c</referenceTo>
        <relationshipLabel>Students</relationshipLabel>
        <relationshipName>Students</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Student__c</fullName>
        <inlineHelpText>Displays the student&apos;s middle name.</inlineHelpText>
        <label>Student Middle Name</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <label>Student</label>
    <nameField>
        <label>Student Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Students</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/Test_Meals.cls
@isTest
private class Test_Meals {
	public static void createTestData(){
		TestDataSetupUtil_v2.setUPCoreData(5);
		TestDataSetupUtil_v2.setUpStaffData(5);
		TestDataSetupUtil_v2.setUpStudentData(5);
		system.debug('Soql after create data: ' + limits.getQueries());
	}

	static testMethod void testAllMeals() {
		createTestData();

		Student__c student = TestDataSetupUtil_v2.studentsList[0];
			Student__c student2 = TestDataSetupUtil_v2.studentsList[1];
			
		Meals_Setup__c ms=
			new Meals_Setup__c(
				State_Reduced_Lunch_Reimbursement__c=1, 
				State_Full_Price_Lunch_Reimbursement__c=1, 
				State_Free_Lunch_Reimbursement__c=1, 
				Setup__c= TestDataSetupUtil_v2.activeSetUp.Id, 
				Fed_Reduced_Lunch_Reimbursement__c=1, 
				Fed_Full_Price_Lunch_Reimbursement__c=1, 
				Fed_Free_Lunch_Reimbursement__c=1, 
				Additional_Reimbursement_3_Amount__c=1, 
				Additional_Reimbursement_2_Amount__c=1, 
				Additional_Reimbursement_1_Amount__c=1,
				State_Reduced_Breakfast_Reimbursement__c=1, 
				State_Full_Price_Breakfast_Reimbursement__c=1, 
				State_Free_Breakfast_Reimbursement__c=1, 
				Fed_Reduced_Breakfast_Reimbursement__c=1, 
				Fed_Full_Price_Breakfast_Reimbursement__c=1, 
				Fed_Free_Breakfast_Reimbursement__c=1,
				Additional_Reimbursement_3_Applies_To__c='Both', 
				Additional_Reimbursement_2_Applies_To__c='Lunch', 
				Additional_Reimbursement_1_Applies_To__c='Breakfast',
				Reduced_Lunch_Price__c=1, 
				Reduced_Breakfast_Price__c=1,
				Full_Price_Lunch_Price__c=1, 
				Full_Price_Breakfast_Price__c=1,
				Active__c=true);
		insert ms;
		
		student.Meals_Category__c = 'Reduced';
		student.Student_Id__c = 'abc123';	
		core_triggerUtils.mealsTriggerUpdate(true);	
		update student;
		student2.Meals_Category__c = 'Free';
		student2.Student_Id__c = 'abc321';		
		update student2;

		Test.startTest();       
			system.runAs(testDataSetupUtil_v2.staffUsersList[0]){
				MealsController mc = new MealsController();
				mc.mealType = 'Lunch';
				mc.studID = student.Student_Id__c;
				mc.pullStudent();
				mc.buyMeal();
				mc.mealType = 'Lunch';
				mc.studID = student.Student_Id__c;
				mc.pullStudent();
				mc.studentMealList[0].Void__c=true;
				mc.voidTransactions();
				
				mc.mealType = 'Lunch';
				mc.studID = student.Student_Id__c;
				mc.pullStudent();
				mc.buyMeal();
				mc.mealType = 'Lunch';
				mc.studID = student2.Student_Id__c;
				mc.pullStudent();
				mc.buyMeal();
		
				string key = (String) TestDataSetupUtil_v2.school.Id + system.now().format('MM/dd/yyy');
				Daily_Meal_Summary__c dms = [select d.ID, d.Name, d.Total_Reduced_Lunches__c, d.Total_Lunches__c, d.Total_Free_Lunches__c From Daily_Meal_Summary__c d where key__c = :key Limit 1];
				system.debug('#### dms: '+dms);
				system.assert(dms.Total_Reduced_Lunches__c==1);
				system.assert(dms.Total_Free_Lunches__c==1);
				system.assert(dms.Total_Lunches__c==2);
			}
		test.stopTest();
	}

	static testMethod void testSchoolwideFreeBreakfast(){
		createTestData();
		Student__c student = TestDataSetupUtil_v2.studentsList[0];
		Student__c student2 = TestDataSetupUtil_v2.studentsList[1];
		Student__c student3 = TestDataSetupUtil_v2.studentsList[2];
		Student__c student4 = TestDataSetupUtil_v2.studentsList[3];
		Student__c student5 = TestDataSetupUtil_v2.studentsList[4];
		
		Meals_Setup__c ms = 
			new Meals_Setup__c(
				Setup__c= TestDataSetupUtil_v2.activeSetUp.Id, 
				State_Reduced_Breakfast_Reimbursement__c=1, 
				State_Full_Price_Breakfast_Reimbursement__c=0, 
				State_Free_Breakfast_Reimbursement__c=2, 
				Fed_Reduced_Breakfast_Reimbursement__c=1, 
				Fed_Full_Price_Breakfast_Reimbursement__c=0, 
				Fed_Free_Breakfast_Reimbursement__c=2,
				Schoolwide_Free_Breakfast__c=true,
				Active__c=true);
		insert ms;
		core_triggerUtils.mealsTriggerUpdate(true);
		List<Student__c> students = new List<Student__c>();

		student.Meals_Category__c = 'Reduced';	
		students.add(student);
		student2.Meals_Category__c = 'Reduced';		
		students.add(student2);
		student3.Meals_Category__c = 'Free';		
		students.add(student3);
		student4.Meals_Category__c = 'Free';		
		students.add(student4);
		student5.Meals_Category__c = 'Full-Priced';		
		students.add(student5);

		update students;

		Test.startTest();       
			system.runAs(testDataSetupUtil_v2.staffUsersList[0]){
				MealsController mc = new MealsController();

				mc.mealType = 'Breakfast';
				mc.studID = student.Student_Id__c;
				mc.pullStudent();
				mc.buyMeal();

				mc.mealType = 'Breakfast';
				mc.studID = student2.Student_Id__c;
				mc.pullStudent();
				mc.buyMeal();

				mc.mealType = 'Breakfast';
				mc.studID = student3.Student_Id__c;
				mc.pullStudent();
				mc.buyMeal();

				mc.mealType = 'Breakfast';
				mc.studID = student5.Student_Id__c;
				mc.pullStudent();
				mc.buyMeal();
				
				string key = (String) TestDataSetupUtil_v2.school.Id + system.now().format('MM/dd/yyy');
				Daily_Meal_Summary__c dms = [select d.Total_State_Local_Reimbursement__c, d.Total_Reduced_Breakfasts__c, d.Total_Full_Price_Breakfasts__c, d.Total_Free_Breakfasts__c, d.Total_Federal_Reimbursement__c, d.Total_Breakfasts__c, d.Additional_Breakfasts_Served__c From Daily_Meal_Summary__c d where key__c = :key Limit 1];
				system.debug('#### dms: '+dms);
				system.assertEquals(1, dms.Total_Free_Breakfasts__c);
				system.assertEquals(2, dms.Total_Reduced_Breakfasts__c);
				system.assertEquals(1, dms.Total_Full_Price_Breakfasts__c);
				system.assertEquals(4, dms.Total_Breakfasts__c);
				system.assertEquals(4, dms.Total_Federal_Reimbursement__c);
				system.assertEquals(4, dms.Total_State_Local_Reimbursement__c);
			}
		Test.stopTest();
	}
}