objects/Picklist_Value__c.object
<CustomObject>
    <label>Picklist Value</label>
    <nameField>
        <label>Display Value</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Picklist Values</pluralLabel>
    <recordTypes>
        <fullName>Attendance</fullName>
        <active>true</active>
        <label>Attendance</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Section__c.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Check this box if the section is a currently active section</description>
        <inlineHelpText>Check this box if the section is a currently active section</inlineHelpText>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Daily_Attendance__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This should be checked if this section is recording daily attendance rather than sectional attendance.</description>
        <inlineHelpText>Select if staff members will take daily attendance in this section. The section will display in the All Day grid and you will not be able to add it to a specific period in your schedule. You must also select the Record Attendance check box.</inlineHelpText>
        <label>Daily Attendance?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Section__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Recursive lookup for groups</description>
        <label>Section</label>
        <referenceTo>Section__c</referenceTo>
        <relationshipLabel>Groups in Section</relationshipLabel>
        <relationshipName>Sections1</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Section</label>
    <nameField>
        <label>Section Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sections</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Session__c.object
<CustomObject>
    <description>This object captures the daily session for each section.</description>
    <fields>
        <fullName>Daily_Attendance__c</fullName>
        <description>This is a cross object formula field that will show whether attendance is being recorded for the section.</description>
        <formula>IF( Section__r.Daily_Attendance__c ,&apos;Y&apos;, &apos;N&apos;)</formula>
        <label>Daily Attendance?</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>End_DateTime__c</fullName>
        <description>End Date and Time for Session</description>
        <label>End Date Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Section__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This is a lookup to the section that the session belongs to.</description>
        <label>Section</label>
        <referenceTo>Section__c</referenceTo>
        <relationshipLabel>Sessions</relationshipLabel>
        <relationshipName>Sessions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Session_Date__c</fullName>
        <formula>DATEVALUE( End_DateTime__c )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Session Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Start_DateTime__c</fullName>
        <description>Date and time that session starts</description>
        <label>Start Date Time</label>
        <type>DateTime</type>
    </fields>
    <label>Session</label>
    <nameField>
        <label>Session Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sessions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Student__c.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>true</defaultValue>
        <inlineHelpText>Indicates whether or not this Student record is active. If checked, then this is the current Student record. If unchecked, this is an old Student record.</inlineHelpText>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Expiration_Date__c</fullName>
        <inlineHelpText>Do not use this field; it is no longer used by SchoolForce.</inlineHelpText>
        <label>Expiration Date*Retired*</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Section__c</fullName>
        <inlineHelpText>Displays the student&apos;s current homeroom name or room number. This field can be used for reporting purposes.</inlineHelpText>
        <label>Current Homeroom</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Student_First_Name__c</fullName>
        <inlineHelpText>Displays the student&apos;s first name.</inlineHelpText>
        <label>Student First Name</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Student_Last_Name__c</fullName>
        <inlineHelpText>Displays the student&apos;s last name.</inlineHelpText>
        <label>Student Last Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Student__c</fullName>
        <inlineHelpText>Displays the student&apos;s middle name.</inlineHelpText>
        <label>Student Middle Name</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <label>Student</label>
    <nameField>
        <label>Student Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Students</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/TestAttendanceDateWizard.cls
@isTest
//the indentation on this test indicates which controller is being used
//this is to keep the controllers from stumbling over themselves and the testing becomes easier
private class TestAttendanceDateWizard {

	static testMethod void TestAttendanceDateWizard() {
		AttendanceDateWizardController con = new AttendanceDateWizardController();
		testDataSetupUtil_v2.isAttendance=true;
		testDataSetupUtil_v2.setUPCoreData(5);
		testDataSetupUtil_v2.setUPStaffData(5);
		testDataSetupUtil_v2.setUPStudentData(5);
		integer i=0;
		for (Section__c sect: testDataSetupUtil_v2.sectionsList){
	 		if (!sect.daily_attendance__c){
	  			testDataSetupUtil_v2.getSessions(10,testDataSetupUtil_v2.semester,sect.Id, i);
	  			i++; 
			}else{
				testDataSetupUtil_v2.getSessions(10,testDataSetupUtil_v2.semester,sect.Id,  null);
			}
		}
  
		List <Picklist_Value__c> pvl = testDataSetupUtil_v2.createDefaultAttendanceTypes(testDataSetupUtil_v2.activeSetup);
  		core_SoqlUtils.loggedInUser = null;
  
  		system.runAs(testDataSetupUtil_v2.staffUsersList[0]){
				con = new AttendanceDateWizardController();

			Test.startTest();
				attendanceDateWizardController controller1 = new attendanceDateWizardController();

				controller1.cancel();
				controller1.go();
				controller1.searchStudent.student.Student_First_Name__c = '*';
				controller1.searchStudent.student.Student_Last_Name__c = '*';
				controller1.go();
					//system.assertEquals([SELECT count() FROM Student__c Where active__c = true], controller1.studentSearchResults.size());
				controller1.searchStudent.student.Student_First_Name__c = 'aoheroehoarep';
				controller1.go();
				system.assertEquals(0, controller1.studentSearchResults.size());
				controller1.displaySections();
				controller1.searchStudent.student.Student_First_Name__c = testDataSetupUtil_v2.studentsList[0].Student_First_Name__c;
				controller1.searchStudent.student.Student_Last_Name__c = testDataSetupUtil_v2.studentsList[0].Student_Last_Name__c;
				controller1.go();
				system.assertEquals(1, controller1.studentSearchResults.size());
				
				ApexPages.currentPage().getParameters().put('firstName', testDataSetupUtil_v2.studentsList[0].Student_First_Name__c);
				ApexPages.currentPage().getParameters().put('lastName', testDataSetupUtil_v2.studentsList[0].Student_Last_Name__c);
				ApexPages.currentPage().getParameters().put('studID', testDataSetupUtil_v2.studentsList[0].ID);	
				controller1.displaySections();
					//do the range first
				controller1.selectedFunction='Range';
				controller1.endDate.Expiration_Date__c = date.valueOf('2010-01-01');
				controller1.startDate.Expiration_Date__c = date.valueOf('2011-01-01');
					//cause error
				controller1.save();
					//create attendance records for the whole year
				controller1.endDate.Expiration_Date__c = date.valueOf('2012-01-01');
				controller1.startDate.Expiration_Date__c = date.valueOf('2010-01-01');
				
				
				controller1.setStatus = pvl[0].id;
				controller1.selectedSection1 = testDataSetupUtil_v2.sectionsList[0].id;
				controller1.selectedSection2 = testDataSetupUtil_v2.sectionsList[0].id;
				
				controller1.searchDate.Expiration_Date__c = [select session_date__c from session__c where section__c = :controller1.selectedSection1 limit 1].session_date__c;
				controller1.displayAttendance();
				
				controller1.save();
				controller1.searchDate.Expiration_Date__c = [select session_date__c from session__c where section__c = :controller1.selectedSection2 limit 1].session_date__c;
				controller1.selectedFunction='Date';
				controller1.setStatus = pvl[0].id;
				controller1.attendanceresult.Picklist_Value__c	= pvl[0].id;
				controller1.save();
				
				
				controller1.setStatus = pvl[5].id;
				controller1.attendanceresult.Picklist_Value__c	= pvl[5].id;
				controller1.save();
				controller1.setStatus = pvl[5].id;
				controller1.attendanceresult.Picklist_Value__c	= pvl[5].id;
				controller1.attendanceresult.Departure_Time__c = system.now();
				controller1.attendanceresult.Arrival_Time__c = system.now();
				controller1.save();
				controller1.setStatus = pvl[5].id;
				controller1.attendanceresult.Picklist_Value__c	= pvl[5].id;
				controller1.attendanceresult.Departure_Time__c = system.now();
				controller1.attendanceresult.Arrival_Time__c = null;
				controller1.save();
				controller1.setStatus = pvl[5].id;
				controller1.attendanceresult.Picklist_Value__c	= pvl[5].id;
				controller1.attendanceresult.Departure_Time__c = controller1.asession.End_DateTime__c.addMinutes(15);
				controller1.save();
				controller1.setStatus = pvl[5].id;
				controller1.attendanceresult.Picklist_Value__c	= pvl[5].id;
				controller1.attendanceresult.Departure_Time__c = controller1.asession.End_DateTime__c.addMinutes(-15);
				controller1.save();
				
				
				controller1.setStatus = pvl[4].id;
				controller1.attendanceresult.Picklist_Value__c	= pvl[4].id;
				controller1.save();
				controller1.setStatus = pvl[4].id;
				controller1.attendanceresult.Picklist_Value__c	= pvl[4].id;
				controller1.attendanceresult.Arrival_Time__c = system.now();
				controller1.save();
				controller1.setStatus = pvl[4].id;
				controller1.attendanceresult.Picklist_Value__c	= pvl[4].id;
				controller1.attendanceresult.Arrival_Time__c = controller1.asession.End_DateTime__c.addMinutes(15);
				controller1.save();
				controller1.setStatus = pvl[4].id;
				controller1.attendanceresult.Picklist_Value__c	= pvl[4].id;
				controller1.attendanceresult.Arrival_Time__c = controller1.asession.Start_DateTime__c.addMinutes(15);
				controller1.save();
			Test.stopTest();
 		}
	}
}