objects/Picklist_Value__c.object
<CustomObject>
    <fields>
        <fullName>Category__c</fullName>
        <label>Category</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Type__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Absent</fullName>
                </value>
                <value>
                    <fullName>Reporting Period</fullName>
                </value>
                <value>
                    <fullName>Custom Period</fullName>
                </value>
                <value>
                    <fullName>In School Suspension</fullName>
                </value>
                <value>
                    <fullName>Out of School Suspension</fullName>
                </value>
                <value>
                    <fullName>Present</fullName>
                </value>
                <value>
                    <fullName>Partial</fullName>
                </value>
                <value>
                    <fullName>Tardy</fullName>
                </value>
                <value>
                    <fullName>Excused Absence</fullName>
                </value>
                <value>
                    <fullName>Unexcused Absence</fullName>
                </value>
                <value>
                    <fullName>Excused Tardy</fullName>
                </value>
                <value>
                    <fullName>Unexcused Tardy</fullName>
                </value>
                <value>
                    <fullName>Missing</fullName>
                </value>
                <value>
                    <fullName>Exempt</fullName>
                </value>
                <value>
                    <fullName>Complete</fullName>
                </value>
                <value>
                    <fullName>Late</fullName>
                </value>
                <value>
                    <fullName>Incomplete</fullName>
                </value>
                <value>
                    <fullName>Default</fullName>
                </value>
                <value>
                    <fullName>Standards</fullName>
                </value>
                <value>
                    <fullName>Credit/No Credit</fullName>
                </value>
                <value>
                    <fullName>Points</fullName>
                </value>
                <value>
                    <fullName>0-100</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Picklist Value</label>
    <nameField>
        <label>Display Value</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Picklist Values</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Points__c.object
<CustomObject>
    <fields>
        <fullName>Category__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Category</label>
        <referenceTo>Picklist_Value__c</referenceTo>
        <relationshipLabel>Points Transactions</relationshipLabel>
        <relationshipName>Points_Transactions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Points__c</fullName>
        <label>Points</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Reference_Id__c</fullName>
        <externalId>true</externalId>
        <label>Reference Id</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Student_Section__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Student/Section</label>
        <referenceTo>Student_Section__c</referenceTo>
        <relationshipLabel>Points Transactions</relationshipLabel>
        <relationshipName>Points_Transactions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Student__c</fullName>
        <label>Student</label>
        <referenceTo>Student__c</referenceTo>
        <relationshipLabel>Points Transactions</relationshipLabel>
        <relationshipName>Points_Transactions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Points Transaction</label>
    <nameField>
        <displayFormat>PT-{000000}</displayFormat>
        <label>Points Transaction Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Points Transactions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Student__c.object
<CustomObject>
    <fields>
        <fullName>Reference_Id__c</fullName>
        <externalId>true</externalId>
        <inlineHelpText>Displays the Salesforce ID for this Student record. Do not modify this field.</inlineHelpText>
        <label>Reference Id</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>School__c</fullName>
        <inlineHelpText>Displays the name of the student&apos;s current SchoolForce school. You can click on the link to see the details of this school.</inlineHelpText>
        <label>School</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Students</relationshipLabel>
        <relationshipName>Students</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Student__c</fullName>
        <inlineHelpText>Displays the student&apos;s middle name.</inlineHelpText>
        <label>Student Middle Name</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <label>Student</label>
    <nameField>
        <label>Student Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Students</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Student_Section__c.object
<CustomObject>
    <fields>
        <fullName>Reference_ID__c</fullName>
        <description>Concatenated unique id = StudentReference_ID__c + Reference Legacy_ID__c</description>
        <externalId>true</externalId>
        <label>Reference ID</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>School__c</fullName>
        <formula>Student__r.School__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>School</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Student__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Student</label>
        <referenceTo>Student__c</referenceTo>
        <relationshipLabel>Section</relationshipLabel>
        <relationshipName>Student_Section</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Student/Section</label>
    <nameField>
        <displayFormat>SS-{000000}</displayFormat>
        <label>Student/Section ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Student/Section</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/Points_MatrixWrapper.cls
public with sharing class Points_MatrixWrapper {
    public static List<Picklist_Value__c> cats  {get;set;}
    public List<Points__c> points               {get;set;}
    public string studentName                   {get;set;}
    public id studentID                         {get;set;}
    public boolean isActive                     {get;set;}
    private id ssID;
    private List<Points__c> sorterHolder;
    public string SchoolId						{get;set;}
    
    
    public Points_MatrixWrapper(){
        cats = new List<Picklist_Value__c>();
        points = new List<Points__c>();
        studentName = '';
    }
    
    public Points_MatrixWrapper(Student_Section__c studentSection){
		Map<String ,Points__c> pointMap=new Map<String ,Points__c>();
		
		sorterHolder = studentSection.Points_Transactions__r;
		studentName = studentSection.Student__r.Name;
		studentID = studentSection.Student__c;
		ssID = studentSection.id;
		isActive = true;
		points = new List<Points__c>();
		schoolId = studentSection.Student__r.School__c;
		fillEmptyPoints();
	}
	
	public Points_MatrixWrapper(Student__c student){
		Map<String ,Points__c> pointMap=new Map<String ,Points__c>();
		
		sorterHolder = student.Points_Transactions__r;
		studentName = student.Name;
		studentID = student.id;
		isActive = true;
		points = new List<Points__c>();
		schoolID = student.School__c;
		fillEmptyPoints();
	}
    
    private void fillEmptyPoints(){
        Set<Id> pvIDs = new Set<ID>();
        Map<ID, Points__c> catMap = new Map<ID, Points__c>();
        if(cats == null || cats.isEmpty()){
            return;
        }
        if(!sorterHolder.isEmpty()){
        	for(Points__c p:sorterHolder){
        		catMap.put(p.Category__c, p);
        	}
        }
        for(Picklist_Value__c p:cats){
        	if(catMap.containsKey(p.id)){
        		points.add(catMap.get(p.id));
        	} else {
        		//new points are given a temp ref id to aid in locating them on the page
        		points.add(new Points__c(Student__c = studentID,
                            Student_Section__c = ssID,
                            Category__r = p,
                            Category__c = p.id,
                            Reference_Id__c = studentID + '_' + p.id
                        ));
        	}
        }
    }
}