objects/Points__c.object
<CustomObject>
    <fields>
        <fullName>Is_Redeem__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is_Redeem</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Points__c</fullName>
        <label>Points</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Reference_Id__c</fullName>
        <externalId>true</externalId>
        <label>Reference Id</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Student_Section__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Student/Section</label>
        <referenceTo>Student_Section__c</referenceTo>
        <relationshipLabel>Points Transactions</relationshipLabel>
        <relationshipName>Points_Transactions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Student__c</fullName>
        <label>Student</label>
        <referenceTo>Student__c</referenceTo>
        <relationshipLabel>Points Transactions</relationshipLabel>
        <relationshipName>Points_Transactions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Points Transaction</label>
    <nameField>
        <displayFormat>PT-{000000}</displayFormat>
        <label>Points Transaction Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Points Transactions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Student__c.object
<CustomObject>
    <fields>
        <fullName>Reference_Id__c</fullName>
        <externalId>true</externalId>
        <inlineHelpText>Displays the Salesforce ID for this Student record. Do not modify this field.</inlineHelpText>
        <label>Reference Id</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>School__c</fullName>
        <inlineHelpText>Displays the name of the student&apos;s current SchoolForce school. You can click on the link to see the details of this school.</inlineHelpText>
        <label>School</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Students</relationshipLabel>
        <relationshipName>Students</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Student__c</fullName>
        <inlineHelpText>Displays the student&apos;s middle name.</inlineHelpText>
        <label>Student Middle Name</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <label>Student</label>
    <nameField>
        <label>Student Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Students</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Student_Section__c.object
<CustomObject>
    <fields>
        <fullName>Reference_ID__c</fullName>
        <description>Concatenated unique id = StudentReference_ID__c + Reference Legacy_ID__c</description>
        <externalId>true</externalId>
        <label>Reference ID</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>School__c</fullName>
        <formula>Student__r.School__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>School</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Student__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Student</label>
        <referenceTo>Student__c</referenceTo>
        <relationshipLabel>Section</relationshipLabel>
        <relationshipName>Student_Section</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Student/Section</label>
    <nameField>
        <displayFormat>SS-{000000}</displayFormat>
        <label>Student/Section ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Student/Section</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/Points_RedeemWrapper.cls
public with sharing class Points_RedeemWrapper {
	public Points__c redeemPoint	{get;set;}
	public string studentName                   {get;set;}
    public id studentID                         {get;set;}
    public boolean isActive                     {get;set;}
    private id ssID;
    public id schoolId;
    
    public Points_RedeemWrapper(){
        redeemPoint = new Points__c();
        studentName = '';
        isActive = true;
    }
    
    public Points_RedeemWrapper(Student_Section__c studentSection){
    	ssID = studentSection.id;
    	studentName = studentSection.Student__r.Name;
		studentID = studentSection.Student__c;
		schoolId = studentSection.Student__r.School__c;
    	if(!studentSection.Points_Transactions__r.isEmpty())
			redeemPoint = studentSection.Points_Transactions__r[0];
		else
			fillEmptyPoints();
			
		
		isActive = true;
	}
	
	public Points_RedeemWrapper(Student__c student){
		studentName = student.Name;
		studentID = student.id;
		schoolId = student.School__c;
		if(!student.Points_Transactions__r.isEmpty())
			redeemPoint = student.Points_Transactions__r[0];
		else
			fillEmptyPoints();
			
		
		isActive = true;
	}
    
    private void fillEmptyPoints(){			
		redeemPoint = new Points__c(Student__c = studentID
                            ,Reference_Id__c=studentID
                            ,is_Redeem__c = true);
		if(ssID != null){
			redeemPoint.Student_Section__c = ssID;
			redeemPoint.Reference_Id__c += '_'+ssID;
		}
    }
}