objects/Program__c.object
<CustomObject>
    <description>Program is an Intervention object. Intervention Programs are aligned with Indicator Areas and are a high level set of activities with defined dosage goals. Each Program has its own frequency, target dosage, and recommended time per session. An example Program is one-on-one reading.</description>
    <label>Program</label>
    <nameField>
        <label>Program Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/Section__c.object
<CustomObject>
    <fields>
        <fullName>Program__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>What intervention Program is this Intervention Section for?</inlineHelpText>
        <label>Program</label>
        <referenceTo>Program__c</referenceTo>
        <relationshipLabel>Sections</relationshipLabel>
        <relationshipName>Sections</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Section__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Recursive lookup for groups</description>
        <label>Section</label>
        <referenceTo>Section__c</referenceTo>
        <relationshipLabel>Groups in Section</relationshipLabel>
        <relationshipName>Sections1</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Section</label>
    <nameField>
        <label>Section Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sections</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Student__c.object
<CustomObject>
    <fields>
        <fullName>Section__c</fullName>
        <inlineHelpText>Displays the student&apos;s current homeroom name or room number. This field can be used for reporting purposes.</inlineHelpText>
        <label>Current Homeroom</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Student__c</fullName>
        <inlineHelpText>Displays the student&apos;s middle name.</inlineHelpText>
        <label>Student Middle Name</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <label>Student</label>
    <nameField>
        <label>Student Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Students</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Student_Program__c.object
<CustomObject>
    <description>This is an object is students/program roll up</description>
    <fields>
        <fullName>Amount_of_Time__c</fullName>
        <label>Total Time for Program</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Program1__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Program Name</label>
        <referenceTo>Program__c</referenceTo>
        <relationshipLabel>Student/Programs</relationshipLabel>
        <relationshipName>Student_Programs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Program__c</fullName>
        <formula>IF(  ISBLANK( Section_del__r.Program__c ) ,  &quot;&quot; ,   Section_del__r.Program__r.Name  )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Program</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Reference__c</fullName>
        <caseSensitive>true</caseSensitive>
        <externalId>true</externalId>
        <label>Reference</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Student__c</fullName>
        <description>Student/Program</description>
        <label>Student</label>
        <referenceTo>Student__c</referenceTo>
        <relationshipLabel>Student/Programs</relationshipLabel>
        <relationshipName>Student_Programs</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Student/Program</label>
    <nameField>
        <displayFormat>SP-{0000}</displayFormat>
        <label>Student/Program Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Student/Programs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Student_Section__c.object
<CustomObject>
    <fields>
        <fullName>Amount_of_Time__c</fullName>
        <label>Amount of time per section</label>
        <summarizedField>Intervention_Session_Result__c.Amount_of_Time__c</summarizedField>
        <summaryForeignKey>Intervention_Session_Result__c.Student_Section__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Program__c</fullName>
        <formula>CASESAFEID(Section__r.Program__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Program</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Section__c</fullName>
        <label>Section</label>
        <referenceTo>Section__c</referenceTo>
        <relationshipLabel>Student</relationshipLabel>
        <relationshipName>Student_Section</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Student_Program__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Student/Program</label>
        <referenceTo>Student_Program__c</referenceTo>
        <relationshipLabel>Student/Section</relationshipLabel>
        <relationshipName>Student_Section</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Student__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Student</label>
        <referenceTo>Student__c</referenceTo>
        <relationshipLabel>Section</relationshipLabel>
        <relationshipName>Student_Section</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Student/Section</label>
    <nameField>
        <displayFormat>SS-{000000}</displayFormat>
        <label>Student/Section ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Student/Section</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/StudentSectionUtils.cls
global class StudentSectionUtils {

	//fill field Student_Program__c on Student_Section__c object 
	public static void fillStudentProgramField(List<Student_Section__c> listStudentSection, Map<Id, Student_Section__c> oldMap){
		Set<String> programIds = new Set<String>();
		Set<String> studentIds = new Set<String>();
		List<Student_Section__c> lstSS = new List<Student_Section__c>();
		for(Student_Section__c ss: listStudentSection){
			if(ss.Student__c != null && ss.Program__c != null && (oldMap==null || ss.Student_Program__c == null || 
					ss.Program__c != oldMap.get(ss.Id).Program__c || ss.Student__c != oldMap.get(ss.Id).Student__c)){
				programIds.add(ss.Program__c);
				studentIds.add(ss.Student__c);
				lstSS.add(ss);
			}
		}
		if(programIds.isEmpty() || studentIds.isEmpty()){
			return;
		}

		Map<String, Student_Program__c> mapStudent2Program = new Map<String, Student_Program__c>();
		for(Student_Program__c studentProgram: [SELECT Id, Student__c, Program1__c, Program__c, Reference__c FROM Student_Program__c 
					WHERE Program1__c IN :programIds AND Student__c IN :studentIds]){
			String key = studentProgram.Student__c + '#' + studentProgram.Program1__c;
			mapStudent2Program.put(key, studentProgram);
		}

		for(Student_Section__c studentSection: lstSS){
			String key = studentSection.Student__c + '#' + studentSection.Program__c;
			//check if Student_Program exists
			if(!mapStudent2Program.containsKey(key)){
				Student_Program__c studentProgram = new Student_Program__c(
						Student__c = studentSection.Student__c, 
						Program1__c = studentSection.Program__c,
						Reference__c = key
						);
				mapStudent2Program.put(key, studentProgram);			
			}
		}

		//upsert Student_Program__c objects
		if(!mapStudent2Program.isEmpty()){
			upsert mapStudent2Program.values();
		}
		
		//update field Student_Program__c
		for(Student_Section__c studentSection: lstSS){
			String key = studentSection.Student__c + '#' + studentSection.Program__c;
			studentSection.Student_Program__c = mapStudent2Program.get(key).Id;
		}
	}

    public static void calculateAmountOfTime(List<Student_Section__c> lstSS, Map<Id, Student_Section__c> oldMap){
		Set<String> studentProgramIds = new Set<String>();
		for(Student_Section__c ss: lstSS){
			if(oldMap==null || (ss.Amount_of_Time__c != oldMap.get(ss.Id).Amount_of_Time__c && ss.Student_Program__c!=null)){
				studentProgramIds.add(ss.Student_Program__c);
			}
		}

		if(!studentProgramIds.isEmpty()){
			List<Student_Section__c> lSS = new List<Student_Section__c>( [SELECT Id, Amount_of_Time__c, Student_Program__c 
					FROM Student_Section__c WHERE Student_Program__c != NULL AND Student_Program__c IN :studentProgramIds]);
	        if(!lSS.isEmpty()){
	        	//calculate sum of time			
	       	 	Map<String, Decimal> mapIdToSum = calcSP2Hours(lSS);
	        	//save sum
				List<Student_Program__c> listSP = populateSPs(mapIdToSum);
				update listSP;
			}
		}
    }   

    //remove studentprogram
    public static void removeStudentPrograms(List<Student_Section__c> lstSS){
    	List<Student_Section__c> lSS = new List<Student_Section__c>();
    	Set<Id> spIds = new Set<Id>();
    	for(Student_Section__c ss: lstSS){
    		spIds.add(ss.Student_Program__c);
    	}
    	spIds.remove(null);

    	if(!spIds.isEmpty()){
			lSS = new List<Student_Section__c>( [SELECT Id, Amount_of_Time__c, Student_Program__c FROM Student_Section__c 
	                    WHERE Student_Program__c != NULL AND Student_Program__c IN :spIds AND Id NOT IN :lstSS]);
    	}

    	//recalc hours
    	if(!lSS.isEmpty()){
    		Map<String, Decimal> mapIdToSum = calcSP2Hours(lSS);
			List<Student_Program__c> listSP = populateSPs(mapIdToSum);
	        //update SP
	        update listSP;
    	}

    	for(Student_Section__c ss: lSS){
 	        //uses another sections
 	        spIds.remove(ss.Student_Program__c);
    	}
    	//remove SP    	
    	if(!spIds.isEmpty()){
	    	List<Student_Program__c> lstSP = new List<Student_Program__c>();
	    	for(Id idx: spIds){
	    		lstSP.add(new Student_Program__c(Id = idx));
	    	}
	    	delete lstSP;
	    }
    }

    public static void removeStudentPrograms(List<Section__c> lstS){
	    List<Student_Section__c> lstSS = [SELECT Id, Amount_of_Time__c, Student_Program__c FROM Student_Section__c 
	            WHERE Student_Program__c != NULL AND Section__c IN :lstS];

	    if(lstSS!=null && !lstSS.isEmpty()){
	    	StudentSectionUtils.removeStudentPrograms(lstSS);
	    }
    }

    private static Map<String, Decimal> calcSP2Hours(List<Student_Section__c> lstSS){
        Map<String, Decimal> mapSP2Sum = new Map<String, Decimal>();
        for(Student_Section__c ss: lstSS){
        	//recalc hours
        	Decimal currentValue =  mapSP2Sum.containsKey(ss.Student_Program__c)?mapSP2Sum.get(ss.Student_Program__c):0;
        	mapSP2Sum.put(ss.Student_Program__c, currentValue + ss.Amount_of_Time__c); 	        	
    	}
    	return mapSP2Sum;
    }

    private static List<Student_Program__c> populateSPs(Map<String, Decimal> mapSP2Sum){
        List<Student_Program__c> listSP = new List<Student_Program__c>();
        for(String key: mapSP2Sum.keySet()){
            listSP.add(new Student_Program__c(Id = key, Amount_of_Time__c = mapSP2Sum.get(key)));
        }
        return listSP;
    }
 
}