objects/Room__c.object
<CustomObject>
    <fields>
        <fullName>Reference_Id__c</fullName>
        <externalId>true</externalId>
        <label>Reference Id</label>
        <length>200</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Schedulable__c</fullName>
        <defaultValue>true</defaultValue>
        <inlineHelpText>Select this checkbox if the room is used for scheduling purposes.</inlineHelpText>
        <label>Use for Scheduling</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>School__c</fullName>
        <label>School</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Rooms</relationshipLabel>
        <relationshipName>Rooms</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Room</label>
    <nameField>
        <label>Room Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Rooms</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Scheduled_Section__c.object
<CustomObject>
    <fields>
        <fullName>Reference_Id__c</fullName>
        <description>Key for Section Scheduled: Setup-Reporting Period-Teacher-Group/Period</description>
        <externalId>true</externalId>
        <label>Reference Id</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Room__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Room</label>
        <referenceTo>Room__c</referenceTo>
        <relationshipName>Schedule_Templates</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Section_ReportingPeriod__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Section/ReportingPeriod</label>
        <referenceTo>Section_ReportingPeriod__c</referenceTo>
        <relationshipLabel>Scheduled Sections</relationshipLabel>
        <relationshipName>Scheduled_Sections</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Section__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Section</label>
        <referenceTo>Section__c</referenceTo>
        <relationshipLabel>Scheduled Sections</relationshipLabel>
        <relationshipName>Scheduled_Sections</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Scheduled Section</label>
    <nameField>
        <label>Scheduled Section Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Scheduled Sections</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Section__c.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Check this box if the section is a currently active section</description>
        <inlineHelpText>Check this box if the section is a currently active section</inlineHelpText>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Available_Grade_Levels__c</fullName>
        <description>Used for &quot;Mass Create Sections&quot; button</description>
        <label>Available Grade Levels</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>PS</fullName>
                </value>
                <value>
                    <fullName>PK</fullName>
                </value>
                <value>
                    <fullName>K</fullName>
                </value>
                <value>
                    <fullName>1</fullName>
                </value>
                <value>
                    <fullName>2</fullName>
                </value>
                <value>
                    <fullName>3</fullName>
                </value>
                <value>
                    <fullName>4</fullName>
                </value>
                <value>
                    <fullName>5</fullName>
                </value>
                <value>
                    <fullName>6</fullName>
                </value>
                <value>
                    <fullName>7</fullName>
                </value>
                <value>
                    <fullName>8</fullName>
                </value>
                <value>
                    <fullName>9</fullName>
                </value>
                <value>
                    <fullName>10</fullName>
                </value>
                <value>
                    <fullName>11</fullName>
                </value>
                <value>
                    <fullName>12</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Number_of_Reporting_Periods__c</fullName>
        <inlineHelpText>Select the number of reporting periods this section meets. SchoolForce will create a section square in each reporting period for the number you select. A grade weighting must be set up in the course for the selected number of reporting periods.</inlineHelpText>
        <label>Number of Reporting Periods</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>1</fullName>
                    <default>true</default>
                    <label>1</label>
                </value>
                <value>
                    <fullName>2</fullName>
                </value>
                <value>
                    <fullName>3</fullName>
                </value>
                <value>
                    <fullName>4</fullName>
                </value>
                <value>
                    <fullName>5</fullName>
                </value>
                <value>
                    <fullName>6</fullName>
                </value>
                <value>
                    <fullName>7</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Reference_Id__c</fullName>
        <externalId>true</externalId>
        <label>Reference Id</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Room__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Room</label>
        <referenceTo>Room__c</referenceTo>
        <relationshipLabel>Sections</relationshipLabel>
        <relationshipName>Sections</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>School__c</fullName>
        <label>School</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Sections</relationshipLabel>
        <relationshipName>Sections</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Section__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Recursive lookup for groups</description>
        <label>Section</label>
        <referenceTo>Section__c</referenceTo>
        <relationshipLabel>Groups in Section</relationshipLabel>
        <relationshipName>Sections1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Time__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Time</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Time_Element__c.Picklist_Value__r.Name</field>
                <operation>equals</operation>
                <value>Year</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Time_Element__c</referenceTo>
        <relationshipLabel>Sections</relationshipLabel>
        <relationshipName>Sections</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Section</label>
    <nameField>
        <label>Section Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sections</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Section_ReportingPeriod__c.object
<CustomObject>
    <fields>
        <fullName>Section__c</fullName>
        <label>Section</label>
        <referenceTo>Section__c</referenceTo>
        <relationshipLabel>Section/ReportingPeriod</relationshipLabel>
        <relationshipName>Section_ReportingPeriod</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Time__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Time</label>
        <referenceTo>Time_Element__c</referenceTo>
        <relationshipLabel>Section/ReportingPeriod</relationshipLabel>
        <relationshipName>Section_ReportingPeriod</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Section/ReportingPeriod</label>
    <nameField>
        <displayFormat>SR-{000000}</displayFormat>
        <label>Section/ReportingPeriod</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Section/ReportingPeriod</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Term__c.object
<CustomObject>
    <description>Junction object  between Time and Setup.</description>
    <fields>
        <fullName>Time_Element__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Time Element</label>
        <referenceTo>Time_Element__c</referenceTo>
        <relationshipLabel>Terms</relationshipLabel>
        <relationshipName>Terms</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Term</label>
    <nameField>
        <displayFormat>Term-{000000}</displayFormat>
        <label>Term Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Terms</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Time_Element__c.object
<CustomObject>
    <fields>
        <fullName>Reference_Id__c</fullName>
        <externalId>true</externalId>
        <label>Reference Id</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>School__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>School</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Time</relationshipLabel>
        <relationshipName>Time</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Time</label>
    <nameField>
        <displayFormat>T-{000000}</displayFormat>
        <label>Time Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Time</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/CT_Test_Scheduler_Grid.cls
@isTest
private  class CT_Test_Scheduler_Grid {
	static testMethod void test_SchedulerGrid(){
		testDataSetupUtil_v2.setUPCoreData(5);
		testDataSetupUtil_v2.setupStaffData(5); 
		CT_mock_setupUtil.setupScheduleTemplates(testDataSetupUtil_v2.activeSetup);
		PageReference pr2 = new PageReference('/apex/CT_scheduler_Grid?setupid='+testDataSetupUtil_v2.activeSetup.id);
		test.startTest();
			test.setCurrentPage(pr2);
			CT_scheduler_Grid gridController = new CT_scheduler_Grid();
			gridController.rpId = testDataSetupUtil_v2.semester.id;
			gridController.setupId=testDataSetupUtil_v2.activeSetup.id;
			gridController.initScheduleGrid();
			gridController.newSection();
			gridController.newSectionMass();
			gridController.selectedCourse = testDataSetupUtil_v2.coursesList[0].id;
			gridController.section.name= 'Test Section 1';
			gridController.section.number_of_reporting_periods__c = '2';
			gridController.section.Active__c = true;
			gridController.section.Time__c=	testDataSetupUtil_v2.semester.id;
			//gridController.section.Available_Grade_Levels__c='PS; PK; K; 1; 2; 3; 4; 5; 6; 7; 8; 9; 10; 11; 12';
			gridController.saveSection();
			Section_ReportingPeriod__c srp= [select id, section__c from Section_ReportingPeriod__c where section__r.name='Test Section 1' and Time__c =:testDataSetupUtil_v2.semester.id];
			section__c sec =[select id,name from section__c where name='Test Section 1'];
			sec.Available_Grade_Levels__c='PS; PK; K; 1; 2; 3; 4; 5; 6; 7; 8; 9; 10; 11; 12';
			update sec;
			gridController.section=sec;
			gridController.saveSection();
			gridController.processView();
			/* New Save method for Ohio*/
			String arrayString = ';'+srp.id+';'+gridController.periodList[0].key__c+';'+testDataSetupUtil_v2.teachersList[0].id+';'+ testDataSetupUtil_v2.roomList[0].id;
			string [] deleteList = new String[]{};
			CT_scheduler_Grid.saveSections_Remote(arrayString, deleteList);
			
			List <Scheduled_Section__c> ssList = [select id from Scheduled_Section__c where section_reportingPeriod__c=:srp.id];
			ApexPages.currentPage().getParameters().put('cmc',ssList[0].id);
			ApexPages.currentPage().getParameters().put('deleteList',ssList[0].id);
			gridController.saveSections();
			Set<id> ssIdset = new Set<Id>();
			ssIdset.add(ssList[0].id);
			gridController.deleteSessions(ssIdset);
			gridController.updateSecRepPeriods(ssIdset);
			deleteList.add(ssList[0].id);
			arrayString ='';
			CT_scheduler_Grid.saveSections_Remote(arrayString, deleteList);
			
			arrayString = ';'+srp.id+';'+gridController.periodList[1].key__c+';'+testDataSetupUtil_v2.teachersList[0].id+';'+ testDataSetupUtil_v2.roomList[0].id;
			deleteList.clear();
			CT_scheduler_Grid.saveSections_Remote(arrayString, deleteList);
			
			gridController.processView();
			gridController.sectionId = srp.section__c;// gridController.rowList[0].scheduledSections[0].sectId;
			gridController.editSection();
			List<Id> newlist = new List<id>();
			newlist.add(testDataSetupUtil_v2.coursesList[0].id);
			gridController.selectedCourses=newlist;
			gridController.section=sec;
			gridController.saveSectionMass();
			gridController.cancelSection();
			gridController.processView();
			List <Time_Element__c> teList = CT_core_SoqlUtils.getTimeElementsByTerm(testDataSetupUtil_v2.activeSetup.term__c, true);
			PageReference pr3 = new PageReference('/apex/CT_scheduler_Grid?setupid='+testDataSetupUtil_v2.activeSetup.id+'&id='+testDataSetupUtil_v2.semester2.id);
			test.setCurrentPage(pr3);
			CT_scheduler_Grid gridController2 = new CT_scheduler_Grid();
			gridController.rpId = testDataSetupUtil_v2.semester.id;
			gridController.initScheduleGrid();
			gridController2.rpId = testDataSetupUtil_v2.semester2.id;
			gridController2.initScheduleGrid();
			gridController2.selectedCopyRp = testDataSetupUtil_v2.semester.id;
			gridController2.copyScheduledSectionsForNewRp();
			gridController.prev();
			gridController.bOccupancyError=true;
			gridController.next();
			CT_scheduler_Grid.massStaffMultiSelector wrapp = new CT_scheduler_Grid.massStaffMultiSelector();
			List<id> staffId = new List<Id>{srp.section__c};
			wrapp.leftselected=staffId;
			wrapp.rightselected=staffId;
			wrapp.selectclick();
			wrapp.unselectclick();
			wrapp.getSelectedValues();
			wrapp.getunSelectedValues();
			List<string> gradeList = new List<string>{'4','5'};
			wrapp.addGrades(gradeList);
		test.stopTest();
		//	system.assert( gridController2.unpublishedSectionList.size()==1);
	}
	
	
	static testMethod void test_SchedulerGrid2(){
		testDataSetupUtil_v2.setUPCoreData(5);
		testDataSetupUtil_v2.setupStaffData(5); 
		CT_mock_setupUtil.setupScheduleTemplates(testDataSetupUtil_v2.activeSetup);
		testDataSetupUtil_v2.activeSetup.room_Dependent__c=true;
		Room__c r = new Room__c(School__c = testDataSetupUtil_v2.school.id, Schedulable__c=true, Reference_Id__c ='101' );
		insert r; 
		PageReference pr2 = new PageReference('/apex/CT_scheduler_Grid?setupid='+testDataSetupUtil_v2.activeSetup.id+'&id='+testDataSetupUtil_v2.semester.id);
		test.startTest();
			test.setCurrentPage(pr2);
			CT_scheduler_Grid gridController = new CT_scheduler_Grid();
			gridController.rpId = testDataSetupUtil_v2.semester.id;
			gridController.initScheduleGrid();
			gridController.newSection();
			gridController.selectedCourse = testDataSetupUtil_v2.coursesList[0].id;
			gridController.section.name= 'Test Section 1';
			gridController.section.Number_of_Reporting_Periods__c = '2';
			gridController.section.Active__c = true;			
			gridController.saveSection();
			Section_ReportingPeriod__c srp= [select id, section__c from Section_ReportingPeriod__c where section__r.name='Test Section 1' and Time__c =:testDataSetupUtil_v2.semester.id];
			ApexPages.currentPage().getParameters().put('selectedType','r');
			ApexPages.currentPage().getParameters().put('selectedTab','0');
			gridController.refreshGrid();
			gridController.sErrorMessages.add('test');
			gridController.processErrorMessages();
			gridController.selectedStaffFilter= new List <Id>{testDataSetupUtil_v2.teachersList[0].id};
			gridController.filterStaff();
			CT_scheduler_Grid.cRowWrapper cr = new CT_scheduler_Grid.cRowWrapper(testDataSetupUtil_v2.teachersList[0]);
			CT_scheduler_Grid.cRowWrapper cr2 = new CT_scheduler_Grid.cRowWrapper(r);
		test.stopTest();
	}
}