objects/Schedule_Template__c.object
<CustomObject>
    <fields>
        <fullName>Color__c</fullName>
        <description>Hex # that represents the color of the template</description>
        <label>Color</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>End_Time__c</fullName>
        <label>End Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Has_Class__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Has Class?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Is_Master__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Master</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Reporting_Period__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Reporting Period</label>
        <referenceTo>Time_Element__c</referenceTo>
        <relationshipLabel>Schedule Templates</relationshipLabel>
        <relationshipName>Schedule_Templates</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Setup__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Setup</label>
        <referenceTo>Setup__c</referenceTo>
        <relationshipLabel>Schedule Templates</relationshipLabel>
        <relationshipName>Schedule_Templates</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Start_Time__c</fullName>
        <label>Start Time</label>
        <type>DateTime</type>
    </fields>
    <label>Schedule Template</label>
    <nameField>
        <label>Schedule Template Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Schedule Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Setup__c.object
<CustomObject>
    <description>This object is used to setup Schoolforce and is referenced in multiple pieces of code.  There should be one setup object per school.</description>
    <label>Setup</label>
    <nameField>
        <displayFormat>S-{0}</displayFormat>
        <label>Setup ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Setup</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

classes/TestReportingPeriodCalendarController.cls
@isTest
private class TestReportingPeriodCalendarController {
	
	static testMethod void myUnitTest() {
		TestDataSetupUtil_v2.setUPCoreData(5);
		
		Schedule_Template__c st = new Schedule_Template__c(Setup__c=TestDataSetupUtil_v2.activeSetUp.id, has_class__c = true,Reporting_Period__c= TestDataSetupUtil_v2.semester.id, Is_Master__c=true ,color__c='#ff0000' );
		st.start_time__c =  dateTime.newInstance(system.today().year(), system.today().addmonths(1).month(), system.today().day(), 9,0,0);
		st.end_time__c =  st.start_time__c.addHours(8);
		insert st;
	
		Schedule_Template__c st2 = new Schedule_Template__c(Setup__c=TestDataSetupUtil_v2.activeSetUp.id, has_class__c = true,Reporting_Period__c= TestDataSetupUtil_v2.semester2.Id, Is_Master__c=true ,color__c='#ff0000' );
		st.start_time__c =  dateTime.newInstance(system.today().year(), system.today().addmonths(1).month(), system.today().day(), 9,0,0);
		st.end_time__c =  st.start_time__c.addHours(8);
		insert st2;
		
		PageReference testPage = new PageReference('/apex/ReportingPeriodCalendarView?setupid='+TestDataSetupUtil_v2.activeSetUp.id);

		Test.setCurrentPage(testPage);
		ReportingPeriodCalendarController controller = new ReportingPeriodCalendarController();
		//system.debug('~~~~~' +controller.repPeriodCal);
		controller.save();
		date d= TestDataSetupUtil_v2.semester.Date_Start_Date__c;
		integer dayCount = 0;
		while (d <= TestDataSetupUtil_v2.semester.End_Date__c){
			if (d.daysBetween(d.toStartOfWeek())!=0&&d.daysBetween(d.toStartOfWeek())!=-6){
				dayCount++;
				system.debug(d.daysBetween(d.toStartOfWeek()));
				system.debug(d);
			}
			d = d.addDays(1);
		}
		system.assertEquals(dayCount,controller.scheduleDaysList.size());
		system.debug(controller.repPeriodCal.repPeriodIdToName.values());
		system.assertEquals(2,controller.repPeriodCal.repPeriodIdToName.values().size());
		
		

	}
}