objects/Schedule_Group__c.object
<CustomObject>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Grade_Level__c</fullName>
        <label>Grade Level</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>K</fullName>
                </value>
                <value>
                    <fullName>1</fullName>
                </value>
                <value>
                    <fullName>2</fullName>
                </value>
                <value>
                    <fullName>3</fullName>
                </value>
                <value>
                    <fullName>4</fullName>
                </value>
                <value>
                    <fullName>5</fullName>
                </value>
                <value>
                    <fullName>6</fullName>
                </value>
                <value>
                    <fullName>7</fullName>
                </value>
                <value>
                    <fullName>8</fullName>
                </value>
                <value>
                    <fullName>9</fullName>
                </value>
                <value>
                    <fullName>10</fullName>
                </value>
                <value>
                    <fullName>11</fullName>
                </value>
                <value>
                    <fullName>12</fullName>
                </value>
                <value>
                    <fullName>PS</fullName>
                </value>
                <value>
                    <fullName>PK</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Reference_Id__c</fullName>
        <description>Key for Scheduler</description>
        <externalId>true</externalId>
        <label>Reference Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Setup__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Setup</label>
        <referenceTo>Setup__c</referenceTo>
        <relationshipLabel>Schedule Groups</relationshipLabel>
        <relationshipName>Schedule_Groups</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Schedule Group</label>
    <nameField>
        <label>Schedule Group Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Schedule Groups</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Schedule_Template__c.object
<CustomObject>
    <fields>
        <fullName>End_Time_Text__c</fullName>
        <label>End Time Text</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Has_Class__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Has Class?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Is_Master__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Master</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Reference_Id__c</fullName>
        <externalId>true</externalId>
        <label>Reference Id</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Reporting_Period__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Reporting Period</label>
        <referenceTo>Time_Element__c</referenceTo>
        <relationshipLabel>Schedule Templates</relationshipLabel>
        <relationshipName>Schedule_Templates</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Setup__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Setup</label>
        <referenceTo>Setup__c</referenceTo>
        <relationshipLabel>Schedule Templates</relationshipLabel>
        <relationshipName>Schedule_Templates</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Start_Time_Text__c</fullName>
        <label>Start Time Text</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>Schedule Template</label>
    <nameField>
        <label>Schedule Template Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Schedule Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Scheduled_Section__c.object
<CustomObject>
    <fields>
        <fullName>End_Time_Text__c</fullName>
        <label>End Time Text</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Grade_Level__c</fullName>
        <formula>TEXT(Schedule_Group__r.Grade_Level__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Grade Level</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Record_Attendance__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Record Attendance</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Reference_Id__c</fullName>
        <description>Key for Section Scheduled: Setup-Reporting Period-Teacher-Group/Period</description>
        <externalId>true</externalId>
        <label>Reference Id</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Reporting_Period__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Reporting Period</label>
        <referenceTo>Time_Element__c</referenceTo>
        <relationshipLabel>Scheduled Sections</relationshipLabel>
        <relationshipName>Scheduled_Sections</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Rounded_Start_Time__c</fullName>
        <label>Rounded Start Time</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Schedule_Group__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Schedule Group</label>
        <referenceTo>Schedule_Group__c</referenceTo>
        <relationshipLabel>Scheduled Sections</relationshipLabel>
        <relationshipName>Scheduled_Sections</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Schedule_Template__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Schedule Template</label>
        <referenceTo>Schedule_Template__c</referenceTo>
        <relationshipLabel>Scheduled Sections</relationshipLabel>
        <relationshipName>Scheduled_Sections</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Section__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Section</label>
        <referenceTo>Section__c</referenceTo>
        <relationshipLabel>Scheduled Sections</relationshipLabel>
        <relationshipName>Scheduled_Sections</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Staff__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Staff</label>
        <referenceTo>Staff__c</referenceTo>
        <relationshipName>Schedule_Templates</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Start_Time_Text__c</fullName>
        <label>Start Time Text</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>Scheduled Section</label>
    <nameField>
        <label>Scheduled Section Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Scheduled Sections</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Section__c.object
<CustomObject>
    <fields>
        <fullName>Description__c</fullName>
        <inlineHelpText>Enter a description of the section. This field only displays in the Description field on the Section record. You can use it on reports.</inlineHelpText>
        <label>Description</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Grade_Level__c</fullName>
        <inlineHelpText>Select the grade level of the course, if desired. SchoolForce uses the All Grades list box to determine the grade level(s) for which the section is available. You can use the Grade Level drop-down list on reports.</inlineHelpText>
        <label>Grade Level</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>PS</fullName>
                </value>
                <value>
                    <fullName>PK</fullName>
                </value>
                <value>
                    <fullName>K</fullName>
                </value>
                <value>
                    <fullName>1</fullName>
                </value>
                <value>
                    <fullName>2</fullName>
                </value>
                <value>
                    <fullName>3</fullName>
                </value>
                <value>
                    <fullName>4</fullName>
                </value>
                <value>
                    <fullName>5</fullName>
                </value>
                <value>
                    <fullName>6</fullName>
                </value>
                <value>
                    <fullName>7</fullName>
                </value>
                <value>
                    <fullName>8</fullName>
                </value>
                <value>
                    <fullName>9</fullName>
                </value>
                <value>
                    <fullName>10</fullName>
                </value>
                <value>
                    <fullName>11</fullName>
                </value>
                <value>
                    <fullName>12</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Record_Attendance__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Should attendance be recorded for this section?</description>
        <inlineHelpText>Leave this check box selected if staff members will take daily or sectional attendance in this section. This field determines whether or not this section is available in the Attendance Wizard.</inlineHelpText>
        <label>Record Attendance</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Reference_Id__c</fullName>
        <externalId>true</externalId>
        <label>Reference Id</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Reporting_Period__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Usually the only reporting period; could be the first if the section spans multiple reporting periods.</description>
        <label>Reporting Period</label>
        <referenceTo>Time_Element__c</referenceTo>
        <relationshipLabel>Sections (First Reporting Period)</relationshipLabel>
        <relationshipName>Sections1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Schedule_Group__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Parent Schedule Group related to this section</description>
        <label>Schedule Group</label>
        <referenceTo>Section__c</referenceTo>
        <relationshipLabel>Sections (Schedule Group)</relationshipLabel>
        <relationshipName>Schedule_Group_Sections</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Section__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Recursive lookup for groups</description>
        <label>Section</label>
        <referenceTo>Section__c</referenceTo>
        <relationshipLabel>Groups in Section</relationshipLabel>
        <relationshipName>Sections1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Staff__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Staff</label>
        <referenceTo>Staff__c</referenceTo>
        <relationshipLabel>Sections</relationshipLabel>
        <relationshipName>Sections</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Section</label>
    <nameField>
        <label>Section Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sections</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Setup__c.object
<CustomObject>
    <description>This object is used to setup Schoolforce and is referenced in multiple pieces of code.  There should be one setup object per school.</description>
    <label>Setup</label>
    <nameField>
        <displayFormat>S-{0}</displayFormat>
        <label>Setup ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Setup</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/Staff__c.object
<CustomObject>
    <fields>
        <fullName>First_Name_Staff__c</fullName>
        <label>Staff First Name</label>
        <length>80</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Reference_Id__c</fullName>
        <externalId>true</externalId>
        <label>Reference Id</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Staff_Last_Name__c</fullName>
        <label>Staff Last Name</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <label>Staff</label>
    <nameField>
        <label>Staff Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Staff</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

classes/TestGroupAgendaView.cls
@isTest
private class TestGroupAgendaView {
	public static List<Schedule_Group__c> 	schedGrpsList; //no longer used Chicago release
	public static List<Section__c>			schedGrpsList_Section;
   
   	public static void createTestData(){    	
    	TestDataSetupUtil_v2.setUPCoreData(3);
    	TestDataSetupUtil_v2.setUpStaffData(5);
    	TestDataSetupUtil_v2.setUpStudentData(5);
    	schedGrpsList_Section = TestDataSetupUtil_v2.getScheduleGroups_Section();
    }
	
    static testMethod void testScheduleTemplateForGroups_New() {
    	createTestData();
    	PageReference scheduleTemplatePage = Page.core_ScheduleTemplate;
        scheduleTemplatePage.getParameters().put('setupId',testDataSetupUtil_v2.activeSetup.id);
        Test.setCurrentPage(scheduleTemplatePage);
    	//Setup Page
		Test.startTest();
			core_scheduleTemplateConfiguration controller = new core_scheduleTemplateConfiguration();
			controller.rpID = testDataSetupUtil_v2.semester.id;
			controller.initTemplate();
			controller.bIsClone = false;
			controller.schedTemplate.name = 'Master temp';
			controller.schedTemplate.Is_Master__c = true;
			controller.schedTemplate.Start_Time_Text__c = '8:00 AM';
			controller.schedTemplate.End_Time_Text__c = '5:00 PM';
			controller.schedTemplate.Has_Class__c = true;
			controller.saveSchedGrp();
		
		Schedule_Template__c st = new Schedule_Template__c();
		st = [SELECT Name,Id, Is_Master__c ,has_class__c,Start_Time_Text__c, End_Time_Text__c FROM Schedule_Template__c WHERE Id = : controller.schedTemplate.Id];
		
		System.assertEquals('Master temp', st.Name);
		System.assertEquals(true, st.Is_Master__c);
		System.assertEquals('8:00 AM', st.Start_Time_Text__c);
		System.assertEquals('5:00 PM', st.End_Time_Text__c);
		/********************  TEST Error Messages ****************************************************************/
		controller.templateId = 	st.Id;
		controller.initTemplate();
		controller.schedTemplate.End_Time_Text__c = '';
		controller.schedTemplate.Start_Time_Text__c = '';
		controller.saveSchedGrp();
		for(ApexPages.Message m : ApexPages.getMessages()){
			if(m.getDetail() == 'You must include both a start and end time for a scheduled section.')
			System.assert(true);
		}
		
		controller.schedTemplate.End_Time_Text__c = '8:00 AM';
		controller.schedTemplate.Start_Time_Text__c = '6:00 PM';
		controller.saveSchedGrp();
		for(ApexPages.Message m : ApexPages.getMessages()){
			if(m.getDetail() == 'End Time must be greater than the Start Time')
			System.assert(true);
		}
		
    	/********************************Test Creating New Scheduled Sections***********************************************************************/
    		PageReference groupAgendaViewPage = Page.GroupAgendaView;
    		groupAgendaViewPage.getParameters().put('setupId',testDataSetupUtil_v2.activeSetup.id);
        	Test.setCurrentPage(groupAgendaViewPage);
    		GroupAgendaViewController gavc = new GroupAgendaViewController();
    		gavc.schedTempId = st.id;
    		gavc.reptPeriod = testDataSetupUtil_v2.semester.id;
    		gavc.initAgendaView();

    			/****************************** Test the list of staff, courses and rooms associated with the setup *******************************************************/
    			for(Integer i = 0;i < testDataSetupUtil_v2.roomList.size();i++){
    				system.debug(gavc.gavw);
    				system.debug(gavc.gavw.roomOptionList[i].getlabel());
    			System.assertEquals(String.valueOf(testDataSetupUtil_v2.roomList[i].Number__c), gavc.gavw.roomOptionList[i].getlabel());
    			}
    			for(Integer i = 0;i < testDataSetupUtil_v2.teachersList.size();i++){
    			//System.assertEquals(testDataSetupUtil_v2.teachersList[i].First_Name_Staff__c + ' '+testDataSetupUtil_v2.teachersList[i].Staff_Last_Name__c, gavc.gavw.staffOptionList[i].getlabel());
    			}
    			for(Integer i = 0;i < testDataSetupUtil_v2.coursesList.size();i++){
    			System.assertEquals(String.valueOf(testDataSetupUtil_v2.coursesList[i].Name), gavc.gavw.courseOptionList[i].getlabel());
    			}
    			System.debug('$$$$$Schedule_Template__c'+gavc.schedTempId);
    		
    			/* *********************************TEST ERROR MESSAGES *****************************************************************************/
    			Apexpages.currentPage().getParameters().put('staffId',testDataSetupUtil_v2.staffSectionsList[0].staff__c);
				Apexpages.currentPage().getParameters().put('roomId',testDataSetupUtil_v2.roomList[0].id);
				Apexpages.currentPage().getParameters().put('courseId',testDataSetupUtil_v2.coursesList[0].Id);
				Apexpages.currentPage().getParameters().put('startTime','');
				Apexpages.currentPage().getParameters().put('endTime','');
				Apexpages.currentPage().getParameters().put('dailyAtt','false');
				Apexpages.currentPage().getParameters().put('recordAtt','false');
				Apexpages.currentPage().getParameters().put('schedId','');
				
				gavc.saveJS();
				for(ApexPages.Message m : ApexPages.getMessages()){
				if(m.getDetail() == 'Start time must be populated' || m.getDetail() == 'End time must be populated')
				System.assert(true);
				}
				
				Apexpages.currentPage().getParameters().put('staffId',testDataSetupUtil_v2.staffSectionsList[0].staff__c);
				Apexpages.currentPage().getParameters().put('roomId',testDataSetupUtil_v2.roomList[0].id);
				Apexpages.currentPage().getParameters().put('courseId',testDataSetupUtil_v2.coursesList[0].Id);
				Apexpages.currentPage().getParameters().put('startTime','10:00 AM');
				Apexpages.currentPage().getParameters().put('endTime','09:15 AM');
				Apexpages.currentPage().getParameters().put('dailyAtt','false');
				Apexpages.currentPage().getParameters().put('recordAtt','false');
				Apexpages.currentPage().getParameters().put('schedId','');
				gavc.saveJS();
				for(ApexPages.Message m : ApexPages.getMessages()){
				if(m.getDetail() == 'Start Time cannot be greater than End Time')
				System.assert(true);
				}
				
				Apexpages.currentPage().getParameters().put('staffId',testDataSetupUtil_v2.staffSectionsList[0].staff__c);
				Apexpages.currentPage().getParameters().put('roomId',testDataSetupUtil_v2.roomList[0].id);
				Apexpages.currentPage().getParameters().put('courseId',testDataSetupUtil_v2.coursesList[0].Id);
				Apexpages.currentPage().getParameters().put('startTime','6:00 AM');
				Apexpages.currentPage().getParameters().put('endTime','10:15 AM');
				Apexpages.currentPage().getParameters().put('dailyAtt','false');
				Apexpages.currentPage().getParameters().put('recordAtt','false');
				Apexpages.currentPage().getParameters().put('schedId','');
    			
    			gavc.saveJS();
    			
    			for(ApexPages.Message m : ApexPages.getMessages()){
				if(m.getDetail() == 'Start Time cannot be less than 8:00 AM')
				System.assert(true);
				}
    			
    			Apexpages.currentPage().getParameters().put('staffId',testDataSetupUtil_v2.staffSectionsList[0].staff__c);
				Apexpages.currentPage().getParameters().put('roomId',testDataSetupUtil_v2.roomList[2].id);
				Apexpages.currentPage().getParameters().put('courseId',testDataSetupUtil_v2.coursesList[2].Id);
				Apexpages.currentPage().getParameters().put('startTime','5:00 PM');
				Apexpages.currentPage().getParameters().put('endTime','7:15 PM');
				Apexpages.currentPage().getParameters().put('dailyAtt','false');
				Apexpages.currentPage().getParameters().put('recordAtt','false');
				Apexpages.currentPage().getParameters().put('schedId','');
    			
    			gavc.saveJS();
    			
    			for(ApexPages.Message m : ApexPages.getMessages()){
				if(m.getDetail() == 'End Time cannot be greater than 6:00 PM')
				System.assert(true);
				}
				
				/************************  TEST NEW SCHEDULED SECTION   ***********************************************************************************/
				Apexpages.currentPage().getParameters().put('staffId',testDataSetupUtil_v2.staffSectionsList[0].staff__c);
				Apexpages.currentPage().getParameters().put('roomId',testDataSetupUtil_v2.roomList[0].id);
				Apexpages.currentPage().getParameters().put('courseId',testDataSetupUtil_v2.coursesList[0].Id);
				Apexpages.currentPage().getParameters().put('startTime','9:00 AM');
				Apexpages.currentPage().getParameters().put('endTime','10:15 AM');
				Apexpages.currentPage().getParameters().put('dailyAtt','false');
				Apexpages.currentPage().getParameters().put('recordAtt','true');
				Apexpages.currentPage().getParameters().put('schedId','');
    			
    			gavc.saveJS();
    			Scheduled_Section__c schedSec = [SELECT Id,Reference_Id__c,Rounded_Start_Time__c,Schedule_Template__c FROM Scheduled_Section__c WHERE Schedule_Template__c = : gavc.schedTempId];
    			System.assertEquals('09:00 AM',schedSec.Rounded_Start_Time__c);
    			System.assertEquals(testDataSetupUtil_v2.school.Id+'-'+schedGrpsList_Section[0].Id+'-'+testDataSetupUtil_v2.coursesList[0].Id+'-'+testDataSetupUtil_v2.semester.Id+'-'+gavc.schedTempId,schedSec.Reference_Id__c );
    			System.debug('$$$$$Schedule_Template__c'+schedSec.Schedule_Template__c);
    			
    			/************************  TEST EDIT SCHEDULED SECTION   ***********************************************************************************/
    			//After save create another record whose end time less than the 1st schedulesection end time and course name same -result upsert happens
    			System.debug('$$$$$TEST$$$$$$$$$4');
    			//de2162 delete schedule template deletes schedSec
    			
    			
    			
    			gavc = new GroupAgendaViewController();
    			gavc.schedTempId = st.id;
    			gavc.reptPeriod = testDataSetupUtil_v2.semester.id;
    			gavc.initAgendaView();
    			Apexpages.currentPage().getParameters().put('staffId',testDataSetupUtil_v2.staffSectionsList[0].staff__c);
				Apexpages.currentPage().getParameters().put('roomId',testDataSetupUtil_v2.roomList[0].id);
				Apexpages.currentPage().getParameters().put('courseId',testDataSetupUtil_v2.coursesList[0].Id);
				Apexpages.currentPage().getParameters().put('startTime','10:00 AM');
				Apexpages.currentPage().getParameters().put('endTime','11:15 AM');
				Apexpages.currentPage().getParameters().put('dailyAtt','false');
				Apexpages.currentPage().getParameters().put('recordAtt','true');
				Apexpages.currentPage().getParameters().put('schedId',schedSec.Id);
    			
    			gavc.saveJS();
    			Scheduled_Section__c schedSec2 = [SELECT Id,Reference_Id__c,Rounded_Start_Time__c FROM Scheduled_Section__c WHERE Id = : schedSec.Id];
    			delete st;    			
    			Test.stopTest();
    			System.assertEquals('10:00 AM',schedSec2.Rounded_Start_Time__c);
    			System.assertEquals(testDataSetupUtil_v2.school.Id+'-'+schedGrpsList_Section[0].Id+'-'+testDataSetupUtil_v2.coursesList[0].Id+'-'+testDataSetupUtil_v2.semester.Id+'-'+gavc.schedTempId,schedSec2.Reference_Id__c );   		
    			system.assertEquals([select count() from Scheduled_Section__c where id=:schedSec.id],0);

    }
    
      static testMethod void testScheduleTemplateForGroups_OverlappingTimes() {
    	createTestData();
    	//Setup Page
    	PageReference scheduleTemplatePage = Page.core_ScheduleTemplate;
        scheduleTemplatePage.getParameters().put('setupId',testDataSetupUtil_v2.activeSetup.id);
        Test.setCurrentPage(scheduleTemplatePage);
		
		Test.startTest();
		core_scheduleTemplateConfiguration controller = new core_scheduleTemplateConfiguration();
		controller.rpID = testDataSetupUtil_v2.semester.id;
		controller.initTemplate();
		controller.bIsClone = false;
		controller.schedTemplate.name = 'Master temp';
		controller.schedTemplate.Is_Master__c = true;
		controller.schedTemplate.Start_Time_Text__c = '8:00 AM';
		controller.schedTemplate.End_Time_Text__c = '5:00 PM';
		controller.schedTemplate.Has_Class__c = true;
		controller.saveSchedGrp();
		
		Schedule_Template__c st = new Schedule_Template__c();
		st = [SELECT Name,Id, Is_Master__c ,has_class__c,Start_Time_Text__c, End_Time_Text__c FROM Schedule_Template__c WHERE Id = : controller.schedTemplate.Id];
	/*************************CREATE A NEW SCHEDULED SECTION************************************************************************************/	
    	PageReference groupAgendaViewPage = Page.GroupAgendaView;
		groupAgendaViewPage.getParameters().put('setupId',testDataSetupUtil_v2.activeSetup.id);
    	Test.setCurrentPage(groupAgendaViewPage);
		GroupAgendaViewController gavc = new GroupAgendaViewController();
		gavc.schedTempId = st.id;
		gavc.reptPeriod = testDataSetupUtil_v2.semester.id;
		gavc.initAgendaView();
    	
    	Apexpages.currentPage().getParameters().put('staffId',testDataSetupUtil_v2.staffSectionsList[0].staff__c);
		Apexpages.currentPage().getParameters().put('roomId',testDataSetupUtil_v2.roomList[0].id);
		Apexpages.currentPage().getParameters().put('courseId',testDataSetupUtil_v2.coursesList[0].Id);
		Apexpages.currentPage().getParameters().put('startTime','9:00 AM');
		Apexpages.currentPage().getParameters().put('endTime','10:15 AM');
		Apexpages.currentPage().getParameters().put('dailyAtt','false');
		Apexpages.currentPage().getParameters().put('recordAtt','true');
		Apexpages.currentPage().getParameters().put('schedId','');
    			
    	gavc.saveJS();
    	
    /************************ CREATE A NEW SCHED SECTION WHOSE TEST START TIME AND END TIME OVERLAPPING WITH THE FIRST SCHEDULED SECTION   ***********************************************************************************/
    			//After save create another record whose start time less than the 1st schedulesection end time and course name different -result error is thrown
		gavc = new GroupAgendaViewController();
		gavc.schedTempId = st.id;
		gavc.reptPeriod = testDataSetupUtil_v2.semester.id;
		gavc.initAgendaView();
    			Apexpages.currentPage().getParameters().put('staffId',testDataSetupUtil_v2.staffSectionsList[1].staff__c);
				Apexpages.currentPage().getParameters().put('roomId',testDataSetupUtil_v2.roomList[1].id);
				Apexpages.currentPage().getParameters().put('courseId',testDataSetupUtil_v2.coursesList[1].Id);
				Apexpages.currentPage().getParameters().put('startTime','9:00 AM');
				Apexpages.currentPage().getParameters().put('endTime','11:15 AM');
				Apexpages.currentPage().getParameters().put('dailyAtt','false');
				Apexpages.currentPage().getParameters().put('recordAtt','true');
				Apexpages.currentPage().getParameters().put('schedId','');
    			
    			gavc.saveJS();
    			System.assertEquals(true, gavc.hasErrors);
    			for(ApexPages.Message m : ApexPages.getMessages()){
    			if(m.getDetail() == 'The start and end times conflict with'+testDataSetupUtil_v2.coursesList[0].Name)
				System.assert(true);
				}
    	Test.stopTest();
    }
    
    static testMethod void testScheduleTemplateForGroups_DeleteAndInsert() {
     	createTestData();
    	//Setup Page
    	PageReference scheduleTemplatePage = Page.core_ScheduleTemplate;
        scheduleTemplatePage.getParameters().put('setupId',testDataSetupUtil_v2.activeSetup.id);
        Test.setCurrentPage(scheduleTemplatePage);
		
		Test.startTest();
		core_scheduleTemplateConfiguration controller = new core_scheduleTemplateConfiguration();
		controller.rpID = testDataSetupUtil_v2.semester.id;
		controller.initTemplate();
		controller.bIsClone = false;
		controller.schedTemplate.name = 'Master temp';
		controller.schedTemplate.Is_Master__c = true;
		controller.schedTemplate.Start_Time_Text__c = '8:00 AM';
		controller.schedTemplate.End_Time_Text__c = '5:00 PM';
		controller.schedTemplate.Has_Class__c = true;
		controller.saveSchedGrp();
		
		Schedule_Template__c st = new Schedule_Template__c();
		st = [SELECT Name,Id, Is_Master__c ,has_class__c,Start_Time_Text__c, End_Time_Text__c FROM Schedule_Template__c WHERE Id = : controller.schedTemplate.Id];
	/*************************CREATE A NEW SCHEDULED SECTION************************************************************************************/	
    	PageReference groupAgendaViewPage = Page.GroupAgendaView;
		groupAgendaViewPage.getParameters().put('setupId',testDataSetupUtil_v2.activeSetup.id);
    	Test.setCurrentPage(groupAgendaViewPage);
		GroupAgendaViewController gavc = new GroupAgendaViewController();
		gavc.schedTempId = st.id;
		gavc.reptPeriod = testDataSetupUtil_v2.semester.id;
		gavc.initAgendaView();
    	
    	Apexpages.currentPage().getParameters().put('staffId',testDataSetupUtil_v2.staffSectionsList[0].staff__c);
		Apexpages.currentPage().getParameters().put('roomId',testDataSetupUtil_v2.roomList[0].id);
		Apexpages.currentPage().getParameters().put('courseId',testDataSetupUtil_v2.coursesList[0].Id);
		Apexpages.currentPage().getParameters().put('startTime','9:00 AM');
		Apexpages.currentPage().getParameters().put('endTime','10:15 AM');
		Apexpages.currentPage().getParameters().put('dailyAtt','false');
		Apexpages.currentPage().getParameters().put('recordAtt','true');
		Apexpages.currentPage().getParameters().put('schedId','');
    			
    	gavc.saveJS();
    	
    	List<Scheduled_Section__c> schedSecList = new List<Scheduled_Section__c>();
    	schedSecList = [SELECT Id,Reference_Id__c,Rounded_Start_Time__c FROM Scheduled_Section__c WHERE Schedule_Template__c = : gavc.schedTempId order by id];
    	System.assertEquals(1, schedSecList.size());
    	Test.stopTest();
     }
    
     static testMethod void testScheduleTemplateForGroups_Delete() {
     	createTestData();
    	//Setup Page
    	PageReference scheduleTemplatePage = Page.core_ScheduleTemplate;
        scheduleTemplatePage.getParameters().put('setupId',testDataSetupUtil_v2.activeSetup.id);
        Test.setCurrentPage(scheduleTemplatePage);

		Test.startTest();
		core_scheduleTemplateConfiguration controller = new core_scheduleTemplateConfiguration();
		controller.rpID = testDataSetupUtil_v2.semester.id;
		controller.initTemplate();
		System.debug('Page URL &&&&&&&&&&&&&7'+System.currentPageReference().getUrl());
		controller.bIsClone = false;
		controller.schedTemplate.name = 'Master temp';
		controller.schedTemplate.Is_Master__c = true;
		controller.schedTemplate.Start_Time_Text__c = '8:00 AM';
		controller.schedTemplate.End_Time_Text__c = '5:00 PM';
		controller.schedTemplate.Has_Class__c = true;
		controller.saveSchedGrp();
		
		Schedule_Template__c st = new Schedule_Template__c();
		st = [SELECT Name,Id, Is_Master__c ,has_class__c,Start_Time_Text__c, End_Time_Text__c FROM Schedule_Template__c WHERE Id = : controller.schedTemplate.Id];
	/*************************CREATE A NEW SCHEDULED SECTION************************************************************************************/	
    	PageReference groupAgendaViewPage = Page.GroupAgendaView;
		groupAgendaViewPage.getParameters().put('setupId',testDataSetupUtil_v2.activeSetup.id);
    	Test.setCurrentPage(groupAgendaViewPage);
		GroupAgendaViewController gavc = new GroupAgendaViewController();
		gavc.schedTempId = st.id;
		gavc.reptPeriod = testDataSetupUtil_v2.semester.id;
		gavc.initAgendaView();
    	
    	Apexpages.currentPage().getParameters().put('staffId',testDataSetupUtil_v2.staffSectionsList[0].staff__c);
		Apexpages.currentPage().getParameters().put('roomId',testDataSetupUtil_v2.roomList[0].id);
		Apexpages.currentPage().getParameters().put('courseId',testDataSetupUtil_v2.coursesList[0].Id);
		Apexpages.currentPage().getParameters().put('startTime','9:00 AM');
		Apexpages.currentPage().getParameters().put('endTime','10:15 AM');
		Apexpages.currentPage().getParameters().put('dailyAtt','false');
		Apexpages.currentPage().getParameters().put('recordAtt','true');
		Apexpages.currentPage().getParameters().put('schedId','');
    			
    	gavc.saveJS();
    	
    	List<Scheduled_Section__c> schedSecList = new List<Scheduled_Section__c>();
    	schedSecList = [SELECT Id,Reference_Id__c,Rounded_Start_Time__c FROM Scheduled_Section__c WHERE Schedule_Template__c = : gavc.schedTempId order by id];
    	System.assertEquals(1, schedSecList.size());
    	/************************  TEST DELETE SCHED SECTION ***********************************************************************************/
    		Apexpages.currentPage().getParameters().put('schedId_del',schedSecList[0].Id);
    		gavc.deleteJS();
    			List<Scheduled_Section__c> schedSecListdel = new List<Scheduled_Section__c>();
    			
    			schedSecListdel = [SELECT Id,Reference_Id__c,Rounded_Start_Time__c FROM Scheduled_Section__c WHERE Id = : schedSecList[0].Id order by id];
    			System.assertEquals(0, schedSecListdel.size());
       
       /************************  TEST REFRESH GROUPS ***********************************************************************************/
    		//	System.assertEquals(true, gavc.gavw.scheduleGroupList[0].isSelected);
     		//	System.assertEquals(false, gavc.gavw.scheduleGroupList[1].isSelected);
    		Apexpages.currentPage().getParameters().put('grpId',schedGrpsList_Section[1].Id);
    			gavc.refreshGroups();
    		//	System.assertEquals(false, gavc.gavw.scheduleGroupList[0].isSelected);
     		//	System.assertEquals(true, gavc.gavw.scheduleGroupList[1].isSelected);
     		Test.stopTest();
     }
     
     static testMethod void testScheduleTemplateForGroups_AllDay() {
     	createTestData();
    	//Setup Page
    	PageReference scheduleTemplatePage = Page.core_ScheduleTemplate;
        scheduleTemplatePage.getParameters().put('setupId',testDataSetupUtil_v2.activeSetup.id);
        Test.setCurrentPage(scheduleTemplatePage);
		
		Test.startTest();
		core_scheduleTemplateConfiguration controller = new core_scheduleTemplateConfiguration();
		controller.rpID = testDataSetupUtil_v2.semester.id;
		controller.initTemplate();
		controller.bIsClone = false;
		controller.schedTemplate.name = 'Master temp';
		controller.schedTemplate.Is_Master__c = true;
		controller.schedTemplate.Start_Time_Text__c = '8:00 AM';
		controller.schedTemplate.End_Time_Text__c = '5:00 PM';
		controller.schedTemplate.Has_Class__c = true;
		controller.saveSchedGrp();
		
		Schedule_Template__c st = new Schedule_Template__c();
		st = [SELECT Name,Id, Is_Master__c ,has_class__c,Start_Time_Text__c, End_Time_Text__c FROM Schedule_Template__c WHERE Id = : controller.schedTemplate.Id];
	/*************************CREATE ALL DAY  SCHEDULED SECTION************************************************************************************/	
    	PageReference groupAgendaViewPage = Page.GroupAgendaView;
		groupAgendaViewPage.getParameters().put('setupId',testDataSetupUtil_v2.activeSetup.id);
    	Test.setCurrentPage(groupAgendaViewPage);
		GroupAgendaViewController gavc = new GroupAgendaViewController();
		gavc.schedTempId = st.id;
		gavc.reptPeriod = testDataSetupUtil_v2.semester.id;
		gavc.initAgendaView();
    	
    	Apexpages.currentPage().getParameters().put('staffId',testDataSetupUtil_v2.staffSectionsList[0].staff__c);
		Apexpages.currentPage().getParameters().put('roomId',testDataSetupUtil_v2.roomList[0].id);
		Apexpages.currentPage().getParameters().put('courseId',testDataSetupUtil_v2.coursesList[0].Id);
		Apexpages.currentPage().getParameters().put('startTime','9:00 AM');
		Apexpages.currentPage().getParameters().put('endTime','10:15 AM');
		Apexpages.currentPage().getParameters().put('dailyAtt','true');
		Apexpages.currentPage().getParameters().put('recordAtt','false');
		Apexpages.currentPage().getParameters().put('noclass','false');
		Apexpages.currentPage().getParameters().put('schedId','');
    			
    	gavc.saveJS();
    	System.debug('----CURRENT SCHED SECTION-------------'+gavc.currSchedSec);
    	List<Scheduled_Section__c> schedSecList = new List<Scheduled_Section__c>();
    	schedSecList = [SELECT Id,Reference_Id__c,Rounded_Start_Time__c,Record_Attendance__c FROM Scheduled_Section__c WHERE Schedule_Template__c = : gavc.schedTempId order by id];
    	System.assertEquals(1, schedSecList.size());
    	System.assertEquals(gavc.currSchedSec.Reference_Id__c, schedSecList[0].Reference_Id__c);
    	System.assertEquals(true, schedSecList[0].Record_Attendance__c);
    	Test.stopTest();
     }
     
     static testMethod void testScheduleTemplateConfig_Clone() {
     	createTestData();
    	//Setup Page
     	PageReference scheduleTemplatePage = Page.core_ScheduleTemplate;
        scheduleTemplatePage.getParameters().put('setupId',testDataSetupUtil_v2.activeSetup.id);
        Test.setCurrentPage(scheduleTemplatePage);

		Test.startTest();
			core_scheduleTemplateConfiguration controller = new core_scheduleTemplateConfiguration();
			controller.rpID = testDataSetupUtil_v2.semester.id;
			controller.initTemplate();
			controller.bIsClone = false;
			controller.schedTemplate.name = 'Master temp';
			controller.schedTemplate.Is_Master__c = true;
			controller.schedTemplate.Start_Time_Text__c = '8:00 AM';
			controller.schedTemplate.End_Time_Text__c = '5:00 PM';
			controller.schedTemplate.Has_Class__c = true;
			controller.saveSchedGrp();
			
			Schedule_Template__c st = new Schedule_Template__c();
			st = [SELECT Name,Id, Is_Master__c ,has_class__c,Start_Time_Text__c, End_Time_Text__c FROM Schedule_Template__c WHERE Id = : controller.schedTemplate.Id];
			/*************************CREATE A NEW SCHEDULED SECTION************************************************************************************/	
	    	PageReference groupAgendaViewPage = Page.GroupAgendaView;
			groupAgendaViewPage.getParameters().put('setupId',testDataSetupUtil_v2.activeSetup.id);
	    	Test.setCurrentPage(groupAgendaViewPage);
			GroupAgendaViewController gavc = new GroupAgendaViewController();
			gavc.schedTempId = st.id;
			gavc.reptPeriod = testDataSetupUtil_v2.semester.id;
			gavc.initAgendaView();
	    	
	    	Apexpages.currentPage().getParameters().put('staffId',testDataSetupUtil_v2.staffSectionsList[0].staff__c);
			Apexpages.currentPage().getParameters().put('roomId',testDataSetupUtil_v2.roomList[0].id);
			Apexpages.currentPage().getParameters().put('courseId',testDataSetupUtil_v2.coursesList[0].Id);
			Apexpages.currentPage().getParameters().put('startTime','9:00 AM');
			Apexpages.currentPage().getParameters().put('endTime','10:15 AM');
			Apexpages.currentPage().getParameters().put('dailyAtt','false');
			Apexpages.currentPage().getParameters().put('recordAtt','true');
			Apexpages.currentPage().getParameters().put('schedId','');
    			
    		gavc.saveJS();
    	
	    	List<Scheduled_Section__c> schedSecList = new List<Scheduled_Section__c>();
	    	schedSecList = [SELECT Id,Reference_Id__c,Rounded_Start_Time__c FROM Scheduled_Section__c WHERE Schedule_Template__c = : gavc.schedTempId order by id];
	    	System.assertEquals(1, schedSecList.size());
	    	controller.templateId = null;
	    	controller.cloneTemplateId = st.id;
	    	controller.bIsClone = true;
	    	controller.initTemplate();

			//controller.schedTemplate = new Schedule_Template__c();
			controller.schedTemplate.name = 'Half Day';
			controller.schedTemplate.Is_Master__c = false;
			controller.schedTemplate.Start_Time_Text__c = '8:00 AM';
			controller.schedTemplate.End_Time_Text__c = '5:00 PM';
			controller.schedTemplate.Has_Class__c = true;
			controller.schedTemplate.Reporting_Period__c = testDataSetupUtil_v2.semester.Id;
			controller.saveSchedGrp();
					
			List<Scheduled_Section__c> schedSecsList2 = [SELECT ID,Reference_Id__c,Schedule_Template__c,Schedule_Template__r.Name FROM Scheduled_Section__c WHERE Schedule_Template__c = : controller.schedTemplate.Id];
	   				
	   		System.assertEquals(schedSecsList2[0].Schedule_Template__r.Name, 'Half Day'); 
	   		System.assertEquals(schedSecsList2.size(), 1);
	   	Test.stopTest(); 
     }
    
     
    public static List<Schedule_Group__c> getScheduleGroups(){
    	schedGrpsList = new List<Schedule_Group__c>();
    	    	/* deprecated for Chicago release
    	schedGrpsList.add(new Schedule_Group__c(Name = '5A',Grade_Level__c = '5',Description__c='test1',SetUp__c = testDataSetupUtil_v2.activeSetUp.Id));
    	schedGrpsList.add(new Schedule_Group__c(Name = '5B',Grade_Level__c = '5',Description__c='test2',SetUp__c = testDataSetupUtil_v2.activeSetUp.Id));
    	insert schedGrpsList;
    	System.debug('----------schedGrpsList -------------------------------'+schedGrpsList);*/
    	return schedGrpsList;
    }
    
}