objects/Section__c.object
<CustomObject>
    <fields>
        <fullName>Completed__c</fullName>
        <defaultValue>false</defaultValue>
        <description>When section has been marked competed for all reporting periods it meets for this flag will be checked.</description>
        <inlineHelpText>When section has been marked competed for all reporting periods it meets for this flag will be checked.</inlineHelpText>
        <label>Completed?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Section__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Recursive lookup for groups</description>
        <label>Section</label>
        <referenceTo>Section__c</referenceTo>
        <relationshipLabel>Groups in Section</relationshipLabel>
        <relationshipName>Sections1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Time__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Time</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Time_Element__c.Picklist_Value__r.Name</field>
                <operation>equals</operation>
                <value>Year</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Time_Element__c</referenceTo>
        <relationshipLabel>Sections</relationshipLabel>
        <relationshipName>Sections</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Section</label>
    <nameField>
        <label>Section Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sections</pluralLabel>
    <recordTypes>
        <fullName>Published</fullName>
        <active>true</active>
        <description>Sections that have been Published and are Viewable by Standard Users</description>
        <label>Published</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Section_ReportingPeriod__c.object
<CustomObject>
    <fields>
        <fullName>Completed__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Is this reporting period for this section completed?</description>
        <label>Completed?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ReferenceId__c</fullName>
        <externalId>true</externalId>
        <label>ReferenceId</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Section__c</fullName>
        <label>Section</label>
        <referenceTo>Section__c</referenceTo>
        <relationshipLabel>Section/ReportingPeriod</relationshipLabel>
        <relationshipName>Section_ReportingPeriod</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Time__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Time</label>
        <referenceTo>Time_Element__c</referenceTo>
        <relationshipLabel>Section/ReportingPeriod</relationshipLabel>
        <relationshipName>Section_ReportingPeriod</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Section/ReportingPeriod</label>
    <nameField>
        <displayFormat>SR-{000000}</displayFormat>
        <label>Section/ReportingPeriod</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Section/ReportingPeriod</pluralLabel>
    <recordTypes>
        <fullName>Published</fullName>
        <active>true</active>
        <label>Published</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/Gradebook_CompleteSectionsController.cls
public class Gradebook_CompleteSectionsController {
	public Gradebook_RunReportCardsController rrcc {get;set;}
	
	public Gradebook_CompleteSectionsController(){
		rrcc  = new Gradebook_RunReportCardsController();
		rrcc.useS3 = false;
		rrcc.gotoDocumentGeneration();
		//clear the as3 messages from run report cards
		for (Gradebook_RunReportCardsWrapper.schoolWrapper schoolWrapper: rrcc.schools){
			schoolWrapper.bTimeFilter=true;
		}
	}
	
	public void markSectionsCompleted(){
		Apexpages.getMessages().clear();
		List <Section_ReportingPeriod__c> srpList = new List <Section_ReportingPeriod__c>();
		for (Gradebook_RunReportCardsWrapper.sectionWrapper sectionWrapper:rrcc.sectionDisplayWrapper){
			if(sectionWrapper.srp != null){
				srpList.add(sectionWrapper.srp);
			}
		}
		rrcc.hideCurrentSections();
		try {
			update srpList;
			Apexpages.addMessage(new apexpages.message(apexpages.severity.Confirm,'Sections updated successfully!' ));
		} catch (exception e){
			Apexpages.addMessage(new apexpages.message(apexpages.severity.Fatal,'Error occurred when updating sections. Please contact your administrator.' ));
		}	
	}

	@isTest static void test_CompleteSections(){
		Test_Gradebook_RunReportCards.setupData();
		List<Section_ReportingPeriod__c> srpList = new List<Section_ReportingPeriod__c>();
		for(Section__c s:TestDataSetupUtil_v2.sectionsList){
			srpList.add(new Section_ReportingPeriod__c(
				Section__c = s.id, 
				Time__c = TestDataSetupUtil_v2.semester.id, 
				ReferenceId__c=s.id+'_'+TestDataSetupUtil_v2.semester.id, //why is it ReferenceId__c on here? *cries*
				RecordTypeID = core_SoqlUtils.getRecordTypesBySobject('Section_ReportingPeriod__c').get('Published')
			)); 
		}
		insert srpList;

		Test.setCurrentPage(Page.Gradebook_CompleteSections);
		Test.startTest();
			Gradebook_CompleteSectionsController controller = new Gradebook_CompleteSectionsController();
			controller.rrcc.selectedSectionSchool = controller.rrcc.schools[0].setup.id;
			controller.rrcc.schools[0].selectedReportingPeriod = TestDataSetupUtil_v2.semester.id;
			controller.rrcc.showCurrentSections();
			controller.rrcc.sectionDisplayWrapper[0].srp.Completed__c = true;
			controller.markSectionsCompleted();
			system.assertEquals(true, controller.rrcc.schools[0].sections[0].srp.Completed__c);
			system.assertEquals(true, [select Completed__c from Section_ReportingPeriod__c where ID =:controller.rrcc.schools[0].sections[0].srp.id][0].Completed__c);
		Test.stopTest();
	}
}