objects/Section__c.object
<CustomObject>
    <fields>
        <fullName>Section__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Recursive lookup for groups</description>
        <label>Section</label>
        <referenceTo>Section__c</referenceTo>
        <relationshipLabel>Groups in Section</relationshipLabel>
        <relationshipName>Sections1</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Section</label>
    <nameField>
        <label>Section Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sections</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Section_Standard__c.object
<CustomObject>
    <fields>
        <fullName>Section__c</fullName>
        <label>Section</label>
        <referenceTo>Section__c</referenceTo>
        <relationshipLabel>Section/Standard</relationshipLabel>
        <relationshipName>Section_Standard</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Standard__c</fullName>
        <label>Standard</label>
        <referenceTo>Standard__c</referenceTo>
        <relationshipLabel>Section/Standard</relationshipLabel>
        <relationshipName>Section_Standard</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Section/Standard</label>
    <nameField>
        <displayFormat>Sec-Stand{0000}</displayFormat>
        <label>Section/Standard Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Section/Standard</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Standard__c.object
<CustomObject>
    <fields>
        <fullName>Strand__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Indicates if a standard looks up to a Strand.  Strand grades are only calculated for the Standards-Only Gradebook.</inlineHelpText>
        <label>Strand</label>
        <referenceTo>Standard__c</referenceTo>
        <relationshipLabel>Standards (Strand)</relationshipLabel>
        <relationshipName>Strands</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Standard</label>
    <nameField>
        <label>Standard Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Standards</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/Test_SectionStandardListController.cls
@isTest
private class Test_SectionStandardListController {
	static testMethod void TestConstructor() {
		testDataSetupUtil_v2.setUPCoreData(5);
		testDataSetupUtil_v2.setUPStaffData(5);
		testDataSetupUtil_v2.setUPStudentData(5);
		testDataSetupUtil_v2.setUpStandards();

		List<Section_standard__c> secStandards = new List<Section_standard__c>();
		secStandards.add(new Section_standard__c(Standard__c=testDataSetupUtil_v2.strandStandard.id, Section__c = testDataSetupUtil_v2.sectionsList[1].id));

		for(Standard__c s:testDataSetupUtil_v2.testStandards){
			secStandards.add(new Section_standard__c(Standard__c=s.id, Section__c = testDataSetupUtil_v2.sectionsList[1].id));
		}

		insert secStandards;
		
		Test.startTest();
			ApexPages.StandardController con = new ApexPages.StandardController(testDataSetupUtil_v2.sectionsList[1]);
			Section_StandardsListController controller = new Section_StandardsListController(con);
			 
			system.assertEquals(testDataSetupUtil_v2.sectionsList[1].id, controller.section.id, 'Section Ids do not match.');
			system.assertEquals(1, controller.standards.size(), 'There should only be 1 strand standard.');
			system.assertEquals(4, controller.standards[0].childStandards.size(), 'There should be 4 child standards.');
			 
			for(Standard__c s: controller.standards[0].childStandards){
				system.assertEquals(controller.standards[0].standard.id, s.Strand__c, 'Theses standards should have the strand as a parent.');
			}
		Test.stopTest();
	}
}