objects/Section__c.object
<CustomObject>
    <fields>
        <fullName>Section__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Recursive lookup for groups</description>
        <label>Section</label>
        <referenceTo>Section__c</referenceTo>
        <relationshipLabel>Groups in Section</relationshipLabel>
        <relationshipName>Sections1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Subject__c</fullName>
        <label>Subject</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Math</fullName>
                </value>
                <value>
                    <fullName>Science</fullName>
                </value>
                <value>
                    <fullName>Reading</fullName>
                </value>
                <value>
                    <fullName>Writing</fullName>
                </value>
                <value>
                    <fullName>Social Studies</fullName>
                </value>
                <value>
                    <fullName>Spanish</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Section</label>
    <nameField>
        <label>Section Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sections</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Section_Standard__c.object
<CustomObject>
    <fields>
        <fullName>Section__c</fullName>
        <label>Section</label>
        <referenceTo>Section__c</referenceTo>
        <relationshipLabel>Section/Standard</relationshipLabel>
        <relationshipName>Section_Standard</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Standard__c</fullName>
        <label>Standard</label>
        <referenceTo>Standard__c</referenceTo>
        <relationshipLabel>Section/Standard</relationshipLabel>
        <relationshipName>Section_Standard</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Section/Standard</label>
    <nameField>
        <displayFormat>Sec-Stand{0000}</displayFormat>
        <label>Section/Standard Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Section/Standard</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Standard__c.object
<CustomObject>
    <fields>
        <fullName>Long_Text__c</fullName>
        <inlineHelpText>Long text description of the standard that displays in the hover over in the Gradebook and on Portal/PGV. Max of 32,000 characters to describe the Standard.</inlineHelpText>
        <label>Long Text</label>
        <length>32000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Parent_Standard__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Indicates if a standard hierarchy is present and what the parent standard is</inlineHelpText>
        <label>Parent Standard</label>
        <referenceTo>Standard__c</referenceTo>
        <relationshipLabel>Standards</relationshipLabel>
        <relationshipName>Standards</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Strand__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Indicates if a standard looks up to a Strand.  Strand grades are only calculated for the Standards-Only Gradebook.</inlineHelpText>
        <label>Strand</label>
        <referenceTo>Standard__c</referenceTo>
        <relationshipLabel>Standards (Strand)</relationshipLabel>
        <relationshipName>Strands</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Subject__c</fullName>
        <inlineHelpText>retired field</inlineHelpText>
        <label>Subject</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>Standard</label>
    <nameField>
        <label>Standard Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Standards</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/Section_StandardsListController.cls
public with sharing class Section_StandardsListController {
	public Section__c section				{get;set;}
	public List<standardWrapper> standards	{get;set;}
	public boolean displayList				{get;set;}
	
	public Section_StandardsListController(ApexPages.StandardController stdCon){
		section = (Section__c) stdCon.getRecord();
		displayList = false;
		standards = new List<standardWrapper>();
		
		List<Section_Standard__c> linkingList = [select id, Standard__c
												from Section_Standard__c 
												where Section__c =: section.id];
		Set<Id> standardIds = new Set<Id>();
		for(Section_Standard__c s: linkingList){
			standardIds.add(s.Standard__c);
		}
		
		List<Standard__c> standardList = [select id, Name, Subject__c, Long_Text__c,Parent_Standard__c, Strand__c 
											from Standard__c
											where id IN: standardIds];
												
		Set<Id> strandIds = new Set<Id>();
		Map<id, List<Standard__c>> strandStandardMap = new Map<id, List<Standard__c>>();
		for(Standard__c s: standardList){
			if(s.Strand__c != null){
				strandIds.add(s.Strand__c);
			}
			
			if(strandStandardMap.containsKey(s.Strand__c)){
				strandStandardMap.get(s.Strand__c).add(s);
			} else {
				strandStandardMap.put(s.Strand__c, new List<Standard__c>{s});
			}
		}
		
		List<Standard__c> strandList = [select id, Name, Subject__c, Long_Text__c 
										from Standard__c
										where id IN:strandIds];
		
		for(Standard__c s:strandList){
			standards.add(new standardWrapper(s, StrandStandardMap.get(s.id)));
		}
		
		 displayList = (standards.isEmpty())? false:true;
	}

	public class standardWrapper {
		public Standard__c standard					{get;set;}
		public List<Standard__c> childStandards		{get;set;}
		
		public standardWrapper(Standard__c strand, List<Standard__c> standards){
			standard = strand;
			childStandards = standards;
		}
	}
}