objects/Setup__c.object
<CustomObject>
    <description>This object is used to setup Schoolforce and is referenced in multiple pieces of code.  There should be one setup object per school.</description>
    <fields>
        <fullName>Points_Reset_Date__c</fullName>
        <description>This field will be set  by an apex job . This field will be used to determine today&apos;s Current Balance field on student record.</description>
        <label>Points Reset Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Points_Reset_Value__c</fullName>
        <label>Points Reset Value</label>
        <precision>6</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Setup</label>
    <nameField>
        <displayFormat>S-{0}</displayFormat>
        <label>Setup ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Setup</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

classes/sched_Points.cls
global class sched_Points implements Schedulable{
	
	global void execute(SchedulableContext sc) { 
		Set<String> setupIds;
		List<Setup__c> setupsUpdated = new List<Setup__c>();
		CronTrigger ct = [SELECT Id, OwnerID FROM CronTrigger WHERE Id = :sc.getTriggerId()];
		Points_Utils.pointsNotifications(ct.OwnerID);
		
		setupIds = Points_Utils.getSetupsForReset();  
		if(setupIds != null){
			for(Setup__c s: [SELECT Points_Reset_Value__c FROM Setup__c WHERE Id in: setupIds]){
				s.Points_Reset_Date__c = System.today();
				setupsUpdated.add(s); 
			}
			
			update setupsUpdated; 
			System.debug('SETUP$$$$$$'+setupsUpdated);
	   		Batch_ResetPoints brp = new Batch_ResetPoints ();
	   		brp.setupIds = setupIds;  
			ID batchprocessid = Database.executeBatch(brp);
		}
	}
	
}