objects/Setup__c.object
<CustomObject>
    <description>This object is used to setup Schoolforce and is referenced in multiple pieces of code.  There should be one setup object per school.</description>
    <fields>
        <fullName>Term__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Term refers to the Term &apos;Template&apos; that the administrator associates to the School; this contains all Semeser/Quarter/Period logic necessary to create Sessions.</description>
        <label>Term</label>
        <referenceTo>Time_Element__c</referenceTo>
        <relationshipLabel>Setup</relationshipLabel>
        <relationshipName>Setup</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Setup</label>
    <nameField>
        <displayFormat>S-{0}</displayFormat>
        <label>Setup ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Setup</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/Standard__c.object
<CustomObject>
    <fields>
        <fullName>Description_Spanish__c</fullName>
        <description>The strand and standard description in Spanish language</description>
        <inlineHelpText>The strand and standard description in Spanish</inlineHelpText>
        <label>Description in Spanish</label>
        <length>32000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Long_Text__c</fullName>
        <inlineHelpText>Long text description of the standard that displays in the hover over in the Gradebook and on Portal/PGV. Max of 32,000 characters to describe the Standard.</inlineHelpText>
        <label>Long Text</label>
        <length>32000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Strand__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Indicates if a standard looks up to a Strand.  Strand grades are only calculated for the Standards-Only Gradebook.</inlineHelpText>
        <label>Strand</label>
        <referenceTo>Standard__c</referenceTo>
        <relationshipLabel>Standards (Strand)</relationshipLabel>
        <relationshipName>Strands</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Subject__c</fullName>
        <inlineHelpText>retired field</inlineHelpText>
        <label>Subject</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>Standard</label>
    <nameField>
        <label>Standard Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Standards</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Standard_Grade__c.object
<CustomObject>
    <fields>
        <fullName>Grade_Overridden__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Has this standard grade been overridden?</inlineHelpText>
        <label>Grade Overridden</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Grade_Override__c</fullName>
        <label>Grade Override</label>
        <precision>4</precision>
        <scale>1</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Reporting_Period__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Reporting Period</label>
        <referenceTo>Time_Element__c</referenceTo>
        <relationshipLabel>Standard Grades</relationshipLabel>
        <relationshipName>Standard_Grades</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Standard_Grade__c</fullName>
        <formula>IF(NOT(ISNULL(Grade_Override__c)), Grade_Override__c,

IF(AND(ISPICKVAL(Student__r.Setup__r.Calculation_Type__c,  &quot;Mean&quot;), Student__r.Setup__r.Rolling_Standard_Grade__c == FALSE), Mean_Grade__c, 

IF(AND(ISPICKVAL(Student__r.Setup__r.Calculation_Type__c, &quot;Highest&quot;), Student__r.Setup__r.Rolling_Standard_Grade__c == FALSE), Highest_Grade__c, 

IF(AND(ISPICKVAL(Student__r.Setup__r.Calculation_Type__c, &quot;Most Recent&quot;), Student__r.Setup__r.Rolling_Standard_Grade__c == FALSE), Most_Recent_Grade__c, 
 
IF(AND(ISPICKVAL(Student__r.Setup__r.Calculation_Type__c, &quot;Power Law&quot;), Student__r.Setup__r.Rolling_Standard_Grade__c == FALSE), Power_Law_Grade__c, 

IF(AND(ISPICKVAL(Student__r.Setup__r.Calculation_Type__c, &quot;Law of Decaying Average&quot;), Student__r.Setup__r.Rolling_Standard_Grade__c == FALSE), Law_of_Decaying_Average_Grade__c, 

IF(AND(ISPICKVAL(Student__r.Setup__r.Calculation_Type__c,  &quot;Mean&quot;), Student__r.Setup__r.Rolling_Standard_Grade__c == TRUE), Rolling_Mean_Grade__c, 

IF(AND(ISPICKVAL(Student__r.Setup__r.Calculation_Type__c, &quot;Highest&quot;), Student__r.Setup__r.Rolling_Standard_Grade__c == TRUE), Rolling_Highest_Grade__c, 

IF(AND(ISPICKVAL(Student__r.Setup__r.Calculation_Type__c, &quot;Most Recent&quot;), Student__r.Setup__r.Rolling_Standard_Grade__c == TRUE), Rolling_Most_Recent_Grade__c, 
 
IF(AND(ISPICKVAL(Student__r.Setup__r.Calculation_Type__c, &quot;Power Law&quot;), Student__r.Setup__r.Rolling_Standard_Grade__c == TRUE), Rolling_Power_Law_Grade__c, 

IF(AND(ISPICKVAL(Student__r.Setup__r.Calculation_Type__c, &quot;Law of Decaying Average&quot;), Student__r.Setup__r.Rolling_Standard_Grade__c == TRUE), Rolling_Law_of_Decaying_Average_Grade__c, 

Weighted_Average_Grade__c

)))))))))))</formula>
        <inlineHelpText>What is the formal standard grade based on the school&apos;s selected standard calculation type? This is a year to date calculation; it is not based on reporting periods.</inlineHelpText>
        <label>Grade</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Standard__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Standard</label>
        <referenceTo>Standard__c</referenceTo>
        <relationshipLabel>Standard Grades</relationshipLabel>
        <relationshipName>Standard_Grades</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Student__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Student</label>
        <referenceTo>Student__c</referenceTo>
        <relationshipLabel>Standard Grades</relationshipLabel>
        <relationshipName>Standard_Grades</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Standard Grade</label>
    <nameField>
        <displayFormat>STDG-{000}</displayFormat>
        <label>Standard Grade Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Standard Grades</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Student__c.object
<CustomObject>
    <fields>
        <fullName>Setup__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Displays the Setup record associated to this Student record. The Setup record defines the settings for the school in a specific school year.</inlineHelpText>
        <label>Setup</label>
        <referenceTo>Setup__c</referenceTo>
        <relationshipLabel>Students</relationshipLabel>
        <relationshipName>Students</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Student__c</fullName>
        <inlineHelpText>Displays the student&apos;s middle name.</inlineHelpText>
        <label>Student Middle Name</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <label>Student</label>
    <nameField>
        <label>Student Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Students</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Term__c.object
<CustomObject>
    <description>Junction object  between Time and Setup.</description>
    <fields>
        <fullName>Setup__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Setup</label>
        <referenceTo>Setup__c</referenceTo>
        <relationshipLabel>Terms</relationshipLabel>
        <relationshipName>Terms</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Time_Element__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Time Element</label>
        <referenceTo>Time_Element__c</referenceTo>
        <relationshipLabel>Terms</relationshipLabel>
        <relationshipName>Terms</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Term</label>
    <nameField>
        <displayFormat>Term-{000000}</displayFormat>
        <label>Term Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Terms</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Time_Element__c.object
<CustomObject>
    <fields>
        <fullName>End_Date__c</fullName>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Reporting_Period__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Reporting Period?</label>
        <type>Checkbox</type>
    </fields>
    <label>Time</label>
    <nameField>
        <displayFormat>T-{000000}</displayFormat>
        <label>Time Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Time</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/Student_StandardGrades.cls
public class Student_StandardGrades {
 		
	public  ApexPages.StandardController controller {get; set;}
	public  List<subjectWrapper> subjectWrappers {get; set;}
	public  ID studentID {get; set;}
	public  Student__c currentStudent {get; set;}
	public  List<Time_Element__c> orderedReportingPeriods {get; set;}
	
	private  Map<String, List<standardWrapper>> standardSubjectMap = new Map<String, List<standardWrapper>>();
	private  List<Standard_Grade__c> standardGrades = new List<Standard_Grade__c>();
	
	public Student_StandardGrades(ApexPages.StandardController controller){
		
		//initialize
		subjectWrappers = new List<subjectWrapper>();
		orderedReportingPeriods = new List<Time_Element__c>();
		
		if (System.currentPageReference().getParameters().containsKey('id')!=null) {
			studentID = System.currentPageReference().getParameters().get('id');
			currentStudent = core_SoqlUtils.getStudentById(studentID)[0];
			getStandardGrades();			
		}
	}

	private void getStandardGrades() {
		//we only care about getting the standard grades for the student.
		//we need rp order? requires section-reporting-periods, standard/strand grades
		//are not section tied, so cannot really rely on srp.
		//first get all the standard grades.  Figure out what is the latest rp.  Then build off of it
		//reason is because of the possibility that there could be a standard grade on a final rp.
		//Loop through standardGrades to find the F-RP Filters.
		standardGrades = [SELECT ID, Standard_Grade__c, Grade_Overridden__c, Grade_Override__c, Standard__r.Name, 
				Standard__r.Description_Spanish__c, 
				Standard__r.Subject__c, Standard__r.Strand__r.Subject__c, 
				Standard__r.Strand__r.Name, 
				Standard__r.Long_Text__c,
				Reporting_Period__c, Standard__c,
				Reporting_Period__r.Reporting_Period__c
				FROM Standard_Grade__c 
				WHERE student__c = :studentId 
				AND (Grade_Overridden__c = FALSE OR (Grade_Overridden__c=TRUE AND Grade_Override__c != NULL))
				AND Standard__c != null
				AND Standard__r.Strand__c != null
				AND Reporting_Period__c != null
				ORDER BY Standard__r.Name, Reporting_Period__r.End_Date__c, Reporting_Period__r.Reporting_Period__c DESC];
		Set<ID> includeRP = new Set<ID>();
		for(Standard_Grade__c sg : standardGrades) {
			if(!sg.Reporting_Period__r.Reporting_Period__c) {
				includeRP.add(sg.Reporting_Period__c);
			}
		}

		orderedReportingPeriods = Gradebook_ReportCard_Utils.getReportingPeriods(currentStudent.Setup__r.Term__c);
		
		for(Integer i = 0; i < orderedReportingPeriods.size(); i++) {
			if(!(orderedReportingPeriods[i].Reporting_Period__c || includeRP.contains(orderedReportingPeriods[i].ID))) {
				orderedReportingPeriods.remove(i);
				i--;
			}
		}

		for(Integer i=0; i < standardGrades.size(); i++){
					
			String standard = standardGrades[i].Standard__c;
			standardWrapper sw = new standardWrapper();
			sw.subject = (standardGrades[i].Standard__r.Strand__r.Subject__c != null) ? standardGrades[i].Standard__r.Strand__r.Subject__c : (standardGrades[i].Standard__r.Subject__c != null) ? standardGrades[i].Standard__r.Subject__c : '';			
			
			sw.Name = standardGrades[i].Standard__r.Name;
			sw.strandName = standardGrades[i].Standard__r.Strand__r.Name;
			sw.Description = standardGrades[i].Standard__r.long_text__c;
			
			for(Time_Element__c rp : orderedReportingPeriods){
				if(i < standardGrades.size()){
					Standard_Grade__c sg = standardGrades[i];
					String sgSubject = (standardGrades[i].Standard__r.Strand__r.Subject__c != null) ? standardGrades[i].Standard__r.Strand__r.Subject__c : (standardGrades[i].Standard__r.Subject__c != null) ? standardGrades[i].Standard__r.Subject__c : '';
					if(sgSubject == sw.subject && sg.Standard__c == standard && sg.Reporting_Period__c == rp.id) {
						if(i > 0){
							Standard_Grade__c lastProcessed = standardGrades[i-1];
							String lpSubject = (standardGrades[i-1].Standard__r.Strand__r.Subject__c != null) ? standardGrades[i-1].Standard__r.Strand__r.Subject__c : (standardGrades[i-1].Standard__r.Subject__c != null) ? standardGrades[i-1].Standard__r.Subject__c : '';
							if(sg.Reporting_Period__c == lastProcessed.Reporting_Period__c && sgSubject == lpSubject && sg.Standard__c == lastProcessed.Standard__c && (sgSubject != null)){
								throw new Gradebook_ReportCard_Utils.DocumentRuntimeException('FATAL:Duplicate standard grades where detected (IDs'+lastProcessed.id+' and '+sg.id+'). Please delete the duplicate.');
							}
						}
						if(sg.Standard_Grade__c == null || (sg.Grade_Overridden__c && sg.Grade_Override__c == null)){
							sw.Grade.add('');
						} else {
							sw.Grade.add(String.valueOf(((sg.Grade_Overridden__c) ? sg.Grade_Override__c : sg.Standard_Grade__c).divide(1,1)));
						}
						i++;
					}
					else{
						sw.Grade.add('');
					}
				} 
				else {
					sw.Grade.add('');
				}
			}
			i--;
			//sorting standards due to conditional subject?
			if(standardSubjectMap.containsKey(sw.subject)){
				standardSubjectMap.get(sw.subject).add(sw);
			}
			else{
				standardSubjectMap.put(sw.subject, new List<StandardWrapper>{sw});
			}
		}	
	
		List<String> subjects = new List<String>(standardSubjectMap.keySet());
		subjects.sort();
		for(String subject:subjects){
			subjectWrappers.add(new subjectWrapper(standardSubjectMap.get(subject)));   
		}

	}
	
	public class subjectWrapper{
		public  List<standardWrapper> standards	{get;set;} //can be strands too
		public  String subject					{get;set;}
		
		public subjectWrapper(List<standardWrapper> standards){
			this.standards = standards;
			this.subject = this.standards[0].subject;
		}
	}
	
	public class standardWrapper{
		public  List<String> grade	{get; set;}
		public  String description	{get; set;}
		public  String strandName	{get; set;}
		public  String Name			{get; set;}
		public  String cssClass		{get; set;}		
		public  String subject 		{get; set;}
		
		public standardWrapper(){
			grade = new List<String>();
		}
	}
}