objects/Setup__c.object
<CustomObject>
    <description>This object is used to setup Schoolforce and is referenced in multiple pieces of code.  There should be one setup object per school.</description>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Is this school setup active for this school year?</inlineHelpText>
        <label>Active?</label>
        <type>Checkbox</type>
    </fields>
    <label>Setup</label>
    <nameField>
        <displayFormat>S-{0}</displayFormat>
        <label>Setup ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Setup</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/Student__c.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>true</defaultValue>
        <inlineHelpText>Indicates whether or not this Student record is active. If checked, then this is the current Student record. If unchecked, this is an old Student record.</inlineHelpText>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Setup__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Displays the Setup record associated to this Student record. The Setup record defines the settings for the school in a specific school year.</inlineHelpText>
        <label>Setup</label>
        <referenceTo>Setup__c</referenceTo>
        <relationshipLabel>Students</relationshipLabel>
        <relationshipName>Students</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Student__c</fullName>
        <inlineHelpText>Displays the student&apos;s middle name.</inlineHelpText>
        <label>Student Middle Name</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <label>Student</label>
    <nameField>
        <label>Student Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Students</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/CT_Batch_ProcessEOYDataTest.cls
/**
 * Created by YuriyRudenko on 10/7/2020.
 */
@IsTest
public with sharing class CT_Batch_ProcessEOYDataTest{
    private static final Integer COUNT = 5;
    private static final Integer AMOUNT = 30;
    private static Setup__c setup;

    private static void setupData(){
        testDataSetupUtil_v2.setUPCoreData(COUNT);
        testDataSetupUtil_v2.setUPStaffData(COUNT);
        testDataSetupUtil_v2.setUPStudentData(COUNT);
        testDataSetupUtil_v2.setUPProgramData(testDataSetupUtil_v2.sectionsList, testDataSetupUtil_v2.school);
        testDataSetupUtil_v2.setUPExistingSessionResults(AMOUNT);

        setup = [SELECT id, Active__c
        FROM Setup__c
        LIMIT 1];

    }

    static testMethod void testBatch() {
        setupData();
        
        Test.startTest();
        Database.executeBatch(new CT_Batch_ProcessEOYData('Student__c', setup.Id));
        Test.stopTest();
    }
}