objects/Standard__c.object
<CustomObject>
    <fields>
        <fullName>Identifier__c</fullName>
        <inlineHelpText>Specific standard or strand Identifier; for example 1.ELA.L.1a.  This is displayed when searching for Standards when creating an Assignment</inlineHelpText>
        <label>Identifier</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Long_Text__c</fullName>
        <inlineHelpText>Long text description of the standard that displays in the hover over in the Gradebook and on Portal/PGV. Max of 32,000 characters to describe the Standard.</inlineHelpText>
        <label>Long Text</label>
        <length>32000</length>
        <type>LongTextArea</type>
    </fields>
    <label>Standard</label>
    <nameField>
        <label>Standard Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Standards</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Standard_Grade__c.object
<CustomObject>
    <fields>
        <fullName>Standard_Grade__c</fullName>
        <formula>IF(NOT(ISNULL(Grade_Override__c)), Grade_Override__c,

IF(AND(ISPICKVAL(Student__r.Setup__r.Calculation_Type__c,  &quot;Mean&quot;), Student__r.Setup__r.Rolling_Standard_Grade__c == FALSE), Mean_Grade__c, 

IF(AND(ISPICKVAL(Student__r.Setup__r.Calculation_Type__c, &quot;Highest&quot;), Student__r.Setup__r.Rolling_Standard_Grade__c == FALSE), Highest_Grade__c, 

IF(AND(ISPICKVAL(Student__r.Setup__r.Calculation_Type__c, &quot;Most Recent&quot;), Student__r.Setup__r.Rolling_Standard_Grade__c == FALSE), Most_Recent_Grade__c, 
 
IF(AND(ISPICKVAL(Student__r.Setup__r.Calculation_Type__c, &quot;Power Law&quot;), Student__r.Setup__r.Rolling_Standard_Grade__c == FALSE), Power_Law_Grade__c, 

IF(AND(ISPICKVAL(Student__r.Setup__r.Calculation_Type__c, &quot;Law of Decaying Average&quot;), Student__r.Setup__r.Rolling_Standard_Grade__c == FALSE), Law_of_Decaying_Average_Grade__c, 

IF(AND(ISPICKVAL(Student__r.Setup__r.Calculation_Type__c,  &quot;Mean&quot;), Student__r.Setup__r.Rolling_Standard_Grade__c == TRUE), Rolling_Mean_Grade__c, 

IF(AND(ISPICKVAL(Student__r.Setup__r.Calculation_Type__c, &quot;Highest&quot;), Student__r.Setup__r.Rolling_Standard_Grade__c == TRUE), Rolling_Highest_Grade__c, 

IF(AND(ISPICKVAL(Student__r.Setup__r.Calculation_Type__c, &quot;Most Recent&quot;), Student__r.Setup__r.Rolling_Standard_Grade__c == TRUE), Rolling_Most_Recent_Grade__c, 
 
IF(AND(ISPICKVAL(Student__r.Setup__r.Calculation_Type__c, &quot;Power Law&quot;), Student__r.Setup__r.Rolling_Standard_Grade__c == TRUE), Rolling_Power_Law_Grade__c, 

IF(AND(ISPICKVAL(Student__r.Setup__r.Calculation_Type__c, &quot;Law of Decaying Average&quot;), Student__r.Setup__r.Rolling_Standard_Grade__c == TRUE), Rolling_Law_of_Decaying_Average_Grade__c, 

Weighted_Average_Grade__c

)))))))))))</formula>
        <inlineHelpText>What is the formal standard grade based on the school&apos;s selected standard calculation type? This is a year to date calculation; it is not based on reporting periods.</inlineHelpText>
        <label>Grade</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Standard__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Standard</label>
        <referenceTo>Standard__c</referenceTo>
        <relationshipLabel>Standard Grades</relationshipLabel>
        <relationshipName>Standard_Grades</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Student__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Student</label>
        <referenceTo>Student__c</referenceTo>
        <relationshipLabel>Standard Grades</relationshipLabel>
        <relationshipName>Standard_Grades</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Standard Grade</label>
    <nameField>
        <displayFormat>STDG-{000}</displayFormat>
        <label>Standard Grade Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Standard Grades</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Student__c.object
<CustomObject>
    <fields>
        <fullName>ELL__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Indicates whether or not the student is an English language learner (ELL).</inlineHelpText>
        <label>ELL</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Ethnicity__c</fullName>
        <inlineHelpText>Displays the student&apos;s ethnic background. You can use this field for reporting purposes.</inlineHelpText>
        <label>Ethnicity</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Hispanic / Latino</fullName>
                </value>
                <value>
                    <fullName>Non-Hispanic / Latino</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>IEP__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Indicates whether or not a student has an Individualized Education Program (IEP).</inlineHelpText>
        <label>IEP</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Race__c</fullName>
        <inlineHelpText>Do not use this field; it is no longer used by SchoolForce.</inlineHelpText>
        <label>Race*Retired*</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>American Indian or Alaskan Native</fullName>
                </value>
                <value>
                    <fullName>African American</fullName>
                </value>
                <value>
                    <fullName>Asian</fullName>
                </value>
                <value>
                    <fullName>Hispanic or Latino</fullName>
                </value>
                <value>
                    <fullName>White</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Student__c</fullName>
        <inlineHelpText>Displays the student&apos;s middle name.</inlineHelpText>
        <label>Student Middle Name</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Title_1_Status__c</fullName>
        <inlineHelpText>This field is not used by SchoolForce, but you can use it for reporting purposes.</inlineHelpText>
        <label>Title 1 Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Free</fullName>
                </value>
                <value>
                    <fullName>Reduced</fullName>
                </value>
                <value>
                    <fullName>Paid</fullName>
                </value>
                <value>
                    <fullName>None</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Student</label>
    <nameField>
        <label>Student Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Students</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/Charts_Test.cls
@isTest
private class Charts_Test {

	static testMethod void testIt() {
		testDataSetupUtil_v2.isGradebook=true;
		testDataSetupUtil_v2.setUPCoreData(2);//Increased the count to 2 to fix the "List out of bounds" Exception in TestDataSetupUtil_V2 line no. 939
		testDataSetupUtil_v2.setUPStaffData(4);
		testDataSetupUtil_v2.setUPStudentData(4);
		Standard__c s = new Standard__c();
		 s.Identifier__c='ABC';
		 s.Name = 'ABC';
		 Insert(s);
		 Standard__c s2 = new Standard__c();
		 s.Identifier__c='ABCD';
		 s.Name = 'ABCD';
		 Insert(s2);
		 Test.startTest();
		 Charts c = new Charts();
		 c.loadFilters();   //cover non-staff specific filter loads
		system.runAs(testDataSetupUtil_v2.staffUsersList[1]){
			 c.loadFilters();
			 c.selectedTeacherIDs = new List<String>();
			 c.selectedSchool = new List<Id>();
			 c.selectedStudents = new List<Charts.StudentWrapper>();
			 
			 c.dummyStandard.Identifier__c = 'ABC*';
			 c.standardCourseSearch = 'ABC*';
			 c.standardStrandSearch = 'ABC*';
			 c.standardSubjectSearch = 'ABC*';
			 c.standardParentStandardSearch = 'ABC*';
			 c.searchStandards();
			 
			 c.dummyStandard.Identifier__c = 'ABC';
			 c.standardCourseSearch = 'ABC';
			 c.standardStrandSearch = 'ABC';
			 c.standardSubjectSearch = 'ABC';
			 c.standardParentStandardSearch = 'ABC';
			 c.searchStandards();
			 
			c.SelectStudents();
			 c.selectedSchool.addAll(c.schoolToSectionOptionsMap.keyset());
			 c.reRenderSections();
			 c.selectedTeacherIDs.addAll(c.teacherToSectionOptionsMap.keyset());
			 c.reRenderSections();
			 c.selectedTeacherIDs.clear();
			 c.reRenderSections();
			 c.dummyStudent.Ethnicity__c = 'White';
			 c.dummyStudent.Race__c = 'Generic';
			 c.dummyStudent.ELL__c = true;
			 c.dummyStudent.IEP__c = true;
			 c.dummyStudent.Title_1_Status__c = 'Title 1';
			 
			 c.getStudents();
		 }
		 Test.stopTest();
	}
	
	static testMethod void testIt2(){
		testDataSetupUtil_v2.isGradebook=true;
		testDataSetupUtil_v2.setUPCoreData(2);//Increased the count to 2 to fix the "List out of bounds" Exception in TestDataSetupUtil_V2 line no. 939
		testDataSetupUtil_v2.setUPStaffData(4);
		testDataSetupUtil_v2.setUPStudentData(4);
		Standard__c s = new Standard__c();
		 s.Identifier__c='ABC';
		 s.Name = 'ABC';
		insert s;
		Standard__c s2 = new Standard__c();
		 s.Identifier__c='ABCD';
		 s.Name = 'ABCD';
		insert s2;
		Test.startTest();
		Charts c = new Charts();
		c.loadFilters();   //cover non-staff specific filter loads
		system.runAs(testDataSetupUtil_v2.staffUsersList[1]){
			 c.dummyStandard.Identifier__c = null;
			 c.standardCourseSearch  = null;
			 c.standardStrandSearch  = null;
			 c.standardSubjectSearch  = null;
			 c.standardParentStandardSearch  = null;
			 c.searchStandards();
			for(Charts.standardWrapper st : c.WrappedStandardS){
				st.selected = true;
			 }
			 c.selectStandards();
			c.dummyStudent = new Student__c();
			 c.getStudents();
			 list<Standard_Grade__c> sgToInsert = new List<Standard_Grade__c>();
			 string tempstudid = '';
			 for(charts.studentWrapper stud : c.wrappedStudents){
				for(charts.standardWrapper sw : c.selectedStandards){
					Standard_Grade__c sg = new Standard_Grade__c();
					sg.Student__c = stud.student.id;
					sg.Standard__c = sw.standard.id;
					sgToInsert.add(sg);
				}
				stud.selected = true;
				tempstudid = stud.student.id;
			 }
			 insert sgToinsert;
			 standard__c tempstd;
			 c.infomap = new map<id, standard__c>();
			 for(charts.standardWrapper sw : c.selectedStandards){
				tempstd = sw.standard;
				tempstd.long_text__c = 'test';
				c.infomap.put(tempstd.id, tempstd);  
			 }
			 ApexPages.currentpage().getparameters().put('removedStandards', tempstd.id);
			 ApexPages.currentpage().getparameters().put('removedStudents', tempstudid);
			 c.SelectStudents();
			 c.generateReports2();
			 c.removeSelectedStandards();
			 c.removeSelectedStudents();
		}
		Test.stopTest();
	}

}