objects/Student__c.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>true</defaultValue>
        <inlineHelpText>Indicates whether or not this Student record is active. If checked, then this is the current Student record. If unchecked, this is an old Student record.</inlineHelpText>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Additional_Information__c</fullName>
        <label>Additional Information</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Archived__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Displays whether or not this Student record is archived. SchoolForce archives Student records in the Process Data Step of the EOY Wizard. You should never manually update this field.</inlineHelpText>
        <label>Archived</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Hobbies__c</fullName>
        <label>Hobbies</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Individual__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Displays the name for the Contact record associated to this Student record. You can click the link to view the student&apos;s Contact record.</inlineHelpText>
        <label>Individual Record</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Student Records</relationshipLabel>
        <relationshipName>Students</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Strengths__c</fullName>
        <label>Strengths</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Student_First_Name__c</fullName>
        <inlineHelpText>Displays the student&apos;s first name.</inlineHelpText>
        <label>Student First Name</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Student_Id__c</fullName>
        <inlineHelpText>Displays the student&apos;s ID. This field displays on report cards, progress reports, and transcripts. It must be unique; SchoolForce uses this ID to link the Student record with the correct Contact record.</inlineHelpText>
        <label>Student Id</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Student_Last_Name__c</fullName>
        <inlineHelpText>Displays the student&apos;s last name.</inlineHelpText>
        <label>Student Last Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Student__c</fullName>
        <inlineHelpText>Displays the student&apos;s middle name.</inlineHelpText>
        <label>Student Middle Name</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <label>Student</label>
    <nameField>
        <label>Student Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Students</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/newStudentController.cls
public with sharing class newStudentController {
	public Student__c stu {get;set;}
	private ApexPages.StandardController con;
	public newStudentController(ApexPages.StandardController controller) {
		con = controller;
   		stu = new Student__c();
    }
    public List<String> addInfo {
		get {
			if(addInfo == null) {
				addInfo = new List<String>();
				addInfo.add('Strengths__c');
				addInfo.add('Hobbies__c');
				addInfo.add('Additional_Information__c');
			}
			return addInfo;
		}
		private set;
	}
	public List<String> sysInfo {
		get {
			if(sysInfo == null) {
				sysInfo = new List<String>();
				sysInfo.add('Individual__c');
				sysInfo.add('Active__c');
				sysInfo.add('Student_Id__c');
				sysInfo.add('Archived__c');
			}
			return sysInfo;
		}
		private set;
	}
	
	public Pagereference saveStudent() {
		stu.Name = stu.Student_First_Name__c +' '+stu.Student_Last_Name__c;
		
		try {
			DMLManager.insertAsUser(new List<Student__c>{stu});
			return new Pagereference('/'+stu.Id);
		} catch(DMLManager.CRUDException e){
			CyUtil.errorMessage('User lacks permissions to create student records.');
		} catch(DMLManager.FLSException e){
			CyUtil.errorMessage('User lacks permissions to key fields on the student record.');
		} catch(System.DMLException e){
			CyUtil.errorMessage(e.getMessage());
		}
		return null;
	}
	
	public Pagereference saveAndNewStudent() {
		saveStudent();

		if(!ApexPages.hasMessages()){
			Schema.DescribeSObjectResult describeResult = con.getRecord().getSObjectType().getDescribe();
            Pagereference pr = new PageReference('/' + describeResult.getKeyPrefix() + '/e');
            pr.setRedirect(true);
            return pr;
        } else {
        	return null;
        }
	}
}