objects/Student__c.object
<CustomObject>
    <fields>
        <fullName>External_Evaluation_ID__c</fullName>
        <label>External Evaluation ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Student__c</fullName>
        <inlineHelpText>Displays the student&apos;s middle name.</inlineHelpText>
        <label>Student Middle Name</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <label>Student</label>
    <nameField>
        <label>Student Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Students</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/StudentUpdateBatch.cls
public class StudentUpdateBatch implements Database.Batchable<sObject>{
    public final String Query;

    public StudentUpdateBatch(){
        Query = 'SELECT Id FROM Student__c WHERE External_Evaluation_ID__c = \'\'';
    }

    public Database.QueryLocator start(Database.BatchableContext BC){
        return Database.getQueryLocator(query);
    }

    public void execute(Database.BatchableContext BC, List<sObject> scope){
        update scope;
    }

    public void finish(Database.BatchableContext BC){

    }

}