objects/Student__c.object
<CustomObject>
    <fields>
        <fullName>Student__c</fullName>
        <inlineHelpText>Displays the student&apos;s middle name.</inlineHelpText>
        <label>Student Middle Name</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <label>Student</label>
    <nameField>
        <label>Student Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Students</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Student_Program__c.object
<CustomObject>
    <description>This is an object is students/program roll up</description>
    <fields>
        <fullName>Amount_of_Time__c</fullName>
        <label>Total Time for Program</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Student__c</fullName>
        <description>Student/Program</description>
        <label>Student</label>
        <referenceTo>Student__c</referenceTo>
        <relationshipLabel>Student/Programs</relationshipLabel>
        <relationshipName>Student_Programs</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Student/Program</label>
    <nameField>
        <displayFormat>SP-{0000}</displayFormat>
        <label>Student/Program Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Student/Programs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/Test_BatchProcessStudentSections.cls
@isTest
private class Test_BatchProcessStudentSections {
	private static final Integer COUNT = 3;	
	private static final Integer AMOUNT = 30;

	static testMethod void test_BatchProcessStudentSections() {
		testDataSetupUtil_v2.setUPCoreData(COUNT);
		testDataSetupUtil_v2.setUPStaffData(COUNT);
		testDataSetupUtil_v2.setUPStudentData(COUNT);
		testDataSetupUtil_v2.setUPProgramData(testDataSetupUtil_v2.sectionsList, testDataSetupUtil_v2.school);
		testDataSetupUtil_v2.setUPExistingSessionResults(AMOUNT);
     	BatchProcessStudentSections bpsc = new BatchProcessStudentSections ();

     	Test.startTest(); 
        	Database.executeBatch(bpsc, 50) ;
     	Test.stopTest();		

    	List<Student_Program__c> studentPrograms = new List<Student_Program__c>([SELECT Id, Student__c, Amount_of_Time__c FROM Student_Program__c]);
    	System.assertEquals(COUNT + 1, studentPrograms.size());     	
	}
}