objects/Student__c.object
<CustomObject>
    <fields>
        <fullName>Student_First_Name__c</fullName>
        <inlineHelpText>Displays the student&apos;s first name.</inlineHelpText>
        <label>Student First Name</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Student_Last_Name__c</fullName>
        <inlineHelpText>Displays the student&apos;s last name.</inlineHelpText>
        <label>Student Last Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Student__c</fullName>
        <inlineHelpText>Displays the student&apos;s middle name.</inlineHelpText>
        <label>Student Middle Name</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <label>Student</label>
    <nameField>
        <label>Student Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Students</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/TestNewStudentController.cls
@isTest
private class TestNewStudentController {

	static testMethod void myUnitTest() {
		Test.startTest();
			ApexPages.StandardController sc = new ApexPages.StandardController(new Student__c());
			NewStudentController controller = new NewStudentController(sc);
			List<String> testList = controller.addInfo;
			system.assertEquals(3,testList.size());
			testList = controller.sysInfo;
			system.assertEquals(4,testList.size());
			controller.stu.Student_First_Name__c = 'Test';
			controller.stu.Student_Last_Name__c = 'LastTest';
			controller.saveStudent();
			controller.saveAndNewStudent();
		Test.stopTest();
	}
}